
#define UART_FIFO_REG( i ) (REG_UART_BASE( i ) + 0x0)
#define UART_RXFIFO_RD_BYTE 0x000000FF
#define UART_RXFIFO_RD_BYTE_S 0

#define UART_INT_RAW_REG( i ) (REG_UART_BASE( i ) + 0x4)
#define UART_WAKEUP_INT_RAW (BIT(19))
#define UART_WAKEUP_INT_RAW_S 19
#define UART_AT_CMD_CHAR_DET_INT_RAW (BIT(18))
#define UART_AT_CMD_CHAR_DET_INT_RAW_S 18
#define UART_RS485_CLASH_INT_RAW (BIT(17))
#define UART_RS485_CLASH_INT_RAW_S 17
#define UART_RS485_FRM_ERR_INT_RAW (BIT(16))
#define UART_RS485_FRM_ERR_INT_RAW_S 16
#define UART_RS485_PARITY_ERR_INT_RAW (BIT(15))
#define UART_RS485_PARITY_ERR_INT_RAW_S 15
#define UART_TX_DONE_INT_RAW (BIT(14))
#define UART_TX_DONE_INT_RAW_S 14
#define UART_TX_BRK_IDLE_DONE_INT_RAW (BIT(13))
#define UART_TX_BRK_IDLE_DONE_INT_RAW_S 13
#define UART_TX_BRK_DONE_INT_RAW (BIT(12))
#define UART_TX_BRK_DONE_INT_RAW_S 12
#define UART_GLITCH_DET_INT_RAW (BIT(11))
#define UART_GLITCH_DET_INT_RAW_S 11
#define UART_SW_XOFF_INT_RAW (BIT(10))
#define UART_SW_XOFF_INT_RAW_S 10
#define UART_SW_XON_INT_RAW (BIT(9))
#define UART_SW_XON_INT_RAW_S 9
#define UART_RXFIFO_TOUT_INT_RAW (BIT(8))
#define UART_RXFIFO_TOUT_INT_RAW_S 8
#define UART_BRK_DET_INT_RAW (BIT(7))
#define UART_BRK_DET_INT_RAW_S 7
#define UART_CTS_CHG_INT_RAW (BIT(6))
#define UART_CTS_CHG_INT_RAW_S 6
#define UART_DSR_CHG_INT_RAW (BIT(5))
#define UART_DSR_CHG_INT_RAW_S 5
#define UART_RXFIFO_OVF_INT_RAW (BIT(4))
#define UART_RXFIFO_OVF_INT_RAW_S 4
#define UART_FRM_ERR_INT_RAW (BIT(3))
#define UART_FRM_ERR_INT_RAW_S 3
#define UART_PARITY_ERR_INT_RAW (BIT(2))
#define UART_PARITY_ERR_INT_RAW_S 2
#define UART_TXFIFO_EMPTY_INT_RAW (BIT(1))
#define UART_TXFIFO_EMPTY_INT_RAW_S 1
#define UART_RXFIFO_FULL_INT_RAW (BIT(0))
#define UART_RXFIFO_FULL_INT_RAW_S 0

#define UART_INT_ST_REG( i ) (REG_UART_BASE( i ) + 0x8)
#define UART_WAKEUP_INT_ST (BIT(19))
#define UART_WAKEUP_INT_ST_S 19
#define UART_AT_CMD_CHAR_DET_INT_ST (BIT(18))
#define UART_AT_CMD_CHAR_DET_INT_ST_S 18
#define UART_RS485_CLASH_INT_ST (BIT(17))
#define UART_RS485_CLASH_INT_ST_S 17
#define UART_RS485_FRM_ERR_INT_ST (BIT(16))
#define UART_RS485_FRM_ERR_INT_ST_S 16
#define UART_RS485_PARITY_ERR_INT_ST (BIT(15))
#define UART_RS485_PARITY_ERR_INT_ST_S 15
#define UART_TX_DONE_INT_ST (BIT(14))
#define UART_TX_DONE_INT_ST_S 14
#define UART_TX_BRK_IDLE_DONE_INT_ST (BIT(13))
#define UART_TX_BRK_IDLE_DONE_INT_ST_S 13
#define UART_TX_BRK_DONE_INT_ST (BIT(12))
#define UART_TX_BRK_DONE_INT_ST_S 12
#define UART_GLITCH_DET_INT_ST (BIT(11))
#define UART_GLITCH_DET_INT_ST_S 11
#define UART_SW_XOFF_INT_ST (BIT(10))
#define UART_SW_XOFF_INT_ST_S 10
#define UART_SW_XON_INT_ST (BIT(9))
#define UART_SW_XON_INT_ST_S 9
#define UART_RXFIFO_TOUT_INT_ST (BIT(8))
#define UART_RXFIFO_TOUT_INT_ST_S 8
#define UART_BRK_DET_INT_ST (BIT(7))
#define UART_BRK_DET_INT_ST_S 7
#define UART_CTS_CHG_INT_ST (BIT(6))
#define UART_CTS_CHG_INT_ST_S 6
#define UART_DSR_CHG_INT_ST (BIT(5))
#define UART_DSR_CHG_INT_ST_S 5
#define UART_RXFIFO_OVF_INT_ST (BIT(4))
#define UART_RXFIFO_OVF_INT_ST_S 4
#define UART_FRM_ERR_INT_ST (BIT(3))
#define UART_FRM_ERR_INT_ST_S 3
#define UART_PARITY_ERR_INT_ST (BIT(2))
#define UART_PARITY_ERR_INT_ST_S 2
#define UART_TXFIFO_EMPTY_INT_ST (BIT(1))
#define UART_TXFIFO_EMPTY_INT_ST_S 1
#define UART_RXFIFO_FULL_INT_ST (BIT(0))
#define UART_RXFIFO_FULL_INT_ST_S 0

#define UART_INT_ENA_REG( i ) (REG_UART_BASE( i ) + 0xC)
#define UART_WAKEUP_INT_ENA (BIT(19))
#define UART_WAKEUP_INT_ENA_S 19
#define UART_AT_CMD_CHAR_DET_INT_ENA (BIT(18))
#define UART_AT_CMD_CHAR_DET_INT_ENA_S 18
#define UART_RS485_CLASH_INT_ENA (BIT(17))
#define UART_RS485_CLASH_INT_ENA_S 17
#define UART_RS485_FRM_ERR_INT_ENA (BIT(16))
#define UART_RS485_FRM_ERR_INT_ENA_S 16
#define UART_RS485_PARITY_ERR_INT_ENA (BIT(15))
#define UART_RS485_PARITY_ERR_INT_ENA_S 15
#define UART_TX_DONE_INT_ENA (BIT(14))
#define UART_TX_DONE_INT_ENA_S 14
#define UART_TX_BRK_IDLE_DONE_INT_ENA (BIT(13))
#define UART_TX_BRK_IDLE_DONE_INT_ENA_S 13
#define UART_TX_BRK_DONE_INT_ENA (BIT(12))
#define UART_TX_BRK_DONE_INT_ENA_S 12
#define UART_GLITCH_DET_INT_ENA (BIT(11))
#define UART_GLITCH_DET_INT_ENA_S 11
#define UART_SW_XOFF_INT_ENA (BIT(10))
#define UART_SW_XOFF_INT_ENA_S 10
#define UART_SW_XON_INT_ENA (BIT(9))
#define UART_SW_XON_INT_ENA_S 9
#define UART_RXFIFO_TOUT_INT_ENA (BIT(8))
#define UART_RXFIFO_TOUT_INT_ENA_S 8
#define UART_BRK_DET_INT_ENA (BIT(7))
#define UART_BRK_DET_INT_ENA_S 7
#define UART_CTS_CHG_INT_ENA (BIT(6))
#define UART_CTS_CHG_INT_ENA_S 6
#define UART_DSR_CHG_INT_ENA (BIT(5))
#define UART_DSR_CHG_INT_ENA_S 5
#define UART_RXFIFO_OVF_INT_ENA (BIT(4))
#define UART_RXFIFO_OVF_INT_ENA_S 4
#define UART_FRM_ERR_INT_ENA (BIT(3))
#define UART_FRM_ERR_INT_ENA_S 3
#define UART_PARITY_ERR_INT_ENA (BIT(2))
#define UART_PARITY_ERR_INT_ENA_S 2
#define UART_TXFIFO_EMPTY_INT_ENA (BIT(1))
#define UART_TXFIFO_EMPTY_INT_ENA_S 1
#define UART_RXFIFO_FULL_INT_ENA (BIT(0))
#define UART_RXFIFO_FULL_INT_ENA_S 0

#define UART_INT_CLR_REG( i ) (REG_UART_BASE( i ) + 0x10)
#define UART_WAKEUP_INT_CLR (BIT(19))
#define UART_WAKEUP_INT_CLR_S 19
#define UART_AT_CMD_CHAR_DET_INT_CLR (BIT(18))
#define UART_AT_CMD_CHAR_DET_INT_CLR_S 18
#define UART_RS485_CLASH_INT_CLR (BIT(17))
#define UART_RS485_CLASH_INT_CLR_S 17
#define UART_RS485_FRM_ERR_INT_CLR (BIT(16))
#define UART_RS485_FRM_ERR_INT_CLR_S 16
#define UART_RS485_PARITY_ERR_INT_CLR (BIT(15))
#define UART_RS485_PARITY_ERR_INT_CLR_S 15
#define UART_TX_DONE_INT_CLR (BIT(14))
#define UART_TX_DONE_INT_CLR_S 14
#define UART_TX_BRK_IDLE_DONE_INT_CLR (BIT(13))
#define UART_TX_BRK_IDLE_DONE_INT_CLR_S 13
#define UART_TX_BRK_DONE_INT_CLR (BIT(12))
#define UART_TX_BRK_DONE_INT_CLR_S 12
#define UART_GLITCH_DET_INT_CLR (BIT(11))
#define UART_GLITCH_DET_INT_CLR_S 11
#define UART_SW_XOFF_INT_CLR (BIT(10))
#define UART_SW_XOFF_INT_CLR_S 10
#define UART_SW_XON_INT_CLR (BIT(9))
#define UART_SW_XON_INT_CLR_S 9
#define UART_RXFIFO_TOUT_INT_CLR (BIT(8))
#define UART_RXFIFO_TOUT_INT_CLR_S 8
#define UART_BRK_DET_INT_CLR (BIT(7))
#define UART_BRK_DET_INT_CLR_S 7
#define UART_CTS_CHG_INT_CLR (BIT(6))
#define UART_CTS_CHG_INT_CLR_S 6
#define UART_DSR_CHG_INT_CLR (BIT(5))
#define UART_DSR_CHG_INT_CLR_S 5
#define UART_RXFIFO_OVF_INT_CLR (BIT(4))
#define UART_RXFIFO_OVF_INT_CLR_S 4
#define UART_FRM_ERR_INT_CLR (BIT(3))
#define UART_FRM_ERR_INT_CLR_S 3
#define UART_PARITY_ERR_INT_CLR (BIT(2))
#define UART_PARITY_ERR_INT_CLR_S 2
#define UART_TXFIFO_EMPTY_INT_CLR (BIT(1))
#define UART_TXFIFO_EMPTY_INT_CLR_S 1
#define UART_RXFIFO_FULL_INT_CLR (BIT(0))
#define UART_RXFIFO_FULL_INT_CLR_S 0

#define UART_CLKDIV_REG( i ) (REG_UART_BASE( i ) + 0x14)
#define UART_CLKDIV_FRAG 0x0000000F
#define UART_CLKDIV_FRAG_S 20
#define UART_CLKDIV 0x000FFFFF
#define UART_CLKDIV_S 0

#define UART_AUTOBAUD_REG( i ) (REG_UART_BASE( i ) + 0x18)
#define UART_GLITCH_FILT 0x000000FF
#define UART_GLITCH_FILT_S 8
#define UART_AUTOBAUD_EN (BIT(0))
#define UART_AUTOBAUD_EN_S 0

#define UART_STATUS_REG( i ) (REG_UART_BASE( i ) + 0x1C)
#define UART_TXD (BIT(31))
#define UART_TXD_S 31
#define UART_RTSN (BIT(30))
#define UART_RTSN_S 30
#define UART_DTRN (BIT(29))
#define UART_DTRN_S 29
#define UART_TXFIFO_CNT 0x000003FF
#define UART_TXFIFO_CNT_S 16
#define UART_RXD (BIT(15))
#define UART_RXD_S 15
#define UART_CTSN (BIT(14))
#define UART_CTSN_S 14
#define UART_DSRN (BIT(13))
#define UART_DSRN_S 13
#define UART_RXFIFO_CNT 0x000003FF
#define UART_RXFIFO_CNT_S 0

#define UART_CONF0_REG( i ) (REG_UART_BASE( i ) + 0x20)
#define UART_TICK_REF_ALWAYS_ON (BIT(27))
#define UART_TICK_REF_ALWAYS_ON_S 27
#define UART_ERR_WR_MASK (BIT(26))
#define UART_ERR_WR_MASK_S 26
#define UART_CLK_EN (BIT(25))
#define UART_CLK_EN_S 25
#define UART_DTR_INV (BIT(24))
#define UART_DTR_INV_S 24
#define UART_RTS_INV (BIT(23))
#define UART_RTS_INV_S 23
#define UART_TXD_INV (BIT(22))
#define UART_TXD_INV_S 22
#define UART_DSR_INV (BIT(21))
#define UART_DSR_INV_S 21
#define UART_CTS_INV (BIT(20))
#define UART_CTS_INV_S 20
#define UART_RXD_INV (BIT(19))
#define UART_RXD_INV_S 19
#define UART_TXFIFO_RST (BIT(18))
#define UART_TXFIFO_RST_S 18
#define UART_RXFIFO_RST (BIT(17))
#define UART_RXFIFO_RST_S 17
#define UART_IRDA_EN (BIT(16))
#define UART_IRDA_EN_S 16
#define UART_TX_FLOW_EN (BIT(15))
#define UART_TX_FLOW_EN_S 15
#define UART_LOOPBACK (BIT(14))
#define UART_LOOPBACK_S 14
#define UART_IRDA_RX_INV (BIT(13))
#define UART_IRDA_RX_INV_S 13
#define UART_IRDA_TX_INV (BIT(12))
#define UART_IRDA_TX_INV_S 12
#define UART_IRDA_WCTL (BIT(11))
#define UART_IRDA_WCTL_S 11
#define UART_IRDA_TX_EN (BIT(10))
#define UART_IRDA_TX_EN_S 10
#define UART_IRDA_DPLX (BIT(9))
#define UART_IRDA_DPLX_S 9
#define UART_TXD_BRK (BIT(8))
#define UART_TXD_BRK_S 8
#define UART_SW_DTR (BIT(7))
#define UART_SW_DTR_S 7
#define UART_SW_RTS (BIT(6))
#define UART_SW_RTS_S 6
#define UART_STOP_BIT_NUM 0x00000003
#define UART_STOP_BIT_NUM_S 4
#define UART_BIT_NUM 0x00000003
#define UART_BIT_NUM_S 2
#define UART_PARITY_EN (BIT(1))
#define UART_PARITY_EN_S 1
#define UART_PARITY (BIT(0))
#define UART_PARITY_S 0

#define UART_CONF1_REG( i ) (REG_UART_BASE( i ) + 0x24)
#define UART_RX_TOUT_EN (BIT(31))
#define UART_RX_TOUT_EN_S 31
#define UART_RX_FLOW_EN (BIT(30))
#define UART_RX_FLOW_EN_S 30
#define UART_RX_TOUT_FLOW_DIS (BIT(29))
#define UART_RX_TOUT_FLOW_DIS_S 29
#define UART_TXFIFO_EMPTY_THRHD 0x000001FF
#define UART_TXFIFO_EMPTY_THRHD_S 9
#define UART_RXFIFO_FULL_THRHD 0x000001FF
#define UART_RXFIFO_FULL_THRHD_S 0

#define UART_LOWPULSE_REG( i ) (REG_UART_BASE( i ) + 0x28)
#define UART_LOWPULSE_MIN_CNT 0x000FFFFF
#define UART_LOWPULSE_MIN_CNT_S 0

#define UART_HIGHPULSE_REG( i ) (REG_UART_BASE( i ) + 0x2C)
#define UART_HIGHPULSE_MIN_CNT 0x000FFFFF
#define UART_HIGHPULSE_MIN_CNT_S 0

#define UART_RXD_CNT_REG( i ) (REG_UART_BASE( i ) + 0x30)
#define UART_RXD_EDGE_CNT 0x000003FF
#define UART_RXD_EDGE_CNT_S 0

#define UART_FLOW_CONF_REG( i ) (REG_UART_BASE( i ) + 0x34)
#define UART_SEND_XOFF (BIT(5))
#define UART_SEND_XOFF_S 5
#define UART_SEND_XON (BIT(4))
#define UART_SEND_XON_S 4
#define UART_FORCE_XOFF (BIT(3))
#define UART_FORCE_XOFF_S 3
#define UART_FORCE_XON (BIT(2))
#define UART_FORCE_XON_S 2
#define UART_XONOFF_DEL (BIT(1))
#define UART_XONOFF_DEL_S 1
#define UART_SW_FLOW_CON_EN (BIT(0))
#define UART_SW_FLOW_CON_EN_S 0

#define UART_SLEEP_CONF_REG( i ) (REG_UART_BASE( i ) + 0x38)
#define UART_ACTIVE_THRESHOLD 0x000003FF
#define UART_ACTIVE_THRESHOLD_S 0

#define UART_SWFC_CONF0_REG( i ) (REG_UART_BASE( i ) + 0x3C)
#define UART_XOFF_CHAR 0x000000FF
#define UART_XOFF_CHAR_S 9
#define UART_XOFF_THRESHOLD 0x000001FF
#define UART_XOFF_THRESHOLD_S 0

#define UART_SWFC_CONF1_REG( i ) (REG_UART_BASE( i ) + 0x40)
#define UART_XON_CHAR 0x000000FF
#define UART_XON_CHAR_S 9
#define UART_XON_THRESHOLD 0x000001FF
#define UART_XON_THRESHOLD_S 0

#define UART_IDLE_CONF_REG( i ) (REG_UART_BASE( i ) + 0x44)
#define UART_TX_BRK_NUM 0x000000FF
#define UART_TX_BRK_NUM_S 20
#define UART_TX_IDLE_NUM 0x000003FF
#define UART_TX_IDLE_NUM_S 10
#define UART_RX_IDLE_THRHD 0x000003FF
#define UART_RX_IDLE_THRHD_S 0

#define UART_RS485_CONF_REG( i ) (REG_UART_BASE( i ) + 0x48)
#define UART_RS485_TX_DLY_NUM 0x0000000F
#define UART_RS485_TX_DLY_NUM_S 6
#define UART_RS485_RX_DLY_NUM (BIT(5))
#define UART_RS485_RX_DLY_NUM_S 5
#define UART_RS485RXBY_TX_EN (BIT(4))
#define UART_RS485RXBY_TX_EN_S 4
#define UART_RS485TX_RX_EN (BIT(3))
#define UART_RS485TX_RX_EN_S 3
#define UART_DL1_EN (BIT(2))
#define UART_DL1_EN_S 2
#define UART_DL0_EN (BIT(1))
#define UART_DL0_EN_S 1
#define UART_RS485_EN (BIT(0))
#define UART_RS485_EN_S 0

#define UART_AT_CMD_PRECNT_REG( i ) (REG_UART_BASE( i ) + 0x4c)
#define UART_PRE_IDLE_NUM 0x0000FFFF
#define UART_PRE_IDLE_NUM_S 0

#define UART_AT_CMD_POSTCNT_REG( i ) (REG_UART_BASE( i ) + 0x50)
#define UART_POST_IDLE_NUM 0x0000FFFF
#define UART_POST_IDLE_NUM_S 0

#define UART_AT_CMD_GAPTOUT_REG( i ) (REG_UART_BASE( i ) + 0x54)
#define UART_RX_GAP_TOUT 0x0000FFFF
#define UART_RX_GAP_TOUT_S 0

#define UART_AT_CMD_CHAR_REG( i ) (REG_UART_BASE( i ) + 0x58)
#define UART_CHAR_NUM 0x000000FF
#define UART_CHAR_NUM_S 8
#define UART_AT_CMD_CHAR 0x000000FF
#define UART_AT_CMD_CHAR_S 0

#define UART_MEM_CONF_REG( i ) (REG_UART_BASE( i ) + 0x5c)
#define UART_RX_TOUT_THRHD 0x000003FF
#define UART_RX_TOUT_THRHD_S 16
#define UART_RX_FLOW_THRHD 0x000001FF
#define UART_RX_FLOW_THRHD_S 7
#define UART_TX_SIZE 0x00000007
#define UART_TX_SIZE_S 4
#define UART_RX_SIZE 0x00000007
#define UART_RX_SIZE_S 1
#define UART_MEM_PD (BIT(0))
#define UART_MEM_PD_S 0

#define UART_MEM_TX_STATUS_REG( i ) (REG_UART_BASE( i ) + 0x60)
#define UART_TX_RADDR 0x000003FF
#define UART_TX_RADDR_S 11
#define UART_APB_TX_WADDR 0x000003FF
#define UART_APB_TX_WADDR_S 0

#define UART_MEM_RX_STATUS_REG( i ) (REG_UART_BASE( i ) + 0x64)
#define UART_RX_WADDR 0x000003FF
#define UART_RX_WADDR_S 11
#define UART_APB_RX_RADDR 0x000003FF
#define UART_APB_RX_RADDR_S 0

#define UART_FSM_STATUS_REG( i ) (REG_UART_BASE( i ) + 0x68)
#define UART_ST_UTX_OUT 0x0000000F
#define UART_ST_UTX_OUT_S 4
#define UART_ST_URX_OUT 0x0000000F
#define UART_ST_URX_OUT_S 0

#define UART_POSPULSE_REG( i ) (REG_UART_BASE( i ) + 0x6c)
#define UART_POSEDGE_MIN_CNT 0x000FFFFF
#define UART_POSEDGE_MIN_CNT_S 0

#define UART_NEGPULSE_REG( i ) (REG_UART_BASE( i ) + 0x70)
#define UART_NEGEDGE_MIN_CNT 0x000FFFFF
#define UART_NEGEDGE_MIN_CNT_S 0

#define UART_DATE_REG( i ) (REG_UART_BASE( i ) + 0x74)
#define UART_DATE 0xFFFFFFFF
#define UART_DATE_S 0
#define UART_DATE_VERSION 0x18082800

#define UART_ID_REG( i ) (REG_UART_BASE( i ) + 0x78)
#define UART_ID 0xFFFFFFFF
#define UART_ID_S 0
