
#define APB_CTRL_SYSCLK_CONF_REG (REG_APB_CTRL_BASE + 0x000)
#define APB_CTRL_SOC_CLK_SEL 0x00000003
#define APB_CTRL_SOC_CLK_SEL_S 14
#define APB_CTRL_RST_TICK_CNT (BIT(12))
#define APB_CTRL_RST_TICK_CNT_S 12
#define APB_CTRL_CLK_EN (BIT(11))
#define APB_CTRL_CLK_EN_S 11
#define APB_CTRL_CLK_320M_EN (BIT(10))
#define APB_CTRL_CLK_320M_EN_S 10
#define APB_CTRL_PRE_DIV_CNT 0x000003FF
#define APB_CTRL_PRE_DIV_CNT_S 0

#define APB_CTRL_TICK_CONF_REG (REG_APB_CTRL_BASE + 0x004)
#define APB_CTRL_TICK_ENABLE (BIT(16))
#define APB_CTRL_TICK_ENABLE_S 16
#define APB_CTRL_CK8M_TICK_NUM 0x000000FF
#define APB_CTRL_CK8M_TICK_NUM_S 8
#define APB_CTRL_XTAL_TICK_NUM 0x000000FF
#define APB_CTRL_XTAL_TICK_NUM_S 0

#define APB_CTRL_APB_SARADC_CTRL_REG (REG_APB_CTRL_BASE + 0x008)
#define APB_CTRL_SARADC_XPD_SAR_FORCE 0x00000003
#define APB_CTRL_SARADC_XPD_SAR_FORCE_S 27
#define APB_CTRL_SARADC_DATA_TO_I2S (BIT(26))
#define APB_CTRL_SARADC_DATA_TO_I2S_S 26
#define APB_CTRL_SARADC_DATA_SAR_SEL (BIT(25))
#define APB_CTRL_SARADC_DATA_SAR_SEL_S 25
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR (BIT(24))
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR_S 24
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR (BIT(23))
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR_S 23
#define APB_CTRL_SARADC_SAR2_PATT_LEN 0x0000000F
#define APB_CTRL_SARADC_SAR2_PATT_LEN_S 19
#define APB_CTRL_SARADC_SAR1_PATT_LEN 0x0000000F
#define APB_CTRL_SARADC_SAR1_PATT_LEN_S 15
#define APB_CTRL_SARADC_SAR_CLK_DIV 0x000000FF
#define APB_CTRL_SARADC_SAR_CLK_DIV_S 7
#define APB_CTRL_SARADC_SAR_CLK_GATED (BIT(6))
#define APB_CTRL_SARADC_SAR_CLK_GATED_S 6
#define APB_CTRL_SARADC_SAR_SEL (BIT(5))
#define APB_CTRL_SARADC_SAR_SEL_S 5
#define APB_CTRL_SARADC_WORK_MODE 0x00000003
#define APB_CTRL_SARADC_WORK_MODE_S 3
#define APB_CTRL_SARADC_START (BIT(1))
#define APB_CTRL_SARADC_START_S 1
#define APB_CTRL_SARADC_START_FORCE (BIT(0))
#define APB_CTRL_SARADC_START_FORCE_S 0

#define APB_CTRL_APB_SARADC_CTRL2_REG (REG_APB_CTRL_BASE + 0x00C)
#define APB_CTRL_SARADC_TIMER_EN (BIT(20))
#define APB_CTRL_SARADC_TIMER_EN_S 20
#define APB_CTRL_SARADC_TIMER_TARGET 0x000000FF
#define APB_CTRL_SARADC_TIMER_TARGET_S 12
#define APB_CTRL_SARADC_TIMER_SEL (BIT(11))
#define APB_CTRL_SARADC_TIMER_SEL_S 11
#define APB_CTRL_SARADC_SAR2_INV (BIT(10))
#define APB_CTRL_SARADC_SAR2_INV_S 10
#define APB_CTRL_SARADC_SAR1_INV (BIT(9))
#define APB_CTRL_SARADC_SAR1_INV_S 9
#define APB_CTRL_SARADC_MAX_MEAS_NUM 0x000000FF
#define APB_CTRL_SARADC_MAX_MEAS_NUM_S 1
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT (BIT(0))
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT_S 0

#define APB_CTRL_APB_SARADC_FSM_REG (REG_APB_CTRL_BASE + 0x010)
#define APB_CTRL_SARADC_SAMPLE_CYCLE 0x000000FF
#define APB_CTRL_SARADC_SAMPLE_CYCLE_S 24
#define APB_CTRL_SARADC_SAMPLE_NUM 0x000000FF
#define APB_CTRL_SARADC_SAMPLE_NUM_S 16

#define APB_CTRL_APB_SARADC_FSM_WAIT_REG (REG_APB_CTRL_BASE + 0x014)
#define APB_CTRL_SARADC_STANDBY_WAIT 0x000000FF
#define APB_CTRL_SARADC_STANDBY_WAIT_S 16
#define APB_CTRL_SARADC_RSTB_WAIT 0x000000FF
#define APB_CTRL_SARADC_RSTB_WAIT_S 8
#define APB_CTRL_SARADC_XPD_WAIT 0x000000FF
#define APB_CTRL_SARADC_XPD_WAIT_S 0

#define APB_CTRL_APB_SARADC_SAR1_STATUS_REG (REG_APB_CTRL_BASE + 0x018)
#define APB_CTRL_SARADC_SAR1_STATUS 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_STATUS_S 0

#define APB_CTRL_APB_SARADC_SAR2_STATUS_REG (REG_APB_CTRL_BASE + 0x01C)
#define APB_CTRL_SARADC_SAR2_STATUS 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_STATUS_S 0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB1_REG (REG_APB_CTRL_BASE + 0x020)
#define APB_CTRL_SARADC_SAR1_PATT_TAB1 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB1_S 0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB2_REG (REG_APB_CTRL_BASE + 0x024)
#define APB_CTRL_SARADC_SAR1_PATT_TAB2 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB2_S 0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB3_REG (REG_APB_CTRL_BASE + 0x028)
#define APB_CTRL_SARADC_SAR1_PATT_TAB3 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB3_S 0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB4_REG (REG_APB_CTRL_BASE + 0x02C)
#define APB_CTRL_SARADC_SAR1_PATT_TAB4 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB4_S 0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB1_REG (REG_APB_CTRL_BASE + 0x030)
#define APB_CTRL_SARADC_SAR2_PATT_TAB1 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB1_S 0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB2_REG (REG_APB_CTRL_BASE + 0x034)
#define APB_CTRL_SARADC_SAR2_PATT_TAB2 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB2_S 0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB3_REG (REG_APB_CTRL_BASE + 0x038)
#define APB_CTRL_SARADC_SAR2_PATT_TAB3 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB3_S 0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB4_REG (REG_APB_CTRL_BASE + 0x03C)
#define APB_CTRL_SARADC_SAR2_PATT_TAB4 0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB4_S 0

#define APB_CTRL_APB_ADC_ARB_CTRL_REG (REG_APB_CTRL_BASE + 0x040)
#define APB_CTRL_ADC_ARB_FIX_PRIORITY (BIT(12))
#define APB_CTRL_ADC_ARB_FIX_PRIORITY_S 12
#define APB_CTRL_ADC_ARB_WIFI_PRIORITY 0x00000003
#define APB_CTRL_ADC_ARB_WIFI_PRIORITY_S 10
#define APB_CTRL_ADC_ARB_RTC_PRIORITY 0x00000003
#define APB_CTRL_ADC_ARB_RTC_PRIORITY_S 8
#define APB_CTRL_ADC_ARB_APB_PRIORITY 0x00000003
#define APB_CTRL_ADC_ARB_APB_PRIORITY_S 6
#define APB_CTRL_ADC_ARB_GRANT_FORCE (BIT(5))
#define APB_CTRL_ADC_ARB_GRANT_FORCE_S 5
#define APB_CTRL_ADC_ARB_WIFI_FORCE (BIT(4))
#define APB_CTRL_ADC_ARB_WIFI_FORCE_S 4
#define APB_CTRL_ADC_ARB_RTC_FORCE (BIT(3))
#define APB_CTRL_ADC_ARB_RTC_FORCE_S 3
#define APB_CTRL_ADC_ARB_APB_FORCE (BIT(2))
#define APB_CTRL_ADC_ARB_APB_FORCE_S 2

#define APB_CTRL_CLK_OUT_EN_REG (REG_APB_CTRL_BASE + 0x044)
#define APB_CTRL_CLK_XTAL_OEN (BIT(10))
#define APB_CTRL_CLK_XTAL_OEN_S 10
#define APB_CTRL_CLK40X_BB_OEN (BIT(9))
#define APB_CTRL_CLK40X_BB_OEN_S 9
#define APB_CTRL_CLK_DAC_CPU_OEN (BIT(8))
#define APB_CTRL_CLK_DAC_CPU_OEN_S 8
#define APB_CTRL_CLK_ADC_INF_OEN (BIT(7))
#define APB_CTRL_CLK_ADC_INF_OEN_S 7
#define APB_CTRL_CLK_320M_OEN (BIT(6))
#define APB_CTRL_CLK_320M_OEN_S 6
#define APB_CTRL_CLK160_OEN (BIT(5))
#define APB_CTRL_CLK160_OEN_S 5
#define APB_CTRL_CLK80_OEN (BIT(4))
#define APB_CTRL_CLK80_OEN_S 4
#define APB_CTRL_CLK_BB_OEN (BIT(3))
#define APB_CTRL_CLK_BB_OEN_S 3
#define APB_CTRL_CLK44_OEN (BIT(2))
#define APB_CTRL_CLK44_OEN_S 2
#define APB_CTRL_CLK22_OEN (BIT(1))
#define APB_CTRL_CLK22_OEN_S 1
#define APB_CTRL_CLK20_OEN (BIT(0))
#define APB_CTRL_CLK20_OEN_S 0

#define APB_CTRL_HOST_INF_SEL_REG (REG_APB_CTRL_BASE + 0x048)
#define APB_CTRL_SPI_PRIOR (BIT(13))
#define APB_CTRL_SPI_PRIOR_S 13
#define APB_CTRL_SPI1_HOLD (BIT(9))
#define APB_CTRL_SPI1_HOLD_S 9
#define APB_CTRL_SPI0_HOLD (BIT(8))
#define APB_CTRL_SPI0_HOLD_S 8
#define APB_CTRL_PERI_IO_SWAP 0x000000FF
#define APB_CTRL_PERI_IO_SWAP_S 0

#define APB_CTRL_EXT_MEM_PMS_LOCK_REG (REG_APB_CTRL_BASE + 0x04C)
#define APB_CTRL_EXT_MEM_PMS_LOCK (BIT(0))
#define APB_CTRL_EXT_MEM_PMS_LOCK_S 0

#define APB_CTRL_FLASH_ACE0_ATTR_REG (REG_APB_CTRL_BASE + 0x050)
#define APB_CTRL_FLASH_ACE0_ATTR 0x00000007
#define APB_CTRL_FLASH_ACE0_ATTR_S 0

#define APB_CTRL_FLASH_ACE1_ATTR_REG (REG_APB_CTRL_BASE + 0x054)
#define APB_CTRL_FLASH_ACE1_ATTR 0x00000007
#define APB_CTRL_FLASH_ACE1_ATTR_S 0

#define APB_CTRL_FLASH_ACE2_ATTR_REG (REG_APB_CTRL_BASE + 0x058)
#define APB_CTRL_FLASH_ACE2_ATTR 0x00000007
#define APB_CTRL_FLASH_ACE2_ATTR_S 0

#define APB_CTRL_FLASH_ACE3_ATTR_REG (REG_APB_CTRL_BASE + 0x05C)
#define APB_CTRL_FLASH_ACE3_ATTR 0x00000007
#define APB_CTRL_FLASH_ACE3_ATTR_S 0

#define APB_CTRL_FLASH_ACE0_ADDR_REG (REG_APB_CTRL_BASE + 0x060)
#define APB_CTRL_FLASH_ACE0_ADDR_S 0xFFFFFFFF
#define APB_CTRL_FLASH_ACE0_ADDR_S_S 0

#define APB_CTRL_FLASH_ACE1_ADDR_REG (REG_APB_CTRL_BASE + 0x064)
#define APB_CTRL_FLASH_ACE1_ADDR_S 0xFFFFFFFF
#define APB_CTRL_FLASH_ACE1_ADDR_S_S 0

#define APB_CTRL_FLASH_ACE2_ADDR_REG (REG_APB_CTRL_BASE + 0x068)
#define APB_CTRL_FLASH_ACE2_ADDR_S 0xFFFFFFFF
#define APB_CTRL_FLASH_ACE2_ADDR_S_S 0

#define APB_CTRL_FLASH_ACE3_ADDR_REG (REG_APB_CTRL_BASE + 0x06C)
#define APB_CTRL_FLASH_ACE3_ADDR_S 0xFFFFFFFF
#define APB_CTRL_FLASH_ACE3_ADDR_S_S 0

#define APB_CTRL_FLASH_ACE0_SIZE_REG (REG_APB_CTRL_BASE + 0x070)
#define APB_CTRL_FLASH_ACE0_SIZE 0x0000FFFF
#define APB_CTRL_FLASH_ACE0_SIZE_S 0

#define APB_CTRL_FLASH_ACE1_SIZE_REG (REG_APB_CTRL_BASE + 0x074)
#define APB_CTRL_FLASH_ACE1_SIZE 0x0000FFFF
#define APB_CTRL_FLASH_ACE1_SIZE_S 0

#define APB_CTRL_FLASH_ACE2_SIZE_REG (REG_APB_CTRL_BASE + 0x078)
#define APB_CTRL_FLASH_ACE2_SIZE 0x0000FFFF
#define APB_CTRL_FLASH_ACE2_SIZE_S 0

#define APB_CTRL_FLASH_ACE3_SIZE_REG (REG_APB_CTRL_BASE + 0x07C)
#define APB_CTRL_FLASH_ACE3_SIZE 0x0000FFFF
#define APB_CTRL_FLASH_ACE3_SIZE_S 0

#define APB_CTRL_SRAM_ACE0_ATTR_REG (REG_APB_CTRL_BASE + 0x080)
#define APB_CTRL_SRAM_ACE0_ATTR 0x00000007
#define APB_CTRL_SRAM_ACE0_ATTR_S 0

#define APB_CTRL_SRAM_ACE1_ATTR_REG (REG_APB_CTRL_BASE + 0x084)
#define APB_CTRL_SRAM_ACE1_ATTR 0x00000007
#define APB_CTRL_SRAM_ACE1_ATTR_S 0

#define APB_CTRL_SRAM_ACE2_ATTR_REG (REG_APB_CTRL_BASE + 0x088)
#define APB_CTRL_SRAM_ACE2_ATTR 0x00000007
#define APB_CTRL_SRAM_ACE2_ATTR_S 0

#define APB_CTRL_SRAM_ACE3_ATTR_REG (REG_APB_CTRL_BASE + 0x08C)
#define APB_CTRL_SRAM_ACE3_ATTR 0x00000007
#define APB_CTRL_SRAM_ACE3_ATTR_S 0

#define APB_CTRL_SRAM_ACE0_ADDR_REG (REG_APB_CTRL_BASE + 0x090)
#define APB_CTRL_SRAM_ACE0_ADDR_S 0xFFFFFFFF
#define APB_CTRL_SRAM_ACE0_ADDR_S_S 0

#define APB_CTRL_SRAM_ACE1_ADDR_REG (REG_APB_CTRL_BASE + 0x094)
#define APB_CTRL_SRAM_ACE1_ADDR_S 0xFFFFFFFF
#define APB_CTRL_SRAM_ACE1_ADDR_S_S 0

#define APB_CTRL_SRAM_ACE2_ADDR_REG (REG_APB_CTRL_BASE + 0x098)
#define APB_CTRL_SRAM_ACE2_ADDR_S 0xFFFFFFFF
#define APB_CTRL_SRAM_ACE2_ADDR_S_S 0

#define APB_CTRL_SRAM_ACE3_ADDR_REG (REG_APB_CTRL_BASE + 0x09C)
#define APB_CTRL_SRAM_ACE3_ADDR_S 0xFFFFFFFF
#define APB_CTRL_SRAM_ACE3_ADDR_S_S 0

#define APB_CTRL_SRAM_ACE0_SIZE_REG (REG_APB_CTRL_BASE + 0x0A0)
#define APB_CTRL_SRAM_ACE0_SIZE 0x0000FFFF
#define APB_CTRL_SRAM_ACE0_SIZE_S 0

#define APB_CTRL_SRAM_ACE1_SIZE_REG (REG_APB_CTRL_BASE + 0x0A4)
#define APB_CTRL_SRAM_ACE1_SIZE 0x0000FFFF
#define APB_CTRL_SRAM_ACE1_SIZE_S 0

#define APB_CTRL_SRAM_ACE2_SIZE_REG (REG_APB_CTRL_BASE + 0x0A8)
#define APB_CTRL_SRAM_ACE2_SIZE 0x0000FFFF
#define APB_CTRL_SRAM_ACE2_SIZE_S 0

#define APB_CTRL_SRAM_ACE3_SIZE_REG (REG_APB_CTRL_BASE + 0x0AC)
#define APB_CTRL_SRAM_ACE3_SIZE 0x0000FFFF
#define APB_CTRL_SRAM_ACE3_SIZE_S 0

#define APB_CTRL_SPI0_PMS_CTRL_REG (REG_APB_CTRL_BASE + 0x0B0)
#define APB_CTRL_SPI0_REJECT_CDE 0x0000001F
#define APB_CTRL_SPI0_REJECT_CDE_S 2
#define APB_CTRL_SPI0_REJECT_CLR (BIT(1))
#define APB_CTRL_SPI0_REJECT_CLR_S 1
#define APB_CTRL_SPI0_REJECT_INT (BIT(0))
#define APB_CTRL_SPI0_REJECT_INT_S 0

#define APB_CTRL_SPI0_REJECT_ADDR_REG (REG_APB_CTRL_BASE + 0x0B4)
#define APB_CTRL_SPI0_REJECT_ADDR 0xFFFFFFFF
#define APB_CTRL_SPI0_REJECT_ADDR_S 0

#define APB_CTRL_SPI1_PMS_CTRL_REG (REG_APB_CTRL_BASE + 0x0B8)
#define APB_CTRL_SPI1_REJECT_CDE 0x0000001F
#define APB_CTRL_SPI1_REJECT_CDE_S 2
#define APB_CTRL_SPI1_REJECT_CLR (BIT(1))
#define APB_CTRL_SPI1_REJECT_CLR_S 1
#define APB_CTRL_SPI1_REJECT_INT (BIT(0))
#define APB_CTRL_SPI1_REJECT_INT_S 0

#define APB_CTRL_SPI1_REJECT_ADDR_REG (REG_APB_CTRL_BASE + 0x0BC)
#define APB_CTRL_SPI1_REJECT_ADDR 0xFFFFFFFF
#define APB_CTRL_SPI1_REJECT_ADDR_S 0

#define APB_CTRL_SDIO_CTRL_REG (REG_APB_CTRL_BASE + 0x0C0)
#define APB_CTRL_SDIO_WIN_ACCESS_EN (BIT(0))
#define APB_CTRL_SDIO_WIN_ACCESS_EN_S 0

#define APB_CTRL_REDCY_SIG0_REG (REG_APB_CTRL_BASE + 0x0C4)
#define APB_CTRL_REDCY_ANDOR (BIT(31))
#define APB_CTRL_REDCY_ANDOR_S 31
#define APB_CTRL_REDCY_SIG0 0x7FFFFFFF
#define APB_CTRL_REDCY_SIG0_S 0

#define APB_CTRL_REDCY_SIG1_REG (REG_APB_CTRL_BASE + 0x0C8)
#define APB_CTRL_REDCY_NANDOR (BIT(31))
#define APB_CTRL_REDCY_NANDOR_S 31
#define APB_CTRL_REDCY_SIG1 0x7FFFFFFF
#define APB_CTRL_REDCY_SIG1_S 0

#define APB_CTRL_WIFI_BB_CFG_REG (REG_APB_CTRL_BASE + 0x0CC)
#define APB_CTRL_WIFI_BB_CFG 0xFFFFFFFF
#define APB_CTRL_WIFI_BB_CFG_S 0

#define APB_CTRL_WIFI_BB_CFG_2_REG (REG_APB_CTRL_BASE + 0x0D0)
#define APB_CTRL_WIFI_BB_CFG_2 0xFFFFFFFF
#define APB_CTRL_WIFI_BB_CFG_2_S 0

#define APB_CTRL_WIFI_CLK_EN_REG (REG_APB_CTRL_BASE + 0x0D4)
#define APB_CTRL_WIFI_CLK_EN 0xFFFFFFFF
#define APB_CTRL_WIFI_CLK_EN_S 0

#define APB_CTRL_WIFI_RST_EN_REG (REG_APB_CTRL_BASE + 0x0D8)
#define APB_CTRL_WIFI_RST 0xFFFFFFFF
#define APB_CTRL_WIFI_RST_S 0

#define APB_CTRL_FRONT_END_MEM_PD_REG (REG_APB_CTRL_BASE + 0x0DC)
#define APB_CTRL_DC_MEM_FORCE_PD (BIT(5))
#define APB_CTRL_DC_MEM_FORCE_PD_S 5
#define APB_CTRL_DC_MEM_FORCE_PU (BIT(4))
#define APB_CTRL_DC_MEM_FORCE_PU_S 4
#define APB_CTRL_PBUS_MEM_FORCE_PD (BIT(3))
#define APB_CTRL_PBUS_MEM_FORCE_PD_S 3
#define APB_CTRL_PBUS_MEM_FORCE_PU (BIT(2))
#define APB_CTRL_PBUS_MEM_FORCE_PU_S 2
#define APB_CTRL_AGC_MEM_FORCE_PD (BIT(1))
#define APB_CTRL_AGC_MEM_FORCE_PD_S 1
#define APB_CTRL_AGC_MEM_FORCE_PU (BIT(0))
#define APB_CTRL_AGC_MEM_FORCE_PU_S 0

#define APB_CTRL_DATE_REG (REG_APB_CTRL_BASE + 0x3FC)
#define APB_CTRL_DATE 0xFFFFFFFF
#define APB_CTRL_DATE_S 0
#define APB_CTRL_DATE_VERSION 0x18102500
