
#define WDEVLECLK_US (REG_WDEVLE_BASE + 0x0000)
#define WDEV_LECLK_US 0xFFFFFFFF
#define WDEV_LECLK_US_S 0

#define WDEVLECLK_US_SW (REG_WDEVLE_BASE + 0x0004)
#define WDEV_LECLK_US_SW 0xFFFFFFFF
#define WDEV_LECLK_US_SW_S 0

#define WDEVLE_AC_ENA (REG_WDEVLE_BASE + 0x0008)
#define WDEV_LERXAC_ENA 0x00000003
#define WDEV_LERXAC_ENA_S 30

#define WDEVLE_AC0 (REG_WDEVLE_BASE + 0x000C)
#define WDEV_LE_AC0 0xFFFFFFFF
#define WDEV_LE_AC0_S 0

#define WDEVLE_AC1 (REG_WDEVLE_BASE + 0x0010)
#define WDEV_LE_AC1 0xFFFFFFFF
#define WDEV_LE_AC1_S 0

#define WDEVLE_TXPMD (REG_WDEVLE_BASE + 0x0014)
#define WDEV_LETXEND_STATE 0x000000FF
#define WDEV_LETXEND_STATE_S 0

#define WDEVLECH (REG_WDEVLE_BASE + 0x0018)
#define WDEV_LECRC_INIT_DATA 0x00FFFFFF
#define WDEV_LECRC_INIT_DATA_S 8
#define WDEV_LECH_INDEX 0x0000003F
#define WDEV_LECH_INDEX_S 0

#define WDEVLETX0_CONF0 (REG_WDEVLE_BASE + 0x001C)
#define WDEV_LETX0_ENA (BIT(31))
#define WDEV_LETX0_ENA_S 31
#define WDEV_LETX0_TYPE (BIT(30))
#define WDEV_LETX0_TYPE_S 30
#define WDEV_LETX0_CRYPT (BIT(29))
#define WDEV_LETX0_CRYPT_S 29
#define WDEV_LETX0_LEN 0x000000FF
#define WDEV_LETX0_LEN_S 20
#define WDEV_LETX0_LINK_ADDR 0x0003FFFF
#define WDEV_LETX0_LINK_ADDR_S 0

#define WDEVLETX0_HEAD (REG_WDEVLE_BASE + 0x0020)
#define WDEV_LETX0_HEAD 0x0000FFFF
#define WDEV_LETX0_HEAD_S 0

#define WDEVLERX0_CONF (REG_WDEVLE_BASE + 0x0024)
#define WDEV_LERX0_ENA (BIT(31))
#define WDEV_LERX0_ENA_S 31
#define WDEV_LERX0_TYPE (BIT(30))
#define WDEV_LERX0_TYPE_S 30
#define WDEV_LERX0_CRYPT (BIT(29))
#define WDEV_LERX0_CRYPT_S 29
#define WDEV_LERX0_FORCE_END (BIT(28))
#define WDEV_LERX0_FORCE_END_S 28

#define WDEVLE_RXAC_TIMER (REG_WDEVLE_BASE + 0x0028)
#define WDEV_LERXAC_DELAY_ENA (BIT(31))
#define WDEV_LERXAC_DELAY_ENA_S 31
#define WDEV_LERXAC_DELAY 0x000001FF
#define WDEV_LERXAC_DELAY_S 0

#define WDEVLE_IFS (REG_WDEVLE_BASE + 0x002C)
#define WDEV_LE_RXTX_DELAY 0x000000FF
#define WDEV_LE_RXTX_DELAY_S 16
#define WDEV_LE_TXRX_DELAY 0x000000FF
#define WDEV_LE_TXRX_DELAY_S 8
#define WDEV_LEIFS 0x000000FF
#define WDEV_LEIFS_S 0

#define INT_ENA_WDEVLE (REG_WDEVLE_BASE + 0x0030)
#define WDEV_LETIMER7_INT_ENA (BIT(15))
#define WDEV_LETIMER7_INT_ENA_S 15
#define WDEV_LETIMER6_INT_ENA (BIT(14))
#define WDEV_LETIMER6_INT_ENA_S 14
#define WDEV_LETIMER5_INT_ENA (BIT(13))
#define WDEV_LETIMER5_INT_ENA_S 13
#define WDEV_LETIMER4_INT_ENA (BIT(12))
#define WDEV_LETIMER4_INT_ENA_S 12
#define WDEV_LETIMER3_INT_ENA (BIT(11))
#define WDEV_LETIMER3_INT_ENA_S 11
#define WDEV_LETIMER2_INT_ENA (BIT(10))
#define WDEV_LETIMER2_INT_ENA_S 10
#define WDEV_LETIMER1_INT_ENA (BIT(9))
#define WDEV_LETIMER1_INT_ENA_S 9
#define WDEV_LETIMER0_INT_ENA (BIT(8))
#define WDEV_LETIMER0_INT_ENA_S 8
#define WDEV_LETXEND_DATA_SUC_INT_ENA (BIT(7))
#define WDEV_LETXEND_DATA_SUC_INT_ENA_S 7
#define WDEV_LETXEND_SUC_INT_ENA (BIT(6))
#define WDEV_LETXEND_SUC_INT_ENA_S 6
#define WDEV_LERXEND_DATA_SUC_INT_ENA (BIT(5))
#define WDEV_LERXEND_DATA_SUC_INT_ENA_S 5
#define WDEV_LERXEND_SUC_INT_ENA (BIT(4))
#define WDEV_LERXEND_SUC_INT_ENA_S 4
#define WDEV_LERXSTART_INT_ENA (BIT(3))
#define WDEV_LERXSTART_INT_ENA_S 3
#define WDEV_LETXSTART_INT_ENA (BIT(2))
#define WDEV_LETXSTART_INT_ENA_S 2
#define WDEV_LERXEND_INT_ENA (BIT(1))
#define WDEV_LERXEND_INT_ENA_S 1
#define WDEV_LETXEND_INT_ENA (BIT(0))
#define WDEV_LETXEND_INT_ENA_S 0

#define INT_RAW_WDEVLE (REG_WDEVLE_BASE + 0x0034)
#define WDEV_LETIMER7_INT_RAW (BIT(15))
#define WDEV_LETIMER7_INT_RAW_S 15
#define WDEV_LETIMER6_INT_RAW (BIT(14))
#define WDEV_LETIMER6_INT_RAW_S 14
#define WDEV_LETIMER5_INT_RAW (BIT(13))
#define WDEV_LETIMER5_INT_RAW_S 13
#define WDEV_LETIMER4_INT_RAW (BIT(12))
#define WDEV_LETIMER4_INT_RAW_S 12
#define WDEV_LETIMER3_INT_RAW (BIT(11))
#define WDEV_LETIMER3_INT_RAW_S 11
#define WDEV_LETIMER2_INT_RAW (BIT(10))
#define WDEV_LETIMER2_INT_RAW_S 10
#define WDEV_LETIMER1_INT_RAW (BIT(9))
#define WDEV_LETIMER1_INT_RAW_S 9
#define WDEV_LETIMER0_INT_RAW (BIT(8))
#define WDEV_LETIMER0_INT_RAW_S 8
#define WDEV_LETXEND_DATA_SUC_INT_RAW (BIT(7))
#define WDEV_LETXEND_DATA_SUC_INT_RAW_S 7
#define WDEV_LETXEND_SUC_INT_RAW (BIT(6))
#define WDEV_LETXEND_SUC_INT_RAW_S 6
#define WDEV_LERXEND_DATA_SUC_INT_RAW (BIT(5))
#define WDEV_LERXEND_DATA_SUC_INT_RAW_S 5
#define WDEV_LERXEND_SUC_INT_RAW (BIT(4))
#define WDEV_LERXEND_SUC_INT_RAW_S 4
#define WDEV_LERXSTART_INT_RAW (BIT(3))
#define WDEV_LERXSTART_INT_RAW_S 3
#define WDEV_LETXSTART_INT_RAW (BIT(2))
#define WDEV_LETXSTART_INT_RAW_S 2
#define WDEV_LERXEND_INT_RAW (BIT(1))
#define WDEV_LERXEND_INT_RAW_S 1
#define WDEV_LETXEND_INT_RAW (BIT(0))
#define WDEV_LETXEND_INT_RAW_S 0

#define INT_ST_WDEVLE (REG_WDEVLE_BASE + 0x0038)
#define WDEV_LETIMER7_INT_ST (BIT(15))
#define WDEV_LETIMER7_INT_ST_S 15
#define WDEV_LETIMER6_INT_ST (BIT(14))
#define WDEV_LETIMER6_INT_ST_S 14
#define WDEV_LETIMER5_INT_ST (BIT(13))
#define WDEV_LETIMER5_INT_ST_S 13
#define WDEV_LETIMER4_INT_ST (BIT(12))
#define WDEV_LETIMER4_INT_ST_S 12
#define WDEV_LETIMER3_INT_ST (BIT(11))
#define WDEV_LETIMER3_INT_ST_S 11
#define WDEV_LETIMER2_INT_ST (BIT(10))
#define WDEV_LETIMER2_INT_ST_S 10
#define WDEV_LETIMER1_INT_ST (BIT(9))
#define WDEV_LETIMER1_INT_ST_S 9
#define WDEV_LETIMER0_INT_ST (BIT(8))
#define WDEV_LETIMER0_INT_ST_S 8
#define WDEV_LETXEND_DATA_SUC_INT_ST (BIT(7))
#define WDEV_LETXEND_DATA_SUC_INT_ST_S 7
#define WDEV_LETXEND_SUC_INT_ST (BIT(6))
#define WDEV_LETXEND_SUC_INT_ST_S 6
#define WDEV_LERXEND_DATA_SUC_INT_ST (BIT(5))
#define WDEV_LERXEND_DATA_SUC_INT_ST_S 5
#define WDEV_LERXEND_SUC_INT_ST (BIT(4))
#define WDEV_LERXEND_SUC_INT_ST_S 4
#define WDEV_LERXSTART_INT_ST (BIT(3))
#define WDEV_LERXSTART_INT_ST_S 3
#define WDEV_LETXSTART_INT_ST (BIT(2))
#define WDEV_LETXSTART_INT_ST_S 2
#define WDEV_LERXEND_INT_ST (BIT(1))
#define WDEV_LERXEND_INT_ST_S 1
#define WDEV_LETXEND_INT_ST (BIT(0))
#define WDEV_LETXEND_INT_ST_S 0

#define INT_CLR_WDEVLE (REG_WDEVLE_BASE + 0x003C)
#define WDEV_LETIMER7_INT_CLR (BIT(15))
#define WDEV_LETIMER7_INT_CLR_S 15
#define WDEV_LETIMER6_INT_CLR (BIT(14))
#define WDEV_LETIMER6_INT_CLR_S 14
#define WDEV_LETIMER5_INT_CLR (BIT(13))
#define WDEV_LETIMER5_INT_CLR_S 13
#define WDEV_LETIMER4_INT_CLR (BIT(12))
#define WDEV_LETIMER4_INT_CLR_S 12
#define WDEV_LETIMER3_INT_CLR (BIT(11))
#define WDEV_LETIMER3_INT_CLR_S 11
#define WDEV_LETIMER2_INT_CLR (BIT(10))
#define WDEV_LETIMER2_INT_CLR_S 10
#define WDEV_LETIMER1_INT_CLR (BIT(9))
#define WDEV_LETIMER1_INT_CLR_S 9
#define WDEV_LETIMER0_INT_CLR (BIT(8))
#define WDEV_LETIMER0_INT_CLR_S 8
#define WDEV_LETXEND_DATA_SUC_INT_CLR (BIT(7))
#define WDEV_LETXEND_DATA_SUC_INT_CLR_S 7
#define WDEV_LETXEND_SUC_INT_CLR (BIT(6))
#define WDEV_LETXEND_SUC_INT_CLR_S 6
#define WDEV_LERXEND_DATA_SUC_INT_CLR (BIT(5))
#define WDEV_LERXEND_DATA_SUC_INT_CLR_S 5
#define WDEV_LERXEND_SUC_INT_CLR (BIT(4))
#define WDEV_LERXEND_SUC_INT_CLR_S 4
#define WDEV_LERXSTART_INT_CLR (BIT(3))
#define WDEV_LERXSTART_INT_CLR_S 3
#define WDEV_LETXSTART_INT_CLR (BIT(2))
#define WDEV_LETXSTART_INT_CLR_S 2
#define WDEV_LERXEND_INT_CLR (BIT(1))
#define WDEV_LERXEND_INT_CLR_S 1
#define WDEV_LETXEND_INT_CLR (BIT(0))
#define WDEV_LETXEND_INT_CLR_S 0

#define WDEVLE_RXMODE (REG_WDEVLE_BASE + 0x0040)
#define WDEV_LERX_ENA_FRC (BIT(31))
#define WDEV_LERX_ENA_FRC_S 31
#define WDEV_LERX_ENA_SUC (BIT(30))
#define WDEV_LERX_ENA_SUC_S 30
#define WDEV_LERX_ENA_ANY (BIT(29))
#define WDEV_LERX_ENA_ANY_S 29

#define WDEVLE_RXBASE (REG_WDEVLE_BASE + 0x0044)
#define WDEV_LERX_BASE 0xFFFFFFFF
#define WDEV_LERX_BASE_S 0

#define WDEVLERXBUFDSCR_LAST (REG_WDEVLE_BASE + 0x0048)
#define WDEV_LELAST_RXBUFDSCR 0xFFFFFFFF
#define WDEV_LELAST_RXBUFDSCR_S 0

#define WDEVLERXBUFBK_CNT (REG_WDEVLE_BASE + 0x004C)
#define WDEV_LELAST_RXBUFBK_CNT 0x000000FF
#define WDEV_LELAST_RXBUFBK_CNT_S 0

#define WDEVLERXBUFDSCR_START (REG_WDEVLE_BASE + 0x0050)
#define WDEV_LESTART_RXBUFDSCR 0xFFFFFFFF
#define WDEV_LESTART_RXBUFDSCR_S 0

#define WDEVLE_RXPMD (REG_WDEVLE_BASE + 0x0054)
#define WDEV_LERXEND_STATE 0x000000FF
#define WDEV_LERXEND_STATE_S 0

#define WDEVLE_CODE_OPTION (REG_WDEVLE_BASE + 0x0058)
#define WDEV_LERX_FORCE_NOWHITE (BIT(1))
#define WDEV_LERX_FORCE_NOWHITE_S 1
#define WDEV_LETX_FORCE_NOWHITE (BIT(0))
#define WDEV_LETX_FORCE_NOWHITE_S 0

#define WDEVLE_TIMER_ENA (REG_WDEVLE_BASE + 0x005C)
#define WDEV_LETIMER7_ENA (BIT(7))
#define WDEV_LETIMER7_ENA_S 7
#define WDEV_LETIMER6_ENA (BIT(6))
#define WDEV_LETIMER6_ENA_S 6
#define WDEV_LETIMER5_ENA (BIT(5))
#define WDEV_LETIMER5_ENA_S 5
#define WDEV_LETIMER4_ENA (BIT(4))
#define WDEV_LETIMER4_ENA_S 4
#define WDEV_LETIMER3_ENA (BIT(3))
#define WDEV_LETIMER3_ENA_S 3
#define WDEV_LETIMER2_ENA (BIT(2))
#define WDEV_LETIMER2_ENA_S 2
#define WDEV_LETIMER1_ENA (BIT(1))
#define WDEV_LETIMER1_ENA_S 1
#define WDEV_LETIMER0_ENA (BIT(0))
#define WDEV_LETIMER0_ENA_S 0

#define WDEVLE_TIMER7 (REG_WDEVLE_BASE + 0x0060)
#define WDEV_LETIMER7 0xFFFFFFFF
#define WDEV_LETIMER7_S 0

#define WDEVLE_TIMER6 (REG_WDEVLE_BASE + 0x0064)
#define WDEV_LETIMER6 0xFFFFFFFF
#define WDEV_LETIMER6_S 0

#define WDEVLE_TIMER5 (REG_WDEVLE_BASE + 0x0068)
#define WDEV_LETIMER5 0xFFFFFFFF
#define WDEV_LETIMER5_S 0

#define WDEVLE_TIMER4 (REG_WDEVLE_BASE + 0x006C)
#define WDEV_LETIMER4 0xFFFFFFFF
#define WDEV_LETIMER4_S 0

#define WDEVLE_TIMER3 (REG_WDEVLE_BASE + 0x0070)
#define WDEV_LETIMER3 0xFFFFFFFF
#define WDEV_LETIMER3_S 0

#define WDEVLE_TIMER2 (REG_WDEVLE_BASE + 0x0074)
#define WDEV_LETIMER2 0xFFFFFFFF
#define WDEV_LETIMER2_S 0

#define WDEVLE_TIMER1 (REG_WDEVLE_BASE + 0x0078)
#define WDEV_LETIMER1 0xFFFFFFFF
#define WDEV_LETIMER1_S 0

#define WDEVLE_TIMER0 (REG_WDEVLE_BASE + 0x007C)
#define WDEV_LETIMER0 0xFFFFFFFF
#define WDEV_LETIMER0_S 0

#define WDEVLE_ENC_ROLE (REG_WDEVLE_BASE + 0x0080)
#define WDEV_LEENCROLE (BIT(31))
#define WDEV_LEENCROLE_S 31

#define WDEVLE_ENC_PCNT0 (REG_WDEVLE_BASE + 0x0084)
#define WDEV_LEENC_PCNT0 0xFFFFFFFF
#define WDEV_LEENC_PCNT0_S 0

#define WDEVLE_ENC_PCNT1 (REG_WDEVLE_BASE + 0x0088)
#define WDEV_LEENC_PCNT1 0x0000007F
#define WDEV_LEENC_PCNT1_S 0

#define WDEVLE_DEBUG_MODE (REG_WDEVLE_BASE + 0x008C)
#define WDEV_LEEDA_DEBUG 0xFFFFFFFF
#define WDEV_LEEDA_DEBUG_S 0

#define WDEVLE_AGC_STATE (REG_WDEVLE_BASE + 0x0090)
#define WDEV_LERX_20US_RISE_CNT 0x0000000F
#define WDEV_LERX_20US_RISE_CNT_S 28
#define WDEV_LERX_20US_DROP_CNT 0x0000000F
#define WDEV_LERX_20US_DROP_CNT_S 24
#define WDEV_LERX_AC_RISE_CNT 0x0000000F
#define WDEV_LERX_AC_RISE_CNT_S 20
#define WDEV_LERX_AC_DROP_CNT 0x0000000F
#define WDEV_LERX_AC_DROP_CNT_S 16
#define WDEV_LERX_DATA_RISE_CNT 0x000000FF
#define WDEV_LERX_DATA_RISE_CNT_S 8
#define WDEV_LERX_DATA_DROP_CNT 0x000000FF
#define WDEV_LERX_DATA_DROP_CNT_S 0

#define WDEVLE_AGC_CONF (REG_WDEVLE_BASE + 0x0094)
#define WDEV_LERX_20US_RISE 0x0000000F
#define WDEV_LERX_20US_RISE_S 28
#define WDEV_LERX_20US_DROP 0x0000000F
#define WDEV_LERX_20US_DROP_S 24
#define WDEV_LERX_AC_RISE 0x0000000F
#define WDEV_LERX_AC_RISE_S 20
#define WDEV_LERX_AC_DROP 0x0000000F
#define WDEV_LERX_AC_DROP_S 16
#define WDEV_LERX_DATA_RISE 0x000000FF
#define WDEV_LERX_DATA_RISE_S 8
#define WDEV_LERX_DATA_DROP 0x000000FF
#define WDEV_LERX_DATA_DROP_S 0

#define WDEVLE_CLOCK_GATING (REG_WDEVLE_BASE + 0x0098)
#define WDEV_LE_CLK_EN (BIT(31))
#define WDEV_LE_CLK_EN_S 31

#define WDEVLEDATA (REG_WDEVLE_BASE + 0x03F8)
#define WDEV_LEMAC_DATE 0x0FFFFFFF
#define WDEV_LEMAC_DATE_S 0
#define WDEV_LEMAC_DATE_VERSION 0x1505190
