
#define WDEVBTCLKN (REG_WDEVBT_BASE + 0x0000)
#define WDEV_BTCLKN_ENA (BIT(31))
#define WDEV_BTCLKN_ENA_S 31
#define WDEV_BTCLKN 0x0FFFFFFF
#define WDEV_BTCLKN_S 0

#define WDEVBTCLKN_TICK (REG_WDEVBT_BASE + 0x0004)
#define WDEV_BTCLKN_TICK 0x000003FF
#define WDEV_BTCLKN_TICK_S 22

#define WDEVBTCLKN_SW (REG_WDEVBT_BASE + 0x0008)
#define WDEV_BTCLKN_SW 0x0FFFFFFF
#define WDEV_BTCLKN_SW_S 0

#define WDEVBTCLKN_TICK_SW (REG_WDEVBT_BASE + 0x000C)
#define WDEV_BTCLKN_TICK_SW 0x000003FF
#define WDEV_BTCLKN_TICK_SW_S 22

#define WDEVBTCLKN_TIMER (REG_WDEVBT_BASE + 0x0010)
#define WDEV_BTCLKN_TIMER_EN (BIT(31))
#define WDEV_BTCLKN_TIMER_EN_S 31
#define WDEV_BTCLKN_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKN_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKN_TIMER 0x0FFFFFFF
#define WDEV_BTCLKN_TIMER_S 0

#define WDEVBTCLKN_TIMER_OFFSET (REG_WDEVBT_BASE + 0x0014)
#define WDEV_BTCLKN_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKN_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKN_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKN_TIMER_OFFSET_S 12

#define WDEVBTCLK_US (REG_WDEVBT_BASE + 0x0018)
#define WDEV_BTCLK_US 0xFFFFFFFF
#define WDEV_BTCLK_US_S 0

#define WDEVBTCLK_US_TIMER_EN (REG_WDEVBT_BASE + 0x001C)
#define WDEV_BTCLK_US_TIMER_EN (BIT(31))
#define WDEV_BTCLK_US_TIMER_EN_S 31

#define WDEVBTCLK_US_TIMER (REG_WDEVBT_BASE + 0x0020)
#define WDEV_BTCLK_US_TIMER 0xFFFFFFFF
#define WDEV_BTCLK_US_TIMER_S 0

#define WDEVBTCLKS (REG_WDEVBT_BASE + 0x0024)
#define WDEV_BTCLKS_ENA (BIT(31))
#define WDEV_BTCLKS_ENA_S 31
#define WDEV_BTCLKS 0x0FFFFFFF
#define WDEV_BTCLKS_S 0

#define WDEVBTCLKS_27_0_OFFSET (REG_WDEVBT_BASE + 0x0028)
#define WDEV_BTCLKS_27_0_OFFSET 0x0FFFFFFF
#define WDEV_BTCLKS_27_0_OFFSET_S 0

#define WDEVBTCLKS_0_5US_OFFSET (REG_WDEVBT_BASE + 0x002C)
#define WDEV_BTCLKS_0_5US_OFFSET 0x000003FF
#define WDEV_BTCLKS_0_5US_OFFSET_S 0

#define WDEVBTCLKS_27_0_OFFSET_SW (REG_WDEVBT_BASE + 0x0030)
#define WDEV_BTCLKS_27_0_OFFSET_SW 0x0FFFFFFF
#define WDEV_BTCLKS_27_0_OFFSET_SW_S 0

#define WDEVBTCLKS_0_5US_OFFSET_SW (REG_WDEVBT_BASE + 0x0034)
#define WDEV_BTCLKS_0_5US_OFFSET_SW 0x000003FF
#define WDEV_BTCLKS_0_5US_OFFSET_SW_S 0

#define WDEVBTCLKS_TIMER (REG_WDEVBT_BASE + 0x0038)
#define WDEV_BTCLKS_TIMER_EN (BIT(31))
#define WDEV_BTCLKS_TIMER_EN_S 31
#define WDEV_BTCLKS_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKS_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKS_TIMER 0x0FFFFFFF
#define WDEV_BTCLKS_TIMER_S 0

#define WDEVBTCLKS_TIMER_OFFSET (REG_WDEVBT_BASE + 0x003C)
#define WDEV_BTCLKS_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKS_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS_TIMER_OFFSET_S 12

#define WDEVBTCLKS1 (REG_WDEVBT_BASE + 0x0040)
#define WDEV_BTCLKS1_ENA (BIT(31))
#define WDEV_BTCLKS1_ENA_S 31
#define WDEV_BTCLKS1 0x0FFFFFFF
#define WDEV_BTCLKS1_S 0

#define WDEVBTCLKS1_27_0_OFFSET_SW (REG_WDEVBT_BASE + 0x0044)
#define WDEV_BTCLKS1_27_0_OFFSET_SW 0x0FFFFFFF
#define WDEV_BTCLKS1_27_0_OFFSET_SW_S 0

#define WDEVBTCLKS1_0_5US_OFFSET_SW (REG_WDEVBT_BASE + 0x0048)
#define WDEV_BTCLKS1_0_5US_OFFSET_SW 0x000003FF
#define WDEV_BTCLKS1_0_5US_OFFSET_SW_S 0

#define WDEVBTCLKS1_TIMER (REG_WDEVBT_BASE + 0x004C)
#define WDEV_BTCLKS1_TIMER_EN (BIT(31))
#define WDEV_BTCLKS1_TIMER_EN_S 31
#define WDEV_BTCLKS1_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKS1_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKS1_TIMER 0x0FFFFFFF
#define WDEV_BTCLKS1_TIMER_S 0

#define WDEVBTCLKS1_TIMER_OFFSET (REG_WDEVBT_BASE + 0x0050)
#define WDEV_BTCLKS1_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS1_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKS1_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS1_TIMER_OFFSET_S 12

#define WDEVBTCLKS2 (REG_WDEVBT_BASE + 0x0054)
#define WDEV_BTCLKS2_ENA (BIT(31))
#define WDEV_BTCLKS2_ENA_S 31
#define WDEV_BTCLKS2 0x0FFFFFFF
#define WDEV_BTCLKS2_S 0

#define WDEVBTCLKS2_27_0_OFFSET_SW (REG_WDEVBT_BASE + 0x0058)
#define WDEV_BTCLKS2_27_0_OFFSET_SW 0x0FFFFFFF
#define WDEV_BTCLKS2_27_0_OFFSET_SW_S 0

#define WDEVBTCLKS2_0_5US_OFFSET_SW (REG_WDEVBT_BASE + 0x005C)
#define WDEV_BTCLKS2_0_5US_OFFSET_SW 0x000003FF
#define WDEV_BTCLKS2_0_5US_OFFSET_SW_S 0

#define WDEVBTCLKS2_TIMER (REG_WDEVBT_BASE + 0x0060)
#define WDEV_BTCLKS2_TIMER_EN (BIT(31))
#define WDEV_BTCLKS2_TIMER_EN_S 31
#define WDEV_BTCLKS2_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKS2_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKS2_TIMER 0x0FFFFFFF
#define WDEV_BTCLKS2_TIMER_S 0

#define WDEVBTCLKS2_TIMER_OFFSET (REG_WDEVBT_BASE + 0x0064)
#define WDEV_BTCLKS2_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS2_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKS2_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS2_TIMER_OFFSET_S 12

#define WDEVBTCLKS3 (REG_WDEVBT_BASE + 0x0068)
#define WDEV_BTCLKS3_ENA (BIT(31))
#define WDEV_BTCLKS3_ENA_S 31
#define WDEV_BTCLKS3 0x0FFFFFFF
#define WDEV_BTCLKS3_S 0

#define WDEVBTCLKS3_27_0_OFFSET_SW (REG_WDEVBT_BASE + 0x006C)
#define WDEV_BTCLKS3_27_0_OFFSET_SW 0x0FFFFFFF
#define WDEV_BTCLKS3_27_0_OFFSET_SW_S 0

#define WDEVBTCLKS3_0_5US_OFFSET_SW (REG_WDEVBT_BASE + 0x0070)
#define WDEV_BTCLKS3_0_5US_OFFSET_SW 0x000003FF
#define WDEV_BTCLKS3_0_5US_OFFSET_SW_S 0

#define WDEVBTCLKS3_TIMER (REG_WDEVBT_BASE + 0x0074)
#define WDEV_BTCLKS3_TIMER_EN (BIT(31))
#define WDEV_BTCLKS3_TIMER_EN_S 31
#define WDEV_BTCLKS3_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKS3_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKS3_TIMER 0x0FFFFFFF
#define WDEV_BTCLKS3_TIMER_S 0

#define WDEVBTCLKS3_TIMER_OFFSET (REG_WDEVBT_BASE + 0x0078)
#define WDEV_BTCLKS3_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS3_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKS3_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKS3_TIMER_OFFSET_S 12

#define WDEVBTCLKE (REG_WDEVBT_BASE + 0x007C)
#define WDEV_BTCLKE_ENA (BIT(31))
#define WDEV_BTCLKE_ENA_S 31
#define WDEV_BTCLKE 0x0FFFFFFF
#define WDEV_BTCLKE_S 0

#define WDEVBTCLKE_TIMER (REG_WDEVBT_BASE + 0x0080)
#define WDEV_BTCLKE_TIMER_EN (BIT(31))
#define WDEV_BTCLKE_TIMER_EN_S 31
#define WDEV_BTCLKE_SLOT_TIMER_EN 0x00000003
#define WDEV_BTCLKE_SLOT_TIMER_EN_S 29
#define WDEV_BTCLKE_TIMER 0x0FFFFFFF
#define WDEV_BTCLKE_TIMER_S 0

#define WDEVBTCLKE_TIMER_OFFSET (REG_WDEVBT_BASE + 0x0084)
#define WDEV_BTCLKE_SLOT_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKE_SLOT_TIMER_OFFSET_S 22
#define WDEV_BTCLKE_TIMER_OFFSET 0x000003FF
#define WDEV_BTCLKE_TIMER_OFFSET_S 12

#define WDEVBTG_ULAP (REG_WDEVBT_BASE + 0x0088)
#define WDEV_BT_GUAP 0x000000FF
#define WDEV_BT_GUAP_S 24
#define WDEV_BT_GLAP 0x00FFFFFF
#define WDEV_BT_GLAP_S 0

#define WDEVBTG_NAP (REG_WDEVBT_BASE + 0x008C)
#define WDEV_BT_GNAP 0x0000FFFF
#define WDEV_BT_GNAP_S 0

#define WDEVBTP_ULAP (REG_WDEVBT_BASE + 0x0090)
#define WDEV_BT_PUAP 0x000000FF
#define WDEV_BT_PUAP_S 24
#define WDEV_BT_PLAP 0x00FFFFFF
#define WDEV_BT_PLAP_S 0

#define WDEVBTP_NAP (REG_WDEVBT_BASE + 0x0094)
#define WDEV_BT_PNAP 0x0000FFFF
#define WDEV_BT_PNAP_S 0

#define WDEVBTBD_ULAP (REG_WDEVBT_BASE + 0x0098)
#define WDEV_BT_UAP 0x000000FF
#define WDEV_BT_UAP_S 24
#define WDEV_BT_LAP 0x00FFFFFF
#define WDEV_BT_LAP_S 0

#define WDEVBTBD_NAP (REG_WDEVBT_BASE + 0x009C)
#define WDEV_BT_NAP 0x0000FFFF
#define WDEV_BT_NAP_S 0

#define WDEVBTS_ULAP (REG_WDEVBT_BASE + 0x00A0)
#define WDEV_BT_SUAP 0x000000FF
#define WDEV_BT_SUAP_S 24
#define WDEV_BT_SLAP 0x00FFFFFF
#define WDEV_BT_SLAP_S 0

#define WDEVBTS_NAP (REG_WDEVBT_BASE + 0x00A4)
#define WDEV_BT_SNAP 0x0000FFFF
#define WDEV_BT_SNAP_S 0

#define WDEVBT_RXAC_UAP (REG_WDEVBT_BASE + 0x00A8)
#define WDEV_BTRXUAP_ENA 0x00000003
#define WDEV_BTRXUAP_ENA_S 30
#define WDEV_BTRXSECOND_UAP 0x00FFFFFF
#define WDEV_BTRXSECOND_UAP_S 0

#define WDEVBT_TXPMD (REG_WDEVBT_BASE + 0x00AC)
#define WDEV_BTTXCOL_MAP 0x0000001F
#define WDEV_BTTXCOL_MAP_S 19
#define WDEV_BTTXCOL_STATE 0x00000003
#define WDEV_BTTXCOL_STATE_S 17
#define WDEV_BTTXSTART_MAP 0x0000001F
#define WDEV_BTTXSTART_MAP_S 12
#define WDEV_BTTXEND_PAYLOAD1_HEAD_LEN 0x00000003
#define WDEV_BTTXEND_PAYLOAD1_HEAD_LEN_S 10
#define WDEV_BTTXEND_PAYLOAD0_HEAD_LEN 0x00000003
#define WDEV_BTTXEND_PAYLOAD0_HEAD_LEN_S 8
#define WDEV_BTTXEND_STATE 0x000000FF
#define WDEV_BTTXEND_STATE_S 0

#define WDEVBTSCO_CONF (REG_WDEVBT_BASE + 0x00B0)
#define WDEV_BTTXESCO_LEN 0x000003FF
#define WDEV_BTTXESCO_LEN_S 12
#define WDEV_BTRXESCO_LEN 0x000003FF
#define WDEV_BTRXESCO_LEN_S 0

#define WDEVBTTX0_CONF0 (REG_WDEVBT_BASE + 0x00B4)
#define WDEV_BTTX0SLOT_ENA (BIT(31))
#define WDEV_BTTX0SLOT_ENA_S 31
#define WDEV_BTTX0_TYPE 0x00000007
#define WDEV_BTTX0_TYPE_S 28
#define WDEV_BTTX0_AFH (BIT(27))
#define WDEV_BTTX0_AFH_S 27
#define WDEV_BTTX0_AUDIO_EN (BIT(26))
#define WDEV_BTTX0_AUDIO_EN_S 26
#define WDEV_BTTX0_LT_SEL 0x00000007
#define WDEV_BTTX0_LT_SEL_S 21
#define WDEV_BTTX0SLOT_VALID (BIT(20))
#define WDEV_BTTX0SLOT_VALID_S 20
#define WDEV_BTTX0_LINK_ADDR 0x0003FFFF
#define WDEV_BTTX0_LINK_ADDR_S 0

#define WDEVBTTX0_CONF1 (REG_WDEVBT_BASE + 0x00B8)
#define WDEV_BTTX0_IS_ID (BIT(31))
#define WDEV_BTTX0_IS_ID_S 31
#define WDEV_BTTX0_HALF_SLOT 0x00000003
#define WDEV_BTTX0_HALF_SLOT_S 29
#define WDEV_BTTX0_SECLINK_ENA (BIT(28))
#define WDEV_BTTX0_SECLINK_ENA_S 28
#define WDEV_BTTX0_SEC_TYPE 0x00000007
#define WDEV_BTTX0_SEC_TYPE_S 25
#define WDEV_BTTX0_CRYPT 0x00000003
#define WDEV_BTTX0_CRYPT_S 12
#define WDEV_BTTX0_LEN 0x000007FF
#define WDEV_BTTX0_LEN_S 0

#define WDEVBTTX0_HEAD (REG_WDEVBT_BASE + 0x00BC)
#define WDEV_BTTX0_PAYLOAD_HEAD 0x0000FFFF
#define WDEV_BTTX0_PAYLOAD_HEAD_S 10
#define WDEV_BTTX0_PACKET_HEAD 0x000003FF
#define WDEV_BTTX0_PACKET_HEAD_S 0

#define WDEVBTRX0_CONF (REG_WDEVBT_BASE + 0x00C0)
#define WDEV_BTRX0SLOT_ENA (BIT(31))
#define WDEV_BTRX0SLOT_ENA_S 31
#define WDEV_BTRX0_TYPE 0x00000007
#define WDEV_BTRX0_TYPE_S 28
#define WDEV_BTRX0_AFH (BIT(27))
#define WDEV_BTRX0_AFH_S 27
#define WDEV_BTRX0_AUDIO_EN (BIT(26))
#define WDEV_BTRX0_AUDIO_EN_S 26
#define WDEV_BTRX0_LT_SEL 0x00000007
#define WDEV_BTRX0_LT_SEL_S 21
#define WDEV_BTRX0_IS_ID (BIT(20))
#define WDEV_BTRX0_IS_ID_S 20
#define WDEV_BTRX0_HALF_SLOT 0x00000003
#define WDEV_BTRX0_HALF_SLOT_S 18
#define WDEV_BTRX0_CRYPT 0x00000003
#define WDEV_BTRX0_CRYPT_S 16
#define WDEV_BTRX0_SECLINK_ENA (BIT(15))
#define WDEV_BTRX0_SECLINK_ENA_S 15
#define WDEV_BTRX0_SEC_TYPE 0x00000007
#define WDEV_BTRX0_SEC_TYPE_S 12

#define WDEVBT_CMD_PMD (REG_WDEVBT_BASE + 0x00C4)
#define WDEV_BTCMD_STATE 0x0000000F
#define WDEV_BTCMD_STATE_S 0

#define WDEVBT_CMD0 (REG_WDEVBT_BASE + 0x00C8)
#define WDEV_BTCMD_CON_M (BIT(8))
#define WDEV_BTCMD_CON_M_S 8
#define WDEV_BTCMD_CON_S (BIT(4))
#define WDEV_BTCMD_CON_S_S 4
#define WDEV_BTCMD 0x0000000F
#define WDEV_BTCMD_S 0

#define WDEVBT_CMD0_CONF1 (REG_WDEVBT_BASE + 0x00CC)
#define WDEV_BTCMD_KOFFSET (BIT(29))
#define WDEV_BTCMD_KOFFSET_S 29
#define WDEV_BTCMD_TRUNCATED_PAGE (BIT(28))
#define WDEV_BTCMD_TRUNCATED_PAGE_S 28
#define WDEV_BTCMD_KNUDGE 0x0000001F
#define WDEV_BTCMD_KNUDGE_S 23
#define WDEV_BTCMD_INTERLACED 0x0000001F
#define WDEV_BTCMD_INTERLACED_S 18
#define WDEV_BTINQEXT_LINK_ADDR 0x0003FFFF
#define WDEV_BTINQEXT_LINK_ADS 0

#define WDEVBT_INQ_EXTEND_CONF (REG_WDEVBT_BASE + 0x00D0)
#define WDEV_BTINQEXT_LEN 0x000007FF
#define WDEV_BTINQEXT_LEN_S 0

#define WDEVBT_INQ_EXTEND_HEAD (REG_WDEVBT_BASE + 0x00D4)
#define WDEV_BTINQEXT_PAYLOAD_HEAD 0x0000FFFF
#define WDEV_BTINQEXT_PAYLOAD_HEAD_S 10
#define WDEV_BTINQEXT_PACKET_HEAD 0x000003FF
#define WDEV_BTINQEXT_PACKET_HEAD_S 0

#define WDEVBT_CMD0_CONF0 (REG_WDEVBT_BASE + 0x00D8)
#define WDEV_BTCMD_PAGE_RETRY_TIME 0x0000000F
#define WDEV_BTCMD_PAGE_RETRY_TIME_S 28
#define WDEV_BTCMD_PAGESCAN_RETRY_TIME 0x0000000F
#define WDEV_BTCMD_PAGESCAN_RETRY_TIME_S 24
#define WDEV_BTCMD_RS2M_RETRY_TIME 0x0000000F
#define WDEV_BTCMD_RS2M_RETRY_TIME_S 20
#define WDEV_BTCMD_RS2S_RETRY_TIME 0x0000000F
#define WDEV_BTCMD_RS2S_RETRY_TIME_S 16
#define WDEV_BTCMD_PAGESCAN_FORCE_RETRY (BIT(15))
#define WDEV_BTCMD_PAGESCAN_FORCE_RETRY_S 15
#define WDEV_BTCMD_RS2S_FORCE_RETRY (BIT(14))
#define WDEV_BTCMD_RS2S_FORCE_RETRY_S 14
#define WDEV_BTCMD_TIMER_DELAY_US 0x000003FF
#define WDEV_BTCMD_TIMER_DELAY_US_S 0

#define WDEVBT_CMD0_CONF2 (REG_WDEVBT_BASE + 0x00DC)
#define WDEV_BTCMD_TIMER_SEL 0x0000000F
#define WDEV_BTCMD_TIMER_SEL_S 28
#define WDEV_BTCMD_TIMER 0x0FFFFFFF
#define WDEV_BTCMD_TIMER_S 0

#define WDEVBT_FHS (REG_WDEVBT_BASE + 0x00E0)
#define WDEV_BTFHS_COD 0x00FFFFFF
#define WDEV_BTFHS_COD_S 8
#define WDEV_BTFHS_LT 0x00000007
#define WDEV_BTFHS_LT_S 4
#define WDEV_BTFHS_SR 0x00000003
#define WDEV_BTFHS_SR_S 1
#define WDEV_BTFHS_EIR (BIT(0))
#define WDEV_BTFHS_EIR_S 0

#define WDEVBT_CLKE_OFFSET (REG_WDEVBT_BASE + 0x00E4)
#define WDEV_BTCLKE_OFFSET 0x0FFFFFFF
#define WDEV_BTCLKE_OFFSET_S 0

#define WDEVBT_RS2S_OFFSET (REG_WDEVBT_BASE + 0x00E8)
#define WDEV_BTRS2S_625OFFSET_OPT (BIT(11))
#define WDEV_BTRS2S_625OFFSET_OPT_S 11
#define WDEV_BTRS2S_OFFSET 0x000007FF
#define WDEV_BTRS2S_OFFSET_S 0

#define WDEVBT_CLKN_OFFSET_S (REG_WDEVBT_BASE + 0x00EC)
#define WDEV_BTCLKN_OFFSET_S 0x000007FF
#define WDEV_BTCLKN_OFFSET_S_S 0

#define WDEVBT_RDDELAY (REG_WDEVBT_BASE + 0x00F0)
#define WDEV_BTTXRADIO_DELAY 0x000001FF
#define WDEV_BTTXRADIO_DELAY_S 16
#define WDEV_BTRXRADIO_DELAY 0x000001FF
#define WDEV_BTRXRADIO_DELAY_S 0

#define WDEVBT_BBDELAY (REG_WDEVBT_BASE + 0x00F4)
#define WDEV_BTTXSTART_DELAY 0x0000003F
#define WDEV_BTTXSTART_DELAY_S 8
#define WDEV_BTRXSTART_DELAY 0x0000003F
#define WDEV_BTRXSTART_DELAY_S 0

#define WDEVBT_RXAC_TIMER (REG_WDEVBT_BASE + 0x00F8)
#define WDEV_BTRXAC_DELAY 0x000001FF
#define WDEV_BTRXAC_DELAY_S 0

#define INT_ENA_WDEVBT (REG_WDEVBT_BASE + 0x00FC)
#define WDEV_BTRX_AC_SUC_INT_ENA (BIT(28))
#define WDEV_BTRX_AC_SUC_INT_ENA_S 28
#define WDEV_BTCLK_US_TIMER_INT_ENA (BIT(27))
#define WDEV_BTCLK_US_TIMER_INT_ENA_S 27
#define WDEV_BTCLKN_TIMER_INT_ENA (BIT(26))
#define WDEV_BTCLKN_TIMER_INT_ENA_S 26
#define WDEV_BTCLKN_SLOT_INT_ENA (BIT(25))
#define WDEV_BTCLKN_SLOT_INT_ENA_S 25
#define WDEV_BTCLKS_TIMER_INT_ENA (BIT(24))
#define WDEV_BTCLKS_TIMER_INT_ENA_S 24
#define WDEV_BTCLKS_SLOT_INT_ENA (BIT(23))
#define WDEV_BTCLKS_SLOT_INT_ENA_S 23
#define WDEV_BTCLKS1_TIMER_INT_ENA (BIT(22))
#define WDEV_BTCLKS1_TIMER_INT_ENA_S 22
#define WDEV_BTCLKS1_SLOT_INT_ENA (BIT(21))
#define WDEV_BTCLKS1_SLOT_INT_ENA_S 21
#define WDEV_BTCLKS2_TIMER_INT_ENA (BIT(20))
#define WDEV_BTCLKS2_TIMER_INT_ENA_S 20
#define WDEV_BTCLKS2_SLOT_INT_ENA (BIT(19))
#define WDEV_BTCLKS2_SLOT_INT_ENA_S 19
#define WDEV_BTCLKS3_TIMER_INT_ENA (BIT(18))
#define WDEV_BTCLKS3_TIMER_INT_ENA_S 18
#define WDEV_BTCLKS3_SLOT_INT_ENA (BIT(17))
#define WDEV_BTCLKS3_SLOT_INT_ENA_S 17
#define WDEV_BTCLKE_TIMER_INT_ENA (BIT(16))
#define WDEV_BTCLKE_TIMER_INT_ENA_S 16
#define WDEV_BTCLKE_SLOT_INT_ENA (BIT(15))
#define WDEV_BTCLKE_SLOT_INT_ENA_S 15
#define WDEV_BTTX_WD_INT_ENA (BIT(14))
#define WDEV_BTTX_WD_INT_ENA_S 14
#define WDEV_BTRX_WD_INT_ENA (BIT(13))
#define WDEV_BTRX_WD_INT_ENA_S 13
#define WDEV_BTFREQ_START_INT_ENA (BIT(12))
#define WDEV_BTFREQ_START_INT_ENA_S 12
#define WDEV_BTCMD_START_INT_ENA (BIT(11))
#define WDEV_BTCMD_START_INT_ENA_S 11
#define WDEV_BTCMD_END_INT_ENA (BIT(10))
#define WDEV_BTCMD_END_INT_ENA_S 10
#define WDEV_BTTXCOL_INT_ENA (BIT(9))
#define WDEV_BTTXCOL_INT_ENA_S 9
#define WDEV_BTRXCOL_INT_ENA (BIT(8))
#define WDEV_BTRXCOL_INT_ENA_S 8
#define WDEV_BTTXEND_DATA_SUC_INT_ENA (BIT(7))
#define WDEV_BTTXEND_DATA_SUC_INT_ENA_S 7
#define WDEV_BTTXEND_SUC_INT_ENA (BIT(6))
#define WDEV_BTTXEND_SUC_INT_ENA_S 6
#define WDEV_BTRXEND_DATA_SUC_INT_ENA (BIT(5))
#define WDEV_BTRXEND_DATA_SUC_INT_ENA_S 5
#define WDEV_BTRXEND_SUC_INT_ENA (BIT(4))
#define WDEV_BTRXEND_SUC_INT_ENA_S 4
#define WDEV_BTRXSTART_INT_ENA (BIT(3))
#define WDEV_BTRXSTART_INT_ENA_S 3
#define WDEV_BTTXSTART_INT_ENA (BIT(2))
#define WDEV_BTTXSTART_INT_ENA_S 2
#define WDEV_BTRXEND_INT_ENA (BIT(1))
#define WDEV_BTRXEND_INT_ENA_S 1
#define WDEV_BTTXEND_INT_ENA (BIT(0))
#define WDEV_BTTXEND_INT_ENA_S 0

#define INT_RAW_WDEVBT (REG_WDEVBT_BASE + 0x0100)
#define WDEV_BTRX_AC_SUC_INT_RAW (BIT(28))
#define WDEV_BTRX_AC_SUC_INT_RAW_S 28
#define WDEV_BTCLK_US_TIMER_INT_RAW (BIT(27))
#define WDEV_BTCLK_US_TIMER_INT_RAW_S 27
#define WDEV_BTCLKN_TIMER_INT_RAW (BIT(26))
#define WDEV_BTCLKN_TIMER_INT_RAW_S 26
#define WDEV_BTCLKN_SLOT_INT_RAW (BIT(25))
#define WDEV_BTCLKN_SLOT_INT_RAW_S 25
#define WDEV_BTCLKS_TIMER_INT_RAW (BIT(24))
#define WDEV_BTCLKS_TIMER_INT_RAW_S 24
#define WDEV_BTCLKS_SLOT_INT_RAW (BIT(23))
#define WDEV_BTCLKS_SLOT_INT_RAW_S 23
#define WDEV_BTCLKS1_TIMER_INT_RAW (BIT(22))
#define WDEV_BTCLKS1_TIMER_INT_RAW_S 22
#define WDEV_BTCLKS1_SLOT_INT_RAW (BIT(21))
#define WDEV_BTCLKS1_SLOT_INT_RAW_S 21
#define WDEV_BTCLKS2_TIMER_INT_RAW (BIT(20))
#define WDEV_BTCLKS2_TIMER_INT_RAW_S 20
#define WDEV_BTCLKS2_SLOT_INT_RAW (BIT(19))
#define WDEV_BTCLKS2_SLOT_INT_RAW_S 19
#define WDEV_BTCLKS3_TIMER_INT_RAW (BIT(18))
#define WDEV_BTCLKS3_TIMER_INT_RAW_S 18
#define WDEV_BTCLKS3_SLOT_INT_RAW (BIT(17))
#define WDEV_BTCLKS3_SLOT_INT_RAW_S 17
#define WDEV_BTCLKE_TIMER_INT_RAW (BIT(16))
#define WDEV_BTCLKE_TIMER_INT_RAW_S 16
#define WDEV_BTCLKE_SLOT_INT_RAW (BIT(15))
#define WDEV_BTCLKE_SLOT_INT_RAW_S 15
#define WDEV_BTTX_WD_INT_RAW (BIT(14))
#define WDEV_BTTX_WD_INT_RAW_S 14
#define WDEV_BTRX_WD_INT_RAW (BIT(13))
#define WDEV_BTRX_WD_INT_RAW_S 13
#define WDEV_BTFREQ_START_INT_RAW (BIT(12))
#define WDEV_BTFREQ_START_INT_RAW_S 12
#define WDEV_BTCMD_START_INT_RAW (BIT(11))
#define WDEV_BTCMD_START_INT_RAW_S 11
#define WDEV_BTCMD_END_INT_RAW (BIT(10))
#define WDEV_BTCMD_END_INT_RAW_S 10
#define WDEV_BTTXCOL_INT_RAW (BIT(9))
#define WDEV_BTTXCOL_INT_RAW_S 9
#define WDEV_BTRXCOL_INT_RAW (BIT(8))
#define WDEV_BTRXCOL_INT_RAW_S 8
#define WDEV_BTTXEND_DATA_SUC_INT_RAW (BIT(7))
#define WDEV_BTTXEND_DATA_SUC_INT_RAW_S 7
#define WDEV_BTTXEND_SUC_INT_RAW (BIT(6))
#define WDEV_BTTXEND_SUC_INT_RAW_S 6
#define WDEV_BTRXEND_DATA_SUC_INT_RAW (BIT(5))
#define WDEV_BTRXEND_DATA_SUC_INT_RAW_S 5
#define WDEV_BTRXEND_SUC_INT_RAW (BIT(4))
#define WDEV_BTRXEND_SUC_INT_RAW_S 4
#define WDEV_BTRXSTART_INT_RAW (BIT(3))
#define WDEV_BTRXSTART_INT_RAW_S 3
#define WDEV_BTTXSTART_INT_RAW (BIT(2))
#define WDEV_BTTXSTART_INT_RAW_S 2
#define WDEV_BTRXEND_INT_RAW (BIT(1))
#define WDEV_BTRXEND_INT_RAW_S 1
#define WDEV_BTTXEND_INT_RAW (BIT(0))
#define WDEV_BTTXEND_INT_RAW_S 0

#define INT_ST_WDEVBT (REG_WDEVBT_BASE + 0x0104)
#define WDEV_BTRX_AC_SUC_INT_ST (BIT(28))
#define WDEV_BTRX_AC_SUC_INT_ST_S 28
#define WDEV_BTCLK_US_TIMER_INT_ST (BIT(27))
#define WDEV_BTCLK_US_TIMER_INT_ST_S 27
#define WDEV_BTCLKN_TIMER_INT_ST (BIT(26))
#define WDEV_BTCLKN_TIMER_INT_ST_S 26
#define WDEV_BTCLKN_SLOT_INT_ST (BIT(25))
#define WDEV_BTCLKN_SLOT_INT_ST_S 25
#define WDEV_BTCLKS_TIMER_INT_ST (BIT(24))
#define WDEV_BTCLKS_TIMER_INT_ST_S 24
#define WDEV_BTCLKS_SLOT_INT_ST (BIT(23))
#define WDEV_BTCLKS_SLOT_INT_ST_S 23
#define WDEV_BTCLKS1_TIMER_INT_ST (BIT(22))
#define WDEV_BTCLKS1_TIMER_INT_ST_S 22
#define WDEV_BTCLKS1_SLOT_INT_ST (BIT(21))
#define WDEV_BTCLKS1_SLOT_INT_ST_S 21
#define WDEV_BTCLKS2_TIMER_INT_ST (BIT(20))
#define WDEV_BTCLKS2_TIMER_INT_ST_S 20
#define WDEV_BTCLKS2_SLOT_INT_ST (BIT(19))
#define WDEV_BTCLKS2_SLOT_INT_ST_S 19
#define WDEV_BTCLKS3_TIMER_INT_ST (BIT(18))
#define WDEV_BTCLKS3_TIMER_INT_ST_S 18
#define WDEV_BTCLKS3_SLOT_INT_ST (BIT(17))
#define WDEV_BTCLKS3_SLOT_INT_ST_S 17
#define WDEV_BTCLKE_TIMER_INT_ST (BIT(16))
#define WDEV_BTCLKE_TIMER_INT_ST_S 16
#define WDEV_BTCLKE_SLOT_INT_ST (BIT(15))
#define WDEV_BTCLKE_SLOT_INT_ST_S 15
#define WDEV_BTTX_WD_INT_ST (BIT(14))
#define WDEV_BTTX_WD_INT_ST_S 14
#define WDEV_BTRX_WD_INT_ST (BIT(13))
#define WDEV_BTRX_WD_INT_ST_S 13
#define WDEV_BTFREQ_START_INT_ST (BIT(12))
#define WDEV_BTFREQ_START_INT_ST_S 12
#define WDEV_BTCMD_START_INT_ST (BIT(11))
#define WDEV_BTCMD_START_INT_ST_S 11
#define WDEV_BTCMD_END_INT_ST (BIT(10))
#define WDEV_BTCMD_END_INT_ST_S 10
#define WDEV_BTTXCOL_INT_ST (BIT(9))
#define WDEV_BTTXCOL_INT_ST_S 9
#define WDEV_BTRXCOL_INT_ST (BIT(8))
#define WDEV_BTRXCOL_INT_ST_S 8
#define WDEV_BTTXEND_DATA_SUC_INT_ST (BIT(7))
#define WDEV_BTTXEND_DATA_SUC_INT_ST_S 7
#define WDEV_BTTXEND_SUC_INT_ST (BIT(6))
#define WDEV_BTTXEND_SUC_INT_ST_S 6
#define WDEV_BTRXEND_DATA_SUC_INT_ST (BIT(5))
#define WDEV_BTRXEND_DATA_SUC_INT_ST_S 5
#define WDEV_BTRXEND_SUC_INT_ST (BIT(4))
#define WDEV_BTRXEND_SUC_INT_ST_S 4
#define WDEV_BTRXSTART_INT_ST (BIT(3))
#define WDEV_BTRXSTART_INT_ST_S 3
#define WDEV_BTTXSTART_INT_ST (BIT(2))
#define WDEV_BTTXSTART_INT_ST_S 2
#define WDEV_BTRXEND_INT_ST (BIT(1))
#define WDEV_BTRXEND_INT_ST_S 1
#define WDEV_BTTXEND_INT_ST (BIT(0))
#define WDEV_BTTXEND_INT_ST_S 0

#define INT_CLR_WDEVBT (REG_WDEVBT_BASE + 0x0108)
#define WDEV_BTRX_AC_SUC_INT_CLR (BIT(28))
#define WDEV_BTRX_AC_SUC_INT_CLR_S 28
#define WDEV_BTCLK_US_TIMER_INT_CLR (BIT(27))
#define WDEV_BTCLK_US_TIMER_INT_CLR_S 27
#define WDEV_BTCLKN_TIMER_INT_CLR (BIT(26))
#define WDEV_BTCLKN_TIMER_INT_CLR_S 26
#define WDEV_BTCLKN_SLOT_INT_CLR (BIT(25))
#define WDEV_BTCLKN_SLOT_INT_CLR_S 25
#define WDEV_BTCLKS_TIMER_INT_CLR (BIT(24))
#define WDEV_BTCLKS_TIMER_INT_CLR_S 24
#define WDEV_BTCLKS_SLOT_INT_CLR (BIT(23))
#define WDEV_BTCLKS_SLOT_INT_CLR_S 23
#define WDEV_BTCLKS1_TIMER_INT_CLR (BIT(22))
#define WDEV_BTCLKS1_TIMER_INT_CLR_S 22
#define WDEV_BTCLKS1_SLOT_INT_CLR (BIT(21))
#define WDEV_BTCLKS1_SLOT_INT_CLR_S 21
#define WDEV_BTCLKS2_TIMER_INT_CLR (BIT(20))
#define WDEV_BTCLKS2_TIMER_INT_CLR_S 20
#define WDEV_BTCLKS2_SLOT_INT_CLR (BIT(19))
#define WDEV_BTCLKS2_SLOT_INT_CLR_S 19
#define WDEV_BTCLKS3_TIMER_INT_CLR (BIT(18))
#define WDEV_BTCLKS3_TIMER_INT_CLR_S 18
#define WDEV_BTCLKS3_SLOT_INT_CLR (BIT(17))
#define WDEV_BTCLKS3_SLOT_INT_CLR_S 17
#define WDEV_BTCLKE_TIMER_INT_CLR (BIT(16))
#define WDEV_BTCLKE_TIMER_INT_CLR_S 16
#define WDEV_BTCLKE_SLOT_INT_CLR (BIT(15))
#define WDEV_BTCLKE_SLOT_INT_CLR_S 15
#define WDEV_BTTX_WD_INT_CLR (BIT(14))
#define WDEV_BTTX_WD_INT_CLR_S 14
#define WDEV_BTRX_WD_INT_CLR (BIT(13))
#define WDEV_BTRX_WD_INT_CLR_S 13
#define WDEV_BTFREQ_START_INT_CLR (BIT(12))
#define WDEV_BTFREQ_START_INT_CLR_S 12
#define WDEV_BTCMD_START_INT_CLR (BIT(11))
#define WDEV_BTCMD_START_INT_CLR_S 11
#define WDEV_BTCMD_END_INT_CLR (BIT(10))
#define WDEV_BTCMD_END_INT_CLR_S 10
#define WDEV_BTTXCOL_INT_CLR (BIT(9))
#define WDEV_BTTXCOL_INT_CLR_S 9
#define WDEV_BTRXCOL_INT_CLR (BIT(8))
#define WDEV_BTRXCOL_INT_CLR_S 8
#define WDEV_BTTXEND_DATA_SUC_INT_CLR (BIT(7))
#define WDEV_BTTXEND_DATA_SUC_INT_CLR_S 7
#define WDEV_BTTXEND_SUC_INT_CLR (BIT(6))
#define WDEV_BTTXEND_SUC_INT_CLR_S 6
#define WDEV_BTRXEND_DATA_SUC_INT_CLR (BIT(5))
#define WDEV_BTRXEND_DATA_SUC_INT_CLR_S 5
#define WDEV_BTRXEND_SUC_INT_CLR (BIT(4))
#define WDEV_BTRXEND_SUC_INT_CLR_S 4
#define WDEV_BTRXSTART_INT_CLR (BIT(3))
#define WDEV_BTRXSTART_INT_CLR_S 3
#define WDEV_BTTXSTART_INT_CLR (BIT(2))
#define WDEV_BTTXSTART_INT_CLR_S 2
#define WDEV_BTRXEND_INT_CLR (BIT(1))
#define WDEV_BTRXEND_INT_CLR_S 1
#define WDEV_BTTXEND_INT_CLR (BIT(0))
#define WDEV_BTTXEND_INT_CLR_S 0

#define WDEVBT_RXMODE (REG_WDEVBT_BASE + 0x010C)
#define WDEV_BTRX_ENA_FRC (BIT(31))
#define WDEV_BTRX_ENA_FRC_S 31
#define WDEV_BTRX_ENA_SUC (BIT(30))
#define WDEV_BTRX_ENA_SUC_S 30
#define WDEV_BTRX_ENA_ANY (BIT(29))
#define WDEV_BTRX_ENA_ANY_S 29

#define WDEVBT_RXBASE (REG_WDEVBT_BASE + 0x0110)
#define WDEV_BTRX_BASE 0xFFFFFFFF
#define WDEV_BTRX_BASE_S 0

#define WDEVBTRXBUFDSCR_LAST (REG_WDEVBT_BASE + 0x0114)
#define WDEV_BTLAST_RXBUFDSCR 0xFFFFFFFF
#define WDEV_BTLAST_RXBUFDSCR_S 0

#define WDEVBTRXBUFBK_CNT (REG_WDEVBT_BASE + 0x0118)
#define WDEV_BTLAST_RXBUFBK_CNT 0x000000FF
#define WDEV_BTLAST_RXBUFBK_CNT_S 0

#define WDEVBTRXBUFDSCR_START (REG_WDEVBT_BASE + 0x011C)
#define WDEV_BTSTART_RXBUFDSCR 0xFFFFFFFF
#define WDEV_BTSTART_RXBUFDSCR_S 0

#define WDEVBT_RXPMD (REG_WDEVBT_BASE + 0x0120)
#define WDEV_BTRXCOL_MAP 0x0000001F
#define WDEV_BTRXCOL_MAP_S 13
#define WDEV_BTRXSTART_MAP 0x0000001F
#define WDEV_BTRXSTART_MAP_S 8
#define WDEV_BTRXEND_STATE 0x000000FF
#define WDEV_BTRXEND_STATE_S 0

#define WDEVBT_CODE_OPTION (REG_WDEVBT_BASE + 0x0124)
#define WDEV_BTRX_DEFEC23_FIX_ENA (BIT(9))
#define WDEV_BTRX_DEFEC23_FIX_ENA_S 9
#define WDEV_BTTX_AUTO_FRAMING (BIT(8))
#define WDEV_BTTX_AUTO_FRAMING_S 8
#define WDEV_BTRX_FORCE_NOFEC (BIT(7))
#define WDEV_BTRX_FORCE_NOFEC_S 7
#define WDEV_BTTX_FORCE_NOFEC (BIT(6))
#define WDEV_BTTX_FORCE_NOFEC_S 6
#define WDEV_BTRX_FORCE_FEC13 (BIT(5))
#define WDEV_BTRX_FORCE_FEC13_S 5
#define WDEV_BTTX_FORCE_FEC13 (BIT(4))
#define WDEV_BTTX_FORCE_FEC13_S 4
#define WDEV_BTRX_FORCE_FEC23 (BIT(3))
#define WDEV_BTRX_FORCE_FEC23_S 3
#define WDEV_BTTX_FORCE_FEC23 (BIT(2))
#define WDEV_BTTX_FORCE_FEC23_S 2
#define WDEV_BTRX_FORCE_NOWHITE (BIT(1))
#define WDEV_BTRX_FORCE_NOWHITE_S 1
#define WDEV_BTTX_FORCE_NOWHITE (BIT(0))
#define WDEV_BTTX_FORCE_NOWHITE_S 0

#define WDEVBT_RXABORT (REG_WDEVBT_BASE + 0x0128)
#define WDEV_BTRX_LTADDRERR_ENA (BIT(31))
#define WDEV_BTRX_LTADDRERR_ENA_S 31
#define WDEV_BTRX_DEFEC23ERR_NUM 0x000003FF
#define WDEV_BTRX_DEFEC23ERR_NUM_S 12
#define WDEV_BTRX_DEFEC13ERR_NUM 0x000007FF
#define WDEV_BTRX_DEFEC13ERR_NUM_S 0

#define WDEVBT_RXDEFEC_PMD (REG_WDEVBT_BASE + 0x012C)
#define WDEV_BTRX_DEFEC13ERR_CNT 0x000007FF
#define WDEV_BTRX_DEFEC13ERR_CNT_S 20
#define WDEV_BTRX_DEFEC23ERR_CNT 0x000003FF
#define WDEV_BTRX_DEFEC23ERR_CNT_S 10
#define WDEV_BTRX_DEFEC23ERR1BIT_CNT 0x000003FF
#define WDEV_BTRX_DEFEC23ERR1BIT_CNT_S 0

#define WDEVBT_RXAC_TO (REG_WDEVBT_BASE + 0x0130)
#define WDEV_BTRXAC_TIMEOUT_INQ 0x000000FF
#define WDEV_BTRXAC_TIMEOUT_INQ_S 8
#define WDEV_BTRXAC_TIMEOUT_CON 0x000000FF
#define WDEV_BTRXAC_TIMEOUT_CON_S 0

#define WDEVBT_FREQ (REG_WDEVBT_BASE + 0x0134)
#define WDEV_BT_CUR_FREQ 0x0000007F
#define WDEV_BT_CUR_FREQ_S 24
#define WDEV_BTFREQ_DEBUG 0x0000007F
#define WDEV_BTFREQ_DEBUG_S 16
#define WDEV_BT_AFH_ENA (BIT(0))
#define WDEV_BT_AFH_ENA_S 0

#define WDEVBT_M0BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0138)
#define WDEV_BTM0BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM0BADFREQ_MAP0_S 0

#define WDEVBT_M0BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x013C)
#define WDEV_BTM0BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM0BADFREQ_MAP1_S 0

#define WDEVBT_M0BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0140)
#define WDEV_BTM0BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM0BADFREQ_MAP2_S 0

#define WDEVBT_M1BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0144)
#define WDEV_BTM1BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM1BADFREQ_MAP0_S 0

#define WDEVBT_M1BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0148)
#define WDEV_BTM1BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM1BADFREQ_MAP1_S 0

#define WDEVBT_M1BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x014C)
#define WDEV_BTM1BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM1BADFREQ_MAP2_S 0

#define WDEVBT_M2BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0150)
#define WDEV_BTM2BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM2BADFREQ_MAP0_S 0

#define WDEVBT_M2BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0154)
#define WDEV_BTM2BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM2BADFREQ_MAP1_S 0

#define WDEVBT_M2BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0158)
#define WDEV_BTM2BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM2BADFREQ_MAP2_S 0

#define WDEVBT_M3BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x015C)
#define WDEV_BTM3BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM3BADFREQ_MAP0_S 0

#define WDEVBT_M3BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0160)
#define WDEV_BTM3BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM3BADFREQ_MAP1_S 0

#define WDEVBT_M3BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0164)
#define WDEV_BTM3BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM3BADFREQ_MAP2_S 0

#define WDEVBT_M4BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0168)
#define WDEV_BTM4BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM4BADFREQ_MAP0_S 0

#define WDEVBT_M4BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x016C)
#define WDEV_BTM4BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM4BADFREQ_MAP1_S 0

#define WDEVBT_M4BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0170)
#define WDEV_BTM4BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM4BADFREQ_MAP2_S 0

#define WDEVBT_M5BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0174)
#define WDEV_BTM5BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM5BADFREQ_MAP0_S 0

#define WDEVBT_M5BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0178)
#define WDEV_BTM5BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM5BADFREQ_MAP1_S 0

#define WDEVBT_M5BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x017C)
#define WDEV_BTM5BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM5BADFREQ_MAP2_S 0

#define WDEVBT_M6BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0180)
#define WDEV_BTM6BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM6BADFREQ_MAP0_S 0

#define WDEVBT_M6BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0184)
#define WDEV_BTM6BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM6BADFREQ_MAP1_S 0

#define WDEVBT_M6BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0188)
#define WDEV_BTM6BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM6BADFREQ_MAP2_S 0

#define WDEVBT_M7BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x018C)
#define WDEV_BTM7BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTM7BADFREQ_MAP0_S 0

#define WDEVBT_M7BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x0190)
#define WDEV_BTM7BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTM7BADFREQ_MAP1_S 0

#define WDEVBT_M7BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x0194)
#define WDEV_BTM7BADFREQ_MAP2 0x00007FFF
#define WDEV_BTM7BADFREQ_MAP2_S 0

#define WDEVBT_S0BADFEQ_MAP0 (REG_WDEVBT_BASE + 0x0198)
#define WDEV_BTS0BADFREQ_MAP0 0xFFFFFFFF
#define WDEV_BTS0BADFREQ_MAP0_S 0

#define WDEVBT_S0BADFEQ_MAP1 (REG_WDEVBT_BASE + 0x019C)
#define WDEV_BTS0BADFREQ_MAP1 0xFFFFFFFF
#define WDEV_BTS0BADFREQ_MAP1_S 0

#define WDEVBT_S0BADFEQ_MAP2 (REG_WDEVBT_BASE + 0x01A0)
#define WDEV_BTS0BADFREQ_MAP2 0x00007FFF
#define WDEV_BTS0BADFREQ_MAP2_S 0

#define WDEVBT_CRYPT_CONF (REG_WDEVBT_BASE + 0x01A4)
#define WDEV_BTCRYPT_TX_ENA (BIT(31))
#define WDEV_BTCRYPT_TX_ENA_S 31
#define WDEV_BTCRYPT_RX_ENA (BIT(30))
#define WDEV_BTCRYPT_RX_ENA_S 30
#define WDEV_BTSCO_ENC_MODE (BIT(29))
#define WDEV_BTSCO_ENC_MODE_S 29

#define WDEVBT_CCM_PCNT0 (REG_WDEVBT_BASE + 0x01A8)
#define WDEV_BTCCM_PCNT0 0xFFFFFFFF
#define WDEV_BTCCM_PCNT0_S 0

#define WDEVBT_CCM_PCNT1 (REG_WDEVBT_BASE + 0x01AC)
#define WDEV_BTCCM_DAYCNT 0x000007FF
#define WDEV_BTCCM_DAYCNT_S 4
#define WDEV_BTCCM_PCNT1 0x0000000F
#define WDEV_BTCCM_PCNT1_S 0

#define WDEVBT_ULAP_DEBUG (REG_WDEVBT_BASE + 0x01B0)
#define WDEV_BT_UAP_DEBUG 0x000000FF
#define WDEV_BT_UAP_DEBUG_S 24
#define WDEV_BT_LAP_DEBUG 0x00FFFFFF
#define WDEV_BT_LAP_DEBUG_S 0

#define WDEVBT_NAP_DEBUG (REG_WDEVBT_BASE + 0x01B4)
#define WDEV_BT_NAP_DEBUG 0x0000FFFF
#define WDEV_BT_NAP_DEBUG_S 0

#define WDEVBT_CLK_DEBUG (REG_WDEVBT_BASE + 0x01B8)
#define WDEV_BTCLK_DEBUG 0x0FFFFFFF
#define WDEV_BTCLK_DEBUG_S 0

#define WDEVBT_DEBUG_MODE (REG_WDEVBT_BASE + 0x01BC)
#define WDEV_BTRX_VALID_DEBUG (BIT(31))
#define WDEV_BTRX_VALID_DEBUG_S 31
#define WDEV_BTTX_VALID_DEBUG (BIT(30))
#define WDEV_BTTX_VALID_DEBUG_S 30
#define WDEV_BTULAP_DEBUG_ENA (BIT(29))
#define WDEV_BTULAP_DEBUG_ENA_S 29
#define WDEV_BTCLK_DEBUG_ENA (BIT(28))
#define WDEV_BTCLK_DEBUG_ENA_S 28
#define WDEV_BTCLK_DEBUG_FRZ (BIT(27))
#define WDEV_BTCLK_DEBUG_FRZ_S 27
#define WDEV_BTTX_BITSTREAM (BIT(26))
#define WDEV_BTTX_BITSTREAM_S 26
#define WDEV_BTFREQ_DEBUG_ENA (BIT(24))
#define WDEV_BTFREQ_DEBUG_ENA_S 24
#define WDEV_BTEDA_DEBUG 0x00FFFFFF
#define WDEV_BTEDA_DEBUG_S 0

#define WDEVBT_SEC_MODE (REG_WDEVBT_BASE + 0x01C0)
#define WDEV_BTSEC_MODE_OPTION 0x00000007
#define WDEV_BTSEC_MODE_OPTION_S 29
#define WDEV_BTSEC_BYPASS_OPTION 0x00000007
#define WDEV_BTSEC_BYPASS_OPTION_S 25

#define WDEVBT_SEC_KMEM_VALID (REG_WDEVBT_BASE + 0x01C4)
#define WDEV_BTSEC_KMEM_VALID 0xFFFFFFFF
#define WDEV_BTSEC_KMEM_VALID_S 0

#define WDEVBT_SEC_KMEM_KMOD (REG_WDEVBT_BASE + 0x01C8)
#define WDEV_BTSEC_KMEM_KMOD 0xFFFFFFFF
#define WDEV_BTSEC_KMEM_KMOD_S 0

#define WDEVBT_WATCHDOG (REG_WDEVBT_BASE + 0x01CC)
#define WDEV_BTTX_WD_EN (BIT(31))
#define WDEV_BTTX_WD_EN_S 31
#define WDEV_BTTX_SOFT_RESET (BIT(30))
#define WDEV_BTTX_SOFT_RESET_S 30
#define WDEV_BTTX_WD_SET 0x000000FF
#define WDEV_BTTX_WD_SET_S 22
#define WDEV_BTRX_WD_EN (BIT(21))
#define WDEV_BTRX_WD_EN_S 21
#define WDEV_BTRX_SOFT_RESET (BIT(20))
#define WDEV_BTRX_SOFT_RESET_S 20
#define WDEV_BTRX_WD_SET 0x000000FF
#define WDEV_BTRX_WD_SET_S 12

#define WDEVBT_RXLEN_PROTECT (REG_WDEVBT_BASE + 0x01D0)
#define WDEV_BT_RXLEN_PROTECT_EN (BIT(31))
#define WDEV_BT_RXLEN_PROTECT_EN_S 31
#define WDEV_BT_RXLEN_PROTECT_MODE 0x00000003
#define WDEV_BT_RXLEN_PROTECT_MODE_S 29

#define WDEVBT_AUDIO (REG_WDEVBT_BASE + 0x01D4)
#define WDEV_BTAUDIO_SCO_EN (BIT(31))
#define WDEV_BTAUDIO_SCO_EN_S 31
#define WDEV_BTAUDIO_RX_MOD (BIT(30))
#define WDEV_BTAUDIO_RX_MOD_S 30
#define WDEV_BTAUDIO_SCO_TYPE 0x0000000F
#define WDEV_BTAUDIO_SCO_TYPE_S 26
#define WDEV_BTAUDIO_LT 0x00000007
#define WDEV_BTAUDIO_LT_S 23

#define WDEVBT_SCO_RXBBERROR_MASK (REG_WDEVBT_BASE + 0x01D8)
#define WDEV_BTSCO_PWR_RD_MASK (BIT(31))
#define WDEV_BTSCO_PWR_RD_MASK_S 31
#define WDEV_BTSCO_PWR_MAX_MASK (BIT(30))
#define WDEV_BTSCO_PWR_MAX_MASK_S 30
#define WDEV_BTSCO_PACEND_MASK (BIT(29))
#define WDEV_BTSCO_PACEND_MASK_S 29

#define WDEVBT_CLOCK_GATING (REG_WDEVBT_BASE + 0x01DC)
#define WDEV_BTMAC_CLK_EN (BIT(31))
#define WDEV_BTMAC_CLK_EN_S 31

#define WDEVBT_RXDIAG0 (REG_WDEVBT_BASE + 0x01E0)
#define WDEV_BTRX_DIAG0 0xFFFFFFFF
#define WDEV_BTRX_DIAG0_S 0

#define WDEVBT_TXDIAG0 (REG_WDEVBT_BASE + 0x01E4)
#define WDEV_BTTX_DIAG0 0xFFFFFFFF
#define WDEV_BTTX_DIAG0_S 0

#define WDEVBT_BRCDIAG0 (REG_WDEVBT_BASE + 0x01E8)
#define WDEV_BTBRC_DIAG0 0xFFFFFFFF
#define WDEV_BTBRC_DIAG0_S 0

#define WDEVBT_LCDIAG0 (REG_WDEVBT_BASE + 0x01EC)
#define WDEV_BTLC_DIAG0 0xFFFFFFFF
#define WDEV_BTLC_DIAG0_S 0

#define WDEVBTDATA (REG_WDEVBT_BASE + 0x03F8)
#define WDEV_BTMAC_DATE 0x0FFFFFFF
#define WDEV_BTMAC_DATE_S 0
#define WDEV_BTMAC_DATE_VERSION 0x1603280
