
#define BT_BITS_GFSK_MODULATOR_CTRL_REG (REG_BT_BASE + 0x0000)
#define BT_BITS_GFSK_MODULATOR_CTRL_NOUSE 0x01FFFFFF
#define BT_BITS_GFSK_MODULATOR_CTRL_NOUSE_S 7
#define BT_BITS_LE_EN (BIT(6))
#define BT_BITS_LE_EN_S 6
#define BT_BITS_MODU_INDX 0x0000000F
#define BT_BITS_MODU_INDX_S 2
#define BT_BITS_NEGATE_GFSK_SYMBOL (BIT(1))
#define BT_BITS_NEGATE_GFSK_SYMBOL_S 1

#define BT_BITS_BT_BUFFER2TX_CTRL_REG (REG_BT_BASE + 0x0004)
#define BT_BITS_BT_BUFFER2TX_GFSK_DONE (BIT(31))
#define BT_BITS_BT_BUFFER2TX_GFSK_DONE_S 31
#define BT_BITS_BT_TX_RD_ADDR_GFSK 0x0000007F
#define BT_BITS_BT_TX_RD_ADDR_GFSK_S 24
#define BT_BITS_INIT_TX_DC (BIT(23))
#define BT_BITS_INIT_TX_DC_S 23
#define BT_BITS_BT_BUFFER2TX_CTRL 0x007FFFFF
#define BT_BITS_BT_BUFFER2TX_CTRL_S 0

#define BT_BITS_BT_BUFFER2TX_CTRL_1_REG (REG_BT_BASE + 0x0008)
#define BT_BITS_BT_BUFFER2TX_PBSK_DONE (BIT(31))
#define BT_BITS_BT_BUFFER2TX_PBSK_DONE_S 31
#define BT_BITS_BT_TX_RD_ADDR_PBSK 0x0000007F
#define BT_BITS_BT_TX_RD_ADDR_PBSK_S 24
#define BT_BITS_BT_BUFFER2TX_CTRL_1 0x00FFFFFF
#define BT_BITS_BT_BUFFER2TX_CTRL_1_S 0

#define BT_BITS_BT_BUFFER2TX_CTRL_2_REG (REG_BT_BASE + 0x000c)
#define BT_BITS_BT_BUFFER2TX_CTRL_2 0xFFFFFFFF
#define BT_BITS_BT_BUFFER2TX_CTRL_2_S 0

#define BT_BITS_BT_BUFFER2TX_CTRL_3_REG (REG_BT_BASE + 0x0010)
#define BT_BITS_BT_BUFFER2TX_CTRL_3 0xFFFFFFFF
#define BT_BITS_BT_BUFFER2TX_CTRL_3_S 0

#define BT_BITS_DPSK_MODULATOR_CTRL_REG (REG_BT_BASE + 0x0014)
#define BT_BITS_DPSK_MODULATOR_CTRL_NOUSE 0x000007FF
#define BT_BITS_DPSK_MODULATOR_CTRL_NOUSE_S 21
#define BT_BITS_DPSK_OUT_END_DELAY 0x000003FF
#define BT_BITS_DPSK_OUT_END_DELAY_S 11
#define BT_BITS_DPSK_OUT_BEGIN_DELAY 0x000003FF
#define BT_BITS_DPSK_OUT_BEGIN_DELAY_S 1

#define BT_BITS_BT_RX_CTRL_REG (REG_BT_BASE + 0x0018)
#define BT_BITS_BT_RX_EN (BIT(31))
#define BT_BITS_BT_RX_EN_S 31
#define BT_BITS_BT_PRE_DET (BIT(30))
#define BT_BITS_BT_PRE_DET_S 30
#define BT_BITS_BT_2M3M_IND (BIT(29))
#define BT_BITS_BT_2M3M_IND_S 29
#define BT_BITS_BIT_LENGTH 0x00003FFF
#define BT_BITS_BIT_LENGTH_S 15
#define BT_BITS_BT_CLK_FORCE_ON (BIT(14))
#define BT_BITS_BT_CLK_FORCE_ON_S 14

#define BT_BITS_BT_BUFFER_CTRL_REG (REG_BT_BASE + 0x001c)
#define BT_BITS_BUFFER_CTRL_APB_MODE (BIT(31))
#define BT_BITS_BUFFER_CTRL_APB_MODE_S 31
#define BT_BITS_BUFFER_CTRL_TX_ON (BIT(30))
#define BT_BITS_BUFFER_CTRL_TX_ON_S 30

#define BT_BITS_RX_FHOPPER_CTRL_REG (REG_BT_BASE + 0x0020)
#define BT_BITS_RF_OFFSET_EN (BIT(8))
#define BT_BITS_RF_OFFSET_EN_S 8
#define BT_BITS_RX_RF_OFFSET_ADD (BIT(7))
#define BT_BITS_RX_RF_OFFSET_ADD_S 7
#define BT_BITS_RX_SWAP (BIT(6))
#define BT_BITS_RX_SWAP_S 6
#define BT_BITS_RX_HOPPE_N500K 0x0000003F
#define BT_BITS_RX_HOPPE_N500K_S 0

#define BT_BITS_RX_DONE_REG (REG_BT_BASE + 0x0024)
#define BT_BITS_RX_DONE (BIT(31))
#define BT_BITS_RX_DONE_S 31

#define BT_BITS_RX_GFILTER_CTRL_REG (REG_BT_BASE + 0x0028)
#define BT_BITS_OUT_POWER_SEL (BIT(7))
#define BT_BITS_OUT_POWER_SEL_S 7
#define BT_BITS_OUT_BB_SEL (BIT(6))
#define BT_BITS_OUT_BB_SEL_S 6
#define BT_BITS_FILTER_ENABLE (BIT(0))
#define BT_BITS_FILTER_ENABLE_S 0

#define BT_BITS_INT_ENA_BT_REG (REG_BT_BASE + 0x002c)
#define BT_BITS_BT_HOPPE_DONE_INT_ENA (BIT(28))
#define BT_BITS_BT_HOPPE_DONE_INT_ENA_S 28
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_ENA (BIT(27))
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_ENA_S 27
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_ENA (BIT(26))
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_ENA_S 26
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_ENA (BIT(25))
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_ENA_S 25
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_ENA (BIT(24))
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_ENA_S 24
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_ENA (BIT(23))
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_ENA_S 23
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_ENA (BIT(22))
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_ENA_S 22
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_ENA (BIT(21))
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_ENA_S 21
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_ENA (BIT(20))
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_ENA_S 20
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_ENA (BIT(19))
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_ENA_S 19
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_ENA (BIT(18))
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_ENA_S 18
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_ENA (BIT(17))
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_ENA_S 17
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_ENA (BIT(16))
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_ENA_S 16
#define BT_BITS_TESCO0_TOG_INT_ENA (BIT(15))
#define BT_BITS_TESCO0_TOG_INT_ENA_S 15
#define BT_BITS_TESCO1_TOG_INT_ENA (BIT(14))
#define BT_BITS_TESCO1_TOG_INT_ENA_S 14
#define BT_BITS_TESCO2_TOG_INT_ENA (BIT(13))
#define BT_BITS_TESCO2_TOG_INT_ENA_S 13
#define BT_BITS_BLE_TOG0_INT_ENA (BIT(12))
#define BT_BITS_BLE_TOG0_INT_ENA_S 12
#define BT_BITS_BLE_TOG1_INT_ENA (BIT(11))
#define BT_BITS_BLE_TOG1_INT_ENA_S 11
#define BT_BITS_BLE_TOG2_INT_ENA (BIT(10))
#define BT_BITS_BLE_TOG2_INT_ENA_S 10
#define BT_BITS_BT_HOPPE_TX_INT_ENA (BIT(9))
#define BT_BITS_BT_HOPPE_TX_INT_ENA_S 9
#define BT_BITS_BT_HOPPE_RX_INT_ENA (BIT(8))
#define BT_BITS_BT_HOPPE_RX_INT_ENA_S 8
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_ENA (BIT(7))
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_ENA_S 7
#define BT_BITS_BT_TX_END_INT_ENA (BIT(6))
#define BT_BITS_BT_TX_END_INT_ENA_S 6
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_ENA (BIT(5))
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_ENA_S 5
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_ENA (BIT(4))
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_ENA_S 4
#define BT_BITS_BT_AGC_RESET_INT_ENA (BIT(3))
#define BT_BITS_BT_AGC_RESET_INT_ENA_S 3
#define BT_BITS_BT_AC_FIND_INT_ENA (BIT(2))
#define BT_BITS_BT_AC_FIND_INT_ENA_S 2
#define BT_BITS_BT_RX_END_INT_ENA (BIT(1))
#define BT_BITS_BT_RX_END_INT_ENA_S 1
#define BT_BITS_BT_RX_START_INT_ENA (BIT(0))
#define BT_BITS_BT_RX_START_INT_ENA_S 0

#define BT_BITS_INT_RAW_BT_REG (REG_BT_BASE + 0x0030)
#define BT_BITS_BT_HOPPE_DONE_INT_RAW (BIT(28))
#define BT_BITS_BT_HOPPE_DONE_INT_RAW_S 28
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_RAW (BIT(27))
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_RAW_S 27
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_RAW (BIT(26))
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_RAW_S 26
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_RAW (BIT(25))
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_RAW_S 25
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_RAW (BIT(24))
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_RAW_S 24
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_RAW (BIT(23))
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_RAW_S 23
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_RAW (BIT(22))
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_RAW_S 22
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_RAW (BIT(21))
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_RAW_S 21
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_RAW (BIT(20))
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_RAW_S 20
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_RAW (BIT(19))
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_RAW_S 19
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_RAW (BIT(18))
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_RAW_S 18
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_RAW (BIT(17))
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_RAW_S 17
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_RAW (BIT(16))
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_RAW_S 16
#define BT_BITS_TESCO0_TOG_INT_RAW (BIT(15))
#define BT_BITS_TESCO0_TOG_INT_RAW_S 15
#define BT_BITS_TESCO1_TOG_INT_RAW (BIT(14))
#define BT_BITS_TESCO1_TOG_INT_RAW_S 14
#define BT_BITS_TESCO2_TOG_INT_RAW (BIT(13))
#define BT_BITS_TESCO2_TOG_INT_RAW_S 13
#define BT_BITS_BLE_TOG0_INT_RAW (BIT(12))
#define BT_BITS_BLE_TOG0_INT_RAW_S 12
#define BT_BITS_BLE_TOG1_INT_RAW (BIT(11))
#define BT_BITS_BLE_TOG1_INT_RAW_S 11
#define BT_BITS_BLE_TOG2_INT_RAW (BIT(10))
#define BT_BITS_BLE_TOG2_INT_RAW_S 10
#define BT_BITS_BT_HOPPE_TX_INT_RAW (BIT(9))
#define BT_BITS_BT_HOPPE_TX_INT_RAW_S 9
#define BT_BITS_BT_HOPPE_RX_INT_RAW (BIT(8))
#define BT_BITS_BT_HOPPE_RX_INT_RAW_S 8
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_RAW (BIT(7))
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_RAW_S 7
#define BT_BITS_BT_TX_END_INT_RAW (BIT(6))
#define BT_BITS_BT_TX_END_INT_RAW_S 6
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_RAW (BIT(5))
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_RAW_S 5
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_RAW (BIT(4))
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_RAW_S 4
#define BT_BITS_BT_AGC_RESET_INT_RAW (BIT(3))
#define BT_BITS_BT_AGC_RESET_INT_RAW_S 3
#define BT_BITS_BT_AC_FIND_INT_RAW (BIT(2))
#define BT_BITS_BT_AC_FIND_INT_RAW_S 2
#define BT_BITS_BT_RX_END_INT_RAW (BIT(1))
#define BT_BITS_BT_RX_END_INT_RAW_S 1
#define BT_BITS_BT_RX_START_INT_RAW (BIT(0))
#define BT_BITS_BT_RX_START_INT_RAW_S 0

#define BT_BITS_INT_ST_BT_REG (REG_BT_BASE + 0x0034)
#define BT_BITS_BT_HOPPE_DONE_INT_ST (BIT(28))
#define BT_BITS_BT_HOPPE_DONE_INT_ST_S 28
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_ST (BIT(27))
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_ST_S 27
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_ST (BIT(26))
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_ST_S 26
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_ST (BIT(25))
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_ST_S 25
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_ST (BIT(24))
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_ST_S 24
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_ST (BIT(23))
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_ST_S 23
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_ST (BIT(22))
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_ST_S 22
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_ST (BIT(21))
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_ST_S 21
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_ST (BIT(20))
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_ST_S 20
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_ST (BIT(19))
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_ST_S 19
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_ST (BIT(18))
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_ST_S 18
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_ST (BIT(17))
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_ST_S 17
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_ST (BIT(16))
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_ST_S 16
#define BT_BITS_TESCO0_TOG_INT_ST (BIT(15))
#define BT_BITS_TESCO0_TOG_INT_ST_S 15
#define BT_BITS_TESCO1_TOG_INT_ST (BIT(14))
#define BT_BITS_TESCO1_TOG_INT_ST_S 14
#define BT_BITS_TESCO2_TOG_INT_ST (BIT(13))
#define BT_BITS_TESCO2_TOG_INT_ST_S 13
#define BT_BITS_BLE_TOG0_INT_ST (BIT(12))
#define BT_BITS_BLE_TOG0_INT_ST_S 12
#define BT_BITS_BLE_TOG1_INT_ST (BIT(11))
#define BT_BITS_BLE_TOG1_INT_ST_S 11
#define BT_BITS_BLE_TOG2_INT_ST (BIT(10))
#define BT_BITS_BLE_TOG2_INT_ST_S 10
#define BT_BITS_BT_HOPPE_TX_INT_ST (BIT(9))
#define BT_BITS_BT_HOPPE_TX_INT_ST_S 9
#define BT_BITS_BT_HOPPE_RX_INT_ST (BIT(8))
#define BT_BITS_BT_HOPPE_RX_INT_ST_S 8
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_ST (BIT(7))
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_ST_S 7
#define BT_BITS_BT_TX_END_INT_ST (BIT(6))
#define BT_BITS_BT_TX_END_INT_ST_S 6
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_ST (BIT(5))
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_ST_S 5
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_ST (BIT(4))
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_ST_S 4
#define BT_BITS_BT_AGC_RESET_INT_ST (BIT(3))
#define BT_BITS_BT_AGC_RESET_INT_ST_S 3
#define BT_BITS_BT_AC_FIND_INT_ST (BIT(2))
#define BT_BITS_BT_AC_FIND_INT_ST_S 2
#define BT_BITS_BT_RX_END_INT_ST (BIT(1))
#define BT_BITS_BT_RX_END_INT_ST_S 1
#define BT_BITS_BT_RX_START_INT_ST (BIT(0))
#define BT_BITS_BT_RX_START_INT_ST_S 0

#define BT_BITS_INT_CLR_BT_REG (REG_BT_BASE + 0x0038)
#define BT_BITS_BT_HOPPE_DONE_INT_CLR (BIT(28))
#define BT_BITS_BT_HOPPE_DONE_INT_CLR_S 28
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_CLR (BIT(27))
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_CLR_S 27
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_CLR (BIT(26))
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_CLR_S 26
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_CLR (BIT(25))
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_CLR_S 25
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_CLR (BIT(24))
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_CLR_S 24
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_CLR (BIT(23))
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_CLR_S 23
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_CLR (BIT(22))
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_CLR_S 22
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_CLR (BIT(21))
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_CLR_S 21
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_CLR (BIT(20))
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_CLR_S 20
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_CLR (BIT(19))
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_CLR_S 19
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_CLR (BIT(18))
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_CLR_S 18
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_CLR (BIT(17))
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_CLR_S 17
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_CLR (BIT(16))
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_CLR_S 16
#define BT_BITS_TESCO0_TOG_INT_CLR (BIT(15))
#define BT_BITS_TESCO0_TOG_INT_CLR_S 15
#define BT_BITS_TESCO1_TOG_INT_CLR (BIT(14))
#define BT_BITS_TESCO1_TOG_INT_CLR_S 14
#define BT_BITS_TESCO2_TOG_INT_CLR (BIT(13))
#define BT_BITS_TESCO2_TOG_INT_CLR_S 13
#define BT_BITS_BLE_TOG0_INT_CLR (BIT(12))
#define BT_BITS_BLE_TOG0_INT_CLR_S 12
#define BT_BITS_BLE_TOG1_INT_CLR (BIT(11))
#define BT_BITS_BLE_TOG1_INT_CLR_S 11
#define BT_BITS_BLE_TOG2_INT_CLR (BIT(10))
#define BT_BITS_BLE_TOG2_INT_CLR_S 10
#define BT_BITS_BT_HOPPE_TX_INT_CLR (BIT(9))
#define BT_BITS_BT_HOPPE_TX_INT_CLR_S 9
#define BT_BITS_BT_HOPPE_RX_INT_CLR (BIT(8))
#define BT_BITS_BT_HOPPE_RX_INT_CLR_S 8
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_CLR (BIT(7))
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_CLR_S 7
#define BT_BITS_BT_TX_END_INT_CLR (BIT(6))
#define BT_BITS_BT_TX_END_INT_CLR_S 6
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_CLR (BIT(5))
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_CLR_S 5
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_CLR (BIT(4))
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_CLR_S 4
#define BT_BITS_BT_AGC_RESET_INT_CLR (BIT(3))
#define BT_BITS_BT_AGC_RESET_INT_CLR_S 3
#define BT_BITS_BT_AC_FIND_INT_CLR (BIT(2))
#define BT_BITS_BT_AC_FIND_INT_CLR_S 2
#define BT_BITS_BT_RX_END_INT_CLR (BIT(1))
#define BT_BITS_BT_RX_END_INT_CLR_S 1
#define BT_BITS_BT_RX_START_INT_CLR (BIT(0))
#define BT_BITS_BT_RX_START_INT_CLR_S 0

#define BT_BITS_BT_TX_IF_REG (REG_BT_BASE + 0x003c)
#define BT_BITS_BT_TX_INTERFACE_EN (BIT(31))
#define BT_BITS_BT_TX_INTERFACE_EN_S 31
#define BT_BITS_BT_TX_GUARD 0x000003FF
#define BT_BITS_BT_TX_GUARD_S 21
#define BT_BITS_BT_TX_ON_AHEAD 0x000003FF
#define BT_BITS_BT_TX_ON_AHEAD_S 11
#define BT_BITS_BT_TX_ON_BEHIND 0x000003FF
#define BT_BITS_BT_TX_ON_BEHIND_S 1
#define BT_BITS_BT_TX_INIT_DC (BIT(0))
#define BT_BITS_BT_TX_INIT_DC_S 0

#define BT_BITS_BT_TX_8M_REG (REG_BT_BASE + 0x0040)
#define BT_BITS_TX_RF_OFFSET_ADD (BIT(28))
#define BT_BITS_TX_RF_OFFSET_ADD_S 28
#define BT_BITS_TX_SWAP (BIT(27))
#define BT_BITS_TX_SWAP_S 27
#define BT_BITS_HOPPE_N500K 0x0000003F
#define BT_BITS_HOPPE_N500K_S 21
#define BT_BITS_FSTEP_500K 0x000FFFFF
#define BT_BITS_FSTEP_500K_S 1
#define BT_BITS_BT_TX_8M_EN (BIT(0))
#define BT_BITS_BT_TX_8M_EN_S 0

#define BT_BITS_BT_TX_RAMP_REG (REG_BT_BASE + 0x0044)
#define BT_BITS_TX_RAMPUP_DELAY 0x000000FF
#define BT_BITS_TX_RAMPUP_DELAY_S 0

#define BT_BITS_BT_AGC_CFG_REG (REG_BT_BASE + 0x0048)
#define BT_BITS_CHANGE_TARGETPOWER_REQ_EN (BIT(30))
#define BT_BITS_CHANGE_TARGETPOWER_REQ_EN_S 30
#define BT_BITS_GUARD_WINDOW_SDELAY 0x000003FF
#define BT_BITS_GUARD_WINDOW_SDELAY_S 20
#define BT_BITS_GUARD_WINDOW_EDELAY 0x000003FF
#define BT_BITS_GUARD_WINDOW_EDELAY_S 10
#define BT_BITS_TARGETPOWER_CHANGE_DELAY 0x000003FF
#define BT_BITS_TARGETPOWER_CHANGE_DELAY_S 0

#define BT_BITS_BT_AGC_CFG_1_REG (REG_BT_BASE + 0x004c)
#define BT_BITS_BT_MODE_DELAY 0x000003FF
#define BT_BITS_BT_MODE_DELAY_S 22
#define BT_BITS_RX_POWER_REF_POINT 0x0000003F
#define BT_BITS_RX_POWER_REF_POINT_S 16
#define BT_BITS_AGC_RESTART_EN (BIT(15))
#define BT_BITS_AGC_RESTART_EN_S 15
#define BT_BITS_PWDET_VALID_DELAY 0x0000001F
#define BT_BITS_PWDET_VALID_DELAY_S 10
#define BT_BITS_AGC_RESTART_WINDOW 0x000003FF
#define BT_BITS_AGC_RESTART_WINDOW_S 0

#define BT_BITS_BT_RX_WARNING_REG (REG_BT_BASE + 0x0050)
#define BT_BITS_BT_RX_SYNC_TIME 0x0000007F
#define BT_BITS_BT_RX_SYNC_TIME_S 17
#define BT_BITS_BT_RX_CORR_TIME 0x000001FF
#define BT_BITS_BT_RX_CORR_TIME_S 8
#define BT_BITS_BT_RX_WARNING 0x000000FF
#define BT_BITS_BT_RX_WARNING_S 0

#define BT_BITS_BT_FREQOS_CFG_REG (REG_BT_BASE + 0x0054)
#define BT_BITS_FREQOS_EN (BIT(31))
#define BT_BITS_FREQOS_EN_S 31
#define BT_BITS_FREQOS 0x0000FFFF
#define BT_BITS_FREQOS_S 0

#define BT_BITS_BT_RX_CFG_REG (REG_BT_BASE + 0x0058)
#define BT_BITS_RX_CFG 0xFFFFFFFF
#define BT_BITS_RX_CFG_S 0

#define BT_BITS_BT_RX_CFG_1_REG (REG_BT_BASE + 0x005c)
#define BT_BITS_RX_CFG_1 0xFFFFFFFF
#define BT_BITS_RX_CFG_1_S 0

#define BT_BITS_BT_RX_CFG_2_REG (REG_BT_BASE + 0x0060)
#define BT_BITS_RX_CFG_2 0xFFFFFFFF
#define BT_BITS_RX_CFG_2_S 0

#define BT_BITS_BT_RX_CFG_3_REG (REG_BT_BASE + 0x0064)
#define BT_BITS_RX_CFG_3 0xFFFFFFFF
#define BT_BITS_RX_CFG_3_S 0

#define BT_BITS_BT_RX_CFG_4_REG (REG_BT_BASE + 0x0068)
#define BT_BITS_RX_CFG_4 0xFFFFFFFF
#define BT_BITS_RX_CFG_4_S 0

#define BT_BITS_BT_RX_CFG_5_REG (REG_BT_BASE + 0x006c)
#define BT_BITS_RX_CFG_5 0xFFFFFFFF
#define BT_BITS_RX_CFG_5_S 0

#define BT_BITS_BT_RX_CFG_6_REG (REG_BT_BASE + 0x0070)
#define BT_BITS_RX_CFG_6 0xFFFFFFFF
#define BT_BITS_RX_CFG_6_S 0

#define BT_BITS_BT_RX_INFO_REG (REG_BT_BASE + 0x0074)
#define BT_BITS_PWR_IN_BAND_PREAMBLE 0x000000FF
#define BT_BITS_PWR_IN_BAND_PREAMBLE_S 24
#define BT_BITS_PWR_FULL_BAND_PREAMBLE 0x000000FF
#define BT_BITS_PWR_FULL_BAND_PREAMBLE_S 16
#define BT_BITS_GAIN_PREAMBLE 0x000000FF
#define BT_BITS_GAIN_PREAMBLE_S 8
#define BT_BITS_PWR_IN_BAND_PACKET 0x000000FF
#define BT_BITS_PWR_IN_BAND_PACKET_S 0

#define BT_BITS_BT_RX_INFO_1_REG (REG_BT_BASE + 0x0078)
#define BT_BITS_PWR_FULL_BAND_PACKET 0x000000FF
#define BT_BITS_PWR_FULL_BAND_PACKET_S 24
#define BT_BITS_GAIN_PACKET 0x000000FF
#define BT_BITS_GAIN_PACKET_S 16
#define BT_BITS_PWR_IN_BAND_MAX 0x000000FF
#define BT_BITS_PWR_IN_BAND_MAX_S 8
#define BT_BITS_PWR_FULL_BAND_MAX 0x000000FF
#define BT_BITS_PWR_FULL_BAND_MAX_S 0

#define BT_BITS_BT_RX_INFO_2_REG (REG_BT_BASE + 0x007c)
#define BT_BITS_PREAMBLE_EVM 0x000000FF
#define BT_BITS_PREAMBLE_EVM_S 24
#define BT_BITS_PACKET_EVM 0x000000FF
#define BT_BITS_PACKET_EVM_S 16
#define BT_BITS_PACKET_TIM 0x0000000F
#define BT_BITS_PACKET_TIM_S 12
#define BT_BITS_GAIN_MAX 0x000000FF
#define BT_BITS_GAIN_MAX_S 4

#define BT_BITS_BT_RX_INFO_3_REG (REG_BT_BASE + 0x0080)
#define BT_BITS_PREAMBLE_FREQ 0x000007FF
#define BT_BITS_PREAMBLE_FREQ_S 21
#define BT_BITS_PACKET_FREQ 0x000007FF
#define BT_BITS_PACKET_FREQ_S 10
#define BT_BITS_RX_PREAMBLE_FREQ_MUX (BIT(9))
#define BT_BITS_RX_PREAMBLE_FREQ_MUX_S 9
#define BT_BITS_RX_PACKET_FREQ_MUX (BIT(8))
#define BT_BITS_RX_PACKET_FREQ_MUX_S 8

#define BT_BITS_BT_RX_INFO_4_REG (REG_BT_BASE + 0x0084)
#define BT_BITS_PWR_IN_BAND_MAX_DELTA_THRESH 0x000000FF
#define BT_BITS_PWR_IN_BAND_MAX_DELTA_THRESH_S 24
#define BT_BITS_PWR_FULL_BAND_MAX_THRESH 0x000000FF
#define BT_BITS_PWR_FULL_BAND_MAX_THRESH_S 16
#define BT_BITS_RX_INFO_3_MUX 0x00000007
#define BT_BITS_RX_INFO_3_MUX_S 13
#define BT_BITS_RX_INFO_2_MUX 0x00000007
#define BT_BITS_RX_INFO_2_MUX_S 10
#define BT_BITS_RX_INFO_1_MUX 0x00000007
#define BT_BITS_RX_INFO_1_MUX_S 7
#define BT_BITS_RX_INFO_0_MUX 0x00000007
#define BT_BITS_RX_INFO_0_MUX_S 4

#define BT_BITS_BT_RX_INFO_5_REG (REG_BT_BASE + 0x0088)
#define BT_BITS_PWR_FULL_BAND_MAX_ERROR_THRESH 0x000000FF
#define BT_BITS_PWR_FULL_BAND_MAX_ERROR_THRESH_S 24
#define BT_BITS_PACKET_END_INBAND_DROP_THRESH 0x000000FF
#define BT_BITS_PACKET_END_INBAND_DROP_THRESH_S 16
#define BT_BITS_PACKET_END_INBAND_ADC_PLOOR 0x000000FF
#define BT_BITS_PACKET_END_INBAND_ADC_PLOOR_S 8
#define BT_BITS_PACKET_END_INBAND_RSSI_PLOOR 0x000000FF
#define BT_BITS_PACKET_END_INBAND_RSSI_PLOOR_S 0

#define BT_BITS_BT_RX_INFO_6_REG (REG_BT_BASE + 0x008c)
#define BT_BITS_PWR_FULL_BAND_MAX_ERROR_EN (BIT(31))
#define BT_BITS_PWR_FULL_BAND_MAX_ERROR_EN_S 31
#define BT_BITS_PACKET_END_INBAND_DROP_ERROR_EN (BIT(30))
#define BT_BITS_PACKET_END_INBAND_DROP_ERROR_EN_S 30
#define BT_BITS_PACKET_END_INBAND_DROP_CHECK_EN (BIT(29))
#define BT_BITS_PACKET_END_INBAND_DROP_CHECK_EN_S 29
#define BT_BITS_PACKET_END_INBAND_DROP_DELAY 0x0000001F
#define BT_BITS_PACKET_END_INBAND_DROP_DELAY_S 24
#define BT_BITS_RX_WARNING_MASK 0x000000FF
#define BT_BITS_RX_WARNING_MASK_S 16
#define BT_BITS_RX_WARNING_SEL_BIT0 0x00000003
#define BT_BITS_RX_WARNING_SEL_BIT0_S 14

#define BT_BITS_BT_RX_NOISE_FLOOR_REG (REG_BT_BASE + 0x0090)
#define BT_BITS_NOISE_FLOOR_EN (BIT(31))
#define BT_BITS_NOISE_FLOOR_EN_S 31
#define BT_BITS_NOISE_FLOOR 0x000000FF
#define BT_BITS_NOISE_FLOOR_S 23
#define BT_BITS_NOISE_NOW 0x000000FF
#define BT_BITS_NOISE_NOW_S 15
#define BT_BITS_NOISE_FILTED 0x000000FF
#define BT_BITS_NOISE_FILTED_S 7

#define BT_BITS_BT_BB2FE_REG (REG_BT_BASE + 0x0094)
#define BT_BITS_BT_MODE_ON_INIT 0x000000FF
#define BT_BITS_BT_MODE_ON_INIT_S 24
#define BT_BITS_BT_MODE_ON_WAIT 0x000000FF
#define BT_BITS_BT_MODE_ON_WAIT_S 16
#define BT_BITS_BT_MODE_OFF_INIT 0x000000FF
#define BT_BITS_BT_MODE_OFF_INIT_S 8
#define BT_BITS_BT_MODE_OFF_WAIT 0x000000FF
#define BT_BITS_BT_MODE_OFF_WAIT_S 0

#define BT_BITS_BT_MUX_CFG_REG (REG_BT_BASE + 0x0098)
#define BT_BITS_BT_MUX_SCAN_FORCE_EN (BIT(31))
#define BT_BITS_BT_MUX_SCAN_FORCE_EN_S 31
#define BT_BITS_BT_MUX_SCAN_FORCE (BIT(30))
#define BT_BITS_BT_MUX_SCAN_FORCE_S 30
#define BT_BITS_RW_TXPWR_EN (BIT(29))
#define BT_BITS_RW_TXPWR_EN_S 29
#define BT_BITS_RW_AC_DELAY 0x00000FFF
#define BT_BITS_RW_AC_DELAY_S 17
#define BT_BITS_RW_BT_TX_EN_DELAY 0x000000FF
#define BT_BITS_RW_BT_TX_EN_DELAY_S 9
#define BT_BITS_RW_BT_RX_EN_DELAY 0x000000FF
#define BT_BITS_RW_BT_RX_EN_DELAY_S 1
#define BT_BITS_BT_MUX_RW_EN (BIT(0))
#define BT_BITS_BT_MUX_RW_EN_S 0

#define BT_BITS_BT_RW_LE_CFG_REG (REG_BT_BASE + 0x009c)
#define BT_BITS_RW_BT_TX_ABORT_EN (BIT(30))
#define BT_BITS_RW_BT_TX_ABORT_EN_S 30
#define BT_BITS_RW_BT_RX_ABORT_EN (BIT(29))
#define BT_BITS_RW_BT_RX_ABORT_EN_S 29
#define BT_BITS_FE_BT_MODE_EN_SEL (BIT(28))
#define BT_BITS_FE_BT_MODE_EN_SEL_S 28
#define BT_BITS_RW_NEW_VERSION_OFF (BIT(27))
#define BT_BITS_RW_NEW_VERSION_OFF_S 27
#define BT_BITS_RW_FAKE_CRC_ERROR_EN (BIT(26))
#define BT_BITS_RW_FAKE_CRC_ERROR_EN_S 26
#define BT_BITS_RW_RF_BUSY_FIX (BIT(25))
#define BT_BITS_RW_RF_BUSY_FIX_S 25
#define BT_BITS_RW_CLK_FORCE_ON (BIT(24))
#define BT_BITS_RW_CLK_FORCE_ON_S 24
#define BT_BITS_RW_LE_TX_EN_DELAY 0x000000FF
#define BT_BITS_RW_LE_TX_EN_DELAY_S 16
#define BT_BITS_RW_LE_RX_EN_DELAY 0x000000FF
#define BT_BITS_RW_LE_RX_EN_DELAY_S 8
#define BT_BITS_RW_LE_AA_DELAY 0x000000FF
#define BT_BITS_RW_LE_AA_DELAY_S 0

#define BT_BITS_BT_RW_EM_BASE_REG (REG_BT_BASE + 0x00a0)
#define BT_BITS_RW_EM_BASE 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE_S 2

#define BT_BITS_BT_RW_RX_PHYINFO_CFG_REG (REG_BT_BASE + 0x00a4)
#define BT_BITS_RW_RX_PHYINFO_READY 0x000000FF
#define BT_BITS_RW_RX_PHYINFO_READY_S 1
#define BT_BITS_RW_RX_PHYINFO_CLEAR (BIT(0))
#define BT_BITS_RW_RX_PHYINFO_CLEAR_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_0A_REG (REG_BT_BASE + 0x00a8)
#define BT_BITS_RW_RX_PHYINFO_LE_0 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_0_S 23
#define BT_BITS_RW_RX_PHYERR_0 0x000000FF
#define BT_BITS_RW_RX_PHYERR_0_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_0 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_0_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_0B_REG (REG_BT_BASE + 0x00ac)
#define BT_BITS_RW_RX_PHYINFO_0 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_0_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_1A_REG (REG_BT_BASE + 0x00b0)
#define BT_BITS_RW_RX_PHYINFO_LE_1 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_1_S 23
#define BT_BITS_RW_RX_PHYERR_1 0x000000FF
#define BT_BITS_RW_RX_PHYERR_1_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_1 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_1_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_1B_REG (REG_BT_BASE + 0x00b4)
#define BT_BITS_RW_RX_PHYINFO_1 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_1_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_2A_REG (REG_BT_BASE + 0x00b8)
#define BT_BITS_RW_RX_PHYINFO_LE_2 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_2_S 23
#define BT_BITS_RW_RX_PHYERR_2 0x000000FF
#define BT_BITS_RW_RX_PHYERR_2_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_2 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_2_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_2B_REG (REG_BT_BASE + 0x00bc)
#define BT_BITS_RW_RX_PHYINFO_2 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_2_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_3A_REG (REG_BT_BASE + 0x00c0)
#define BT_BITS_RW_RX_PHYINFO_LE_3 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_3_S 23
#define BT_BITS_RW_RX_PHYERR_3 0x000000FF
#define BT_BITS_RW_RX_PHYERR_3_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_3 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_3_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_3B_REG (REG_BT_BASE + 0x00c4)
#define BT_BITS_RW_RX_PHYINFO_3 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_3_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_4A_REG (REG_BT_BASE + 0x00c8)
#define BT_BITS_RW_RX_PHYINFO_LE_4 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_4_S 23
#define BT_BITS_RW_RX_PHYERR_4 0x000000FF
#define BT_BITS_RW_RX_PHYERR_4_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_4 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_4_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_4B_REG (REG_BT_BASE + 0x00cc)
#define BT_BITS_RW_RX_PHYINFO_4 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_4_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_5A_REG (REG_BT_BASE + 0x00d0)
#define BT_BITS_RW_RX_PHYINFO_LE_5 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_5_S 23
#define BT_BITS_RW_RX_PHYERR_5 0x000000FF
#define BT_BITS_RW_RX_PHYERR_5_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_5 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_5_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_5B_REG (REG_BT_BASE + 0x00d4)
#define BT_BITS_RW_RX_PHYINFO_5 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_5_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_6A_REG (REG_BT_BASE + 0x00d8)
#define BT_BITS_RW_RX_PHYINFO_LE_6 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_6_S 23
#define BT_BITS_RW_RX_PHYERR_6 0x000000FF
#define BT_BITS_RW_RX_PHYERR_6_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_6 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_6_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_6B_REG (REG_BT_BASE + 0x00dc)
#define BT_BITS_RW_RX_PHYINFO_6 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_6_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_7A_REG (REG_BT_BASE + 0x00e0)
#define BT_BITS_RW_RX_PHYINFO_LE_7 (BIT(23))
#define BT_BITS_RW_RX_PHYINFO_LE_7_S 23
#define BT_BITS_RW_RX_PHYERR_7 0x000000FF
#define BT_BITS_RW_RX_PHYERR_7_S 15
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_7 0x00007FFF
#define BT_BITS_RW_RX_PHYINFO_DESCPTR_7_S 0

#define BT_BITS_BT_RW_RX_PHYINFO_7B_REG (REG_BT_BASE + 0x00e4)
#define BT_BITS_RW_RX_PHYINFO_7 0xFFFFFFFF
#define BT_BITS_RW_RX_PHYINFO_7_S 0

#define BT_BITS_BT_RW_BT_NMI_REG (REG_BT_BASE + 0x00e8)
#define BT_BITS_RW_BT_SLOT_NMI (BIT(16))
#define BT_BITS_RW_BT_SLOT_NMI_S 16
#define BT_BITS_RW_BT_SW_NMI (BIT(15))
#define BT_BITS_RW_BT_SW_NMI_S 15
#define BT_BITS_RW_BT_SKET_NMI (BIT(14))
#define BT_BITS_RW_BT_SKET_NMI_S 14
#define BT_BITS_RW_BT_FRAME_NMI (BIT(13))
#define BT_BITS_RW_BT_FRAME_NMI_S 13
#define BT_BITS_RW_BT_RX_NMI (BIT(12))
#define BT_BITS_RW_BT_RX_NMI_S 12
#define BT_BITS_RW_BT_SLP_NMI (BIT(11))
#define BT_BITS_RW_BT_SLP_NMI_S 11
#define BT_BITS_RW_BT_AUDIO0_NMI (BIT(10))
#define BT_BITS_RW_BT_AUDIO0_NMI_S 10
#define BT_BITS_RW_BT_AUDIO1_NMI (BIT(9))
#define BT_BITS_RW_BT_AUDIO1_NMI_S 9
#define BT_BITS_RW_BT_AUDIO2_NMI (BIT(8))
#define BT_BITS_RW_BT_AUDIO2_NMI_S 8
#define BT_BITS_RW_BT_MWS_FR_SYNC_NMI (BIT(7))
#define BT_BITS_RW_BT_MWS_FR_SYNC_NMI_S 7
#define BT_BITS_RW_BT_MWS_MT_OFFSET0_NMI (BIT(6))
#define BT_BITS_RW_BT_MWS_MT_OFFSET0_NMI_S 6
#define BT_BITS_RW_BT_MWS_MT_OFFSET1_NMI (BIT(5))
#define BT_BITS_RW_BT_MWS_MT_OFFSET1_NMI_S 5
#define BT_BITS_RW_BT_MWS_WCI_TX_NMI (BIT(4))
#define BT_BITS_RW_BT_MWS_WCI_TX_NMI_S 4
#define BT_BITS_RW_BT_MWS_WCI_RX_NMI (BIT(3))
#define BT_BITS_RW_BT_MWS_WCI_RX_NMI_S 3
#define BT_BITS_RW_BT_FINETGTIM_NMI (BIT(2))
#define BT_BITS_RW_BT_FINETGTIM_NMI_S 2
#define BT_BITS_RW_BT_GROSSTGTIM_NMI (BIT(1))
#define BT_BITS_RW_BT_GROSSTGTIM_NMI_S 1
#define BT_BITS_RW_BT_ERROR_NMI (BIT(0))
#define BT_BITS_RW_BT_ERROR_NMI_S 0

#define BT_BITS_BT_RW_LE_NMI_REG (REG_BT_BASE + 0x00ec)
#define BT_BITS_RW_LE_CSCNT_NMI (BIT(11))
#define BT_BITS_RW_LE_CSCNT_NMI_S 11
#define BT_BITS_RW_LE_SW_NMI (BIT(10))
#define BT_BITS_RW_LE_SW_NMI_S 10
#define BT_BITS_RW_LE_AUDIO0_NMI (BIT(9))
#define BT_BITS_RW_LE_AUDIO0_NMI_S 9
#define BT_BITS_RW_LE_AUDIO1_NMI (BIT(8))
#define BT_BITS_RW_LE_AUDIO1_NMI_S 8
#define BT_BITS_RW_LE_AUDIO2_NMI (BIT(7))
#define BT_BITS_RW_LE_AUDIO2_NMI_S 7
#define BT_BITS_RW_LE_RX_NMI (BIT(6))
#define BT_BITS_RW_LE_RX_NMI_S 6
#define BT_BITS_RW_LE_SLP_NMI (BIT(5))
#define BT_BITS_RW_LE_SLP_NMI_S 5
#define BT_BITS_RW_LE_EVENT_NMI (BIT(4))
#define BT_BITS_RW_LE_EVENT_NMI_S 4
#define BT_BITS_RW_LE_CRYPT_NMI (BIT(3))
#define BT_BITS_RW_LE_CRYPT_NMI_S 3
#define BT_BITS_RW_LE_ERROR_NMI (BIT(2))
#define BT_BITS_RW_LE_ERROR_NMI_S 2
#define BT_BITS_RW_LE_GROSSTGTIM_NMI (BIT(1))
#define BT_BITS_RW_LE_GROSSTGTIM_NMI_S 1
#define BT_BITS_RW_LE_FINETGTIM_NMI (BIT(0))
#define BT_BITS_RW_LE_FINETGTIM_NMI_S 0

#define BT_BITS_INT_NMI_BT_REG (REG_BT_BASE + 0x00f0)
#define BT_BITS_BT_HOPPE_DONE_INT_NMI (BIT(28))
#define BT_BITS_BT_HOPPE_DONE_INT_NMI_S 28
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_NMI (BIT(27))
#define BT_BITS_BT_INVL0_0_IN_VALID_INT_NMI_S 27
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_NMI (BIT(26))
#define BT_BITS_BT_INVL0_1_IN_VALID_INT_NMI_S 26
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_NMI (BIT(25))
#define BT_BITS_BT_INVL1_0_IN_VALID_INT_NMI_S 25
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_NMI (BIT(24))
#define BT_BITS_BT_INVL1_1_IN_VALID_INT_NMI_S 24
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_NMI (BIT(23))
#define BT_BITS_BT_INVL2_0_IN_VALID_INT_NMI_S 23
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_NMI (BIT(22))
#define BT_BITS_BT_INVL2_1_IN_VALID_INT_NMI_S 22
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_NMI (BIT(21))
#define BT_BITS_BLE_INVL0_1_IN_VALID_INT_NMI_S 21
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_NMI (BIT(20))
#define BT_BITS_BLE_INVL0_0_IN_VALID_INT_NMI_S 20
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_NMI (BIT(19))
#define BT_BITS_BLE_INVL1_1_IN_VALID_INT_NMI_S 19
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_NMI (BIT(18))
#define BT_BITS_BLE_INVL1_0_IN_VALID_INT_NMI_S 18
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_NMI (BIT(17))
#define BT_BITS_BLE_INVL2_1_IN_VALID_INT_NMI_S 17
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_NMI (BIT(16))
#define BT_BITS_BLE_INVL2_0_IN_VALID_INT_NMI_S 16
#define BT_BITS_TESCO0_TOG_INT_NMI (BIT(15))
#define BT_BITS_TESCO0_TOG_INT_NMI_S 15
#define BT_BITS_TESCO1_TOG_INT_NMI (BIT(14))
#define BT_BITS_TESCO1_TOG_INT_NMI_S 14
#define BT_BITS_TESCO2_TOG_INT_NMI (BIT(13))
#define BT_BITS_TESCO2_TOG_INT_NMI_S 13
#define BT_BITS_BLE_TOG0_INT_NMI (BIT(12))
#define BT_BITS_BLE_TOG0_INT_NMI_S 12
#define BT_BITS_BLE_TOG1_INT_NMI (BIT(11))
#define BT_BITS_BLE_TOG1_INT_NMI_S 11
#define BT_BITS_BLE_TOG2_INT_NMI (BIT(10))
#define BT_BITS_BLE_TOG2_INT_NMI_S 10
#define BT_BITS_BT_HOPPE_TX_INT_NMI (BIT(9))
#define BT_BITS_BT_HOPPE_TX_INT_NMI_S 9
#define BT_BITS_BT_HOPPE_RX_INT_NMI (BIT(8))
#define BT_BITS_BT_HOPPE_RX_INT_NMI_S 8
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_NMI (BIT(7))
#define BT_BITS_RW_RX_PHYINFO_FULL_INT_NMI_S 7
#define BT_BITS_BT_TX_END_INT_NMI (BIT(6))
#define BT_BITS_BT_TX_END_INT_NMI_S 6
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_NMI (BIT(5))
#define BT_BITS_BT_RX_AC_SYNC_ERR_INT_NMI_S 5
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_NMI (BIT(4))
#define BT_BITS_BT_RX_PSK_SYNC_ERR_INT_NMI_S 4
#define BT_BITS_BT_AGC_RESET_INT_NMI (BIT(3))
#define BT_BITS_BT_AGC_RESET_INT_NMI_S 3
#define BT_BITS_BT_AC_FIND_INT_NMI (BIT(2))
#define BT_BITS_BT_AC_FIND_INT_NMI_S 2
#define BT_BITS_BT_RX_END_INT_NMI (BIT(1))
#define BT_BITS_BT_RX_END_INT_NMI_S 1
#define BT_BITS_BT_RX_START_INT_NMI (BIT(0))
#define BT_BITS_BT_RX_START_INT_NMI_S 0

#define BT_BITS_BT_DUMP_CFG_REG (REG_BT_BASE + 0x00f4)
#define BT_BITS_BT_DUMP_PWR_SEL 0x00000003
#define BT_BITS_BT_DUMP_PWR_SEL_S 6
#define BT_BITS_BT_DUMP_TRIGGER_FORCE_EN (BIT(5))
#define BT_BITS_BT_DUMP_TRIGGER_FORCE_EN_S 5
#define BT_BITS_BT_DUMP_TRIGGER_FORCE (BIT(4))
#define BT_BITS_BT_DUMP_TRIGGER_FORCE_S 4
#define BT_BITS_BT_DUMP_TRIGGER_SEL 0x00000003
#define BT_BITS_BT_DUMP_TRIGGER_SEL_S 2
#define BT_BITS_BT_DUMP_DATA_SEL (BIT(1))
#define BT_BITS_BT_DUMP_DATA_SEL_S 1
#define BT_BITS_BT_DUMP_EN (BIT(0))
#define BT_BITS_BT_DUMP_EN_S 0

#define BT_BITS_INT1_ENA_BT_REG (REG_BT_BASE + 0x00f8)
#define BT_BITS_RW_TICK_625US_P_INT_ENA (BIT(24))
#define BT_BITS_RW_TICK_625US_P_INT_ENA_S 24
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_ENA (BIT(23))
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_ENA_S 23
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_ENA (BIT(22))
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_ENA_S 22
#define BT_BITS_RW_T0_INT_ENA (BIT(21))
#define BT_BITS_RW_T0_INT_ENA_S 21
#define BT_BITS_RW_T1_INT_ENA (BIT(20))
#define BT_BITS_RW_T1_INT_ENA_S 20
#define BT_BITS_RW_T2_INT_ENA (BIT(19))
#define BT_BITS_RW_T2_INT_ENA_S 19
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_ENA (BIT(18))
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_ENA_S 18
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_ENA (BIT(17))
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_ENA_S 17
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_ENA (BIT(16))
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_ENA_S 16
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_ENA (BIT(15))
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_ENA_S 15
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_ENA (BIT(14))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_ENA_S 14
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_ENA (BIT(13))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_ENA_S 13
#define BT_BITS_RW_BTDMTXABORT_P_INT_ENA (BIT(12))
#define BT_BITS_RW_BTDMTXABORT_P_INT_ENA_S 12
#define BT_BITS_RW_BTDMRXABORT_P_INT_ENA (BIT(11))
#define BT_BITS_RW_BTDMRXABORT_P_INT_ENA_S 11
#define BT_BITS_RW_BT_FH_DONE_P_INT_ENA (BIT(10))
#define BT_BITS_RW_BT_FH_DONE_P_INT_ENA_S 10
#define BT_BITS_RW_BLE_FH_DONE_P_INT_ENA (BIT(9))
#define BT_BITS_RW_BLE_FH_DONE_P_INT_ENA_S 9
#define BT_BITS_RW_TX_EN_P_INT_ENA (BIT(8))
#define BT_BITS_RW_TX_EN_P_INT_ENA_S 8
#define BT_BITS_RW_TX_EN_N_INT_ENA (BIT(7))
#define BT_BITS_RW_TX_EN_N_INT_ENA_S 7
#define BT_BITS_RW_RX_EN_P_INT_ENA (BIT(6))
#define BT_BITS_RW_RX_EN_P_INT_ENA_S 6
#define BT_BITS_RW_RX_EN_N_INT_ENA (BIT(5))
#define BT_BITS_RW_RX_EN_N_INT_ENA_S 5
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_ENA (BIT(4))
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_ENA_S 4
#define BT_BITS_BT_MUX_TX_START_INT_ENA (BIT(3))
#define BT_BITS_BT_MUX_TX_START_INT_ENA_S 3
#define BT_BITS_BT_MUX_TX_END_INT_ENA (BIT(2))
#define BT_BITS_BT_MUX_TX_END_INT_ENA_S 2
#define BT_BITS_BT_MUX_RX_END_INT_ENA (BIT(1))
#define BT_BITS_BT_MUX_RX_END_INT_ENA_S 1
#define BT_BITS_BT_MUX_BT_RX_START_INT_ENA (BIT(0))
#define BT_BITS_BT_MUX_BT_RX_START_INT_ENA_S 0

#define BT_BITS_INT1_RAW_BT_REG (REG_BT_BASE + 0x00fc)
#define BT_BITS_RW_TICK_625US_P_INT_RAW (BIT(24))
#define BT_BITS_RW_TICK_625US_P_INT_RAW_S 24
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_RAW (BIT(23))
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_RAW_S 23
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_RAW (BIT(22))
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_RAW_S 22
#define BT_BITS_RW_T0_INT_RAW (BIT(21))
#define BT_BITS_RW_T0_INT_RAW_S 21
#define BT_BITS_RW_T1_INT_RAW (BIT(20))
#define BT_BITS_RW_T1_INT_RAW_S 20
#define BT_BITS_RW_T2_INT_RAW (BIT(19))
#define BT_BITS_RW_T2_INT_RAW_S 19
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_RAW (BIT(18))
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_RAW_S 18
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_RAW (BIT(17))
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_RAW_S 17
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_RAW (BIT(16))
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_RAW_S 16
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_RAW (BIT(15))
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_RAW_S 15
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_RAW (BIT(14))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_RAW_S 14
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_RAW (BIT(13))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_RAW_S 13
#define BT_BITS_RW_BTDMTXABORT_P_INT_RAW (BIT(12))
#define BT_BITS_RW_BTDMTXABORT_P_INT_RAW_S 12
#define BT_BITS_RW_BTDMRXABORT_P_INT_RAW (BIT(11))
#define BT_BITS_RW_BTDMRXABORT_P_INT_RAW_S 11
#define BT_BITS_RW_BT_FH_DONE_P_INT_RAW (BIT(10))
#define BT_BITS_RW_BT_FH_DONE_P_INT_RAW_S 10
#define BT_BITS_RW_BLE_FH_DONE_P_INT_RAW (BIT(9))
#define BT_BITS_RW_BLE_FH_DONE_P_INT_RAW_S 9
#define BT_BITS_RW_TX_EN_P_INT_RAW (BIT(8))
#define BT_BITS_RW_TX_EN_P_INT_RAW_S 8
#define BT_BITS_RW_TX_EN_N_INT_RAW (BIT(7))
#define BT_BITS_RW_TX_EN_N_INT_RAW_S 7
#define BT_BITS_RW_RX_EN_P_INT_RAW (BIT(6))
#define BT_BITS_RW_RX_EN_P_INT_RAW_S 6
#define BT_BITS_RW_RX_EN_N_INT_RAW (BIT(5))
#define BT_BITS_RW_RX_EN_N_INT_RAW_S 5
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_RAW (BIT(4))
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_RAW_S 4
#define BT_BITS_BT_MUX_TX_START_INT_RAW (BIT(3))
#define BT_BITS_BT_MUX_TX_START_INT_RAW_S 3
#define BT_BITS_BT_MUX_TX_END_INT_RAW (BIT(2))
#define BT_BITS_BT_MUX_TX_END_INT_RAW_S 2
#define BT_BITS_BT_MUX_RX_END_INT_RAW (BIT(1))
#define BT_BITS_BT_MUX_RX_END_INT_RAW_S 1
#define BT_BITS_BT_MUX_BT_RX_START_INT_RAW (BIT(0))
#define BT_BITS_BT_MUX_BT_RX_START_INT_RAW_S 0

#define BT_BITS_INT1_ST_BT_REG (REG_BT_BASE + 0x0100)
#define BT_BITS_RW_TICK_625US_P_INT_ST (BIT(24))
#define BT_BITS_RW_TICK_625US_P_INT_ST_S 24
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_ST (BIT(23))
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_ST_S 23
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_ST (BIT(22))
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_ST_S 22
#define BT_BITS_RW_T0_INT_ST (BIT(21))
#define BT_BITS_RW_T0_INT_ST_S 21
#define BT_BITS_RW_T1_INT_ST (BIT(20))
#define BT_BITS_RW_T1_INT_ST_S 20
#define BT_BITS_RW_T2_INT_ST (BIT(19))
#define BT_BITS_RW_T2_INT_ST_S 19
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_ST (BIT(18))
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_ST_S 18
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_ST (BIT(17))
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_ST_S 17
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_ST (BIT(16))
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_ST_S 16
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_ST (BIT(15))
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_ST_S 15
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_ST (BIT(14))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_ST_S 14
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_ST (BIT(13))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_ST_S 13
#define BT_BITS_RW_BTDMTXABORT_P_INT_ST (BIT(12))
#define BT_BITS_RW_BTDMTXABORT_P_INT_ST_S 12
#define BT_BITS_RW_BTDMRXABORT_P_INT_ST (BIT(11))
#define BT_BITS_RW_BTDMRXABORT_P_INT_ST_S 11
#define BT_BITS_RW_BT_FH_DONE_P_INT_ST (BIT(10))
#define BT_BITS_RW_BT_FH_DONE_P_INT_ST_S 10
#define BT_BITS_RW_BLE_FH_DONE_P_INT_ST (BIT(9))
#define BT_BITS_RW_BLE_FH_DONE_P_INT_ST_S 9
#define BT_BITS_RW_TX_EN_P_INT_ST (BIT(8))
#define BT_BITS_RW_TX_EN_P_INT_ST_S 8
#define BT_BITS_RW_TX_EN_N_INT_ST (BIT(7))
#define BT_BITS_RW_TX_EN_N_INT_ST_S 7
#define BT_BITS_RW_RX_EN_P_INT_ST (BIT(6))
#define BT_BITS_RW_RX_EN_P_INT_ST_S 6
#define BT_BITS_RW_RX_EN_N_INT_ST (BIT(5))
#define BT_BITS_RW_RX_EN_N_INT_ST_S 5
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_ST (BIT(4))
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_ST_S 4
#define BT_BITS_BT_MUX_TX_START_INT_ST (BIT(3))
#define BT_BITS_BT_MUX_TX_START_INT_ST_S 3
#define BT_BITS_BT_MUX_TX_END_INT_ST (BIT(2))
#define BT_BITS_BT_MUX_TX_END_INT_ST_S 2
#define BT_BITS_BT_MUX_RX_END_INT_ST (BIT(1))
#define BT_BITS_BT_MUX_RX_END_INT_ST_S 1
#define BT_BITS_BT_MUX_BT_RX_START_INT_ST (BIT(0))
#define BT_BITS_BT_MUX_BT_RX_START_INT_ST_S 0

#define BT_BITS_INT1_CLR_BT_REG (REG_BT_BASE + 0x0104)
#define BT_BITS_RW_TICK_625US_P_INT_CLR (BIT(24))
#define BT_BITS_RW_TICK_625US_P_INT_CLR_S 24
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_CLR (BIT(23))
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_CLR_S 23
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_CLR (BIT(22))
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_CLR_S 22
#define BT_BITS_RW_T0_INT_CLR (BIT(21))
#define BT_BITS_RW_T0_INT_CLR_S 21
#define BT_BITS_RW_T1_INT_CLR (BIT(20))
#define BT_BITS_RW_T1_INT_CLR_S 20
#define BT_BITS_RW_T2_INT_CLR (BIT(19))
#define BT_BITS_RW_T2_INT_CLR_S 19
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_CLR (BIT(18))
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_CLR_S 18
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_CLR (BIT(17))
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_CLR_S 17
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_CLR (BIT(16))
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_CLR_S 16
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_CLR (BIT(15))
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_CLR_S 15
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_CLR (BIT(14))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_CLR_S 14
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_CLR (BIT(13))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_CLR_S 13
#define BT_BITS_RW_BTDMTXABORT_P_INT_CLR (BIT(12))
#define BT_BITS_RW_BTDMTXABORT_P_INT_CLR_S 12
#define BT_BITS_RW_BTDMRXABORT_P_INT_CLR (BIT(11))
#define BT_BITS_RW_BTDMRXABORT_P_INT_CLR_S 11
#define BT_BITS_RW_BT_FH_DONE_P_INT_CLR (BIT(10))
#define BT_BITS_RW_BT_FH_DONE_P_INT_CLR_S 10
#define BT_BITS_RW_BLE_FH_DONE_P_INT_CLR (BIT(9))
#define BT_BITS_RW_BLE_FH_DONE_P_INT_CLR_S 9
#define BT_BITS_RW_TX_EN_P_INT_CLR (BIT(8))
#define BT_BITS_RW_TX_EN_P_INT_CLR_S 8
#define BT_BITS_RW_TX_EN_N_INT_CLR (BIT(7))
#define BT_BITS_RW_TX_EN_N_INT_CLR_S 7
#define BT_BITS_RW_RX_EN_P_INT_CLR (BIT(6))
#define BT_BITS_RW_RX_EN_P_INT_CLR_S 6
#define BT_BITS_RW_RX_EN_N_INT_CLR (BIT(5))
#define BT_BITS_RW_RX_EN_N_INT_CLR_S 5
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_CLR (BIT(4))
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_CLR_S 4
#define BT_BITS_BT_MUX_TX_START_INT_CLR (BIT(3))
#define BT_BITS_BT_MUX_TX_START_INT_CLR_S 3
#define BT_BITS_BT_MUX_TX_END_INT_CLR (BIT(2))
#define BT_BITS_BT_MUX_TX_END_INT_CLR_S 2
#define BT_BITS_BT_MUX_RX_END_INT_CLR (BIT(1))
#define BT_BITS_BT_MUX_RX_END_INT_CLR_S 1
#define BT_BITS_BT_MUX_BT_RX_START_INT_CLR (BIT(0))
#define BT_BITS_BT_MUX_BT_RX_START_INT_CLR_S 0

#define BT_BITS_INT1_NMI_BT_REG (REG_BT_BASE + 0x0108)
#define BT_BITS_RW_TICK_625US_P_INT_NMI (BIT(24))
#define BT_BITS_RW_TICK_625US_P_INT_NMI_S 24
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_NMI (BIT(23))
#define BT_BITS_RW_BLE_TICK_PREFETCH_P_INT_NMI_S 23
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_NMI (BIT(22))
#define BT_BITS_RW_BT_TICK_PREFETCH_P_INT_NMI_S 22
#define BT_BITS_RW_T0_INT_NMI (BIT(21))
#define BT_BITS_RW_T0_INT_NMI_S 21
#define BT_BITS_RW_T1_INT_NMI (BIT(20))
#define BT_BITS_RW_T1_INT_NMI_S 20
#define BT_BITS_RW_T2_INT_NMI (BIT(19))
#define BT_BITS_RW_T2_INT_NMI_S 19
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_NMI (BIT(18))
#define BT_BITS_RW_BLE_PKTCNTL_DONE_P_INT_NMI_S 18
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_NMI (BIT(17))
#define BT_BITS_RW_BT_PKTCNTL_DONE_P_INT_NMI_S 17
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_NMI (BIT(16))
#define BT_BITS_RW_BT_DM_ARBITRATION_P_INT_NMI_S 16
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_NMI (BIT(15))
#define BT_BITS_RW_BLE_DM_ARBITRATION_P_INT_NMI_S 15
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_NMI (BIT(14))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_P_INT_NMI_S 14
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_NMI (BIT(13))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_P_INT_NMI_S 13
#define BT_BITS_RW_BTDMTXABORT_P_INT_NMI (BIT(12))
#define BT_BITS_RW_BTDMTXABORT_P_INT_NMI_S 12
#define BT_BITS_RW_BTDMRXABORT_P_INT_NMI (BIT(11))
#define BT_BITS_RW_BTDMRXABORT_P_INT_NMI_S 11
#define BT_BITS_RW_BT_FH_DONE_P_INT_NMI (BIT(10))
#define BT_BITS_RW_BT_FH_DONE_P_INT_NMI_S 10
#define BT_BITS_RW_BLE_FH_DONE_P_INT_NMI (BIT(9))
#define BT_BITS_RW_BLE_FH_DONE_P_INT_NMI_S 9
#define BT_BITS_RW_TX_EN_P_INT_NMI (BIT(8))
#define BT_BITS_RW_TX_EN_P_INT_NMI_S 8
#define BT_BITS_RW_TX_EN_N_INT_NMI (BIT(7))
#define BT_BITS_RW_TX_EN_N_INT_NMI_S 7
#define BT_BITS_RW_RX_EN_P_INT_NMI (BIT(6))
#define BT_BITS_RW_RX_EN_P_INT_NMI_S 6
#define BT_BITS_RW_RX_EN_N_INT_NMI (BIT(5))
#define BT_BITS_RW_RX_EN_N_INT_NMI_S 5
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_NMI (BIT(4))
#define BT_BITS_RW_SYNCFOUND_PULSE_DELAYED_INT_NMI_S 4
#define BT_BITS_BT_MUX_TX_START_INT_NMI (BIT(3))
#define BT_BITS_BT_MUX_TX_START_INT_NMI_S 3
#define BT_BITS_BT_MUX_TX_END_INT_NMI (BIT(2))
#define BT_BITS_BT_MUX_TX_END_INT_NMI_S 2
#define BT_BITS_BT_MUX_RX_END_INT_NMI (BIT(1))
#define BT_BITS_BT_MUX_RX_END_INT_NMI_S 1
#define BT_BITS_BT_MUX_BT_RX_START_INT_NMI (BIT(0))
#define BT_BITS_BT_MUX_BT_RX_START_INT_NMI_S 0

#define BT_BITS_BT_RW_STATUS0_REG (REG_BT_BASE + 0x010c)
#define BT_BITS_RW_BT_GRANTED (BIT(31))
#define BT_BITS_RW_BT_GRANTED_S 31
#define BT_BITS_RW_LE_GRANTED (BIT(30))
#define BT_BITS_RW_LE_GRANTED_S 30
#define BT_BITS_RW_RADCNTL_BTDM_TX (BIT(29))
#define BT_BITS_RW_RADCNTL_BTDM_TX_S 29
#define BT_BITS_RW_RADCNTL_BTDM_RX (BIT(28))
#define BT_BITS_RW_RADCNTL_BTDM_RX_S 28
#define BT_BITS_RW_BTDM_CHANNEL_INDEX 0x0000007F
#define BT_BITS_RW_BTDM_CHANNEL_INDEX_S 21
#define BT_BITS_RW_TX_EN (BIT(20))
#define BT_BITS_RW_TX_EN_S 20
#define BT_BITS_RW_RX_EN (BIT(19))
#define BT_BITS_RW_RX_EN_S 19
#define BT_BITS_RW_TXPWR 0x000000FF
#define BT_BITS_RW_TXPWR_S 11
#define BT_BITS_RW_LE_EN (BIT(10))
#define BT_BITS_RW_LE_EN_S 10
#define BT_BITS_RW_TX_EDR (BIT(9))
#define BT_BITS_RW_TX_EDR_S 9
#define BT_BITS_RW_FREQ 0x000000FF
#define BT_BITS_RW_FREQ_S 1
#define BT_BITS_RW_EVENT_IN_PROCESS (BIT(0))
#define BT_BITS_RW_EVENT_IN_PROCESS_S 0

#define BT_BITS_BT_RW_STATUS1_REG (REG_BT_BASE + 0x0110)
#define BT_BITS_RW_TX_BRIDGE_ST 0x00000007
#define BT_BITS_RW_TX_BRIDGE_ST_S 29
#define BT_BITS_RW_MUX_TX_ST 0x00000003
#define BT_BITS_RW_MUX_TX_ST_S 27
#define BT_BITS_RW_RX_BRIDGE_ST 0x00000007
#define BT_BITS_RW_RX_BRIDGE_ST_S 24
#define BT_BITS_RW_MUX_RX_ST 0x00000003
#define BT_BITS_RW_MUX_RX_ST_S 22
#define BT_BITS_RW_BT_CURRENTPRIO_VALID (BIT(21))
#define BT_BITS_RW_BT_CURRENTPRIO_VALID_S 21
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID (BIT(20))
#define BT_BITS_RW_BLE_CURRENTPRIO_VALID_S 20
#define BT_BITS_RW_BTDMTXABORT (BIT(19))
#define BT_BITS_RW_BTDMTXABORT_S 19
#define BT_BITS_RW_BTDMRXABORT (BIT(18))
#define BT_BITS_RW_BTDMRXABORT_S 18
#define BT_BITS_RW_RADIO_CNTL_FSM_FIX_TX (BIT(17))
#define BT_BITS_RW_RADIO_CNTL_FSM_FIX_TX_S 17
#define BT_BITS_RW_RADIO_CNTL_FSM_FIX_RX (BIT(16))
#define BT_BITS_RW_RADIO_CNTL_FSM_FIX_RX_S 16
#define BT_BITS_RW_BT_NCBO_THRESH 0x0000000F
#define BT_BITS_RW_BT_NCBO_THRESH_S 12
#define BT_BITS_RW_RSSI_ALWAYS_READY (BIT(11))
#define BT_BITS_RW_RSSI_ALWAYS_READY_S 11

#define BT_BITS_BT_RW_EM_BASE0_CFG_REG (REG_BT_BASE + 0x0114)
#define BT_BITS_RW_EM_BASE0_EN (BIT(31))
#define BT_BITS_RW_EM_BASE0_EN_S 31
#define BT_BITS_RW_EM_BASE0_START 0x00003FFF
#define BT_BITS_RW_EM_BASE0_START_S 17
#define BT_BITS_RW_EM_BASE0_END 0x00003FFF
#define BT_BITS_RW_EM_BASE0_END_S 3

#define BT_BITS_BT_RW_EM_BASE0_REG (REG_BT_BASE + 0x0118)
#define BT_BITS_RW_EM_BASE0 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE0_S 2

#define BT_BITS_BT_RW_EM_BASE1_CFG_REG (REG_BT_BASE + 0x011c)
#define BT_BITS_RW_EM_BASE1_EN (BIT(31))
#define BT_BITS_RW_EM_BASE1_EN_S 31
#define BT_BITS_RW_EM_BASE1_START 0x00003FFF
#define BT_BITS_RW_EM_BASE1_START_S 17
#define BT_BITS_RW_EM_BASE1_END 0x00003FFF
#define BT_BITS_RW_EM_BASE1_END_S 3

#define BT_BITS_BT_RW_EM_BASE1_REG (REG_BT_BASE + 0x0120)
#define BT_BITS_RW_EM_BASE1 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE1_S 2

#define BT_BITS_BT_RW_EM_BASE2_CFG_REG (REG_BT_BASE + 0x0124)
#define BT_BITS_RW_EM_BASE2_EN (BIT(31))
#define BT_BITS_RW_EM_BASE2_EN_S 31
#define BT_BITS_RW_EM_BASE2_START 0x00003FFF
#define BT_BITS_RW_EM_BASE2_START_S 17
#define BT_BITS_RW_EM_BASE2_END 0x00003FFF
#define BT_BITS_RW_EM_BASE2_END_S 3

#define BT_BITS_BT_RW_EM_BASE2_REG (REG_BT_BASE + 0x0128)
#define BT_BITS_RW_EM_BASE2 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE2_S 2

#define BT_BITS_BT_RW_EM_BASE3_CFG_REG (REG_BT_BASE + 0x012c)
#define BT_BITS_RW_EM_BASE3_EN (BIT(31))
#define BT_BITS_RW_EM_BASE3_EN_S 31
#define BT_BITS_RW_EM_BASE3_START 0x00003FFF
#define BT_BITS_RW_EM_BASE3_START_S 17
#define BT_BITS_RW_EM_BASE3_END 0x00003FFF
#define BT_BITS_RW_EM_BASE3_END_S 3

#define BT_BITS_BT_RW_EM_BASE3_REG (REG_BT_BASE + 0x0130)
#define BT_BITS_RW_EM_BASE3 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE3_S 2

#define BT_BITS_BT_RW_EM_BASE4_CFG_REG (REG_BT_BASE + 0x0134)
#define BT_BITS_RW_EM_BASE4_EN (BIT(31))
#define BT_BITS_RW_EM_BASE4_EN_S 31
#define BT_BITS_RW_EM_BASE4_START 0x00003FFF
#define BT_BITS_RW_EM_BASE4_START_S 17
#define BT_BITS_RW_EM_BASE4_END 0x00003FFF
#define BT_BITS_RW_EM_BASE4_END_S 3

#define BT_BITS_BT_RW_EM_BASE4_REG (REG_BT_BASE + 0x0138)
#define BT_BITS_RW_EM_BASE4 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE4_S 2

#define BT_BITS_BT_RW_EM_BASE5_CFG_REG (REG_BT_BASE + 0x013c)
#define BT_BITS_RW_EM_BASE5_EN (BIT(31))
#define BT_BITS_RW_EM_BASE5_EN_S 31
#define BT_BITS_RW_EM_BASE5_START 0x00003FFF
#define BT_BITS_RW_EM_BASE5_START_S 17
#define BT_BITS_RW_EM_BASE5_END 0x00003FFF
#define BT_BITS_RW_EM_BASE5_END_S 3

#define BT_BITS_BT_RW_EM_BASE5_REG (REG_BT_BASE + 0x0140)
#define BT_BITS_RW_EM_BASE5 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE5_S 2

#define BT_BITS_BT_RW_EM_BASE6_CFG_REG (REG_BT_BASE + 0x0144)
#define BT_BITS_RW_EM_BASE6_EN (BIT(31))
#define BT_BITS_RW_EM_BASE6_EN_S 31
#define BT_BITS_RW_EM_BASE6_START 0x00003FFF
#define BT_BITS_RW_EM_BASE6_START_S 17
#define BT_BITS_RW_EM_BASE6_END 0x00003FFF
#define BT_BITS_RW_EM_BASE6_END_S 3

#define BT_BITS_BT_RW_EM_BASE6_REG (REG_BT_BASE + 0x0148)
#define BT_BITS_RW_EM_BASE6 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE6_S 2

#define BT_BITS_BT_RW_EM_BASE7_CFG_REG (REG_BT_BASE + 0x014c)
#define BT_BITS_RW_EM_BASE7_EN (BIT(31))
#define BT_BITS_RW_EM_BASE7_EN_S 31
#define BT_BITS_RW_EM_BASE7_START 0x00003FFF
#define BT_BITS_RW_EM_BASE7_START_S 17
#define BT_BITS_RW_EM_BASE7_END 0x00003FFF
#define BT_BITS_RW_EM_BASE7_END_S 3

#define BT_BITS_BT_RW_EM_BASE7_REG (REG_BT_BASE + 0x0150)
#define BT_BITS_RW_EM_BASE7 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE7_S 2

#define BT_BITS_BT_RW_EM_BASE8_CFG_REG (REG_BT_BASE + 0x0154)
#define BT_BITS_RW_EM_BASE8_EN (BIT(31))
#define BT_BITS_RW_EM_BASE8_EN_S 31
#define BT_BITS_RW_EM_BASE8_START 0x00003FFF
#define BT_BITS_RW_EM_BASE8_START_S 17
#define BT_BITS_RW_EM_BASE8_END 0x00003FFF
#define BT_BITS_RW_EM_BASE8_END_S 3

#define BT_BITS_BT_RW_EM_BASE8_REG (REG_BT_BASE + 0x0158)
#define BT_BITS_RW_EM_BASE8 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE8_S 2

#define BT_BITS_BT_RW_EM_BASE9_CFG_REG (REG_BT_BASE + 0x015c)
#define BT_BITS_RW_EM_BASE9_EN (BIT(31))
#define BT_BITS_RW_EM_BASE9_EN_S 31
#define BT_BITS_RW_EM_BASE9_START 0x00003FFF
#define BT_BITS_RW_EM_BASE9_START_S 17
#define BT_BITS_RW_EM_BASE9_END 0x00003FFF
#define BT_BITS_RW_EM_BASE9_END_S 3

#define BT_BITS_BT_RW_EM_BASE9_REG (REG_BT_BASE + 0x0160)
#define BT_BITS_RW_EM_BASE9 0x3FFFFFFF
#define BT_BITS_RW_EM_BASE9_S 2

#define BT_BITS_BT_RW_CLKN_REG (REG_BT_BASE + 0x0164)
#define BT_BITS_CLKNCNT 0x0FFFFFFF
#define BT_BITS_CLKNCNT_S 4

#define BT_BITS_BT_RW_FINE_TIME_REG (REG_BT_BASE + 0x0168)
#define BT_BITS_FINECNT 0x000003FF
#define BT_BITS_FINECNT_S 22

#define BT_BITS_BT_RW_TIMER0_CFG0_REG (REG_BT_BASE + 0x016c)
#define BT_BITS_RW_T0_CLKNCNT_TARGET 0x07FFFFFF
#define BT_BITS_RW_T0_CLKNCNT_TARGET_S 5
#define BT_BITS_RW_T0_CLKNCNT_TARGET_EN (BIT(4))
#define BT_BITS_RW_T0_CLKNCNT_TARGET_EN_S 4
#define BT_BITS_RW_T0_EN (BIT(3))
#define BT_BITS_RW_T0_EN_S 3

#define BT_BITS_BT_RW_TIMER0_CFG1_REG (REG_BT_BASE + 0x0170)
#define BT_BITS_RW_T0_FCNT_TARGET 0x000003FF
#define BT_BITS_RW_T0_FCNT_TARGET_S 22

#define BT_BITS_BT_RW_TIMER1_CFG0_REG (REG_BT_BASE + 0x0174)
#define BT_BITS_RW_T1_CLKNCNT_TARGET 0x07FFFFFF
#define BT_BITS_RW_T1_CLKNCNT_TARGET_S 5
#define BT_BITS_RW_T1_CLKNCNT_TARGET_EN (BIT(4))
#define BT_BITS_RW_T1_CLKNCNT_TARGET_EN_S 4
#define BT_BITS_RW_T1_EN (BIT(3))
#define BT_BITS_RW_T1_EN_S 3

#define BT_BITS_BT_RW_TIMER1_CFG1_REG (REG_BT_BASE + 0x0178)
#define BT_BITS_RW_T1_FCNT_TARGET 0x000003FF
#define BT_BITS_RW_T1_FCNT_TARGET_S 22

#define BT_BITS_BT_RW_TIMER2_CFG0_REG (REG_BT_BASE + 0x017c)
#define BT_BITS_RW_T2_CLKNCNT_TARGET 0x07FFFFFF
#define BT_BITS_RW_T2_CLKNCNT_TARGET_S 5
#define BT_BITS_RW_T2_CLKNCNT_TARGET_EN (BIT(4))
#define BT_BITS_RW_T2_CLKNCNT_TARGET_EN_S 4
#define BT_BITS_RW_T2_EN (BIT(3))
#define BT_BITS_RW_T2_EN_S 3

#define BT_BITS_BT_RW_TIMER2_CFG1_REG (REG_BT_BASE + 0x0180)
#define BT_BITS_RW_T2_FCNT_TARGET 0x000003FF
#define BT_BITS_RW_T2_FCNT_TARGET_S 22

#define BT_BITS_BT_IF_STATE_REG (REG_BT_BASE + 0x0184)
#define BT_BITS_IF_STATE_MAIN 0x0000000F
#define BT_BITS_IF_STATE_MAIN_S 0

#define BT_BITS_BT_DPSK_STATE_REG (REG_BT_BASE + 0x0188)
#define BT_BITS_DPSK_STATE 0x00000003
#define BT_BITS_DPSK_STATE_S 0

#define BT_BITS_BT_DPSK_STATE_BD_REG (REG_BT_BASE + 0x018c)
#define BT_BITS_DPSK_STATE_BEGIN_DELAY 0x00000003
#define BT_BITS_DPSK_STATE_BEGIN_DELAY_S 0

#define BT_BITS_BT_UP_STATE_REG (REG_BT_BASE + 0x0190)
#define BT_BITS_UP_STATE_DELAY 0x0000000F
#define BT_BITS_UP_STATE_DELAY_S 0

#define BT_BITS_BT_RAMP_STATE_REG (REG_BT_BASE + 0x0194)
#define BT_BITS_STATE_RAMP 0x0000000F
#define BT_BITS_STATE_RAMP_S 0

#define BT_BITS_BT_RW_BT_INT_CNT0_REG (REG_BT_BASE + 0x0198)
#define BT_BITS_CNT_SKET_EN (BIT(31))
#define BT_BITS_CNT_SKET_EN_S 31
#define BT_BITS_CNT_SWINT_EN (BIT(30))
#define BT_BITS_CNT_SWINT_EN_S 30
#define BT_BITS_CNT_APFA_EN (BIT(29))
#define BT_BITS_CNT_APFA_EN_S 29
#define BT_BITS_CNT_FRAME_EN (BIT(28))
#define BT_BITS_CNT_FRAME_EN_S 28
#define BT_BITS_CNT_ERROR_EN (BIT(27))
#define BT_BITS_CNT_ERROR_EN_S 27
#define BT_BITS_CNT_GROSS_EN (BIT(26))
#define BT_BITS_CNT_GROSS_EN_S 26
#define BT_BITS_CNT_FINE_EN (BIT(25))
#define BT_BITS_CNT_FINE_EN_S 25
#define BT_BITS_CNT_AUDIO0_EN (BIT(24))
#define BT_BITS_CNT_AUDIO0_EN_S 24
#define BT_BITS_CNT_AUDIO1_EN (BIT(23))
#define BT_BITS_CNT_AUDIO1_EN_S 23
#define BT_BITS_CNT_AUDIO2_EN (BIT(22))
#define BT_BITS_CNT_AUDIO2_EN_S 22
#define BT_BITS_CNT_RX_EN (BIT(21))
#define BT_BITS_CNT_RX_EN_S 21
#define BT_BITS_CNT_CLK_EN (BIT(20))
#define BT_BITS_CNT_CLK_EN_S 20
#define BT_BITS_CNT_SKET_CLEAR (BIT(19))
#define BT_BITS_CNT_SKET_CLEAR_S 19
#define BT_BITS_CNT_SWINT_CLEAR (BIT(18))
#define BT_BITS_CNT_SWINT_CLEAR_S 18
#define BT_BITS_CNT_APFA_CLEAR (BIT(17))
#define BT_BITS_CNT_APFA_CLEAR_S 17
#define BT_BITS_CNT_FRAME_CLEAR (BIT(16))
#define BT_BITS_CNT_FRAME_CLEAR_S 16
#define BT_BITS_CNT_ERROR_CLEAR (BIT(15))
#define BT_BITS_CNT_ERROR_CLEAR_S 15
#define BT_BITS_CNT_GROSS_CLEAR (BIT(14))
#define BT_BITS_CNT_GROSS_CLEAR_S 14
#define BT_BITS_CNT_FINE_CLEAR (BIT(13))
#define BT_BITS_CNT_FINE_CLEAR_S 13
#define BT_BITS_CNT_AUDIO0_CLEAR (BIT(12))
#define BT_BITS_CNT_AUDIO0_CLEAR_S 12
#define BT_BITS_CNT_AUDIO1_CLEAR (BIT(11))
#define BT_BITS_CNT_AUDIO1_CLEAR_S 11
#define BT_BITS_CNT_AUDIO2_CLEAR (BIT(10))
#define BT_BITS_CNT_AUDIO2_CLEAR_S 10
#define BT_BITS_CNT_RX_CLEAR (BIT(9))
#define BT_BITS_CNT_RX_CLEAR_S 9
#define BT_BITS_CNT_CLK_CLEAR (BIT(8))
#define BT_BITS_CNT_CLK_CLEAR_S 8
#define BT_BITS_CLK_EN (BIT(0))
#define BT_BITS_CLK_EN_S 0

#define BT_BITS_BT_RW_BT_INT_CNT1_REG (REG_BT_BASE + 0x019c)
#define BT_BITS_CNT_SKET 0x00000003
#define BT_BITS_CNT_SKET_S 30
#define BT_BITS_CNT_SWINT 0x00000003
#define BT_BITS_CNT_SWINT_S 28
#define BT_BITS_CNT_APFA 0x00000003
#define BT_BITS_CNT_APFA_S 26
#define BT_BITS_CNT_FRAME 0x00000003
#define BT_BITS_CNT_FRAME_S 24
#define BT_BITS_CNT_ERROR 0x00000003
#define BT_BITS_CNT_ERROR_S 22
#define BT_BITS_CNT_GROSS 0x00000003
#define BT_BITS_CNT_GROSS_S 20
#define BT_BITS_CNT_FINE 0x00000003
#define BT_BITS_CNT_FINE_S 18
#define BT_BITS_CNT_AUDIO0 0x00000003
#define BT_BITS_CNT_AUDIO0_S 16
#define BT_BITS_CNT_AUDIO1 0x00000003
#define BT_BITS_CNT_AUDIO1_S 14
#define BT_BITS_CNT_AUDIO2 0x00000003
#define BT_BITS_CNT_AUDIO2_S 12
#define BT_BITS_CNT_RX 0x00000003
#define BT_BITS_CNT_RX_S 10
#define BT_BITS_CNT_CLK 0x00000003
#define BT_BITS_CNT_CLK_S 8

#define BT_BITS_BT_RW_BT_INT_CNT2_REG (REG_BT_BASE + 0x01a0)
#define BT_BITS_APFA_TIME_NOW 0x0000000F
#define BT_BITS_APFA_TIME_NOW_S 28
#define BT_BITS_APFA_TIME_PRE 0x0000000F
#define BT_BITS_APFA_TIME_PRE_S 24
#define BT_BITS_FRAME_TIME_NOW 0x0000000F
#define BT_BITS_FRAME_TIME_NOW_S 20
#define BT_BITS_FRAME_TIME_PRE 0x0000000F
#define BT_BITS_FRAME_TIME_PRE_S 16
#define BT_BITS_ERROR_TIME_NOW 0x0000000F
#define BT_BITS_ERROR_TIME_NOW_S 12
#define BT_BITS_ERROR_TIME_PRE 0x0000000F
#define BT_BITS_ERROR_TIME_PRE_S 8
#define BT_BITS_RX_TIME_NOW 0x0000000F
#define BT_BITS_RX_TIME_NOW_S 4
#define BT_BITS_RX_TIME_PRE 0x0000000F
#define BT_BITS_RX_TIME_PRE_S 0

#define BT_BITS_BT_RW_PRIVACY_ERROR_CFG_REG (REG_BT_BASE + 0x01a0)
#define BT_BITS_PRIVACY_ERROR0_EN (BIT(31))
#define BT_BITS_PRIVACY_ERROR0_EN_S 31
#define BT_BITS_PRIVACY_ERROR1_EN (BIT(30))
#define BT_BITS_PRIVACY_ERROR1_EN_S 30
#define BT_BITS_PRIVACY_ERROR2_EN (BIT(29))
#define BT_BITS_PRIVACY_ERROR2_EN_S 29
#define BT_BITS_PRIVACY_ERROR3_EN (BIT(28))
#define BT_BITS_PRIVACY_ERROR3_EN_S 28

#define BT_BITS_BT_ANT_CFG_REG (REG_BT_BASE + 0x01a4)
#define BT_BITS_BT_TX_ANT_EN (BIT(31))
#define BT_BITS_BT_TX_ANT_EN_S 31
#define BT_BITS_BT_RX_ANT_EN (BIT(30))
#define BT_BITS_BT_RX_ANT_EN_S 30
#define BT_BITS_LE_TX_ANT_EN (BIT(29))
#define BT_BITS_LE_TX_ANT_EN_S 29
#define BT_BITS_LE_RX_ANT_EN (BIT(28))
#define BT_BITS_LE_RX_ANT_EN_S 28

#define BT_BITS_BT_RW_PKTCNTL_REG (REG_BT_BASE + 0x01a8)
#define BT_BITS_RW_BT_ABORT (BIT(31))
#define BT_BITS_RW_BT_ABORT_S 31
#define BT_BITS_RW_LE_ABORT (BIT(30))
#define BT_BITS_RW_LE_ABORT_S 30

#define BT_BITS_BT_BB_DATE_REG (REG_BT_BASE + 0x01ac)
#define BT_BITS_BT_BB_DATE 0x0FFFFFFF
#define BT_BITS_BT_BB_DATE_S 0
#define BT_BITS_BT_BB_DATE_VERSION 0x1805170
