
#define BT_V2_BITS_FE_CTRL_0_REG (REG_BT_V2_BASE + 0x0000)
#define BT_V2_BITS_FE_BT_MODE_EN_SEL (BIT(31))
#define BT_V2_BITS_FE_BT_MODE_EN_SEL_S 31
#define BT_V2_BITS_BT_MODE_DELAY 0x000003FF
#define BT_V2_BITS_BT_MODE_DELAY_S 21
#define BT_V2_BITS_BT_MODE_ON_INIT 0x000000FF
#define BT_V2_BITS_BT_MODE_ON_INIT_S 13
#define BT_V2_BITS_BT_MODE_ON_WAIT 0x000000FF
#define BT_V2_BITS_BT_MODE_ON_WAIT_S 5
#define BT_V2_BITS_TX_SWAP (BIT(4))
#define BT_V2_BITS_TX_SWAP_S 4
#define BT_V2_BITS_RX_SWAP (BIT(3))
#define BT_V2_BITS_RX_SWAP_S 3
#define BT_V2_BITS_DEMOD_EN_FORCE_ON (BIT(2))
#define BT_V2_BITS_DEMOD_EN_FORCE_ON_S 2
#define BT_V2_BITS_DEMOD_EN_FORCE (BIT(1))
#define BT_V2_BITS_DEMOD_EN_FORCE_S 1

#define BT_V2_BITS_FE_CTRL_1_REG (REG_BT_V2_BASE + 0x0004)
#define BT_V2_BITS_BT_MODE_OFF_INIT 0x000000FF
#define BT_V2_BITS_BT_MODE_OFF_INIT_S 24
#define BT_V2_BITS_BT_MODE_OFF_WAIT 0x000000FF
#define BT_V2_BITS_BT_MODE_OFF_WAIT_S 16
#define BT_V2_BITS_BT_PRE_DET (BIT(15))
#define BT_V2_BITS_BT_PRE_DET_S 15
#define BT_V2_BITS_RW_TXPWR_MSB 0x00000003
#define BT_V2_BITS_RW_TXPWR_MSB_S 13
#define BT_V2_BITS_RW_TXPWR_EN (BIT(12))
#define BT_V2_BITS_RW_TXPWR_EN_S 12
#define BT_V2_BITS_RW_TX_EN_FORCE_ON (BIT(11))
#define BT_V2_BITS_RW_TX_EN_FORCE_ON_S 11
#define BT_V2_BITS_RW_TX_EN_FORCE (BIT(10))
#define BT_V2_BITS_RW_TX_EN_FORCE_S 10
#define BT_V2_BITS_RW_RX_EN_FORCE_ON (BIT(9))
#define BT_V2_BITS_RW_RX_EN_FORCE_ON_S 9
#define BT_V2_BITS_RW_RX_EN_FORCE (BIT(8))
#define BT_V2_BITS_RW_RX_EN_FORCE_S 8
#define BT_V2_BITS_RW_RATE_FORCE_ON (BIT(7))
#define BT_V2_BITS_RW_RATE_FORCE_ON_S 7
#define BT_V2_BITS_RW_RATE_FORCE 0x00000003
#define BT_V2_BITS_RW_RATE_FORCE_S 5
#define BT_V2_BITS_RW_SYNW_FORCE_ON (BIT(4))
#define BT_V2_BITS_RW_SYNW_FORCE_ON_S 4
#define BT_V2_BITS_RW_LE_EN_FORCE_ON (BIT(3))
#define BT_V2_BITS_RW_LE_EN_FORCE_ON_S 3
#define BT_V2_BITS_RW_LE_EN_FORCE (BIT(2))
#define BT_V2_BITS_RW_LE_EN_FORCE_S 2
#define BT_V2_BITS_TX_INTERFACE_RESET (BIT(1))
#define BT_V2_BITS_TX_INTERFACE_RESET_S 1

#define BT_V2_BITS_MIXER_CFG_0_REG (REG_BT_V2_BASE + 0x0008)
#define BT_V2_BITS_RF_OFFSET_EN (BIT(31))
#define BT_V2_BITS_RF_OFFSET_EN_S 31
#define BT_V2_BITS_RX_RF_OFFSET_ADD (BIT(30))
#define BT_V2_BITS_RX_RF_OFFSET_ADD_S 30
#define BT_V2_BITS_TX_RF_OFFSET_ADD (BIT(29))
#define BT_V2_BITS_TX_RF_OFFSET_ADD_S 29
#define BT_V2_BITS_RX_HOPPE_N500K 0x0000003F
#define BT_V2_BITS_RX_HOPPE_N500K_S 23
#define BT_V2_BITS_HOPPE_N500K 0x0000003F
#define BT_V2_BITS_HOPPE_N500K_S 17
#define BT_V2_BITS_FREQOS 0x0000FFFF
#define BT_V2_BITS_FREQOS_S 1
#define BT_V2_BITS_FREQOS_EN (BIT(0))
#define BT_V2_BITS_FREQOS_EN_S 0

#define BT_V2_BITS_MIXER_CFG_1_REG (REG_BT_V2_BASE + 0x000c)
#define BT_V2_BITS_FSTEP_500K 0x000FFFFF
#define BT_V2_BITS_FSTEP_500K_S 12
#define BT_V2_BITS_MODU_INDX 0x0000000F
#define BT_V2_BITS_MODU_INDX_S 8

#define BT_V2_BITS_TX_CFG_0_REG (REG_BT_V2_BASE + 0x0010)
#define BT_V2_BITS_TX_ON_DELAY 0x000007FF
#define BT_V2_BITS_TX_ON_DELAY_S 21
#define BT_V2_BITS_TX_HEAD_DELAY 0x000000FF
#define BT_V2_BITS_TX_HEAD_DELAY_S 13
#define BT_V2_BITS_LE_TX_ON_DELAY 0x000007FF
#define BT_V2_BITS_LE_TX_ON_DELAY_S 2

#define BT_V2_BITS_TX_CFG_1_REG (REG_BT_V2_BASE + 0x0014)
#define BT_V2_BITS_LE_TX_HEAD_DELAY 0x000000FF
#define BT_V2_BITS_LE_TX_HEAD_DELAY_S 24
#define BT_V2_BITS_TX_OFF_DELAY 0x000000FF
#define BT_V2_BITS_TX_OFF_DELAY_S 16
#define BT_V2_BITS_TX_EDR_OFF_DELAY 0x000000FF
#define BT_V2_BITS_TX_EDR_OFF_DELAY_S 8
#define BT_V2_BITS_TX_RAMPUP_DELAY 0x000000FF
#define BT_V2_BITS_TX_RAMPUP_DELAY_S 0

#define BT_V2_BITS_TX_CFG_2_REG (REG_BT_V2_BASE + 0x0018)
#define BT_V2_BITS_TX_RAMPDOWN_DELAY 0x000000FF
#define BT_V2_BITS_TX_RAMPDOWN_DELAY_S 24
#define BT_V2_BITS_LE_TX_RAMPUP_DELAY 0x000000FF
#define BT_V2_BITS_LE_TX_RAMPUP_DELAY_S 16
#define BT_V2_BITS_LE_TX_RAMPDOWN_DELAY 0x000000FF
#define BT_V2_BITS_LE_TX_RAMPDOWN_DELAY_S 8
#define BT_V2_BITS_TX_RAMP_DELAY 0x000000FF
#define BT_V2_BITS_TX_RAMP_DELAY_S 0

#define BT_V2_BITS_TX_CFG_3_REG (REG_BT_V2_BASE + 0x001c)
#define BT_V2_BITS_TX_EDR_DELAY 0x000000FF
#define BT_V2_BITS_TX_EDR_DELAY_S 24
#define BT_V2_BITS_DPSK_OUT_END_DELAY 0x000003FF
#define BT_V2_BITS_DPSK_OUT_END_DELAY_S 14
#define BT_V2_BITS_NEGATE_GFSK_SYMBOL (BIT(13))
#define BT_V2_BITS_NEGATE_GFSK_SYMBOL_S 13

#define BT_V2_BITS_RX_FILTER_CFG_REG (REG_BT_V2_BASE + 0x0020)
#define BT_V2_BITS_OUT_BB_SEL (BIT(31))
#define BT_V2_BITS_OUT_BB_SEL_S 31
#define BT_V2_BITS_OUT_POWER_SEL (BIT(30))
#define BT_V2_BITS_OUT_POWER_SEL_S 30
#define BT_V2_BITS_FILTER_ENABLE (BIT(29))
#define BT_V2_BITS_FILTER_ENABLE_S 29
#define BT_V2_BITS_DPO_START_DELAY 0x0000003F
#define BT_V2_BITS_DPO_START_DELAY_S 23
#define BT_V2_BITS_DPO_EN (BIT(22))
#define BT_V2_BITS_DPO_EN_S 22
#define BT_V2_BITS_LEN_SHIFT 0x0000000F
#define BT_V2_BITS_LEN_SHIFT_S 18
#define BT_V2_BITS_DPO_SHIFT_INIT 0x0000000F
#define BT_V2_BITS_DPO_SHIFT_INIT_S 14
#define BT_V2_BITS_DPO_SHIFT_SAMP 0x0000000F
#define BT_V2_BITS_DPO_SHIFT_SAMP_S 10
#define BT_V2_BITS_SUM_PHASE_SHIFT 0x0000000F
#define BT_V2_BITS_SUM_PHASE_SHIFT_S 6
#define BT_V2_BITS_DPO_CONSIST_THRESH 0x0000003F
#define BT_V2_BITS_DPO_CONSIST_THRESH_S 0

#define BT_V2_BITS_RX_DEMOD_0_REG (REG_BT_V2_BASE + 0x0024)
#define BT_V2_BITS_SAMP_SEL_EN (BIT(31))
#define BT_V2_BITS_SAMP_SEL_EN_S 31
#define BT_V2_BITS_LEN_SAMP 0x0000000F
#define BT_V2_BITS_LEN_SAMP_S 27
#define BT_V2_BITS_DP_NONSTOP (BIT(26))
#define BT_V2_BITS_DP_NONSTOP_S 26
#define BT_V2_BITS_PF_DELTA_THRESH_0 0x000003FF
#define BT_V2_BITS_PF_DELTA_THRESH_0_S 16
#define BT_V2_BITS_PF_DELTA_THRESH_1 0x000003FF
#define BT_V2_BITS_PF_DELTA_THRESH_1_S 6
#define BT_V2_BITS_PF_CORR_ROUND_0 0x00000003
#define BT_V2_BITS_PF_CORR_ROUND_0_S 4
#define BT_V2_BITS_PF_CORR_ROUND_1 0x00000003
#define BT_V2_BITS_PF_CORR_ROUND_1_S 2
#define BT_V2_BITS_DPO_DSAMP_EN (BIT(1))
#define BT_V2_BITS_DPO_DSAMP_EN_S 1

#define BT_V2_BITS_RX_DEMOD_1_REG (REG_BT_V2_BASE + 0x0028)
#define BT_V2_BITS_PF_CORR_MASK_0 0x000FFFFF
#define BT_V2_BITS_PF_CORR_MASK_0_S 12
#define BT_V2_BITS_DPO_CONSIST_THRESH_2 0x0000003F
#define BT_V2_BITS_DPO_CONSIST_THRESH_2_S 6
#define BT_V2_BITS_SAMP_AMP_SEL 0x00000003
#define BT_V2_BITS_SAMP_AMP_SEL_S 4
#define BT_V2_BITS_DPO_PREAMBLE_SEL 0x00000003
#define BT_V2_BITS_DPO_PREAMBLE_SEL_S 2
#define BT_V2_BITS_GFILTER_SEL_1M (BIT(1))
#define BT_V2_BITS_GFILTER_SEL_1M_S 1
#define BT_V2_BITS_GFILTER_SEL_2M (BIT(0))
#define BT_V2_BITS_GFILTER_SEL_2M_S 0

#define BT_V2_BITS_RX_DEMOD_2_REG (REG_BT_V2_BASE + 0x002c)
#define BT_V2_BITS_PF_CORR_MASK_1 0x000FFFFF
#define BT_V2_BITS_PF_CORR_MASK_1_S 12
#define BT_V2_BITS_DPO_SAMP_THRESH 0x000000FF
#define BT_V2_BITS_DPO_SAMP_THRESH_S 4
#define BT_V2_BITS_DPO_EARLY_EN (BIT(3))
#define BT_V2_BITS_DPO_EARLY_EN_S 3

#define BT_V2_BITS_RX_DEMOD_3_REG (REG_BT_V2_BASE + 0x0030)
#define BT_V2_BITS_PF_CORR_MASK_2 0x000FFFFF
#define BT_V2_BITS_PF_CORR_MASK_2_S 12

#define BT_V2_BITS_RX_DEMOD_4_REG (REG_BT_V2_BASE + 0x0034)
#define BT_V2_BITS_PF_WAIT_0 0x000003FF
#define BT_V2_BITS_PF_WAIT_0_S 22
#define BT_V2_BITS_PF_WAIT_1 0x000003FF
#define BT_V2_BITS_PF_WAIT_1_S 12
#define BT_V2_BITS_PF_INTERVAL_0 0x00000007
#define BT_V2_BITS_PF_INTERVAL_0_S 9
#define BT_V2_BITS_PF_INTERVAL_1 0x00000007
#define BT_V2_BITS_PF_INTERVAL_1_S 6
#define BT_V2_BITS_PF_INTERVAL_2 0x00000007
#define BT_V2_BITS_PF_INTERVAL_2_S 3

#define BT_V2_BITS_RX_DEMOD_5_REG (REG_BT_V2_BASE + 0x0038)
#define BT_V2_BITS_D_PHI_DELAY_BR 0x00000007
#define BT_V2_BITS_D_PHI_DELAY_BR_S 29
#define BT_V2_BITS_D_PHI_DELAY_1M 0x00000007
#define BT_V2_BITS_D_PHI_DELAY_1M_S 26
#define BT_V2_BITS_D_PHI_DELAY_2M 0x00000007
#define BT_V2_BITS_D_PHI_DELAY_2M_S 23
#define BT_V2_BITS_D_PHI_DELAY_CODED 0x00000007
#define BT_V2_BITS_D_PHI_DELAY_CODED_S 20
#define BT_V2_BITS_BEST_PHASE_DELAY_1M 0x00000007
#define BT_V2_BITS_BEST_PHASE_DELAY_1M_S 17
#define BT_V2_BITS_BEST_PHASE_DELAY_2M 0x00000007
#define BT_V2_BITS_BEST_PHASE_DELAY_2M_S 14
#define BT_V2_BITS_BEST_PHASE_DELAY_CODED 0x00000007
#define BT_V2_BITS_BEST_PHASE_DELAY_CODED_S 11
#define BT_V2_BITS_LEN_INIT 0x0000000F
#define BT_V2_BITS_LEN_INIT_S 7
#define BT_V2_BITS_DPSK_SYNC_ND_EN (BIT(6))
#define BT_V2_BITS_DPSK_SYNC_ND_EN_S 6
#define BT_V2_BITS_DPSK_SYNC_ND_THRESH 0x0000003F
#define BT_V2_BITS_DPSK_SYNC_ND_THRESH_S 0

#define BT_V2_BITS_RX_DEMOD_6_REG (REG_BT_V2_BASE + 0x003c)
#define BT_V2_BITS_PREAMBLE_THRESH_BR 0x000000FF
#define BT_V2_BITS_PREAMBLE_THRESH_BR_S 24
#define BT_V2_BITS_PREAMBLE_THRESH_1M 0x000000FF
#define BT_V2_BITS_PREAMBLE_THRESH_1M_S 16
#define BT_V2_BITS_PREAMBLE_THRESH_2M 0x000000FF
#define BT_V2_BITS_PREAMBLE_THRESH_2M_S 8
#define BT_V2_BITS_PREAMBLE_THRESH_CODED 0x000000FF
#define BT_V2_BITS_PREAMBLE_THRESH_CODED_S 0

#define BT_V2_BITS_RX_DEMOD_7_REG (REG_BT_V2_BASE + 0x0040)
#define BT_V2_BITS_DPSK_SYNC_DPHI_THRESH 0x000000FF
#define BT_V2_BITS_DPSK_SYNC_DPHI_THRESH_S 24
#define BT_V2_BITS_DPSK_SYNC_THRESH 0x0000000F
#define BT_V2_BITS_DPSK_SYNC_THRESH_S 20
#define BT_V2_BITS_DPSK_PEAK_THRESH 0x0000000F
#define BT_V2_BITS_DPSK_PEAK_THRESH_S 16
#define BT_V2_BITS_DPSK_DEMOD_DELAY 0x0000000F
#define BT_V2_BITS_DPSK_DEMOD_DELAY_S 12
#define BT_V2_BITS_DPSK_DEMOD_DPO_SEL 0x00000003
#define BT_V2_BITS_DPSK_DEMOD_DPO_SEL_S 10
#define BT_V2_BITS_DPSK_DEMOD_SYNC_WAIT 0x00000007
#define BT_V2_BITS_DPSK_DEMOD_SYNC_WAIT_S 7
#define BT_V2_BITS_DPSK_DEMOD_SYNC_SPUR 0x0000001F
#define BT_V2_BITS_DPSK_DEMOD_SYNC_SPUR_S 2
#define BT_V2_BITS_DPSK_COHERENT_OFFSET_SEL 0x00000003
#define BT_V2_BITS_DPSK_COHERENT_OFFSET_SEL_S 0

#define BT_V2_BITS_RX_DEMOD_8_REG (REG_BT_V2_BASE + 0x0044)
#define BT_V2_BITS_DPSK_FREQTRACK_ETA 0x00000FFF
#define BT_V2_BITS_DPSK_FREQTRACK_ETA_S 20
#define BT_V2_BITS_PHASE_CORRECTION_THRESH 0x000000FF
#define BT_V2_BITS_PHASE_CORRECTION_THRESH_S 12
#define BT_V2_BITS_EVM_SUM_SHIFT 0x0000000F
#define BT_V2_BITS_EVM_SUM_SHIFT_S 8
#define BT_V2_BITS_PHASE_CORRECTION_WAIT 0x000000FF
#define BT_V2_BITS_PHASE_CORRECTION_WAIT_S 0

#define BT_V2_BITS_RX_DEMOD_9_REG (REG_BT_V2_BASE + 0x0048)
#define BT_V2_BITS_DPSK_DEVM_ETA 0x00000FFF
#define BT_V2_BITS_DPSK_DEVM_ETA_S 20
#define BT_V2_BITS_EVM_ACC_SHIFT 0x0000000F
#define BT_V2_BITS_EVM_ACC_SHIFT_S 16
#define BT_V2_BITS_DAMP_ACC_SHIFT 0x00000007
#define BT_V2_BITS_DAMP_ACC_SHIFT_S 13
#define BT_V2_BITS_DAMP_DIFF_THRESH 0x00001FFF
#define BT_V2_BITS_DAMP_DIFF_THRESH_S 0

#define BT_V2_BITS_RX_CFG_0_REG (REG_BT_V2_BASE + 0x004c)
#define BT_V2_BITS_PWDET_VALID_DELAY 0x0000001F
#define BT_V2_BITS_PWDET_VALID_DELAY_S 27
#define BT_V2_BITS_GUARD_WINDOW_SDELAY 0x000003FF
#define BT_V2_BITS_GUARD_WINDOW_SDELAY_S 17
#define BT_V2_BITS_GUARD_WINDOW_EDELAY 0x000003FF
#define BT_V2_BITS_GUARD_WINDOW_EDELAY_S 7
#define BT_V2_BITS_BT_FILTER_SEL_FORCE_EN (BIT(6))
#define BT_V2_BITS_BT_FILTER_SEL_FORCE_EN_S 6
#define BT_V2_BITS_BT_FILTER_SEL_FORCE (BIT(5))
#define BT_V2_BITS_BT_FILTER_SEL_FORCE_S 5
#define BT_V2_BITS_BT_FILTER_SEL_1 (BIT(4))
#define BT_V2_BITS_BT_FILTER_SEL_1_S 4
#define BT_V2_BITS_BT_FILTER_SEL_0 (BIT(3))
#define BT_V2_BITS_BT_FILTER_SEL_0_S 3

#define BT_V2_BITS_RX_CFG_1_REG (REG_BT_V2_BASE + 0x0050)
#define BT_V2_BITS_TARGETPOWER_CHANGE_DELAY 0x000003FF
#define BT_V2_BITS_TARGETPOWER_CHANGE_DELAY_S 22
#define BT_V2_BITS_RX_ON_DELAY 0x000007FF
#define BT_V2_BITS_RX_ON_DELAY_S 11
#define BT_V2_BITS_LE_RX_ON_DELAY 0x000007FF
#define BT_V2_BITS_LE_RX_ON_DELAY_S 0

#define BT_V2_BITS_RX_CFG_2_REG (REG_BT_V2_BASE + 0x0054)
#define BT_V2_BITS_RX_POWER_REF_POINT 0x0000003F
#define BT_V2_BITS_RX_POWER_REF_POINT_S 26
#define BT_V2_BITS_AGC_RESTART_WINDOW 0x000003FF
#define BT_V2_BITS_AGC_RESTART_WINDOW_S 16
#define BT_V2_BITS_AGC_RESTART_EN (BIT(15))
#define BT_V2_BITS_AGC_RESTART_EN_S 15
#define BT_V2_BITS_AGC_RESTART_WINDOW_CODED 0x000003FF
#define BT_V2_BITS_AGC_RESTART_WINDOW_CODED_S 5

#define BT_V2_BITS_RX_CFG_3_REG (REG_BT_V2_BASE + 0x0058)
#define BT_V2_BITS_EDR_DATA_DELAY 0x000007FF
#define BT_V2_BITS_EDR_DATA_DELAY_S 21
#define BT_V2_BITS_FORCE_S8 (BIT(20))
#define BT_V2_BITS_FORCE_S8_S 20
#define BT_V2_BITS_CODED_VALID_DELAY 0x000000FF
#define BT_V2_BITS_CODED_VALID_DELAY_S 12
#define BT_V2_BITS_CODED_SYNCFOUND_FLAG_DELAY 0x000000FF
#define BT_V2_BITS_CODED_SYNCFOUND_FLAG_DELAY_S 4

#define BT_V2_BITS_TX_MOD_0_REG (REG_BT_V2_BASE + 0x005c)
#define BT_V2_BITS_RW_EDR_DUMP 0x0000001F
#define BT_V2_BITS_RW_EDR_DUMP_S 27
#define BT_V2_BITS_RW_EDR_DUMP_GFSK 0x0000001F
#define BT_V2_BITS_RW_EDR_DUMP_GFSK_S 22

#define BT_V2_BITS_PHASE_GEN_CFG_REG (REG_BT_V2_BASE + 0x0060)
#define BT_V2_BITS_HIGH_SEL 0x00000007
#define BT_V2_BITS_HIGH_SEL_S 29
#define BT_V2_BITS_LOW_SEL 0x00000007
#define BT_V2_BITS_LOW_SEL_S 26
#define BT_V2_BITS_PHASE_EN (BIT(25))
#define BT_V2_BITS_PHASE_EN_S 25
#define BT_V2_BITS_PHASE_MATCH_CORRECT (BIT(24))
#define BT_V2_BITS_PHASE_MATCH_CORRECT_S 24

#define BT_V2_BITS_RX_ACCESS_CORR_CFG_REG (REG_BT_V2_BASE + 0x0064)
#define BT_V2_BITS_CORR_THRESH_BREDR 0x0000003F
#define BT_V2_BITS_CORR_THRESH_BREDR_S 26
#define BT_V2_BITS_CORR_THRESH_LE_1M 0x0000003F
#define BT_V2_BITS_CORR_THRESH_LE_1M_S 20
#define BT_V2_BITS_CORR_THRESH_LE_2M 0x0000003F
#define BT_V2_BITS_CORR_THRESH_LE_2M_S 14
#define BT_V2_BITS_CORR_THRESH_LE_CODED 0x0000003F
#define BT_V2_BITS_CORR_THRESH_LE_CODED_S 8
#define BT_V2_BITS_CORR_SPUR_WIDTH 0x0000003F
#define BT_V2_BITS_CORR_SPUR_WIDTH_S 2

#define BT_V2_BITS_RW_EM_BASE_REG (REG_BT_V2_BASE + 0x0068)
#define BT_V2_BITS_RW_EM_BASE 0x3FFFFFFF
#define BT_V2_BITS_RW_EM_BASE_S 2

#define BT_V2_BITS_DIAG_0_REG (REG_BT_V2_BASE + 0x006c)
#define BT_V2_BITS_RW_TX_DATA 0x00000007
#define BT_V2_BITS_RW_TX_DATA_S 29
#define BT_V2_BITS_RW_TX_DATA_VALID (BIT(28))
#define BT_V2_BITS_RW_TX_DATA_VALID_S 28
#define BT_V2_BITS_RW_RATE 0x00000003
#define BT_V2_BITS_RW_RATE_S 26
#define BT_V2_BITS_RW_TX_EN (BIT(25))
#define BT_V2_BITS_RW_TX_EN_S 25
#define BT_V2_BITS_RW_RX_EN (BIT(24))
#define BT_V2_BITS_RW_RX_EN_S 24
#define BT_V2_BITS_RW_TXPWR 0x000000FF
#define BT_V2_BITS_RW_TXPWR_S 16
#define BT_V2_BITS_RW_SYNCFOUND_PULSE_DELAYED (BIT(15))
#define BT_V2_BITS_RW_SYNCFOUND_PULSE_DELAYED_S 15
#define BT_V2_BITS_RW_LE_EN (BIT(14))
#define BT_V2_BITS_RW_LE_EN_S 14
#define BT_V2_BITS_RW_RSSI_REQ (BIT(13))
#define BT_V2_BITS_RW_RSSI_REQ_S 13
#define BT_V2_BITS_RW_FREQ 0x0000007F
#define BT_V2_BITS_RW_FREQ_S 6
#define BT_V2_BITS_RW_LEN_VALID (BIT(5))
#define BT_V2_BITS_RW_LEN_VALID_S 5
#define BT_V2_BITS_RW_LRFLUSH (BIT(4))
#define BT_V2_BITS_RW_LRFLUSH_S 4
#define BT_V2_BITS_RW_OPT_SAMPLING_TRAIN (BIT(3))
#define BT_V2_BITS_RW_OPT_SAMPLING_TRAIN_S 3
#define BT_V2_BITS_RW_IN_PROCESS (BIT(2))
#define BT_V2_BITS_RW_IN_PROCESS_S 2
#define BT_V2_BITS_RW_RF_BUSY (BIT(1))
#define BT_V2_BITS_RW_RF_BUSY_S 1
#define BT_V2_BITS_RW_AGC_RSSI_READY (BIT(0))
#define BT_V2_BITS_RW_AGC_RSSI_READY_S 0

#define BT_V2_BITS_DIAG_1_REG (REG_BT_V2_BASE + 0x0070)
#define BT_V2_BITS_RW_AGC_RSSI 0x000000FF
#define BT_V2_BITS_RW_AGC_RSSI_S 24
#define BT_V2_BITS_RW_RX_VALID (BIT(23))
#define BT_V2_BITS_RW_RX_VALID_S 23
#define BT_V2_BITS_RW_RX_DATA 0x00000007
#define BT_V2_BITS_RW_RX_DATA_S 20
#define BT_V2_BITS_RW_LEN 0x000007FF
#define BT_V2_BITS_RW_LEN_S 9

#define BT_V2_BITS_DIAG_2_REG (REG_BT_V2_BASE + 0x0074)
#define BT_V2_BITS_RW_SYNW_H 0xFFFFFFFF
#define BT_V2_BITS_RW_SYNW_H_S 0

#define BT_V2_BITS_DIAG_3_REG (REG_BT_V2_BASE + 0x0078)
#define BT_V2_BITS_RW_SYNW_L 0xFFFFFFFF
#define BT_V2_BITS_RW_SYNW_L_S 0

#define BT_V2_BITS_DIAG_4_REG (REG_BT_V2_BASE + 0x007c)
#define BT_V2_BITS_TX_ITF_STATE 0x0000000F
#define BT_V2_BITS_TX_ITF_STATE_S 28
#define BT_V2_BITS_DPSK_STATE 0x00000003
#define BT_V2_BITS_DPSK_STATE_S 26
#define BT_V2_BITS_TX_RAMP_STATE 0x00000003
#define BT_V2_BITS_TX_RAMP_STATE_S 24
#define BT_V2_BITS_RX_ST 0x00000003
#define BT_V2_BITS_RX_ST_S 22
#define BT_V2_BITS_DEMOD_DPSK_STATE 0x0000000F
#define BT_V2_BITS_DEMOD_DPSK_STATE_S 18
#define BT_V2_BITS_DPSK_EVM_NOW 0x000001FF
#define BT_V2_BITS_DPSK_EVM_NOW_S 9

#define BT_V2_BITS_DIAG_5_REG (REG_BT_V2_BASE + 0x0080)
#define BT_V2_BITS_BT_RX_POWER_DB_REF 0x000007FF
#define BT_V2_BITS_BT_RX_POWER_DB_REF_S 21

#define BT_V2_BITS_INT_ENA_BT_REG (REG_BT_V2_BASE + 0x0084)
#define BT_V2_BITS_BT_BB_TX_ON_INT_ENA (BIT(17))
#define BT_V2_BITS_BT_BB_TX_ON_INT_ENA_S 17
#define BT_V2_BITS_RW_RX_EN_N_INT_ENA (BIT(16))
#define BT_V2_BITS_RW_RX_EN_N_INT_ENA_S 16
#define BT_V2_BITS_RW_TX_EN_N_INT_ENA (BIT(15))
#define BT_V2_BITS_RW_TX_EN_N_INT_ENA_S 15
#define BT_V2_BITS_RW_RX_EN_P_INT_ENA (BIT(14))
#define BT_V2_BITS_RW_RX_EN_P_INT_ENA_S 14
#define BT_V2_BITS_RW_TX_EN_P_INT_ENA (BIT(13))
#define BT_V2_BITS_RW_TX_EN_P_INT_ENA_S 13
#define BT_V2_BITS_RW_LE_EN_INT_ENA (BIT(12))
#define BT_V2_BITS_RW_LE_EN_INT_ENA_S 12
#define BT_V2_BITS_BT_RX_EN_INT_ENA (BIT(11))
#define BT_V2_BITS_BT_RX_EN_INT_ENA_S 11
#define BT_V2_BITS_IN_RECEIVE_INT_ENA (BIT(10))
#define BT_V2_BITS_IN_RECEIVE_INT_ENA_S 10
#define BT_V2_BITS_AGC_PWR_RISE_INT_ENA (BIT(9))
#define BT_V2_BITS_AGC_PWR_RISE_INT_ENA_S 9
#define BT_V2_BITS_AGC_PWR_DROP_INT_ENA (BIT(8))
#define BT_V2_BITS_AGC_PWR_DROP_INT_ENA_S 8
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_ENA (BIT(7))
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_ENA_S 7
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_ENA (BIT(6))
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_ENA_S 6
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_ENA (BIT(5))
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_ENA_S 5
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_ENA (BIT(4))
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_ENA_S 4
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_ENA (BIT(3))
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_ENA_S 3
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_ENA (BIT(2))
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_ENA_S 2
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_ENA (BIT(1))
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_ENA_S 1
#define BT_V2_BITS_SFP_TIMER_INT_ENA (BIT(0))
#define BT_V2_BITS_SFP_TIMER_INT_ENA_S 0

#define BT_V2_BITS_INT_RAW_BT_REG (REG_BT_V2_BASE + 0x0088)
#define BT_V2_BITS_BT_BB_TX_ON_INT_RAW (BIT(17))
#define BT_V2_BITS_BT_BB_TX_ON_INT_RAW_S 17
#define BT_V2_BITS_RW_RX_EN_N_INT_RAW (BIT(16))
#define BT_V2_BITS_RW_RX_EN_N_INT_RAW_S 16
#define BT_V2_BITS_RW_TX_EN_N_INT_RAW (BIT(15))
#define BT_V2_BITS_RW_TX_EN_N_INT_RAW_S 15
#define BT_V2_BITS_RW_RX_EN_P_INT_RAW (BIT(14))
#define BT_V2_BITS_RW_RX_EN_P_INT_RAW_S 14
#define BT_V2_BITS_RW_TX_EN_P_INT_RAW (BIT(13))
#define BT_V2_BITS_RW_TX_EN_P_INT_RAW_S 13
#define BT_V2_BITS_RW_LE_EN_INT_RAW (BIT(12))
#define BT_V2_BITS_RW_LE_EN_INT_RAW_S 12
#define BT_V2_BITS_BT_RX_EN_INT_RAW (BIT(11))
#define BT_V2_BITS_BT_RX_EN_INT_RAW_S 11
#define BT_V2_BITS_IN_RECEIVE_INT_RAW (BIT(10))
#define BT_V2_BITS_IN_RECEIVE_INT_RAW_S 10
#define BT_V2_BITS_AGC_PWR_RISE_INT_RAW (BIT(9))
#define BT_V2_BITS_AGC_PWR_RISE_INT_RAW_S 9
#define BT_V2_BITS_AGC_PWR_DROP_INT_RAW (BIT(8))
#define BT_V2_BITS_AGC_PWR_DROP_INT_RAW_S 8
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_RAW (BIT(7))
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_RAW_S 7
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_RAW (BIT(6))
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_RAW_S 6
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_RAW (BIT(5))
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_RAW_S 5
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_RAW (BIT(4))
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_RAW_S 4
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_RAW (BIT(3))
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_RAW_S 3
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_RAW (BIT(2))
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_RAW_S 2
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_RAW (BIT(1))
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_RAW_S 1
#define BT_V2_BITS_SFP_TIMER_INT_RAW (BIT(0))
#define BT_V2_BITS_SFP_TIMER_INT_RAW_S 0

#define BT_V2_BITS_INT_ST_BT_REG (REG_BT_V2_BASE + 0x008c)
#define BT_V2_BITS_BT_BB_TX_ON_INT_ST (BIT(17))
#define BT_V2_BITS_BT_BB_TX_ON_INT_ST_S 17
#define BT_V2_BITS_RW_RX_EN_N_INT_ST (BIT(16))
#define BT_V2_BITS_RW_RX_EN_N_INT_ST_S 16
#define BT_V2_BITS_RW_TX_EN_N_INT_ST (BIT(15))
#define BT_V2_BITS_RW_TX_EN_N_INT_ST_S 15
#define BT_V2_BITS_RW_RX_EN_P_INT_ST (BIT(14))
#define BT_V2_BITS_RW_RX_EN_P_INT_ST_S 14
#define BT_V2_BITS_RW_TX_EN_P_INT_ST (BIT(13))
#define BT_V2_BITS_RW_TX_EN_P_INT_ST_S 13
#define BT_V2_BITS_RW_LE_EN_INT_ST (BIT(12))
#define BT_V2_BITS_RW_LE_EN_INT_ST_S 12
#define BT_V2_BITS_BT_RX_EN_INT_ST (BIT(11))
#define BT_V2_BITS_BT_RX_EN_INT_ST_S 11
#define BT_V2_BITS_IN_RECEIVE_INT_ST (BIT(10))
#define BT_V2_BITS_IN_RECEIVE_INT_ST_S 10
#define BT_V2_BITS_AGC_PWR_RISE_INT_ST (BIT(9))
#define BT_V2_BITS_AGC_PWR_RISE_INT_ST_S 9
#define BT_V2_BITS_AGC_PWR_DROP_INT_ST (BIT(8))
#define BT_V2_BITS_AGC_PWR_DROP_INT_ST_S 8
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_ST (BIT(7))
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_ST_S 7
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_ST (BIT(6))
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_ST_S 6
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_ST (BIT(5))
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_ST_S 5
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_ST (BIT(4))
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_ST_S 4
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_ST (BIT(3))
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_ST_S 3
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_ST (BIT(2))
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_ST_S 2
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_ST (BIT(1))
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_ST_S 1
#define BT_V2_BITS_SFP_TIMER_INT_ST (BIT(0))
#define BT_V2_BITS_SFP_TIMER_INT_ST_S 0

#define BT_V2_BITS_INT_CLR_BT_REG (REG_BT_V2_BASE + 0x0090)
#define BT_V2_BITS_BT_BB_TX_ON_INT_CLR (BIT(17))
#define BT_V2_BITS_BT_BB_TX_ON_INT_CLR_S 17
#define BT_V2_BITS_RW_RX_EN_N_INT_CLR (BIT(16))
#define BT_V2_BITS_RW_RX_EN_N_INT_CLR_S 16
#define BT_V2_BITS_RW_TX_EN_N_INT_CLR (BIT(15))
#define BT_V2_BITS_RW_TX_EN_N_INT_CLR_S 15
#define BT_V2_BITS_RW_RX_EN_P_INT_CLR (BIT(14))
#define BT_V2_BITS_RW_RX_EN_P_INT_CLR_S 14
#define BT_V2_BITS_RW_TX_EN_P_INT_CLR (BIT(13))
#define BT_V2_BITS_RW_TX_EN_P_INT_CLR_S 13
#define BT_V2_BITS_RW_LE_EN_INT_CLR (BIT(12))
#define BT_V2_BITS_RW_LE_EN_INT_CLR_S 12
#define BT_V2_BITS_BT_RX_EN_INT_CLR (BIT(11))
#define BT_V2_BITS_BT_RX_EN_INT_CLR_S 11
#define BT_V2_BITS_IN_RECEIVE_INT_CLR (BIT(10))
#define BT_V2_BITS_IN_RECEIVE_INT_CLR_S 10
#define BT_V2_BITS_AGC_PWR_RISE_INT_CLR (BIT(9))
#define BT_V2_BITS_AGC_PWR_RISE_INT_CLR_S 9
#define BT_V2_BITS_AGC_PWR_DROP_INT_CLR (BIT(8))
#define BT_V2_BITS_AGC_PWR_DROP_INT_CLR_S 8
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_CLR (BIT(7))
#define BT_V2_BITS_AGC_PWR_RISE_ERROR_INT_CLR_S 7
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_CLR (BIT(6))
#define BT_V2_BITS_AGC_PWR_DROP_ERROR_INT_CLR_S 6
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_CLR (BIT(5))
#define BT_V2_BITS_SET_CHAN_FREQ_DONE_INT_CLR_S 5
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_CLR (BIT(4))
#define BT_V2_BITS_RW_IN_PROCESS_P_INT_CLR_S 4
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_CLR (BIT(3))
#define BT_V2_BITS_RW_IN_PROCESS_N_INT_CLR_S 3
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_CLR (BIT(2))
#define BT_V2_BITS_SYNC_FOUND_PULSE_CODED_INT_CLR_S 2
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_CLR (BIT(1))
#define BT_V2_BITS_SYNC_FOUND_PULSE__INT_CLR_S 1
#define BT_V2_BITS_SFP_TIMER_INT_CLR (BIT(0))
#define BT_V2_BITS_SFP_TIMER_INT_CLR_S 0

#define BT_V2_BITS_BT_BB_INT_CFG_REG (REG_BT_V2_BASE + 0x0094)
#define BT_V2_BITS_BT_INT_EN (BIT(31))
#define BT_V2_BITS_BT_INT_EN_S 31

#define BT_V2_BITS_SFP_TIMER_CFG_REG (REG_BT_V2_BASE + 0x0098)
#define BT_V2_BITS_SFP_TIMER_EN (BIT(31))
#define BT_V2_BITS_SFP_TIMER_EN_S 31
#define BT_V2_BITS_SFP_TIMER_STAMP 0x0000FFFF
#define BT_V2_BITS_SFP_TIMER_STAMP_S 15

#define BT_V2_BITS_RW_SYNW_FORCE_L_REG (REG_BT_V2_BASE + 0x009c)
#define BT_V2_BITS_RW_SYNW_FORCE_L 0xFFFFFFFF
#define BT_V2_BITS_RW_SYNW_FORCE_L_S 0

#define BT_V2_BITS_RW_SYNW_FORCE_H_REG (REG_BT_V2_BASE + 0x00a0)
#define BT_V2_BITS_RW_SYNW_FORCE_H 0xFFFFFFFF
#define BT_V2_BITS_RW_SYNW_FORCE_H_S 0

#define BT_V2_BITS_RX_PHY_INFO_CFG_0_REG (REG_BT_V2_BASE + 0x00a4)
#define BT_V2_BITS_RX_PHY_INFO_EN (BIT(31))
#define BT_V2_BITS_RX_PHY_INFO_EN_S 31
#define BT_V2_BITS_TARGET_POWER 0x000000FF
#define BT_V2_BITS_TARGET_POWER_S 23
#define BT_V2_BITS_INBAND_DELTA_THRESH 0x000000FF
#define BT_V2_BITS_INBAND_DELTA_THRESH_S 15
#define BT_V2_BITS_INBAND_RISE_THRESH 0x000000FF
#define BT_V2_BITS_INBAND_RISE_THRESH_S 7

#define BT_V2_BITS_RX_PHY_INFO_CFG_1_REG (REG_BT_V2_BASE + 0x00a8)
#define BT_V2_BITS_FULLBAND_MAX_THRESH 0x000000FF
#define BT_V2_BITS_FULLBAND_MAX_THRESH_S 24

#define BT_V2_BITS_GPIO_DIAG_REG (REG_BT_V2_BASE + 0x00ac)
#define BT_V2_BITS_GPIO_BB_DIAG0_SEL 0x00000007
#define BT_V2_BITS_GPIO_BB_DIAG0_SEL_S 29
#define BT_V2_BITS_GPIO_BB_DIAG1_SEL 0x00000007
#define BT_V2_BITS_GPIO_BB_DIAG1_SEL_S 26
#define BT_V2_BITS_GPIO_BB_DIAG2_SEL 0x00000007
#define BT_V2_BITS_GPIO_BB_DIAG2_SEL_S 23
#define BT_V2_BITS_GPIO_LC_DIAG0_SEL 0x0000000F
#define BT_V2_BITS_GPIO_LC_DIAG0_SEL_S 19
#define BT_V2_BITS_GPIO_LC_DIAG1_SEL 0x0000000F
#define BT_V2_BITS_GPIO_LC_DIAG1_SEL_S 15
#define BT_V2_BITS_GPIO_LC_DIAG2_SEL 0x0000000F
#define BT_V2_BITS_GPIO_LC_DIAG2_SEL_S 11

#define BT_V2_BITS_DIAG_6_REG (REG_BT_V2_BASE + 0x00b0)
#define BT_V2_BITS_RX_PHY_INFO_INBAND_PWR_CUR 0x000000FF
#define BT_V2_BITS_RX_PHY_INFO_INBAND_PWR_CUR_S 24
#define BT_V2_BITS_RX_PHY_INFO_FULLBAND_PWR_CUR 0x000000FF
#define BT_V2_BITS_RX_PHY_INFO_FULLBAND_PWR_CUR_S 16
#define BT_V2_BITS_RX_PHY_INFO_GAIN_CUR 0x000000FF
#define BT_V2_BITS_RX_PHY_INFO_GAIN_CUR_S 8
#define BT_V2_BITS_RX_PHY_INFO_RSSI_CUR 0x000000FF
#define BT_V2_BITS_RX_PHY_INFO_RSSI_CUR_S 0

#define BT_V2_BITS_DUMP_CFG_REG (REG_BT_V2_BASE + 0x00b4)
#define BT_V2_BITS_BT_DUMP_PWR_SEL 0x00000003
#define BT_V2_BITS_BT_DUMP_PWR_SEL_S 6
#define BT_V2_BITS_BT_DUMP_TRIGGER_FORCE (BIT(5))
#define BT_V2_BITS_BT_DUMP_TRIGGER_FORCE_S 5
#define BT_V2_BITS_BT_DUMP_TRIGGER_FORCE_EN (BIT(4))
#define BT_V2_BITS_BT_DUMP_TRIGGER_FORCE_EN_S 4
#define BT_V2_BITS_BT_DUMP_DATA_SEL (BIT(3))
#define BT_V2_BITS_BT_DUMP_DATA_SEL_S 3
#define BT_V2_BITS_BT_DUMP_TRIGGER_SEL 0x00000003
#define BT_V2_BITS_BT_DUMP_TRIGGER_SEL_S 1
#define BT_V2_BITS_BT_DUMP_EN (BIT(0))
#define BT_V2_BITS_BT_DUMP_EN_S 0

#define BT_V2_BITS_BT_BB_DATE_REG (REG_BT_V2_BASE + 0x00b8)
#define BT_V2_BITS_CLK_FORCE_ON (BIT(29))
#define BT_V2_BITS_CLK_FORCE_ON_S 29
#define BT_V2_BITS_CLK_EN (BIT(28))
#define BT_V2_BITS_CLK_EN_S 28
#define BT_V2_BITS_BT_BB_DATE 0x0FFFFFFF
#define BT_V2_BITS_BT_BB_DATE_S 0
#define BT_V2_BITS_BT_BB_DATE_VERSION 0x1907250
