
#define CP_DMA_CP_INT_RAW_REG (REG_CP_DMA_BASE + 0x0000)
#define CP_DMA_CP_CRC_DONE_INT_RAW (BIT(8))
#define CP_DMA_CP_CRC_DONE_INT_RAW_S 8
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_RAW (BIT(7))
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_RAW_S 7
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_RAW (BIT(6))
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_RAW_S 6
#define CP_DMA_CP_OUT_DSCR_ERR_INT_RAW (BIT(5))
#define CP_DMA_CP_OUT_DSCR_ERR_INT_RAW_S 5
#define CP_DMA_CP_IN_DSCR_ERR_INT_RAW (BIT(4))
#define CP_DMA_CP_IN_DSCR_ERR_INT_RAW_S 4
#define CP_DMA_CP_OUT_EOF_INT_RAW (BIT(3))
#define CP_DMA_CP_OUT_EOF_INT_RAW_S 3
#define CP_DMA_CP_OUT_DONE_INT_RAW (BIT(2))
#define CP_DMA_CP_OUT_DONE_INT_RAW_S 2
#define CP_DMA_CP_IN_SUC_EOF_INT_RAW (BIT(1))
#define CP_DMA_CP_IN_SUC_EOF_INT_RAW_S 1
#define CP_DMA_CP_IN_DONE_INT_RAW (BIT(0))
#define CP_DMA_CP_IN_DONE_INT_RAW_S 0

#define CP_DMA_CP_INT_ST_REG (REG_CP_DMA_BASE + 0x0004)
#define CP_DMA_CP_CRC_DONE_INT_ST (BIT(8))
#define CP_DMA_CP_CRC_DONE_INT_ST_S 8
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_ST (BIT(7))
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_ST_S 7
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_ST (BIT(6))
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_ST_S 6
#define CP_DMA_CP_OUT_DSCR_ERR_INT_ST (BIT(5))
#define CP_DMA_CP_OUT_DSCR_ERR_INT_ST_S 5
#define CP_DMA_CP_IN_DSCR_ERR_INT_ST (BIT(4))
#define CP_DMA_CP_IN_DSCR_ERR_INT_ST_S 4
#define CP_DMA_CP_OUT_EOF_INT_ST (BIT(3))
#define CP_DMA_CP_OUT_EOF_INT_ST_S 3
#define CP_DMA_CP_OUT_DONE_INT_ST (BIT(2))
#define CP_DMA_CP_OUT_DONE_INT_ST_S 2
#define CP_DMA_CP_IN_SUC_EOF_INT_ST (BIT(1))
#define CP_DMA_CP_IN_SUC_EOF_INT_ST_S 1
#define CP_DMA_CP_IN_DONE_INT_ST (BIT(0))
#define CP_DMA_CP_IN_DONE_INT_ST_S 0

#define CP_DMA_CP_INT_ENA_REG (REG_CP_DMA_BASE + 0x008)
#define CP_DMA_CP_CRC_DONE_INT_ENA (BIT(8))
#define CP_DMA_CP_CRC_DONE_INT_ENA_S 8
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_ENA (BIT(7))
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_ENA_S 7
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_ENA (BIT(6))
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_ENA_S 6
#define CP_DMA_CP_OUT_DSCR_ERR_INT_ENA (BIT(5))
#define CP_DMA_CP_OUT_DSCR_ERR_INT_ENA_S 5
#define CP_DMA_CP_IN_DSCR_ERR_INT_ENA (BIT(4))
#define CP_DMA_CP_IN_DSCR_ERR_INT_ENA_S 4
#define CP_DMA_CP_OUT_EOF_INT_ENA (BIT(3))
#define CP_DMA_CP_OUT_EOF_INT_ENA_S 3
#define CP_DMA_CP_OUT_DONE_INT_ENA (BIT(2))
#define CP_DMA_CP_OUT_DONE_INT_ENA_S 2
#define CP_DMA_CP_IN_SUC_EOF_INT_ENA (BIT(1))
#define CP_DMA_CP_IN_SUC_EOF_INT_ENA_S 1
#define CP_DMA_CP_IN_DONE_INT_ENA (BIT(0))
#define CP_DMA_CP_IN_DONE_INT_ENA_S 0

#define CP_DMA_CP_INT_CLR_REG (REG_CP_DMA_BASE + 0x000c)
#define CP_DMA_CP_CRC_DONE_INT_CLR (BIT(8))
#define CP_DMA_CP_CRC_DONE_INT_CLR_S 8
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_CLR (BIT(7))
#define CP_DMA_CP_OUT_TOTAL_EOF_INT_CLR_S 7
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_CLR (BIT(6))
#define CP_DMA_CP_IN_DSCR_EMPTY_INT_CLR_S 6
#define CP_DMA_CP_OUT_DSCR_ERR_INT_CLR (BIT(5))
#define CP_DMA_CP_OUT_DSCR_ERR_INT_CLR_S 5
#define CP_DMA_CP_IN_DSCR_ERR_INT_CLR (BIT(4))
#define CP_DMA_CP_IN_DSCR_ERR_INT_CLR_S 4
#define CP_DMA_CP_OUT_EOF_INT_CLR (BIT(3))
#define CP_DMA_CP_OUT_EOF_INT_CLR_S 3
#define CP_DMA_CP_OUT_DONE_INT_CLR (BIT(2))
#define CP_DMA_CP_OUT_DONE_INT_CLR_S 2
#define CP_DMA_CP_IN_SUC_EOF_INT_CLR (BIT(1))
#define CP_DMA_CP_IN_SUC_EOF_INT_CLR_S 1
#define CP_DMA_CP_IN_DONE_INT_CLR (BIT(0))
#define CP_DMA_CP_IN_DONE_INT_CLR_S 0

#define CP_DMA_CP_OUT_LINK_REG (REG_CP_DMA_BASE + 0x0010)
#define CP_DMA_OUTLINK_PARK (BIT(31))
#define CP_DMA_OUTLINK_PARK_S 31
#define CP_DMA_CP_OUTLINK_RESTART (BIT(30))
#define CP_DMA_CP_OUTLINK_RESTART_S 30
#define CP_DMA_CP_OUTLINK_START (BIT(29))
#define CP_DMA_CP_OUTLINK_START_S 29
#define CP_DMA_CP_OUTLINK_STOP (BIT(28))
#define CP_DMA_CP_OUTLINK_STOP_S 28
#define CP_DMA_CP_OUTLINK_ADDR 0x000FFFFF
#define CP_DMA_CP_OUTLINK_ADDR_S 0

#define CP_DMA_CP_IN_LINK_REG (REG_CP_DMA_BASE + 0x0014)
#define CP_DMA_INLINK_PARK (BIT(31))
#define CP_DMA_INLINK_PARK_S 31
#define CP_DMA_CP_INLINK_RESTART (BIT(30))
#define CP_DMA_CP_INLINK_RESTART_S 30
#define CP_DMA_CP_INLINK_START (BIT(29))
#define CP_DMA_CP_INLINK_START_S 29
#define CP_DMA_CP_INLINK_STOP (BIT(28))
#define CP_DMA_CP_INLINK_STOP_S 28
#define CP_DMA_CP_INLINK_ADDR 0x000FFFFF
#define CP_DMA_CP_INLINK_ADDR_S 0

#define CP_DMA_CP_OUT_EOF_DES_ADDR_REG (REG_CP_DMA_BASE + 0x0018)
#define CP_DMA_CP_OUT_EOF_DES_ADDR 0xFFFFFFFF
#define CP_DMA_CP_OUT_EOF_DES_ADDR_S 0

#define CP_DMA_CP_IN_EOF_DES_ADDR_REG (REG_CP_DMA_BASE + 0x001c)
#define CP_DMA_CP_IN_SUC_EOF_DES_ADDR 0xFFFFFFFF
#define CP_DMA_CP_IN_SUC_EOF_DES_ADDR_S 0

#define CP_DMA_CP_OUT_EOF_BFR_DES_ADDR_REG (REG_CP_DMA_BASE + 0x0020)
#define CP_DMA_CP_OUT_EOF_BFR_DES_ADDR 0xFFFFFFFF
#define CP_DMA_CP_OUT_EOF_BFR_DES_ADDR_S 0

#define CP_DMA_CP_INLINK_DSCR_REG (REG_CP_DMA_BASE + 0x0024)
#define CP_DMA_CP_INLINK_DSCR 0xFFFFFFFF
#define CP_DMA_CP_INLINK_DSCR_S 0

#define CP_DMA_CP_INLINK_DSCR_BF0_REG (REG_CP_DMA_BASE + 0x0028)
#define CP_DMA_CP_INLINK_DSCR_BF0 0xFFFFFFFF
#define CP_DMA_CP_INLINK_DSCR_BF0_S 0

#define CP_DMA_CP_INLINK_DSCR_BF1_REG (REG_CP_DMA_BASE + 0x002c)
#define CP_DMA_CP_INLINK_DSCR_BF1 0xFFFFFFFF
#define CP_DMA_CP_INLINK_DSCR_BF1_S 0

#define CP_DMA_CP_OUTLINK_DSCR_REG (REG_CP_DMA_BASE + 0x0030)
#define CP_DMA_CP_OUTLINK_DSCR 0xFFFFFFFF
#define CP_DMA_CP_OUTLINK_DSCR_S 0

#define CP_DMA_CP_OUTLINK_DSCR_BF0_REG (REG_CP_DMA_BASE + 0x0034)
#define CP_DMA_CP_OUTLINK_DSCR_BF0 0xFFFFFFFF
#define CP_DMA_CP_OUTLINK_DSCR_BF0_S 0

#define CP_DMA_CP_OUTLINK_DSCR_BF1_REG (REG_CP_DMA_BASE + 0x0038)
#define CP_DMA_CP_OUTLINK_DSCR_BF1 0xFFFFFFFF
#define CP_DMA_CP_OUTLINK_DSCR_BF1_S 0

#define CP_DMA_CP_CONF_REG (REG_CP_DMA_BASE + 0x003c)
#define CP_DMA_CLK_EN (BIT(31))
#define CP_DMA_CLK_EN_S 31
#define CP_DMA_CRC_OUT_REVERSE_EN (BIT(11))
#define CP_DMA_CRC_OUT_REVERSE_EN_S 11
#define CP_DMA_CRC_BIG_ENDIAN_EN (BIT(10))
#define CP_DMA_CRC_BIG_ENDIAN_EN_S 10
#define CP_DMA_CRC_CAL_EN (BIT(9))
#define CP_DMA_CRC_CAL_EN_S 9
#define CP_DMA_CRC_CAL_RESET (BIT(8))
#define CP_DMA_CRC_CAL_RESET_S 8
#define CP_DMA_CHECK_OWNER (BIT(7))
#define CP_DMA_CHECK_OWNER_S 7
#define CP_DMA_OUT_AUTO_WRBACK (BIT(6))
#define CP_DMA_OUT_AUTO_WRBACK_S 6
#define CP_DMA_IN_OWNER (BIT(5))
#define CP_DMA_IN_OWNER_S 5
#define CP_DMA_OUT_OWNER (BIT(4))
#define CP_DMA_OUT_OWNER_S 4
#define CP_DMA_FIFO_RST (BIT(3))
#define CP_DMA_FIFO_RST_S 3
#define CP_DMA_CMDFIFO_RST (BIT(2))
#define CP_DMA_CMDFIFO_RST_S 2
#define CP_DMA_OUT_RST (BIT(1))
#define CP_DMA_OUT_RST_S 1
#define CP_DMA_IN_RST (BIT(0))
#define CP_DMA_IN_RST_S 0

#define CP_DMA_CP_IN_ST_REG (REG_CP_DMA_BASE + 0x0040)
#define CP_DMA_FIFO_EMPTY (BIT(23))
#define CP_DMA_FIFO_EMPTY_S 23
#define CP_DMA_IN_STATE 0x00000007
#define CP_DMA_IN_STATE_S 20
#define CP_DMA_IN_DSCR_STATE 0x00000003
#define CP_DMA_IN_DSCR_STATE_S 18
#define CP_DMA_INLINK_DSCR_ADDR 0x0003FFFF
#define CP_DMA_INLINK_DSCR_ADDR_S 0

#define CP_DMA_CP_OUT_ST_REG (REG_CP_DMA_BASE + 0x0044)
#define CP_DMA_FIFO_FULL (BIT(23))
#define CP_DMA_FIFO_FULL_S 23
#define CP_DMA_OUT_STATE 0x00000007
#define CP_DMA_OUT_STATE_S 20
#define CP_DMA_OUT_DSCR_STATE 0x00000003
#define CP_DMA_OUT_DSCR_STATE_S 18
#define CP_DMA_OUTLINK_DSCR_ADDR 0x0003FFFF
#define CP_DMA_OUTLINK_DSCR_ADDR_S 0

#define CP_DMA_CP_CRC_OUT_REG (REG_CP_DMA_BASE + 0x0048)
#define CP_DMA_CRC_RESULT 0xFFFFFFFF
#define CP_DMA_CRC_RESULT_S 0

#define CP_DMA_CP_DATE_REG (REG_CP_DMA_BASE + 0x00fc)
#define CP_DMA_DATE 0xFFFFFFFF
#define CP_DMA_DATE_S 0
#define CP_DMA_DATE_VERSION 0x18082000
