
#define EFUSE_PGM_DATA0_REG (REG_EFUSE_BASE + 0x000)
#define EFUSE_WR_DIS 0xFFFFFFFF
#define EFUSE_WR_DIS_S 0

#define EFUSE_PGM_DATA1_REG (REG_EFUSE_BASE + 0x004)
#define EFUSE_SDIO_DREFH 0x00000003
#define EFUSE_SDIO_DREFH_S 30
#define EFUSE_SDIO_MODECURLIM (BIT(29))
#define EFUSE_SDIO_MODECURLIM_S 29
#define EFUSE_USB_DRES 0x00000007
#define EFUSE_USB_DRES_S 26
#define EFUSE_EXT_PHY_ENABLE (BIT(25))
#define EFUSE_EXT_PHY_ENABLE_S 25
#define EFUSE_USB_EXCHG_PINS (BIT(24))
#define EFUSE_USB_EXCHG_PINS_S 24
#define EFUSE_USB_DREFL 0x00000003
#define EFUSE_USB_DREFL_S 22
#define EFUSE_USB_DREFH 0x00000003
#define EFUSE_USB_DREFH_S 20
#define EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT (BIT(19))
#define EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT_S 19
#define EFUSE_HARD_DIS_JTAG (BIT(18))
#define EFUSE_HARD_DIS_JTAG_S 18
#define EFUSE_SOFT_DIS_JTAG (BIT(17))
#define EFUSE_SOFT_DIS_JTAG_S 17
#define EFUSE_DIS_EFUSE_ATE_WR (BIT(16))
#define EFUSE_DIS_EFUSE_ATE_WR_S 16
#define EFUSE_DIS_SDIO_ACCESS (BIT(15))
#define EFUSE_DIS_SDIO_ACCESS_S 15
#define EFUSE_DIS_CAN (BIT(14))
#define EFUSE_DIS_CAN_S 14
#define EFUSE_DIS_USB (BIT(13))
#define EFUSE_DIS_USB_S 13
#define EFUSE_DIS_BT (BIT(12))
#define EFUSE_DIS_BT_S 12
#define EFUSE_DIS_DOWNLOAD_DCACHE (BIT(11))
#define EFUSE_DIS_DOWNLOAD_DCACHE_S 11
#define EFUSE_DIS_DOWNLOAD_ICACHE (BIT(10))
#define EFUSE_DIS_DOWNLOAD_ICACHE_S 10
#define EFUSE_DIS_DCACHE (BIT(9))
#define EFUSE_DIS_DCACHE_S 9
#define EFUSE_DIS_ICACHE (BIT(8))
#define EFUSE_DIS_ICACHE_S 8
#define EFUSE_DIS_RTC_RAM_BOOT (BIT(7))
#define EFUSE_DIS_RTC_RAM_BOOT_S 7
#define EFUSE_RD_DIS 0x0000007F
#define EFUSE_RD_DIS_S 0

#define EFUSE_PGM_DATA2_REG (REG_EFUSE_BASE + 0x008)
#define EFUSE_KEY_PURPOSE_1 0x0000000F
#define EFUSE_KEY_PURPOSE_1_S 28
#define EFUSE_KEY_PURPOSE_0 0x0000000F
#define EFUSE_KEY_PURPOSE_0_S 24
#define EFUSE_SECURE_BOOT_KEY_REVOKE2 (BIT(23))
#define EFUSE_SECURE_BOOT_KEY_REVOKE2_S 23
#define EFUSE_SECURE_BOOT_KEY_REVOKE1 (BIT(22))
#define EFUSE_SECURE_BOOT_KEY_REVOKE1_S 22
#define EFUSE_SECURE_BOOT_KEY_REVOKE0 (BIT(21))
#define EFUSE_SECURE_BOOT_KEY_REVOKE0_S 21
#define EFUSE_SPI_BOOT_CRYPT_CNT 0x00000007
#define EFUSE_SPI_BOOT_CRYPT_CNT_S 18
#define EFUSE_WDT_DELAY_SEL 0x00000003
#define EFUSE_WDT_DELAY_SEL_S 16
#define EFUSE_SDIO_DCAP 0x00000003
#define EFUSE_SDIO_DCAP_S 14
#define EFUSE_SDIO_INIT 0x00000003
#define EFUSE_SDIO_INIT_S 12
#define EFUSE_SDIO_DCURLIM 0x00000007
#define EFUSE_SDIO_DCURLIM_S 9
#define EFUSE_SDIO_ENCURLIM (BIT(8))
#define EFUSE_SDIO_ENCURLIM_S 8
#define EFUSE_SDIO_EN_INIT (BIT(7))
#define EFUSE_SDIO_EN_INIT_S 7
#define EFUSE_SDIO_FORCE (BIT(6))
#define EFUSE_SDIO_FORCE_S 6
#define EFUSE_SDIO_TIEH (BIT(5))
#define EFUSE_SDIO_TIEH_S 5
#define EFUSE_SDIO_XPD (BIT(4))
#define EFUSE_SDIO_XPD_S 4
#define EFUSE_SDIO_DREFL 0x00000003
#define EFUSE_SDIO_DREFL_S 2
#define EFUSE_SDIO_DREFM 0x00000003
#define EFUSE_SDIO_DREFM_S 0

#define EFUSE_PGM_DATA3_REG (REG_EFUSE_BASE + 0x00c)
#define EFUSE_FLASH_TPUW 0x0000000F
#define EFUSE_FLASH_TPUW_S 28
#define EFUSE_XTAL_FREQ 0x0000003F
#define EFUSE_XTAL_FREQ_S 22
#define EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE (BIT(21))
#define EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE_S 21
#define EFUSE_SECURE_BOOT_EN (BIT(20))
#define EFUSE_SECURE_BOOT_EN_S 20
#define EFUSE_KEY_PURPOSE_6 0x0000000F
#define EFUSE_KEY_PURPOSE_6_S 16
#define EFUSE_KEY_PURPOSE_5 0x0000000F
#define EFUSE_KEY_PURPOSE_5_S 12
#define EFUSE_KEY_PURPOSE_4 0x0000000F
#define EFUSE_KEY_PURPOSE_4_S 8
#define EFUSE_KEY_PURPOSE_3 0x0000000F
#define EFUSE_KEY_PURPOSE_3_S 4
#define EFUSE_KEY_PURPOSE_2 0x0000000F
#define EFUSE_KEY_PURPOSE_2_S 0

#define EFUSE_PGM_DATA4_REG (REG_EFUSE_BASE + 0x010)
#define EFUSE_RESERVE 0x00FFFFFF
#define EFUSE_RESERVE_S 8
#define EFUSE_UART_PRINT_CONTROL 0x00000003
#define EFUSE_UART_PRINT_CONTROL_S 6
#define EFUSE_ENABLE_SECURITY_DOWNLOAD (BIT(5))
#define EFUSE_ENABLE_SECURITY_DOWNLOAD_S 5
#define EFUSE_DIS_USB_DOWNLOAD_MODE (BIT(4))
#define EFUSE_DIS_USB_DOWNLOAD_MODE_S 4
#define EFUSE_DIS_TINY_BASIC (BIT(3))
#define EFUSE_DIS_TINY_BASIC_S 3
#define EFUSE_UART_PRINT_CHANNEL (BIT(2))
#define EFUSE_UART_PRINT_CHANNEL_S 2
#define EFUSE_DIS_LEGACY_SPI_BOOT (BIT(1))
#define EFUSE_DIS_LEGACY_SPI_BOOT_S 1
#define EFUSE_DIS_DOWNLOAD_MODE (BIT(0))
#define EFUSE_DIS_DOWNLOAD_MODE_S 0

#define EFUSE_PGM_DATA5_REG (REG_EFUSE_BASE + 0x014)
#define EFUSE_RS_DATA_23 0x000000FF
#define EFUSE_RS_DATA_23_S 24
#define EFUSE_CHIP_VERSION 0x00FFFFFF
#define EFUSE_CHIP_VERSION_S 0

#define EFUSE_PGM_DATA6_REG (REG_EFUSE_BASE + 0x018)
#define EFUSE_RS_DATA_24_27 0xFFFFFFFF
#define EFUSE_RS_DATA_24_27_S 0

#define EFUSE_PGM_DATA7_REG (REG_EFUSE_BASE + 0x01c)
#define EFUSE_RS_DATA_28_31 0xFFFFFFFF
#define EFUSE_RS_DATA_28_31_S 0

#define EFUSE_PGM_CHECK_VALUE0_REG (REG_EFUSE_BASE + 0x020)
#define EFUSE_RS_DATA_32_35 0xFFFFFFFF
#define EFUSE_RS_DATA_32_35_S 0

#define EFUSE_PGM_CHECK_VALUE1_REG (REG_EFUSE_BASE + 0x024)
#define EFUSE_RS_DATA_36_39 0xFFFFFFFF
#define EFUSE_RS_DATA_36_39_S 0

#define EFUSE_PGM_CHECK_VALUE2_REG (REG_EFUSE_BASE + 0x028)
#define EFUSE_RS_DATA_40_43 0xFFFFFFFF
#define EFUSE_RS_DATA_40_43_S 0

#define EFUSE_RD_WR_DIS_REG (REG_EFUSE_BASE + 0x02c)
#define EFUSE_WR_DIS 0xFFFFFFFF
#define EFUSE_WR_DIS_S 0

#define EFUSE_RD_REPEAT_DATA0_REG (REG_EFUSE_BASE + 0x030)
#define EFUSE_SDIO_DREFH 0x00000003
#define EFUSE_SDIO_DREFH_S 30
#define EFUSE_SDIO_MODECURLIM (BIT(29))
#define EFUSE_SDIO_MODECURLIM_S 29
#define EFUSE_USB_DRES 0x00000007
#define EFUSE_USB_DRES_S 26
#define EFUSE_EXT_PHY_ENABLE (BIT(25))
#define EFUSE_EXT_PHY_ENABLE_S 25
#define EFUSE_USB_EXCHG_PINS (BIT(24))
#define EFUSE_USB_EXCHG_PINS_S 24
#define EFUSE_USB_DREFL 0x00000003
#define EFUSE_USB_DREFL_S 22
#define EFUSE_USB_DREFH 0x00000003
#define EFUSE_USB_DREFH_S 20
#define EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT (BIT(19))
#define EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT_S 19
#define EFUSE_HARD_DIS_JTAG (BIT(18))
#define EFUSE_HARD_DIS_JTAG_S 18
#define EFUSE_SOFT_DIS_JTAG (BIT(17))
#define EFUSE_SOFT_DIS_JTAG_S 17
#define EFUSE_DIS_EFUSE_ATE_WR (BIT(16))
#define EFUSE_DIS_EFUSE_ATE_WR_S 16
#define EFUSE_DIS_SDIO_ACCESS (BIT(15))
#define EFUSE_DIS_SDIO_ACCESS_S 15
#define EFUSE_DIS_CAN (BIT(14))
#define EFUSE_DIS_CAN_S 14
#define EFUSE_DIS_USB (BIT(13))
#define EFUSE_DIS_USB_S 13
#define EFUSE_DIS_BT (BIT(12))
#define EFUSE_DIS_BT_S 12
#define EFUSE_DIS_DOWNLOAD_DCACHE (BIT(11))
#define EFUSE_DIS_DOWNLOAD_DCACHE_S 11
#define EFUSE_DIS_DOWNLOAD_ICACHE (BIT(10))
#define EFUSE_DIS_DOWNLOAD_ICACHE_S 10
#define EFUSE_DIS_DCACHE (BIT(9))
#define EFUSE_DIS_DCACHE_S 9
#define EFUSE_DIS_ICACHE (BIT(8))
#define EFUSE_DIS_ICACHE_S 8
#define EFUSE_DIS_RTC_RAM_BOOT (BIT(7))
#define EFUSE_DIS_RTC_RAM_BOOT_S 7
#define EFUSE_RD_DIS 0x0000007F
#define EFUSE_RD_DIS_S 0

#define EFUSE_RD_REPEAT_DATA1_REG (REG_EFUSE_BASE + 0x034)
#define EFUSE_KEY_PURPOSE_1 0x0000000F
#define EFUSE_KEY_PURPOSE_1_S 28
#define EFUSE_KEY_PURPOSE_0 0x0000000F
#define EFUSE_KEY_PURPOSE_0_S 24
#define EFUSE_SECURE_BOOT_KEY_REVOKE2 (BIT(23))
#define EFUSE_SECURE_BOOT_KEY_REVOKE2_S 23
#define EFUSE_SECURE_BOOT_KEY_REVOKE1 (BIT(22))
#define EFUSE_SECURE_BOOT_KEY_REVOKE1_S 22
#define EFUSE_SECURE_BOOT_KEY_REVOKE0 (BIT(21))
#define EFUSE_SECURE_BOOT_KEY_REVOKE0_S 21
#define EFUSE_SPI_BOOT_CRYPT_CNT 0x00000007
#define EFUSE_SPI_BOOT_CRYPT_CNT_S 18
#define EFUSE_WDT_DELAY_SEL 0x00000003
#define EFUSE_WDT_DELAY_SEL_S 16
#define EFUSE_EUFSE_SDIO_DCAP 0x00000003
#define EFUSE_EUFSE_SDIO_DCAP_S 14
#define EFUSE_SDIO_INIT 0x00000003
#define EFUSE_SDIO_INIT_S 12
#define EFUSE_SDIO_DCURLIM 0x00000007
#define EFUSE_SDIO_DCURLIM_S 9
#define EFUSE_SDIO_ENCURLIM (BIT(8))
#define EFUSE_SDIO_ENCURLIM_S 8
#define EFUSE_SDIO_EN_INIT (BIT(7))
#define EFUSE_SDIO_EN_INIT_S 7
#define EFUSE_SDIO_FORCE (BIT(6))
#define EFUSE_SDIO_FORCE_S 6
#define EFUSE_SDIO_TIEH (BIT(5))
#define EFUSE_SDIO_TIEH_S 5
#define EFUSE_SDIO_XPD (BIT(4))
#define EFUSE_SDIO_XPD_S 4
#define EFUSE_SDIO_DREFL 0x00000003
#define EFUSE_SDIO_DREFL_S 2
#define EFUSE_SDIO_DREFM 0x00000003
#define EFUSE_SDIO_DREFM_S 0

#define EFUSE_RD_REPEAT_DATA2_REG (REG_EFUSE_BASE + 0x038)
#define EFUSE_FLASH_TPUW 0x0000000F
#define EFUSE_FLASH_TPUW_S 28
#define EFUSE_XTAL_FREQ 0x0000003F
#define EFUSE_XTAL_FREQ_S 22
#define EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE (BIT(21))
#define EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE_S 21
#define EFUSE_SECURE_BOOT_EN (BIT(20))
#define EFUSE_SECURE_BOOT_EN_S 20
#define EFUSE_KEY_PURPOSE_6 0x0000000F
#define EFUSE_KEY_PURPOSE_6_S 16
#define EFUSE_KEY_PURPOSE_5 0x0000000F
#define EFUSE_KEY_PURPOSE_5_S 12
#define EFUSE_KEY_PURPOSE_4 0x0000000F
#define EFUSE_KEY_PURPOSE_4_S 8
#define EFUSE_KEY_PURPOSE_3 0x0000000F
#define EFUSE_KEY_PURPOSE_3_S 4
#define EFUSE_KEY_PURPOSE_2 0x0000000F
#define EFUSE_KEY_PURPOSE_2_S 0

#define EFUSE_RD_REPEAT_DATA3_REG (REG_EFUSE_BASE + 0x03c)
#define EFUSE_RESERVE 0x00FFFFFF
#define EFUSE_RESERVE_S 8
#define EFUSE_UART_PRINT_CONTROL 0x00000003
#define EFUSE_UART_PRINT_CONTROL_S 6
#define EFUSE_ENABLE_SECURITY_DOWNLOAD (BIT(5))
#define EFUSE_ENABLE_SECURITY_DOWNLOAD_S 5
#define EFUSE_DIS_USB_DOWNLOAD_MODE (BIT(4))
#define EFUSE_DIS_USB_DOWNLOAD_MODE_S 4
#define EFUSE_DIS_TINY_BASIC (BIT(3))
#define EFUSE_DIS_TINY_BASIC_S 3
#define EFUSE_UART_PRINT_CHANNEL (BIT(2))
#define EFUSE_UART_PRINT_CHANNEL_S 2
#define EFUSE_DIS_LEGACY_SPI_BOOT (BIT(1))
#define EFUSE_DIS_LEGACY_SPI_BOOT_S 1
#define EFUSE_DIS_DOWNLOAD_MODE (BIT(0))
#define EFUSE_DIS_DOWNLOAD_MODE_S 0

#define EFUSE_RD_REPEAT_DATA4_REG (REG_EFUSE_BASE + 0x040)
#define EFUSE_CHIP_VERSION 0x00FFFFFF
#define EFUSE_CHIP_VERSION_S 0

#define EFUSE_RD_MAC_SPI_8M_0_REG (REG_EFUSE_BASE + 0x044)
#define EFUSE_MAC_0 0xFFFFFFFF
#define EFUSE_MAC_0_S 0

#define EFUSE_RD_MAC_SPI_8M_1_REG (REG_EFUSE_BASE + 0x048)
#define EFUSE_SPI_PAD_CONF_0 0x0000FFFF
#define EFUSE_SPI_PAD_CONF_0_S 16
#define EFUSE_MAC_1 0x0000FFFF
#define EFUSE_MAC_1_S 0

#define EFUSE_RD_MAC_SPI_8M_2_REG (REG_EFUSE_BASE + 0x04c)
#define EFUSE_CLK8M_FREQ 0x00000FFF
#define EFUSE_CLK8M_FREQ_S 20
#define EFUSE_SPI_PAD_CONF_1 0x000FFFFF
#define EFUSE_SPI_PAD_CONF_1_S 0

#define EFUSE_RD_MAC_SPI_8M_3_REG (REG_EFUSE_BASE + 0x050)
#define EFUSE_SYS_DATA_PART0_0 0xFFFFFFFF
#define EFUSE_SYS_DATA_PART0_0_S 0

#define EFUSE_RD_MAC_SPI_8M_4_REG (REG_EFUSE_BASE + 0x054)
#define EFUSE_SYS_DATA_PART0_1 0xFFFFFFFF
#define EFUSE_SYS_DATA_PART0_1_S 0

#define EFUSE_RD_MAC_SPI_8M_5_REG (REG_EFUSE_BASE + 0x058)
#define EFUSE_SYS_DATA_PART0_2 0xFFFFFFFF
#define EFUSE_SYS_DATA_PART0_2_S 0

#define EFUSE_RD_SYS_DATA0_REG (REG_EFUSE_BASE + 0x05c)
#define EFUSE_SYS_DATA0 0xFFFFFFFF
#define EFUSE_SYS_DATA0_S 0

#define EFUSE_RD_SYS_DATA1_REG (REG_EFUSE_BASE + 0x060)
#define EFUSE_SYS_DATA1 0xFFFFFFFF
#define EFUSE_SYS_DATA1_S 0

#define EFUSE_RD_SYS_DATA2_REG (REG_EFUSE_BASE + 0x064)
#define EFUSE_SYS_DATA2 0xFFFFFFFF
#define EFUSE_SYS_DATA2_S 0

#define EFUSE_RD_SYS_DATA3_REG (REG_EFUSE_BASE + 0x068)
#define EFUSE_SYS_DATA3 0xFFFFFFFF
#define EFUSE_SYS_DATA3_S 0

#define EFUSE_RD_SYS_DATA4_REG (REG_EFUSE_BASE + 0x06c)
#define EFUSE_SYS_DATA4 0xFFFFFFFF
#define EFUSE_SYS_DATA4_S 0

#define EFUSE_RD_SYS_DATA5_REG (REG_EFUSE_BASE + 0x070)
#define EFUSE_SYS_DATA5 0xFFFFFFFF
#define EFUSE_SYS_DATA5_S 0

#define EFUSE_RD_SYS_DATA6_REG (REG_EFUSE_BASE + 0x074)
#define EFUSE_SYS_DATA6 0xFFFFFFFF
#define EFUSE_SYS_DATA6_S 0

#define EFUSE_RD_SYS_DATA7_REG (REG_EFUSE_BASE + 0x078)
#define EFUSE_SYS_DATA7 0xFFFFFFFF
#define EFUSE_SYS_DATA7_S 0

#define EFUSE_RD_USR_DATA0_REG (REG_EFUSE_BASE + 0x07c)
#define EFUSE_USR_DATA0 0xFFFFFFFF
#define EFUSE_USR_DATA0_S 0

#define EFUSE_RD_USR_DATA1_REG (REG_EFUSE_BASE + 0x080)
#define EFUSE_USR_DATA1 0xFFFFFFFF
#define EFUSE_USR_DATA1_S 0

#define EFUSE_RD_USR_DATA2_REG (REG_EFUSE_BASE + 0x084)
#define EFUSE_USR_DATA2 0xFFFFFFFF
#define EFUSE_USR_DATA2_S 0

#define EFUSE_RD_USR_DATA3_REG (REG_EFUSE_BASE + 0x088)
#define EFUSE_USR_DATA3 0xFFFFFFFF
#define EFUSE_USR_DATA3_S 0

#define EFUSE_RD_USR_DATA4_REG (REG_EFUSE_BASE + 0x08c)
#define EFUSE_USR_DATA4 0xFFFFFFFF
#define EFUSE_USR_DATA4_S 0

#define EFUSE_RD_USR_DATA5_REG (REG_EFUSE_BASE + 0x090)
#define EFUSE_USR_DATA5 0xFFFFFFFF
#define EFUSE_USR_DATA5_S 0

#define EFUSE_RD_USR_DATA6_REG (REG_EFUSE_BASE + 0x094)
#define EFUSE_USR_DATA6 0xFFFFFFFF
#define EFUSE_USR_DATA6_S 0

#define EFUSE_RD_USR_DATA7_REG (REG_EFUSE_BASE + 0x098)
#define EFUSE_USR_DATA7 0xFFFFFFFF
#define EFUSE_USR_DATA7_S 0

#define EFUSE_RD_KEY0_DATA0_REG (REG_EFUSE_BASE + 0x09c)
#define EFUSE_KEY0_DATA0 0xFFFFFFFF
#define EFUSE_KEY0_DATA0_S 0

#define EFUSE_RD_KEY0_DATA1_REG (REG_EFUSE_BASE + 0x0a0)
#define EFUSE_KEY0_DATA1 0xFFFFFFFF
#define EFUSE_KEY0_DATA1_S 0

#define EFUSE_RD_KEY0_DATA2_REG (REG_EFUSE_BASE + 0x0a4)
#define EFUSE_KEY0_DATA2 0xFFFFFFFF
#define EFUSE_KEY0_DATA2_S 0

#define EFUSE_RD_KEY0_DATA3_REG (REG_EFUSE_BASE + 0x0a8)
#define EFUSE_KEY0_DATA3 0xFFFFFFFF
#define EFUSE_KEY0_DATA3_S 0

#define EFUSE_RD_KEY0_DATA4_REG (REG_EFUSE_BASE + 0x0ac)
#define EFUSE_KEY0_DATA4 0xFFFFFFFF
#define EFUSE_KEY0_DATA4_S 0

#define EFUSE_RD_KEY0_DATA5_REG (REG_EFUSE_BASE + 0x0b0)
#define EFUSE_KEY0_DATA5 0xFFFFFFFF
#define EFUSE_KEY0_DATA5_S 0

#define EFUSE_RD_KEY0_DATA6_REG (REG_EFUSE_BASE + 0x0b4)
#define EFUSE_KEY0_DATA6 0xFFFFFFFF
#define EFUSE_KEY0_DATA6_S 0

#define EFUSE_RD_KEY0_DATA7_REG (REG_EFUSE_BASE + 0x0b8)
#define EFUSE_KEY0_DATA7 0xFFFFFFFF
#define EFUSE_KEY0_DATA7_S 0

#define EFUSE_RD_KEY1_DATA0_REG (REG_EFUSE_BASE + 0x0bc)
#define EFUSE_KEY1_DATA0 0xFFFFFFFF
#define EFUSE_KEY1_DATA0_S 0

#define EFUSE_RD_KEY1_DATA1_REG (REG_EFUSE_BASE + 0x0c0)
#define EFUSE_KEY1_DATA1 0xFFFFFFFF
#define EFUSE_KEY1_DATA1_S 0

#define EFUSE_RD_KEY1_DATA2_REG (REG_EFUSE_BASE + 0x0c4)
#define EFUSE_KEY1_DATA2 0xFFFFFFFF
#define EFUSE_KEY1_DATA2_S 0

#define EFUSE_RD_KEY1_DATA3_REG (REG_EFUSE_BASE + 0x0c8)
#define EFUSE_KEY1_DATA3 0xFFFFFFFF
#define EFUSE_KEY1_DATA3_S 0

#define EFUSE_RD_KEY1_DATA4_REG (REG_EFUSE_BASE + 0x0cc)
#define EFUSE_KEY1_DATA4 0xFFFFFFFF
#define EFUSE_KEY1_DATA4_S 0

#define EFUSE_RD_KEY1_DATA5_REG (REG_EFUSE_BASE + 0x0d0)
#define EFUSE_KEY1_DATA5 0xFFFFFFFF
#define EFUSE_KEY1_DATA5_S 0

#define EFUSE_RD_KEY1_DATA6_REG (REG_EFUSE_BASE + 0x0d4)
#define EFUSE_KEY1_DATA6 0xFFFFFFFF
#define EFUSE_KEY1_DATA6_S 0

#define EFUSE_RD_KEY1_DATA7_REG (REG_EFUSE_BASE + 0x0d8)
#define EFUSE_KEY1_DATA7 0xFFFFFFFF
#define EFUSE_KEY1_DATA7_S 0

#define EFUSE_RD_KEY2_DATA0_REG (REG_EFUSE_BASE + 0x0dc)
#define EFUSE_KEY2_DATA0 0xFFFFFFFF
#define EFUSE_KEY2_DATA0_S 0

#define EFUSE_RD_KEY2_DATA1_REG (REG_EFUSE_BASE + 0x0e0)
#define EFUSE_KEY2_DATA1 0xFFFFFFFF
#define EFUSE_KEY2_DATA1_S 0

#define EFUSE_RD_KEY2_DATA2_REG (REG_EFUSE_BASE + 0x0e4)
#define EFUSE_KEY2_DATA2 0xFFFFFFFF
#define EFUSE_KEY2_DATA2_S 0

#define EFUSE_RD_KEY2_DATA3_REG (REG_EFUSE_BASE + 0x0e8)
#define EFUSE_KEY2_DATA3 0xFFFFFFFF
#define EFUSE_KEY2_DATA3_S 0

#define EFUSE_RD_KEY2_DATA4_REG (REG_EFUSE_BASE + 0x0ec)
#define EFUSE_KEY2_DATA4 0xFFFFFFFF
#define EFUSE_KEY2_DATA4_S 0

#define EFUSE_RD_KEY2_DATA5_REG (REG_EFUSE_BASE + 0x0f0)
#define EFUSE_KEY2_DATA5 0xFFFFFFFF
#define EFUSE_KEY2_DATA5_S 0

#define EFUSE_RD_KEY2_DATA6_REG (REG_EFUSE_BASE + 0x0f4)
#define EFUSE_KEY2_DATA6 0xFFFFFFFF
#define EFUSE_KEY2_DATA6_S 0

#define EFUSE_RD_KEY2_DATA7_REG (REG_EFUSE_BASE + 0x0f8)
#define EFUSE_KEY2_DATA7 0xFFFFFFFF
#define EFUSE_KEY2_DATA7_S 0

#define EFUSE_RD_KEY3_DATA0_REG (REG_EFUSE_BASE + 0x0fc)
#define EFUSE_KEY3_DATA0 0xFFFFFFFF
#define EFUSE_KEY3_DATA0_S 0

#define EFUSE_RD_KEY3_DATA1_REG (REG_EFUSE_BASE + 0x100)
#define EFUSE_KEY3_DATA1 0xFFFFFFFF
#define EFUSE_KEY3_DATA1_S 0

#define EFUSE_RD_KEY3_DATA2_REG (REG_EFUSE_BASE + 0x104)
#define EFUSE_KEY3_DATA2 0xFFFFFFFF
#define EFUSE_KEY3_DATA2_S 0

#define EFUSE_RD_KEY3_DATA3_REG (REG_EFUSE_BASE + 0x108)
#define EFUSE_KEY3_DATA3 0xFFFFFFFF
#define EFUSE_KEY3_DATA3_S 0

#define EFUSE_RD_KEY3_DATA4_REG (REG_EFUSE_BASE + 0x10c)
#define EFUSE_KEY3_DATA4 0xFFFFFFFF
#define EFUSE_KEY3_DATA4_S 0

#define EFUSE_RD_KEY3_DATA5_REG (REG_EFUSE_BASE + 0x110)
#define EFUSE_KEY3_DATA5 0xFFFFFFFF
#define EFUSE_KEY3_DATA5_S 0

#define EFUSE_RD_KEY3_DATA6_REG (REG_EFUSE_BASE + 0x114)
#define EFUSE_KEY3_DATA6 0xFFFFFFFF
#define EFUSE_KEY3_DATA6_S 0

#define EFUSE_RD_KEY3_DATA7_REG (REG_EFUSE_BASE + 0x118)
#define EFUSE_KEY3_DATA7 0xFFFFFFFF
#define EFUSE_KEY3_DATA7_S 0

#define EFUSE_RD_KEY4_DATA0_REG (REG_EFUSE_BASE + 0x11c)
#define EFUSE_KEY4_DATA0 0xFFFFFFFF
#define EFUSE_KEY4_DATA0_S 0

#define EFUSE_RD_KEY4_DATA1_REG (REG_EFUSE_BASE + 0x120)
#define EFUSE_KEY4_DATA1 0xFFFFFFFF
#define EFUSE_KEY4_DATA1_S 0

#define EFUSE_RD_KEY4_DATA2_REG (REG_EFUSE_BASE + 0x124)
#define EFUSE_KEY4_DATA2 0xFFFFFFFF
#define EFUSE_KEY4_DATA2_S 0

#define EFUSE_RD_KEY4_DATA3_REG (REG_EFUSE_BASE + 0x128)
#define EFUSE_KEY4_DATA3 0xFFFFFFFF
#define EFUSE_KEY4_DATA3_S 0

#define EFUSE_RD_KEY4_DATA4_REG (REG_EFUSE_BASE + 0x12c)
#define EFUSE_KEY4_DATA4 0xFFFFFFFF
#define EFUSE_KEY4_DATA4_S 0

#define EFUSE_RD_KEY4_DATA5_REG (REG_EFUSE_BASE + 0x130)
#define EFUSE_KEY4_DATA5 0xFFFFFFFF
#define EFUSE_KEY4_DATA5_S 0

#define EFUSE_RD_KEY4_DATA6_REG (REG_EFUSE_BASE + 0x134)
#define EFUSE_KEY4_DATA6 0xFFFFFFFF
#define EFUSE_KEY4_DATA6_S 0

#define EFUSE_RD_KEY4_DATA7_REG (REG_EFUSE_BASE + 0x138)
#define EFUSE_KEY4_DATA7 0xFFFFFFFF
#define EFUSE_KEY4_DATA7_S 0

#define EFUSE_RD_KEY5_DATA0_REG (REG_EFUSE_BASE + 0x13c)
#define EFUSE_KEY5_DATA0 0xFFFFFFFF
#define EFUSE_KEY5_DATA0_S 0

#define EFUSE_RD_KEY5_DATA1_REG (REG_EFUSE_BASE + 0x140)
#define EFUSE_KEY5_DATA1 0xFFFFFFFF
#define EFUSE_KEY5_DATA1_S 0

#define EFUSE_RD_KEY5_DATA2_REG (REG_EFUSE_BASE + 0x144)
#define EFUSE_KEY5_DATA2 0xFFFFFFFF
#define EFUSE_KEY5_DATA2_S 0

#define EFUSE_RD_KEY5_DATA3_REG (REG_EFUSE_BASE + 0x148)
#define EFUSE_KEY5_DATA3 0xFFFFFFFF
#define EFUSE_KEY5_DATA3_S 0

#define EFUSE_RD_KEY5_DATA4_REG (REG_EFUSE_BASE + 0x14c)
#define EFUSE_KEY5_DATA4 0xFFFFFFFF
#define EFUSE_KEY5_DATA4_S 0

#define EFUSE_RD_KEY5_DATA5_REG (REG_EFUSE_BASE + 0x150)
#define EFUSE_KEY5_DATA5 0xFFFFFFFF
#define EFUSE_KEY5_DATA5_S 0

#define EFUSE_RD_KEY5_DATA6_REG (REG_EFUSE_BASE + 0x154)
#define EFUSE_KEY5_DATA6 0xFFFFFFFF
#define EFUSE_KEY5_DATA6_S 0

#define EFUSE_RD_KEY5_DATA7_REG (REG_EFUSE_BASE + 0x158)
#define EFUSE_KEY5_DATA7 0xFFFFFFFF
#define EFUSE_KEY5_DATA7_S 0

#define EFUSE_RD_KEY6_DATA0_REG (REG_EFUSE_BASE + 0x15c)
#define EFUSE_KEY6_DATA0 0xFFFFFFFF
#define EFUSE_KEY6_DATA0_S 0

#define EFUSE_RD_KEY6_DATA1_REG (REG_EFUSE_BASE + 0x160)
#define EFUSE_KEY6_DATA1 0xFFFFFFFF
#define EFUSE_KEY6_DATA1_S 0

#define EFUSE_RD_KEY6_DATA2_REG (REG_EFUSE_BASE + 0x164)
#define EFUSE_KEY6_DATA2 0xFFFFFFFF
#define EFUSE_KEY6_DATA2_S 0

#define EFUSE_RD_KEY6_DATA3_REG (REG_EFUSE_BASE + 0x168)
#define EFUSE_KEY6_DATA3 0xFFFFFFFF
#define EFUSE_KEY6_DATA3_S 0

#define EFUSE_RD_KEY6_DATA4_REG (REG_EFUSE_BASE + 0x16c)
#define EFUSE_KEY6_DATA4 0xFFFFFFFF
#define EFUSE_KEY6_DATA4_S 0

#define EFUSE_RD_KEY6_DATA5_REG (REG_EFUSE_BASE + 0x170)
#define EFUSE_KEY6_DATA5 0xFFFFFFFF
#define EFUSE_KEY6_DATA5_S 0

#define EFUSE_RD_KEY6_DATA6_REG (REG_EFUSE_BASE + 0x174)
#define EFUSE_KEY6_DATA6 0xFFFFFFFF
#define EFUSE_KEY6_DATA6_S 0

#define EFUSE_RD_KEY6_DATA7_REG (REG_EFUSE_BASE + 0x178)
#define EFUSE_KEY6_DATA7 0xFFFFFFFF
#define EFUSE_KEY6_DATA7_S 0

#define EFUSE_RD_REPEAT_ERR0_REG (REG_EFUSE_BASE + 0x17c)
#define EFUSE_RD_SDIO_DREFH_ERR 0x00000003
#define EFUSE_RD_SDIO_DREFH_ERR_S 30
#define EFUSE_RD_SDIO_MODECURLIM_ERR (BIT(29))
#define EFUSE_RD_SDIO_MODECURLIM_ERR_S 29
#define EFUSE_RD_USB_DRES_ERR 0x00000007
#define EFUSE_RD_USB_DRES_ERR_S 26
#define EFUSE_RD_EXT_PHY_ENABLE (BIT(25))
#define EFUSE_RD_EXT_PHY_ENABLE_S 25
#define EFUSE_RD_USB_EXCHG_PINS_ERR (BIT(24))
#define EFUSE_RD_USB_EXCHG_PINS_ERR_S 24
#define EFUSE_RD_USB_DREFL_ERR 0x00000003
#define EFUSE_RD_USB_DREFL_ERR_S 22
#define EFUSE_RD_USB_DREFH_ERR 0x00000003
#define EFUSE_RD_USB_DREFH_ERR_S 20
#define EFUSE_RD_DIS_DOWNLOAD_MANUAL_ENCRYPT_ERR (BIT(19))
#define EFUSE_RD_DIS_DOWNLOAD_MANUAL_ENCRYPT_ERR_S 19
#define EFUSE_RD_HARD_DIS_JTAG_ERR (BIT(18))
#define EFUSE_RD_HARD_DIS_JTAG_ERR_S 18
#define EFUSE_RD_SOFT_DIS_JTAG_ERR (BIT(17))
#define EFUSE_RD_SOFT_DIS_JTAG_ERR_S 17
#define EFUSE_RD_DIS_EFUSE_ATE_WR_ERR (BIT(16))
#define EFUSE_RD_DIS_EFUSE_ATE_WR_ERR_S 16
#define EFUSE_RD_DIS_SDIO_ACCESS_ERR (BIT(15))
#define EFUSE_RD_DIS_SDIO_ACCESS_ERR_S 15
#define EFUSE_RD_DIS_CAN_ERR (BIT(14))
#define EFUSE_RD_DIS_CAN_ERR_S 14
#define EFUSE_RD_DIS_USB_ERR (BIT(13))
#define EFUSE_RD_DIS_USB_ERR_S 13
#define EFUSE_RD_DIS_BT_ERR (BIT(12))
#define EFUSE_RD_DIS_BT_ERR_S 12
#define EFUSE_RD_DIS_DOWNLOAD_DCACHE_ERR (BIT(11))
#define EFUSE_RD_DIS_DOWNLOAD_DCACHE_ERR_S 11
#define EFUSE_RD_DIS_DOWNLOAD_ICACHE_ERR (BIT(10))
#define EFUSE_RD_DIS_DOWNLOAD_ICACHE_ERR_S 10
#define EFUSE_RD_DIS_DCACHE_ERR (BIT(9))
#define EFUSE_RD_DIS_DCACHE_ERR_S 9
#define EFUSE_RD_DIS_ICACHE_ERR (BIT(8))
#define EFUSE_RD_DIS_ICACHE_ERR_S 8
#define EFUSE_RD_DIS_RTC_RAM_BOOT_ERR (BIT(7))
#define EFUSE_RD_DIS_RTC_RAM_BOOT_ERR_S 7
#define EFUSE_RD_RD_DIS_ERR 0x0000007F
#define EFUSE_RD_RD_DIS_ERR_S 0

#define EFUSE_RD_REPEAT_ERR1_REG (REG_EFUSE_BASE + 0x180)
#define EFUSE_RD_KEY_PURPOSE_1_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_1_ERR_S 28
#define EFUSE_RD_KEY_PURPOSE_0_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_0_ERR_S 24
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE2_ERR (BIT(23))
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE2_ERR_S 23
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE1_ERR (BIT(22))
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE1_ERR_S 22
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE0_ERR (BIT(21))
#define EFUSE_RD_SECURE_BOOT_KEY_REVOKE0_ERR_S 21
#define EFUSE_RD_SPI_BOOT_CRYPT_CNT_ERR 0x00000007
#define EFUSE_RD_SPI_BOOT_CRYPT_CNT_ERR_S 18
#define EFUSE_RD_WDT_DELAY_SEL_ERR 0x00000003
#define EFUSE_RD_WDT_DELAY_SEL_ERR_S 16
#define EFUSE_RD_SDIO_DCAP_ERR 0x00000003
#define EFUSE_RD_SDIO_DCAP_ERR_S 14
#define EFUSE_RD_SDIO_INIT_ERR 0x00000003
#define EFUSE_RD_SDIO_INIT_ERR_S 12
#define EFUSE_RD_SDIO_DCURLIM_ERR 0x00000007
#define EFUSE_RD_SDIO_DCURLIM_ERR_S 9
#define EFUSE_RD_SDIO_ENCURLIM_ERR (BIT(8))
#define EFUSE_RD_SDIO_ENCURLIM_ERR_S 8
#define EFUSE_RD_SDIO_EN_INIT_ERR (BIT(7))
#define EFUSE_RD_SDIO_EN_INIT_ERR_S 7
#define EFUSE_RD_SDIO_FORCE_ERR (BIT(6))
#define EFUSE_RD_SDIO_FORCE_ERR_S 6
#define EFUSE_RD_SDIO_TIEH_ERR (BIT(5))
#define EFUSE_RD_SDIO_TIEH_ERR_S 5
#define EFUSE_RD_SDIO_XPD_ERR (BIT(4))
#define EFUSE_RD_SDIO_XPD_ERR_S 4
#define EFUSE_RD_SDIO_DREFL_ERR 0x00000003
#define EFUSE_RD_SDIO_DREFL_ERR_S 2
#define EFUSE_RD_SDIO_DREFM_ERR 0x00000003
#define EFUSE_RD_SDIO_DREFM_ERR_S 0

#define EFUSE_RD_REPEAT_ERR2_REG (REG_EFUSE_BASE + 0x184)
#define EFUSE_RD_FLASH_TPUW_ERR 0x0000000F
#define EFUSE_RD_FLASH_TPUW_ERR_S 28
#define EFUSE_RD_XTAL_FREQ_ERR 0x0000003F
#define EFUSE_RD_XTAL_FREQ_ERR_S 22
#define EFUSE_RD_SECURE_BOOT_AGGRESSIVE_REVOKE_ERR (BIT(21))
#define EFUSE_RD_SECURE_BOOT_AGGRESSIVE_REVOKE_ERR_S 21
#define EFUSE_RD_SECURE_BOOT_EN_ERR (BIT(20))
#define EFUSE_RD_SECURE_BOOT_EN_ERR_S 20
#define EFUSE_RD_KEY_PURPOSE_6_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_6_ERR_S 16
#define EFUSE_RD_KEY_PURPOSE_5_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_5_ERR_S 12
#define EFUSE_RD_KEY_PURPOSE_4_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_4_ERR_S 8
#define EFUSE_RD_KEY_PURPOSE_3_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_3_ERR_S 4
#define EFUSE_RD_KEY_PURPOSE_2_ERR 0x0000000F
#define EFUSE_RD_KEY_PURPOSE_2_ERR_S 0

#define EFUSE_RD_REPEAT_ERR3_REG (REG_EFUSE_BASE + 0x188)
#define EFUSE_RD_RESERVE_ERR 0x00FFFFFF
#define EFUSE_RD_RESERVE_ERR_S 8
#define EFUSE_RD_UART_PRINT_CONTROL 0x00000003
#define EFUSE_RD_UART_PRINT_CONTROL_S 6
#define EFUSE_RD_ENABLE_SECURITY_DOWNLOAD (BIT(5))
#define EFUSE_RD_ENABLE_SECURITY_DOWNLOAD_S 5
#define EFUSE_RD_DIS_USB_DOWNLOAD_MODE (BIT(4))
#define EFUSE_RD_DIS_USB_DOWNLOAD_MODE_S 4
#define EFUSE_RD_DIS_TINY_BASIC (BIT(3))
#define EFUSE_RD_DIS_TINY_BASIC_S 3
#define EFUSE_RD_UART_PRINT_CHANNEL (BIT(2))
#define EFUSE_RD_UART_PRINT_CHANNEL_S 2
#define EFUSE_RD_DIS_LEGACY_SPI_BOOT_ERR (BIT(1))
#define EFUSE_RD_DIS_LEGACY_SPI_BOOT_ERR_S 1
#define EFUSE_RD_DIS_DOWNLOAD_MODE_ERR (BIT(0))
#define EFUSE_RD_DIS_DOWNLOAD_MODE_ERR_S 0

#define EFUSE_RD_REPEAT_ERR4_REG (REG_EFUSE_BASE + 0x190)
#define EFUSE_RD_CHIP_VERSION_ERR 0x00FFFFFF
#define EFUSE_RD_CHIP_VERSION_ERR_S 0

#define EFUSE_RD_RS_ERR0_REG (REG_EFUSE_BASE + 0x194)
#define EFUSE_RD_KEY4_FAIL (BIT(31))
#define EFUSE_RD_KEY4_FAIL_S 31
#define EFUSE_RD_KEY4_ERR_NUM 0x00000007
#define EFUSE_RD_KEY4_ERR_NUM_S 28
#define EFUSE_RD_KEY3_FAIL (BIT(27))
#define EFUSE_RD_KEY3_FAIL_S 27
#define EFUSE_RD_KEY3_ERR_NUM 0x00000007
#define EFUSE_RD_KEY3_ERR_NUM_S 24
#define EFUSE_RD_KEY2_FAIL (BIT(23))
#define EFUSE_RD_KEY2_FAIL_S 23
#define EFUSE_RD_KEY2_ERR_NUM 0x00000007
#define EFUSE_RD_KEY2_ERR_NUM_S 20
#define EFUSE_RD_KEY1_FAIL (BIT(19))
#define EFUSE_RD_KEY1_FAIL_S 19
#define EFUSE_RD_KEY1_ERR_NUM 0x00000007
#define EFUSE_RD_KEY1_ERR_NUM_S 16
#define EFUSE_RD_KEY0_FAIL (BIT(15))
#define EFUSE_RD_KEY0_FAIL_S 15
#define EFUSE_RD_KEY0_ERR_NUM 0x00000007
#define EFUSE_RD_KEY0_ERR_NUM_S 12
#define EFUSE_RD_USR_DATA_FAIL (BIT(11))
#define EFUSE_RD_USR_DATA_FAIL_S 11
#define EFUSE_RD_USR_DATA_ERR_NUM 0x00000007
#define EFUSE_RD_USR_DATA_ERR_NUM_S 8
#define EFUSE_RD_SYS_ERR_FAIL (BIT(7))
#define EFUSE_RD_SYS_ERR_FAIL_S 7
#define EFUSE_RD_SYS_ERR_NUM 0x00000007
#define EFUSE_RD_SYS_ERR_NUM_S 4
#define EFUSE_RD_MAC_SPI_8M_FAIL (BIT(3))
#define EFUSE_RD_MAC_SPI_8M_FAIL_S 3
#define EFUSE_RD_MAC_SPI_8M_ERR_NUM 0x00000007
#define EFUSE_RD_MAC_SPI_8M_ERR_NUM_S 0

#define EFUSE_RD_RS_ERR1_REG (REG_EFUSE_BASE + 0x198)
#define EFUSE_RD_KEY6_FAIL (BIT(7))
#define EFUSE_RD_KEY6_FAIL_S 7
#define EFUSE_RD_KEY6_ERR_NUM 0x00000007
#define EFUSE_RD_KEY6_ERR_NUM_S 4
#define EFUSE_RD_KEY5_FAIL (BIT(3))
#define EFUSE_RD_KEY5_FAIL_S 3
#define EFUSE_RD_KEY5_ERR_NUM 0x00000007
#define EFUSE_RD_KEY5_ERR_NUM_S 0

#define EFUSE_CLK_REG (REG_EFUSE_BASE + 0x19c)
#define EFUSE_CLK_EN (BIT(16))
#define EFUSE_CLK_EN_S 16
#define EFUSE_MEM_PD (BIT(0))
#define EFUSE_MEM_PD_S 0

#define EFUSE_CONF_REG (REG_EFUSE_BASE + 0x1a0)
#define EFUSE_OP_CODE 0x0000FFFF
#define EFUSE_OP_CODE_S 0

#define EFUSE_STATUS_REG (REG_EFUSE_BASE + 0x1a4)
#define EFUSE_REPEAT_ERR_CNT 0x000000FF
#define EFUSE_REPEAT_ERR_CNT_S 9
#define EFUSE_OTP_VDDQ_IS_SW (BIT(8))
#define EFUSE_OTP_VDDQ_IS_SW_S 8
#define EFUSE_OTP_PGENB_SW (BIT(7))
#define EFUSE_OTP_PGENB_SW_S 7
#define EFUSE_OTP_CSB_SW (BIT(6))
#define EFUSE_OTP_CSB_SW_S 6
#define EFUSE_OTP_STROBE_SW (BIT(5))
#define EFUSE_OTP_STROBE_SW_S 5
#define EFUSE_OTP_VDDQ_C_SYNC2 (BIT(4))
#define EFUSE_OTP_VDDQ_C_SYNC2_S 4
#define EFUSE_OTP_LOAD_SW (BIT(3))
#define EFUSE_OTP_LOAD_SW_S 3
#define EFUSE_STATE 0x00000007
#define EFUSE_STATE_S 0

#define EFUSE_CMD_REG (REG_EFUSE_BASE + 0x1a8)
#define EFUSE_BLK_NUM 0x0000000F
#define EFUSE_BLK_NUM_S 2
#define EFUSE_PGM_CMD (BIT(1))
#define EFUSE_PGM_CMD_S 1
#define EFUSE_READ_CMD (BIT(0))
#define EFUSE_READ_CMD_S 0

#define EFUSE_INT_RAW_REG (REG_EFUSE_BASE + 0x1ac)
#define EFUSE_PGM_DONE_INT_RAW (BIT(1))
#define EFUSE_PGM_DONE_INT_RAW_S 1
#define EFUSE_READ_DONE_INT_RAW (BIT(0))
#define EFUSE_READ_DONE_INT_RAW_S 0

#define EFUSE_INT_ST_REG (REG_EFUSE_BASE + 0x1b0)
#define EFUSE_PGM_DONE_INT_ST (BIT(1))
#define EFUSE_PGM_DONE_INT_ST_S 1
#define EFUSE_READ_DONE_INT_ST (BIT(0))
#define EFUSE_READ_DONE_INT_ST_S 0

#define EFUSE_INT_ENA_REG (REG_EFUSE_BASE + 0x1b4)
#define EFUSE_PGM_DONE_INT_ENA (BIT(1))
#define EFUSE_PGM_DONE_INT_ENA_S 1
#define EFUSE_READ_DONE_INT_ENA (BIT(0))
#define EFUSE_READ_DONE_INT_ENA_S 0

#define EFUSE_INT_CLR_REG (REG_EFUSE_BASE + 0x1b8)
#define EFUSE_PGM_DONE_INT_CLR (BIT(1))
#define EFUSE_PGM_DONE_INT_CLR_S 1
#define EFUSE_READ_DONE_INT_CLR (BIT(0))
#define EFUSE_READ_DONE_INT_CLR_S 0

#define EFUSE_DAC_CONF_REG (REG_EFUSE_BASE + 0x1bc)
#define EFUSE_DAC_CLK_PAD_SEL (BIT(8))
#define EFUSE_DAC_CLK_PAD_SEL_S 8
#define EFUSE_DAC_CLK_DIV 0x000000FF
#define EFUSE_DAC_CLK_DIV_S 0

#define EFUSE_RD_TIM_CONF_REG (REG_EFUSE_BASE + 0x1c0)
#define EFUSE_READ_INIT_NUM 0x000000FF
#define EFUSE_READ_INIT_NUM_S 24
#define EFUSE_TSUR_A 0x000000FF
#define EFUSE_TSUR_A_S 16
#define EFUSE_TRD 0x000000FF
#define EFUSE_TRD_S 8
#define EFUSE_THR_A 0x000000FF
#define EFUSE_THR_A_S 0

#define EFUSE_WR_TIM_CONF0_REG (REG_EFUSE_BASE + 0x1c4)
#define EFUSE_TPGM 0x0000FFFF
#define EFUSE_TPGM_S 16
#define EFUSE_TPGM_INACTIVE 0x000000FF
#define EFUSE_TPGM_INACTIVE_S 8
#define EFUSE_THP_A 0x000000FF
#define EFUSE_THP_A_S 0

#define EFUSE_WR_TIM_CONF1_REG (REG_EFUSE_BASE + 0x1c8)
#define EFUSE_PWR_ON_NUM 0x0000FFFF
#define EFUSE_PWR_ON_NUM_S 8
#define EFUSE_TSUP_A 0x000000FF
#define EFUSE_TSUP_A_S 0

#define EFUSE_DATE_REG (REG_EFUSE_BASE + 0x1FC)
#define EFUSE_DATE 0xFFFFFFFF
#define EFUSE_DATE_S 0
#define EFUSE_DATE_VERSION 0x18112000
