 
#ifndef EXTMEM_H_INCLUDED
#define EXTMEM_H_INCLUDED

#define EXTMEM_PRO_DCACHE_CTRL_REG (REG_EXTMEM_BASE + 0x000)
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE (BIT(23))
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE_S 23
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA (BIT(22))
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA_S 22
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE (BIT(21))
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE_S 21
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA (BIT(20))
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA_S 20
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE (BIT(19))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE_S 19
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA (BIT(18))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA_S 18
#define EXTMEM_PRO_DCACHE_LOCK1_EN (BIT(15))
#define EXTMEM_PRO_DCACHE_LOCK1_EN_S 15
#define EXTMEM_PRO_DCACHE_LOCK0_EN (BIT(14))
#define EXTMEM_PRO_DCACHE_LOCK0_EN_S 14
#define EXTMEM_PRO_DCACHE_CLEAN_DONE (BIT(13))
#define EXTMEM_PRO_DCACHE_CLEAN_DONE_S 13
#define EXTMEM_PRO_DCACHE_CLEAN_ENA (BIT(12))
#define EXTMEM_PRO_DCACHE_CLEAN_ENA_S 12
#define EXTMEM_PRO_DCACHE_FLUSH_DONE (BIT(11))
#define EXTMEM_PRO_DCACHE_FLUSH_DONE_S 11
#define EXTMEM_PRO_DCACHE_FLUSH_ENA (BIT(10))
#define EXTMEM_PRO_DCACHE_FLUSH_ENA_S 10
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE (BIT(9))
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE_S 9
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA (BIT(8))
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA_S 8
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE 0x00000003
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE_S 3
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE (BIT(2))
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE_S 2
#define EXTMEM_PRO_DCACHE_MODE (BIT(1))
#define EXTMEM_PRO_DCACHE_MODE_S 1
#define EXTMEM_PRO_DCACHE_ENABLE (BIT(0))
#define EXTMEM_PRO_DCACHE_ENABLE_S 0

#define EXTMEM_PRO_DCACHE_CTRL1_REG (REG_EXTMEM_BASE + 0x004)
#define EXTMEM_PRO_DCACHE_MASK_BUS3 (BIT(3))
#define EXTMEM_PRO_DCACHE_MASK_BUS3_S 3
#define EXTMEM_PRO_DCACHE_MASK_BUS2 (BIT(2))
#define EXTMEM_PRO_DCACHE_MASK_BUS2_S 2
#define EXTMEM_PRO_DCACHE_MASK_BUS1 (BIT(1))
#define EXTMEM_PRO_DCACHE_MASK_BUS1_S 1
#define EXTMEM_PRO_DCACHE_MASK_BUS0 (BIT(0))
#define EXTMEM_PRO_DCACHE_MASK_BUS0_S 0

#define EXTMEM_PRO_DCACHE_TAG_POWER_CTRL_REG (REG_EXTMEM_BASE + 0x008)
#define EXTMEM_PRO_DCACHE_TAG_MEM_PD (BIT(1))
#define EXTMEM_PRO_DCACHE_TAG_MEM_PD_S 1
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON (BIT(0))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON_S 0

#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_REG (REG_EXTMEM_BASE + 0x00C)
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_S 0

#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_REG (REG_EXTMEM_BASE + 0x010)
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE 0x0000FFFF
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_S 0

#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_REG (REG_EXTMEM_BASE + 0x014)
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_S 0

#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_REG (REG_EXTMEM_BASE + 0x018)
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE 0x0000FFFF
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_S 0

#define EXTMEM_PRO_DCACHE_MEM_SYNC0_REG (REG_EXTMEM_BASE + 0x01C)
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_S 0

#define EXTMEM_PRO_DCACHE_MEM_SYNC1_REG (REG_EXTMEM_BASE + 0x020)
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE 0x007FFFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_S 0

#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_REG (REG_EXTMEM_BASE + 0x024)
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_S 0

#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_REG (REG_EXTMEM_BASE + 0x028)
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER (BIT(16))
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER_S 16
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE 0x0000FFFF
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_S 0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_CFG_REG (REG_EXTMEM_BASE + 0x02C)
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE 0x0000FFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_S 6
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST 0x00000003
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_S 4
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER (BIT(3))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER_S 3
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP 0x00000003
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_S 1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE (BIT(0))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE_S 0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION0_ADDR_REG (REG_EXTMEM_BASE + 0x030)
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_S 0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION0_SIZE_REG (REG_EXTMEM_BASE + 0x034)
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE 0x00FFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_S 0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION1_ADDR_REG (REG_EXTMEM_BASE + 0x038)
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_S 0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION1_SIZE_REG (REG_EXTMEM_BASE + 0x03C)
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE 0x00FFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_S 0

#define EXTMEM_PRO_ICACHE_CTRL_REG (REG_EXTMEM_BASE + 0x040)
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE (BIT(23))
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE_S 23
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA (BIT(22))
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA_S 22
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE (BIT(21))
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE_S 21
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA (BIT(20))
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA_S 20
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE (BIT(19))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE_S 19
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA (BIT(18))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA_S 18
#define EXTMEM_PRO_ICACHE_LOCK1_EN (BIT(15))
#define EXTMEM_PRO_ICACHE_LOCK1_EN_S 15
#define EXTMEM_PRO_ICACHE_LOCK0_EN (BIT(14))
#define EXTMEM_PRO_ICACHE_LOCK0_EN_S 14
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE (BIT(9))
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE_S 9
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA (BIT(8))
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA_S 8
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE 0x00000003
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE_S 3
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE (BIT(2))
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE_S 2
#define EXTMEM_PRO_ICACHE_MODE (BIT(1))
#define EXTMEM_PRO_ICACHE_MODE_S 1
#define EXTMEM_PRO_ICACHE_ENABLE (BIT(0))
#define EXTMEM_PRO_ICACHE_ENABLE_S 0

#define EXTMEM_PRO_ICACHE_CTRL1_REG (REG_EXTMEM_BASE + 0x044)
#define EXTMEM_PRO_ICACHE_MASK_BUS3 (BIT(3))
#define EXTMEM_PRO_ICACHE_MASK_BUS3_S 3
#define EXTMEM_PRO_ICACHE_MASK_BUS2 (BIT(2))
#define EXTMEM_PRO_ICACHE_MASK_BUS2_S 2
#define EXTMEM_PRO_ICACHE_MASK_BUS1 (BIT(1))
#define EXTMEM_PRO_ICACHE_MASK_BUS1_S 1
#define EXTMEM_PRO_ICACHE_MASK_BUS0 (BIT(0))
#define EXTMEM_PRO_ICACHE_MASK_BUS0_S 0

#define EXTMEM_PRO_ICACHE_TAG_POWER_CTRL_REG (REG_EXTMEM_BASE + 0x048)
#define EXTMEM_PRO_ICACHE_TAG_MEM_PD (BIT(1))
#define EXTMEM_PRO_ICACHE_TAG_MEM_PD_S 1
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON (BIT(0))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON_S 0

#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_REG (REG_EXTMEM_BASE + 0x04C)
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_S 0

#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_REG (REG_EXTMEM_BASE + 0x050)
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE 0x0000FFFF
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_S 0

#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_REG (REG_EXTMEM_BASE + 0x054)
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_S 0

#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_REG (REG_EXTMEM_BASE + 0x058)
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE 0x0000FFFF
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_S 0

#define EXTMEM_PRO_ICACHE_MEM_SYNC0_REG (REG_EXTMEM_BASE + 0x05C)
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_S 0

#define EXTMEM_PRO_ICACHE_MEM_SYNC1_REG (REG_EXTMEM_BASE + 0x060)
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE 0x007FFFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_S 0

#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_REG (REG_EXTMEM_BASE + 0x064)
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_S 0

#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_REG (REG_EXTMEM_BASE + 0x068)
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER (BIT(16))
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER_S 16
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE 0x0000FFFF
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_S 0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_CFG_REG (REG_EXTMEM_BASE + 0x06C)
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE 0x0000FFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_S 6
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST 0x00000003
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_S 4
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER (BIT(3))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER_S 3
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP 0x00000003
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_S 1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE (BIT(0))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE_S 0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION0_ADDR_REG (REG_EXTMEM_BASE + 0x070)
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_S 0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION0_SIZE_REG (REG_EXTMEM_BASE + 0x074)
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE 0x00FFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_S 0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION1_ADDR_REG (REG_EXTMEM_BASE + 0x078)
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_S 0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION1_SIZE_REG (REG_EXTMEM_BASE + 0x07C)
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE 0x00FFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_S 0

#define EXTMEM_IC_PRELOAD_CNT_REG (REG_EXTMEM_BASE + 0x080)
#define EXTMEM_IC_PRELOAD_CNT 0x0000FFFF
#define EXTMEM_IC_PRELOAD_CNT_S 0

#define EXTMEM_IC_PRELOAD_EVICT_CNT_REG (REG_EXTMEM_BASE + 0x084)
#define EXTMEM_IC_PRELOAD_EVICT_CNT 0x0000FFFF
#define EXTMEM_IC_PRELOAD_EVICT_CNT_S 0

#define EXTMEM_IC_PRELOAD_MISS_CNT_REG (REG_EXTMEM_BASE + 0x088)
#define EXTMEM_IC_PRELOAD_MISS_CNT 0x0000FFFF
#define EXTMEM_IC_PRELOAD_MISS_CNT_S 0

#define EXTMEM_IBUS3_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x08C)
#define EXTMEM_IBUS3_ABANDON_CNT 0x0000FFFF
#define EXTMEM_IBUS3_ABANDON_CNT_S 0

#define EXTMEM_IBUS2_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x090)
#define EXTMEM_IBUS2_ABANDON_CNT 0x0000FFFF
#define EXTMEM_IBUS2_ABANDON_CNT_S 0

#define EXTMEM_IBUS1_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x094)
#define EXTMEM_IBUS1_ABANDON_CNT 0x0000FFFF
#define EXTMEM_IBUS1_ABANDON_CNT_S 0

#define EXTMEM_IBUS0_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x098)
#define EXTMEM_IBUS0_ABANDON_CNT 0x0000FFFF
#define EXTMEM_IBUS0_ABANDON_CNT_S 0

#define EXTMEM_IBUS3_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x09C)
#define EXTMEM_IBUS3_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS3_ACS_MISS_CNT_S 0

#define EXTMEM_IBUS2_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0A0)
#define EXTMEM_IBUS2_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_MISS_CNT_S 0

#define EXTMEM_IBUS1_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0A4)
#define EXTMEM_IBUS1_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_MISS_CNT_S 0

#define EXTMEM_IBUS0_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0A8)
#define EXTMEM_IBUS0_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_MISS_CNT_S 0

#define EXTMEM_IBUS3_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0AC)
#define EXTMEM_IBUS3_ACS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS3_ACS_CNT_S 0

#define EXTMEM_IBUS2_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0B0)
#define EXTMEM_IBUS2_ACS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_CNT_S 0

#define EXTMEM_IBUS1_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0B4)
#define EXTMEM_IBUS1_ACS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_CNT_S 0

#define EXTMEM_IBUS0_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0B8)
#define EXTMEM_IBUS0_ACS_CNT 0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_CNT_S 0

#define EXTMEM_DC_PRELOAD_CNT_REG (REG_EXTMEM_BASE + 0x0BC)
#define EXTMEM_DC_PRELOAD_CNT 0x0000FFFF
#define EXTMEM_DC_PRELOAD_CNT_S 0

#define EXTMEM_DC_PRELOAD_EVICT_CNT_REG (REG_EXTMEM_BASE + 0x0C0)
#define EXTMEM_DC_PRELOAD_EVICT_CNT 0x0000FFFF
#define EXTMEM_DC_PRELOAD_EVICT_CNT_S 0

#define EXTMEM_DC_PRELOAD_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0C4)
#define EXTMEM_DC_PRELOAD_MISS_CNT 0x0000FFFF
#define EXTMEM_DC_PRELOAD_MISS_CNT_S 0

#define EXTMEM_DBUS3_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x0C8)
#define EXTMEM_DBUS3_ABANDON_CNT 0x0000FFFF
#define EXTMEM_DBUS3_ABANDON_CNT_S 0

#define EXTMEM_DBUS2_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x0CC)
#define EXTMEM_DBUS2_ABANDON_CNT 0x0000FFFF
#define EXTMEM_DBUS2_ABANDON_CNT_S 0

#define EXTMEM_DBUS1_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x0D0)
#define EXTMEM_DBUS1_ABANDON_CNT 0x0000FFFF
#define EXTMEM_DBUS1_ABANDON_CNT_S 0

#define EXTMEM_DBUS0_ABANDON_CNT_REG (REG_EXTMEM_BASE + 0x0D4)
#define EXTMEM_DBUS0_ABANDON_CNT 0x0000FFFF
#define EXTMEM_DBUS0_ABANDON_CNT_S 0

#define EXTMEM_DBUS3_ACS_WB_CNT_REG (REG_EXTMEM_BASE + 0x0D8)
#define EXTMEM_DBUS3_ACS_WB_CNT 0x000FFFFF
#define EXTMEM_DBUS3_ACS_WB_CNT_S 0

#define EXTMEM_DBUS2_ACS_WB_CNT_REG (REG_EXTMEM_BASE + 0x0DC)
#define EXTMEM_DBUS2_ACS_WB_CNT 0x000FFFFF
#define EXTMEM_DBUS2_ACS_WB_CNT_S 0

#define EXTMEM_DBUS1_ACS_WB_CNT_REG (REG_EXTMEM_BASE + 0x0E0)
#define EXTMEM_DBUS1_ACS_WB_CNT 0x000FFFFF
#define EXTMEM_DBUS1_ACS_WB_CNT_S 0

#define EXTMEM_DBUS0_ACS_WB_CNT_REG (REG_EXTMEM_BASE + 0x0E4)
#define EXTMEM_DBUS0_ACS_WB_CNT 0x000FFFFF
#define EXTMEM_DBUS0_ACS_WB_CNT_S 0

#define EXTMEM_DBUS3_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0E8)
#define EXTMEM_DBUS3_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS3_ACS_MISS_CNT_S 0

#define EXTMEM_DBUS2_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0EC)
#define EXTMEM_DBUS2_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_MISS_CNT_S 0

#define EXTMEM_DBUS1_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0F0)
#define EXTMEM_DBUS1_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_MISS_CNT_S 0

#define EXTMEM_DBUS0_ACS_MISS_CNT_REG (REG_EXTMEM_BASE + 0x0F4)
#define EXTMEM_DBUS0_ACS_MISS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_MISS_CNT_S 0

#define EXTMEM_DBUS3_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0F8)
#define EXTMEM_DBUS3_ACS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS3_ACS_CNT_S 0

#define EXTMEM_DBUS2_ACS_CNT_REG (REG_EXTMEM_BASE + 0x0FC)
#define EXTMEM_DBUS2_ACS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_CNT_S 0

#define EXTMEM_DBUS1_ACS_CNT_REG (REG_EXTMEM_BASE + 0x100)
#define EXTMEM_DBUS1_ACS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_CNT_S 0

#define EXTMEM_DBUS0_ACS_CNT_REG (REG_EXTMEM_BASE + 0x104)
#define EXTMEM_DBUS0_ACS_CNT 0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_CNT_S 0

#define EXTMEM_CACHE_DBG_INT_ENA_REG (REG_EXTMEM_BASE + 0x108)
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA (BIT(13))
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_S 13
#define EXTMEM_DCACHE_REJECT_INT_ENA (BIT(12))
#define EXTMEM_DCACHE_REJECT_INT_ENA_S 12
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA (BIT(11))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA_S 11
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA (BIT(10))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA_S 10
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA (BIT(9))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA_S 9
#define EXTMEM_DBUS_CNT_OVF_INT_ENA (BIT(8))
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_S 8
#define EXTMEM_DBUS_ACS_MSK_IC_INT_ENA (BIT(7))
#define EXTMEM_DBUS_ACS_MSK_IC_INT_ENA_S 7
#define EXTMEM_ICACHE_REJECT_INT_ENA (BIT(6))
#define EXTMEM_ICACHE_REJECT_INT_ENA_S 6
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA (BIT(5))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA_S 5
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA (BIT(4))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA_S 4
#define EXTMEM_IBUS_CNT_OVF_INT_ENA (BIT(3))
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_S 3
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA (BIT(2))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA_S 2
#define EXTMEM_CACHE_DBG_EN (BIT(0))
#define EXTMEM_CACHE_DBG_EN_S 0

#define EXTMEM_CACHE_DBG_INT_CLR_REG (REG_EXTMEM_BASE + 0x10C)
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR (BIT(11))
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_S 11
#define EXTMEM_DCACHE_REJECT_INT_CLR (BIT(10))
#define EXTMEM_DCACHE_REJECT_INT_CLR_S 10
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR (BIT(9))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR_S 9
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR (BIT(8))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR_S 8
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR (BIT(7))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR_S 7
#define EXTMEM_DBUS_CNT_OVF_INT_CLR (BIT(6))
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_S 6
#define EXTMEM_DBUS_ACS_MSK_IC_INT_CLR (BIT(5))
#define EXTMEM_DBUS_ACS_MSK_IC_INT_CLR_S 5
#define EXTMEM_ICACHE_REJECT_INT_CLR (BIT(4))
#define EXTMEM_ICACHE_REJECT_INT_CLR_S 4
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR (BIT(3))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR_S 3
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR (BIT(2))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR_S 2
#define EXTMEM_IBUS_CNT_OVF_INT_CLR (BIT(1))
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_S 1
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR (BIT(0))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR_S 0

#define EXTMEM_CACHE_DBG_STATUS0_REG (REG_EXTMEM_BASE + 0x110)
#define EXTMEM_ICACHE_REJECT_ST (BIT(21))
#define EXTMEM_ICACHE_REJECT_ST_S 21
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST (BIT(20))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST_S 20
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST (BIT(19))
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST_S 19
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST (BIT(18))
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST_S 18
#define EXTMEM_IC_PRELOAD_EVICT_CNT_OVF_ST (BIT(17))
#define EXTMEM_IC_PRELOAD_EVICT_CNT_OVF_ST_S 17
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST (BIT(16))
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST_S 16
#define EXTMEM_IBUS3_ABANDON_CNT_OVF_ST (BIT(15))
#define EXTMEM_IBUS3_ABANDON_CNT_OVF_ST_S 15
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST (BIT(14))
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST_S 14
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST (BIT(13))
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST_S 13
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST (BIT(12))
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST_S 12
#define EXTMEM_IBUS3_ACS_MISS_CNT_OVF_ST (BIT(11))
#define EXTMEM_IBUS3_ACS_MISS_CNT_OVF_ST_S 11
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST (BIT(10))
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST_S 10
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST (BIT(9))
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST_S 9
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST (BIT(8))
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST_S 8
#define EXTMEM_IBUS3_ACS_CNT_OVF_ST (BIT(7))
#define EXTMEM_IBUS3_ACS_CNT_OVF_ST_S 7
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST (BIT(6))
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST_S 6
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST (BIT(5))
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST_S 5
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST (BIT(4))
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST_S 4
#define EXTMEM_IBUS3_ACS_MSK_ICACHE_ST (BIT(3))
#define EXTMEM_IBUS3_ACS_MSK_ICACHE_ST_S 3
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST (BIT(2))
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST_S 2
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST (BIT(1))
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST_S 1
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST (BIT(0))
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST_S 0

#define EXTMEM_CACHE_DBG_STATUS1_REG (REG_EXTMEM_BASE + 0x114)
#define EXTMEM_MMU_ENTRY_FAULT_ST (BIT(27))
#define EXTMEM_MMU_ENTRY_FAULT_ST_S 27
#define EXTMEM_DCACHE_REJECT_ST (BIT(26))
#define EXTMEM_DCACHE_REJECT_ST_S 26
#define EXTMEM_DCACHE_WRITE_FLASH_ST (BIT(25))
#define EXTMEM_DCACHE_WRITE_FLASH_ST_S 25
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST (BIT(24))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST_S 24
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST (BIT(23))
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST_S 23
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST (BIT(22))
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST_S 22
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST (BIT(21))
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST_S 21
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST (BIT(20))
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST_S 20
#define EXTMEM_DBUS3_ABANDON_CNT_OVF_ST (BIT(19))
#define EXTMEM_DBUS3_ABANDON_CNT_OVF_ST_S 19
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST (BIT(18))
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST_S 18
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST (BIT(17))
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST_S 17
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST (BIT(16))
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST_S 16
#define EXTMEM_DBUS3_ACS_WB_CNT_OVF_ST (BIT(15))
#define EXTMEM_DBUS3_ACS_WB_CNT_OVF_ST_S 15
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST (BIT(14))
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST_S 14
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST (BIT(13))
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST_S 13
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST (BIT(12))
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST_S 12
#define EXTMEM_DBUS3_ACS_MISS_CNT_OVF_ST (BIT(11))
#define EXTMEM_DBUS3_ACS_MISS_CNT_OVF_ST_S 11
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST (BIT(10))
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST_S 10
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST (BIT(9))
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST_S 9
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST (BIT(8))
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST_S 8
#define EXTMEM_DBUS3_ACS_CNT_OVF_ST (BIT(7))
#define EXTMEM_DBUS3_ACS_CNT_OVF_ST_S 7
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST (BIT(6))
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST_S 6
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST (BIT(5))
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST_S 5
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST (BIT(4))
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST_S 4
#define EXTMEM_DBUS3_ACS_MSK_DCACHE_ST (BIT(3))
#define EXTMEM_DBUS3_ACS_MSK_DCACHE_ST_S 3
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST (BIT(2))
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST_S 2
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST (BIT(1))
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST_S 1
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST (BIT(0))
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST_S 0

#define EXTMEM_PRO_CACHE_ACS_CNT_CLR_REG (REG_EXTMEM_BASE + 0x118)
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR (BIT(1))
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR_S 1
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR (BIT(0))
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR_S 0

#define EXTMEM_PRO_DCACHE_REJECT_ST_REG (REG_EXTMEM_BASE + 0x11C)
#define EXTMEM_PRO_DCACHE_CPU_ATTR 0x00000007
#define EXTMEM_PRO_DCACHE_CPU_ATTR_S 3
#define EXTMEM_PRO_DCACHE_TAG_ATTR 0x00000007
#define EXTMEM_PRO_DCACHE_TAG_ATTR_S 0

#define EXTMEM_PRO_DCACHE_REJECT_VADDR_REG (REG_EXTMEM_BASE + 0x120)
#define EXTMEM_PRO_DCACHE_CPU_VADDR 0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_CPU_VADDR_S 0

#define EXTMEM_PRO_ICACHE_REJECT_ST_REG (REG_EXTMEM_BASE + 0x124)
#define EXTMEM_PRO_ICACHE_CPU_ATTR 0x00000007
#define EXTMEM_PRO_ICACHE_CPU_ATTR_S 3
#define EXTMEM_PRO_ICACHE_TAG_ATTR 0x00000007
#define EXTMEM_PRO_ICACHE_TAG_ATTR_S 0

#define EXTMEM_PRO_ICACHE_REJECT_VADDR_REG (REG_EXTMEM_BASE + 0x128)
#define EXTMEM_PRO_ICACHE_CPU_VADDR 0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_CPU_VADDR_S 0

#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_REG (REG_EXTMEM_BASE + 0x12C)
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT 0x0001FFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_S 0

#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_REG (REG_EXTMEM_BASE + 0x130)
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR 0xFFFFFFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_S 0

#define EXTMEM_PRO_CACHE_WRAP_AROUND_CTRL_REG (REG_EXTMEM_BASE + 0x134)
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND (BIT(1))
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND_S 1
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND (BIT(0))
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND_S 0

#define EXTMEM_PRO_CACHE_MMU_POWER_CTRL_REG (REG_EXTMEM_BASE + 0x138)
#define EXTMEM_PRO_CACHE_MMU_MEM_PD (BIT(1))
#define EXTMEM_PRO_CACHE_MMU_MEM_PD_S 1
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON (BIT(0))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON_S 0

#define EXTMEM_PRO_CACHE_STATE_REG (REG_EXTMEM_BASE + 0x13C)
#define EXTMEM_PRO_DCACHE_STATE 0x00000FFF
#define EXTMEM_PRO_DCACHE_STATE_S 12
#define EXTMEM_PRO_ICACHE_STATE 0x00000FFF
#define EXTMEM_PRO_ICACHE_STATE_S 0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_RECORD_DISABLE_REG (REG_EXTMEM_BASE + 0x140)
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT (BIT(1))
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_S 1
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT (BIT(0))
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_S 0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_CLK_FORCE_ON_REG (REG_EXTMEM_BASE + 0x144)
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT (BIT(2))
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT_S 2
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT (BIT(1))
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT_S 1
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT (BIT(0))
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT_S 0

#define EXTMEM_CACHE_BRIDGE_ARBITER_CTRL_REG (REG_EXTMEM_BASE + 0x148)
#define EXTMEM_ALLOC_WB_HOLD_ARBITER (BIT(0))
#define EXTMEM_ALLOC_WB_HOLD_ARBITER_S 0

#define EXTMEM_CACHE_PRELOAD_INT_CTRL_REG (REG_EXTMEM_BASE + 0x14C)
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR (BIT(5))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR_S 5
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA (BIT(4))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA_S 4
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST (BIT(3))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST_S 3
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR (BIT(2))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR_S 2
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA (BIT(1))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA_S 1
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST (BIT(0))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST_S 0

#define EXTMEM_CACHE_CONF_MISC_REG (REG_EXTMEM_BASE + 0x150)
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT (BIT(1))
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_S 1
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT (BIT(0))
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_S 0

#define EXTMEM_CLOCK_GATE_REG (REG_EXTMEM_BASE + 0x154)
#define EXTMEM_CLK_EN (BIT(0))
#define EXTMEM_CLK_EN_S 0

#define EXTMEM_PRO_EXTMEM_REG_DATE_REG (REG_EXTMEM_BASE + 0x3FC)
#define EXTMEM_PRO_EXTMEM_DATE 0x0FFFFFFF
#define EXTMEM_PRO_EXTMEM_DATE_S 0
#define EXTMEM_PRO_EXTMEM_DATE_VERSION 0x1812130
#endif // EXTMEM_H_INCLUDED
