
#define FE_TX_GAIN_CTRL_REG (REG_FE_BASE + 0x0000)
#define FE_DAC_GAIN2_EN (BIT(26))
#define FE_DAC_GAIN2_EN_S 26
#define FE_TXGAIN_ADDR_BASE 0x000000FF
#define FE_TXGAIN_ADDR_BASE_S 18
#define FE_FORCE_TXGAIN_ADDR 0x000000FF
#define FE_FORCE_TXGAIN_ADDR_S 10
#define FE_FORCE_DAC_GAIN 0x000000FF
#define FE_FORCE_DAC_GAIN_S 2
#define FE_FORCE_TXGAIN_ADDR_EN (BIT(1))
#define FE_FORCE_TXGAIN_ADDR_EN_S 1
#define FE_FORCE_DAC_GAIN_EN (BIT(0))
#define FE_FORCE_DAC_GAIN_EN_S 0

#define FE_TX_GAIN_CTRL_1_REG (REG_FE_BASE + 0x0004)
#define FE_TX_GAIN_CTRL1 0xFFFFFFFF
#define FE_TX_GAIN_CTRL1_S 0

#define FE_TX_GAIN_CTRL_2_REG (REG_FE_BASE + 0x0008)
#define FE_TX_GAIN_CTRL2 0xFFFFFFFF
#define FE_TX_GAIN_CTRL2_S 0

#define FE_TX_GAIN_CTRL_3_REG (REG_FE_BASE + 0x000c)
#define FE_TX_GAIN_CTRL3 0xFFFFFFFF
#define FE_TX_GAIN_CTRL3_S 0

#define FE_TX_GAIN_CTRL_4_REG (REG_FE_BASE + 0x0010)
#define FE_TX_GAIN_CTRL4 0xFFFFFFFF
#define FE_TX_GAIN_CTRL4_S 0

#define FE_PUBS_CFG0_REG (REG_FE_BASE + 0x0030)
#define FE_RXOFF_END 0x000000FF
#define FE_RXOFF_END_S 24
#define FE_RXOFF_START 0x000000FF
#define FE_RXOFF_START_S 16
#define FE_RXON_END 0x000000FF
#define FE_RXON_END_S 8
#define FE_RXON_START 0x000000FF
#define FE_RXON_START_S 0

#define FE_PUBS_CFG1_REG (REG_FE_BASE + 0x0034)
#define FE_TXOFF_END 0x000000FF
#define FE_TXOFF_END_S 24
#define FE_TXOFF_START 0x000000FF
#define FE_TXOFF_START_S 16
#define FE_TXON_END 0x000000FF
#define FE_TXON_END_S 8
#define FE_TXON_START 0x000000FF
#define FE_TXON_START_S 0

#define FE_PUBS_CFG2_REG (REG_FE_BASE + 0x0038)
#define FE_PAOFF_END 0x000000FF
#define FE_PAOFF_END_S 24
#define FE_PAOFF_START 0x000000FF
#define FE_PAOFF_START_S 16
#define FE_PAON_END 0x000000FF
#define FE_PAON_END_S 8
#define FE_PAON_START 0x000000FF
#define FE_PAON_START_S 0

#define FE_PUBS_CFG3_REG (REG_FE_BASE + 0x003c)
#define FE_RXOFF_BT_END 0x000000FF
#define FE_RXOFF_BT_END_S 24
#define FE_RXOFF_BT_START 0x000000FF
#define FE_RXOFF_BT_START_S 16
#define FE_RXON_BT_END 0x000000FF
#define FE_RXON_BT_END_S 8
#define FE_RXON_BT_START 0x000000FF
#define FE_RXON_BT_START_S 0

#define FE_PUBS_CFG4_REG (REG_FE_BASE + 0x0040)
#define FE_TXOFF_BT_END 0x000000FF
#define FE_TXOFF_BT_END_S 24
#define FE_TXOFF_BT_START 0x000000FF
#define FE_TXOFF_BT_START_S 16
#define FE_TXON_BT_END 0x000000FF
#define FE_TXON_BT_END_S 8
#define FE_TXON_BT_START 0x000000FF
#define FE_TXON_BT_START_S 0

#define FE_PUBS_CFG5_REG (REG_FE_BASE + 0x0044)
#define FE_PAOFF_BT_END 0x000000FF
#define FE_PAOFF_BT_END_S 24
#define FE_PAOFF_BT_START 0x000000FF
#define FE_PAOFF_BT_START_S 16
#define FE_PAON_BT_END 0x000000FF
#define FE_PAON_BT_END_S 8
#define FE_PAON_BT_START 0x000000FF
#define FE_PAON_BT_START_S 0

#define FE_PUBS_CFG6_REG (REG_FE_BASE + 0x0048)
#define FE_PAOFF_DELAY 0x000000FF
#define FE_PAOFF_DELAY_S 24
#define FE_TXOFF_DELAY 0x000000FF
#define FE_TXOFF_DELAY_S 16
#define FE_PAON_DELAY 0x000000FF
#define FE_PAON_DELAY_S 8
#define FE_TXON_DELAY 0x000000FF
#define FE_TXON_DELAY_S 0

#define FE_PUBS_CFG7_REG (REG_FE_BASE + 0x004c)
#define FE_PAOFF_BT_DELAY 0x000000FF
#define FE_PAOFF_BT_DELAY_S 24
#define FE_TXOFF_BT_DELAY 0x000000FF
#define FE_TXOFF_BT_DELAY_S 16
#define FE_PAON_BT_DELAY 0x000000FF
#define FE_PAON_BT_DELAY_S 8
#define FE_TXON_BT_DELAY 0x000000FF
#define FE_TXON_BT_DELAY_S 0

#define FE_PUBS_CFG8_REG (REG_FE_BASE + 0x0050)
#define FE_BT_FBW_SEL 0x00000003
#define FE_BT_FBW_SEL_S 22
#define FE_WIFI_RXFBW_SEL 0x00000003
#define FE_WIFI_RXFBW_SEL_S 20
#define FE_WIFI_RXFBW_EN (BIT(19))
#define FE_WIFI_RXFBW_EN_S 19
#define FE_WIFI_TXFBW_SEL 0x00000003
#define FE_WIFI_TXFBW_SEL_S 17
#define FE_WIFI_TXFBW_EN (BIT(16))
#define FE_WIFI_TXFBW_EN_S 16
#define FE_RXON_BT_DELAY 0x000000FF
#define FE_RXON_BT_DELAY_S 8
#define FE_RXON_DELAY 0x000000FF
#define FE_RXON_DELAY_S 0

#define FE_IQ_EST_CTRL_01_REG (REG_FE_BASE + 0x0060)
#define FE_IQ_EST_SSEA_DONE (BIT(31))
#define FE_IQ_EST_SSEA_DONE_S 31
#define FE_IQ_EST_SSEA_OVERFLOWA (BIT(30))
#define FE_IQ_EST_SSEA_OVERFLOWA_S 30
#define FE_IQ_EST_SSEA_OVERFLOWM (BIT(29))
#define FE_IQ_EST_SSEA_OVERFLOWM_S 29
#define FE_IQ_EST_CTRL_1 0x1FFFFFFF
#define FE_IQ_EST_CTRL_1_S 0

#define FE_IQ_SSEA_CORR1_REG (REG_FE_BASE + 0x0064)
#define FE_IQ_EST_SSEA_CORR1 0xFFFFFFFF
#define FE_IQ_EST_SSEA_CORR1_S 0

#define FE_IQ_SSEA_CORR1_CONJ_REG (REG_FE_BASE + 0x0068)
#define FE_IQ_EST_SSEA_CORR1_CONJ 0xFFFFFFFF
#define FE_IQ_EST_SSEA_CORR1_CONJ_S 0

#define FE_IQ_SSEA_CORR2_REG (REG_FE_BASE + 0x006c)
#define FE_IQ_EST_SSEA_CORR2 0xFFFFFFFF
#define FE_IQ_EST_SSEA_CORR2_S 0

#define FE_IQ_SSEA_CORR2_CONJ_REG (REG_FE_BASE + 0x0070)
#define FE_IQ_EST_SSEA_CORR2_CONJ 0xFFFFFFFF
#define FE_IQ_EST_SSEA_CORR2_CONJ_S 0

#define FE_IQ_SSEA_DC_REG (REG_FE_BASE + 0x0074)
#define FE_IQ_EST_SSEA_DC 0xFFFFFFFF
#define FE_IQ_EST_SSEA_DC_S 0

#define FE_IQ_SSEA_POWER_REG (REG_FE_BASE + 0x0078)
#define FE_IQ_EST_SSEA_POWER 0xFFFFFFFF
#define FE_IQ_EST_SSEA_POWER_S 0

#define FE_IQ_EST_CTRL_00_REG (REG_FE_BASE + 0x007c)
#define FE_IQ_EST_CTRL_0 0x7FFFFFFF
#define FE_IQ_EST_CTRL_0_S 0

#define FE_IQ_RESULT1_REG (REG_FE_BASE + 0x0080)
#define FE_IQ_EST_MULT_II 0xFFFFFFFF
#define FE_IQ_EST_MULT_II_S 0

#define FE_IQ_RESULT2_REG (REG_FE_BASE + 0x0084)
#define FE_IQ_EST_MULT_IQ 0xFFFFFFFF
#define FE_IQ_EST_MULT_IQ_S 0

#define FE_IQ_RESULT3_REG (REG_FE_BASE + 0x0088)
#define FE_IQ_EST_MULT_QI 0xFFFFFFFF
#define FE_IQ_EST_MULT_QI_S 0

#define FE_IQ_RESULT4_REG (REG_FE_BASE + 0x008c)
#define FE_IQ_EST_MULT_QQ 0xFFFFFFFF
#define FE_IQ_EST_MULT_QQ_S 0

#define FE_GEN_CTRL_REG (REG_FE_BASE + 0x0090)
#define FE_IQ_EST_FORCE_PU (BIT(5))
#define FE_IQ_EST_FORCE_PU_S 5
#define FE_IQ_EST_FORCE_PD (BIT(4))
#define FE_IQ_EST_FORCE_PD_S 4
#define FE_FILT_ATT_1DB_EN (BIT(3))
#define FE_FILT_ATT_1DB_EN_S 3
#define FE_ADC_80M_DSP (BIT(2))
#define FE_ADC_80M_DSP_S 2
#define FE_DUMP_MODE 0x00000003
#define FE_DUMP_MODE_S 0

#define FE_PUBS_CTRL0_REG (REG_FE_BASE + 0x0094)
#define FE_PBUS_DATA_EXT_NUM 0x00000003
#define FE_PBUS_DATA_EXT_NUM_S 30
#define FE_PBUS_DATA_EXT (BIT(29))
#define FE_PBUS_DATA_EXT_S 29
#define FE_PBUS_EN_NODELAY (BIT(28))
#define FE_PBUS_EN_NODELAY_S 28
#define FE_RF_CFG_FORCE_PBUS_WE 0x000001FF
#define FE_RF_CFG_FORCE_PBUS_WE_S 19
#define FE_VGA_DG_BUF (BIT(18))
#define FE_VGA_DG_BUF_S 18
#define FE_HOST_INF_2CYC (BIT(17))
#define FE_HOST_INF_2CYC_S 17
#define FE_RF_CFG_FORCE_EN 0x00000003
#define FE_RF_CFG_FORCE_EN_S 15
#define FE_RF_CFG_FORCE_PBUS 0x000001FF
#define FE_RF_CFG_FORCE_PBUS_S 6
#define FE_RF_CFG_FORCE_BUS_SEL 0x0000000F
#define FE_RF_CFG_FORCE_BUS_SEL_S 2
#define FE_RF_CFG_FORCE_VALID (BIT(1))
#define FE_RF_CFG_FORCE_VALID_S 1
#define FE_RF_CFG_FORCE_MODE (BIT(0))
#define FE_RF_CFG_FORCE_MODE_S 0

#define FE_PUBS_CTRL1_REG (REG_FE_BASE + 0x0098)
#define FE_TICK_BT_TXON 0x00000003
#define FE_TICK_BT_TXON_S 6
#define FE_TICK_BT_RXON 0x00000003
#define FE_TICK_BT_RXON_S 4
#define FE_TICK_WIFI_TXON 0x00000003
#define FE_TICK_WIFI_TXON_S 2
#define FE_TICK_WIFI_RXON 0x00000003
#define FE_TICK_WIFI_RXON_S 0

#define FE_PUBS_CTRL2_REG (REG_FE_BASE + 0x009c)
#define FE_PWDET_BT_EN (BIT(31))
#define FE_PWDET_BT_EN_S 31
#define FE_PLL_STOP_USE_BT (BIT(30))
#define FE_PLL_STOP_USE_BT_S 30
#define FE_PLL_STOP_USE_WIFI (BIT(29))
#define FE_PLL_STOP_USE_WIFI_S 29
#define FE_PBUS_BT_PROT (BIT(28))
#define FE_PBUS_BT_PROT_S 28
#define FE_PBUS_FORCE_PROT (BIT(27))
#define FE_PBUS_FORCE_PROT_S 27
#define FE_PBUS_RX_PROT (BIT(26))
#define FE_PBUS_RX_PROT_S 26
#define FE_PBUS_TX_PROT (BIT(25))
#define FE_PBUS_TX_PROT_S 25
#define FE_TXRF2_PBUS_EN_MASK (BIT(24))
#define FE_TXRF2_PBUS_EN_MASK_S 24
#define FE_TXRF1_PBUS_EN_MASK 0x00000003
#define FE_TXRF1_PBUS_EN_MASK_S 22
#define FE_DCOQ_PBUS_EN_MASK 0x00000003
#define FE_DCOQ_PBUS_EN_MASK_S 20
#define FE_DCOI_PBUS_EN_MASK 0x00000003
#define FE_DCOI_PBUS_EN_MASK_S 18
#define FE_BB_PBUS_EN_MASK 0x00000003
#define FE_BB_PBUS_EN_MASK_S 16
#define FE_RFRX_PBUS_EN_MASK (BIT(15))
#define FE_RFRX_PBUS_EN_MASK_S 15
#define FE_SW_RXTX_INV (BIT(14))
#define FE_SW_RXTX_INV_S 14
#define FE_SW_WIFIBT_INV (BIT(13))
#define FE_SW_WIFIBT_INV_S 13
#define FE_GAIN_CHANGE_REQ_EN (BIT(12))
#define FE_GAIN_CHANGE_REQ_EN_S 12
#define FE_PA_OFF_BT_REQ_EN (BIT(11))
#define FE_PA_OFF_BT_REQ_EN_S 11
#define FE_PA_ON_BT_REQ_EN (BIT(10))
#define FE_PA_ON_BT_REQ_EN_S 10
#define FE_TX_OFF_BT_REQ_EN (BIT(9))
#define FE_TX_OFF_BT_REQ_EN_S 9
#define FE_TX_ON_BT_REQ_EN (BIT(8))
#define FE_TX_ON_BT_REQ_EN_S 8
#define FE_RX_OFF_BT_REQ_EN (BIT(7))
#define FE_RX_OFF_BT_REQ_EN_S 7
#define FE_RX_ON_BT_REQ_EN (BIT(6))
#define FE_RX_ON_BT_REQ_EN_S 6
#define FE_PA_OFF_REQ_EN (BIT(5))
#define FE_PA_OFF_REQ_EN_S 5
#define FE_PA_ON_REQ_EN (BIT(4))
#define FE_PA_ON_REQ_EN_S 4
#define FE_TX_OFF_REQ_EN (BIT(3))
#define FE_TX_OFF_REQ_EN_S 3
#define FE_TX_ON_REQ_EN (BIT(2))
#define FE_TX_ON_REQ_EN_S 2
#define FE_RX_OFF_REQ_EN (BIT(1))
#define FE_RX_OFF_REQ_EN_S 1
#define FE_RX_ON_REQ_EN (BIT(0))
#define FE_RX_ON_REQ_EN_S 0

#define FE_PUBS_CTRL3_REG (REG_FE_BASE + 0x00a0)
#define FE_RF_CFG_FORCE_BUSY (BIT(31))
#define FE_RF_CFG_FORCE_BUSY_S 31
#define FE_PBUS_CFG_FORCE_MODE (BIT(30))
#define FE_PBUS_CFG_FORCE_MODE_S 30
#define FE_TEST_FAIL_CLR (BIT(29))
#define FE_TEST_FAIL_CLR_S 29
#define FE_PBUS_RXON_BT_FORCE_EN (BIT(28))
#define FE_PBUS_RXON_BT_FORCE_EN_S 28
#define FE_PBUS_RXON_BT_FORCE (BIT(27))
#define FE_PBUS_RXON_BT_FORCE_S 27
#define FE_PBUS_RXON_FORCE_EN (BIT(26))
#define FE_PBUS_RXON_FORCE_EN_S 26
#define FE_PBUS_RXON_FORCE (BIT(25))
#define FE_PBUS_RXON_FORCE_S 25
#define FE_PBUS_EN_SWAP 0x00000007
#define FE_PBUS_EN_SWAP_S 22
#define FE_DACPWD_FORCE_EN (BIT(21))
#define FE_DACPWD_FORCE_EN_S 21
#define FE_DACPWD_FORCE (BIT(20))
#define FE_DACPWD_FORCE_S 20
#define FE_ADCPWD_FORCE_EN (BIT(19))
#define FE_ADCPWD_FORCE_EN_S 19
#define FE_ADCPWD_FORCE (BIT(18))
#define FE_ADCPWD_FORCE_S 18
#define FE_TXON_FORCE_EN (BIT(17))
#define FE_TXON_FORCE_EN_S 17
#define FE_TXON_FORCE (BIT(16))
#define FE_TXON_FORCE_S 16
#define FE_RXON_FORCE_EN (BIT(15))
#define FE_RXON_FORCE_EN_S 15
#define FE_RXON_FORCE (BIT(14))
#define FE_RXON_FORCE_S 14
#define FE_BT_MODE_ON_FORCE_EN (BIT(13))
#define FE_BT_MODE_ON_FORCE_EN_S 13
#define FE_BT_MODE_ON_FORCE (BIT(12))
#define FE_BT_MODE_ON_FORCE_S 12
#define FE_DAC_ON_FORCE_EN (BIT(11))
#define FE_DAC_ON_FORCE_EN_S 11
#define FE_DAC_ON_FORCE (BIT(10))
#define FE_DAC_ON_FORCE_S 10
#define FE_ADC_ON_FORCE_EN (BIT(9))
#define FE_ADC_ON_FORCE_EN_S 9
#define FE_ADC_ON_FORCE (BIT(8))
#define FE_ADC_ON_FORCE_S 8

#define FE_PUBS_RD0_REG (REG_FE_BASE + 0x00a4)
#define FE_R_BB_PBUS_2_BT_RX 0x000001FF
#define FE_R_BB_PBUS_2_BT_RX_S 18
#define FE_R_BB_PBUS_2_WIFI_RX 0x000001FF
#define FE_R_BB_PBUS_2_WIFI_RX_S 9
#define FE_R_BB_PBUS_2_BT_TX 0x000001FF
#define FE_R_BB_PBUS_2_BT_TX_S 0

#define FE_PUBS_RD1_REG (REG_FE_BASE + 0x00a8)
#define FE_R_BB_PBUS_2_WIFI_TX 0x000001FF
#define FE_R_BB_PBUS_2_WIFI_TX_S 18
#define FE_R_RFRX_PBUS_1 0x000001FF
#define FE_R_RFRX_PBUS_1_S 9
#define FE_R_BB_PBUS_1 0x000001FF
#define FE_R_BB_PBUS_1_S 0

#define FE_PUBS_RD2_REG (REG_FE_BASE + 0x00ac)
#define FE_R_BB_PBUS_2 0x000001FF
#define FE_R_BB_PBUS_2_S 18
#define FE_R_DCOI_PBUS_1 0x000001FF
#define FE_R_DCOI_PBUS_1_S 9
#define FE_R_DCOI_PBUS_2 0x000001FF
#define FE_R_DCOI_PBUS_2_S 0

#define FE_PUBS_RD3_REG (REG_FE_BASE + 0x00b0)
#define FE_CFG_REQ_FAIL_H 0x0000000F
#define FE_CFG_REQ_FAIL_H_S 27
#define FE_R_DCOQ_PBUS_1 0x000001FF
#define FE_R_DCOQ_PBUS_1_S 18
#define FE_R_DCOQ_PBUS_2 0x000001FF
#define FE_R_DCOQ_PBUS_2_S 9
#define FE_R_TXRF1_PBUS_1 0x000001FF
#define FE_R_TXRF1_PBUS_1_S 0

#define FE_PUBS_RD4_REG (REG_FE_BASE + 0x00b4)
#define FE_R_TXRF1_PBUS_2 0x000001FF
#define FE_R_TXRF1_PBUS_2_S 9
#define FE_R_TXRF2_PBUS_1 0x000001FF
#define FE_R_TXRF2_PBUS_1_S 0

#define FE_TX_TEST_CTRL_0_REG (REG_FE_BASE + 0x00b8)
#define FE_TX_TEST_CTRL0 0xFFFFFFFF
#define FE_TX_TEST_CTRL0_S 0

#define FE_TX_TEST_CTRL_1_REG (REG_FE_BASE + 0x00bc)
#define FE_TX_TEST_CTRL1 0xFFFFFFFF
#define FE_TX_TEST_CTRL1_S 0

#define FE_TX_TEST_CTRL_2_REG (REG_FE_BASE + 0x00c0)
#define FE_TX_TEST_CTRL2 0xFFFFFFFF
#define FE_TX_TEST_CTRL2_S 0

#define FE_TX_TEST_CTRL_3_REG (REG_FE_BASE + 0x00c4)
#define FE_TX_TEST_CTRL3 0xFFFFFFFF
#define FE_TX_TEST_CTRL3_S 0

#define FE_PUBS_RD5_REG (REG_FE_BASE + 0x00c8)
#define FE_TEST_FAIL (BIT(22))
#define FE_TEST_FAIL_S 22
#define FE_CFG_REQ_D1 0x00001FFF
#define FE_CFG_REQ_D1_S 9
#define FE_CFG_REQ_FAIL_L 0x000001FF
#define FE_CFG_REQ_FAIL_L_S 0

#define FE_IQ_RESULT_2_1_REG (REG_FE_BASE + 0x00cc)
#define FE_IQ_EST_MULT2_II 0xFFFFFFFF
#define FE_IQ_EST_MULT2_II_S 0

#define FE_IQ_RESULT_2_2_REG (REG_FE_BASE + 0x00d0)
#define FE_IQ_EST_MULT2_IQ 0xFFFFFFFF
#define FE_IQ_EST_MULT2_IQ_S 0

#define FE_IQ_RESULT_2_3_REG (REG_FE_BASE + 0x00d4)
#define FE_IQ_EST_MULT2_QI 0xFFFFFFFF
#define FE_IQ_EST_MULT2_QI_S 0

#define FE_IQ_RESULT_2_4_REG (REG_FE_BASE + 0x00d8)
#define FE_IQ_EST_MULT2_QQ 0xFFFFFFFF
#define FE_IQ_EST_MULT2_QQ_S 0

#define FE_IQ_RESULT_DC_I_REG (REG_FE_BASE + 0x00dc)
#define FE_IQ_EST_MULT_DC_I 0xFFFFFFFF
#define FE_IQ_EST_MULT_DC_I_S 0

#define FE_IQ_RESULT_DC_Q_REG (REG_FE_BASE + 0x00e0)
#define FE_IQ_EST_MULT_DC_Q 0xFFFFFFFF
#define FE_IQ_EST_MULT_DC_Q_S 0

#define FE_IQ_RESULT_PWR_REG (REG_FE_BASE + 0x00e4)
#define FE_IQ_EST_MULT_PWR 0xFFFFFFFF
#define FE_IQ_EST_MULT_PWR_S 0

#define FE_IQ_RESULT_PWR_I_REG (REG_FE_BASE + 0x00ec)
#define FE_IQ_EST_MULT_PWR_I 0xFFFFFFFF
#define FE_IQ_EST_MULT_PWR_I_S 0

#define FE_IQ_RESULT_PWR_Q_REG (REG_FE_BASE + 0x00f0)
#define FE_IQ_EST_MULT_PWR_Q 0xFFFFFFFF
#define FE_IQ_EST_MULT_PWR_Q_S 0

#define FE_IQ_RESULT_PWR_IQ_REG (REG_FE_BASE + 0x00f4)
#define FE_IQ_EST_MULT_PWR_IQ 0xFFFFFFFF
#define FE_IQ_EST_MULT_PWR_IQ_S 0

#define FE_NOUSE_REG (REG_FE_BASE + 0x00f8)
#define FE_NOUSE 0xFFFFFFFF
#define FE_NOUSE_S 0

#define FE_NOUSE_2_REG (REG_FE_BASE + 0x00fc)
#define FE_CLK_EN (BIT(28))
#define FE_CLK_EN_S 28

#define FE_IQ_RESULT_LOOP_1_REG (REG_FE_BASE + 0x0100)
#define FE_R_LOOP_MULT_II 0xFFFFFFFF
#define FE_R_LOOP_MULT_II_S 0

#define FE_IQ_RESULT_LOOP_2_REG (REG_FE_BASE + 0x0104)
#define FE_R_LOOP_MULT_IQ 0xFFFFFFFF
#define FE_R_LOOP_MULT_IQ_S 0

#define FE_IQ_RESULT_LOOP_3_REG (REG_FE_BASE + 0x0108)
#define FE_R_LOOP_MULT_QI 0xFFFFFFFF
#define FE_R_LOOP_MULT_QI_S 0

#define FE_IQ_RESULT_LOOP_4_REG (REG_FE_BASE + 0x010c)
#define FE_R_LOOP_MULT_QQ 0xFFFFFFFF
#define FE_R_LOOP_MULT_QQ_S 0

#define FE_IQ_RESULT_LOOP_2_1_REG (REG_FE_BASE + 0x0110)
#define FE_R_LOOP_MULT2_II 0xFFFFFFFF
#define FE_R_LOOP_MULT2_II_S 0

#define FE_IQ_RESULT_LOOP_2_2_REG (REG_FE_BASE + 0x0114)
#define FE_R_LOOP_MULT2_IQ 0xFFFFFFFF
#define FE_R_LOOP_MULT2_IQ_S 0

#define FE_IQ_RESULT_LOOP_2_3_REG (REG_FE_BASE + 0x0118)
#define FE_R_LOOP_MULT2_QI 0xFFFFFFFF
#define FE_R_LOOP_MULT2_QI_S 0

#define FE_IQ_RESULT_LOOP_2_4_REG (REG_FE_BASE + 0x011c)
#define FE_R_LOOP_MULT2_QQ 0xFFFFFFFF
#define FE_R_LOOP_MULT2_QQ_S 0

#define FE_IQ_RESULT_LOOP_DC_I_REG (REG_FE_BASE + 0x0120)
#define FE_R_LOOP_MULT_DC_I 0xFFFFFFFF
#define FE_R_LOOP_MULT_DC_I_S 0

#define FE_IQ_RESULT_LOOP_DC_Q_REG (REG_FE_BASE + 0x0124)
#define FE_R_LOOP_MULT_DC_Q 0xFFFFFFFF
#define FE_R_LOOP_MULT_DC_Q_S 0

#define FE_IQ_RESULT_LOOP_PWR_REG (REG_FE_BASE + 0x0128)
#define FE_LOOP_MULT_PWR 0xFFFFFFFF
#define FE_LOOP_MULT_PWR_S 0

#define FE_IQ_RESULT_LOOP_PWR_I_REG (REG_FE_BASE + 0x012c)
#define FE_R_LOOP_MULT_PWR_I 0xFFFFFFFF
#define FE_R_LOOP_MULT_PWR_I_S 0

#define FE_IQ_RESULT_LOOP_PWR_Q_REG (REG_FE_BASE + 0x0130)
#define FE_R_LOOP_MULT_PWR_Q 0xFFFFFFFF
#define FE_R_LOOP_MULT_PWR_Q_S 0

#define FE_IQ_RESULT_LOOP_PWR_IQ_REG (REG_FE_BASE + 0x0134)
#define FE_R_LOOP_MULT_PWR_IQ 0xFFFFFFFF
#define FE_R_LOOP_MULT_PWR_IQ_S 0

#define FE_IQ_LOOP_CTRL_REG (REG_FE_BASE + 0x0138)
#define FE_IQ_EST_LOOP_HUNG (BIT(17))
#define FE_IQ_EST_LOOP_HUNG_S 17
#define FE_IQ_EST_DONE (BIT(16))
#define FE_IQ_EST_DONE_S 16
#define FE_R_IQ_EST_LOOP 0x000000FF
#define FE_R_IQ_EST_LOOP_S 8
#define FE_IQ_EST_LOOP 0x000000FF
#define FE_IQ_EST_LOOP_S 0

#define FE_BTTX_GAIN_CTRL_1_REG (REG_FE_BASE + 0x013c)
#define FE_BTTX_GAIN_CTRL1 0xFFFFFFFF
#define FE_BTTX_GAIN_CTRL1_S 0

#define FE_BTTX_GAIN_CTRL_2_REG (REG_FE_BASE + 0x0140)
#define FE_BTTX_GAIN_CTRL2 0xFFFFFFFF
#define FE_BTTX_GAIN_CTRL2_S 0

#define FE_BTTX_GAIN_CTRL_3_REG (REG_FE_BASE + 0x0144)
#define FE_BTTX_GAIN_CTRL3 0xFFFFFFFF
#define FE_BTTX_GAIN_CTRL3_S 0

#define FE_BTTX_GAIN_CTRL_4_REG (REG_FE_BASE + 0x0148)
#define FE_BTTX_GAIN_CTRL4 0xFFFFFFFF
#define FE_BTTX_GAIN_CTRL4_S 0

#define FE_ANA_SCALE_CTRL_1_REG (REG_FE_BASE + 0x014c)
#define FE_ANA_SCALE_CTRL1 0xFFFFFFFF
#define FE_ANA_SCALE_CTRL1_S 0

#define FE_ANA_SCALE_CTRL_2_REG (REG_FE_BASE + 0x0150)
#define FE_ANA_SCALE_CTRL2 0xFFFFFFFF
#define FE_ANA_SCALE_CTRL2_S 0

#define FE_ANA_SCALE_CTRL_3_REG (REG_FE_BASE + 0x0154)
#define FE_ANA_SCALE_CTRL3 0xFFFFFFFF
#define FE_ANA_SCALE_CTRL3_S 0

#define FE_ANA_SCALE_CTRL_4_REG (REG_FE_BASE + 0x0158)
#define FE_ANA_SCALE_CTRL4 0xFFFFFFFF
#define FE_ANA_SCALE_CTRL4_S 0

#define FE_TXFILT_BAND_CTRL_1_REG (REG_FE_BASE + 0x015c)
#define FE_TXFILT_BAND_CTRL1 0xFFFFFFFF
#define FE_TXFILT_BAND_CTRL1_S 0

#define FE_NOUSE_3_REG (REG_FE_BASE + 0x01fc)
#define FE_DATE 0x0FFFFFFF
#define FE_DATE_S 0
#define FE_DATE_VERSION 0x1807101
