
#define I2C_EXT_SCL_LOW_PERIOD_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0000)
#define I2C_EXT_SCL_LOW_PERIOD 0x00003FFF
#define I2C_EXT_SCL_LOW_PERIOD_S 0

#define I2C_EXT_CTR_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0004)
#define I2C_EXT_REF_ALWAYS_ON (BIT(11))
#define I2C_EXT_REF_ALWAYS_ON_S 11
#define I2C_EXT_FSM_RST (BIT(10))
#define I2C_EXT_FSM_RST_S 10
#define I2C_EXT_ARBITRATION_EN (BIT(9))
#define I2C_EXT_ARBITRATION_EN_S 9
#define I2C_EXT_CLK_EN (BIT(8))
#define I2C_EXT_CLK_EN_S 8
#define I2C_EXT_RX_LSB_FIRST (BIT(7))
#define I2C_EXT_RX_LSB_FIRST_S 7
#define I2C_EXT_TX_LSB_FIRST (BIT(6))
#define I2C_EXT_TX_LSB_FIRST_S 6
#define I2C_EXT_TRANS_START (BIT(5))
#define I2C_EXT_TRANS_START_S 5
#define I2C_EXT_MS_MODE (BIT(4))
#define I2C_EXT_MS_MODE_S 4
#define I2C_EXT_ACK_LEVEL (BIT(3))
#define I2C_EXT_ACK_LEVEL_S 3
#define I2C_EXT_SAMPLE_SCL_LEVEL (BIT(2))
#define I2C_EXT_SAMPLE_SCL_LEVEL_S 2
#define I2C_EXT_SCL_FORCE_OUT (BIT(1))
#define I2C_EXT_SCL_FORCE_OUT_S 1
#define I2C_EXT_SDA_FORCE_OUT (BIT(0))
#define I2C_EXT_SDA_FORCE_OUT_S 0

#define I2C_EXT_SR_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0008)
#define I2C_EXT_SCL_STATE_LAST 0x00000007
#define I2C_EXT_SCL_STATE_LAST_S 28
#define I2C_EXT_SCL_MAIN_STATE_LAST 0x00000007
#define I2C_EXT_SCL_MAIN_STATE_LAST_S 24
#define I2C_EXT_TXFIFO_CNT 0x0000003F
#define I2C_EXT_TXFIFO_CNT_S 18
#define I2C_EXT_RXFIFO_CNT 0x0000003F
#define I2C_EXT_RXFIFO_CNT_S 8
#define I2C_EXT_BYTE_TRANS (BIT(6))
#define I2C_EXT_BYTE_TRANS_S 6
#define I2C_EXT_SLAVE_ADDRESSED (BIT(5))
#define I2C_EXT_SLAVE_ADDRESSED_S 5
#define I2C_EXT_BUS_BUSY (BIT(4))
#define I2C_EXT_BUS_BUSY_S 4
#define I2C_EXT_ARB_LOST (BIT(3))
#define I2C_EXT_ARB_LOST_S 3
#define I2C_EXT_TIME_OUT (BIT(2))
#define I2C_EXT_TIME_OUT_S 2
#define I2C_EXT_SLAVE_RW (BIT(1))
#define I2C_EXT_SLAVE_RW_S 1
#define I2C_EXT_ACK_REC (BIT(0))
#define I2C_EXT_ACK_REC_S 0

#define I2C_EXT_TO_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x000c)
#define I2C_EXT_TIME_OUT_EN (BIT(24))
#define I2C_EXT_TIME_OUT_EN_S 24
#define I2C_EXT_TIME_OUT_REG 0x00FFFFFF
#define I2C_EXT_TIME_OUT_REG_S 0

#define I2C_EXT_SLAVE_ADDR_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0010)
#define I2C_EXT_ADDR_10BIT_EN (BIT(31))
#define I2C_EXT_ADDR_10BIT_EN_S 31
#define I2C_EXT_SLAVE_ADDR 0x00007FFF
#define I2C_EXT_SLAVE_ADDR_S 0

#define I2C_EXT_RXFIFO_ST_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0014)
#define I2C_EXT_RXFIFO_INIT_WADDR 0x0000001F
#define I2C_EXT_RXFIFO_INIT_WADDR_S 27
#define I2C_EXT_TXFIFO_INIT_RADDR 0x0000001F
#define I2C_EXT_TXFIFO_INIT_RADDR_S 22
#define I2C_EXT_TX_UPDATE (BIT(21))
#define I2C_EXT_TX_UPDATE_S 21
#define I2C_EXT_RX_UPDATE (BIT(20))
#define I2C_EXT_RX_UPDATE_S 20
#define I2C_EXT_TXFIFO_END_ADDR 0x0000001F
#define I2C_EXT_TXFIFO_END_ADDR_S 15
#define I2C_EXT_TXFIFO_START_ADDR 0x0000001F
#define I2C_EXT_TXFIFO_START_ADDR_S 10
#define I2C_EXT_RXFIFO_END_ADDR 0x0000001F
#define I2C_EXT_RXFIFO_END_ADDR_S 5
#define I2C_EXT_RXFIFO_START_ADDR 0x0000001F
#define I2C_EXT_RXFIFO_START_ADDR_S 0

#define I2C_EXT_I2C_FIFO_CONF_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0018)
#define I2C_EXT_NONFIFO_TX_THRES 0x0000003F
#define I2C_EXT_NONFIFO_TX_THRES_S 20
#define I2C_EXT_NONFIFO_RX_THRES 0x0000003F
#define I2C_EXT_NONFIFO_RX_THRES_S 14
#define I2C_EXT_TX_FIFO_RST (BIT(13))
#define I2C_EXT_TX_FIFO_RST_S 13
#define I2C_EXT_RX_FIFO_RST (BIT(12))
#define I2C_EXT_RX_FIFO_RST_S 12
#define I2C_EXT_FIFO_ADDR_CFG_EN (BIT(11))
#define I2C_EXT_FIFO_ADDR_CFG_EN_S 11
#define I2C_EXT_NONFIFO_EN (BIT(10))
#define I2C_EXT_NONFIFO_EN_S 10
#define I2C_EXT_TXFIFO_EMPTY_THRHD 0x0000001F
#define I2C_EXT_TXFIFO_EMPTY_THRHD_S 5
#define I2C_EXT_RXFIFO_FULL_THRHD 0x0000001F
#define I2C_EXT_RXFIFO_FULL_THRHD_S 0

#define I2C_EXT_I2C_DATA_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x001c)
#define I2C_EXT_FIFO_RDATA 0x000000FF
#define I2C_EXT_FIFO_RDATA_S 0

#define I2C_EXT_I2C_INT_RAW_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0020)
#define I2C_EXT_DET_START_INT_RAW (BIT(15))
#define I2C_EXT_DET_START_INT_RAW_S 15
#define I2C_EXT_SCL_MAIN_ST_TO_INT_RAW (BIT(14))
#define I2C_EXT_SCL_MAIN_ST_TO_INT_RAW_S 14
#define I2C_EXT_SCL_ST_TO_INT_RAW (BIT(13))
#define I2C_EXT_SCL_ST_TO_INT_RAW_S 13
#define I2C_EXT_TX_SEND_EMPTY_INT_RAW (BIT(12))
#define I2C_EXT_TX_SEND_EMPTY_INT_RAW_S 12
#define I2C_EXT_RX_REC_FULL_INT_RAW (BIT(11))
#define I2C_EXT_RX_REC_FULL_INT_RAW_S 11
#define I2C_EXT_ACK_ERR_INT_RAW (BIT(10))
#define I2C_EXT_ACK_ERR_INT_RAW_S 10
#define I2C_EXT_TRANS_START_INT_RAW (BIT(9))
#define I2C_EXT_TRANS_START_INT_RAW_S 9
#define I2C_EXT_TIME_OUT_INT_RAW (BIT(8))
#define I2C_EXT_TIME_OUT_INT_RAW_S 8
#define I2C_EXT_TRANS_COMPLETE_INT_RAW (BIT(7))
#define I2C_EXT_TRANS_COMPLETE_INT_RAW_S 7
#define I2C_EXT_MASTER_TRAN_COMP_INT_RAW (BIT(6))
#define I2C_EXT_MASTER_TRAN_COMP_INT_RAW_S 6
#define I2C_EXT_ARBITRATION_LOST_INT_RAW (BIT(5))
#define I2C_EXT_ARBITRATION_LOST_INT_RAW_S 5
#define I2C_EXT_SLAVE_TRAN_COMP_INT_RAW (BIT(4))
#define I2C_EXT_SLAVE_TRAN_COMP_INT_RAW_S 4
#define I2C_EXT_END_DETECT_INT_RAW (BIT(3))
#define I2C_EXT_END_DETECT_INT_RAW_S 3
#define I2C_EXT_RXFIFO_OVF_INT_RAW (BIT(2))
#define I2C_EXT_RXFIFO_OVF_INT_RAW_S 2
#define I2C_EXT_TXFIFO_EMPTY_INT_RAW (BIT(1))
#define I2C_EXT_TXFIFO_EMPTY_INT_RAW_S 1
#define I2C_EXT_RXFIFO_FULL_INT_RAW (BIT(0))
#define I2C_EXT_RXFIFO_FULL_INT_RAW_S 0

#define I2C_EXT_I2C_INT_CLR_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0024)
#define I2C_EXT_DET_START_INT_CLR (BIT(15))
#define I2C_EXT_DET_START_INT_CLR_S 15
#define I2C_EXT_SCL_MAIN_ST_TO_INT_CLR (BIT(14))
#define I2C_EXT_SCL_MAIN_ST_TO_INT_CLR_S 14
#define I2C_EXT_SCL_ST_TO_INT_CLR (BIT(13))
#define I2C_EXT_SCL_ST_TO_INT_CLR_S 13
#define I2C_EXT_TX_SEND_EMPTY_INT_CLR (BIT(12))
#define I2C_EXT_TX_SEND_EMPTY_INT_CLR_S 12
#define I2C_EXT_RX_REC_FULL_INT_CLR (BIT(11))
#define I2C_EXT_RX_REC_FULL_INT_CLR_S 11
#define I2C_EXT_ACK_ERR_INT_CLR (BIT(10))
#define I2C_EXT_ACK_ERR_INT_CLR_S 10
#define I2C_EXT_TRANS_START_INT_CLR (BIT(9))
#define I2C_EXT_TRANS_START_INT_CLR_S 9
#define I2C_EXT_TIME_OUT_INT_CLR (BIT(8))
#define I2C_EXT_TIME_OUT_INT_CLR_S 8
#define I2C_EXT_TRANS_COMPLETE_INT_CLR (BIT(7))
#define I2C_EXT_TRANS_COMPLETE_INT_CLR_S 7
#define I2C_EXT_MASTER_TRAN_COMP_INT_CLR (BIT(6))
#define I2C_EXT_MASTER_TRAN_COMP_INT_CLR_S 6
#define I2C_EXT_ARBITRATION_LOST_INT_CLR (BIT(5))
#define I2C_EXT_ARBITRATION_LOST_INT_CLR_S 5
#define I2C_EXT_SLAVE_TRAN_COMP_INT_CLR (BIT(4))
#define I2C_EXT_SLAVE_TRAN_COMP_INT_CLR_S 4
#define I2C_EXT_END_DETECT_INT_CLR (BIT(3))
#define I2C_EXT_END_DETECT_INT_CLR_S 3
#define I2C_EXT_RXFIFO_OVF_INT_CLR (BIT(2))
#define I2C_EXT_RXFIFO_OVF_INT_CLR_S 2
#define I2C_EXT_TXFIFO_EMPTY_INT_CLR (BIT(1))
#define I2C_EXT_TXFIFO_EMPTY_INT_CLR_S 1
#define I2C_EXT_RXFIFO_FULL_INT_CLR (BIT(0))
#define I2C_EXT_RXFIFO_FULL_INT_CLR_S 0

#define I2C_EXT_I2C_INT_ENA_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0028)
#define I2C_EXT_DET_START_INT_ENA (BIT(15))
#define I2C_EXT_DET_START_INT_ENA_S 15
#define I2C_EXT_SCL_MAIN_ST_TO_INT_ENA (BIT(14))
#define I2C_EXT_SCL_MAIN_ST_TO_INT_ENA_S 14
#define I2C_EXT_SCL_ST_TO_INT_ENA (BIT(13))
#define I2C_EXT_SCL_ST_TO_INT_ENA_S 13
#define I2C_EXT_TX_SEND_EMPTY_INT_ENA (BIT(12))
#define I2C_EXT_TX_SEND_EMPTY_INT_ENA_S 12
#define I2C_EXT_RX_REC_FULL_INT_ENA (BIT(11))
#define I2C_EXT_RX_REC_FULL_INT_ENA_S 11
#define I2C_EXT_ACK_ERR_INT_ENA (BIT(10))
#define I2C_EXT_ACK_ERR_INT_ENA_S 10
#define I2C_EXT_TRANS_START_INT_ENA (BIT(9))
#define I2C_EXT_TRANS_START_INT_ENA_S 9
#define I2C_EXT_TIME_OUT_INT_ENA (BIT(8))
#define I2C_EXT_TIME_OUT_INT_ENA_S 8
#define I2C_EXT_TRANS_COMPLETE_INT_ENA (BIT(7))
#define I2C_EXT_TRANS_COMPLETE_INT_ENA_S 7
#define I2C_EXT_MASTER_TRAN_COMP_INT_ENA (BIT(6))
#define I2C_EXT_MASTER_TRAN_COMP_INT_ENA_S 6
#define I2C_EXT_ARBITRATION_LOST_INT_ENA (BIT(5))
#define I2C_EXT_ARBITRATION_LOST_INT_ENA_S 5
#define I2C_EXT_SLAVE_TRAN_COMP_INT_ENA (BIT(4))
#define I2C_EXT_SLAVE_TRAN_COMP_INT_ENA_S 4
#define I2C_EXT_END_DETECT_INT_ENA (BIT(3))
#define I2C_EXT_END_DETECT_INT_ENA_S 3
#define I2C_EXT_RXFIFO_OVF_INT_ENA (BIT(2))
#define I2C_EXT_RXFIFO_OVF_INT_ENA_S 2
#define I2C_EXT_TXFIFO_EMPTY_INT_ENA (BIT(1))
#define I2C_EXT_TXFIFO_EMPTY_INT_ENA_S 1
#define I2C_EXT_RXFIFO_FULL_INT_ENA (BIT(0))
#define I2C_EXT_RXFIFO_FULL_INT_ENA_S 0

#define I2C_EXT_I2C_INT_STATUS_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x002c)
#define I2C_EXT_DET_START_INT_ST (BIT(15))
#define I2C_EXT_DET_START_INT_ST_S 15
#define I2C_EXT_SCL_MAIN_ST_TO_INT_ST (BIT(14))
#define I2C_EXT_SCL_MAIN_ST_TO_INT_ST_S 14
#define I2C_EXT_SCL_ST_TO_INT_ST (BIT(13))
#define I2C_EXT_SCL_ST_TO_INT_ST_S 13
#define I2C_EXT_TX_SEND_EMPTY_INT_ST (BIT(12))
#define I2C_EXT_TX_SEND_EMPTY_INT_ST_S 12
#define I2C_EXT_RX_REC_FULL_INT_ST (BIT(11))
#define I2C_EXT_RX_REC_FULL_INT_ST_S 11
#define I2C_EXT_ACK_ERR_INT_ST (BIT(10))
#define I2C_EXT_ACK_ERR_INT_ST_S 10
#define I2C_EXT_TRANS_START_INT_ST (BIT(9))
#define I2C_EXT_TRANS_START_INT_ST_S 9
#define I2C_EXT_TIME_OUT_INT_ST (BIT(8))
#define I2C_EXT_TIME_OUT_INT_ST_S 8
#define I2C_EXT_TRANS_COMPLETE_INT_ST (BIT(7))
#define I2C_EXT_TRANS_COMPLETE_INT_ST_S 7
#define I2C_EXT_MASTER_TRAN_COMP_INT_ST (BIT(6))
#define I2C_EXT_MASTER_TRAN_COMP_INT_ST_S 6
#define I2C_EXT_ARBITRATION_LOST_INT_ST (BIT(5))
#define I2C_EXT_ARBITRATION_LOST_INT_ST_S 5
#define I2C_EXT_SLAVE_TRAN_COMP_INT_ST (BIT(4))
#define I2C_EXT_SLAVE_TRAN_COMP_INT_ST_S 4
#define I2C_EXT_END_DETECT_INT_ST (BIT(3))
#define I2C_EXT_END_DETECT_INT_ST_S 3
#define I2C_EXT_RXFIFO_OVF_INT_ST (BIT(2))
#define I2C_EXT_RXFIFO_OVF_INT_ST_S 2
#define I2C_EXT_TXFIFO_EMPTY_INT_ST (BIT(1))
#define I2C_EXT_TXFIFO_EMPTY_INT_ST_S 1
#define I2C_EXT_RXFIFO_FULL_INT_ST (BIT(0))
#define I2C_EXT_RXFIFO_FULL_INT_ST_S 0

#define I2C_EXT_I2C_SDA_HOLD_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0030)
#define I2C_EXT_SDA_HOLD_TIME 0x000003FF
#define I2C_EXT_SDA_HOLD_TIME_S 0

#define I2C_EXT_I2C_SDA_SAMPLE_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0034)
#define I2C_EXT_SDA_SAMPLE_TIME 0x000003FF
#define I2C_EXT_SDA_SAMPLE_TIME_S 0

#define I2C_EXT_SCL_HIGH_PERIOD_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0038)
#define I2C_EXT_SCL_WAIT_HIGH_PERIOD 0x00003FFF
#define I2C_EXT_SCL_WAIT_HIGH_PERIOD_S 14
#define I2C_EXT_SCL_HIGH_PERIOD 0x00003FFF
#define I2C_EXT_SCL_HIGH_PERIOD_S 0

#define I2C_EXT_SCL_START_HOLD_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0040)
#define I2C_EXT_SCL_START_HOLD_TIME 0x000003FF
#define I2C_EXT_SCL_START_HOLD_TIME_S 0

#define I2C_EXT_SCL_RSTART_SETUP_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0044)
#define I2C_EXT_SCL_RSTART_SETUP_TIME 0x000003FF
#define I2C_EXT_SCL_RSTART_SETUP_TIME_S 0

#define I2C_EXT_SCL_STOP_HOLD_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0048)
#define I2C_EXT_SCL_STOP_HOLD_TIME 0x00003FFF
#define I2C_EXT_SCL_STOP_HOLD_TIME_S 0

#define I2C_EXT_SCL_STOP_SETUP_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x004C)
#define I2C_EXT_SCL_STOP_SETUP_TIME 0x000003FF
#define I2C_EXT_SCL_STOP_SETUP_TIME_S 0

#define I2C_EXT_SCL_FILTER_CFG_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0050)
#define I2C_EXT_SCL_FILTER_EN (BIT(3))
#define I2C_EXT_SCL_FILTER_EN_S 3
#define I2C_EXT_SCL_FILTER_THRES 0x00000007
#define I2C_EXT_SCL_FILTER_THRES_S 0

#define I2C_EXT_SDA_FILTER_CFG_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0054)
#define I2C_EXT_SDA_FILTER_EN (BIT(3))
#define I2C_EXT_SDA_FILTER_EN_S 3
#define I2C_EXT_SDA_FILTER_THRES 0x00000007
#define I2C_EXT_SDA_FILTER_THRES_S 0

#define I2C_EXT_I2C_COMD0_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0058)
#define I2C_EXT_COMMAND0_DONE (BIT(31))
#define I2C_EXT_COMMAND0_DONE_S 31
#define I2C_EXT_COMMAND0 0x00003FFF
#define I2C_EXT_COMMAND0_S 0

#define I2C_EXT_I2C_COMD1_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x005C)
#define I2C_EXT_COMMAND1_DONE (BIT(31))
#define I2C_EXT_COMMAND1_DONE_S 31
#define I2C_EXT_COMMAND1 0x00003FFF
#define I2C_EXT_COMMAND1_S 0

#define I2C_EXT_I2C_COMD2_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0060)
#define I2C_EXT_COMMAND2_DONE (BIT(31))
#define I2C_EXT_COMMAND2_DONE_S 31
#define I2C_EXT_COMMAND2 0x00003FFF
#define I2C_EXT_COMMAND2_S 0

#define I2C_EXT_I2C_COMD3_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0064)
#define I2C_EXT_COMMAND3_DONE (BIT(31))
#define I2C_EXT_COMMAND3_DONE_S 31
#define I2C_EXT_COMMAND3 0x00003FFF
#define I2C_EXT_COMMAND3_S 0

#define I2C_EXT_I2C_COMD4_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0068)
#define I2C_EXT_COMMAND4_DONE (BIT(31))
#define I2C_EXT_COMMAND4_DONE_S 31
#define I2C_EXT_COMMAND4 0x00003FFF
#define I2C_EXT_COMMAND4_S 0

#define I2C_EXT_I2C_COMD5_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x006C)
#define I2C_EXT_COMMAND5_DONE (BIT(31))
#define I2C_EXT_COMMAND5_DONE_S 31
#define I2C_EXT_COMMAND5 0x00003FFF
#define I2C_EXT_COMMAND5_S 0

#define I2C_EXT_I2C_COMD6_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0070)
#define I2C_EXT_COMMAND6_DONE (BIT(31))
#define I2C_EXT_COMMAND6_DONE_S 31
#define I2C_EXT_COMMAND6 0x00003FFF
#define I2C_EXT_COMMAND6_S 0

#define I2C_EXT_I2C_COMD7_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0074)
#define I2C_EXT_COMMAND7_DONE (BIT(31))
#define I2C_EXT_COMMAND7_DONE_S 31
#define I2C_EXT_COMMAND7 0x00003FFF
#define I2C_EXT_COMMAND7_S 0

#define I2C_EXT_I2C_COMD8_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0078)
#define I2C_EXT_COMMAND8_DONE (BIT(31))
#define I2C_EXT_COMMAND8_DONE_S 31
#define I2C_EXT_COMMAND8 0x00003FFF
#define I2C_EXT_COMMAND8_S 0

#define I2C_EXT_I2C_COMD9_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x007C)
#define I2C_EXT_COMMAND9_DONE (BIT(31))
#define I2C_EXT_COMMAND9_DONE_S 31
#define I2C_EXT_COMMAND9 0x00003FFF
#define I2C_EXT_COMMAND9_S 0

#define I2C_EXT_I2C_COMD10_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0080)
#define I2C_EXT_COMMAND10_DONE (BIT(31))
#define I2C_EXT_COMMAND10_DONE_S 31
#define I2C_EXT_COMMAND10 0x00003FFF
#define I2C_EXT_COMMAND10_S 0

#define I2C_EXT_I2C_COMD11_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0084)
#define I2C_EXT_COMMAND11_DONE (BIT(31))
#define I2C_EXT_COMMAND11_DONE_S 31
#define I2C_EXT_COMMAND11 0x00003FFF
#define I2C_EXT_COMMAND11_S 0

#define I2C_EXT_I2C_COMD12_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0088)
#define I2C_EXT_COMMAND12_DONE (BIT(31))
#define I2C_EXT_COMMAND12_DONE_S 31
#define I2C_EXT_COMMAND12 0x00003FFF
#define I2C_EXT_COMMAND12_S 0

#define I2C_EXT_I2C_COMD13_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x008C)
#define I2C_EXT_COMMAND13_DONE (BIT(31))
#define I2C_EXT_COMMAND13_DONE_S 31
#define I2C_EXT_COMMAND13 0x00003FFF
#define I2C_EXT_COMMAND13_S 0

#define I2C_EXT_I2C_COMD14_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0090)
#define I2C_EXT_COMMAND14_DONE (BIT(31))
#define I2C_EXT_COMMAND14_DONE_S 31
#define I2C_EXT_COMMAND14 0x00003FFF
#define I2C_EXT_COMMAND14_S 0

#define I2C_EXT_I2C_COMD15_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0094)
#define I2C_EXT_COMMAND15_DONE (BIT(31))
#define I2C_EXT_COMMAND15_DONE_S 31
#define I2C_EXT_COMMAND15 0x00003FFF
#define I2C_EXT_COMMAND15_S 0

#define I2C_EXT_SCL_ST_TIME_OUT_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0098)
#define I2C_EXT_SCL_ST_TO_REG 0x00FFFFFF
#define I2C_EXT_SCL_ST_TO_REG_S 0

#define I2C_EXT_SCL_MAIN_ST_TIME_OUT_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x009c)
#define I2C_EXT_SCL_MAIN_ST_TO_REG 0x00FFFFFF
#define I2C_EXT_SCL_MAIN_ST_TO_REG_S 0

#define I2C_EXT_SCL_SP_CONF_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x00a0)
#define I2C_EXT_SDA_PD_EN (BIT(7))
#define I2C_EXT_SDA_PD_EN_S 7
#define I2C_EXT_SCL_PD_EN (BIT(6))
#define I2C_EXT_SCL_PD_EN_S 6
#define I2C_EXT_SCL_RST_SLV_NUM 0x0000001F
#define I2C_EXT_SCL_RST_SLV_NUM_S 1
#define I2C_EXT_SCL_RST_SLV_EN (BIT(0))
#define I2C_EXT_SCL_RST_SLV_EN_S 0

#define I2C_EXT_I2C_DATE_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x00F8)
#define I2C_EXT_I2C_DATE 0xFFFFFFFF
#define I2C_EXT_I2C_DATE_S 0
#define I2C_EXT_I2C_DATE_VERSION 0x18073100

#define I2C_EXT_I2C_FIFO_START_ADDR_REG( i ) (REG_I2C_EXT_BASE( i ) + 0x0100)
