
#define INTERRUPT_PRO_MAC_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x000)
#define INTERRUPT_PRO_MAC_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_MAC_INTR_MAP_S 0

#define INTERRUPT_PRO_MAC_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x004)
#define INTERRUPT_PRO_MAC_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_MAC_NMI_MAP_S 0

#define INTERRUPT_PRO_PWR_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x008)
#define INTERRUPT_PRO_PWR_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PWR_INTR_MAP_S 0

#define INTERRUPT_PRO_BB_INT_MAP_REG (REG_INTERRUPT_BASE + 0x00C)
#define INTERRUPT_PRO_BB_INT_MAP 0x0000001F
#define INTERRUPT_PRO_BB_INT_MAP_S 0

#define INTERRUPT_PRO_BT_MAC_INT_MAP_REG (REG_INTERRUPT_BASE + 0x010)
#define INTERRUPT_PRO_BT_MAC_INT_MAP 0x0000001F
#define INTERRUPT_PRO_BT_MAC_INT_MAP_S 0

#define INTERRUPT_PRO_BT_BB_INT_MAP_REG (REG_INTERRUPT_BASE + 0x014)
#define INTERRUPT_PRO_BT_BB_INT_MAP 0x0000001F
#define INTERRUPT_PRO_BT_BB_INT_MAP_S 0

#define INTERRUPT_PRO_BT_BB_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x018)
#define INTERRUPT_PRO_BT_BB_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_BT_BB_NMI_MAP_S 0

#define INTERRUPT_PRO_RWBT_IRQ_MAP_REG (REG_INTERRUPT_BASE + 0x01C)
#define INTERRUPT_PRO_RWBT_IRQ_MAP 0x0000001F
#define INTERRUPT_PRO_RWBT_IRQ_MAP_S 0

#define INTERRUPT_PRO_RWBLE_IRQ_MAP_REG (REG_INTERRUPT_BASE + 0x020)
#define INTERRUPT_PRO_RWBLE_IRQ_MAP 0x0000001F
#define INTERRUPT_PRO_RWBLE_IRQ_MAP_S 0

#define INTERRUPT_PRO_RWBT_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x024)
#define INTERRUPT_PRO_RWBT_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_RWBT_NMI_MAP_S 0

#define INTERRUPT_PRO_RWBLE_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x028)
#define INTERRUPT_PRO_RWBLE_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_RWBLE_NMI_MAP_S 0

#define INTERRUPT_PRO_SLC0_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x02C)
#define INTERRUPT_PRO_SLC0_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_SLC0_INTR_MAP_S 0

#define INTERRUPT_PRO_SLC1_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x030)
#define INTERRUPT_PRO_SLC1_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_SLC1_INTR_MAP_S 0

#define INTERRUPT_PRO_UHCI0_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x034)
#define INTERRUPT_PRO_UHCI0_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_UHCI0_INTR_MAP_S 0

#define INTERRUPT_PRO_UHCI1_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x038)
#define INTERRUPT_PRO_UHCI1_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_UHCI1_INTR_MAP_S 0

#define INTERRUPT_PRO_TG_T0_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x03C)
#define INTERRUPT_PRO_TG_T0_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_T0_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG_T1_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x040)
#define INTERRUPT_PRO_TG_T1_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_T1_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG_WDT_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x044)
#define INTERRUPT_PRO_TG_WDT_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_WDT_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG_LACT_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x048)
#define INTERRUPT_PRO_TG_LACT_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_LACT_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_T0_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x04C)
#define INTERRUPT_PRO_TG1_T0_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_T0_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_T1_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x050)
#define INTERRUPT_PRO_TG1_T1_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_T1_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_WDT_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x054)
#define INTERRUPT_PRO_TG1_WDT_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_WDT_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_LACT_LEVEL_INT_MAP_REG (REG_INTERRUPT_BASE + 0x058)
#define INTERRUPT_PRO_TG1_LACT_LEVEL_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_LACT_LEVEL_INT_MAP_S 0

#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_MAP_REG (REG_INTERRUPT_BASE + 0x05C)
#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_MAP 0x0000001F
#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_MAP_S 0

#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x060)
#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_GPIO_INTERRUPT_PRO_NMI_MAP_S 0

#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_MAP_REG (REG_INTERRUPT_BASE + 0x064)
#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_MAP 0x0000001F
#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_MAP_S 0

#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_NMI_MAP_REG (REG_INTERRUPT_BASE + 0x068)
#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_NMI_MAP 0x0000001F
#define INTERRUPT_PRO_GPIO_INTERRUPT_APP_NMI_MAP_S 0

#define INTERRUPT_PRO_DEDICATED_GPIO_IN_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x06C)
#define INTERRUPT_PRO_DEDICATED_GPIO_IN_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_DEDICATED_GPIO_IN_INTR_MAP_S 0

#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_0_MAP_REG (REG_INTERRUPT_BASE + 0x070)
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_0_MAP 0x0000001F
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_0_MAP_S 0

#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_1_MAP_REG (REG_INTERRUPT_BASE + 0x074)
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_1_MAP 0x0000001F
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_1_MAP_S 0

#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_2_MAP_REG (REG_INTERRUPT_BASE + 0x078)
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_2_MAP 0x0000001F
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_2_MAP_S 0

#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_3_MAP_REG (REG_INTERRUPT_BASE + 0x07C)
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_3_MAP 0x0000001F
#define INTERRUPT_PRO_CPU_INTR_FROM_CPU_3_MAP_S 0

#define INTERRUPT_PRO_SPI_INTR_1_MAP_REG (REG_INTERRUPT_BASE + 0x080)
#define INTERRUPT_PRO_SPI_INTR_1_MAP 0x0000001F
#define INTERRUPT_PRO_SPI_INTR_1_MAP_S 0

#define INTERRUPT_PRO_SPI_INTR_2_MAP_REG (REG_INTERRUPT_BASE + 0x084)
#define INTERRUPT_PRO_SPI_INTR_2_MAP 0x0000001F
#define INTERRUPT_PRO_SPI_INTR_2_MAP_S 0

#define INTERRUPT_PRO_SPI_INTR_3_MAP_REG (REG_INTERRUPT_BASE + 0x088)
#define INTERRUPT_PRO_SPI_INTR_3_MAP 0x0000001F
#define INTERRUPT_PRO_SPI_INTR_3_MAP_S 0

#define INTERRUPT_PRO_I2S0_INT_MAP_REG (REG_INTERRUPT_BASE + 0x08C)
#define INTERRUPT_PRO_I2S0_INT_MAP 0x0000001F
#define INTERRUPT_PRO_I2S0_INT_MAP_S 0

#define INTERRUPT_PRO_I2S1_INT_MAP_REG (REG_INTERRUPT_BASE + 0x090)
#define INTERRUPT_PRO_I2S1_INT_MAP 0x0000001F
#define INTERRUPT_PRO_I2S1_INT_MAP_S 0

#define INTERRUPT_PRO_UART_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x094)
#define INTERRUPT_PRO_UART_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_UART_INTR_MAP_S 0

#define INTERRUPT_PRO_UART1_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x098)
#define INTERRUPT_PRO_UART1_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_UART1_INTR_MAP_S 0

#define INTERRUPT_PRO_UART2_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x09C)
#define INTERRUPT_PRO_UART2_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_UART2_INTR_MAP_S 0

#define INTERRUPT_PRO_SDIO_HOST_INTERRUPT_MAP_REG (REG_INTERRUPT_BASE + 0x0A0)
#define INTERRUPT_PRO_SDIO_HOST_INTERRUPT_MAP 0x0000001F
#define INTERRUPT_PRO_SDIO_HOST_INTERRUPT_MAP_S 0

#define INTERRUPT_PRO_PWM0_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0A4)
#define INTERRUPT_PRO_PWM0_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PWM0_INTR_MAP_S 0

#define INTERRUPT_PRO_PWM1_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0A8)
#define INTERRUPT_PRO_PWM1_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PWM1_INTR_MAP_S 0

#define INTERRUPT_PRO_PWM2_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0AC)
#define INTERRUPT_PRO_PWM2_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PWM2_INTR_MAP_S 0

#define INTERRUPT_PRO_PWM3_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0B0)
#define INTERRUPT_PRO_PWM3_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PWM3_INTR_MAP_S 0

#define INTERRUPT_PRO_LEDC_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0B4)
#define INTERRUPT_PRO_LEDC_INT_MAP 0x0000001F
#define INTERRUPT_PRO_LEDC_INT_MAP_S 0

#define INTERRUPT_PRO_EFUSE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0B8)
#define INTERRUPT_PRO_EFUSE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_EFUSE_INT_MAP_S 0

#define INTERRUPT_PRO_CAN_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0BC)
#define INTERRUPT_PRO_CAN_INT_MAP 0x0000001F
#define INTERRUPT_PRO_CAN_INT_MAP_S 0

#define INTERRUPT_PRO_USB_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0C0)
#define INTERRUPT_PRO_USB_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_USB_INTR_MAP_S 0

#define INTERRUPT_PRO_RTC_CORE_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0C4)
#define INTERRUPT_PRO_RTC_CORE_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_RTC_CORE_INTR_MAP_S 0

#define INTERRUPT_PRO_RMT_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0C8)
#define INTERRUPT_PRO_RMT_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_RMT_INTR_MAP_S 0

#define INTERRUPT_PRO_PCNT_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0CC)
#define INTERRUPT_PRO_PCNT_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PCNT_INTR_MAP_S 0

#define INTERRUPT_PRO_I2C_EXT0_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0D0)
#define INTERRUPT_PRO_I2C_EXT0_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_I2C_EXT0_INTR_MAP_S 0

#define INTERRUPT_PRO_I2C_EXT1_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0D4)
#define INTERRUPT_PRO_I2C_EXT1_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_I2C_EXT1_INTR_MAP_S 0

#define INTERRUPT_PRO_RSA_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x0D8)
#define INTERRUPT_PRO_RSA_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_RSA_INTR_MAP_S 0

#define INTERRUPT_PRO_SPI1_DMA_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0DC)
#define INTERRUPT_PRO_SPI1_DMA_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SPI1_DMA_INT_MAP_S 0

#define INTERRUPT_PRO_SPI2_DMA_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0E0)
#define INTERRUPT_PRO_SPI2_DMA_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SPI2_DMA_INT_MAP_S 0

#define INTERRUPT_PRO_SPI3_DMA_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0E4)
#define INTERRUPT_PRO_SPI3_DMA_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SPI3_DMA_INT_MAP_S 0

#define INTERRUPT_PRO_WDG_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0E8)
#define INTERRUPT_PRO_WDG_INT_MAP 0x0000001F
#define INTERRUPT_PRO_WDG_INT_MAP_S 0

#define INTERRUPT_PRO_TIMER_INT1_MAP_REG (REG_INTERRUPT_BASE + 0x0EC)
#define INTERRUPT_PRO_TIMER_INT1_MAP 0x0000001F
#define INTERRUPT_PRO_TIMER_INT1_MAP_S 0

#define INTERRUPT_PRO_TIMER_INT2_MAP_REG (REG_INTERRUPT_BASE + 0x0F0)
#define INTERRUPT_PRO_TIMER_INT2_MAP 0x0000001F
#define INTERRUPT_PRO_TIMER_INT2_MAP_S 0

#define INTERRUPT_PRO_TG_T0_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0F4)
#define INTERRUPT_PRO_TG_T0_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_T0_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG_T1_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0F8)
#define INTERRUPT_PRO_TG_T1_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_T1_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG_WDT_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x0FC)
#define INTERRUPT_PRO_TG_WDT_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_WDT_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG_LACT_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x100)
#define INTERRUPT_PRO_TG_LACT_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG_LACT_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_T0_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x104)
#define INTERRUPT_PRO_TG1_T0_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_T0_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_T1_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x108)
#define INTERRUPT_PRO_TG1_T1_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_T1_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_WDT_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x10C)
#define INTERRUPT_PRO_TG1_WDT_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_WDT_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_TG1_LACT_EDGE_INT_MAP_REG (REG_INTERRUPT_BASE + 0x110)
#define INTERRUPT_PRO_TG1_LACT_EDGE_INT_MAP 0x0000001F
#define INTERRUPT_PRO_TG1_LACT_EDGE_INT_MAP_S 0

#define INTERRUPT_PRO_CACHE_IA_INT_MAP_REG (REG_INTERRUPT_BASE + 0x114)
#define INTERRUPT_PRO_CACHE_IA_INT_MAP 0x0000001F
#define INTERRUPT_PRO_CACHE_IA_INT_MAP_S 0

#define INTERRUPT_PRO_SYSTIMER_TARGET0_INT_MAP_REG (REG_INTERRUPT_BASE + 0x118)
#define INTERRUPT_PRO_SYSTIMER_TARGET0_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SYSTIMER_TARGET0_INT_MAP_S 0

#define INTERRUPT_PRO_SYSTIMER_TARGET1_INT_MAP_REG (REG_INTERRUPT_BASE + 0x11C)
#define INTERRUPT_PRO_SYSTIMER_TARGET1_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SYSTIMER_TARGET1_INT_MAP_S 0

#define INTERRUPT_PRO_SYSTIMER_TARGET2_INT_MAP_REG (REG_INTERRUPT_BASE + 0x120)
#define INTERRUPT_PRO_SYSTIMER_TARGET2_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SYSTIMER_TARGET2_INT_MAP_S 0

#define INTERRUPT_PRO_ASSIST_DEBUG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x124)
#define INTERRUPT_PRO_ASSIST_DEBUG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_ASSIST_DEBUG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_PRO_IRAM0_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x128)
#define INTERRUPT_PRO_PMS_PRO_IRAM0_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_PRO_IRAM0_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_PRO_DRAM0_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x12C)
#define INTERRUPT_PRO_PMS_PRO_DRAM0_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_PRO_DRAM0_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_PRO_DPORT_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x130)
#define INTERRUPT_PRO_PMS_PRO_DPORT_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_PRO_DPORT_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_PRO_AHB_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x134)
#define INTERRUPT_PRO_PMS_PRO_AHB_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_PRO_AHB_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_PRO_CACHE_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x138)
#define INTERRUPT_PRO_PMS_PRO_CACHE_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_PRO_CACHE_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_DMA_APB_I_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x13C)
#define INTERRUPT_PRO_PMS_DMA_APB_I_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_DMA_APB_I_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_DMA_RX_I_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x140)
#define INTERRUPT_PRO_PMS_DMA_RX_I_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_DMA_RX_I_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_PMS_DMA_TX_I_ILG_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x144)
#define INTERRUPT_PRO_PMS_DMA_TX_I_ILG_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_PMS_DMA_TX_I_ILG_INTR_MAP_S 0

#define INTERRUPT_PRO_SPI0_REJECT_CACHE_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x148)
#define INTERRUPT_PRO_SPI0_REJECT_CACHE_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_SPI0_REJECT_CACHE_INTR_MAP_S 0

#define INTERRUPT_PRO_SPI1_REJECT_CPU_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x14C)
#define INTERRUPT_PRO_SPI1_REJECT_CPU_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_SPI1_REJECT_CPU_INTR_MAP_S 0

#define INTERRUPT_PRO_DMA_COPY_INTR_MAP_REG (REG_INTERRUPT_BASE + 0x150)
#define INTERRUPT_PRO_DMA_COPY_INTR_MAP 0x0000001F
#define INTERRUPT_PRO_DMA_COPY_INTR_MAP_S 0

#define INTERRUPT_PRO_SPI4_DMA_INT_MAP_REG (REG_INTERRUPT_BASE + 0x154)
#define INTERRUPT_PRO_SPI4_DMA_INT_MAP 0x0000001F
#define INTERRUPT_PRO_SPI4_DMA_INT_MAP_S 0

#define INTERRUPT_PRO_SPI_INTR_4_MAP_REG (REG_INTERRUPT_BASE + 0x158)
#define INTERRUPT_PRO_SPI_INTR_4_MAP 0x0000001F
#define INTERRUPT_PRO_SPI_INTR_4_MAP_S 0

#define INTERRUPT_PRO_DCACHE_PRELOAD_INT_MAP_REG (REG_INTERRUPT_BASE + 0x15C)
#define INTERRUPT_PRO_DCACHE_PRELOAD_INT_MAP 0x0000001F
#define INTERRUPT_PRO_DCACHE_PRELOAD_INT_MAP_S 0

#define INTERRUPT_PRO_ICACHE_PRELOAD_INT_MAP_REG (REG_INTERRUPT_BASE + 0x160)
#define INTERRUPT_PRO_ICACHE_PRELOAD_INT_MAP 0x0000001F
#define INTERRUPT_PRO_ICACHE_PRELOAD_INT_MAP_S 0

#define INTERRUPT_PRO_INTR_STATUS_REG_0_REG (REG_INTERRUPT_BASE + 0x164)
#define INTERRUPT_PRO_INTR_STATUS_0 0xFFFFFFFF
#define INTERRUPT_PRO_INTR_STATUS_0_S 0

#define INTERRUPT_PRO_INTR_STATUS_REG_1_REG (REG_INTERRUPT_BASE + 0x168)
#define INTERRUPT_PRO_INTR_STATUS_1 0xFFFFFFFF
#define INTERRUPT_PRO_INTR_STATUS_1_S 0

#define INTERRUPT_PRO_INTR_STATUS_REG_2_REG (REG_INTERRUPT_BASE + 0x16C)
#define INTERRUPT_PRO_INTR_STATUS_2 0xFFFFFFFF
#define INTERRUPT_PRO_INTR_STATUS_2_S 0

#define INTERRUPT_CLOCK_GATE_REG (REG_INTERRUPT_BASE + 0x170)
#define INTERRUPT_PRO_NMI_MASK_HW (BIT(1))
#define INTERRUPT_PRO_NMI_MASK_HW_S 1
#define INTERRUPT_CLK_EN (BIT(0))
#define INTERRUPT_CLK_EN_S 0

#define INTERRUPT_REG_DATE_REG (REG_INTERRUPT_BASE + 0xFFC)
#define INTERRUPT_DATE 0x0FFFFFFF
#define INTERRUPT_DATE_S 0
#define INTERRUPT_DATE_VERSION 0x1810250
