
#define LEDC_LSCH0_CONF0_REG (REG_LEDC_BASE + 0x0000)
#define LEDC_CLK_EN (BIT(31))
#define LEDC_CLK_EN_S 31
#define LEDC_OVF_CNT_RESET_ST_LSCH0 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH0_S 17
#define LEDC_OVF_CNT_RESET_LSCH0 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH0_S 16
#define LEDC_OVF_CNT_EN_LSCH0 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH0_S 15
#define LEDC_OVF_NUM_LSCH0 0x000003FF
#define LEDC_OVF_NUM_LSCH0_S 5
#define LEDC_PARA_UP_LSCH0 (BIT(4))
#define LEDC_PARA_UP_LSCH0_S 4
#define LEDC_IDLE_LV_LSCH0 (BIT(3))
#define LEDC_IDLE_LV_LSCH0_S 3
#define LEDC_SIG_OUT_EN_LSCH0 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH0_S 2
#define LEDC_TIMER_SEL_LSCH0 0x00000003
#define LEDC_TIMER_SEL_LSCH0_S 0

#define LEDC_LSCH0_HPOINT_REG (REG_LEDC_BASE + 0x0004)
#define LEDC_HPOINT_LSCH0 0x00003FFF
#define LEDC_HPOINT_LSCH0_S 0

#define LEDC_LSCH0_DUTY_REG (REG_LEDC_BASE + 0x0008)
#define LEDC_DUTY_LSCH0 0x0007FFFF
#define LEDC_DUTY_LSCH0_S 0

#define LEDC_LSCH0_CONF1_REG (REG_LEDC_BASE + 0x000C)
#define LEDC_DUTY_START_LSCH0 (BIT(31))
#define LEDC_DUTY_START_LSCH0_S 31
#define LEDC_DUTY_INC_LSCH0 (BIT(30))
#define LEDC_DUTY_INC_LSCH0_S 30
#define LEDC_DUTY_NUM_LSCH0 0x000003FF
#define LEDC_DUTY_NUM_LSCH0_S 20
#define LEDC_DUTY_CYCLE_LSCH0 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH0_S 10
#define LEDC_DUTY_SCALE_LSCH0 0x000003FF
#define LEDC_DUTY_SCALE_LSCH0_S 0

#define LEDC_LSCH0_DUTY_R_REG (REG_LEDC_BASE + 0x0010)
#define LEDC_DUTY_LSCH0 0x0007FFFF
#define LEDC_DUTY_LSCH0_S 0

#define LEDC_LSCH1_CONF0_REG (REG_LEDC_BASE + 0x0014)
#define LEDC_OVF_CNT_RESET_ST_LSCH1 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH1_S 17
#define LEDC_OVF_CNT_RESET_LSCH1 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH1_S 16
#define LEDC_OVF_CNT_EN_LSCH1 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH1_S 15
#define LEDC_OVF_NUM_LSCH1 0x000003FF
#define LEDC_OVF_NUM_LSCH1_S 5
#define LEDC_PARA_UP_LSCH1 (BIT(4))
#define LEDC_PARA_UP_LSCH1_S 4
#define LEDC_IDLE_LV_LSCH1 (BIT(3))
#define LEDC_IDLE_LV_LSCH1_S 3
#define LEDC_SIG_OUT_EN_LSCH1 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH1_S 2
#define LEDC_TIMER_SEL_LSCH1 0x00000003
#define LEDC_TIMER_SEL_LSCH1_S 0

#define LEDC_LSCH1_HPOINT_REG (REG_LEDC_BASE + 0x0018)
#define LEDC_HPOINT_LSCH1 0x00003FFF
#define LEDC_HPOINT_LSCH1_S 0

#define LEDC_LSCH1_DUTY_REG (REG_LEDC_BASE + 0x001C)
#define LEDC_DUTY_LSCH1 0x0007FFFF
#define LEDC_DUTY_LSCH1_S 0

#define LEDC_LSCH1_CONF1_REG (REG_LEDC_BASE + 0x0020)
#define LEDC_DUTY_START_LSCH1 (BIT(31))
#define LEDC_DUTY_START_LSCH1_S 31
#define LEDC_DUTY_INC_LSCH1 (BIT(30))
#define LEDC_DUTY_INC_LSCH1_S 30
#define LEDC_DUTY_NUM_LSCH1 0x000003FF
#define LEDC_DUTY_NUM_LSCH1_S 20
#define LEDC_DUTY_CYCLE_LSCH1 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH1_S 10
#define LEDC_DUTY_SCALE_LSCH1 0x000003FF
#define LEDC_DUTY_SCALE_LSCH1_S 0

#define LEDC_LSCH1_DUTY_R_REG (REG_LEDC_BASE + 0x0024)
#define LEDC_DUTY_LSCH1 0x0007FFFF
#define LEDC_DUTY_LSCH1_S 0

#define LEDC_LSCH2_CONF0_REG (REG_LEDC_BASE + 0x0028)
#define LEDC_OVF_CNT_RESET_ST_LSCH2 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH2_S 17
#define LEDC_OVF_CNT_RESET_LSCH2 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH2_S 16
#define LEDC_OVF_CNT_EN_LSCH2 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH2_S 15
#define LEDC_OVF_NUM_LSCH2 0x000003FF
#define LEDC_OVF_NUM_LSCH2_S 5
#define LEDC_PARA_UP_LSCH2 (BIT(4))
#define LEDC_PARA_UP_LSCH2_S 4
#define LEDC_IDLE_LV_LSCH2 (BIT(3))
#define LEDC_IDLE_LV_LSCH2_S 3
#define LEDC_SIG_OUT_EN_LSCH2 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH2_S 2
#define LEDC_TIMER_SEL_LSCH2 0x00000003
#define LEDC_TIMER_SEL_LSCH2_S 0

#define LEDC_LSCH2_HPOINT_REG (REG_LEDC_BASE + 0x002C)
#define LEDC_HPOINT_LSCH2 0x00003FFF
#define LEDC_HPOINT_LSCH2_S 0

#define LEDC_LSCH2_DUTY_REG (REG_LEDC_BASE + 0x0030)
#define LEDC_DUTY_LSCH2 0x0007FFFF
#define LEDC_DUTY_LSCH2_S 0

#define LEDC_LSCH2_CONF1_REG (REG_LEDC_BASE + 0x0034)
#define LEDC_DUTY_START_LSCH2 (BIT(31))
#define LEDC_DUTY_START_LSCH2_S 31
#define LEDC_DUTY_INC_LSCH2 (BIT(30))
#define LEDC_DUTY_INC_LSCH2_S 30
#define LEDC_DUTY_NUM_LSCH2 0x000003FF
#define LEDC_DUTY_NUM_LSCH2_S 20
#define LEDC_DUTY_CYCLE_LSCH2 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH2_S 10
#define LEDC_DUTY_SCALE_LSCH2 0x000003FF
#define LEDC_DUTY_SCALE_LSCH2_S 0

#define LEDC_LSCH2_DUTY_R_REG (REG_LEDC_BASE + 0x0038)
#define LEDC_DUTY_LSCH2 0x0007FFFF
#define LEDC_DUTY_LSCH2_S 0

#define LEDC_LSCH3_CONF0_REG (REG_LEDC_BASE + 0x003C)
#define LEDC_OVF_CNT_RESET_ST_LSCH3 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH3_S 17
#define LEDC_OVF_CNT_RESET_LSCH3 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH3_S 16
#define LEDC_OVF_CNT_EN_LSCH3 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH3_S 15
#define LEDC_OVF_NUM_LSCH3 0x000003FF
#define LEDC_OVF_NUM_LSCH3_S 5
#define LEDC_PARA_UP_LSCH3 (BIT(4))
#define LEDC_PARA_UP_LSCH3_S 4
#define LEDC_IDLE_LV_LSCH3 (BIT(3))
#define LEDC_IDLE_LV_LSCH3_S 3
#define LEDC_SIG_OUT_EN_LSCH3 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH3_S 2
#define LEDC_TIMER_SEL_LSCH3 0x00000003
#define LEDC_TIMER_SEL_LSCH3_S 0

#define LEDC_LSCH3_HPOINT_REG (REG_LEDC_BASE + 0x0040)
#define LEDC_HPOINT_LSCH3 0x00003FFF
#define LEDC_HPOINT_LSCH3_S 0

#define LEDC_LSCH3_DUTY_REG (REG_LEDC_BASE + 0x0044)
#define LEDC_DUTY_LSCH3 0x0007FFFF
#define LEDC_DUTY_LSCH3_S 0

#define LEDC_LSCH3_CONF1_REG (REG_LEDC_BASE + 0x0048)
#define LEDC_DUTY_START_LSCH3 (BIT(31))
#define LEDC_DUTY_START_LSCH3_S 31
#define LEDC_DUTY_INC_LSCH3 (BIT(30))
#define LEDC_DUTY_INC_LSCH3_S 30
#define LEDC_DUTY_NUM_LSCH3 0x000003FF
#define LEDC_DUTY_NUM_LSCH3_S 20
#define LEDC_DUTY_CYCLE_LSCH3 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH3_S 10
#define LEDC_DUTY_SCALE_LSCH3 0x000003FF
#define LEDC_DUTY_SCALE_LSCH3_S 0

#define LEDC_LSCH3_DUTY_R_REG (REG_LEDC_BASE + 0x004C)
#define LEDC_DUTY_LSCH3 0x0007FFFF
#define LEDC_DUTY_LSCH3_S 0

#define LEDC_LSCH4_CONF0_REG (REG_LEDC_BASE + 0x0050)
#define LEDC_OVF_CNT_RESET_ST_LSCH4 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH4_S 17
#define LEDC_OVF_CNT_RESET_LSCH4 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH4_S 16
#define LEDC_OVF_CNT_EN_LSCH4 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH4_S 15
#define LEDC_OVF_NUM_LSCH4 0x000003FF
#define LEDC_OVF_NUM_LSCH4_S 5
#define LEDC_PARA_UP_LSCH4 (BIT(4))
#define LEDC_PARA_UP_LSCH4_S 4
#define LEDC_IDLE_LV_LSCH4 (BIT(3))
#define LEDC_IDLE_LV_LSCH4_S 3
#define LEDC_SIG_OUT_EN_LSCH4 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH4_S 2
#define LEDC_TIMER_SEL_LSCH4 0x00000003
#define LEDC_TIMER_SEL_LSCH4_S 0

#define LEDC_LSCH4_HPOINT_REG (REG_LEDC_BASE + 0x0054)
#define LEDC_HPOINT_LSCH4 0x00003FFF
#define LEDC_HPOINT_LSCH4_S 0

#define LEDC_LSCH4_DUTY_REG (REG_LEDC_BASE + 0x0058)
#define LEDC_DUTY_LSCH4 0x0007FFFF
#define LEDC_DUTY_LSCH4_S 0

#define LEDC_LSCH4_CONF1_REG (REG_LEDC_BASE + 0x005C)
#define LEDC_DUTY_START_LSCH4 (BIT(31))
#define LEDC_DUTY_START_LSCH4_S 31
#define LEDC_DUTY_INC_LSCH4 (BIT(30))
#define LEDC_DUTY_INC_LSCH4_S 30
#define LEDC_DUTY_NUM_LSCH4 0x000003FF
#define LEDC_DUTY_NUM_LSCH4_S 20
#define LEDC_DUTY_CYCLE_LSCH4 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH4_S 10
#define LEDC_DUTY_SCALE_LSCH4 0x000003FF
#define LEDC_DUTY_SCALE_LSCH4_S 0

#define LEDC_LSCH4_DUTY_R_REG (REG_LEDC_BASE + 0x0060)
#define LEDC_DUTY_LSCH4 0x0007FFFF
#define LEDC_DUTY_LSCH4_S 0

#define LEDC_LSCH5_CONF0_REG (REG_LEDC_BASE + 0x0064)
#define LEDC_OVF_CNT_RESET_ST_LSCH5 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH5_S 17
#define LEDC_OVF_CNT_RESET_LSCH5 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH5_S 16
#define LEDC_OVF_CNT_EN_LSCH5 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH5_S 15
#define LEDC_OVF_NUM_LSCH5 0x000003FF
#define LEDC_OVF_NUM_LSCH5_S 5
#define LEDC_PARA_UP_LSCH5 (BIT(4))
#define LEDC_PARA_UP_LSCH5_S 4
#define LEDC_IDLE_LV_LSCH5 (BIT(3))
#define LEDC_IDLE_LV_LSCH5_S 3
#define LEDC_SIG_OUT_EN_LSCH5 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH5_S 2
#define LEDC_TIMER_SEL_LSCH5 0x00000003
#define LEDC_TIMER_SEL_LSCH5_S 0

#define LEDC_LSCH5_HPOINT_REG (REG_LEDC_BASE + 0x0068)
#define LEDC_HPOINT_LSCH5 0x00003FFF
#define LEDC_HPOINT_LSCH5_S 0

#define LEDC_LSCH5_DUTY_REG (REG_LEDC_BASE + 0x006C)
#define LEDC_DUTY_LSCH5 0x0007FFFF
#define LEDC_DUTY_LSCH5_S 0

#define LEDC_LSCH5_CONF1_REG (REG_LEDC_BASE + 0x0070)
#define LEDC_DUTY_START_LSCH5 (BIT(31))
#define LEDC_DUTY_START_LSCH5_S 31
#define LEDC_DUTY_INC_LSCH5 (BIT(30))
#define LEDC_DUTY_INC_LSCH5_S 30
#define LEDC_DUTY_NUM_LSCH5 0x000003FF
#define LEDC_DUTY_NUM_LSCH5_S 20
#define LEDC_DUTY_CYCLE_LSCH5 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH5_S 10
#define LEDC_DUTY_SCALE_LSCH5 0x000003FF
#define LEDC_DUTY_SCALE_LSCH5_S 0

#define LEDC_LSCH5_DUTY_R_REG (REG_LEDC_BASE + 0x0074)
#define LEDC_DUTY_LSCH5 0x0007FFFF
#define LEDC_DUTY_LSCH5_S 0

#define LEDC_LSCH6_CONF0_REG (REG_LEDC_BASE + 0x0078)
#define LEDC_OVF_CNT_RESET_ST_LSCH6 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH6_S 17
#define LEDC_OVF_CNT_RESET_LSCH6 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH6_S 16
#define LEDC_OVF_CNT_EN_LSCH6 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH6_S 15
#define LEDC_OVF_NUM_LSCH6 0x000003FF
#define LEDC_OVF_NUM_LSCH6_S 5
#define LEDC_PARA_UP_LSCH6 (BIT(4))
#define LEDC_PARA_UP_LSCH6_S 4
#define LEDC_IDLE_LV_LSCH6 (BIT(3))
#define LEDC_IDLE_LV_LSCH6_S 3
#define LEDC_SIG_OUT_EN_LSCH6 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH6_S 2
#define LEDC_TIMER_SEL_LSCH6 0x00000003
#define LEDC_TIMER_SEL_LSCH6_S 0

#define LEDC_LSCH6_HPOINT_REG (REG_LEDC_BASE + 0x007C)
#define LEDC_HPOINT_LSCH6 0x00003FFF
#define LEDC_HPOINT_LSCH6_S 0

#define LEDC_LSCH6_DUTY_REG (REG_LEDC_BASE + 0x0080)
#define LEDC_DUTY_LSCH6 0x0007FFFF
#define LEDC_DUTY_LSCH6_S 0

#define LEDC_LSCH6_CONF1_REG (REG_LEDC_BASE + 0x0084)
#define LEDC_DUTY_START_LSCH6 (BIT(31))
#define LEDC_DUTY_START_LSCH6_S 31
#define LEDC_DUTY_INC_LSCH6 (BIT(30))
#define LEDC_DUTY_INC_LSCH6_S 30
#define LEDC_DUTY_NUM_LSCH6 0x000003FF
#define LEDC_DUTY_NUM_LSCH6_S 20
#define LEDC_DUTY_CYCLE_LSCH6 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH6_S 10
#define LEDC_DUTY_SCALE_LSCH6 0x000003FF
#define LEDC_DUTY_SCALE_LSCH6_S 0

#define LEDC_LSCH6_DUTY_R_REG (REG_LEDC_BASE + 0x0088)
#define LEDC_DUTY_LSCH6 0x0007FFFF
#define LEDC_DUTY_LSCH6_S 0

#define LEDC_LSCH7_CONF0_REG (REG_LEDC_BASE + 0x008C)
#define LEDC_OVF_CNT_RESET_ST_LSCH7 (BIT(17))
#define LEDC_OVF_CNT_RESET_ST_LSCH7_S 17
#define LEDC_OVF_CNT_RESET_LSCH7 (BIT(16))
#define LEDC_OVF_CNT_RESET_LSCH7_S 16
#define LEDC_OVF_CNT_EN_LSCH7 (BIT(15))
#define LEDC_OVF_CNT_EN_LSCH7_S 15
#define LEDC_OVF_NUM_LSCH7 0x000003FF
#define LEDC_OVF_NUM_LSCH7_S 5
#define LEDC_PARA_UP_LSCH7 (BIT(4))
#define LEDC_PARA_UP_LSCH7_S 4
#define LEDC_IDLE_LV_LSCH7 (BIT(3))
#define LEDC_IDLE_LV_LSCH7_S 3
#define LEDC_SIG_OUT_EN_LSCH7 (BIT(2))
#define LEDC_SIG_OUT_EN_LSCH7_S 2
#define LEDC_TIMER_SEL_LSCH7 0x00000003
#define LEDC_TIMER_SEL_LSCH7_S 0

#define LEDC_LSCH7_HPOINT_REG (REG_LEDC_BASE + 0x0090)
#define LEDC_HPOINT_LSCH7 0x00003FFF
#define LEDC_HPOINT_LSCH7_S 0

#define LEDC_LSCH7_DUTY_REG (REG_LEDC_BASE + 0x0094)
#define LEDC_DUTY_LSCH7 0x0007FFFF
#define LEDC_DUTY_LSCH7_S 0

#define LEDC_LSCH7_CONF1_REG (REG_LEDC_BASE + 0x0098)
#define LEDC_DUTY_START_LSCH7 (BIT(31))
#define LEDC_DUTY_START_LSCH7_S 31
#define LEDC_DUTY_INC_LSCH7 (BIT(30))
#define LEDC_DUTY_INC_LSCH7_S 30
#define LEDC_DUTY_NUM_LSCH7 0x000003FF
#define LEDC_DUTY_NUM_LSCH7_S 20
#define LEDC_DUTY_CYCLE_LSCH7 0x000003FF
#define LEDC_DUTY_CYCLE_LSCH7_S 10
#define LEDC_DUTY_SCALE_LSCH7 0x000003FF
#define LEDC_DUTY_SCALE_LSCH7_S 0

#define LEDC_LSCH7_DUTY_R_REG (REG_LEDC_BASE + 0x009C)
#define LEDC_DUTY_LSCH7 0x0007FFFF
#define LEDC_DUTY_LSCH7_S 0

#define LEDC_LSTIMER0_CONF_REG (REG_LEDC_BASE + 0x00a0)
#define LEDC_LSTIMER0_PARA_UP (BIT(25))
#define LEDC_LSTIMER0_PARA_UP_S 25
#define LEDC_TICK_SEL_LSTIMER0 (BIT(24))
#define LEDC_TICK_SEL_LSTIMER0_S 24
#define LEDC_LSTIMER0_RST (BIT(23))
#define LEDC_LSTIMER0_RST_S 23
#define LEDC_LSTIMER0_PAUSE (BIT(22))
#define LEDC_LSTIMER0_PAUSE_S 22
#define LEDC_CLK_DIV_LSTIMER0 0x0003FFFF
#define LEDC_CLK_DIV_LSTIMER0_S 4
#define LEDC_LSTIMER0_DUTY_RES 0x0000000F
#define LEDC_LSTIMER0_DUTY_RES_S 0

#define LEDC_LSTIMER0_VALUE_REG (REG_LEDC_BASE + 0x00a4)
#define LEDC_LSTIMER0_CNT 0x00003FFF
#define LEDC_LSTIMER0_CNT_S 0

#define LEDC_LSTIMER1_CONF_REG (REG_LEDC_BASE + 0x00a8)
#define LEDC_LSTIMER1_PARA_UP (BIT(25))
#define LEDC_LSTIMER1_PARA_UP_S 25
#define LEDC_TICK_SEL_LSTIMER1 (BIT(24))
#define LEDC_TICK_SEL_LSTIMER1_S 24
#define LEDC_LSTIMER1_RST (BIT(23))
#define LEDC_LSTIMER1_RST_S 23
#define LEDC_LSTIMER1_PAUSE (BIT(22))
#define LEDC_LSTIMER1_PAUSE_S 22
#define LEDC_CLK_DIV_LSTIMER1 0x0003FFFF
#define LEDC_CLK_DIV_LSTIMER1_S 4
#define LEDC_LSTIMER1_DUTY_RES 0x0000000F
#define LEDC_LSTIMER1_DUTY_RES_S 0

#define LEDC_LSTIMER1_VALUE_REG (REG_LEDC_BASE + 0x00aC)
#define LEDC_LSTIMER1_CNT 0x00003FFF
#define LEDC_LSTIMER1_CNT_S 0

#define LEDC_LSTIMER2_CONF_REG (REG_LEDC_BASE + 0x00b0)
#define LEDC_LSTIMER2_PARA_UP (BIT(25))
#define LEDC_LSTIMER2_PARA_UP_S 25
#define LEDC_TICK_SEL_LSTIMER2 (BIT(24))
#define LEDC_TICK_SEL_LSTIMER2_S 24
#define LEDC_LSTIMER2_RST (BIT(23))
#define LEDC_LSTIMER2_RST_S 23
#define LEDC_LSTIMER2_PAUSE (BIT(22))
#define LEDC_LSTIMER2_PAUSE_S 22
#define LEDC_CLK_DIV_LSTIMER2 0x0003FFFF
#define LEDC_CLK_DIV_LSTIMER2_S 4
#define LEDC_LSTIMER2_DUTY_RES 0x0000000F
#define LEDC_LSTIMER2_DUTY_RES_S 0

#define LEDC_LSTIMER2_VALUE_REG (REG_LEDC_BASE + 0x00b4)
#define LEDC_LSTIMER2_CNT 0x00003FFF
#define LEDC_LSTIMER2_CNT_S 0

#define LEDC_LSTIMER3_CONF_REG (REG_LEDC_BASE + 0x00b8)
#define LEDC_LSTIMER3_PARA_UP (BIT(25))
#define LEDC_LSTIMER3_PARA_UP_S 25
#define LEDC_TICK_SEL_LSTIMER3 (BIT(24))
#define LEDC_TICK_SEL_LSTIMER3_S 24
#define LEDC_LSTIMER3_RST (BIT(23))
#define LEDC_LSTIMER3_RST_S 23
#define LEDC_LSTIMER3_PAUSE (BIT(22))
#define LEDC_LSTIMER3_PAUSE_S 22
#define LEDC_CLK_DIV_LSTIMER3 0x0003FFFF
#define LEDC_CLK_DIV_LSTIMER3_S 4
#define LEDC_LSTIMER3_DUTY_RES 0x0000000F
#define LEDC_LSTIMER3_DUTY_RES_S 0

#define LEDC_LSTIMER3_VALUE_REG (REG_LEDC_BASE + 0x00bC)
#define LEDC_LSTIMER3_CNT 0x00003FFF
#define LEDC_LSTIMER3_CNT_S 0

#define LEDC_INT_RAW_REG (REG_LEDC_BASE + 0x00c0)
#define LEDC_OVF_CNT_LSCH7_INT_RAW (BIT(19))
#define LEDC_OVF_CNT_LSCH7_INT_RAW_S 19
#define LEDC_OVF_CNT_LSCH6_INT_RAW (BIT(18))
#define LEDC_OVF_CNT_LSCH6_INT_RAW_S 18
#define LEDC_OVF_CNT_LSCH5_INT_RAW (BIT(17))
#define LEDC_OVF_CNT_LSCH5_INT_RAW_S 17
#define LEDC_OVF_CNT_LSCH4_INT_RAW (BIT(16))
#define LEDC_OVF_CNT_LSCH4_INT_RAW_S 16
#define LEDC_OVF_CNT_LSCH3_INT_RAW (BIT(15))
#define LEDC_OVF_CNT_LSCH3_INT_RAW_S 15
#define LEDC_OVF_CNT_LSCH2_INT_RAW (BIT(14))
#define LEDC_OVF_CNT_LSCH2_INT_RAW_S 14
#define LEDC_OVF_CNT_LSCH1_INT_RAW (BIT(13))
#define LEDC_OVF_CNT_LSCH1_INT_RAW_S 13
#define LEDC_OVF_CNT_LSCH0_INT_RAW (BIT(12))
#define LEDC_OVF_CNT_LSCH0_INT_RAW_S 12
#define LEDC_DUTY_CHNG_END_LSCH7_INT_RAW (BIT(11))
#define LEDC_DUTY_CHNG_END_LSCH7_INT_RAW_S 11
#define LEDC_DUTY_CHNG_END_LSCH6_INT_RAW (BIT(10))
#define LEDC_DUTY_CHNG_END_LSCH6_INT_RAW_S 10
#define LEDC_DUTY_CHNG_END_LSCH5_INT_RAW (BIT(9))
#define LEDC_DUTY_CHNG_END_LSCH5_INT_RAW_S 9
#define LEDC_DUTY_CHNG_END_LSCH4_INT_RAW (BIT(8))
#define LEDC_DUTY_CHNG_END_LSCH4_INT_RAW_S 8
#define LEDC_DUTY_CHNG_END_LSCH3_INT_RAW (BIT(7))
#define LEDC_DUTY_CHNG_END_LSCH3_INT_RAW_S 7
#define LEDC_DUTY_CHNG_END_LSCH2_INT_RAW (BIT(6))
#define LEDC_DUTY_CHNG_END_LSCH2_INT_RAW_S 6
#define LEDC_DUTY_CHNG_END_LSCH1_INT_RAW (BIT(5))
#define LEDC_DUTY_CHNG_END_LSCH1_INT_RAW_S 5
#define LEDC_DUTY_CHNG_END_LSCH0_INT_RAW (BIT(4))
#define LEDC_DUTY_CHNG_END_LSCH0_INT_RAW_S 4
#define LEDC_LSTIMER3_OVF_INT_RAW (BIT(3))
#define LEDC_LSTIMER3_OVF_INT_RAW_S 3
#define LEDC_LSTIMER2_OVF_INT_RAW (BIT(2))
#define LEDC_LSTIMER2_OVF_INT_RAW_S 2
#define LEDC_LSTIMER1_OVF_INT_RAW (BIT(1))
#define LEDC_LSTIMER1_OVF_INT_RAW_S 1
#define LEDC_LSTIMER0_OVF_INT_RAW (BIT(0))
#define LEDC_LSTIMER0_OVF_INT_RAW_S 0

#define LEDC_INT_ST_REG (REG_LEDC_BASE + 0x00c4)
#define LEDC_OVF_CNT_LSCH7_INT_ST (BIT(19))
#define LEDC_OVF_CNT_LSCH7_INT_ST_S 19
#define LEDC_OVF_CNT_LSCH6_INT_ST (BIT(18))
#define LEDC_OVF_CNT_LSCH6_INT_ST_S 18
#define LEDC_OVF_CNT_LSCH5_INT_ST (BIT(17))
#define LEDC_OVF_CNT_LSCH5_INT_ST_S 17
#define LEDC_OVF_CNT_LSCH4_INT_ST (BIT(16))
#define LEDC_OVF_CNT_LSCH4_INT_ST_S 16
#define LEDC_OVF_CNT_LSCH3_INT_ST (BIT(15))
#define LEDC_OVF_CNT_LSCH3_INT_ST_S 15
#define LEDC_OVF_CNT_LSCH2_INT_ST (BIT(14))
#define LEDC_OVF_CNT_LSCH2_INT_ST_S 14
#define LEDC_OVF_CNT_LSCH1_INT_ST (BIT(13))
#define LEDC_OVF_CNT_LSCH1_INT_ST_S 13
#define LEDC_OVF_CNT_LSCH0_INT_ST (BIT(12))
#define LEDC_OVF_CNT_LSCH0_INT_ST_S 12
#define LEDC_DUTY_CHNG_END_LSCH7_INT_ST (BIT(11))
#define LEDC_DUTY_CHNG_END_LSCH7_INT_ST_S 11
#define LEDC_DUTY_CHNG_END_LSCH6_INT_ST (BIT(10))
#define LEDC_DUTY_CHNG_END_LSCH6_INT_ST_S 10
#define LEDC_DUTY_CHNG_END_LSCH5_INT_ST (BIT(9))
#define LEDC_DUTY_CHNG_END_LSCH5_INT_ST_S 9
#define LEDC_DUTY_CHNG_END_LSCH4_INT_ST (BIT(8))
#define LEDC_DUTY_CHNG_END_LSCH4_INT_ST_S 8
#define LEDC_DUTY_CHNG_END_LSCH3_INT_ST (BIT(7))
#define LEDC_DUTY_CHNG_END_LSCH3_INT_ST_S 7
#define LEDC_DUTY_CHNG_END_LSCH2_INT_ST (BIT(6))
#define LEDC_DUTY_CHNG_END_LSCH2_INT_ST_S 6
#define LEDC_DUTY_CHNG_END_LSCH1_INT_ST (BIT(5))
#define LEDC_DUTY_CHNG_END_LSCH1_INT_ST_S 5
#define LEDC_DUTY_CHNG_END_LSCH0_INT_ST (BIT(4))
#define LEDC_DUTY_CHNG_END_LSCH0_INT_ST_S 4
#define LEDC_LSTIMER3_OVF_INT_ST (BIT(3))
#define LEDC_LSTIMER3_OVF_INT_ST_S 3
#define LEDC_LSTIMER2_OVF_INT_ST (BIT(2))
#define LEDC_LSTIMER2_OVF_INT_ST_S 2
#define LEDC_LSTIMER1_OVF_INT_ST (BIT(1))
#define LEDC_LSTIMER1_OVF_INT_ST_S 1
#define LEDC_LSTIMER0_OVF_INT_ST (BIT(0))
#define LEDC_LSTIMER0_OVF_INT_ST_S 0

#define LEDC_INT_ENA_REG (REG_LEDC_BASE + 0x00c8)
#define LEDC_OVF_CNT_LSCH7_INT_ENA (BIT(19))
#define LEDC_OVF_CNT_LSCH7_INT_ENA_S 19
#define LEDC_OVF_CNT_LSCH6_INT_ENA (BIT(18))
#define LEDC_OVF_CNT_LSCH6_INT_ENA_S 18
#define LEDC_OVF_CNT_LSCH5_INT_ENA (BIT(17))
#define LEDC_OVF_CNT_LSCH5_INT_ENA_S 17
#define LEDC_OVF_CNT_LSCH4_INT_ENA (BIT(16))
#define LEDC_OVF_CNT_LSCH4_INT_ENA_S 16
#define LEDC_OVF_CNT_LSCH3_INT_ENA (BIT(15))
#define LEDC_OVF_CNT_LSCH3_INT_ENA_S 15
#define LEDC_OVF_CNT_LSCH2_INT_ENA (BIT(14))
#define LEDC_OVF_CNT_LSCH2_INT_ENA_S 14
#define LEDC_OVF_CNT_LSCH1_INT_ENA (BIT(13))
#define LEDC_OVF_CNT_LSCH1_INT_ENA_S 13
#define LEDC_OVF_CNT_LSCH0_INT_ENA (BIT(12))
#define LEDC_OVF_CNT_LSCH0_INT_ENA_S 12
#define LEDC_DUTY_CHNG_END_LSCH7_INT_ENA (BIT(11))
#define LEDC_DUTY_CHNG_END_LSCH7_INT_ENA_S 11
#define LEDC_DUTY_CHNG_END_LSCH6_INT_ENA (BIT(10))
#define LEDC_DUTY_CHNG_END_LSCH6_INT_ENA_S 10
#define LEDC_DUTY_CHNG_END_LSCH5_INT_ENA (BIT(9))
#define LEDC_DUTY_CHNG_END_LSCH5_INT_ENA_S 9
#define LEDC_DUTY_CHNG_END_LSCH4_INT_ENA (BIT(8))
#define LEDC_DUTY_CHNG_END_LSCH4_INT_ENA_S 8
#define LEDC_DUTY_CHNG_END_LSCH3_INT_ENA (BIT(7))
#define LEDC_DUTY_CHNG_END_LSCH3_INT_ENA_S 7
#define LEDC_DUTY_CHNG_END_LSCH2_INT_ENA (BIT(6))
#define LEDC_DUTY_CHNG_END_LSCH2_INT_ENA_S 6
#define LEDC_DUTY_CHNG_END_LSCH1_INT_ENA (BIT(5))
#define LEDC_DUTY_CHNG_END_LSCH1_INT_ENA_S 5
#define LEDC_DUTY_CHNG_END_LSCH0_INT_ENA (BIT(4))
#define LEDC_DUTY_CHNG_END_LSCH0_INT_ENA_S 4
#define LEDC_LSTIMER3_OVF_INT_ENA (BIT(3))
#define LEDC_LSTIMER3_OVF_INT_ENA_S 3
#define LEDC_LSTIMER2_OVF_INT_ENA (BIT(2))
#define LEDC_LSTIMER2_OVF_INT_ENA_S 2
#define LEDC_LSTIMER1_OVF_INT_ENA (BIT(1))
#define LEDC_LSTIMER1_OVF_INT_ENA_S 1
#define LEDC_LSTIMER0_OVF_INT_ENA (BIT(0))
#define LEDC_LSTIMER0_OVF_INT_ENA_S 0

#define LEDC_INT_CLR_REG (REG_LEDC_BASE + 0x00cC)
#define LEDC_OVF_CNT_LSCH7_INT_CLR (BIT(19))
#define LEDC_OVF_CNT_LSCH7_INT_CLR_S 19
#define LEDC_OVF_CNT_LSCH6_INT_CLR (BIT(18))
#define LEDC_OVF_CNT_LSCH6_INT_CLR_S 18
#define LEDC_OVF_CNT_LSCH5_INT_CLR (BIT(17))
#define LEDC_OVF_CNT_LSCH5_INT_CLR_S 17
#define LEDC_OVF_CNT_LSCH4_INT_CLR (BIT(16))
#define LEDC_OVF_CNT_LSCH4_INT_CLR_S 16
#define LEDC_OVF_CNT_LSCH3_INT_CLR (BIT(15))
#define LEDC_OVF_CNT_LSCH3_INT_CLR_S 15
#define LEDC_OVF_CNT_LSCH2_INT_CLR (BIT(14))
#define LEDC_OVF_CNT_LSCH2_INT_CLR_S 14
#define LEDC_OVF_CNT_LSCH1_INT_CLR (BIT(13))
#define LEDC_OVF_CNT_LSCH1_INT_CLR_S 13
#define LEDC_OVF_CNT_LSCH0_INT_CLR (BIT(12))
#define LEDC_OVF_CNT_LSCH0_INT_CLR_S 12
#define LEDC_DUTY_CHNG_END_LSCH7_INT_CLR (BIT(11))
#define LEDC_DUTY_CHNG_END_LSCH7_INT_CLR_S 11
#define LEDC_DUTY_CHNG_END_LSCH6_INT_CLR (BIT(10))
#define LEDC_DUTY_CHNG_END_LSCH6_INT_CLR_S 10
#define LEDC_DUTY_CHNG_END_LSCH5_INT_CLR (BIT(9))
#define LEDC_DUTY_CHNG_END_LSCH5_INT_CLR_S 9
#define LEDC_DUTY_CHNG_END_LSCH4_INT_CLR (BIT(8))
#define LEDC_DUTY_CHNG_END_LSCH4_INT_CLR_S 8
#define LEDC_DUTY_CHNG_END_LSCH3_INT_CLR (BIT(7))
#define LEDC_DUTY_CHNG_END_LSCH3_INT_CLR_S 7
#define LEDC_DUTY_CHNG_END_LSCH2_INT_CLR (BIT(6))
#define LEDC_DUTY_CHNG_END_LSCH2_INT_CLR_S 6
#define LEDC_DUTY_CHNG_END_LSCH1_INT_CLR (BIT(5))
#define LEDC_DUTY_CHNG_END_LSCH1_INT_CLR_S 5
#define LEDC_DUTY_CHNG_END_LSCH0_INT_CLR (BIT(4))
#define LEDC_DUTY_CHNG_END_LSCH0_INT_CLR_S 4
#define LEDC_LSTIMER3_OVF_INT_CLR (BIT(3))
#define LEDC_LSTIMER3_OVF_INT_CLR_S 3
#define LEDC_LSTIMER2_OVF_INT_CLR (BIT(2))
#define LEDC_LSTIMER2_OVF_INT_CLR_S 2
#define LEDC_LSTIMER1_OVF_INT_CLR (BIT(1))
#define LEDC_LSTIMER1_OVF_INT_CLR_S 1
#define LEDC_LSTIMER0_OVF_INT_CLR (BIT(0))
#define LEDC_LSTIMER0_OVF_INT_CLR_S 0

#define LEDC_CONF_REG (REG_LEDC_BASE + 0x00d0)
#define LEDC_APB_CLK_SEL 0x00000003
#define LEDC_APB_CLK_SEL_S 0

#define LEDC_DATE_REG (REG_LEDC_BASE + 0x00FC)
#define LEDC_DATE 0xFFFFFFFF
#define LEDC_DATE_S 0
#define LEDC_DATE_VERSION 0x18072700
