
#define WDEVTIME_REG (REG_WDEVPWR_BASE + 0x0000)
#define WDEV_MACTIME 0xFFFFFFFF
#define WDEV_MACTIME_S 0

#define WDEVEMAC_TIMER_NS_REG (REG_WDEVPWR_BASE + 0x0004)
#define WDEV_EMACTIMER_NS 0xFFFFFFFF
#define WDEV_EMACTIMER_NS_S 0

#define WDEVEMAC_TIMER_S_REG (REG_WDEVPWR_BASE + 0x0008)
#define WDEV_EMACTIMER_S 0xFFFFFFFF
#define WDEV_EMACTIMER_S_S 0

#define WDEVTIME_SW_REG (REG_WDEVPWR_BASE + 0x000C)
#define WDEV_MACTIME_SW 0xFFFFFFFF
#define WDEV_MACTIME_SW_S 0

#define WDEVTSF_OPTIONS_REG (REG_WDEVPWR_BASE + 0x0010)
#define WDEV_TSFBBTX_COMPEN 0x000000FF
#define WDEV_TSFBBTX_COMPEN_S 24
#define WDEV_TSFBBRX_COMPEN 0x000000FF
#define WDEV_TSFBBRX_COMPEN_S 16

#define WDEVTSF_TIME_FZ_REG (REG_WDEVPWR_BASE + 0x0014)
#define WDEV_MACSW_WR (BIT(10))
#define WDEV_MACSW_WR_S 10
#define WDEV_TSF3SW_WR (BIT(9))
#define WDEV_TSF3SW_WR_S 9
#define WDEV_TSF2SW_WR (BIT(8))
#define WDEV_TSF2SW_WR_S 8
#define WDEV_TSF1SW_WR (BIT(7))
#define WDEV_TSF1SW_WR_S 7
#define WDEV_TSF0SW_WR (BIT(6))
#define WDEV_TSF0SW_WR_S 6
#define WDEV_EMACTIME_FZ (BIT(5))
#define WDEV_EMACTIME_FZ_S 5
#define WDEV_TSF3TIME_FZ (BIT(3))
#define WDEV_TSF3TIME_FZ_S 3
#define WDEV_TSF2TIME_FZ (BIT(2))
#define WDEV_TSF2TIME_FZ_S 2
#define WDEV_TSF1TIME_FZ (BIT(1))
#define WDEV_TSF1TIME_FZ_S 1
#define WDEV_TSF0TIME_FZ (BIT(0))
#define WDEV_TSF0TIME_FZ_S 0

#define WDEVTSF0_TIME_LO_REG (REG_WDEVPWR_BASE + 0x0018)
#define WDEV_TSFTIME0_LO 0xFFFFFFFF
#define WDEV_TSFTIME0_LO_S 0

#define WDEVTSF0_TIME_HI_REG (REG_WDEVPWR_BASE + 0x001C)
#define WDEV_TSFTIME0_HI 0xFFFFFFFF
#define WDEV_TSFTIME0_HI_S 0

#define WDEVSLEEP_ST_REG (REG_WDEVPWR_BASE + 0x0020)
#define WDEV_MAC_UPBYRTC (BIT(25))
#define WDEV_MAC_UPBYRTC_S 25
#define WDEV_PWR_US_FIX 0x00000003
#define WDEV_PWR_US_FIX_S 23
#define WDEV_DIGCLK_DIV 0x0000007F
#define WDEV_DIGCLK_DIV_S 16
#define WDEV_WAKEUP_EARLY 0x0000FFFF
#define WDEV_WAKEUP_EARLY_S 0

#define WDEVSLEEP0_CONF_REG (REG_WDEVPWR_BASE + 0x0024)
#define WDEV_TSFUP0_ENA (BIT(31))
#define WDEV_TSFUP0_ENA_S 31
#define WDEV_TXBEACON0_ENA (BIT(30))
#define WDEV_TXBEACON0_ENA_S 30
#define WDEV_WAKEUP0_ENA (BIT(29))
#define WDEV_WAKEUP0_ENA_S 29
#define WDEV_TSF0RTCUP_ENA (BIT(28))
#define WDEV_TSF0RTCUP_ENA_S 28
#define WDEV_TSF0HWUP_ENA (BIT(27))
#define WDEV_TSF0HWUP_ENA_S 27
#define WDEV_BEACON_TARGET0_VALID (BIT(25))
#define WDEV_BEACON_TARGET0_VALID_S 25
#define WDEV_PWRCLK_EN (BIT(23))
#define WDEV_PWRCLK_EN_S 23

#define WDEVTSF0_ACTIVE_REG (REG_WDEVPWR_BASE + 0x0028)
#define WDEV_TSF0_ACTIVE_ST (BIT(1))
#define WDEV_TSF0_ACTIVE_ST_S 1
#define WDEV_TSF0_ACTIVE_CLR (BIT(0))
#define WDEV_TSF0_ACTIVE_CLR_S 0

#define WDEVTSFSW0_LO_REG (REG_WDEVPWR_BASE + 0x002C)
#define WDEV_TSFUPSW0_LO 0xFFFFFFFF
#define WDEV_TSFUPSW0_LO_S 0

#define WDEVTSFSW0_HI_REG (REG_WDEVPWR_BASE + 0x0030)
#define WDEV_TSFUPSW0_HI 0xFFFFFFFF
#define WDEV_TSFUPSW0_HI_S 0

#define WDEVBEACTAR0_LO_REG (REG_WDEVPWR_BASE + 0x0034)
#define WDEV_BEACSTART_TARGET0_LO 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET0_LO_S 0

#define WDEVBEACTAR0_HI_REG (REG_WDEVPWR_BASE + 0x0038)
#define WDEV_BEACSTART_TARGET0_HI 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET0_HI_S 0

#define WDEVBEATAR0_LO_REG (REG_WDEVPWR_BASE + 0x003C)
#define WDEV_BEACON_TARGET0_LO 0xFFFFFFFF
#define WDEV_BEACON_TARGET0_LO_S 0

#define WDEVBEATAR0_HI_REG (REG_WDEVPWR_BASE + 0x0040)
#define WDEV_BEACON_TARGET0_HI 0xFFFFFFFF
#define WDEV_BEACON_TARGET0_HI_S 0

#define WDEVBEA_CUR_TAR0_REG (REG_WDEVPWR_BASE + 0x0044)
#define WDEV_BEACON_CUR_TAR0 0xFFFFFFFF
#define WDEV_BEACON_CUR_TAR0_S 0

#define WDEVBEAINTER0_REG (REG_WDEVPWR_BASE + 0x0048)
#define WDEV_TBTT0_EARLY_TIME 0x0000FFFF
#define WDEV_TBTT0_EARLY_TIME_S 16
#define WDEV_TBTT0 0x0000FFFF
#define WDEV_TBTT0_S 0

#define WDEVTSF1_TIME_LO_REG (REG_WDEVPWR_BASE + 0x004C)
#define WDEV_TSFTIME1_LO 0xFFFFFFFF
#define WDEV_TSFTIME1_LO_S 0

#define WDEVTSF1_TIME_HI_REG (REG_WDEVPWR_BASE + 0x0050)
#define WDEV_TSFTIME1_HI 0xFFFFFFFF
#define WDEV_TSFTIME1_HI_S 0

#define WDEVSLEEP1_CONF_REG (REG_WDEVPWR_BASE + 0x0054)
#define WDEV_TSFUP1_ENA (BIT(31))
#define WDEV_TSFUP1_ENA_S 31
#define WDEV_TXBEACON1_ENA (BIT(30))
#define WDEV_TXBEACON1_ENA_S 30
#define WDEV_WAKEUP1_ENA (BIT(29))
#define WDEV_WAKEUP1_ENA_S 29
#define WDEV_TSF1RTCUP_ENA (BIT(28))
#define WDEV_TSF1RTCUP_ENA_S 28
#define WDEV_TSF1HWUP_ENA (BIT(27))
#define WDEV_TSF1HWUP_ENA_S 27
#define WDEV_BEACON_TARGET1_VALID (BIT(25))
#define WDEV_BEACON_TARGET1_VALID_S 25

#define WDEVTSF1_ACTIVE_REG (REG_WDEVPWR_BASE + 0x0058)
#define WDEV_TSF1_ACTIVE_ST (BIT(1))
#define WDEV_TSF1_ACTIVE_ST_S 1
#define WDEV_TSF1_ACTIVE_CLR (BIT(0))
#define WDEV_TSF1_ACTIVE_CLR_S 0

#define WDEVTSFSW1_LO_REG (REG_WDEVPWR_BASE + 0x005C)
#define WDEV_TSFUPSW1_LO 0xFFFFFFFF
#define WDEV_TSFUPSW1_LO_S 0

#define WDEVTSFSW1_HI_REG (REG_WDEVPWR_BASE + 0x0060)
#define WDEV_TSFUPSW1_HI 0xFFFFFFFF
#define WDEV_TSFUPSW1_HI_S 0

#define WDEVBEACTAR1_LO_REG (REG_WDEVPWR_BASE + 0x0064)
#define WDEV_BEACSTART_TARGET1_LO 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET1_LO_S 0

#define WDEVBEACTAR1_HI_REG (REG_WDEVPWR_BASE + 0x0068)
#define WDEV_BEACSTART_TARGET1_HI 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET1_HI_S 0

#define WDEVBEATAR1_LO_REG (REG_WDEVPWR_BASE + 0x006C)
#define WDEV_BEACON_TARGET1_LO 0xFFFFFFFF
#define WDEV_BEACON_TARGET1_LO_S 0

#define WDEVBEATAR1_HI_REG (REG_WDEVPWR_BASE + 0x0070)
#define WDEV_BEACON_TARGET1_HI 0xFFFFFFFF
#define WDEV_BEACON_TARGET1_HI_S 0

#define WDEVBEA_CUR_TAR1_REG (REG_WDEVPWR_BASE + 0x0074)
#define WDEV_BEACON_CUR_TAR1 0xFFFFFFFF
#define WDEV_BEACON_CUR_TAR1_S 0

#define WDEVBEAINTER1_REG (REG_WDEVPWR_BASE + 0x0078)
#define WDEV_TBTT1_EARLY_TIME 0x0000FFFF
#define WDEV_TBTT1_EARLY_TIME_S 16
#define WDEV_TBTT1 0x0000FFFF
#define WDEV_TBTT1_S 0

#define WDEVTSF2_TIME_LO_REG (REG_WDEVPWR_BASE + 0x007C)
#define WDEV_TSFTIME2_LO 0xFFFFFFFF
#define WDEV_TSFTIME2_LO_S 0

#define WDEVTSF2_TIME_HI_REG (REG_WDEVPWR_BASE + 0x0080)
#define WDEV_TSFTIME2_HI 0xFFFFFFFF
#define WDEV_TSFTIME2_HI_S 0

#define WDEVSLEEP2_CONF_REG (REG_WDEVPWR_BASE + 0x0084)
#define WDEV_TSFUP2_ENA (BIT(31))
#define WDEV_TSFUP2_ENA_S 31
#define WDEV_TXBEACON2_ENA (BIT(30))
#define WDEV_TXBEACON2_ENA_S 30
#define WDEV_WAKEUP2_ENA (BIT(29))
#define WDEV_WAKEUP2_ENA_S 29
#define WDEV_TSF2RTCUP_ENA (BIT(28))
#define WDEV_TSF2RTCUP_ENA_S 28
#define WDEV_TSF2HWUP_ENA (BIT(27))
#define WDEV_TSF2HWUP_ENA_S 27
#define WDEV_BEACON_TARGET2_VALID (BIT(25))
#define WDEV_BEACON_TARGET2_VALID_S 25

#define WDEVTSF2_ACTIVE_REG (REG_WDEVPWR_BASE + 0x0088)
#define WDEV_TSF2_ACTIVE_ST (BIT(1))
#define WDEV_TSF2_ACTIVE_ST_S 1
#define WDEV_TSF2_ACTIVE_CLR (BIT(0))
#define WDEV_TSF2_ACTIVE_CLR_S 0

#define WDEVTSFSW2_LO_REG (REG_WDEVPWR_BASE + 0x008C)
#define WDEV_TSFUPSW2_LO 0xFFFFFFFF
#define WDEV_TSFUPSW2_LO_S 0

#define WDEVTSFSW2_HI_REG (REG_WDEVPWR_BASE + 0x0090)
#define WDEV_TSFUPSW2_HI 0xFFFFFFFF
#define WDEV_TSFUPSW2_HI_S 0

#define WDEVBEACTAR2_LO_REG (REG_WDEVPWR_BASE + 0x0094)
#define WDEV_BEACSTART_TARGET2_LO 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET2_LO_S 0

#define WDEVBEACTAR2_HI_REG (REG_WDEVPWR_BASE + 0x0098)
#define WDEV_BEACSTART_TARGET2_HI 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET2_HI_S 0

#define WDEVBEATAR2_LO_REG (REG_WDEVPWR_BASE + 0x009C)
#define WDEV_BEACON_TARGET2_LO 0xFFFFFFFF
#define WDEV_BEACON_TARGET2_LO_S 0

#define WDEVBEATAR2_HI_REG (REG_WDEVPWR_BASE + 0x00A0)
#define WDEV_BEACON_TARGET2_HI 0xFFFFFFFF
#define WDEV_BEACON_TARGET2_HI_S 0

#define WDEVBEA_CUR_TAR2_REG (REG_WDEVPWR_BASE + 0x00A4)
#define WDEV_BEACON_CUR_TAR2 0xFFFFFFFF
#define WDEV_BEACON_CUR_TAR2_S 0

#define WDEVBEAINTER2_REG (REG_WDEVPWR_BASE + 0x00A8)
#define WDEV_TBTT2_EARLY_TIME 0x0000FFFF
#define WDEV_TBTT2_EARLY_TIME_S 16
#define WDEV_TBTT2 0x0000FFFF
#define WDEV_TBTT2_S 0

#define WDEVTSF3_TIME_LO_REG (REG_WDEVPWR_BASE + 0x00AC)
#define WDEV_TSFTIME3_LO 0xFFFFFFFF
#define WDEV_TSFTIME3_LO_S 0

#define WDEVTSF3_TIME_HI_REG (REG_WDEVPWR_BASE + 0x00B0)
#define WDEV_TSFTIME3_HI 0xFFFFFFFF
#define WDEV_TSFTIME3_HI_S 0

#define WDEVSLEEP3_CONF_REG (REG_WDEVPWR_BASE + 0x00B4)
#define WDEV_TSFUP3_ENA (BIT(31))
#define WDEV_TSFUP3_ENA_S 31
#define WDEV_TXBEACON3_ENA (BIT(30))
#define WDEV_TXBEACON3_ENA_S 30
#define WDEV_WAKEUP3_ENA (BIT(29))
#define WDEV_WAKEUP3_ENA_S 29
#define WDEV_TSF3RTCUP_ENA (BIT(28))
#define WDEV_TSF3RTCUP_ENA_S 28
#define WDEV_TSF3HWUP_ENA (BIT(27))
#define WDEV_TSF3HWUP_ENA_S 27
#define WDEV_BEACON_TARGET3_VALID (BIT(25))
#define WDEV_BEACON_TARGET3_VALID_S 25

#define WDEVTSF3_ACTIVE_REG (REG_WDEVPWR_BASE + 0x00B8)
#define WDEV_TSF3_ACTIVE_ST (BIT(1))
#define WDEV_TSF3_ACTIVE_ST_S 1
#define WDEV_TSF3_ACTIVE_CLR (BIT(0))
#define WDEV_TSF3_ACTIVE_CLR_S 0

#define WDEVTSFSW3_LO_REG (REG_WDEVPWR_BASE + 0x00BC)
#define WDEV_TSFUPSW3_LO 0xFFFFFFFF
#define WDEV_TSFUPSW3_LO_S 0

#define WDEVTSFSW3_HI_REG (REG_WDEVPWR_BASE + 0x00C0)
#define WDEV_TSFUPSW3_HI 0xFFFFFFFF
#define WDEV_TSFUPSW3_HI_S 0

#define WDEVBEACTAR3_LO_REG (REG_WDEVPWR_BASE + 0x00C4)
#define WDEV_BEACSTART_TARGET3_LO 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET3_LO_S 0

#define WDEVBEACTAR3_HI_REG (REG_WDEVPWR_BASE + 0x00C8)
#define WDEV_BEACSTART_TARGET3_HI 0xFFFFFFFF
#define WDEV_BEACSTART_TARGET3_HI_S 0

#define WDEVBEATAR3_LO_REG (REG_WDEVPWR_BASE + 0x00CC)
#define WDEV_BEACON_TARGET3_LO 0xFFFFFFFF
#define WDEV_BEACON_TARGET3_LO_S 0

#define WDEVBEATAR3_HI_REG (REG_WDEVPWR_BASE + 0x00D0)
#define WDEV_BEACON_TARGET3_HI 0xFFFFFFFF
#define WDEV_BEACON_TARGET3_HI_S 0

#define WDEVBEA_CUR_TAR3_REG (REG_WDEVPWR_BASE + 0x00D4)
#define WDEV_BEACON_CUR_TAR3 0xFFFFFFFF
#define WDEV_BEACON_CUR_TAR3_S 0

#define WDEVBEAINTER3_REG (REG_WDEVPWR_BASE + 0x00D8)
#define WDEV_TBTT3_EARLY_TIME 0x0000FFFF
#define WDEV_TBTT3_EARLY_TIME_S 16
#define WDEV_TBTT3 0x0000FFFF
#define WDEV_TBTT3_S 0

#define WDEVRTC_CALISW_REG (REG_WDEVPWR_BASE + 0x00DC)
#define WDEV_CALISW_VALUE 0x0003FFFF
#define WDEV_CALISW_VALUE_S 0

#define WDEVTSF0TIMER_ENA_REG (REG_WDEVPWR_BASE + 0x00E0)
#define WDEV_TSF0TIMER_ENA (BIT(31))
#define WDEV_TSF0TIMER_ENA_S 31
#define WDEV_TSF0TIMER_WAKEUP_ENA (BIT(30))
#define WDEV_TSF0TIMER_WAKEUP_ENA_S 30

#define WDEVTSF0_TIMER_LO_REG (REG_WDEVPWR_BASE + 0x00E4)
#define WDEV_TSF0TIMER_LO 0xFFFFFFFF
#define WDEV_TSF0TIMER_LO_S 0

#define WDEVTSF0_TIMER_HI_REG (REG_WDEVPWR_BASE + 0x00E8)
#define WDEV_TSF0TIMER_HI 0xFFFFFFFF
#define WDEV_TSF0TIMER_HI_S 0

#define WDEVTSF1TIMER_ENA_REG (REG_WDEVPWR_BASE + 0x00EC)
#define WDEV_TSF1TIMER_ENA (BIT(31))
#define WDEV_TSF1TIMER_ENA_S 31
#define WDEV_TSF1TIMER_WAKEUP_ENA (BIT(30))
#define WDEV_TSF1TIMER_WAKEUP_ENA_S 30

#define WDEVTSF1_TIMER_LO_REG (REG_WDEVPWR_BASE + 0x00F0)
#define WDEV_TSF1TIMER_LO 0xFFFFFFFF
#define WDEV_TSF1TIMER_LO_S 0

#define WDEVTSF1_TIMER_HI_REG (REG_WDEVPWR_BASE + 0x00F4)
#define WDEV_TSF1TIMER_HI 0xFFFFFFFF
#define WDEV_TSF1TIMER_HI_S 0

#define WDEVTSF2TIMER_ENA_REG (REG_WDEVPWR_BASE + 0x00F8)
#define WDEV_TSF2TIMER_ENA (BIT(31))
#define WDEV_TSF2TIMER_ENA_S 31
#define WDEV_TSF2TIMER_WAKEUP_ENA (BIT(30))
#define WDEV_TSF2TIMER_WAKEUP_ENA_S 30

#define WDEVTSF2_TIMER_LO_REG (REG_WDEVPWR_BASE + 0x00FC)
#define WDEV_TSF2TIMER_LO 0xFFFFFFFF
#define WDEV_TSF2TIMER_LO_S 0

#define WDEVTSF2_TIMER_HI_REG (REG_WDEVPWR_BASE + 0x0100)
#define WDEV_TSF2TIMER_HI 0xFFFFFFFF
#define WDEV_TSF2TIMER_HI_S 0

#define WDEVTSF3TIMER_ENA_REG (REG_WDEVPWR_BASE + 0x0104)
#define WDEV_TSF3TIMER_ENA (BIT(31))
#define WDEV_TSF3TIMER_ENA_S 31
#define WDEV_TSF3TIMER_WAKEUP_ENA (BIT(30))
#define WDEV_TSF3TIMER_WAKEUP_ENA_S 30

#define WDEVTSF3_TIMER_LO_REG (REG_WDEVPWR_BASE + 0x0108)
#define WDEV_TSF3TIMER_LO 0xFFFFFFFF
#define WDEV_TSF3TIMER_LO_S 0

#define WDEVTSF3_TIMER_HI_REG (REG_WDEVPWR_BASE + 0x010C)
#define WDEV_TSF3TIMER_HI 0xFFFFFFFF
#define WDEV_TSF3TIMER_HI_S 0

#define WDEVRND_REG (REG_WDEVPWR_BASE + 0x0110)
#define WDEV_MAC_RND_DATA 0xFFFFFFFF
#define WDEV_MAC_RND_DATA_S 0

#define WDEVRXBEA_TO_REG (REG_WDEVPWR_BASE + 0x0114)
#define WDEV_RXBEACONTIMOUT 0x0000FFFF
#define WDEV_RXBEACONTIMOUT_S 0

#define WDEVRWBT_COEX_CONF_REG (REG_WDEVPWR_BASE + 0x0118)
#define WDEV_RW_NBT_PRIO_BLE 0x00000003
#define WDEV_RW_NBT_PRIO_BLE_S 30
#define WDEV_RW_BT_PRIO_SEL 0x0000000F
#define WDEV_RW_BT_PRIO_SEL_S 24
#define WDEV_FREQ_HOP_TIMER 0x00000FFF
#define WDEV_FREQ_HOP_TIMER_S 8
#define WDEV_WLANAT_INV (BIT(3))
#define WDEV_WLANAT_INV_S 3
#define WDEV_FREQ_HOP_BUSY_ENA (BIT(1))
#define WDEV_FREQ_HOP_BUSY_ENA_S 1
#define WDEV_RW_BT_COEX_EN (BIT(0))
#define WDEV_RW_BT_COEX_EN_S 0

#define WDEVTSF_PTI_CLR_REG (REG_WDEVPWR_BASE + 0x011C)
#define WDEV_WLAN_RXBEACON3_MT_CLR (BIT(3))
#define WDEV_WLAN_RXBEACON3_MT_CLR_S 3
#define WDEV_WLAN_RXBEACON2_MT_CLR (BIT(2))
#define WDEV_WLAN_RXBEACON2_MT_CLR_S 2
#define WDEV_WLAN_RXBEACON1_MT_CLR (BIT(1))
#define WDEV_WLAN_RXBEACON1_MT_CLR_S 1
#define WDEV_WLAN_RXBEACON0_MT_CLR (BIT(0))
#define WDEV_WLAN_RXBEACON0_MT_CLR_S 0

#define WDEVTSF_PTI_MT_CNT_REG (REG_WDEVPWR_BASE + 0x0120)
#define WDEV_WLAN_RXBEACON3_MT_CNT 0x000000FF
#define WDEV_WLAN_RXBEACON3_MT_CNT_S 24
#define WDEV_WLAN_RXBEACON2_MT_CNT 0x000000FF
#define WDEV_WLAN_RXBEACON2_MT_CNT_S 16
#define WDEV_WLAN_RXBEACON1_MT_CNT 0x000000FF
#define WDEV_WLAN_RXBEACON1_MT_CNT_S 8
#define WDEV_WLAN_RXBEACON0_MT_CNT 0x000000FF
#define WDEV_WLAN_RXBEACON0_MT_CNT_S 0

#define WDEVTSF_PTI_MT_CONF_REG (REG_WDEVPWR_BASE + 0x0124)
#define WDEV_WLAN_RXBEACON3_MT_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON3_MT_PTI_S 12
#define WDEV_WLAN_RXBEACON2_MT_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON2_MT_PTI_S 8
#define WDEV_WLAN_RXBEACON1_MT_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON1_MT_PTI_S 4
#define WDEV_WLAN_RXBEACON0_MT_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON0_MT_PTI_S 0

#define WDEVTSF_PTI_CONF_REG (REG_WDEVPWR_BASE + 0x0128)
#define WDEV_WLAN_RXBEACON3_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON3_PTI_S 24
#define WDEV_WLAN_RXBEACON2_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON2_PTI_S 20
#define WDEV_WLAN_RXBEACON1_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON1_PTI_S 16
#define WDEV_WLAN_RXBEACON0_PTI 0x0000000F
#define WDEV_WLAN_RXBEACON0_PTI_S 12
#define WDEV_WLAN_DEFAULT_PTI 0x0000000F
#define WDEV_WLAN_DEFAULT_PTI_S 8
#define WDEV_WLAN_DEFAULT_ACTIVE (BIT(4))
#define WDEV_WLAN_DEFAULT_ACTIVE_S 4
#define WDEV_EXTERN_GET (BIT(3))
#define WDEV_EXTERN_GET_S 3
#define WDEV_WLAN_GET (BIT(2))
#define WDEV_WLAN_GET_S 2
#define WDEV_WLAN_RWBT_ANT_SEL (BIT(1))
#define WDEV_WLAN_RWBT_ANT_SEL_S 1
#define WDEV_RW_BT_GET (BIT(0))
#define WDEV_RW_BT_GET_S 0

#define WDEVRWBT_COEX_WAIT0_REG (REG_WDEVPWR_BASE + 0x012C)
#define WDEV_WLAN_ANT_SEL_TAIL_WAIT 0x0000FFFF
#define WDEV_WLAN_ANT_SEL_TAIL_WAIT_S 16

#define WDEVRWBT_COEX_WAIT1_REG (REG_WDEVPWR_BASE + 0x0130)
#define WDEV_WLAN_ANT_SEL_HEAD_WAIT 0x0000FFFF
#define WDEV_WLAN_ANT_SEL_HEAD_WAIT_S 16
#define WDEV_MAC_REFUSE_TIME 0x0000FFFF
#define WDEV_MAC_REFUSE_TIME_S 0

#define WDEVRWBT_COEX_DYNAMIC_PRIORITY_REG (REG_WDEVPWR_BASE + 0x0134)
#define WDEV_BT_DYNAMIC_PRIO_EN (BIT(31))
#define WDEV_BT_DYNAMIC_PRIO_EN_S 31
#define WDEV_BT_DYNAMIC_PRIO 0x0000000F
#define WDEV_BT_DYNAMIC_PRIO_S 27
#define WDEV_WLAN_DYNAMIC_PRIO_EN (BIT(26))
#define WDEV_WLAN_DYNAMIC_PRIO_EN_S 26
#define WDEV_WLAN_DYNAMIC_PRIO 0x0000000F
#define WDEV_WLAN_DYNAMIC_PRIO_S 22

#define WDEVRWBT_COEX_GPIO_SEL_REG (REG_WDEVPWR_BASE + 0x0138)
#define WDEV_FREQ_HOP_BUSY 0x00000003
#define WDEV_FREQ_HOP_BUSY_S 30
#define WDEV_GPIO_BT_PRIORITY_SEL 0x00000007
#define WDEV_GPIO_BT_PRIORITY_SEL_S 6
#define WDEV_GPIO_BT_ACTIVE_SEL 0x00000007
#define WDEV_GPIO_BT_ACTIVE_SEL_S 3
#define WDEV_GPIO_WLAN_ACTIVE_SEL 0x00000007
#define WDEV_GPIO_WLAN_ACTIVE_SEL_S 0

#define WDEVRWBT_COEX_TIMER0_CONF0_REG (REG_WDEVPWR_BASE + 0x013C)
#define WDEV_COEX_TIMER0_ENA (BIT(31))
#define WDEV_COEX_TIMER0_ENA_S 31
#define WDEV_COEX_TIMER0_SRC (BIT(30))
#define WDEV_COEX_TIMER0_SRC_S 30
#define WDEV_COEX_TIMER0_FH (BIT(28))
#define WDEV_COEX_TIMER0_FH_S 28
#define WDEV_COEX_TIMER0_PTI 0x0000000F
#define WDEV_COEX_TIMER0_PTI_S 24
#define WDEV_COEX_TIMER0_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER0_LEN_S 0

#define WDEVRWBT_COEX_TIMER0_CONF1_REG (REG_WDEVPWR_BASE + 0x0140)
#define WDEV_COEX_TIMER0_START 0xFFFFFFFF
#define WDEV_COEX_TIMER0_START_S 0

#define WDEVRWBT_COEX_TIMER1_CONF0_REG (REG_WDEVPWR_BASE + 0x0144)
#define WDEV_COEX_TIMER1_ENA (BIT(31))
#define WDEV_COEX_TIMER1_ENA_S 31
#define WDEV_COEX_TIMER1_SRC (BIT(30))
#define WDEV_COEX_TIMER1_SRC_S 30
#define WDEV_COEX_TIMER1_FH (BIT(28))
#define WDEV_COEX_TIMER1_FH_S 28
#define WDEV_COEX_TIMER1_PTI 0x0000000F
#define WDEV_COEX_TIMER1_PTI_S 24
#define WDEV_COEX_TIMER1_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER1_LEN_S 0

#define WDEVRWBT_COEX_TIMER1_CONF1_REG (REG_WDEVPWR_BASE + 0x0148)
#define WDEV_COEX_TIMER1_START 0xFFFFFFFF
#define WDEV_COEX_TIMER1_START_S 0

#define WDEVRWBT_COEX_TIMER2_CONF0_REG (REG_WDEVPWR_BASE + 0x014C)
#define WDEV_COEX_TIMER2_ENA (BIT(31))
#define WDEV_COEX_TIMER2_ENA_S 31
#define WDEV_COEX_TIMER2_SRC (BIT(30))
#define WDEV_COEX_TIMER2_SRC_S 30
#define WDEV_COEX_TIMER2_FH (BIT(28))
#define WDEV_COEX_TIMER2_FH_S 28
#define WDEV_COEX_TIMER2_PTI 0x0000000F
#define WDEV_COEX_TIMER2_PTI_S 24
#define WDEV_COEX_TIMER2_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER2_LEN_S 0

#define WDEVRWBT_COEX_TIMER2_CONF1_REG (REG_WDEVPWR_BASE + 0x0150)
#define WDEV_COEX_TIMER2_START 0xFFFFFFFF
#define WDEV_COEX_TIMER2_START_S 0

#define WDEVRWBT_COEX_TIMER3_CONF0_REG (REG_WDEVPWR_BASE + 0x0154)
#define WDEV_COEX_TIMER3_ENA (BIT(31))
#define WDEV_COEX_TIMER3_ENA_S 31
#define WDEV_COEX_TIMER3_SRC (BIT(30))
#define WDEV_COEX_TIMER3_SRC_S 30
#define WDEV_COEX_TIMER3_FH (BIT(28))
#define WDEV_COEX_TIMER3_FH_S 28
#define WDEV_COEX_TIMER3_PTI 0x0000000F
#define WDEV_COEX_TIMER3_PTI_S 24
#define WDEV_COEX_TIMER3_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER3_LEN_S 0

#define WDEVRWBT_COEX_TIMER3_CONF1_REG (REG_WDEVPWR_BASE + 0x0158)
#define WDEV_COEX_TIMER3_START 0xFFFFFFFF
#define WDEV_COEX_TIMER3_START_S 0

#define WDEVRWBT_COEX_TIMER4_CONF0_REG (REG_WDEVPWR_BASE + 0x015C)
#define WDEV_COEX_TIMER4_ENA (BIT(31))
#define WDEV_COEX_TIMER4_ENA_S 31
#define WDEV_COEX_TIMER4_SRC (BIT(30))
#define WDEV_COEX_TIMER4_SRC_S 30
#define WDEV_COEX_TIMER4_FH (BIT(28))
#define WDEV_COEX_TIMER4_FH_S 28
#define WDEV_COEX_TIMER4_PTI 0x0000000F
#define WDEV_COEX_TIMER4_PTI_S 24
#define WDEV_COEX_TIMER4_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER4_LEN_S 0

#define WDEVRWBT_COEX_TIMER4_CONF1_REG (REG_WDEVPWR_BASE + 0x0160)
#define WDEV_COEX_TIMER4_START 0xFFFFFFFF
#define WDEV_COEX_TIMER4_START_S 0

#define WDEVRWBT_COEX_TIMER5_CONF0_REG (REG_WDEVPWR_BASE + 0x0164)
#define WDEV_COEX_TIMER5_ENA (BIT(31))
#define WDEV_COEX_TIMER5_ENA_S 31
#define WDEV_COEX_TIMER5_SRC (BIT(30))
#define WDEV_COEX_TIMER5_SRC_S 30
#define WDEV_COEX_TIMER5_FH (BIT(28))
#define WDEV_COEX_TIMER5_FH_S 28
#define WDEV_COEX_TIMER5_PTI 0x0000000F
#define WDEV_COEX_TIMER5_PTI_S 24
#define WDEV_COEX_TIMER5_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER5_LEN_S 0

#define WDEVRWBT_COEX_TIMER5_CONF1_REG (REG_WDEVPWR_BASE + 0x0168)
#define WDEV_COEX_TIMER5_START 0xFFFFFFFF
#define WDEV_COEX_TIMER5_START_S 0

#define WDEVRWBT_COEX_TIMER6_CONF0_REG (REG_WDEVPWR_BASE + 0x016C)
#define WDEV_COEX_TIMER6_ENA (BIT(31))
#define WDEV_COEX_TIMER6_ENA_S 31
#define WDEV_COEX_TIMER6_SRC (BIT(30))
#define WDEV_COEX_TIMER6_SRC_S 30
#define WDEV_COEX_TIMER6_FH (BIT(28))
#define WDEV_COEX_TIMER6_FH_S 28
#define WDEV_COEX_TIMER6_PTI 0x0000000F
#define WDEV_COEX_TIMER6_PTI_S 24
#define WDEV_COEX_TIMER6_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER6_LEN_S 0

#define WDEVRWBT_COEX_TIMER6_CONF1_REG (REG_WDEVPWR_BASE + 0x0170)
#define WDEV_COEX_TIMER6_START 0xFFFFFFFF
#define WDEV_COEX_TIMER6_START_S 0

#define WDEVRWBT_COEX_TIMER7_CONF0_REG (REG_WDEVPWR_BASE + 0x0174)
#define WDEV_COEX_TIMER7_ENA (BIT(31))
#define WDEV_COEX_TIMER7_ENA_S 31
#define WDEV_COEX_TIMER7_SRC (BIT(30))
#define WDEV_COEX_TIMER7_SRC_S 30
#define WDEV_COEX_TIMER7_FH (BIT(28))
#define WDEV_COEX_TIMER7_FH_S 28
#define WDEV_COEX_TIMER7_PTI 0x0000000F
#define WDEV_COEX_TIMER7_PTI_S 24
#define WDEV_COEX_TIMER7_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER7_LEN_S 0

#define WDEVRWBT_COEX_TIMER7_CONF1_REG (REG_WDEVPWR_BASE + 0x0178)
#define WDEV_COEX_TIMER7_START 0xFFFFFFFF
#define WDEV_COEX_TIMER7_START_S 0

#define WDEVRWBT_COEX_TIMER8_CONF0_REG (REG_WDEVPWR_BASE + 0x017C)
#define WDEV_COEX_TIMER8_ENA (BIT(31))
#define WDEV_COEX_TIMER8_ENA_S 31
#define WDEV_COEX_TIMER8_SRC (BIT(30))
#define WDEV_COEX_TIMER8_SRC_S 30
#define WDEV_COEX_TIMER8_FH (BIT(28))
#define WDEV_COEX_TIMER8_FH_S 28
#define WDEV_COEX_TIMER8_PTI 0x0000000F
#define WDEV_COEX_TIMER8_PTI_S 24
#define WDEV_COEX_TIMER8_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER8_LEN_S 0

#define WDEVRWBT_COEX_TIMER8_CONF1_REG (REG_WDEVPWR_BASE + 0x0180)
#define WDEV_COEX_TIMER8_START 0xFFFFFFFF
#define WDEV_COEX_TIMER8_START_S 0

#define WDEVRWBT_COEX_TIMER9_CONF0_REG (REG_WDEVPWR_BASE + 0x0184)
#define WDEV_COEX_TIMER9_ENA (BIT(31))
#define WDEV_COEX_TIMER9_ENA_S 31
#define WDEV_COEX_TIMER9_SRC (BIT(30))
#define WDEV_COEX_TIMER9_SRC_S 30
#define WDEV_COEX_TIMER9_FH (BIT(28))
#define WDEV_COEX_TIMER9_FH_S 28
#define WDEV_COEX_TIMER9_PTI 0x0000000F
#define WDEV_COEX_TIMER9_PTI_S 24
#define WDEV_COEX_TIMER9_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER9_LEN_S 0

#define WDEVRWBT_COEX_TIMER9_CONF1_REG (REG_WDEVPWR_BASE + 0x0188)
#define WDEV_COEX_TIMER9_START 0xFFFFFFFF
#define WDEV_COEX_TIMER9_START_S 0

#define WDEVRWBT_COEX_TIMER10_CONF0_REG (REG_WDEVPWR_BASE + 0x018C)
#define WDEV_COEX_TIMER10_ENA (BIT(31))
#define WDEV_COEX_TIMER10_ENA_S 31
#define WDEV_COEX_TIMER10_SRC (BIT(30))
#define WDEV_COEX_TIMER10_SRC_S 30
#define WDEV_COEX_TIMER10_FH (BIT(28))
#define WDEV_COEX_TIMER10_FH_S 28
#define WDEV_COEX_TIMER10_PTI 0x0000000F
#define WDEV_COEX_TIMER10_PTI_S 24
#define WDEV_COEX_TIMER10_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER10_LEN_S 0

#define WDEVRWBT_COEX_TIMER10_CONF1_REG (REG_WDEVPWR_BASE + 0x0190)
#define WDEV_COEX_TIMER10_START 0xFFFFFFFF
#define WDEV_COEX_TIMER10_START_S 0

#define WDEVRWBT_COEX_TIMER11_CONF0_REG (REG_WDEVPWR_BASE + 0x0194)
#define WDEV_COEX_TIMER11_ENA (BIT(31))
#define WDEV_COEX_TIMER11_ENA_S 31
#define WDEV_COEX_TIMER11_SRC (BIT(30))
#define WDEV_COEX_TIMER11_SRC_S 30
#define WDEV_COEX_TIMER11_FH (BIT(28))
#define WDEV_COEX_TIMER11_FH_S 28
#define WDEV_COEX_TIMER11_PTI 0x0000000F
#define WDEV_COEX_TIMER11_PTI_S 24
#define WDEV_COEX_TIMER11_LEN 0x00FFFFFF
#define WDEV_COEX_TIMER11_LEN_S 0

#define WDEVRWBT_COEX_TIMER11_CONF1_REG (REG_WDEVPWR_BASE + 0x0198)
#define WDEV_COEX_TIMER11_START 0xFFFFFFFF
#define WDEV_COEX_TIMER11_START_S 0

#define WDEVRWBT_COEX_TIMER_END_ST_REG (REG_WDEVPWR_BASE + 0x019C)
#define WDEV_COEX_TIMER11_END_ST (BIT(11))
#define WDEV_COEX_TIMER11_END_ST_S 11
#define WDEV_COEX_TIMER10_END_ST (BIT(10))
#define WDEV_COEX_TIMER10_END_ST_S 10
#define WDEV_COEX_TIMER9_END_ST (BIT(9))
#define WDEV_COEX_TIMER9_END_ST_S 9
#define WDEV_COEX_TIMER8_END_ST (BIT(8))
#define WDEV_COEX_TIMER8_END_ST_S 8
#define WDEV_COEX_TIMER7_END_ST (BIT(7))
#define WDEV_COEX_TIMER7_END_ST_S 7
#define WDEV_COEX_TIMER6_END_ST (BIT(6))
#define WDEV_COEX_TIMER6_END_ST_S 6
#define WDEV_COEX_TIMER5_END_ST (BIT(5))
#define WDEV_COEX_TIMER5_END_ST_S 5
#define WDEV_COEX_TIMER4_END_ST (BIT(4))
#define WDEV_COEX_TIMER4_END_ST_S 4
#define WDEV_COEX_TIMER3_END_ST (BIT(3))
#define WDEV_COEX_TIMER3_END_ST_S 3
#define WDEV_COEX_TIMER2_END_ST (BIT(2))
#define WDEV_COEX_TIMER2_END_ST_S 2
#define WDEV_COEX_TIMER1_END_ST (BIT(1))
#define WDEV_COEX_TIMER1_END_ST_S 1
#define WDEV_COEX_TIMER0_END_ST (BIT(0))
#define WDEV_COEX_TIMER0_END_ST_S 0

#define WDEVRWBT_COEX_TIMER_END_CLR_REG (REG_WDEVPWR_BASE + 0x01A0)
#define WDEV_COEX_TIMER11_END_CLR (BIT(11))
#define WDEV_COEX_TIMER11_END_CLR_S 11
#define WDEV_COEX_TIMER10_END_CLR (BIT(10))
#define WDEV_COEX_TIMER10_END_CLR_S 10
#define WDEV_COEX_TIMER9_END_CLR (BIT(9))
#define WDEV_COEX_TIMER9_END_CLR_S 9
#define WDEV_COEX_TIMER8_END_CLR (BIT(8))
#define WDEV_COEX_TIMER8_END_CLR_S 8
#define WDEV_COEX_TIMER7_END_CLR (BIT(7))
#define WDEV_COEX_TIMER7_END_CLR_S 7
#define WDEV_COEX_TIMER6_END_CLR (BIT(6))
#define WDEV_COEX_TIMER6_END_CLR_S 6
#define WDEV_COEX_TIMER5_END_CLR (BIT(5))
#define WDEV_COEX_TIMER5_END_CLR_S 5
#define WDEV_COEX_TIMER4_END_CLR (BIT(4))
#define WDEV_COEX_TIMER4_END_CLR_S 4
#define WDEV_COEX_TIMER3_END_CLR (BIT(3))
#define WDEV_COEX_TIMER3_END_CLR_S 3
#define WDEV_COEX_TIMER2_END_CLR (BIT(2))
#define WDEV_COEX_TIMER2_END_CLR_S 2
#define WDEV_COEX_TIMER1_END_CLR (BIT(1))
#define WDEV_COEX_TIMER1_END_CLR_S 1
#define WDEV_COEX_TIMER0_END_CLR (BIT(0))
#define WDEV_COEX_TIMER0_END_CLR_S 0

#define WDEV_INT_ENA_MACPWR_REG (REG_WDEVPWR_BASE + 0x01A4)
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_ENA (BIT(12))
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_ENA_S 12
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_ENA (BIT(11))
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_ENA_S 11
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_ENA (BIT(10))
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_ENA_S 10
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_ENA (BIT(9))
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_ENA_S 9
#define WDEV_TSF0_REACH_INT_ENA (BIT(8))
#define WDEV_TSF0_REACH_INT_ENA_S 8
#define WDEV_TSF1_REACH_INT_ENA (BIT(7))
#define WDEV_TSF1_REACH_INT_ENA_S 7
#define WDEV_TSF2_REACH_INT_ENA (BIT(6))
#define WDEV_TSF2_REACH_INT_ENA_S 6
#define WDEV_TSF3_REACH_INT_ENA (BIT(5))
#define WDEV_TSF3_REACH_INT_ENA_S 5
#define WDEV_TBTT0_INT_ENA (BIT(4))
#define WDEV_TBTT0_INT_ENA_S 4
#define WDEV_TBTT1_INT_ENA (BIT(3))
#define WDEV_TBTT1_INT_ENA_S 3
#define WDEV_TBTT2_INT_ENA (BIT(2))
#define WDEV_TBTT2_INT_ENA_S 2
#define WDEV_TBTT3_INT_ENA (BIT(1))
#define WDEV_TBTT3_INT_ENA_S 1
#define WDEV_COEX_TIMER_END_INT_ENA (BIT(0))
#define WDEV_COEX_TIMER_END_INT_ENA_S 0

#define WDEV_INT_RAW_MACPWR_REG (REG_WDEVPWR_BASE + 0x01A8)
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_RAW (BIT(12))
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_RAW_S 12
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_RAW (BIT(11))
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_RAW_S 11
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_RAW (BIT(10))
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_RAW_S 10
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_RAW (BIT(9))
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_RAW_S 9
#define WDEV_TSF0_REACH_INT_RAW (BIT(8))
#define WDEV_TSF0_REACH_INT_RAW_S 8
#define WDEV_TSF1_REACH_INT_RAW (BIT(7))
#define WDEV_TSF1_REACH_INT_RAW_S 7
#define WDEV_TSF2_REACH_INT_RAW (BIT(6))
#define WDEV_TSF2_REACH_INT_RAW_S 6
#define WDEV_TSF3_REACH_INT_RAW (BIT(5))
#define WDEV_TSF3_REACH_INT_RAW_S 5
#define WDEV_TBTT0_INT_RAW (BIT(4))
#define WDEV_TBTT0_INT_RAW_S 4
#define WDEV_TBTT1_INT_RAW (BIT(3))
#define WDEV_TBTT1_INT_RAW_S 3
#define WDEV_TBTT2_INT_RAW (BIT(2))
#define WDEV_TBTT2_INT_RAW_S 2
#define WDEV_TBTT3_INT_RAW (BIT(1))
#define WDEV_TBTT3_INT_RAW_S 1
#define WDEV_COEX_TIMER_END_INT_RAW (BIT(0))
#define WDEV_COEX_TIMER_END_INT_RAW_S 0

#define WDEV_INT_ST_MACPWR_REG (REG_WDEVPWR_BASE + 0x01AC)
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_ST (BIT(12))
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_ST_S 12
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_ST (BIT(11))
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_ST_S 11
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_ST (BIT(10))
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_ST_S 10
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_ST (BIT(9))
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_ST_S 9
#define WDEV_TSF0_REACH_INT_ST (BIT(8))
#define WDEV_TSF0_REACH_INT_ST_S 8
#define WDEV_TSF1_REACH_INT_ST (BIT(7))
#define WDEV_TSF1_REACH_INT_ST_S 7
#define WDEV_TSF2_REACH_INT_ST (BIT(6))
#define WDEV_TSF2_REACH_INT_ST_S 6
#define WDEV_TSF3_REACH_INT_ST (BIT(5))
#define WDEV_TSF3_REACH_INT_ST_S 5
#define WDEV_TBTT0_INT_ST (BIT(4))
#define WDEV_TBTT0_INT_ST_S 4
#define WDEV_TBTT1_INT_ST (BIT(3))
#define WDEV_TBTT1_INT_ST_S 3
#define WDEV_TBTT2_INT_ST (BIT(2))
#define WDEV_TBTT2_INT_ST_S 2
#define WDEV_TBTT3_INT_ST (BIT(1))
#define WDEV_TBTT3_INT_ST_S 1
#define WDEV_COEX_TIMER_END_INT_ST (BIT(0))
#define WDEV_COEX_TIMER_END_INT_ST_S 0

#define WDEV_INT_CLR_MACPWR_REG (REG_WDEVPWR_BASE + 0x01B0)
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_CLR (BIT(12))
#define WDEV_RXBEACON3_MAINTAIN_REACH_INT_CLR_S 12
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_CLR (BIT(11))
#define WDEV_RXBEACON2_MAINTAIN_REACH_INT_CLR_S 11
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_CLR (BIT(10))
#define WDEV_RXBEACON1_MAINTAIN_REACH_INT_CLR_S 10
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_CLR (BIT(9))
#define WDEV_RXBEACON0_MAINTAIN_REACH_INT_CLR_S 9
#define WDEV_TSF0_REACH_INT_CLR (BIT(8))
#define WDEV_TSF0_REACH_INT_CLR_S 8
#define WDEV_TSF1_REACH_INT_CLR (BIT(7))
#define WDEV_TSF1_REACH_INT_CLR_S 7
#define WDEV_TSF2_REACH_INT_CLR (BIT(6))
#define WDEV_TSF2_REACH_INT_CLR_S 6
#define WDEV_TSF3_REACH_INT_CLR (BIT(5))
#define WDEV_TSF3_REACH_INT_CLR_S 5
#define WDEV_TBTT0_INT_CLR (BIT(4))
#define WDEV_TBTT0_INT_CLR_S 4
#define WDEV_TBTT1_INT_CLR (BIT(3))
#define WDEV_TBTT1_INT_CLR_S 3
#define WDEV_TBTT2_INT_CLR (BIT(2))
#define WDEV_TBTT2_INT_CLR_S 2
#define WDEV_TBTT3_INT_CLR (BIT(1))
#define WDEV_TBTT3_INT_CLR_S 1
#define WDEV_COEX_TIMER_END_INT_CLR (BIT(0))
#define WDEV_COEX_TIMER_END_INT_CLR_S 0

#define WDEVCO_EXTERN_CONF0_REG (REG_WDEVPWR_BASE + 0x01B4)
#define WDEV_EXTERN_IN0_PTI 0x0000000F
#define WDEV_EXTERN_IN0_PTI_S 28
#define WDEV_EXTERN_IN1_PTI 0x0000000F
#define WDEV_EXTERN_IN1_PTI_S 24
#define WDEV_EXTERN_IN2_PTI 0x0000000F
#define WDEV_EXTERN_IN2_PTI_S 20
#define WDEV_EXTERN_IN3_PTI 0x0000000F
#define WDEV_EXTERN_IN3_PTI_S 16
#define WDEV_EXTERN_OUT0_PTI 0x0000000F
#define WDEV_EXTERN_OUT0_PTI_S 12
#define WDEV_EXTERN_OUT1_PTI 0x0000000F
#define WDEV_EXTERN_OUT1_PTI_S 8
#define WDEV_EXTERN_OUT2_PTI 0x0000000F
#define WDEV_EXTERN_OUT2_PTI_S 4
#define WDEV_EXTERN_OUT3_PTI 0x0000000F
#define WDEV_EXTERN_OUT3_PTI_S 0

#define WDEVCO_EXTERN_CONF1_REG (REG_WDEVPWR_BASE + 0x01B8)
#define WDEV_EXTERN_ANT_FOLLOW_WLAN (BIT(0))
#define WDEV_EXTERN_ANT_FOLLOW_WLAN_S 0

#define WDEVPWRDATE_REG (REG_WDEVPWR_BASE + 0x03F8)
#define WDEV_MACPWR_DATE 0x0FFFFFFF
#define WDEV_MACPWR_DATE_S 0
#define WDEV_MACPWR_DATE_VERSION 0x1906140
