
#define WDEVBSSID0LO_REG (REG_WDEVRX_BASE + 0x0000)
#define WDEV_MACBSSID0_LO 0xFFFFFFFF
#define WDEV_MACBSSID0_LO_S 0

#define WDEVBSSID0HI_REG (REG_WDEVRX_BASE + 0x0004)
#define WDEV_MACBSSID0_HI 0x0000FFFF
#define WDEV_MACBSSID0_HI_S 0

#define WDEVBSSID1LO_REG (REG_WDEVRX_BASE + 0x0008)
#define WDEV_MACBSSID1_LO 0xFFFFFFFF
#define WDEV_MACBSSID1_LO_S 0

#define WDEVBSSID1HI_REG (REG_WDEVRX_BASE + 0x000C)
#define WDEV_MACBSSID1_HI 0x0000FFFF
#define WDEV_MACBSSID1_HI_S 0

#define WDEVBSSID2LO_REG (REG_WDEVRX_BASE + 0x0010)
#define WDEV_MACBSSID2_LO 0xFFFFFFFF
#define WDEV_MACBSSID2_LO_S 0

#define WDEVBSSID2HI_REG (REG_WDEVRX_BASE + 0x0014)
#define WDEV_MACBSSID2_HI 0x0000FFFF
#define WDEV_MACBSSID2_HI_S 0

#define WDEVBSSID3LO_REG (REG_WDEVRX_BASE + 0x0018)
#define WDEV_MACBSSID3_LO 0xFFFFFFFF
#define WDEV_MACBSSID3_LO_S 0

#define WDEVBSSID3HI_REG (REG_WDEVRX_BASE + 0x001C)
#define WDEV_MACBSSID3_HI 0x0000FFFF
#define WDEV_MACBSSID3_HI_S 0

#define WDEVBSSID0_MASKLO_REG (REG_WDEVRX_BASE + 0x0020)
#define WDEV_MACBSSID0_MASKLO 0xFFFFFFFF
#define WDEV_MACBSSID0_MASKLO_S 0

#define WDEVBSSID0_MASKHI_REG (REG_WDEVRX_BASE + 0x0024)
#define WDEV_MACBSSID0_ENA (BIT(16))
#define WDEV_MACBSSID0_ENA_S 16
#define WDEV_MACBSSID0_MASKHI 0x0000FFFF
#define WDEV_MACBSSID0_MASKHI_S 0

#define WDEVBSSID1_MASKLO_REG (REG_WDEVRX_BASE + 0x0028)
#define WDEV_MACBSSID1_MASKLO 0xFFFFFFFF
#define WDEV_MACBSSID1_MASKLO_S 0

#define WDEVBSSID1_MASKHI_REG (REG_WDEVRX_BASE + 0x002C)
#define WDEV_MACBSSID1_ENA (BIT(16))
#define WDEV_MACBSSID1_ENA_S 16
#define WDEV_MACBSSID1_MASKHI 0x0000FFFF
#define WDEV_MACBSSID1_MASKHI_S 0

#define WDEVBSSID2_MASKLO_REG (REG_WDEVRX_BASE + 0x0030)
#define WDEV_MACBSSID2_MASKLO 0xFFFFFFFF
#define WDEV_MACBSSID2_MASKLO_S 0

#define WDEVBSSID2_MASKHI_REG (REG_WDEVRX_BASE + 0x0034)
#define WDEV_MACBSSID2_ENA (BIT(16))
#define WDEV_MACBSSID2_ENA_S 16
#define WDEV_MACBSSID2_MASKHI 0x0000FFFF
#define WDEV_MACBSSID2_MASKHI_S 0

#define WDEVBSSID3_MASKLO_REG (REG_WDEVRX_BASE + 0x0038)
#define WDEV_MACBSSID3_MASKLO 0xFFFFFFFF
#define WDEV_MACBSSID3_MASKLO_S 0

#define WDEVBSSID3_MASKHI_REG (REG_WDEVRX_BASE + 0x003C)
#define WDEV_MACBSSID3_ENA (BIT(16))
#define WDEV_MACBSSID3_ENA_S 16
#define WDEV_MACBSSID3_MASKHI 0x0000FFFF
#define WDEV_MACBSSID3_MASKHI_S 0

#define WDEVDA0LO_REG (REG_WDEVRX_BASE + 0x0040)
#define WDEV_MACDA0_LO 0xFFFFFFFF
#define WDEV_MACDA0_LO_S 0

#define WDEVDA0HI_REG (REG_WDEVRX_BASE + 0x0044)
#define WDEV_MACDA0_HI 0x0000FFFF
#define WDEV_MACDA0_HI_S 0

#define WDEVDA1LO_REG (REG_WDEVRX_BASE + 0x0048)
#define WDEV_MACDA1_LO 0xFFFFFFFF
#define WDEV_MACDA1_LO_S 0

#define WDEVDA1HI_REG (REG_WDEVRX_BASE + 0x004C)
#define WDEV_MACDA1_HI 0x0000FFFF
#define WDEV_MACDA1_HI_S 0

#define WDEVDA2LO_REG (REG_WDEVRX_BASE + 0x0050)
#define WDEV_MACDA2_LO 0xFFFFFFFF
#define WDEV_MACDA2_LO_S 0

#define WDEVDA2HI_REG (REG_WDEVRX_BASE + 0x0054)
#define WDEV_MACDA2_HI 0x0000FFFF
#define WDEV_MACDA2_HI_S 0

#define WDEVDA3LO_REG (REG_WDEVRX_BASE + 0x0058)
#define WDEV_MACDA3_LO 0xFFFFFFFF
#define WDEV_MACDA3_LO_S 0

#define WDEVDA3HI_REG (REG_WDEVRX_BASE + 0x005C)
#define WDEV_MACDA3_HI 0x0000FFFF
#define WDEV_MACDA3_HI_S 0

#define WDEVDA0_MASKLO_REG (REG_WDEVRX_BASE + 0x0060)
#define WDEV_MACDA0_MASKLO 0xFFFFFFFF
#define WDEV_MACDA0_MASKLO_S 0

#define WDEVDA0_MASKHI_REG (REG_WDEVRX_BASE + 0x0064)
#define WDEV_MACDA0_ENA (BIT(16))
#define WDEV_MACDA0_ENA_S 16
#define WDEV_MACDA0_MASKHI 0x0000FFFF
#define WDEV_MACDA0_MASKHI_S 0

#define WDEVDA1_MASKLO_REG (REG_WDEVRX_BASE + 0x0068)
#define WDEV_MACDA1_MASKLO 0xFFFFFFFF
#define WDEV_MACDA1_MASKLO_S 0

#define WDEVDA1_MASKHI_REG (REG_WDEVRX_BASE + 0x006C)
#define WDEV_MACDA1_ENA (BIT(16))
#define WDEV_MACDA1_ENA_S 16
#define WDEV_MACDA1_MASKHI 0x0000FFFF
#define WDEV_MACDA1_MASKHI_S 0

#define WDEVDA2_MASKLO_REG (REG_WDEVRX_BASE + 0x0070)
#define WDEV_MACDA2_MASKLO 0xFFFFFFFF
#define WDEV_MACDA2_MASKLO_S 0

#define WDEVDA2_MASKHI_REG (REG_WDEVRX_BASE + 0x0074)
#define WDEV_MACDA2_ENA (BIT(16))
#define WDEV_MACDA2_ENA_S 16
#define WDEV_MACDA2_MASKHI 0x0000FFFF
#define WDEV_MACDA2_MASKHI_S 0

#define WDEVDA3_MASKLO_REG (REG_WDEVRX_BASE + 0x0078)
#define WDEV_MACDA3_MASKLO 0xFFFFFFFF
#define WDEV_MACDA3_MASKLO_S 0

#define WDEVDA3_MASKHI_REG (REG_WDEVRX_BASE + 0x007C)
#define WDEV_MACDA3_ENA (BIT(16))
#define WDEV_MACDA3_ENA_S 16
#define WDEV_MACDA3_MASKHI 0x0000FFFF
#define WDEV_MACDA3_MASKHI_S 0

#define WDEVRXBUF_CONF_REG (REG_WDEVRX_BASE + 0x0080)
#define WDEV_RXAPLK_ENA (BIT(29))
#define WDEV_RXAPLK_ENA_S 29
#define WDEV_RXDUMPCON_ENA (BIT(28))
#define WDEV_RXDUMPCON_ENA_S 28
#define WDEV_RXRESBUF_SIZE 0x000000FF
#define WDEV_RXRESBUF_SIZE_S 0

#define WDEVRXESTMODE_REG (REG_WDEVRX_BASE + 0x0084)
#define WDEV_RXEST_ENA_FRC (BIT(31))
#define WDEV_RXEST_ENA_FRC_S 31
#define WDEV_RXEST_ENA_SUC (BIT(30))
#define WDEV_RXEST_ENA_SUC_S 30
#define WDEV_RXEST_ENA_ANY (BIT(29))
#define WDEV_RXEST_ENA_ANY_S 29
#define WDEV_RXEST_SIZE 0x00000FFF
#define WDEV_RXEST_SIZE_S 0

#define WDEVRXMODE_REG (REG_WDEVRX_BASE + 0x0088)
#define WDEV_RXBUFLK_ENA_FRC (BIT(31))
#define WDEV_RXBUFLK_ENA_FRC_S 31
#define WDEV_RXBUFLK_ENA_SUC (BIT(30))
#define WDEV_RXBUFLK_ENA_SUC_S 30
#define WDEV_RXBUFLK_ENA_ANY (BIT(29))
#define WDEV_RXBUFLK_ENA_ANY_S 29
#define WDEV_RXBUFDSCR_RELOAD (BIT(0))
#define WDEV_RXBUFDSCR_RELOAD_S 0

#define WDEVRXESTBASE_REG (REG_WDEVRX_BASE + 0x008C)
#define WDEV_RXEST_BASE 0xFFFFFFFF
#define WDEV_RXEST_BASE_S 0

#define WDEVRXBASE_REG (REG_WDEVRX_BASE + 0x0090)
#define WDEV_RXBUFLK_BASE 0xFFFFFFFF
#define WDEV_RXBUFLK_BASE_S 0

#define WDEVRXBUFDSCR_NEXT_REG (REG_WDEVRX_BASE + 0x0094)
#define WDEV_NEXT_RXBUFDSCR 0xFFFFFFFF
#define WDEV_NEXT_RXBUFDSCR_S 0

#define WDEVRXBUFDSCR_LAST_REG (REG_WDEVRX_BASE + 0x0098)
#define WDEV_LAST_RXBUFDSCR 0xFFFFFFFF
#define WDEV_LAST_RXBUFDSCR_S 0

#define WDEVRXBUFBK_CNT_REG (REG_WDEVRX_BASE + 0x009C)
#define WDEV_LAST_RXBUFBK_CNT 0x000000FF
#define WDEV_LAST_RXBUFBK_CNT_S 0

#define WDEVRXBUFDSCR_START_REG (REG_WDEVRX_BASE + 0x00A0)
#define WDEV_START_RXBUFDSCR 0xFFFFFFFF
#define WDEV_START_RXBUFDSCR_S 0

#define WDEVRXOPTION_REG (REG_WDEVRX_BASE + 0x00A4)
#define WDEV_RXCLK_EN (BIT(30))
#define WDEV_RXCLK_EN_S 30
#define WDEV_RX_BBFIFO_CLKA_EN (BIT(29))
#define WDEV_RX_BBFIFO_CLKA_EN_S 29
#define WDEV_RX_BBFIFO_CLKB_EN (BIT(28))
#define WDEV_RX_BBFIFO_CLKB_EN_S 28
#define WDEV_RXLASTBLOCK_BUF_ENA (BIT(27))
#define WDEV_RXLASTBLOCK_BUF_ENA_S 27
#define WDEV_BTRXABORT_ENA (BIT(26))
#define WDEV_BTRXABORT_ENA_S 26
#define WDEV_RXCHAEST_DUMP_ENA (BIT(23))
#define WDEV_RXCHAEST_DUMP_ENA_S 23
#define WDEV_RXBUF_DUMP_EST_ENA (BIT(22))
#define WDEV_RXBUF_DUMP_EST_ENA_S 22
#define WDEV_RXBUF_EST_CLOSE (BIT(21))
#define WDEV_RXBUF_EST_CLOSE_S 21
#define WDEV_RXABORTFRSELF_ENA (BIT(20))
#define WDEV_RXABORTFRSELF_ENA_S 20
#define WDEV_RXBLOCK_INT_SIZE 0x000000FF
#define WDEV_RXBLOCK_INT_SIZE_S 8
#define WDEV_RXSAMPDU_INT_SIZE 0x000000FF
#define WDEV_RXSAMPDU_INT_SIZE_S 0

#define WDEVRX_ABORT_CONF_REG (REG_WDEVRX_BASE + 0x00A8)
#define WDEV_RXABORT_BYTENUM 0x000000FF
#define WDEV_RXABORT_BYTENUM_S 24
#define WDEV_BSSIDWDS0_ENA (BIT(23))
#define WDEV_BSSIDWDS0_ENA_S 23
#define WDEV_BSSIDWDS1_ENA (BIT(22))
#define WDEV_BSSIDWDS1_ENA_S 22
#define WDEV_BSSIDWDS2_ENA (BIT(21))
#define WDEV_BSSIDWDS2_ENA_S 21
#define WDEV_BSSIDWDS3_ENA (BIT(20))
#define WDEV_BSSIDWDS3_ENA_S 20
#define WDEV_BSSIDWDS_SEL 0x00000003
#define WDEV_BSSIDWDS_SEL_S 18
#define WDEV_BSSIDSEC_SEL 0x00000003
#define WDEV_BSSIDSEC_SEL_S 16
#define WDEV_BSSID_DEFAULT_SEL 0x0000000F
#define WDEV_BSSID_DEFAULT_SEL_S 12

#define WDEVRXPMD_REG (REG_WDEVRX_BASE + 0x00AC)
#define WDEV_RX_IS_ACK (BIT(26))
#define WDEV_RX_IS_ACK_S 26
#define WDEV_RX_IS_CTS (BIT(25))
#define WDEV_RX_IS_CTS_S 25
#define WDEV_RX_IS_RTS (BIT(24))
#define WDEV_RX_IS_RTS_S 24
#define WDEV_RXDA_AMPDU (BIT(21))
#define WDEV_RXDA_AMPDU_S 21
#define WDEV_RXDA_GROUP (BIT(20))
#define WDEV_RXDA_GROUP_S 20
#define WDEV_RXBSSID_MATCH1 (BIT(19))
#define WDEV_RXBSSID_MATCH1_S 19
#define WDEV_RXBSSID_MATCH0 (BIT(18))
#define WDEV_RXBSSID_MATCH0_S 18
#define WDEV_RXDA_MATCH1 (BIT(17))
#define WDEV_RXDA_MATCH1_S 17
#define WDEV_RXDA_MATCH0 (BIT(16))
#define WDEV_RXDA_MATCH0_S 16
#define WDEV_RXEND_STATE 0x0000FFFF
#define WDEV_RXEND_STATE_S 0

#define WDEVRXPLCP_REG (REG_WDEVRX_BASE + 0x00B0)
#define WDEV_RX_RSSI 0x000000FF
#define WDEV_RX_RSSI_S 24
#define WDEV_RX_SIG_MODE 0x00000003
#define WDEV_RX_SIG_MODE_S 22
#define WDEV_RX_RATE 0x0000001F
#define WDEV_RX_RATE_S 16
#define WDEV_RX_CBW 0x00000003
#define WDEV_RX_CBW_S 12
#define WDEV_RX_LEGACY_LENGTH 0x00000FFF
#define WDEV_RX_LEGACY_LENGTH_S 0

#define WDEVRXHTSIG1_REG (REG_WDEVRX_BASE + 0x00B4)
#define WDEV_RX_HTSIG_LO 0xFFFFFFFF
#define WDEV_RX_HTSIG_LO_S 0

#define WDEVRXHTSIG2_REG (REG_WDEVRX_BASE + 0x00B8)
#define WDEV_RX_HTSIG_HI 0x0000FFFF
#define WDEV_RX_HTSIG_HI_S 0

#define WDEVRXMPDU0_REG (REG_WDEVRX_BASE + 0x00BC)
#define WDEV_RX_MPDU0 0xFFFFFFFF
#define WDEV_RX_MPDU0_S 0

#define WDEVRXMPDU1_REG (REG_WDEVRX_BASE + 0x00C0)
#define WDEV_RX_MPDU1 0xFFFFFFFF
#define WDEV_RX_MPDU1_S 0

#define WDEVRXMPDU2_REG (REG_WDEVRX_BASE + 0x00C4)
#define WDEV_RX_MPDU2 0xFFFFFFFF
#define WDEV_RX_MPDU2_S 0

#define WDEVRXMPDU3_REG (REG_WDEVRX_BASE + 0x00C8)
#define WDEV_RX_MPDU3 0xFFFFFFFF
#define WDEV_RX_MPDU3_S 0

#define WDEVRXMPDU4_REG (REG_WDEVRX_BASE + 0x00CC)
#define WDEV_RX_MPDU4 0xFFFFFFFF
#define WDEV_RX_MPDU4_S 0

#define WDEVRXMPDU5_REG (REG_WDEVRX_BASE + 0x00D0)
#define WDEV_RX_MPDU5 0xFFFFFFFF
#define WDEV_RX_MPDU5_S 0

#define WDEVRXMPDU6_REG (REG_WDEVRX_BASE + 0x00D4)
#define WDEV_RX_MPDU6 0xFFFFFFFF
#define WDEV_RX_MPDU6_S 0

#define WDEVRXMPDU7_REG (REG_WDEVRX_BASE + 0x00D8)
#define WDEV_RX_MPDU7 0xFFFFFFFF
#define WDEV_RX_MPDU7_S 0

#define WDEVRX_CONF_REG (REG_WDEVRX_BASE + 0x00DC)
#define WDEV_FRMHDR_ALIGN (BIT(0))
#define WDEV_FRMHDR_ALIGN_S 0

#define WDEVRX_ABORT0_REG (REG_WDEVRX_BASE + 0x00E0)
#define WDEV_AUTOACK_SECTKIPERR0_DIS (BIT(17))
#define WDEV_AUTOACK_SECTKIPERR0_DIS_S 17
#define WDEV_AUTOACK_SECERR0_DIS (BIT(16))
#define WDEV_AUTOACK_SECERR0_DIS_S 16
#define WDEV_AUTOACK_DISABLE0 (BIT(15))
#define WDEV_AUTOACK_DISABLE0_S 15
#define WDEV_AUTOACK_NOTGROUP0 (BIT(14))
#define WDEV_AUTOACK_NOTGROUP0_S 14
#define WDEV_AUTOACK_BBSSID0CHK (BIT(13))
#define WDEV_AUTOACK_BBSSID0CHK_S 13
#define WDEV_AUTOACK_DA0CHK (BIT(12))
#define WDEV_AUTOACK_DA0CHK_S 12
#define WDEV_AUTOACK_BSSID0CHK (BIT(11))
#define WDEV_AUTOACK_BSSID0CHK_S 11
#define WDEV_AUTOACK_FRDS0CHK (BIT(10))
#define WDEV_AUTOACK_FRDS0CHK_S 10
#define WDEV_AUTOACK_TODS0CHK (BIT(9))
#define WDEV_AUTOACK_TODS0CHK_S 9
#define WDEV_RXMANAGER_NOTCK0_BSSID (BIT(8))
#define WDEV_RXMANAGER_NOTCK0_BSSID_S 8
#define WDEV_RXSECERR_DUMP0_ENA (BIT(7))
#define WDEV_RXSECERR_DUMP0_ENA_S 7
#define WDEV_RXSECTKIPERR_DUMP0_ENA (BIT(6))
#define WDEV_RXSECTKIPERR_DUMP0_ENA_S 6
#define WDEV_RXSAMEBM_DUMP0_ENA (BIT(5))
#define WDEV_RXSAMEBM_DUMP0_ENA_S 5
#define WDEV_RXPASSBEACON0_ENA (BIT(4))
#define WDEV_RXPASSBEACON0_ENA_S 4
#define WDEV_RXABORTGROUP0_ENA (BIT(3))
#define WDEV_RXABORTGROUP0_ENA_S 3
#define WDEV_RXABORTBBSC0_ENA (BIT(2))
#define WDEV_RXABORTBBSC0_ENA_S 2
#define WDEV_RXABORTUBSC0_ENA (BIT(1))
#define WDEV_RXABORTUBSC0_ENA_S 1
#define WDEV_RXABORTUDAC0_ENA (BIT(0))
#define WDEV_RXABORTUDAC0_ENA_S 0

#define WDEVRX_ABORT1_REG (REG_WDEVRX_BASE + 0x00E4)
#define WDEV_AUTOACK_SECTKIPERR1_DIS (BIT(17))
#define WDEV_AUTOACK_SECTKIPERR1_DIS_S 17
#define WDEV_AUTOACK_SECERR1_DIS (BIT(16))
#define WDEV_AUTOACK_SECERR1_DIS_S 16
#define WDEV_AUTOACK_DISABLE1 (BIT(15))
#define WDEV_AUTOACK_DISABLE1_S 15
#define WDEV_AUTOACK_NOTGROUP1 (BIT(14))
#define WDEV_AUTOACK_NOTGROUP1_S 14
#define WDEV_AUTOACK_BBSSID1CHK (BIT(13))
#define WDEV_AUTOACK_BBSSID1CHK_S 13
#define WDEV_AUTOACK_DA1CHK (BIT(12))
#define WDEV_AUTOACK_DA1CHK_S 12
#define WDEV_AUTOACK_BSSID1CHK (BIT(11))
#define WDEV_AUTOACK_BSSID1CHK_S 11
#define WDEV_AUTOACK_FRDS1CHK (BIT(10))
#define WDEV_AUTOACK_FRDS1CHK_S 10
#define WDEV_AUTOACK_TODS1CHK (BIT(9))
#define WDEV_AUTOACK_TODS1CHK_S 9
#define WDEV_RXMANAGER_NOTCK1_BSSID (BIT(8))
#define WDEV_RXMANAGER_NOTCK1_BSSID_S 8
#define WDEV_RXSECERR_DUMP1_ENA (BIT(7))
#define WDEV_RXSECERR_DUMP1_ENA_S 7
#define WDEV_RXSECTKIPERR_DUMP1_ENA (BIT(6))
#define WDEV_RXSECTKIPERR_DUMP1_ENA_S 6
#define WDEV_RXSAMEBM_DUMP1_ENA (BIT(5))
#define WDEV_RXSAMEBM_DUMP1_ENA_S 5
#define WDEV_RXPASSBEACON1_ENA (BIT(4))
#define WDEV_RXPASSBEACON1_ENA_S 4
#define WDEV_RXABORTGROUP1_ENA (BIT(3))
#define WDEV_RXABORTGROUP1_ENA_S 3
#define WDEV_RXABORTBBSC1_ENA (BIT(2))
#define WDEV_RXABORTBBSC1_ENA_S 2
#define WDEV_RXABORTUBSC1_ENA (BIT(1))
#define WDEV_RXABORTUBSC1_ENA_S 1
#define WDEV_RXABORTUDAC1_ENA (BIT(0))
#define WDEV_RXABORTUDAC1_ENA_S 0

#define WDEVRX_ABORT2_REG (REG_WDEVRX_BASE + 0x00E8)
#define WDEV_AUTOACK_SECTKIPERR2_DIS (BIT(17))
#define WDEV_AUTOACK_SECTKIPERR2_DIS_S 17
#define WDEV_AUTOACK_SECERR2_DIS (BIT(16))
#define WDEV_AUTOACK_SECERR2_DIS_S 16
#define WDEV_AUTOACK_DISABLE2 (BIT(15))
#define WDEV_AUTOACK_DISABLE2_S 15
#define WDEV_AUTOACK_NOTGROUP2 (BIT(14))
#define WDEV_AUTOACK_NOTGROUP2_S 14
#define WDEV_AUTOACK_BBSSID2CHK (BIT(13))
#define WDEV_AUTOACK_BBSSID2CHK_S 13
#define WDEV_AUTOACK_DA2CHK (BIT(12))
#define WDEV_AUTOACK_DA2CHK_S 12
#define WDEV_AUTOACK_BSSID2CHK (BIT(11))
#define WDEV_AUTOACK_BSSID2CHK_S 11
#define WDEV_AUTOACK_FRDS2CHK (BIT(10))
#define WDEV_AUTOACK_FRDS2CHK_S 10
#define WDEV_AUTOACK_TODS2CHK (BIT(9))
#define WDEV_AUTOACK_TODS2CHK_S 9
#define WDEV_RXMANAGER_NOTCK2_BSSID (BIT(8))
#define WDEV_RXMANAGER_NOTCK2_BSSID_S 8
#define WDEV_RXSECERR_DUMP2_ENA (BIT(7))
#define WDEV_RXSECERR_DUMP2_ENA_S 7
#define WDEV_RXSECTKIPERR_DUMP2_ENA (BIT(6))
#define WDEV_RXSECTKIPERR_DUMP2_ENA_S 6
#define WDEV_RXSAMEBM_DUMP2_ENA (BIT(5))
#define WDEV_RXSAMEBM_DUMP2_ENA_S 5
#define WDEV_RXPASSBEACON2_ENA (BIT(4))
#define WDEV_RXPASSBEACON2_ENA_S 4
#define WDEV_RXABORTGROUP2_ENA (BIT(3))
#define WDEV_RXABORTGROUP2_ENA_S 3
#define WDEV_RXABORTBBSC2_ENA (BIT(2))
#define WDEV_RXABORTBBSC2_ENA_S 2
#define WDEV_RXABORTUBSC2_ENA (BIT(1))
#define WDEV_RXABORTUBSC2_ENA_S 1
#define WDEV_RXABORTUDAC2_ENA (BIT(0))
#define WDEV_RXABORTUDAC2_ENA_S 0

#define WDEVRX_ABORT3_REG (REG_WDEVRX_BASE + 0x00EC)
#define WDEV_AUTOACK_SECTKIPERR3_DIS (BIT(17))
#define WDEV_AUTOACK_SECTKIPERR3_DIS_S 17
#define WDEV_AUTOACK_SECERR3_DIS (BIT(16))
#define WDEV_AUTOACK_SECERR3_DIS_S 16
#define WDEV_AUTOACK_DISABLE3 (BIT(15))
#define WDEV_AUTOACK_DISABLE3_S 15
#define WDEV_AUTOACK_NOTGROUP3 (BIT(14))
#define WDEV_AUTOACK_NOTGROUP3_S 14
#define WDEV_AUTOACK_BBSSID3CHK (BIT(13))
#define WDEV_AUTOACK_BBSSID3CHK_S 13
#define WDEV_AUTOACK_DA3CHK (BIT(12))
#define WDEV_AUTOACK_DA3CHK_S 12
#define WDEV_AUTOACK_BSSID3CHK (BIT(11))
#define WDEV_AUTOACK_BSSID3CHK_S 11
#define WDEV_AUTOACK_FRDS3CHK (BIT(10))
#define WDEV_AUTOACK_FRDS3CHK_S 10
#define WDEV_AUTOACK_TODS3CHK (BIT(9))
#define WDEV_AUTOACK_TODS3CHK_S 9
#define WDEV_RXMANAGER_NOTCK3_BSSID (BIT(8))
#define WDEV_RXMANAGER_NOTCK3_BSSID_S 8
#define WDEV_RXSECERR_DUMP3_ENA (BIT(7))
#define WDEV_RXSECERR_DUMP3_ENA_S 7
#define WDEV_RXSECTKIPERR_DUMP3_ENA (BIT(6))
#define WDEV_RXSECTKIPERR_DUMP3_ENA_S 6
#define WDEV_RXSAMEBM_DUMP3_ENA (BIT(5))
#define WDEV_RXSAMEBM_DUMP3_ENA_S 5
#define WDEV_RXPASSBEACON3_ENA (BIT(4))
#define WDEV_RXPASSBEACON3_ENA_S 4
#define WDEV_RXABORTGROUP3_ENA (BIT(3))
#define WDEV_RXABORTGROUP3_ENA_S 3
#define WDEV_RXABORTBBSC3_ENA (BIT(2))
#define WDEV_RXABORTBBSC3_ENA_S 2
#define WDEV_RXABORTUBSC3_ENA (BIT(1))
#define WDEV_RXABORTUBSC3_ENA_S 1
#define WDEV_RXABORTUDAC3_ENA (BIT(0))
#define WDEV_RXABORTUDAC3_ENA_S 0

#define WDEVRX_DUMP0_ERRCODE_REG (REG_WDEVRX_BASE + 0x00F0)
#define WDEV_DUMP0_ERRCODE 0x000000FF
#define WDEV_DUMP0_ERRCODE_S 8
#define WDEV_DUMP0_ERRCODE_MASK 0x000000FF
#define WDEV_DUMP0_ERRCODE_MASK_S 0

#define WDEVRX_DUMP1_ERRCODE_REG (REG_WDEVRX_BASE + 0x00F4)
#define WDEV_DUMP1_ERRCODE 0x000000FF
#define WDEV_DUMP1_ERRCODE_S 8
#define WDEV_DUMP1_ERRCODE_MASK 0x000000FF
#define WDEV_DUMP1_ERRCODE_MASK_S 0

#define WDEVRX_DUMP2_ERRCODE_REG (REG_WDEVRX_BASE + 0x00F8)
#define WDEV_DUMP2_ERRCODE 0x000000FF
#define WDEV_DUMP2_ERRCODE_S 8
#define WDEV_DUMP2_ERRCODE_MASK 0x000000FF
#define WDEV_DUMP2_ERRCODE_MASK_S 0

#define WDEVRX_DUMP3_ERRCODE_REG (REG_WDEVRX_BASE + 0x00FC)
#define WDEV_DUMP3_ERRCODE 0x000000FF
#define WDEV_DUMP3_ERRCODE_S 8
#define WDEV_DUMP3_ERRCODE_MASK 0x000000FF
#define WDEV_DUMP3_ERRCODE_MASK_S 0

#define WDEVRX_DUMP3_ERRCODE1_REG (REG_WDEVRX_BASE + 0x0100)
#define WDEV_DUMP3_ERRCODE1 0x000000FF
#define WDEV_DUMP3_ERRCODE1_S 8
#define WDEV_DUMP3_ERRCODE1_MASK 0x000000FF
#define WDEV_DUMP3_ERRCODE1_MASK_S 0

#define WDEVRX_DUMP3_ERRCODE2_REG (REG_WDEVRX_BASE + 0x0104)
#define WDEV_DUMP3_ERRCODE2 0x000000FF
#define WDEV_DUMP3_ERRCODE2_S 8
#define WDEV_DUMP3_ERRCODE2_MASK 0x000000FF
#define WDEV_DUMP3_ERRCODE2_MASK_S 0

#define WDEVRX_DUMP0_LIM_REG (REG_WDEVRX_BASE + 0x0108)
#define WDEV_RXCTLDUMP0_ENA 0x0000FFFF
#define WDEV_RXCTLDUMP0_ENA_S 16
#define WDEV_RXDUMP0_LEN 0x00000FFF
#define WDEV_RXDUMP0_LEN_S 0

#define WDEVRX_DUMP1_LIM_REG (REG_WDEVRX_BASE + 0x010C)
#define WDEV_RXCTLDUMP1_ENA 0x0000FFFF
#define WDEV_RXCTLDUMP1_ENA_S 16
#define WDEV_RXDUMP1_LEN 0x00000FFF
#define WDEV_RXDUMP1_LEN_S 0

#define WDEVRX_DUMP2_LIM_REG (REG_WDEVRX_BASE + 0x0110)
#define WDEV_RXCTLDUMP2_ENA 0x0000FFFF
#define WDEV_RXCTLDUMP2_ENA_S 16
#define WDEV_RXDUMP2_LEN 0x00000FFF
#define WDEV_RXDUMP2_LEN_S 0

#define WDEVRX_DUMP3_LIM_REG (REG_WDEVRX_BASE + 0x0114)
#define WDEV_RXCTLDUMP3_ENA 0x0000FFFF
#define WDEV_RXCTLDUMP3_ENA_S 16
#define WDEV_RXDUMP3_LEN 0x00000FFF
#define WDEV_RXDUMP3_LEN_S 0

#define WDEVRXCTR_BSSIDLIST_REG (REG_WDEVRX_BASE + 0x0118)
#define WDEV_RXCTL15_BSSID_POS 0x00000003
#define WDEV_RXCTL15_BSSID_POS_S 30
#define WDEV_RXCTL14_BSSID_POS 0x00000003
#define WDEV_RXCTL14_BSSID_POS_S 28
#define WDEV_RXCTL13_BSSID_POS 0x00000003
#define WDEV_RXCTL13_BSSID_POS_S 26
#define WDEV_RXCTL12_BSSID_POS 0x00000003
#define WDEV_RXCTL12_BSSID_POS_S 24
#define WDEV_RXCTL11_BSSID_POS 0x00000003
#define WDEV_RXCTL11_BSSID_POS_S 22
#define WDEV_RXCTL10_BSSID_POS 0x00000003
#define WDEV_RXCTL10_BSSID_POS_S 20
#define WDEV_RXCTL9_BSSID_POS 0x00000003
#define WDEV_RXCTL9_BSSID_POS_S 18
#define WDEV_RXCTL8_BSSID_POS 0x00000003
#define WDEV_RXCTL8_BSSID_POS_S 16
#define WDEV_RXCTL7_BSSID_POS 0x00000003
#define WDEV_RXCTL7_BSSID_POS_S 14
#define WDEV_RXCTL6_BSSID_POS 0x00000003
#define WDEV_RXCTL6_BSSID_POS_S 12
#define WDEV_RXCTL5_BSSID_POS 0x00000003
#define WDEV_RXCTL5_BSSID_POS_S 10
#define WDEV_RXCTL4_BSSID_POS 0x00000003
#define WDEV_RXCTL4_BSSID_POS_S 8
#define WDEV_RXCTL3_BSSID_POS 0x00000003
#define WDEV_RXCTL3_BSSID_POS_S 6
#define WDEV_RXCTL2_BSSID_POS 0x00000003
#define WDEV_RXCTL2_BSSID_POS_S 4
#define WDEV_RXCTL1_BSSID_POS 0x00000003
#define WDEV_RXCTL1_BSSID_POS_S 2
#define WDEV_RXCTL0_BSSID_POS 0x00000003
#define WDEV_RXCTL0_BSSID_POS_S 0

#define WDEVRXQOS_BITMAPUP_LIST_REG (REG_WDEVRX_BASE + 0x011C)
#define WDEV_RXQOS_BITMAPUP7_ENA (BIT(7))
#define WDEV_RXQOS_BITMAPUP7_ENA_S 7
#define WDEV_RXQOS_BITMAPUP6_ENA (BIT(6))
#define WDEV_RXQOS_BITMAPUP6_ENA_S 6
#define WDEV_RXQOS_BITMAPUP5_ENA (BIT(5))
#define WDEV_RXQOS_BITMAPUP5_ENA_S 5
#define WDEV_RXQOS_BITMAPUP4_ENA (BIT(4))
#define WDEV_RXQOS_BITMAPUP4_ENA_S 4
#define WDEV_RXQOS_BITMAPUP3_ENA (BIT(3))
#define WDEV_RXQOS_BITMAPUP3_ENA_S 3
#define WDEV_RXQOS_BITMAPUP2_ENA (BIT(2))
#define WDEV_RXQOS_BITMAPUP2_ENA_S 2
#define WDEV_RXQOS_BITMAPUP1_ENA (BIT(1))
#define WDEV_RXQOS_BITMAPUP1_ENA_S 1
#define WDEV_RXQOS_BITMAPUP0_ENA (BIT(0))
#define WDEV_RXQOS_BITMAPUP0_ENA_S 0

#define WDEVRX_FACKHT_REG (REG_WDEVRX_BASE + 0x0120)
#define WDEV_RX_FAKE_HT (BIT(0))
#define WDEV_RX_FAKE_HT_S 0

#define WDEVRXBBTF_ENA_REG (REG_WDEVRX_BASE + 0x0124)
#define WDEV_RXBBTF_ENA (BIT(31))
#define WDEV_RXBBTF_ENA_S 31
#define WDEV_RXBBTF_TIMER 0x000000FF
#define WDEV_RXBBTF_TIMER_S 20

#define WDEVRXADDR_MAX_REG (REG_WDEVRX_BASE + 0x0128)
#define WDEV_MAXRXADDR 0xFFFFFFFF
#define WDEV_MAXRXADDR_S 0

#define WDEVRXADDR_MIN_REG (REG_WDEVRX_BASE + 0x012C)
#define WDEV_MINRXADDR 0xFFFFFFFF
#define WDEV_MINRXADDR_S 0

#define WDEVRXENT_MAX_REG (REG_WDEVRX_BASE + 0x0130)
#define WDEV_MAXRXENT 0xFFFFFFFF
#define WDEV_MAXRXENT_S 0

#define WDEVRXENT_MIN_REG (REG_WDEVRX_BASE + 0x0134)
#define WDEV_MINRXENT 0xFFFFFFFF
#define WDEV_MINRXENT_S 0

#define WDEVBBABORTOPTION_REG (REG_WDEVRX_BASE + 0x0138)
#define WDEV_BBABORT_ENA (BIT(31))
#define WDEV_BBABORT_ENA_S 31
#define WDEV_DURTRUST_FT 0x0000FFFF
#define WDEV_DURTRUST_FT_S 0

#define WDEVBBNAVOPTION_REG (REG_WDEVRX_BASE + 0x013C)
#define WDEV_BBNAV_ENA (BIT(31))
#define WDEV_BBNAV_ENA_S 31
#define WDEV_BBNAVENA_FT 0x0000FFFF
#define WDEV_BBNAVENA_FT_S 0

#define WDEVBBABORT_RSSITAB0_REG (REG_WDEVRX_BASE + 0x0140)
#define WDEV_BBABORT_RSSI3 0x000000FF
#define WDEV_BBABORT_RSSI3_S 24
#define WDEV_BBABORT_RSSI2 0x000000FF
#define WDEV_BBABORT_RSSI2_S 16
#define WDEV_BBABORT_RSSI1 0x000000FF
#define WDEV_BBABORT_RSSI1_S 8
#define WDEV_BBABORT_RSSI0 0x000000FF
#define WDEV_BBABORT_RSSI0_S 0

#define WDEVBBABORT_RSSITAB1_REG (REG_WDEVRX_BASE + 0x0144)
#define WDEV_BBABORT_RSSI7 0x000000FF
#define WDEV_BBABORT_RSSI7_S 24
#define WDEV_BBABORT_RSSI6 0x000000FF
#define WDEV_BBABORT_RSSI6_S 16
#define WDEV_BBABORT_RSSI5 0x000000FF
#define WDEV_BBABORT_RSSI5_S 8
#define WDEV_BBABORT_RSSI4 0x000000FF
#define WDEV_BBABORT_RSSI4_S 0

#define WDEVBBABORT_LENTAB0_REG (REG_WDEVRX_BASE + 0x0148)
#define WDEV_BBABORT_LEN3 0x000000FF
#define WDEV_BBABORT_LEN3_S 24
#define WDEV_BBABORT_LEN2 0x000000FF
#define WDEV_BBABORT_LEN2_S 16
#define WDEV_BBABORT_LEN1 0x000000FF
#define WDEV_BBABORT_LEN1_S 8
#define WDEV_BBABORT_LEN0 0x000000FF
#define WDEV_BBABORT_LEN0_S 0

#define WDEVBBABORT_LENTAB1_REG (REG_WDEVRX_BASE + 0x014C)
#define WDEV_BBABORT_LEN7 0x000000FF
#define WDEV_BBABORT_LEN7_S 24
#define WDEV_BBABORT_LEN6 0x000000FF
#define WDEV_BBABORT_LEN6_S 16
#define WDEV_BBABORT_LEN5 0x000000FF
#define WDEV_BBABORT_LEN5_S 8
#define WDEV_BBABORT_LEN4 0x000000FF
#define WDEV_BBABORT_LEN4_S 0

#define WDEVRX_TXACK_TIMER_CYC_REG (REG_WDEVRX_BASE + 0x0150)
#define WDEV_RXTXACK_TIMER_START (BIT(31))
#define WDEV_RXTXACK_TIMER_START_S 31
#define WDEV_RXTXACK_TIMER_VALID (BIT(30))
#define WDEV_RXTXACK_TIMER_VALID_S 30
#define WDEV_RXTXACK_TIMER_CYC 0x0000007F
#define WDEV_RXTXACK_TIMER_CYC_S 0

#define WDEVRX_TXACK_TIMER_US_REG (REG_WDEVRX_BASE + 0x0154)
#define WDEV_RXTXACK_TIMER_US 0xFFFFFFFF
#define WDEV_RXTXACK_TIMER_US_S 0

#define WDEVRX_DATA_DUMP_CONF_REG (REG_WDEVRX_BASE + 0x0158)
#define WDEV_RXEST_DUMP_FILTER0_OP (BIT(27))
#define WDEV_RXEST_DUMP_FILTER0_OP_S 27
#define WDEV_RXEST_DUMP_FILTER1_OP (BIT(26))
#define WDEV_RXEST_DUMP_FILTER1_OP_S 26
#define WDEV_RXEST_DUMP_FILTER2_OP (BIT(25))
#define WDEV_RXEST_DUMP_FILTER2_OP_S 25
#define WDEV_RXEST_DUMP_FILTER3_OP (BIT(24))
#define WDEV_RXEST_DUMP_FILTER3_OP_S 24
#define WDEV_RXEST_DUMP_FILTER4_OP (BIT(23))
#define WDEV_RXEST_DUMP_FILTER4_OP_S 23
#define WDEV_RXEST_DUMP_FILTER5_OP (BIT(22))
#define WDEV_RXEST_DUMP_FILTER5_OP_S 22
#define WDEV_RXEST_DUMP_FILTER6_OP (BIT(21))
#define WDEV_RXEST_DUMP_FILTER6_OP_S 21
#define WDEV_RXEST_DUMP_FILTER0_ENA (BIT(20))
#define WDEV_RXEST_DUMP_FILTER0_ENA_S 20
#define WDEV_RXEST_DUMP_FILTER1_ENA (BIT(19))
#define WDEV_RXEST_DUMP_FILTER1_ENA_S 19
#define WDEV_RXEST_DUMP_FILTER2_ENA (BIT(18))
#define WDEV_RXEST_DUMP_FILTER2_ENA_S 18
#define WDEV_RXEST_DUMP_FILTER3_ENA (BIT(17))
#define WDEV_RXEST_DUMP_FILTER3_ENA_S 17
#define WDEV_RXEST_DUMP_FILTER4_ENA (BIT(16))
#define WDEV_RXEST_DUMP_FILTER4_ENA_S 16
#define WDEV_RXEST_DUMP_FILTER5_ENA (BIT(15))
#define WDEV_RXEST_DUMP_FILTER5_ENA_S 15
#define WDEV_RXEST_DUMP_FILTER6_ENA (BIT(14))
#define WDEV_RXEST_DUMP_FILTER6_ENA_S 14
#define WDEV_LASTBUF_DUMP_FILTER0_OP (BIT(13))
#define WDEV_LASTBUF_DUMP_FILTER0_OP_S 13
#define WDEV_LASTBUF_DUMP_FILTER1_OP (BIT(12))
#define WDEV_LASTBUF_DUMP_FILTER1_OP_S 12
#define WDEV_LASTBUF_DUMP_FILTER2_OP (BIT(11))
#define WDEV_LASTBUF_DUMP_FILTER2_OP_S 11
#define WDEV_LASTBUF_DUMP_FILTER3_OP (BIT(10))
#define WDEV_LASTBUF_DUMP_FILTER3_OP_S 10
#define WDEV_LASTBUF_DUMP_FILTER4_OP (BIT(9))
#define WDEV_LASTBUF_DUMP_FILTER4_OP_S 9
#define WDEV_LASTBUF_DUMP_FILTER5_OP (BIT(8))
#define WDEV_LASTBUF_DUMP_FILTER5_OP_S 8
#define WDEV_LASTBUF_DUMP_FILTER6_OP (BIT(7))
#define WDEV_LASTBUF_DUMP_FILTER6_OP_S 7
#define WDEV_LASTBUF_DUMP_FILTER0_ENA (BIT(6))
#define WDEV_LASTBUF_DUMP_FILTER0_ENA_S 6
#define WDEV_LASTBUF_DUMP_FILTER1_ENA (BIT(5))
#define WDEV_LASTBUF_DUMP_FILTER1_ENA_S 5
#define WDEV_LASTBUF_DUMP_FILTER2_ENA (BIT(4))
#define WDEV_LASTBUF_DUMP_FILTER2_ENA_S 4
#define WDEV_LASTBUF_DUMP_FILTER3_ENA (BIT(3))
#define WDEV_LASTBUF_DUMP_FILTER3_ENA_S 3
#define WDEV_LASTBUF_DUMP_FILTER4_ENA (BIT(2))
#define WDEV_LASTBUF_DUMP_FILTER4_ENA_S 2
#define WDEV_LASTBUF_DUMP_FILTER5_ENA (BIT(1))
#define WDEV_LASTBUF_DUMP_FILTER5_ENA_S 1
#define WDEV_LASTBUF_DUMP_FILTER6_ENA (BIT(0))
#define WDEV_LASTBUF_DUMP_FILTER6_ENA_S 0

#define WDEVRX_DATA_DUMP_CONF1_REG (REG_WDEVRX_BASE + 0x015C)
#define WDEV_TXACKTIMER_DUMP_FILTER0_OP (BIT(13))
#define WDEV_TXACKTIMER_DUMP_FILTER0_OP_S 13
#define WDEV_TXACKTIMER_DUMP_FILTER1_OP (BIT(12))
#define WDEV_TXACKTIMER_DUMP_FILTER1_OP_S 12
#define WDEV_TXACKTIMER_DUMP_FILTER2_OP (BIT(11))
#define WDEV_TXACKTIMER_DUMP_FILTER2_OP_S 11
#define WDEV_TXACKTIMER_DUMP_FILTER3_OP (BIT(10))
#define WDEV_TXACKTIMER_DUMP_FILTER3_OP_S 10
#define WDEV_TXACKTIMER_DUMP_FILTER4_OP (BIT(9))
#define WDEV_TXACKTIMER_DUMP_FILTER4_OP_S 9
#define WDEV_TXACKTIMER_DUMP_FILTER5_OP (BIT(8))
#define WDEV_TXACKTIMER_DUMP_FILTER5_OP_S 8
#define WDEV_TXACKTIMER_DUMP_FILTER6_OP (BIT(7))
#define WDEV_TXACKTIMER_DUMP_FILTER6_OP_S 7
#define WDEV_TXACKTIMER_DUMP_FILTER0_ENA (BIT(6))
#define WDEV_TXACKTIMER_DUMP_FILTER0_ENA_S 6
#define WDEV_TXACKTIMER_DUMP_FILTER1_ENA (BIT(5))
#define WDEV_TXACKTIMER_DUMP_FILTER1_ENA_S 5
#define WDEV_TXACKTIMER_DUMP_FILTER2_ENA (BIT(4))
#define WDEV_TXACKTIMER_DUMP_FILTER2_ENA_S 4
#define WDEV_TXACKTIMER_DUMP_FILTER3_ENA (BIT(3))
#define WDEV_TXACKTIMER_DUMP_FILTER3_ENA_S 3
#define WDEV_TXACKTIMER_DUMP_FILTER4_ENA (BIT(2))
#define WDEV_TXACKTIMER_DUMP_FILTER4_ENA_S 2
#define WDEV_TXACKTIMER_DUMP_FILTER5_ENA (BIT(1))
#define WDEV_TXACKTIMER_DUMP_FILTER5_ENA_S 1
#define WDEV_TXACKTIMER_DUMP_FILTER6_ENA (BIT(0))
#define WDEV_TXACKTIMER_DUMP_FILTER6_ENA_S 0

#define WDEVRX_DATA_FILTER0_CONF_REG (REG_WDEVRX_BASE + 0x0160)
#define WDEV_RXDATA_FILTER0_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER0_FRBODY_S 17
#define WDEV_RXDATA_FILTER0_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER0_FRPLCP_S 16
#define WDEV_RXDATA_FILTER0_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER0_BSSID_S 12
#define WDEV_RXDATA_FILTER0_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER0_OFFSET_S 0

#define WDEVRX_DATA_FILTER1_CONF_REG (REG_WDEVRX_BASE + 0x0164)
#define WDEV_RXDATA_FILTER1_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER1_FRBODY_S 17
#define WDEV_RXDATA_FILTER1_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER1_FRPLCP_S 16
#define WDEV_RXDATA_FILTER1_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER1_BSSID_S 12
#define WDEV_RXDATA_FILTER1_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER1_OFFSET_S 0

#define WDEVRX_DATA_FILTER2_CONF_REG (REG_WDEVRX_BASE + 0x0168)
#define WDEV_RXDATA_FILTER2_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER2_FRBODY_S 17
#define WDEV_RXDATA_FILTER2_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER2_FRPLCP_S 16
#define WDEV_RXDATA_FILTER2_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER2_BSSID_S 12
#define WDEV_RXDATA_FILTER2_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER2_OFFSET_S 0

#define WDEVRX_DATA_FILTER3_CONF_REG (REG_WDEVRX_BASE + 0x016C)
#define WDEV_RXDATA_FILTER3_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER3_FRBODY_S 17
#define WDEV_RXDATA_FILTER3_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER3_FRPLCP_S 16
#define WDEV_RXDATA_FILTER3_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER3_BSSID_S 12
#define WDEV_RXDATA_FILTER3_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER3_OFFSET_S 0

#define WDEVRX_DATA_FILTER4_CONF_REG (REG_WDEVRX_BASE + 0x0170)
#define WDEV_RXDATA_FILTER4_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER4_FRBODY_S 17
#define WDEV_RXDATA_FILTER4_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER4_FRPLCP_S 16
#define WDEV_RXDATA_FILTER4_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER4_BSSID_S 12
#define WDEV_RXDATA_FILTER4_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER4_OFFSET_S 0

#define WDEVRX_DATA_FILTER5_CONF_REG (REG_WDEVRX_BASE + 0x0174)
#define WDEV_RXDATA_FILTER5_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER5_FRBODY_S 17
#define WDEV_RXDATA_FILTER5_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER5_FRPLCP_S 16
#define WDEV_RXDATA_FILTER5_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER5_BSSID_S 12
#define WDEV_RXDATA_FILTER5_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER5_OFFSET_S 0

#define WDEVRX_DATA_FILTER6_CONF_REG (REG_WDEVRX_BASE + 0x0178)
#define WDEV_RXDATA_FILTER6_FRBODY (BIT(17))
#define WDEV_RXDATA_FILTER6_FRBODY_S 17
#define WDEV_RXDATA_FILTER6_FRPLCP (BIT(16))
#define WDEV_RXDATA_FILTER6_FRPLCP_S 16
#define WDEV_RXDATA_FILTER6_BSSID 0x0000000F
#define WDEV_RXDATA_FILTER6_BSSID_S 12
#define WDEV_RXDATA_FILTER6_OFFSET 0x00000FFF
#define WDEV_RXDATA_FILTER6_OFFSET_S 0

#define WDEVRX_DATA_FILTER0_DATA_REG (REG_WDEVRX_BASE + 0x017C)
#define WDEV_RXDATA_FILTER0_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER0_DATA_S 0

#define WDEVRX_DATA_FILTER1_DATA_REG (REG_WDEVRX_BASE + 0x0180)
#define WDEV_RXDATA_FILTER1_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER1_DATA_S 0

#define WDEVRX_DATA_FILTER2_DATA_REG (REG_WDEVRX_BASE + 0x0184)
#define WDEV_RXDATA_FILTER2_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER2_DATA_S 0

#define WDEVRX_DATA_FILTER3_DATA_REG (REG_WDEVRX_BASE + 0x0188)
#define WDEV_RXDATA_FILTER3_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER3_DATA_S 0

#define WDEVRX_DATA_FILTER4_DATA_REG (REG_WDEVRX_BASE + 0x018C)
#define WDEV_RXDATA_FILTER4_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER4_DATA_S 0

#define WDEVRX_DATA_FILTER5_DATA_REG (REG_WDEVRX_BASE + 0x0190)
#define WDEV_RXDATA_FILTER5_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER5_DATA_S 0

#define WDEVRX_DATA_FILTER6_DATA_REG (REG_WDEVRX_BASE + 0x0194)
#define WDEV_RXDATA_FILTER6_DATA 0xFFFFFFFF
#define WDEV_RXDATA_FILTER6_DATA_S 0

#define WDEVRX_DATA_FILTER0_MASK_REG (REG_WDEVRX_BASE + 0x0198)
#define WDEV_RXDATA_FILTER0_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER0_MASK_S 0

#define WDEVRX_DATA_FILTER1_MASK_REG (REG_WDEVRX_BASE + 0x019C)
#define WDEV_RXDATA_FILTER1_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER1_MASK_S 0

#define WDEVRX_DATA_FILTER2_MASK_REG (REG_WDEVRX_BASE + 0x01A0)
#define WDEV_RXDATA_FILTER2_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER2_MASK_S 0

#define WDEVRX_DATA_FILTER3_MASK_REG (REG_WDEVRX_BASE + 0x01A4)
#define WDEV_RXDATA_FILTER3_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER3_MASK_S 0

#define WDEVRX_DATA_FILTER4_MASK_REG (REG_WDEVRX_BASE + 0x01A8)
#define WDEV_RXDATA_FILTER4_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER4_MASK_S 0

#define WDEVRX_DATA_FILTER5_MASK_REG (REG_WDEVRX_BASE + 0x01AC)
#define WDEV_RXDATA_FILTER5_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER5_MASK_S 0

#define WDEVRX_DATA_FILTER6_MASK_REG (REG_WDEVRX_BASE + 0x01B0)
#define WDEV_RXDATA_FILTER6_MASK 0xFFFFFFFF
#define WDEV_RXDATA_FILTER6_MASK_S 0

#define WDEVRXBA7_CONF_REG (REG_WDEVRX_BASE + 0x01B4)
#define WDEV_RXBA7_ENA (BIT(31))
#define WDEV_RXBA7_ENA_S 31
#define WDEV_RXBA7_IMR (BIT(30))
#define WDEV_RXBA7_IMR_S 30
#define WDEV_RXBA7_TID 0x0000000F
#define WDEV_RXBA7_TID_S 12
#define WDEV_RXBA7_COMPBM (BIT(2))
#define WDEV_RXBA7_COMPBM_S 2
#define WDEV_RXBA7_MULTITID (BIT(1))
#define WDEV_RXBA7_MULTITID_S 1
#define WDEV_RXBA7_ACKPOLICY (BIT(0))
#define WDEV_RXBA7_ACKPOLICY_S 0

#define WDEVRXBA7_TAHI_REG (REG_WDEVRX_BASE + 0x01B8)
#define WDEV_RXBA7_BSSIDSEL 0x00000003
#define WDEV_RXBA7_BSSIDSEL_S 16
#define WDEV_RXBA7_TAHI 0x0000FFFF
#define WDEV_RXBA7_TAHI_S 0

#define WDEVRXBA7_TALO_REG (REG_WDEVRX_BASE + 0x01BC)
#define WDEV_RXBA7_TALO 0xFFFFFFFF
#define WDEV_RXBA7_TALO_S 0

#define WDEVRXBA7_WINCONF_REG (REG_WDEVRX_BASE + 0x01C0)
#define WDEV_RXBA7_CURR_WS 0x00000FFF
#define WDEV_RXBA7_CURR_WS_S 20
#define WDEV_RXBA7_WINLEN 0x0000007F
#define WDEV_RXBA7_WINLEN_S 13
#define WDEV_RXBA7_WINSTART 0x00000FFF
#define WDEV_RXBA7_WINSTART_S 0

#define WDEVRXBA7_BMHI_SW_REG (REG_WDEVRX_BASE + 0x01C4)
#define WDEV_RXBA7_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA7_BMHI_SW_S 0

#define WDEVRXBA7_BMLO_SW_REG (REG_WDEVRX_BASE + 0x01C8)
#define WDEV_RXBA7_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA7_BMLO_SW_S 0

#define WDEVRXBA7_BMHI_REG (REG_WDEVRX_BASE + 0x01CC)
#define WDEV_RXBA7_BMHI 0xFFFFFFFF
#define WDEV_RXBA7_BMHI_S 0

#define WDEVRXBA7_BMLO_REG (REG_WDEVRX_BASE + 0x01D0)
#define WDEV_RXBA7_BMLO 0xFFFFFFFF
#define WDEV_RXBA7_BMLO_S 0

#define WDEVRXBA6_CONF_REG (REG_WDEVRX_BASE + 0x01D4)
#define WDEV_RXBA6_ENA (BIT(31))
#define WDEV_RXBA6_ENA_S 31
#define WDEV_RXBA6_IMR (BIT(30))
#define WDEV_RXBA6_IMR_S 30
#define WDEV_RXBA6_TID 0x0000000F
#define WDEV_RXBA6_TID_S 12
#define WDEV_RXBA6_COMPBM (BIT(2))
#define WDEV_RXBA6_COMPBM_S 2
#define WDEV_RXBA6_MULTITID (BIT(1))
#define WDEV_RXBA6_MULTITID_S 1
#define WDEV_RXBA6_ACKPOLICY (BIT(0))
#define WDEV_RXBA6_ACKPOLICY_S 0

#define WDEVRXBA6_TAHI_REG (REG_WDEVRX_BASE + 0x01D8)
#define WDEV_RXBA6_BSSIDSEL 0x00000003
#define WDEV_RXBA6_BSSIDSEL_S 16
#define WDEV_RXBA6_TAHI 0x0000FFFF
#define WDEV_RXBA6_TAHI_S 0

#define WDEVRXBA6_TALO_REG (REG_WDEVRX_BASE + 0x01DC)
#define WDEV_RXBA6_TALO 0xFFFFFFFF
#define WDEV_RXBA6_TALO_S 0

#define WDEVRXBA6_WINCONF_REG (REG_WDEVRX_BASE + 0x01E0)
#define WDEV_RXBA6_CURR_WS 0x00000FFF
#define WDEV_RXBA6_CURR_WS_S 20
#define WDEV_RXBA6_WINLEN 0x0000007F
#define WDEV_RXBA6_WINLEN_S 13
#define WDEV_RXBA6_WINSTART 0x00000FFF
#define WDEV_RXBA6_WINSTART_S 0

#define WDEVRXBA6_BMHI_SW_REG (REG_WDEVRX_BASE + 0x01E4)
#define WDEV_RXBA6_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA6_BMHI_SW_S 0

#define WDEVRXBA6_BMLO_SW_REG (REG_WDEVRX_BASE + 0x01E8)
#define WDEV_RXBA6_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA6_BMLO_SW_S 0

#define WDEVRXBA6_BMHI_REG (REG_WDEVRX_BASE + 0x01EC)
#define WDEV_RXBA6_BMHI 0xFFFFFFFF
#define WDEV_RXBA6_BMHI_S 0

#define WDEVRXBA6_BMLO_REG (REG_WDEVRX_BASE + 0x01F0)
#define WDEV_RXBA6_BMLO 0xFFFFFFFF
#define WDEV_RXBA6_BMLO_S 0

#define WDEVRXBA5_CONF_REG (REG_WDEVRX_BASE + 0x01F4)
#define WDEV_RXBA5_ENA (BIT(31))
#define WDEV_RXBA5_ENA_S 31
#define WDEV_RXBA5_IMR (BIT(30))
#define WDEV_RXBA5_IMR_S 30
#define WDEV_RXBA5_TID 0x0000000F
#define WDEV_RXBA5_TID_S 12
#define WDEV_RXBA5_COMPBM (BIT(2))
#define WDEV_RXBA5_COMPBM_S 2
#define WDEV_RXBA5_MULTITID (BIT(1))
#define WDEV_RXBA5_MULTITID_S 1
#define WDEV_RXBA5_ACKPOLICY (BIT(0))
#define WDEV_RXBA5_ACKPOLICY_S 0

#define WDEVRXBA5_TAHI_REG (REG_WDEVRX_BASE + 0x01F8)
#define WDEV_RXBA5_BSSIDSEL 0x00000003
#define WDEV_RXBA5_BSSIDSEL_S 16
#define WDEV_RXBA5_TAHI 0x0000FFFF
#define WDEV_RXBA5_TAHI_S 0

#define WDEVRXBA5_TALO_REG (REG_WDEVRX_BASE + 0x01FC)
#define WDEV_RXBA5_TALO 0xFFFFFFFF
#define WDEV_RXBA5_TALO_S 0

#define WDEVRXBA5_WINCONF_REG (REG_WDEVRX_BASE + 0x0200)
#define WDEV_RXBA5_CURR_WS 0x00000FFF
#define WDEV_RXBA5_CURR_WS_S 20
#define WDEV_RXBA5_WINLEN 0x0000007F
#define WDEV_RXBA5_WINLEN_S 13
#define WDEV_RXBA5_WINSTART 0x00000FFF
#define WDEV_RXBA5_WINSTART_S 0

#define WDEVRXBA5_BMHI_SW_REG (REG_WDEVRX_BASE + 0x0204)
#define WDEV_RXBA5_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA5_BMHI_SW_S 0

#define WDEVRXBA5_BMLO_SW_REG (REG_WDEVRX_BASE + 0x0208)
#define WDEV_RXBA5_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA5_BMLO_SW_S 0

#define WDEVRXBA5_BMHI_REG (REG_WDEVRX_BASE + 0x020C)
#define WDEV_RXBA5_BMHI 0xFFFFFFFF
#define WDEV_RXBA5_BMHI_S 0

#define WDEVRXBA5_BMLO_REG (REG_WDEVRX_BASE + 0x0210)
#define WDEV_RXBA5_BMLO 0xFFFFFFFF
#define WDEV_RXBA5_BMLO_S 0

#define WDEVRXBA4_CONF_REG (REG_WDEVRX_BASE + 0x0214)
#define WDEV_RXBA4_ENA (BIT(31))
#define WDEV_RXBA4_ENA_S 31
#define WDEV_RXBA4_IMR (BIT(30))
#define WDEV_RXBA4_IMR_S 30
#define WDEV_RXBA4_TID 0x0000000F
#define WDEV_RXBA4_TID_S 12
#define WDEV_RXBA4_COMPBM (BIT(2))
#define WDEV_RXBA4_COMPBM_S 2
#define WDEV_RXBA4_MULTITID (BIT(1))
#define WDEV_RXBA4_MULTITID_S 1
#define WDEV_RXBA4_ACKPOLICY (BIT(0))
#define WDEV_RXBA4_ACKPOLICY_S 0

#define WDEVRXBA4_TAHI_REG (REG_WDEVRX_BASE + 0x0218)
#define WDEV_RXBA4_BSSIDSEL 0x00000003
#define WDEV_RXBA4_BSSIDSEL_S 16
#define WDEV_RXBA4_TAHI 0x0000FFFF
#define WDEV_RXBA4_TAHI_S 0

#define WDEVRXBA4_TALO_REG (REG_WDEVRX_BASE + 0x021C)
#define WDEV_RXBA4_TALO 0xFFFFFFFF
#define WDEV_RXBA4_TALO_S 0

#define WDEVRXBA4_WINCONF_REG (REG_WDEVRX_BASE + 0x0220)
#define WDEV_RXBA4_CURR_WS 0x00000FFF
#define WDEV_RXBA4_CURR_WS_S 20
#define WDEV_RXBA4_WINLEN 0x0000007F
#define WDEV_RXBA4_WINLEN_S 13
#define WDEV_RXBA4_WINSTART 0x00000FFF
#define WDEV_RXBA4_WINSTART_S 0

#define WDEVRXBA4_BMHI_SW_REG (REG_WDEVRX_BASE + 0x0224)
#define WDEV_RXBA4_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA4_BMHI_SW_S 0

#define WDEVRXBA4_BMLO_SW_REG (REG_WDEVRX_BASE + 0x0228)
#define WDEV_RXBA4_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA4_BMLO_SW_S 0

#define WDEVRXBA4_BMHI_REG (REG_WDEVRX_BASE + 0x022C)
#define WDEV_RXBA4_BMHI 0xFFFFFFFF
#define WDEV_RXBA4_BMHI_S 0

#define WDEVRXBA4_BMLO_REG (REG_WDEVRX_BASE + 0x0230)
#define WDEV_RXBA4_BMLO 0xFFFFFFFF
#define WDEV_RXBA4_BMLO_S 0

#define WDEVRXBA3_CONF_REG (REG_WDEVRX_BASE + 0x0234)
#define WDEV_RXBA3_ENA (BIT(31))
#define WDEV_RXBA3_ENA_S 31
#define WDEV_RXBA3_IMR (BIT(30))
#define WDEV_RXBA3_IMR_S 30
#define WDEV_RXBA3_TID 0x0000000F
#define WDEV_RXBA3_TID_S 12
#define WDEV_RXBA3_COMPBM (BIT(2))
#define WDEV_RXBA3_COMPBM_S 2
#define WDEV_RXBA3_MULTITID (BIT(1))
#define WDEV_RXBA3_MULTITID_S 1
#define WDEV_RXBA3_ACKPOLICY (BIT(0))
#define WDEV_RXBA3_ACKPOLICY_S 0

#define WDEVRXBA3_TAHI_REG (REG_WDEVRX_BASE + 0x0238)
#define WDEV_RXBA3_BSSIDSEL 0x00000003
#define WDEV_RXBA3_BSSIDSEL_S 16
#define WDEV_RXBA3_TAHI 0x0000FFFF
#define WDEV_RXBA3_TAHI_S 0

#define WDEVRXBA3_TALO_REG (REG_WDEVRX_BASE + 0x023C)
#define WDEV_RXBA3_TALO 0xFFFFFFFF
#define WDEV_RXBA3_TALO_S 0

#define WDEVRXBA3_WINCONF_REG (REG_WDEVRX_BASE + 0x0240)
#define WDEV_RXBA3_CURR_WS 0x00000FFF
#define WDEV_RXBA3_CURR_WS_S 20
#define WDEV_RXBA3_WINLEN 0x0000007F
#define WDEV_RXBA3_WINLEN_S 13
#define WDEV_RXBA3_WINSTART 0x00000FFF
#define WDEV_RXBA3_WINSTART_S 0

#define WDEVRXBA3_BMHI_SW_REG (REG_WDEVRX_BASE + 0x0244)
#define WDEV_RXBA3_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA3_BMHI_SW_S 0

#define WDEVRXBA3_BMLO_SW_REG (REG_WDEVRX_BASE + 0x0248)
#define WDEV_RXBA3_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA3_BMLO_SW_S 0

#define WDEVRXBA3_BMHI_REG (REG_WDEVRX_BASE + 0x024C)
#define WDEV_RXBA3_BMHI 0xFFFFFFFF
#define WDEV_RXBA3_BMHI_S 0

#define WDEVRXBA3_BMLO_REG (REG_WDEVRX_BASE + 0x0250)
#define WDEV_RXBA3_BMLO 0xFFFFFFFF
#define WDEV_RXBA3_BMLO_S 0

#define WDEVRXBA2_CONF_REG (REG_WDEVRX_BASE + 0x0254)
#define WDEV_RXBA2_ENA (BIT(31))
#define WDEV_RXBA2_ENA_S 31
#define WDEV_RXBA2_IMR (BIT(30))
#define WDEV_RXBA2_IMR_S 30
#define WDEV_RXBA2_TID 0x0000000F
#define WDEV_RXBA2_TID_S 12
#define WDEV_RXBA2_COMPBM (BIT(2))
#define WDEV_RXBA2_COMPBM_S 2
#define WDEV_RXBA2_MULTITID (BIT(1))
#define WDEV_RXBA2_MULTITID_S 1
#define WDEV_RXBA2_ACKPOLICY (BIT(0))
#define WDEV_RXBA2_ACKPOLICY_S 0

#define WDEVRXBA2_TAHI_REG (REG_WDEVRX_BASE + 0x0258)
#define WDEV_RXBA2_BSSIDSEL 0x00000003
#define WDEV_RXBA2_BSSIDSEL_S 16
#define WDEV_RXBA2_TAHI 0x0000FFFF
#define WDEV_RXBA2_TAHI_S 0

#define WDEVRXBA2_TALO_REG (REG_WDEVRX_BASE + 0x025C)
#define WDEV_RXBA2_TALO 0xFFFFFFFF
#define WDEV_RXBA2_TALO_S 0

#define WDEVRXBA2_WINCONF_REG (REG_WDEVRX_BASE + 0x0260)
#define WDEV_RXBA2_CURR_WS 0x00000FFF
#define WDEV_RXBA2_CURR_WS_S 20
#define WDEV_RXBA2_WINLEN 0x0000007F
#define WDEV_RXBA2_WINLEN_S 13
#define WDEV_RXBA2_WINSTART 0x00000FFF
#define WDEV_RXBA2_WINSTART_S 0

#define WDEVRXBA2_BMHI_SW_REG (REG_WDEVRX_BASE + 0x0264)
#define WDEV_RXBA2_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA2_BMHI_SW_S 0

#define WDEVRXBA2_BMLO_SW_REG (REG_WDEVRX_BASE + 0x0268)
#define WDEV_RXBA2_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA2_BMLO_SW_S 0

#define WDEVRXBA2_BMHI_REG (REG_WDEVRX_BASE + 0x026C)
#define WDEV_RXBA2_BMHI 0xFFFFFFFF
#define WDEV_RXBA2_BMHI_S 0

#define WDEVRXBA2_BMLO_REG (REG_WDEVRX_BASE + 0x0270)
#define WDEV_RXBA2_BMLO 0xFFFFFFFF
#define WDEV_RXBA2_BMLO_S 0

#define WDEVRXBA1_CONF_REG (REG_WDEVRX_BASE + 0x0274)
#define WDEV_RXBA1_ENA (BIT(31))
#define WDEV_RXBA1_ENA_S 31
#define WDEV_RXBA1_IMR (BIT(30))
#define WDEV_RXBA1_IMR_S 30
#define WDEV_RXBA1_TID 0x0000000F
#define WDEV_RXBA1_TID_S 12
#define WDEV_RXBA1_COMPBM (BIT(2))
#define WDEV_RXBA1_COMPBM_S 2
#define WDEV_RXBA1_MULTITID (BIT(1))
#define WDEV_RXBA1_MULTITID_S 1
#define WDEV_RXBA1_ACKPOLICY (BIT(0))
#define WDEV_RXBA1_ACKPOLICY_S 0

#define WDEVRXBA1_TAHI_REG (REG_WDEVRX_BASE + 0x0278)
#define WDEV_RXBA1_BSSIDSEL 0x00000003
#define WDEV_RXBA1_BSSIDSEL_S 16
#define WDEV_RXBA1_TAHI 0x0000FFFF
#define WDEV_RXBA1_TAHI_S 0

#define WDEVRXBA1_TALO_REG (REG_WDEVRX_BASE + 0x027C)
#define WDEV_RXBA1_TALO 0xFFFFFFFF
#define WDEV_RXBA1_TALO_S 0

#define WDEVRXBA1_WINCONF_REG (REG_WDEVRX_BASE + 0x0280)
#define WDEV_RXBA1_CURR_WS 0x00000FFF
#define WDEV_RXBA1_CURR_WS_S 20
#define WDEV_RXBA1_WINLEN 0x0000007F
#define WDEV_RXBA1_WINLEN_S 13
#define WDEV_RXBA1_WINSTART 0x00000FFF
#define WDEV_RXBA1_WINSTART_S 0

#define WDEVRXBA1_BMHI_SW_REG (REG_WDEVRX_BASE + 0x0284)
#define WDEV_RXBA1_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA1_BMHI_SW_S 0

#define WDEVRXBA1_BMLO_SW_REG (REG_WDEVRX_BASE + 0x0288)
#define WDEV_RXBA1_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA1_BMLO_SW_S 0

#define WDEVRXBA1_BMHI_REG (REG_WDEVRX_BASE + 0x028C)
#define WDEV_RXBA1_BMHI 0xFFFFFFFF
#define WDEV_RXBA1_BMHI_S 0

#define WDEVRXBA1_BMLO_REG (REG_WDEVRX_BASE + 0x0290)
#define WDEV_RXBA1_BMLO 0xFFFFFFFF
#define WDEV_RXBA1_BMLO_S 0

#define WDEVRXBA0_CONF_REG (REG_WDEVRX_BASE + 0x0294)
#define WDEV_RXBA0_ENA (BIT(31))
#define WDEV_RXBA0_ENA_S 31
#define WDEV_RXBA0_IMR (BIT(30))
#define WDEV_RXBA0_IMR_S 30
#define WDEV_RXBA0_TID 0x0000000F
#define WDEV_RXBA0_TID_S 12
#define WDEV_RXBA0_COMPBM (BIT(2))
#define WDEV_RXBA0_COMPBM_S 2
#define WDEV_RXBA0_MULTITID (BIT(1))
#define WDEV_RXBA0_MULTITID_S 1
#define WDEV_RXBA0_ACKPOLICY (BIT(0))
#define WDEV_RXBA0_ACKPOLICY_S 0

#define WDEVRXBA0_TAHI_REG (REG_WDEVRX_BASE + 0x0298)
#define WDEV_RXBA0_BSSIDSEL 0x00000003
#define WDEV_RXBA0_BSSIDSEL_S 16
#define WDEV_RXBA0_TAHI 0x0000FFFF
#define WDEV_RXBA0_TAHI_S 0

#define WDEVRXBA0_TALO_REG (REG_WDEVRX_BASE + 0x029C)
#define WDEV_RXBA0_TALO 0xFFFFFFFF
#define WDEV_RXBA0_TALO_S 0

#define WDEVRXBA0_WINCONF_REG (REG_WDEVRX_BASE + 0x02A0)
#define WDEV_RXBA0_CURR_WS 0x00000FFF
#define WDEV_RXBA0_CURR_WS_S 20
#define WDEV_RXBA0_WINLEN 0x0000007F
#define WDEV_RXBA0_WINLEN_S 13
#define WDEV_RXBA0_WINSTART 0x00000FFF
#define WDEV_RXBA0_WINSTART_S 0

#define WDEVRXBA0_BMHI_SW_REG (REG_WDEVRX_BASE + 0x02A4)
#define WDEV_RXBA0_BMHI_SW 0xFFFFFFFF
#define WDEV_RXBA0_BMHI_SW_S 0

#define WDEVRXBA0_BMLO_SW_REG (REG_WDEVRX_BASE + 0x02A8)
#define WDEV_RXBA0_BMLO_SW 0xFFFFFFFF
#define WDEV_RXBA0_BMLO_SW_S 0

#define WDEVRXBA0_BMHI_REG (REG_WDEVRX_BASE + 0x02AC)
#define WDEV_RXBA0_BMHI 0xFFFFFFFF
#define WDEV_RXBA0_BMHI_S 0

#define WDEVRXBA0_BMLO_REG (REG_WDEVRX_BASE + 0x02B0)
#define WDEV_RXBA0_BMLO 0xFFFFFFFF
#define WDEV_RXBA0_BMLO_S 0

#define WDEVTXBA_BMHI_REG (REG_WDEVRX_BASE + 0x02B4)
#define WDEV_TXBA_BMHI 0xFFFFFFFF
#define WDEV_TXBA_BMHI_S 0

#define WDEVTXBA_BMLO_REG (REG_WDEVRX_BASE + 0x02B8)
#define WDEV_TXBA_BMLO 0xFFFFFFFF
#define WDEV_TXBA_BMLO_S 0

#define WDEVTXBA_TAHI_REG (REG_WDEVRX_BASE + 0x02BC)
#define WDEV_TXBA_TAHI 0x0000FFFF
#define WDEV_TXBA_TAHI_S 0

#define WDEVTXBA_TALO_REG (REG_WDEVRX_BASE + 0x02C0)
#define WDEV_TXBA_TALO 0xFFFFFFFF
#define WDEV_TXBA_TALO_S 0

#define WDEVTXBA_SSN_REG (REG_WDEVRX_BASE + 0x02C4)
#define WDEV_TXBA_TID 0x0000000F
#define WDEV_TXBA_TID_S 12
#define WDEV_TXBA_SSN 0x00000FFF
#define WDEV_TXBA_SSN_S 0

#define WDEVRX_ANT_CONF_REG (REG_WDEVRX_BASE + 0x02C8)
#define WDEV_RXTXANT_LAST (BIT(5))
#define WDEV_RXTXANT_LAST_S 5
#define WDEV_RXTXANT_VALUE (BIT(4))
#define WDEV_RXTXANT_VALUE_S 4
#define WDEV_RXTXANT_FORCE (BIT(3))
#define WDEV_RXTXANT_FORCE_S 3
#define WDEV_RXANT_LAST (BIT(2))
#define WDEV_RXANT_LAST_S 2
#define WDEV_RXANT_VALUE (BIT(1))
#define WDEV_RXANT_VALUE_S 1
#define WDEV_RXANT_FORCE (BIT(0))
#define WDEV_RXANT_FORCE_S 0

#define WDEVRX_PTI_CONF_REG (REG_WDEVRX_BASE + 0x02CC)
#define WDEV_RXTXACK_PTI 0x0000000F
#define WDEV_RXTXACK_PTI_S 4
#define WDEV_RXACTIVE_PTI 0x0000000F
#define WDEV_RXACTIVE_PTI_S 0

#define WDEVRX_STATIS_CLEAR_REG (REG_WDEVRX_BASE + 0x02D0)
#define WDEV_RX_STATIS_ENA (BIT(1))
#define WDEV_RX_STATIS_ENA_S 1
#define WDEV_RX_STATIS_CLEAR (BIT(0))
#define WDEV_RX_STATIS_CLEAR_S 0

#define WDEVRX_CCK_ERRCNT_REG (REG_WDEVRX_BASE + 0x02D4)
#define WDEV_RXCCK_ERR_CNT 0xFFFFFFFF
#define WDEV_RXCCK_ERR_CNT_S 0

#define WDEVRX_OFDM_ERRCNT_REG (REG_WDEVRX_BASE + 0x02D8)
#define WDEV_RXOFDM_ERR_CNT 0xFFFFFFFF
#define WDEV_RXOFDM_ERR_CNT_S 0

#define WDEVRX_AGC_ERRCNT_REG (REG_WDEVRX_BASE + 0x02DC)
#define WDEV_RXAGC_ERR_CNT 0xFFFFFFFF
#define WDEV_RXAGC_ERR_CNT_S 0

#define WDEVRX_SF_CNT_REG (REG_WDEVRX_BASE + 0x02E0)
#define WDEV_RXSF_CNT 0xFFFFFFFF
#define WDEV_RXSF_CNT_S 0

#define WDEVRX_ABORT_CNT_REG (REG_WDEVRX_BASE + 0x02E4)
#define WDEV_RXABORT_CNT 0xFFFFFFFF
#define WDEV_RXABORT_CNT_S 0

#define WDEVRX_FCS_ERRCNT_REG (REG_WDEVRX_BASE + 0x02E8)
#define WDEV_RXFCS_ERR_CNT 0xFFFFFFFF
#define WDEV_RXFCS_ERR_CNT_S 0

#define WDEVRX_FIFO_OVFCNT_REG (REG_WDEVRX_BASE + 0x02EC)
#define WDEV_RXFIFO_OVF_CNT 0xFFFFFFFF
#define WDEV_RXFIFO_OVF_CNT_S 0

#define WDEVRX_APENTRYBUF_FULLCNT_REG (REG_WDEVRX_BASE + 0x02F0)
#define WDEV_RXAPENTRYBUF_FULL_CNT 0xFFFFFFFF
#define WDEV_RXAPENTRYBUF_FULL_CNT_S 0

#define WDEVRX_BUF_FULLCNT_REG (REG_WDEVRX_BASE + 0x02F4)
#define WDEV_RXBUF_FULL_CNT 0xFFFFFFFF
#define WDEV_RXBUF_FULL_CNT_S 0

#define WDEVRX_OTHER_UNICASTCNT_REG (REG_WDEVRX_BASE + 0x02F8)
#define WDEV_RXOTHER_UNICAST_CNT 0xFFFFFFFF
#define WDEV_RXOTHER_UNICAST_CNT_S 0

#define WDEVRX_TKIP_ERRCNT_REG (REG_WDEVRX_BASE + 0x02FC)
#define WDEV_RXTKIP_ERR_CNT 0xFFFFFFFF
#define WDEV_RXTKIP_ERR_CNT_S 0

#define WDEVRX_SAMEBM_ERRCNT_REG (REG_WDEVRX_BASE + 0x0300)
#define WDEV_RXSAMEBM_ERR_CNT 0xFFFFFFFF
#define WDEV_RXSAMEBM_ERR_CNT_S 0

#define WDEVRXACK_INT_CNT_REG (REG_WDEVRX_BASE + 0x0304)
#define WDEV_RXACKINT_CNT 0xFFFFFFFF
#define WDEV_RXACKINT_CNT_S 0

#define WDEVRXRTS_INT_CNT_REG (REG_WDEVRX_BASE + 0x0308)
#define WDEV_RXRTSINT_CNT 0xFFFFFFFF
#define WDEV_RXRTSINT_CNT_S 0

#define WDEVRXCTS_INT_CNT_REG (REG_WDEVRX_BASE + 0x030C)
#define WDEV_RXCTSINT_CNT 0xFFFFFFFF
#define WDEV_RXCTSINT_CNT_S 0

#define WDEVRXRIFS_INT_CNT_REG (REG_WDEVRX_BASE + 0x0310)
#define WDEV_RXRIFSINT_CNT 0xFFFFFFFF
#define WDEV_RXRIFSINT_CNT_S 0

#define WDEVRX_DATASUC_CNT_REG (REG_WDEVRX_BASE + 0x0314)
#define WDEV_RXDATA_SUC_CNT 0xFFFFFFFF
#define WDEV_RXDATA_SUC_CNT_S 0

#define WDEVRX_END_CNT_REG (REG_WDEVRX_BASE + 0x0318)
#define WDEV_RXEND_CNT 0xFFFFFFFF
#define WDEV_RXEND_CNT_S 0

#define WDEVRX_BTBLOCK_ERR_CNT_REG (REG_WDEVRX_BASE + 0x031C)
#define WDEV_RXBTBLOCK_ERR_CNT 0xFFFFFFFF
#define WDEV_RXBTBLOCK_ERR_CNT_S 0

#define WDEVRX_FREQHOP_ERR_CNT_REG (REG_WDEVRX_BASE + 0x0320)
#define WDEV_RXFREQ_HOP_ERR_CNT 0xFFFFFFFF
#define WDEV_RXFREQ_HOP_ERR_CNT_S 0

#define WDEVRX_LASTUNMATCH_ERR_CNT_REG (REG_WDEVRX_BASE + 0x0324)
#define WDEV_RXLAST_UNMATCH_ERR_CNT 0xFFFFFFFF
#define WDEV_RXLAST_UNMATCH_ERR_CNT_S 0

#define WDEVRX_BLOCK_ERR_CNT_REG (REG_WDEVRX_BASE + 0x0328)
#define WDEV_RXBLOCK_ERR_CNT 0xFFFFFFFF
#define WDEV_RXBLOCK_ERR_CNT_S 0

#define WDEVRXFRAME_LOWTO_REG (REG_WDEVRX_BASE + 0x032C)
#define WDEV_RXFRAME_LOWTO_ENA (BIT(31))
#define WDEV_RXFRAME_LOWTO_ENA_S 31
#define WDEV_RXFRAME_LOWTO_TIMER 0x0000FFFF
#define WDEV_RXFRAME_LOWTO_TIMER_S 0

#define WDEVRX_ERRTO_REG (REG_WDEVRX_BASE + 0x0330)
#define WDEV_RXERR_TO_ENA (BIT(31))
#define WDEV_RXERR_TO_ENA_S 31
#define WDEV_FCSERR_ONLY (BIT(30))
#define WDEV_FCSERR_ONLY_S 30
#define WDEV_RXERR_TO_TIMER 0x0000FFFF
#define WDEV_RXERR_TO_TIMER_S 0

#define WDEVRX_AHB_REG (REG_WDEVRX_BASE + 0x0334)
#define WDEV_RXESTBURST_MAX_LEN 0x0000000F
#define WDEV_RXESTBURST_MAX_LEN_S 8
#define WDEV_RXDSCRBURST_MAX_LEN 0x0000000F
#define WDEV_RXDSCRBURST_MAX_LEN_S 4
#define WDEV_RXBURST_MAX_LEN 0x0000000F
#define WDEV_RXBURST_MAX_LEN_S 0

#define WDEVDIAG4_REG (REG_WDEVRX_BASE + 0x0338)
#define WDEV_MAC_RX_DIAG0 0xFFFFFFFF
#define WDEV_MAC_RX_DIAG0_S 0

#define WDEVDIAG5_REG (REG_WDEVRX_BASE + 0x033C)
#define WDEV_MAC_RX_DIAG1 0xFFFFFFFF
#define WDEV_MAC_RX_DIAG1_S 0

#define WDEVDIAG6_REG (REG_WDEVRX_BASE + 0x0340)
#define WDEV_MAC_RX_DIAG2 0xFFFFFFFF
#define WDEV_MAC_RX_DIAG2_S 0

#define WDEVDIAG7_REG (REG_WDEVRX_BASE + 0x0344)
#define WDEV_MAC_RX_DIAG3 0xFFFFFFFF
#define WDEV_MAC_RX_DIAG3_S 0

#define WDEVRXDATE_REG (REG_WDEVRX_BASE + 0x03F8)
#define WDEV_MACRX_DATE 0x0FFFFFFF
#define WDEV_MACRX_DATE_S 0
#define WDEV_MACRX_DATE_VERSION 0x1802221
