
#define WDEVSEC_CONF0_REG (REG_WDEVSEC_BASE + 0x0000)
#define WDEV_SEC_CONF0 0xFFFFFFFF
#define WDEV_SEC_CONF0_S 0

#define WDEVSEC_CONF1_REG (REG_WDEVSEC_BASE + 0x0004)
#define WDEV_SEC_CONF1 0xFFFFFFFF
#define WDEV_SEC_CONF1_S 0

#define WDEVSEC_CONF10_REG (REG_WDEVSEC_BASE + 0x0008)
#define WDEV_SEC_CONF10 0xFFFFFFFF
#define WDEV_SEC_CONF10_S 0

#define WDEVSEC_CONF11_REG (REG_WDEVSEC_BASE + 0x000C)
#define WDEV_SEC_CONF11 0xFFFFFFFF
#define WDEV_SEC_CONF11_S 0

#define WDEVSEC_CONF2_REG (REG_WDEVSEC_BASE + 0x0010)
#define WDEV_SEC_CONF2 0xFFFFFFFF
#define WDEV_SEC_CONF2_S 0

#define WDEVSEC_CONF3_REG (REG_WDEVSEC_BASE + 0x0014)
#define WDEV_SEC_CONF3 0xFFFFFFFF
#define WDEV_SEC_CONF3_S 0

#define WDEVSEC_CONF4_REG (REG_WDEVSEC_BASE + 0x0018)
#define WDEV_SEC_CONF4 0xFFFFFFFF
#define WDEV_SEC_CONF4_S 0

#define WDEVSEC_CONF5_REG (REG_WDEVSEC_BASE + 0x001C)
#define WDEV_SEC_CONF5 0xFFFFFFFF
#define WDEV_SEC_CONF5_S 0

#define WDEVSEC_CONF6_REG (REG_WDEVSEC_BASE + 0x0020)
#define WDEV_SEC_CONF6 0xFFFFFFFF
#define WDEV_SEC_CONF6_S 0

#define WDEVSEC_CONF7_REG (REG_WDEVSEC_BASE + 0x0024)
#define WDEV_SEC_CONF7 0xFFFFFFFF
#define WDEV_SEC_CONF7_S 0

#define WDEVSEC_CONF8_REG (REG_WDEVSEC_BASE + 0x0028)
#define WDEV_SEC_CONF8 0xFFFFFFFF
#define WDEV_SEC_CONF8_S 0

#define WDEVSEC_CONF9_REG (REG_WDEVSEC_BASE + 0x002C)
#define WDEV_SEC_CONF9 0xFFFFFFFF
#define WDEV_SEC_CONF9_S 0

#define WDEVSEC_STATE0_REG (REG_WDEVSEC_BASE + 0x0030)
#define WDEV_SEC_STATE0 0xFFFFFFFF
#define WDEV_SEC_STATE0_S 0

#define WDEVSEC_STATE1_REG (REG_WDEVSEC_BASE + 0x0034)
#define WDEV_SEC_STATE1 0xFFFFFFFF
#define WDEV_SEC_STATE1_S 0

#define WDEVSEC_STATE2_REG (REG_WDEVSEC_BASE + 0x0038)
#define WDEV_SEC_STATE2 0xFFFFFFFF
#define WDEV_SEC_STATE2_S 0

#define WDEVSEC_STATE3_REG (REG_WDEVSEC_BASE + 0x003C)
#define WDEV_SEC_STATE3 0xFFFFFFFF
#define WDEV_SEC_STATE3_S 0

#define WDEVSEC_CLK_CONF_REG (REG_WDEVSEC_BASE + 0x0040)
#define WDEV_KMEM_CLK_EN (BIT(6))
#define WDEV_KMEM_CLK_EN_S 6
#define WDEV_SECCLK_EN (BIT(5))
#define WDEV_SECCLK_EN_S 5
#define WDEV_SECTX_CLK_EN (BIT(4))
#define WDEV_SECTX_CLK_EN_S 4
#define WDEV_SECRX_CLK_EN (BIT(3))
#define WDEV_SECRX_CLK_EN_S 3
#define WDEV_TKIP_CLK_EN (BIT(2))
#define WDEV_TKIP_CLK_EN_S 2
#define WDEV_WAPI_CLK_EN (BIT(1))
#define WDEV_WAPI_CLK_EN_S 1
#define WDEV_CCMP_CLK_EN (BIT(0))
#define WDEV_CCMP_CLK_EN_S 0

#define WDEVSECDATE_REG (REG_WDEVSEC_BASE + 0x03F8)
#define WDEV_MACSEC_DATE 0x0FFFFFFF
#define WDEV_MACSEC_DATE_S 0
#define WDEV_MACSEC_DATE_VERSION 0x1505051
