
#define RTC_OPTIONS0 (REG_RTCCNTL_BASE + 0x0)
#define RTC_CNTL_SW_SYS_RST (BIT(31))
#define RTC_CNTL_SW_SYS_RST_S 31
#define RTC_CNTL_DG_WRAP_FORCE_NORST (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_NORST_S 30
#define RTC_CNTL_DG_WRAP_FORCE_RST (BIT(29))
#define RTC_CNTL_DG_WRAP_FORCE_RST_S 29
#define RTC_CNTL_ANALOG_FORCE_NOISO (BIT(28))
#define RTC_CNTL_ANALOG_FORCE_NOISO_S 28
#define RTC_CNTL_PLL_FORCE_NOISO (BIT(27))
#define RTC_CNTL_PLL_FORCE_NOISO_S 27
#define RTC_CNTL_XTL_FORCE_NOISO (BIT(26))
#define RTC_CNTL_XTL_FORCE_NOISO_S 26
#define RTC_CNTL_ANALOG_FORCE_ISO (BIT(25))
#define RTC_CNTL_ANALOG_FORCE_ISO_S 25
#define RTC_CNTL_PLL_FORCE_ISO (BIT(24))
#define RTC_CNTL_PLL_FORCE_ISO_S 24
#define RTC_CNTL_XTL_FORCE_ISO (BIT(23))
#define RTC_CNTL_XTL_FORCE_ISO_S 23
#define RTC_CNTL_BIAS_CORE_FORCE_PU (BIT(22))
#define RTC_CNTL_BIAS_CORE_FORCE_PU_S 22
#define RTC_CNTL_BIAS_CORE_FORCE_PD (BIT(21))
#define RTC_CNTL_BIAS_CORE_FORCE_PD_S 21
#define RTC_CNTL_BIAS_CORE_FOLW_8M (BIT(20))
#define RTC_CNTL_BIAS_CORE_FOLW_8M_S 20
#define RTC_CNTL_BIAS_I2C_FORCE_PU (BIT(19))
#define RTC_CNTL_BIAS_I2C_FORCE_PU_S 19
#define RTC_CNTL_BIAS_I2C_FORCE_PD (BIT(18))
#define RTC_CNTL_BIAS_I2C_FORCE_PD_S 18
#define RTC_CNTL_BIAS_I2C_FOLW_8M (BIT(17))
#define RTC_CNTL_BIAS_I2C_FOLW_8M_S 17
#define RTC_CNTL_BIAS_FORCE_NOSLEEP (BIT(16))
#define RTC_CNTL_BIAS_FORCE_NOSLEEP_S 16
#define RTC_CNTL_BIAS_FORCE_SLEEP (BIT(15))
#define RTC_CNTL_BIAS_FORCE_SLEEP_S 15
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M (BIT(14))
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M_S 14
#define RTC_CNTL_XTL_FORCE_PU (BIT(13))
#define RTC_CNTL_XTL_FORCE_PU_S 13
#define RTC_CNTL_XTL_FORCE_PD (BIT(12))
#define RTC_CNTL_XTL_FORCE_PD_S 12
#define RTC_CNTL_BBPLL_FORCE_PU (BIT(11))
#define RTC_CNTL_BBPLL_FORCE_PU_S 11
#define RTC_CNTL_BBPLL_FORCE_PD (BIT(10))
#define RTC_CNTL_BBPLL_FORCE_PD_S 10
#define RTC_CNTL_BBPLL_I2C_FORCE_PU (BIT(9))
#define RTC_CNTL_BBPLL_I2C_FORCE_PU_S 9
#define RTC_CNTL_BBPLL_I2C_FORCE_PD (BIT(8))
#define RTC_CNTL_BBPLL_I2C_FORCE_PD_S 8
#define RTC_CNTL_BB_I2C_FORCE_PU (BIT(7))
#define RTC_CNTL_BB_I2C_FORCE_PU_S 7
#define RTC_CNTL_BB_I2C_FORCE_PD (BIT(6))
#define RTC_CNTL_BB_I2C_FORCE_PD_S 6
#define RTC_CNTL_SW_PROCPU_RST (BIT(5))
#define RTC_CNTL_SW_PROCPU_RST_S 5
#define RTC_CNTL_SW_APPCPU_RST (BIT(4))
#define RTC_CNTL_SW_APPCPU_RST_S 4
#define RTC_CNTL_SW_STALL_PROCPU_C0 0x00000003
#define RTC_CNTL_SW_STALL_PROCPU_C0_S 2
#define RTC_CNTL_SW_STALL_APPCPU_C0 0x00000003
#define RTC_CNTL_SW_STALL_APPCPU_C0_S 0

#define RTC_SLP_TIMER0 (REG_RTCCNTL_BASE + 0x4)
#define RTC_CNTL_SLP_VAL_LO 0xFFFFFFFF
#define RTC_CNTL_SLP_VAL_LO_S 0

#define RTC_SLP_TIMER1 (REG_RTCCNTL_BASE + 0x8)
#define RTC_CNTL_RTC_MAIN_TIMER_ALARM_EN (BIT(16))
#define RTC_CNTL_RTC_MAIN_TIMER_ALARM_EN_S 16
#define RTC_CNTL_SLP_VAL_HI 0x0000FFFF
#define RTC_CNTL_SLP_VAL_HI_S 0

#define RTC_TIME_UPDATE (REG_RTCCNTL_BASE + 0xc)
#define RTC_CNTL_RTC_TIME_UPDATE (BIT(31))
#define RTC_CNTL_RTC_TIME_UPDATE_S 31
#define RTC_CNTL_RTC_TIME_VALID (BIT(30))
#define RTC_CNTL_RTC_TIME_VALID_S 30
#define RTC_CNTL_TIMER_SYS_RST (BIT(29))
#define RTC_CNTL_TIMER_SYS_RST_S 29
#define RTC_CNTL_TIMER_XTL_OFF (BIT(28))
#define RTC_CNTL_TIMER_XTL_OFF_S 28
#define RTC_CNTL_TIMER_SYS_STALL (BIT(27))
#define RTC_CNTL_TIMER_SYS_STALL_S 27

#define RTC_TIME_LOW0 (REG_RTCCNTL_BASE + 0x10)
#define RTC_CNTL_RTC_TIMER_VALUE0_LOW 0xFFFFFFFF
#define RTC_CNTL_RTC_TIMER_VALUE0_LOW_S 0

#define RTC_TIME_HIGH0 (REG_RTCCNTL_BASE + 0x14)
#define RTC_CNTL_RTC_TIMER_VALUE0_HIGH 0x0000FFFF
#define RTC_CNTL_RTC_TIMER_VALUE0_HIGH_S 0

#define RTC_STATE0 (REG_RTCCNTL_BASE + 0x18)
#define RTC_CNTL_SLEEP_EN (BIT(31))
#define RTC_CNTL_SLEEP_EN_S 31
#define RTC_CNTL_SLP_REJECT (BIT(30))
#define RTC_CNTL_SLP_REJECT_S 30
#define RTC_CNTL_SLP_WAKEUP (BIT(29))
#define RTC_CNTL_SLP_WAKEUP_S 29
#define RTC_CNTL_SDIO_ACTIVE_IND (BIT(28))
#define RTC_CNTL_SDIO_ACTIVE_IND_S 28
#define RTC_CNTL_APB2RTC_BRIDGE_SEL (BIT(22))
#define RTC_CNTL_APB2RTC_BRIDGE_SEL_S 22

#define RTC_TIMER1 (REG_RTCCNTL_BASE + 0x1c)
#define RTC_CNTL_PLL_BUF_WAIT 0x000000FF
#define RTC_CNTL_PLL_BUF_WAIT_S 24
#define RTC_CNTL_XTL_BUF_WAIT 0x000003FF
#define RTC_CNTL_XTL_BUF_WAIT_S 14
#define RTC_CNTL_CK8M_WAIT 0x000000FF
#define RTC_CNTL_CK8M_WAIT_S 6
#define RTC_CNTL_CPU_STALL_WAIT 0x0000001F
#define RTC_CNTL_CPU_STALL_WAIT_S 1
#define RTC_CNTL_CPU_STALL_EN (BIT(0))
#define RTC_CNTL_CPU_STALL_EN_S 0

#define RTC_TIMER2 (REG_RTCCNTL_BASE + 0x20)
#define RTC_CNTL_MIN_TIME_CK8M_OFF 0x000000FF
#define RTC_CNTL_MIN_TIME_CK8M_OFF_S 24
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT 0x000001FF
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT_S 15

#define RTC_TIMER3 (REG_RTCCNTL_BASE + 0x24)
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER_S 25
#define RTC_CNTL_ROM_RAM_WAIT_TIMER 0x000001FF
#define RTC_CNTL_ROM_RAM_WAIT_TIMER_S 16
#define RTC_CNTL_WIFI_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_WIFI_POWERUP_TIMER_S 9
#define RTC_CNTL_WIFI_WAIT_TIMER 0x000001FF
#define RTC_CNTL_WIFI_WAIT_TIMER_S 0

#define RTC_TIMER4 (REG_RTCCNTL_BASE + 0x28)
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER_S 25
#define RTC_CNTL_DG_WRAP_WAIT_TIMER 0x000001FF
#define RTC_CNTL_DG_WRAP_WAIT_TIMER_S 16
#define RTC_CNTL_RTC_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_RTC_POWERUP_TIMER_S 9
#define RTC_CNTL_RTC_WAIT_TIMER 0x000001FF
#define RTC_CNTL_RTC_WAIT_TIMER_S 0

#define RTC_TIMER5 (REG_RTCCNTL_BASE + 0x2c)
#define RTC_CNTL_RTCMEM_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_RTCMEM_POWERUP_TIMER_S 25
#define RTC_CNTL_RTCMEM_WAIT_TIMER 0x000001FF
#define RTC_CNTL_RTCMEM_WAIT_TIMER_S 16
#define RTC_CNTL_MIN_SLP_VAL 0x000000FF
#define RTC_CNTL_MIN_SLP_VAL_S 8

#define RTC_TIMER6 (REG_RTCCNTL_BASE + 0x30)
#define RTC_CNTL_DG_DCDC_POWERUP_TIMER 0x0000007F
#define RTC_CNTL_DG_DCDC_POWERUP_TIMER_S 25
#define RTC_CNTL_DG_DCDC_WAIT_TIMER 0x000001FF
#define RTC_CNTL_DG_DCDC_WAIT_TIMER_S 16

#define RTC_ANA_CONF (REG_RTCCNTL_BASE + 0x34)
#define RTC_CNTL_PLL_I2C_PU (BIT(31))
#define RTC_CNTL_PLL_I2C_PU_S 31
#define RTC_CNTL_CKGEN_I2C_PU (BIT(30))
#define RTC_CNTL_CKGEN_I2C_PU_S 30
#define RTC_CNTL_RFRX_PBUS_PU (BIT(28))
#define RTC_CNTL_RFRX_PBUS_PU_S 28
#define RTC_CNTL_TXRF_I2C_PU (BIT(27))
#define RTC_CNTL_TXRF_I2C_PU_S 27
#define RTC_CNTL_PVTMON_PU (BIT(26))
#define RTC_CNTL_PVTMON_PU_S 26
#define RTC_CNTL_BBPLL_CAL_SLP_START (BIT(25))
#define RTC_CNTL_BBPLL_CAL_SLP_START_S 25
#define RTC_CNTL_PLLA_FORCE_PU (BIT(24))
#define RTC_CNTL_PLLA_FORCE_PU_S 24
#define RTC_CNTL_PLLA_FORCE_PD (BIT(23))
#define RTC_CNTL_PLLA_FORCE_PD_S 23

#define RTC_RESET_STATE (REG_RTCCNTL_BASE + 0x38)
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL (BIT(13))
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL_S 13
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL (BIT(12))
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL_S 12
#define RTC_CNTL_RESET_CAUSE_APPCPU 0x0000003F
#define RTC_CNTL_RESET_CAUSE_APPCPU_S 6
#define RTC_CNTL_RESET_CAUSE_PROCPU 0x0000003F
#define RTC_CNTL_RESET_CAUSE_PROCPU_S 0

#define RTC_WAKEUP_STATE (REG_RTCCNTL_BASE + 0x3c)
#define RTC_CNTL_GPIO_WAKEUP_FILTER (BIT(24))
#define RTC_CNTL_GPIO_WAKEUP_FILTER_S 24
#define RTC_CNTL_RTC_WAKEUP_ENA 0x00000FFF
#define RTC_CNTL_RTC_WAKEUP_ENA_S 12
#define RTC_CNTL_WAKEUP_CAUSE 0x00000FFF
#define RTC_CNTL_WAKEUP_CAUSE_S 0

#define INT_ENA_RTC (REG_RTCCNTL_BASE + 0x40)
#define RTC_CNTL_RTC_SWD_INT_ENA (BIT(15))
#define RTC_CNTL_RTC_SWD_INT_ENA_S 15
#define RTC_CNTL_RTC_SARADC2_INT_ENA (BIT(14))
#define RTC_CNTL_RTC_SARADC2_INT_ENA_S 14
#define RTC_CNTL_RTC_COCPU_INT_ENA (BIT(13))
#define RTC_CNTL_RTC_COCPU_INT_ENA_S 13
#define RTC_CNTL_RTC_TSENS_INT_ENA (BIT(12))
#define RTC_CNTL_RTC_TSENS_INT_ENA_S 12
#define RTC_CNTL_RTC_SARADC1_INT_ENA (BIT(11))
#define RTC_CNTL_RTC_SARADC1_INT_ENA_S 11
#define RTC_CNTL_RTC_MAIN_TIMER_INT_ENA (BIT(10))
#define RTC_CNTL_RTC_MAIN_TIMER_INT_ENA_S 10
#define RTC_CNTL_RTC_BROWN_OUT_INT_ENA (BIT(9))
#define RTC_CNTL_RTC_BROWN_OUT_INT_ENA_S 9
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_ENA (BIT(8))
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_ENA_S 8
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_ENA (BIT(7))
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_ENA_S 7
#define RTC_CNTL_RTC_TOUCH_DONE_INT_ENA (BIT(6))
#define RTC_CNTL_RTC_TOUCH_DONE_INT_ENA_S 6
#define RTC_CNTL_RTC_ULP_CP_INT_ENA (BIT(5))
#define RTC_CNTL_RTC_ULP_CP_INT_ENA_S 5
#define RTC_CNTL_RTC_TIME_VALID_INT_ENA (BIT(4))
#define RTC_CNTL_RTC_TIME_VALID_INT_ENA_S 4
#define RTC_CNTL_RTC_WDT_INT_ENA (BIT(3))
#define RTC_CNTL_RTC_WDT_INT_ENA_S 3
#define RTC_CNTL_SDIO_IDLE_INT_ENA (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ENA_S 2
#define RTC_CNTL_SLP_REJECT_INT_ENA (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ENA_S 1
#define RTC_CNTL_SLP_WAKEUP_INT_ENA (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ENA_S 0

#define INT_RAW_RTC (REG_RTCCNTL_BASE + 0x44)
#define RTC_CNTL_RTC_SWD_INT_RAW (BIT(15))
#define RTC_CNTL_RTC_SWD_INT_RAW_S 15
#define RTC_CNTL_RTC_SARADC2_INT_RAW (BIT(14))
#define RTC_CNTL_RTC_SARADC2_INT_RAW_S 14
#define RTC_CNTL_RTC_COCPU_INT_RAW (BIT(13))
#define RTC_CNTL_RTC_COCPU_INT_RAW_S 13
#define RTC_CNTL_RTC_TSENS_INT_RAW (BIT(12))
#define RTC_CNTL_RTC_TSENS_INT_RAW_S 12
#define RTC_CNTL_RTC_SARADC1_INT_RAW (BIT(11))
#define RTC_CNTL_RTC_SARADC1_INT_RAW_S 11
#define RTC_CNTL_RTC_MAIN_TIMER_INT_RAW (BIT(10))
#define RTC_CNTL_RTC_MAIN_TIMER_INT_RAW_S 10
#define RTC_CNTL_RTC_BROWN_OUT_INT_RAW (BIT(9))
#define RTC_CNTL_RTC_BROWN_OUT_INT_RAW_S 9
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_RAW (BIT(8))
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_RAW_S 8
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_RAW (BIT(7))
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_RAW_S 7
#define RTC_CNTL_RTC_TOUCH_DONE_INT_RAW (BIT(6))
#define RTC_CNTL_RTC_TOUCH_DONE_INT_RAW_S 6
#define RTC_CNTL_RTC_ULP_CP_INT_RAW (BIT(5))
#define RTC_CNTL_RTC_ULP_CP_INT_RAW_S 5
#define RTC_CNTL_RTC_TIME_VALID_INT_RAW (BIT(4))
#define RTC_CNTL_RTC_TIME_VALID_INT_RAW_S 4
#define RTC_CNTL_RTC_WDT_INT_RAW (BIT(3))
#define RTC_CNTL_RTC_WDT_INT_RAW_S 3
#define RTC_CNTL_SDIO_IDLE_INT_RAW (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_RAW_S 2
#define RTC_CNTL_SLP_REJECT_INT_RAW (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_RAW_S 1
#define RTC_CNTL_SLP_WAKEUP_INT_RAW (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_RAW_S 0

#define INT_ST_RTC (REG_RTCCNTL_BASE + 0x48)
#define RTC_CNTL_RTC_SWD_INT_ST (BIT(15))
#define RTC_CNTL_RTC_SWD_INT_ST_S 15
#define RTC_CNTL_RTC_SARADC2_INT_ST (BIT(14))
#define RTC_CNTL_RTC_SARADC2_INT_ST_S 14
#define RTC_CNTL_RTC_COCPU_INT_ST (BIT(13))
#define RTC_CNTL_RTC_COCPU_INT_ST_S 13
#define RTC_CNTL_RTC_TSENS_INT_ST (BIT(12))
#define RTC_CNTL_RTC_TSENS_INT_ST_S 12
#define RTC_CNTL_RTC_SARADC1_INT_ST (BIT(11))
#define RTC_CNTL_RTC_SARADC1_INT_ST_S 11
#define RTC_CNTL_RTC_MAIN_TIMER_INT_ST (BIT(10))
#define RTC_CNTL_RTC_MAIN_TIMER_INT_ST_S 10
#define RTC_CNTL_RTC_BROWN_OUT_INT_ST (BIT(9))
#define RTC_CNTL_RTC_BROWN_OUT_INT_ST_S 9
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_ST (BIT(8))
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_ST_S 8
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_ST (BIT(7))
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_ST_S 7
#define RTC_CNTL_RTC_TOUCH_DONE_INT_ST (BIT(6))
#define RTC_CNTL_RTC_TOUCH_DONE_INT_ST_S 6
#define RTC_CNTL_RTC_ULP_CP_INT_ST (BIT(5))
#define RTC_CNTL_RTC_ULP_CP_INT_ST_S 5
#define RTC_CNTL_RTC_TIME_VALID_INT_ST (BIT(4))
#define RTC_CNTL_RTC_TIME_VALID_INT_ST_S 4
#define RTC_CNTL_RTC_WDT_INT_ST (BIT(3))
#define RTC_CNTL_RTC_WDT_INT_ST_S 3
#define RTC_CNTL_SDIO_IDLE_INT_ST (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ST_S 2
#define RTC_CNTL_SLP_REJECT_INT_ST (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ST_S 1
#define RTC_CNTL_SLP_WAKEUP_INT_ST (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ST_S 0

#define INT_CLR_RTC (REG_RTCCNTL_BASE + 0x4c)
#define RTC_CNTL_RTC_SWD_INT_CLR (BIT(15))
#define RTC_CNTL_RTC_SWD_INT_CLR_S 15
#define RTC_CNTL_RTC_SARADC2_INT_CLR (BIT(14))
#define RTC_CNTL_RTC_SARADC2_INT_CLR_S 14
#define RTC_CNTL_RTC_COCPU_INT_CLR (BIT(13))
#define RTC_CNTL_RTC_COCPU_INT_CLR_S 13
#define RTC_CNTL_RTC_TSENS_INT_CLR (BIT(12))
#define RTC_CNTL_RTC_TSENS_INT_CLR_S 12
#define RTC_CNTL_RTC_SARADC1_INT_CLR (BIT(11))
#define RTC_CNTL_RTC_SARADC1_INT_CLR_S 11
#define RTC_CNTL_RTC_MAIN_TIMER_INT_CLR (BIT(10))
#define RTC_CNTL_RTC_MAIN_TIMER_INT_CLR_S 10
#define RTC_CNTL_RTC_BROWN_OUT_INT_CLR (BIT(9))
#define RTC_CNTL_RTC_BROWN_OUT_INT_CLR_S 9
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_CLR (BIT(8))
#define RTC_CNTL_RTC_TOUCH_INACTIVE_INT_CLR_S 8
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_CLR (BIT(7))
#define RTC_CNTL_RTC_TOUCH_ACTIVE_INT_CLR_S 7
#define RTC_CNTL_RTC_TOUCH_DONE_INT_CLR (BIT(6))
#define RTC_CNTL_RTC_TOUCH_DONE_INT_CLR_S 6
#define RTC_CNTL_RTC_ULP_CP_INT_CLR (BIT(5))
#define RTC_CNTL_RTC_ULP_CP_INT_CLR_S 5
#define RTC_CNTL_RTC_TIME_VALID_INT_CLR (BIT(4))
#define RTC_CNTL_RTC_TIME_VALID_INT_CLR_S 4
#define RTC_CNTL_RTC_WDT_INT_CLR (BIT(3))
#define RTC_CNTL_RTC_WDT_INT_CLR_S 3
#define RTC_CNTL_SDIO_IDLE_INT_CLR (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_CLR_S 2
#define RTC_CNTL_SLP_REJECT_INT_CLR (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_CLR_S 1
#define RTC_CNTL_SLP_WAKEUP_INT_CLR (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_CLR_S 0

#define RTC_STORE0 (REG_RTCCNTL_BASE + 0x50)
#define RTC_CNTL_RTC_SCRATCH0 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH0_S 0

#define RTC_STORE1 (REG_RTCCNTL_BASE + 0x54)
#define RTC_CNTL_RTC_SCRATCH1 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH1_S 0

#define RTC_STORE2 (REG_RTCCNTL_BASE + 0x58)
#define RTC_CNTL_RTC_SCRATCH2 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH2_S 0

#define RTC_STORE3 (REG_RTCCNTL_BASE + 0x5c)
#define RTC_CNTL_RTC_SCRATCH3 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH3_S 0

#define RTC_EXT_XTL_CONF (REG_RTCCNTL_BASE + 0x60)
#define RTC_CNTL_XTL_EXT_CTR_EN (BIT(31))
#define RTC_CNTL_XTL_EXT_CTR_EN_S 31
#define RTC_CNTL_XTL_EXT_CTR_LV (BIT(30))
#define RTC_CNTL_XTL_EXT_CTR_LV_S 30
#define RTC_CNTL_RTC_XTAL32K_GPIO_SEL (BIT(22))
#define RTC_CNTL_RTC_XTAL32K_GPIO_SEL_S 22
#define RTC_CNTL_DAC_XTAL_32K 0x0000003F
#define RTC_CNTL_DAC_XTAL_32K_S 16
#define RTC_CNTL_XPD_XTAL_32K (BIT(15))
#define RTC_CNTL_XPD_XTAL_32K_S 15
#define RTC_CNTL_DRES_XTAL_32K 0x00000007
#define RTC_CNTL_DRES_XTAL_32K_S 12
#define RTC_CNTL_DGM_XTAL_32K 0x00000007
#define RTC_CNTL_DGM_XTAL_32K_S 9
#define RTC_CNTL_DBUF_XTAL_32K (BIT(8))
#define RTC_CNTL_DBUF_XTAL_32K_S 8
#define RTC_CNTL_ENCKINIT_XTAL_32K (BIT(7))
#define RTC_CNTL_ENCKINIT_XTAL_32K_S 7
#define RTC_CNTL_XTAL32K_XPD_FORCE (BIT(6))
#define RTC_CNTL_XTAL32K_XPD_FORCE_S 6
#define RTC_CNTL_XTAL32K_AUTO_RETURN (BIT(5))
#define RTC_CNTL_XTAL32K_AUTO_RETURN_S 5
#define RTC_CNTL_XTAL32K_AUTO_RESTART (BIT(4))
#define RTC_CNTL_XTAL32K_AUTO_RESTART_S 4
#define RTC_CNTL_XTAL32K_AUTO_BACKUP (BIT(3))
#define RTC_CNTL_XTAL32K_AUTO_BACKUP_S 3
#define RTC_CNTL_XTAL32K_EXT_CLK_FO (BIT(2))
#define RTC_CNTL_XTAL32K_EXT_CLK_FO_S 2
#define RTC_CNTL_XTAL32K_WDT_CLK_FO (BIT(1))
#define RTC_CNTL_XTAL32K_WDT_CLK_FO_S 1
#define RTC_CNTL_XTAL32K_WDT_EN (BIT(0))
#define RTC_CNTL_XTAL32K_WDT_EN_S 0

#define RTC_EXT_WAKEUP_CONF (REG_RTCCNTL_BASE + 0x64)
#define RTC_CNTL_EXT_WAKEUP1_LV (BIT(31))
#define RTC_CNTL_EXT_WAKEUP1_LV_S 31
#define RTC_CNTL_EXT_WAKEUP0_LV (BIT(30))
#define RTC_CNTL_EXT_WAKEUP0_LV_S 30

#define RTC_SLP_REJECT_CONF (REG_RTCCNTL_BASE + 0x68)
#define RTC_CNTL_REJECT_CAUSE 0x0000000F
#define RTC_CNTL_REJECT_CAUSE_S 28
#define RTC_CNTL_DEEP_SLP_REJECT_EN (BIT(27))
#define RTC_CNTL_DEEP_SLP_REJECT_EN_S 27
#define RTC_CNTL_LIGHT_SLP_REJECT_EN (BIT(26))
#define RTC_CNTL_LIGHT_SLP_REJECT_EN_S 26
#define RTC_CNTL_SDIO_REJECT_EN (BIT(25))
#define RTC_CNTL_SDIO_REJECT_EN_S 25
#define RTC_CNTL_GPIO_REJECT_EN (BIT(24))
#define RTC_CNTL_GPIO_REJECT_EN_S 24

#define RTC_CPU_PERIOD_CONF (REG_RTCCNTL_BASE + 0x6c)
#define RTC_CNTL_RTC_CPUPERIOD_SEL 0x00000003
#define RTC_CNTL_RTC_CPUPERIOD_SEL_S 30
#define RTC_CNTL_RTC_CPUSEL_CONF (BIT(29))
#define RTC_CNTL_RTC_CPUSEL_CONF_S 29

#define RTC_SDIO_ACT_CONF (REG_RTCCNTL_BASE + 0x70)
#define RTC_CNTL_SDIO_ACT_DNUM 0x000003FF
#define RTC_CNTL_SDIO_ACT_DNUM_S 22

#define RTC_CLK_CONF (REG_RTCCNTL_BASE + 0x74)
#define RTC_CNTL_ANA_CLK_RTC_SEL 0x00000003
#define RTC_CNTL_ANA_CLK_RTC_SEL_S 30
#define RTC_CNTL_FAST_CLK_RTC_SEL (BIT(29))
#define RTC_CNTL_FAST_CLK_RTC_SEL_S 29
#define RTC_CNTL_CK8M_FORCE_PU (BIT(26))
#define RTC_CNTL_CK8M_FORCE_PU_S 26
#define RTC_CNTL_CK8M_FORCE_PD (BIT(25))
#define RTC_CNTL_CK8M_FORCE_PD_S 25
#define RTC_CNTL_CK8M_DFREQ 0x000000FF
#define RTC_CNTL_CK8M_DFREQ_S 17
#define RTC_CNTL_CK8M_FORCE_NOGATING (BIT(16))
#define RTC_CNTL_CK8M_FORCE_NOGATING_S 16
#define RTC_CNTL_XTAL_FORCE_NOGATING (BIT(15))
#define RTC_CNTL_XTAL_FORCE_NOGATING_S 15
#define RTC_CNTL_CK8M_DIV_SEL 0x00000007
#define RTC_CNTL_CK8M_DIV_SEL_S 12
#define RTC_CNTL_DIG_CLK8M_EN (BIT(10))
#define RTC_CNTL_DIG_CLK8M_EN_S 10
#define RTC_CNTL_DIG_CLK8M_D256_EN (BIT(9))
#define RTC_CNTL_DIG_CLK8M_D256_EN_S 9
#define RTC_CNTL_DIG_XTAL32K_EN (BIT(8))
#define RTC_CNTL_DIG_XTAL32K_EN_S 8
#define RTC_CNTL_ENB_CK8M_DIV (BIT(7))
#define RTC_CNTL_ENB_CK8M_DIV_S 7
#define RTC_CNTL_ENB_CK8M (BIT(6))
#define RTC_CNTL_ENB_CK8M_S 6
#define RTC_CNTL_CK8M_DIV 0x00000003
#define RTC_CNTL_CK8M_DIV_S 4
#define RTC_CNTL_CK8M_DIV_SEL_VLD (BIT(3))
#define RTC_CNTL_CK8M_DIV_SEL_VLD_S 3

#define RTC_SLOW_CLK_CONF (REG_RTCCNTL_BASE + 0x78)
#define RTC_CNTL_RTC_SLOW_CLK_NEXT_EDGE (BIT(31))
#define RTC_CNTL_RTC_SLOW_CLK_NEXT_EDGE_S 31
#define RTC_CNTL_RTC_ANA_CLK_DIV 0x000000FF
#define RTC_CNTL_RTC_ANA_CLK_DIV_S 23
#define RTC_CNTL_RTC_ANA_CLK_DIV_VLD (BIT(22))
#define RTC_CNTL_RTC_ANA_CLK_DIV_VLD_S 22

#define RTC_SDIO_CONF (REG_RTCCNTL_BASE + 0x7c)
#define RTC_CNTL_XPD_SDIO_REG (BIT(31))
#define RTC_CNTL_XPD_SDIO_REG_S 31
#define RTC_CNTL_DREFH_SDIO 0x00000003
#define RTC_CNTL_DREFH_SDIO_S 29
#define RTC_CNTL_DREFM_SDIO 0x00000003
#define RTC_CNTL_DREFM_SDIO_S 27
#define RTC_CNTL_DREFL_SDIO 0x00000003
#define RTC_CNTL_DREFL_SDIO_S 25
#define RTC_CNTL_REG1P8_READY (BIT(24))
#define RTC_CNTL_REG1P8_READY_S 24
#define RTC_CNTL_SDIO_TIEH (BIT(23))
#define RTC_CNTL_SDIO_TIEH_S 23
#define RTC_CNTL_SDIO_FORCE (BIT(22))
#define RTC_CNTL_SDIO_FORCE_S 22
#define RTC_CNTL_SDIO_REG_PD_EN (BIT(21))
#define RTC_CNTL_SDIO_REG_PD_EN_S 21
#define RTC_CNTL_SDIO_ENCURLIM (BIT(20))
#define RTC_CNTL_SDIO_ENCURLIM_S 20
#define RTC_CNTL_SDIO_MODECURLIM (BIT(19))
#define RTC_CNTL_SDIO_MODECURLIM_S 19
#define RTC_CNTL_SDIO_DCURLIM 0x00000007
#define RTC_CNTL_SDIO_DCURLIM_S 16
#define RTC_CNTL_SDIO_EN_INITI (BIT(15))
#define RTC_CNTL_SDIO_EN_INITI_S 15
#define RTC_CNTL_SDIO_INITI 0x00000003
#define RTC_CNTL_SDIO_INITI_S 13
#define RTC_CNTL_SDIO_DCAP 0x00000003
#define RTC_CNTL_SDIO_DCAP_S 11
#define RTC_CNTL_SDIO_DTHDRV 0x00000003
#define RTC_CNTL_SDIO_DTHDRV_S 9
#define RTC_CNTL_SDIO_TIMER_TARGET 0x000000FF
#define RTC_CNTL_SDIO_TIMER_TARGET_S 0

#define RTC_BIAS_CONF (REG_RTCCNTL_BASE + 0x80)
#define RTC_CNTL_RST_BIAS_I2C (BIT(31))
#define RTC_CNTL_RST_BIAS_I2C_S 31
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH (BIT(30))
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH_S 30
#define RTC_CNTL_INC_HEARTBEAT_PERIOD (BIT(29))
#define RTC_CNTL_INC_HEARTBEAT_PERIOD_S 29
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD (BIT(28))
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD_S 28
#define RTC_CNTL_INC_HEARTBEAT_REFRESH (BIT(27))
#define RTC_CNTL_INC_HEARTBEAT_REFRESH_S 27
#define RTC_CNTL_ENB_SCK_XTAL (BIT(26))
#define RTC_CNTL_ENB_SCK_XTAL_S 26
#define RTC_CNTL_DBG_ATTEN 0x00000003
#define RTC_CNTL_DBG_ATTEN_S 24

#define RTC_REG (REG_RTCCNTL_BASE + 0x84)
#define RTC_CNTL_RTC_REGULATOR_FORCE_PU (BIT(31))
#define RTC_CNTL_RTC_REGULATOR_FORCE_PU_S 31
#define RTC_CNTL_RTC_REGULATOR_FORCE_PD (BIT(30))
#define RTC_CNTL_RTC_REGULATOR_FORCE_PD_S 30
#define RTC_CNTL_RTC_DBOOST_FORCE_PU (BIT(29))
#define RTC_CNTL_RTC_DBOOST_FORCE_PU_S 29
#define RTC_CNTL_RTC_DBOOST_FORCE_PD (BIT(28))
#define RTC_CNTL_RTC_DBOOST_FORCE_PD_S 28
#define RTC_CNTL_RTC_DBIAS_WAK 0x00000007
#define RTC_CNTL_RTC_DBIAS_WAK_S 25
#define RTC_CNTL_RTC_DBIAS_SLP 0x00000007
#define RTC_CNTL_RTC_DBIAS_SLP_S 22
#define RTC_CNTL_SCK_DCAP 0x000000FF
#define RTC_CNTL_SCK_DCAP_S 14
#define RTC_CNTL_DIG_REG_DBIAS_WAK 0x00000007
#define RTC_CNTL_DIG_REG_DBIAS_WAK_S 11
#define RTC_CNTL_DIG_REG_DBIAS_SLP 0x00000007
#define RTC_CNTL_DIG_REG_DBIAS_SLP_S 8

#define RTC_PWC (REG_RTCCNTL_BASE + 0x88)
#define RTC_CNTL_RTC_PAD_FORCE_HOLD (BIT(21))
#define RTC_CNTL_RTC_PAD_FORCE_HOLD_S 21
#define RTC_CNTL_RTC_PD_EN (BIT(20))
#define RTC_CNTL_RTC_PD_EN_S 20
#define RTC_CNTL_RTC_FORCE_PU (BIT(19))
#define RTC_CNTL_RTC_FORCE_PU_S 19
#define RTC_CNTL_RTC_FORCE_PD (BIT(18))
#define RTC_CNTL_RTC_FORCE_PD_S 18
#define RTC_CNTL_RTC_SLOWMEM_PD_EN (BIT(17))
#define RTC_CNTL_RTC_SLOWMEM_PD_EN_S 17
#define RTC_CNTL_RTC_SLOWMEM_FORCE_PU (BIT(16))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_PU_S 16
#define RTC_CNTL_RTC_SLOWMEM_FORCE_PD (BIT(15))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_PD_S 15
#define RTC_CNTL_RTC_FASTMEM_PD_EN (BIT(14))
#define RTC_CNTL_RTC_FASTMEM_PD_EN_S 14
#define RTC_CNTL_RTC_FASTMEM_FORCE_PU (BIT(13))
#define RTC_CNTL_RTC_FASTMEM_FORCE_PU_S 13
#define RTC_CNTL_RTC_FASTMEM_FORCE_PD (BIT(12))
#define RTC_CNTL_RTC_FASTMEM_FORCE_PD_S 12
#define RTC_CNTL_RTC_SLOWMEM_FORCE_LPU (BIT(11))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_LPU_S 11
#define RTC_CNTL_RTC_SLOWMEM_FORCE_LPD (BIT(10))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_LPD_S 10
#define RTC_CNTL_RTC_SLOWMEM_FOLW_CPU (BIT(9))
#define RTC_CNTL_RTC_SLOWMEM_FOLW_CPU_S 9
#define RTC_CNTL_RTC_FASTMEM_FORCE_LPU (BIT(8))
#define RTC_CNTL_RTC_FASTMEM_FORCE_LPU_S 8
#define RTC_CNTL_RTC_FASTMEM_FORCE_LPD (BIT(7))
#define RTC_CNTL_RTC_FASTMEM_FORCE_LPD_S 7
#define RTC_CNTL_RTC_FASTMEM_FOLW_CPU (BIT(6))
#define RTC_CNTL_RTC_FASTMEM_FOLW_CPU_S 6
#define RTC_CNTL_RTC_FORCE_NOISO (BIT(5))
#define RTC_CNTL_RTC_FORCE_NOISO_S 5
#define RTC_CNTL_RTC_FORCE_ISO (BIT(4))
#define RTC_CNTL_RTC_FORCE_ISO_S 4
#define RTC_CNTL_RTC_SLOWMEM_FORCE_ISO (BIT(3))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_ISO_S 3
#define RTC_CNTL_RTC_SLOWMEM_FORCE_NOISO (BIT(2))
#define RTC_CNTL_RTC_SLOWMEM_FORCE_NOISO_S 2
#define RTC_CNTL_RTC_FASTMEM_FORCE_ISO (BIT(1))
#define RTC_CNTL_RTC_FASTMEM_FORCE_ISO_S 1
#define RTC_CNTL_RTC_FASTMEM_FORCE_NOISO (BIT(0))
#define RTC_CNTL_RTC_FASTMEM_FORCE_NOISO_S 0

#define DIG_PWC (REG_RTCCNTL_BASE + 0x8c)
#define RTC_CNTL_DG_WRAP_PD_EN (BIT(31))
#define RTC_CNTL_DG_WRAP_PD_EN_S 31
#define RTC_CNTL_WIFI_PD_EN (BIT(30))
#define RTC_CNTL_WIFI_PD_EN_S 30
#define RTC_CNTL_INTER_RAM4_PD_EN (BIT(29))
#define RTC_CNTL_INTER_RAM4_PD_EN_S 29
#define RTC_CNTL_INTER_RAM3_PD_EN (BIT(28))
#define RTC_CNTL_INTER_RAM3_PD_EN_S 28
#define RTC_CNTL_INTER_RAM2_PD_EN (BIT(27))
#define RTC_CNTL_INTER_RAM2_PD_EN_S 27
#define RTC_CNTL_INTER_RAM1_PD_EN (BIT(26))
#define RTC_CNTL_INTER_RAM1_PD_EN_S 26
#define RTC_CNTL_INTER_RAM0_PD_EN (BIT(25))
#define RTC_CNTL_INTER_RAM0_PD_EN_S 25
#define RTC_CNTL_ROM0_PD_EN (BIT(24))
#define RTC_CNTL_ROM0_PD_EN_S 24
#define RTC_CNTL_DG_DCDC_PD_EN (BIT(23))
#define RTC_CNTL_DG_DCDC_PD_EN_S 23
#define RTC_CNTL_DG_DCDC_FORCE_PU (BIT(22))
#define RTC_CNTL_DG_DCDC_FORCE_PU_S 22
#define RTC_CNTL_DG_DCDC_FORCE_PD (BIT(21))
#define RTC_CNTL_DG_DCDC_FORCE_PD_S 21
#define RTC_CNTL_DG_WRAP_FORCE_PU (BIT(20))
#define RTC_CNTL_DG_WRAP_FORCE_PU_S 20
#define RTC_CNTL_DG_WRAP_FORCE_PD (BIT(19))
#define RTC_CNTL_DG_WRAP_FORCE_PD_S 19
#define RTC_CNTL_WIFI_FORCE_PU (BIT(18))
#define RTC_CNTL_WIFI_FORCE_PU_S 18
#define RTC_CNTL_WIFI_FORCE_PD (BIT(17))
#define RTC_CNTL_WIFI_FORCE_PD_S 17
#define RTC_CNTL_INTER_RAM4_FORCE_PU (BIT(16))
#define RTC_CNTL_INTER_RAM4_FORCE_PU_S 16
#define RTC_CNTL_INTER_RAM4_FORCE_PD (BIT(15))
#define RTC_CNTL_INTER_RAM4_FORCE_PD_S 15
#define RTC_CNTL_INTER_RAM3_FORCE_PU (BIT(14))
#define RTC_CNTL_INTER_RAM3_FORCE_PU_S 14
#define RTC_CNTL_INTER_RAM3_FORCE_PD (BIT(13))
#define RTC_CNTL_INTER_RAM3_FORCE_PD_S 13
#define RTC_CNTL_INTER_RAM2_FORCE_PU (BIT(12))
#define RTC_CNTL_INTER_RAM2_FORCE_PU_S 12
#define RTC_CNTL_INTER_RAM2_FORCE_PD (BIT(11))
#define RTC_CNTL_INTER_RAM2_FORCE_PD_S 11
#define RTC_CNTL_INTER_RAM1_FORCE_PU (BIT(10))
#define RTC_CNTL_INTER_RAM1_FORCE_PU_S 10
#define RTC_CNTL_INTER_RAM1_FORCE_PD (BIT(9))
#define RTC_CNTL_INTER_RAM1_FORCE_PD_S 9
#define RTC_CNTL_INTER_RAM0_FORCE_PU (BIT(8))
#define RTC_CNTL_INTER_RAM0_FORCE_PU_S 8
#define RTC_CNTL_INTER_RAM0_FORCE_PD (BIT(7))
#define RTC_CNTL_INTER_RAM0_FORCE_PD_S 7
#define RTC_CNTL_ROM0_FORCE_PU (BIT(6))
#define RTC_CNTL_ROM0_FORCE_PU_S 6
#define RTC_CNTL_ROM0_FORCE_PD (BIT(5))
#define RTC_CNTL_ROM0_FORCE_PD_S 5
#define RTC_CNTL_LSLP_MEM_FORCE_PU (BIT(4))
#define RTC_CNTL_LSLP_MEM_FORCE_PU_S 4
#define RTC_CNTL_LSLP_MEM_FORCE_PD (BIT(3))
#define RTC_CNTL_LSLP_MEM_FORCE_PD_S 3

#define DIG_ISO (REG_RTCCNTL_BASE + 0x90)
#define RTC_CNTL_DG_WRAP_FORCE_NOISO (BIT(31))
#define RTC_CNTL_DG_WRAP_FORCE_NOISO_S 31
#define RTC_CNTL_DG_WRAP_FORCE_ISO (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_ISO_S 30
#define RTC_CNTL_WIFI_FORCE_NOISO (BIT(29))
#define RTC_CNTL_WIFI_FORCE_NOISO_S 29
#define RTC_CNTL_WIFI_FORCE_ISO (BIT(28))
#define RTC_CNTL_WIFI_FORCE_ISO_S 28
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO (BIT(27))
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO_S 27
#define RTC_CNTL_INTER_RAM4_FORCE_ISO (BIT(26))
#define RTC_CNTL_INTER_RAM4_FORCE_ISO_S 26
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO (BIT(25))
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO_S 25
#define RTC_CNTL_INTER_RAM3_FORCE_ISO (BIT(24))
#define RTC_CNTL_INTER_RAM3_FORCE_ISO_S 24
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO (BIT(23))
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO_S 23
#define RTC_CNTL_INTER_RAM2_FORCE_ISO (BIT(22))
#define RTC_CNTL_INTER_RAM2_FORCE_ISO_S 22
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO (BIT(21))
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO_S 21
#define RTC_CNTL_INTER_RAM1_FORCE_ISO (BIT(20))
#define RTC_CNTL_INTER_RAM1_FORCE_ISO_S 20
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO (BIT(19))
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO_S 19
#define RTC_CNTL_INTER_RAM0_FORCE_ISO (BIT(18))
#define RTC_CNTL_INTER_RAM0_FORCE_ISO_S 18
#define RTC_CNTL_ROM0_FORCE_NOISO (BIT(17))
#define RTC_CNTL_ROM0_FORCE_NOISO_S 17
#define RTC_CNTL_ROM0_FORCE_ISO (BIT(16))
#define RTC_CNTL_ROM0_FORCE_ISO_S 16
#define RTC_CNTL_DG_PAD_FORCE_HOLD (BIT(15))
#define RTC_CNTL_DG_PAD_FORCE_HOLD_S 15
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD (BIT(14))
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD_S 14
#define RTC_CNTL_DG_PAD_FORCE_ISO (BIT(13))
#define RTC_CNTL_DG_PAD_FORCE_ISO_S 13
#define RTC_CNTL_DG_PAD_FORCE_NOISO (BIT(12))
#define RTC_CNTL_DG_PAD_FORCE_NOISO_S 12
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN (BIT(11))
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN_S 11
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD (BIT(10))
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD_S 10
#define RTC_CNTL_DG_PAD_AUTOHOLD (BIT(9))
#define RTC_CNTL_DG_PAD_AUTOHOLD_S 9
#define RTC_CNTL_DIG_ISO_FORCE_ON (BIT(8))
#define RTC_CNTL_DIG_ISO_FORCE_ON_S 8
#define RTC_CNTL_DIG_ISO_FORCE_OFF (BIT(7))
#define RTC_CNTL_DIG_ISO_FORCE_OFF_S 7

#define RTC_WDTCONFIG0 (REG_RTCCNTL_BASE + 0x94)
#define RTC_CNTL_WDT_EN (BIT(31))
#define RTC_CNTL_WDT_EN_S 31
#define RTC_CNTL_WDT_STG0 0x00000007
#define RTC_CNTL_WDT_STG0_S 28
#define RTC_CNTL_WDT_STG1 0x00000007
#define RTC_CNTL_WDT_STG1_S 25
#define RTC_CNTL_WDT_STG2 0x00000007
#define RTC_CNTL_WDT_STG2_S 22
#define RTC_CNTL_WDT_STG3 0x00000007
#define RTC_CNTL_WDT_STG3_S 19
#define RTC_CNTL_WDT_CPU_RESET_LENGTH 0x00000007
#define RTC_CNTL_WDT_CPU_RESET_LENGTH_S 16
#define RTC_CNTL_WDT_SYS_RESET_LENGTH 0x00000007
#define RTC_CNTL_WDT_SYS_RESET_LENGTH_S 13
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN (BIT(12))
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN_S 12
#define RTC_CNTL_WDT_PROCPU_RESET_EN (BIT(11))
#define RTC_CNTL_WDT_PROCPU_RESET_EN_S 11
#define RTC_CNTL_WDT_APPCPU_RESET_EN (BIT(10))
#define RTC_CNTL_WDT_APPCPU_RESET_EN_S 10
#define RTC_CNTL_WDT_PAUSE_IN_SLP (BIT(9))
#define RTC_CNTL_WDT_PAUSE_IN_SLP_S 9
#define RTC_CNTL_WDT_CHIP_RESET_EN (BIT(8))
#define RTC_CNTL_WDT_CHIP_RESET_EN_S 8
#define RTC_CNTL_WDT_CHIP_RESET_WIDTH 0x000000FF
#define RTC_CNTL_WDT_CHIP_RESET_WIDTH_S 0

#define RTC_WDTCONFIG1 (REG_RTCCNTL_BASE + 0x98)
#define RTC_CNTL_WDT_STG0_HOLD 0xFFFFFFFF
#define RTC_CNTL_WDT_STG0_HOLD_S 0

#define RTC_WDTCONFIG2 (REG_RTCCNTL_BASE + 0x9c)
#define RTC_CNTL_WDT_STG1_HOLD 0xFFFFFFFF
#define RTC_CNTL_WDT_STG1_HOLD_S 0

#define RTC_WDTCONFIG3 (REG_RTCCNTL_BASE + 0xa0)
#define RTC_CNTL_WDT_STG2_HOLD 0xFFFFFFFF
#define RTC_CNTL_WDT_STG2_HOLD_S 0

#define RTC_WDTCONFIG4 (REG_RTCCNTL_BASE + 0xa4)
#define RTC_CNTL_WDT_STG3_HOLD 0xFFFFFFFF
#define RTC_CNTL_WDT_STG3_HOLD_S 0

#define RTC_WDTFEED (REG_RTCCNTL_BASE + 0xa8)
#define RTC_CNTL_RTC_WDT_FEED (BIT(31))
#define RTC_CNTL_RTC_WDT_FEED_S 31

#define RTC_WDTWPROTECT (REG_RTCCNTL_BASE + 0xac)
#define RTC_CNTL_WDT_WKEY 0xFFFFFFFF
#define RTC_CNTL_WDT_WKEY_S 0

#define RTC_SWD_CONF (REG_RTCCNTL_BASE + 0xb0)
#define RTC_CNTL_SWD_AUTO_FEED_EN (BIT(31))
#define RTC_CNTL_SWD_AUTO_FEED_EN_S 31
#define RTC_CNTL_SWD_DISABLE (BIT(30))
#define RTC_CNTL_SWD_DISABLE_S 30
#define RTC_CNTL_SWD_FEED (BIT(29))
#define RTC_CNTL_SWD_FEED_S 29
#define RTC_CNTL_SWD_RST_FLAG_CLR (BIT(28))
#define RTC_CNTL_SWD_RST_FLAG_CLR_S 28
#define RTC_CNTL_SWD_SIGNAL_WIDTH 0x000000FF
#define RTC_CNTL_SWD_SIGNAL_WIDTH_S 20
#define RTC_CNTL_SWD_FEED_INT (BIT(1))
#define RTC_CNTL_SWD_FEED_INT_S 1
#define RTC_CNTL_SWD_RESET_FLAG (BIT(0))
#define RTC_CNTL_SWD_RESET_FLAG_S 0

#define RTC_SWD_WPROTECT (REG_RTCCNTL_BASE + 0xb4)
#define RTC_CNTL_SWD_WKEY 0xFFFFFFFF
#define RTC_CNTL_SWD_WKEY_S 0

#define RTC_TEST_MUX (REG_RTCCNTL_BASE + 0xb8)
#define RTC_CNTL_DTEST_RTC 0x00000003
#define RTC_CNTL_DTEST_RTC_S 30
#define RTC_CNTL_ENT_RTC (BIT(29))
#define RTC_CNTL_ENT_RTC_S 29
#define RTC_CNTL_ENT_TSENS (BIT(28))
#define RTC_CNTL_ENT_TSENS_S 28

#define RTC_SW_CPU_STALL (REG_RTCCNTL_BASE + 0xbc)
#define RTC_CNTL_SW_STALL_PROCPU_C1 0x0000003F
#define RTC_CNTL_SW_STALL_PROCPU_C1_S 26
#define RTC_CNTL_SW_STALL_APPCPU_C1 0x0000003F
#define RTC_CNTL_SW_STALL_APPCPU_C1_S 20

#define RTC_STORE4 (REG_RTCCNTL_BASE + 0xc0)
#define RTC_CNTL_RTC_SCRATCH4 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH4_S 0

#define RTC_STORE5 (REG_RTCCNTL_BASE + 0xc4)
#define RTC_CNTL_RTC_SCRATCH5 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH5_S 0

#define RTC_STORE6 (REG_RTCCNTL_BASE + 0xc8)
#define RTC_CNTL_RTC_SCRATCH6 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH6_S 0

#define RTC_STORE7 (REG_RTCCNTL_BASE + 0xcc)
#define RTC_CNTL_RTC_SCRATCH7 0xFFFFFFFF
#define RTC_CNTL_RTC_SCRATCH7_S 0

#define RTC_LOW_POWER_ST (REG_RTCCNTL_BASE + 0xd0)
#define RTC_CNTL_RTC_MAIN_STATE 0x0000000F
#define RTC_CNTL_RTC_MAIN_STATE_S 28
#define RTC_CNTL_RTC_MAIN_STATE_IN_IDLE (BIT(27))
#define RTC_CNTL_RTC_MAIN_STATE_IN_IDLE_S 27
#define RTC_CNTL_RTC_MAIN_STATE_IN_SLP (BIT(26))
#define RTC_CNTL_RTC_MAIN_STATE_IN_SLP_S 26
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_XTL (BIT(25))
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_XTL_S 25
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_PLL (BIT(24))
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_PLL_S 24
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_8M (BIT(23))
#define RTC_CNTL_RTC_MAIN_STATE_IN_WAIT_8M_S 23
#define RTC_CNTL_RTC_IN_LOW_POWER_STATE (BIT(22))
#define RTC_CNTL_RTC_IN_LOW_POWER_STATE_S 22
#define RTC_CNTL_RTC_IN_WAKEUP_STATE (BIT(21))
#define RTC_CNTL_RTC_IN_WAKEUP_STATE_S 21
#define RTC_CNTL_RTC_MAIN_STATE_WAIT_END (BIT(20))
#define RTC_CNTL_RTC_MAIN_STATE_WAIT_END_S 20
#define RTC_CNTL_RTC_RDY_FOR_WAKEUP (BIT(19))
#define RTC_CNTL_RTC_RDY_FOR_WAKEUP_S 19
#define RTC_CNTL_RTC_MAIN_STATE_PLL_ON (BIT(18))
#define RTC_CNTL_RTC_MAIN_STATE_PLL_ON_S 18
#define RTC_CNTL_RTC_MAIN_STATE_XTAL_ISO (BIT(17))
#define RTC_CNTL_RTC_MAIN_STATE_XTAL_ISO_S 17
#define RTC_CNTL_RTC_COCPU_DONE (BIT(16))
#define RTC_CNTL_RTC_COCPU_DONE_S 16
#define RTC_CNTL_RTC_COCPU_SLP (BIT(15))
#define RTC_CNTL_RTC_COCPU_SLP_S 15
#define RTC_CNTL_RTC_COCPU_STATE_SWITCH (BIT(14))
#define RTC_CNTL_RTC_COCPU_STATE_SWITCH_S 14
#define RTC_CNTL_RTC_COCPU_START (BIT(13))
#define RTC_CNTL_RTC_COCPU_START_S 13
#define RTC_CNTL_RTC_TOUCH_DONE (BIT(12))
#define RTC_CNTL_RTC_TOUCH_DONE_S 12
#define RTC_CNTL_RTC_TOUCH_SLP (BIT(11))
#define RTC_CNTL_RTC_TOUCH_SLP_S 11
#define RTC_CNTL_RTC_TOUCH_STATE_SWITCH (BIT(10))
#define RTC_CNTL_RTC_TOUCH_STATE_SWITCH_S 10
#define RTC_CNTL_RTC_TOUCH_START (BIT(9))
#define RTC_CNTL_RTC_TOUCH_START_S 9
#define RTC_CNTL_XPD_DIG (BIT(8))
#define RTC_CNTL_XPD_DIG_S 8
#define RTC_CNTL_DIG_ISO (BIT(7))
#define RTC_CNTL_DIG_ISO_S 7
#define RTC_CNTL_XPD_WIFI (BIT(6))
#define RTC_CNTL_XPD_WIFI_S 6
#define RTC_CNTL_WIFI_ISO (BIT(5))
#define RTC_CNTL_WIFI_ISO_S 5
#define RTC_CNTL_XPD_RTC_PERI (BIT(4))
#define RTC_CNTL_XPD_RTC_PERI_S 4
#define RTC_CNTL_RTC_PERI_ISO (BIT(3))
#define RTC_CNTL_RTC_PERI_ISO_S 3
#define RTC_CNTL_XPD_DIG_DCDC (BIT(2))
#define RTC_CNTL_XPD_DIG_DCDC_S 2
#define RTC_CNTL_XPD_ROM0 (BIT(0))
#define RTC_CNTL_XPD_ROM0_S 0

#define RTC_DIAG0 (REG_RTCCNTL_BASE + 0xd4)
#define RTC_CNTL_RTC_LOW_POWER_DIAG1 0xFFFFFFFF
#define RTC_CNTL_RTC_LOW_POWER_DIAG1_S 0

#define RTC_PAD_HOLD (REG_RTCCNTL_BASE + 0xd8)
#define RTC_CNTL_RTC_PAD20_HOLD (BIT(20))
#define RTC_CNTL_RTC_PAD20_HOLD_S 20
#define RTC_CNTL_RTC_PAD19_HOLD (BIT(19))
#define RTC_CNTL_RTC_PAD19_HOLD_S 19
#define RTC_CNTL_PDAC2_HOLD (BIT(18))
#define RTC_CNTL_PDAC2_HOLD_S 18
#define RTC_CNTL_PDAC1_HOLD (BIT(17))
#define RTC_CNTL_PDAC1_HOLD_S 17
#define RTC_CNTL_X32N_HOLD (BIT(16))
#define RTC_CNTL_X32N_HOLD_S 16
#define RTC_CNTL_X32P_HOLD (BIT(15))
#define RTC_CNTL_X32P_HOLD_S 15
#define RTC_CNTL_TOUCH_PAD14_HOLD (BIT(14))
#define RTC_CNTL_TOUCH_PAD14_HOLD_S 14
#define RTC_CNTL_TOUCH_PAD13_HOLD (BIT(13))
#define RTC_CNTL_TOUCH_PAD13_HOLD_S 13
#define RTC_CNTL_TOUCH_PAD12_HOLD (BIT(12))
#define RTC_CNTL_TOUCH_PAD12_HOLD_S 12
#define RTC_CNTL_TOUCH_PAD11_HOLD (BIT(11))
#define RTC_CNTL_TOUCH_PAD11_HOLD_S 11
#define RTC_CNTL_TOUCH_PAD10_HOLD (BIT(10))
#define RTC_CNTL_TOUCH_PAD10_HOLD_S 10
#define RTC_CNTL_TOUCH_PAD9_HOLD (BIT(9))
#define RTC_CNTL_TOUCH_PAD9_HOLD_S 9
#define RTC_CNTL_TOUCH_PAD8_HOLD (BIT(8))
#define RTC_CNTL_TOUCH_PAD8_HOLD_S 8
#define RTC_CNTL_TOUCH_PAD7_HOLD (BIT(7))
#define RTC_CNTL_TOUCH_PAD7_HOLD_S 7
#define RTC_CNTL_TOUCH_PAD6_HOLD (BIT(6))
#define RTC_CNTL_TOUCH_PAD6_HOLD_S 6
#define RTC_CNTL_TOUCH_PAD5_HOLD (BIT(5))
#define RTC_CNTL_TOUCH_PAD5_HOLD_S 5
#define RTC_CNTL_TOUCH_PAD4_HOLD (BIT(4))
#define RTC_CNTL_TOUCH_PAD4_HOLD_S 4
#define RTC_CNTL_TOUCH_PAD3_HOLD (BIT(3))
#define RTC_CNTL_TOUCH_PAD3_HOLD_S 3
#define RTC_CNTL_TOUCH_PAD2_HOLD (BIT(2))
#define RTC_CNTL_TOUCH_PAD2_HOLD_S 2
#define RTC_CNTL_TOUCH_PAD1_HOLD (BIT(1))
#define RTC_CNTL_TOUCH_PAD1_HOLD_S 1
#define RTC_CNTL_TOUCH_PAD0_HOLD (BIT(0))
#define RTC_CNTL_TOUCH_PAD0_HOLD_S 0

#define DIG_PAD_HOLD (REG_RTCCNTL_BASE + 0xdc)
#define RTC_CNTL_DIG_PAD_HOLD 0xFFFFFFFF
#define RTC_CNTL_DIG_PAD_HOLD_S 0

#define RTC_EXT_WAKEUP1 (REG_RTCCNTL_BASE + 0xe0)
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR (BIT(21))
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_S 21
#define RTC_CNTL_EXT_WAKEUP1_SEL 0x001FFFFF
#define RTC_CNTL_EXT_WAKEUP1_SEL_S 0

#define RTC_EXT_WAKEUP1_STATUS (REG_RTCCNTL_BASE + 0xe4)
#define RTC_CNTL_EXT_WAKEUP1_STATUS 0x001FFFFF
#define RTC_CNTL_EXT_WAKEUP1_STATUS_S 0

#define RTC_BROWN_OUT (REG_RTCCNTL_BASE + 0xe8)
#define RTC_CNTL_RTC_BROWN_OUT_DET (BIT(31))
#define RTC_CNTL_RTC_BROWN_OUT_DET_S 31
#define RTC_CNTL_BROWN_OUT_ENA (BIT(30))
#define RTC_CNTL_BROWN_OUT_ENA_S 30
#define RTC_CNTL_DBROWN_OUT_THRES 0x00000007
#define RTC_CNTL_DBROWN_OUT_THRES_S 27
#define RTC_CNTL_BROWN_OUT_RST_ENA (BIT(26))
#define RTC_CNTL_BROWN_OUT_RST_ENA_S 26
#define RTC_CNTL_BROWN_OUT_RST_WAIT 0x000003FF
#define RTC_CNTL_BROWN_OUT_RST_WAIT_S 16
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA (BIT(15))
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA_S 15
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA (BIT(14))
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_S 14

#define RTC_TIME_LOW1 (REG_RTCCNTL_BASE + 0xec)
#define RTC_CNTL_RTC_TIMER_VALUE1_LOW 0xFFFFFFFF
#define RTC_CNTL_RTC_TIMER_VALUE1_LOW_S 0

#define RTC_TIME_HIGH1 (REG_RTCCNTL_BASE + 0xf0)
#define RTC_CNTL_RTC_TIMER_VALUE1_HIGH 0x0000FFFF
#define RTC_CNTL_RTC_TIMER_VALUE1_HIGH_S 0

#define RTC_XTAL32K_CLK_FACTOR (REG_RTCCNTL_BASE + 0xf4)
#define RTC_CNTL_XTAL32K_CLK_FACTOR 0xFFFFFFFF
#define RTC_CNTL_XTAL32K_CLK_FACTOR_S 0

#define RTC_XTAL32K_CONF (REG_RTCCNTL_BASE + 0xf8)
#define RTC_CNTL_XTAL32K_STABLE_THRES 0x0000000F
#define RTC_CNTL_XTAL32K_STABLE_THRES_S 28
#define RTC_CNTL_XTAL32K_WDT_TIMEOUT 0x000000FF
#define RTC_CNTL_XTAL32K_WDT_TIMEOUT_S 20
#define RTC_CNTL_XTAL32K_RESTART_WAIT 0x0000FFFF
#define RTC_CNTL_XTAL32K_RESTART_WAIT_S 4
#define RTC_CNTL_XTAL32K_RETURN_WAIT 0x0000000F
#define RTC_CNTL_XTAL32K_RETURN_WAIT_S 0

#define RTC_ULP_CP_TIMER (REG_RTCCNTL_BASE + 0xfc)
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN (BIT(31))
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN_S 31
#define RTC_CNTL_ULP_CP_GPIO_WAKEUP_CLR (BIT(30))
#define RTC_CNTL_ULP_CP_GPIO_WAKEUP_CLR_S 30
#define RTC_CNTL_ULP_CP_GPIO_WAKEUP_ENA (BIT(29))
#define RTC_CNTL_ULP_CP_GPIO_WAKEUP_ENA_S 29
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN (BIT(28))
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_S 28
#define RTC_CNTL_ULP_CP_TIMER_SLP_CYCLE 0x0000FFFF
#define RTC_CNTL_ULP_CP_TIMER_SLP_CYCLE_S 12
#define RTC_CNTL_ULP_CP_PC_INIT 0x000007FF
#define RTC_CNTL_ULP_CP_PC_INIT_S 0

#define RTC_ULP_CP_CTRL (REG_RTCCNTL_BASE + 0x100)
#define RTC_CNTL_ULP_CP_START_TOP (BIT(31))
#define RTC_CNTL_ULP_CP_START_TOP_S 31
#define RTC_CNTL_ULP_CP_FORCE_START_TOP (BIT(30))
#define RTC_CNTL_ULP_CP_FORCE_START_TOP_S 30
#define RTC_CNTL_ULP_CP_RESET (BIT(29))
#define RTC_CNTL_ULP_CP_RESET_S 29
#define RTC_CNTL_ULP_CP_CLK_FO (BIT(28))
#define RTC_CNTL_ULP_CP_CLK_FO_S 28
#define RTC_CNTL_ULP_CP_MEM_OFFST_CLR (BIT(22))
#define RTC_CNTL_ULP_CP_MEM_OFFST_CLR_S 22
#define RTC_CNTL_ULP_CP_MEM_ADDR_SIZE 0x000007FF
#define RTC_CNTL_ULP_CP_MEM_ADDR_SIZE_S 11
#define RTC_CNTL_ULP_CP_MEM_ADDR_INIT 0x000007FF
#define RTC_CNTL_ULP_CP_MEM_ADDR_INIT_S 0

#define RTC_COCPU_CTRL (REG_RTCCNTL_BASE + 0x104)
#define RTC_CNTL_COCPU_WAKEUP_FORCE_EN (BIT(26))
#define RTC_CNTL_COCPU_WAKEUP_FORCE_EN_S 26
#define RTC_CNTL_COCPU_WAKEUP (BIT(25))
#define RTC_CNTL_COCPU_WAKEUP_S 25
#define RTC_CNTL_COCPU_SW_INT_TRIGGER (BIT(24))
#define RTC_CNTL_COCPU_SW_INT_TRIGGER_S 24
#define RTC_CNTL_COCPU_DONE (BIT(23))
#define RTC_CNTL_COCPU_DONE_S 23
#define RTC_CNTL_COCPU_DONE_FORCE (BIT(22))
#define RTC_CNTL_COCPU_DONE_FORCE_S 22
#define RTC_CNTL_COCPU_SEL (BIT(21))
#define RTC_CNTL_COCPU_SEL_S 21
#define RTC_CNTL_COCPU_SHUT_RESET_EN (BIT(20))
#define RTC_CNTL_COCPU_SHUT_RESET_EN_S 20
#define RTC_CNTL_COCPU_SHUT_2_CLK_DIS 0x0000003F
#define RTC_CNTL_COCPU_SHUT_2_CLK_DIS_S 14
#define RTC_CNTL_COCPU_SHUT (BIT(13))
#define RTC_CNTL_COCPU_SHUT_S 13
#define RTC_CNTL_COCPU_START_2_INTR_EN 0x0000003F
#define RTC_CNTL_COCPU_START_2_INTR_EN_S 7
#define RTC_CNTL_COCPU_START_2_RESET_DIS 0x0000003F
#define RTC_CNTL_COCPU_START_2_RESET_DIS_S 1
#define RTC_CNTL_COCPU_CLK_FO (BIT(0))
#define RTC_CNTL_COCPU_CLK_FO_S 0

#define RTC_TOUCH_CTRL1 (REG_RTCCNTL_BASE + 0x108)
#define RTC_CNTL_TOUCH_MEAS_NUM 0x0000FFFF
#define RTC_CNTL_TOUCH_MEAS_NUM_S 16
#define RTC_CNTL_TOUCH_SLEEP_CYCLES 0x0000FFFF
#define RTC_CNTL_TOUCH_SLEEP_CYCLES_S 0

#define RTC_TOUCH_CTRL2 (REG_RTCCNTL_BASE + 0x10c)
#define RTC_CNTL_TOUCH_CLKGATE_EN (BIT(31))
#define RTC_CNTL_TOUCH_CLKGATE_EN_S 31
#define RTC_CNTL_TOUCH_CLK_FO (BIT(30))
#define RTC_CNTL_TOUCH_CLK_FO_S 30
#define RTC_CNTL_TOUCH_RESET (BIT(29))
#define RTC_CNTL_TOUCH_RESET_S 29
#define RTC_CNTL_TOUCH_SLP_CYC_DIV 0x00000003
#define RTC_CNTL_TOUCH_SLP_CYC_DIV_S 25
#define RTC_CNTL_TOUCH_XPD_WAIT 0x000000FF
#define RTC_CNTL_TOUCH_XPD_WAIT_S 17
#define RTC_CNTL_TOUCH_START_FORCE (BIT(16))
#define RTC_CNTL_TOUCH_START_FORCE_S 16
#define RTC_CNTL_TOUCH_START_EN (BIT(15))
#define RTC_CNTL_TOUCH_START_EN_S 15
#define RTC_CNTL_TOUCH_START_FSM_EN (BIT(14))
#define RTC_CNTL_TOUCH_START_FSM_EN_S 14
#define RTC_CNTL_TOUCH_SLP_TIMER_EN (BIT(13))
#define RTC_CNTL_TOUCH_SLP_TIMER_EN_S 13
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN (BIT(12))
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_S 12
#define RTC_CNTL_TOUCH_REFC 0x00000007
#define RTC_CNTL_TOUCH_REFC_S 9
#define RTC_CNTL_TOUCH_XPD_BIAS (BIT(8))
#define RTC_CNTL_TOUCH_XPD_BIAS_S 8
#define RTC_CNTL_TOUCH_DREFH 0x00000003
#define RTC_CNTL_TOUCH_DREFH_S 6
#define RTC_CNTL_TOUCH_DREFL 0x00000003
#define RTC_CNTL_TOUCH_DREFL_S 4
#define RTC_CNTL_TOUCH_DRANGE 0x00000003
#define RTC_CNTL_TOUCH_DRANGE_S 2

#define RTC_TOUCH_SCAN_CTRL (REG_RTCCNTL_BASE + 0x110)
#define RTC_CNTL_TOUCH_OUT_RING 0x0000000F
#define RTC_CNTL_TOUCH_OUT_RING_S 28
#define RTC_CNTL_TOUCH_BUFDRV 0x00000007
#define RTC_CNTL_TOUCH_BUFDRV_S 25
#define RTC_CNTL_TOUCH_SCAN_PAD_MAP 0x00007FFF
#define RTC_CNTL_TOUCH_SCAN_PAD_MAP_S 10
#define RTC_CNTL_TOUCH_SHIELD_PAD_EN (BIT(9))
#define RTC_CNTL_TOUCH_SHIELD_PAD_EN_S 9
#define RTC_CNTL_TOUCH_INACTIVE_CONNECTION (BIT(8))
#define RTC_CNTL_TOUCH_INACTIVE_CONNECTION_S 8
#define RTC_CNTL_TOUCH_DENOISE_EN (BIT(2))
#define RTC_CNTL_TOUCH_DENOISE_EN_S 2
#define RTC_CNTL_TOUCH_DENOISE_RES 0x00000003
#define RTC_CNTL_TOUCH_DENOISE_RES_S 0

#define RTC_TOUCH_SLP_THRES (REG_RTCCNTL_BASE + 0x114)
#define RTC_CNTL_TOUCH_SLP_PAD 0x0000001F
#define RTC_CNTL_TOUCH_SLP_PAD_S 27
#define RTC_CNTL_TOUCH_SLP_APPROACH_EN (BIT(26))
#define RTC_CNTL_TOUCH_SLP_APPROACH_EN_S 26
#define RTC_CNTL_TOUCH_SLP_TH 0x003FFFFF
#define RTC_CNTL_TOUCH_SLP_TH_S 0

#define RTC_TOUCH_APPROACH (REG_RTCCNTL_BASE + 0x118)
#define RTC_CNTL_TOUCH_APPROACH_MEAS_TIME 0x000000FF
#define RTC_CNTL_TOUCH_APPROACH_MEAS_TIME_S 24

#define RTC_TOUCH_FILTER_CTRL (REG_RTCCNTL_BASE + 0x11c)
#define RTC_CNTL_TOUCH_FILTER_EN (BIT(31))
#define RTC_CNTL_TOUCH_FILTER_EN_S 31
#define RTC_CNTL_TOUCH_FILTER_MODE 0x00000003
#define RTC_CNTL_TOUCH_FILTER_MODE_S 29
#define RTC_CNTL_TOUCH_DEBOUNCE 0x00000007
#define RTC_CNTL_TOUCH_DEBOUNCE_S 26
#define RTC_CNTL_TOUCH_HYSTERESIS 0x00000003
#define RTC_CNTL_TOUCH_HYSTERESIS_S 24
#define RTC_CNTL_TOUCH_NOISE_THRES 0x00000003
#define RTC_CNTL_TOUCH_NOISE_THRES_S 22
#define RTC_CNTL_TOUCH_NEG_NOISE_THRES 0x00000003
#define RTC_CNTL_TOUCH_NEG_NOISE_THRES_S 20
#define RTC_CNTL_TOUCH_BASELINE_RESET (BIT(19))
#define RTC_CNTL_TOUCH_BASELINE_RESET_S 19

#define RTC_CNTL_DATE (REG_RTCCNTL_BASE + 0x120)
#define RTC_CNTL_RTC_CNTL_DATE 0x0FFFFFFF
#define RTC_CNTL_RTC_CNTL_DATE_S 0
#define RTC_CNTL_RTC_CNTL_DATE_VERSION 0x1807161
