
#define SENSITIVE_PMS_SDIO_0_REG (REG_SENSITIVE_BASE + 0x000)
#define SENSITIVE_PMS_SDIO_LOCK (BIT(0))
#define SENSITIVE_PMS_SDIO_LOCK_S 0

#define SENSITIVE_PMS_SDIO_1_REG (REG_SENSITIVE_BASE + 0x004)
#define SENSITIVE_PMS_SDIO_DISABLE (BIT(0))
#define SENSITIVE_PMS_SDIO_DISABLE_S 0

#define SENSITIVE_PMS_MAC_DUMP_0_REG (REG_SENSITIVE_BASE + 0x008)
#define SENSITIVE_PMS_MAC_DUMP_LOCK (BIT(0))
#define SENSITIVE_PMS_MAC_DUMP_LOCK_S 0

#define SENSITIVE_PMS_MAC_DUMP_1_REG (REG_SENSITIVE_BASE + 0x00C)
#define SENSITIVE_PMS_MAC_DUMP_CONNECT 0x00000FFF
#define SENSITIVE_PMS_MAC_DUMP_CONNECT_S 0

#define SENSITIVE_PMS_PRO_IRAM0_0_REG (REG_SENSITIVE_BASE + 0x010)
#define SENSITIVE_PMS_PRO_IRAM0_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_IRAM0_LOCK_S 0

#define SENSITIVE_PMS_PRO_IRAM0_1_REG (REG_SENSITIVE_BASE + 0x014)
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_W (BIT(11))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_W_S 11
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_R (BIT(10))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_R_S 10
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_F (BIT(9))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_3_F_S 9
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_W (BIT(8))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_W_S 8
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_R (BIT(7))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_R_S 7
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_F (BIT(6))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_2_F_S 6
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_W (BIT(5))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_W_S 5
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_R (BIT(4))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_R_S 4
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_F (BIT(3))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_1_F_S 3
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_W (BIT(2))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_W_S 2
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_R (BIT(1))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_R_S 1
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_F (BIT(0))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_0_F_S 0

#define SENSITIVE_PMS_PRO_IRAM0_2_REG (REG_SENSITIVE_BASE + 0x018)
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_W (BIT(22))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_W_S 22
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_R (BIT(21))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_R_S 21
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_F (BIT(20))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_H_F_S 20
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_W (BIT(19))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_W_S 19
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_R (BIT(18))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_R_S 18
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_F (BIT(17))
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_L_F_S 17
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_SPLTADDR 0x0001FFFF
#define SENSITIVE_PMS_PRO_IRAM0_SRAM_4_SPLTADDR_S 0

#define SENSITIVE_PMS_PRO_IRAM0_3_REG (REG_SENSITIVE_BASE + 0x01C)
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_W (BIT(16))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_W_S 16
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_R (BIT(15))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_R_S 15
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_F (BIT(14))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_H_F_S 14
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_W (BIT(13))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_W_S 13
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_R (BIT(12))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_R_S 12
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_F (BIT(11))
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_L_F_S 11
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_SPLTADDR 0x000007FF
#define SENSITIVE_PMS_PRO_IRAM0_RTCFAST_SPLTADDR_S 0

#define SENSITIVE_PMS_PRO_IRAM0_4_REG (REG_SENSITIVE_BASE + 0x020)
#define SENSITIVE_PMS_PRO_IRAM0_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_PRO_IRAM0_ILG_INTR_S 2
#define SENSITIVE_PMS_PRO_IRAM0_ILG_EN (BIT(1))
#define SENSITIVE_PMS_PRO_IRAM0_ILG_EN_S 1
#define SENSITIVE_PMS_PRO_IRAM0_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_PRO_IRAM0_ILG_CLR_S 0

#define SENSITIVE_PMS_PRO_IRAM0_5_REG (REG_SENSITIVE_BASE + 0x024)
#define SENSITIVE_PMS_PRO_IRAM0_ILG_ST 0x003FFFFF
#define SENSITIVE_PMS_PRO_IRAM0_ILG_ST_S 0

#define SENSITIVE_PMS_PRO_DRAM0_0_REG (REG_SENSITIVE_BASE + 0x028)
#define SENSITIVE_PMS_PRO_DRAM0_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_DRAM0_LOCK_S 0

#define SENSITIVE_PMS_PRO_DRAM0_1_REG (REG_SENSITIVE_BASE + 0x02C)
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_H_W (BIT(28))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_H_W_S 28
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_H_R (BIT(27))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_H_R_S 27
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_L_W (BIT(26))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_L_W_S 26
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_L_R (BIT(25))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_L_R_S 25
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_SPLTADDR 0x0001FFFF
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_4_SPLTADDR_S 8
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_3_W (BIT(7))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_3_W_S 7
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_3_R (BIT(6))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_3_R_S 6
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_2_W (BIT(5))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_2_W_S 5
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_2_R (BIT(4))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_2_R_S 4
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_1_W (BIT(3))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_1_W_S 3
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_1_R (BIT(2))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_1_R_S 2
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_0_W (BIT(1))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_0_W_S 1
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_0_R (BIT(0))
#define SENSITIVE_PMS_PRO_DRAM0_SRAM_0_R_S 0

#define SENSITIVE_PMS_PRO_DRAM0_2_REG (REG_SENSITIVE_BASE + 0x030)
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_H_W (BIT(14))
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_H_W_S 14
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_H_R (BIT(13))
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_H_R_S 13
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_L_W (BIT(12))
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_L_W_S 12
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_L_R (BIT(11))
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_L_R_S 11
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_SPLTADDR 0x000007FF
#define SENSITIVE_PMS_PRO_DRAM0_RTCFAST_SPLTADDR_S 0

#define SENSITIVE_PMS_PRO_DRAM0_3_REG (REG_SENSITIVE_BASE + 0x034)
#define SENSITIVE_PMS_PRO_DRAM0_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_PRO_DRAM0_ILG_INTR_S 2
#define SENSITIVE_PMS_PRO_DRAM0_ILG_EN (BIT(1))
#define SENSITIVE_PMS_PRO_DRAM0_ILG_EN_S 1
#define SENSITIVE_PMS_PRO_DRAM0_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_PRO_DRAM0_ILG_CLR_S 0

#define SENSITIVE_PMS_PRO_DRAM0_4_REG (REG_SENSITIVE_BASE + 0x038)
#define SENSITIVE_PMS_PRO_DRAM0_ILG_ST 0x03FFFFFF
#define SENSITIVE_PMS_PRO_DRAM0_ILG_ST_S 0

#define SENSITIVE_PMS_PRO_DPORT_0_REG (REG_SENSITIVE_BASE + 0x03C)
#define SENSITIVE_PMS_PRO_DPORT_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_DPORT_LOCK_S 0

#define SENSITIVE_PMS_PRO_DPORT_1_REG (REG_SENSITIVE_BASE + 0x040)
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_VALID 0x0000000F
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_VALID_S 16
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_H_W (BIT(15))
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_H_W_S 15
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_H_R (BIT(14))
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_H_R_S 14
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_L_W (BIT(13))
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_L_W_S 13
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_L_R (BIT(12))
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_L_R_S 12
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_SPLTADDR 0x000007FF
#define SENSITIVE_PMS_PRO_DPORT_RTCSLOW_SPLTADDR_S 1
#define SENSITIVE_PMS_PRO_DPORT_APB_PERIPHERAL_FORBID (BIT(0))
#define SENSITIVE_PMS_PRO_DPORT_APB_PERIPHERAL_FORBID_S 0

#define SENSITIVE_PMS_PRO_DPORT_2_REG (REG_SENSITIVE_BASE + 0x044)
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_0 0x0003FFFF
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_0_S 0

#define SENSITIVE_PMS_PRO_DPORT_3_REG (REG_SENSITIVE_BASE + 0x048)
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_1 0x0003FFFF
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_1_S 0

#define SENSITIVE_PMS_PRO_DPORT_4_REG (REG_SENSITIVE_BASE + 0x04C)
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_2 0x0003FFFF
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_2_S 0

#define SENSITIVE_PMS_PRO_DPORT_5_REG (REG_SENSITIVE_BASE + 0x050)
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_3 0x0003FFFF
#define SENSITIVE_PMS_PRO_DPORT_RESERVE_FIFO_3_S 0

#define SENSITIVE_PMS_PRO_DPORT_6_REG (REG_SENSITIVE_BASE + 0x054)
#define SENSITIVE_PMS_PRO_DPORT_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_PRO_DPORT_ILG_INTR_S 2
#define SENSITIVE_PMS_PRO_DPORT_ILG_EN (BIT(1))
#define SENSITIVE_PMS_PRO_DPORT_ILG_EN_S 1
#define SENSITIVE_PMS_PRO_DPORT_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_PRO_DPORT_ILG_CLR_S 0

#define SENSITIVE_PMS_PRO_DPORT_7_REG (REG_SENSITIVE_BASE + 0x058)
#define SENSITIVE_PMS_PRO_DPORT_ILG_ST 0x03FFFFFF
#define SENSITIVE_PMS_PRO_DPORT_ILG_ST_S 0

#define SENSITIVE_PMS_PRO_AHB_0_REG (REG_SENSITIVE_BASE + 0x05C)
#define SENSITIVE_PMS_PRO_AHB_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_AHB_LOCK_S 0

#define SENSITIVE_PMS_PRO_AHB_1_REG (REG_SENSITIVE_BASE + 0x060)
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_W (BIT(16))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_W_S 16
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_R (BIT(15))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_R_S 15
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_F (BIT(14))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_H_F_S 14
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_W (BIT(13))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_W_S 13
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_R (BIT(12))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_R_S 12
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_F (BIT(11))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_L_F_S 11
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_SPLTADDR 0x000007FF
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_0_SPLTADDR_S 0

#define SENSITIVE_PMS_PRO_AHB_2_REG (REG_SENSITIVE_BASE + 0x064)
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_W (BIT(16))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_W_S 16
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_R (BIT(15))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_R_S 15
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_F (BIT(14))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_H_F_S 14
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_W (BIT(13))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_W_S 13
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_R (BIT(12))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_R_S 12
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_F (BIT(11))
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_L_F_S 11
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_SPLTADDR 0x000007FF
#define SENSITIVE_PMS_PRO_AHB_RTCSLOW_1_SPLTADDR_S 0

#define SENSITIVE_PMS_PRO_AHB_3_REG (REG_SENSITIVE_BASE + 0x068)
#define SENSITIVE_PMS_PRO_AHB_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_PRO_AHB_ILG_INTR_S 2
#define SENSITIVE_PMS_PRO_AHB_ILG_EN (BIT(1))
#define SENSITIVE_PMS_PRO_AHB_ILG_EN_S 1
#define SENSITIVE_PMS_PRO_AHB_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_PRO_AHB_ILG_CLR_S 0

#define SENSITIVE_PMS_PRO_AHB_4_REG (REG_SENSITIVE_BASE + 0x06C)
#define SENSITIVE_PMS_PRO_AHB_ILG_ST 0xFFFFFFFF
#define SENSITIVE_PMS_PRO_AHB_ILG_ST_S 0

#define SENSITIVE_PMS_PRO_TRACE_0_REG (REG_SENSITIVE_BASE + 0x070)
#define SENSITIVE_PMS_PRO_TRACE_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_TRACE_LOCK_S 0

#define SENSITIVE_PMS_PRO_TRACE_1_REG (REG_SENSITIVE_BASE + 0x074)
#define SENSITIVE_PMS_PRO_TRACE_DISABLE (BIT(0))
#define SENSITIVE_PMS_PRO_TRACE_DISABLE_S 0

#define SENSITIVE_PMS_PRO_CACHE_0_REG (REG_SENSITIVE_BASE + 0x078)
#define SENSITIVE_PMS_PRO_CACHE_LOCK (BIT(0))
#define SENSITIVE_PMS_PRO_CACHE_LOCK_S 0

#define SENSITIVE_PMS_PRO_CACHE_1_REG (REG_SENSITIVE_BASE + 0x07C)
#define SENSITIVE_PMS_PRO_CACHE_CONNECT 0x0000FFFF
#define SENSITIVE_PMS_PRO_CACHE_CONNECT_S 0

#define SENSITIVE_PMS_PRO_CACHE_2_REG (REG_SENSITIVE_BASE + 0x080)
#define SENSITIVE_PMS_PRO_CACHE_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_PRO_CACHE_ILG_INTR_S 2
#define SENSITIVE_PMS_PRO_CACHE_ILG_EN (BIT(1))
#define SENSITIVE_PMS_PRO_CACHE_ILG_EN_S 1
#define SENSITIVE_PMS_PRO_CACHE_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_PRO_CACHE_ILG_CLR_S 0

#define SENSITIVE_PMS_PRO_CACHE_3_REG (REG_SENSITIVE_BASE + 0x084)
#define SENSITIVE_PMS_PRO_CACHE_ILG_ST_I 0x0001FFFF
#define SENSITIVE_PMS_PRO_CACHE_ILG_ST_I_S 0

#define SENSITIVE_PMS_PRO_CACHE_4_REG (REG_SENSITIVE_BASE + 0x088)
#define SENSITIVE_PMS_PRO_CACHE_ILG_ST_D 0x0001FFFF
#define SENSITIVE_PMS_PRO_CACHE_ILG_ST_D_S 0

#define SENSITIVE_PMS_DMA_APB_I_0_REG (REG_SENSITIVE_BASE + 0x08C)
#define SENSITIVE_PMS_DMA_APB_I_LOCK (BIT(0))
#define SENSITIVE_PMS_DMA_APB_I_LOCK_S 0

#define SENSITIVE_PMS_DMA_APB_I_1_REG (REG_SENSITIVE_BASE + 0x090)
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_H_W (BIT(28))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_H_W_S 28
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_H_R (BIT(27))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_H_R_S 27
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_L_W (BIT(26))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_L_W_S 26
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_L_R (BIT(25))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_L_R_S 25
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_SPLTADDR 0x0001FFFF
#define SENSITIVE_PMS_DMA_APB_I_SRAM_4_SPLTADDR_S 8
#define SENSITIVE_PMS_DMA_APB_I_SRAM_3_W (BIT(7))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_3_W_S 7
#define SENSITIVE_PMS_DMA_APB_I_SRAM_3_R (BIT(6))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_3_R_S 6
#define SENSITIVE_PMS_DMA_APB_I_SRAM_2_W (BIT(5))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_2_W_S 5
#define SENSITIVE_PMS_DMA_APB_I_SRAM_2_R (BIT(4))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_2_R_S 4
#define SENSITIVE_PMS_DMA_APB_I_SRAM_1_W (BIT(3))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_1_W_S 3
#define SENSITIVE_PMS_DMA_APB_I_SRAM_1_R (BIT(2))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_1_R_S 2
#define SENSITIVE_PMS_DMA_APB_I_SRAM_0_W (BIT(1))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_0_W_S 1
#define SENSITIVE_PMS_DMA_APB_I_SRAM_0_R (BIT(0))
#define SENSITIVE_PMS_DMA_APB_I_SRAM_0_R_S 0

#define SENSITIVE_PMS_DMA_APB_I_2_REG (REG_SENSITIVE_BASE + 0x094)
#define SENSITIVE_PMS_DMA_APB_I_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_DMA_APB_I_ILG_INTR_S 2
#define SENSITIVE_PMS_DMA_APB_I_ILG_EN (BIT(1))
#define SENSITIVE_PMS_DMA_APB_I_ILG_EN_S 1
#define SENSITIVE_PMS_DMA_APB_I_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_DMA_APB_I_ILG_CLR_S 0

#define SENSITIVE_PMS_DMA_APB_I_3_REG (REG_SENSITIVE_BASE + 0x098)
#define SENSITIVE_PMS_DMA_APB_I_ILG_ST 0x007FFFFF
#define SENSITIVE_PMS_DMA_APB_I_ILG_ST_S 0

#define SENSITIVE_PMS_DMA_RX_I_0_REG (REG_SENSITIVE_BASE + 0x09C)
#define SENSITIVE_PMS_DMA_RX_I_LOCK (BIT(0))
#define SENSITIVE_PMS_DMA_RX_I_LOCK_S 0

#define SENSITIVE_PMS_DMA_RX_I_1_REG (REG_SENSITIVE_BASE + 0x0A0)
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_H_W (BIT(28))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_H_W_S 28
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_H_R (BIT(27))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_H_R_S 27
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_L_W (BIT(26))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_L_W_S 26
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_L_R (BIT(25))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_L_R_S 25
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_SPLTADDR 0x0001FFFF
#define SENSITIVE_PMS_DMA_RX_I_SRAM_4_SPLTADDR_S 8
#define SENSITIVE_PMS_DMA_RX_I_SRAM_3_W (BIT(7))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_3_W_S 7
#define SENSITIVE_PMS_DMA_RX_I_SRAM_3_R (BIT(6))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_3_R_S 6
#define SENSITIVE_PMS_DMA_RX_I_SRAM_2_W (BIT(5))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_2_W_S 5
#define SENSITIVE_PMS_DMA_RX_I_SRAM_2_R (BIT(4))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_2_R_S 4
#define SENSITIVE_PMS_DMA_RX_I_SRAM_1_W (BIT(3))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_1_W_S 3
#define SENSITIVE_PMS_DMA_RX_I_SRAM_1_R (BIT(2))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_1_R_S 2
#define SENSITIVE_PMS_DMA_RX_I_SRAM_0_W (BIT(1))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_0_W_S 1
#define SENSITIVE_PMS_DMA_RX_I_SRAM_0_R (BIT(0))
#define SENSITIVE_PMS_DMA_RX_I_SRAM_0_R_S 0

#define SENSITIVE_PMS_DMA_RX_I_2_REG (REG_SENSITIVE_BASE + 0x0A4)
#define SENSITIVE_PMS_DMA_RX_I_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_DMA_RX_I_ILG_INTR_S 2
#define SENSITIVE_PMS_DMA_RX_I_ILG_EN (BIT(1))
#define SENSITIVE_PMS_DMA_RX_I_ILG_EN_S 1
#define SENSITIVE_PMS_DMA_RX_I_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_DMA_RX_I_ILG_CLR_S 0

#define SENSITIVE_PMS_DMA_RX_I_3_REG (REG_SENSITIVE_BASE + 0x0A8)
#define SENSITIVE_PMS_DMA_RX_I_ILG_ST 0x007FFFFF
#define SENSITIVE_PMS_DMA_RX_I_ILG_ST_S 0

#define SENSITIVE_PMS_DMA_TX_I_0_REG (REG_SENSITIVE_BASE + 0x0AC)
#define SENSITIVE_PMS_DMA_TX_I_LOCK (BIT(0))
#define SENSITIVE_PMS_DMA_TX_I_LOCK_S 0

#define SENSITIVE_PMS_DMA_TX_I_1_REG (REG_SENSITIVE_BASE + 0x0B0)
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_H_W (BIT(28))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_H_W_S 28
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_H_R (BIT(27))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_H_R_S 27
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_L_W (BIT(26))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_L_W_S 26
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_L_R (BIT(25))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_L_R_S 25
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_SPLTADDR 0x0001FFFF
#define SENSITIVE_PMS_DMA_TX_I_SRAM_4_SPLTADDR_S 8
#define SENSITIVE_PMS_DMA_TX_I_SRAM_3_W (BIT(7))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_3_W_S 7
#define SENSITIVE_PMS_DMA_TX_I_SRAM_3_R (BIT(6))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_3_R_S 6
#define SENSITIVE_PMS_DMA_TX_I_SRAM_2_W (BIT(5))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_2_W_S 5
#define SENSITIVE_PMS_DMA_TX_I_SRAM_2_R (BIT(4))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_2_R_S 4
#define SENSITIVE_PMS_DMA_TX_I_SRAM_1_W (BIT(3))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_1_W_S 3
#define SENSITIVE_PMS_DMA_TX_I_SRAM_1_R (BIT(2))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_1_R_S 2
#define SENSITIVE_PMS_DMA_TX_I_SRAM_0_W (BIT(1))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_0_W_S 1
#define SENSITIVE_PMS_DMA_TX_I_SRAM_0_R (BIT(0))
#define SENSITIVE_PMS_DMA_TX_I_SRAM_0_R_S 0

#define SENSITIVE_PMS_DMA_TX_I_2_REG (REG_SENSITIVE_BASE + 0x0B4)
#define SENSITIVE_PMS_DMA_TX_I_ILG_INTR (BIT(2))
#define SENSITIVE_PMS_DMA_TX_I_ILG_INTR_S 2
#define SENSITIVE_PMS_DMA_TX_I_ILG_EN (BIT(1))
#define SENSITIVE_PMS_DMA_TX_I_ILG_EN_S 1
#define SENSITIVE_PMS_DMA_TX_I_ILG_CLR (BIT(0))
#define SENSITIVE_PMS_DMA_TX_I_ILG_CLR_S 0

#define SENSITIVE_PMS_DMA_TX_I_3_REG (REG_SENSITIVE_BASE + 0x0B8)
#define SENSITIVE_PMS_DMA_TX_I_ILG_ST 0x007FFFFF
#define SENSITIVE_PMS_DMA_TX_I_ILG_ST_S 0

#define SENSITIVE_PRO_BOOT_LOCATION_0_REG (REG_SENSITIVE_BASE + 0x0BC)
#define SENSITIVE_PRO_BOOT_LOCATION_LOCK (BIT(0))
#define SENSITIVE_PRO_BOOT_LOCATION_LOCK_S 0

#define SENSITIVE_PRO_BOOT_LOCATION_1_REG (REG_SENSITIVE_BASE + 0x0C0)
#define SENSITIVE_PRO_BOOT_REMAP (BIT(0))
#define SENSITIVE_PRO_BOOT_REMAP_S 0

#define SENSITIVE_CACHE_SOURCE_0_REG (REG_SENSITIVE_BASE + 0x0C4)
#define SENSITIVE_CACHE_SOURCE_LOCK (BIT(0))
#define SENSITIVE_CACHE_SOURCE_LOCK_S 0

#define SENSITIVE_CACHE_SOURCE_1_REG (REG_SENSITIVE_BASE + 0x0C8)
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DROM0 (BIT(5))
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DROM0_S 5
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DPORT (BIT(4))
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DPORT_S 4
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DRAM0 (BIT(3))
#define SENSITIVE_PRO_CACHE_D_SOURCE_PRO_DRAM0_S 3
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_DROM0 (BIT(2))
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_DROM0_S 2
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_IROM0 (BIT(1))
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_IROM0_S 1
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_IRAM1 (BIT(0))
#define SENSITIVE_PRO_CACHE_I_SOURCE_PRO_IRAM1_S 0

#define SENSITIVE_APB_PERIPHERAL_0_REG (REG_SENSITIVE_BASE + 0x0CC)
#define SENSITIVE_APB_PERIPHERAL_LOCK (BIT(0))
#define SENSITIVE_APB_PERIPHERAL_LOCK_S 0

#define SENSITIVE_APB_PERIPHERAL_1_REG (REG_SENSITIVE_BASE + 0x0D0)
#define SENSITIVE_APB_PERIPHERAL_SPLIT_BURST (BIT(0))
#define SENSITIVE_APB_PERIPHERAL_SPLIT_BURST_S 0

#define SENSITIVE_PMS_OCCUPY_0_REG (REG_SENSITIVE_BASE + 0x0D4)
#define SENSITIVE_PMS_OCCUPY_LOCK (BIT(0))
#define SENSITIVE_PMS_OCCUPY_LOCK_S 0

#define SENSITIVE_PMS_OCCUPY_1_REG (REG_SENSITIVE_BASE + 0x0D8)
#define SENSITIVE_PMS_OCCUPY_CACHE 0x0000000F
#define SENSITIVE_PMS_OCCUPY_CACHE_S 0

#define SENSITIVE_PMS_OCCUPY_2_REG (REG_SENSITIVE_BASE + 0x0DC)
#define SENSITIVE_PMS_OCCUPY_MAC_DUMP 0x0000000F
#define SENSITIVE_PMS_OCCUPY_MAC_DUMP_S 0

#define SENSITIVE_PMS_OCCUPY_3_REG (REG_SENSITIVE_BASE + 0x0E0)
#define SENSITIVE_PMS_OCCUPY_PRO_TRACE 0x0003FFFF
#define SENSITIVE_PMS_OCCUPY_PRO_TRACE_S 0

#define SENSITIVE_CACHE_TAG_ACCESS_0_REG (REG_SENSITIVE_BASE + 0x0E4)
#define SENSITIVE_CACHE_TAG_ACCESS_LOCK (BIT(0))
#define SENSITIVE_CACHE_TAG_ACCESS_LOCK_S 0

#define SENSITIVE_CACHE_TAG_ACCESS_1_REG (REG_SENSITIVE_BASE + 0x0E8)
#define SENSITIVE_PRO_D_TAG_WR_ACS (BIT(3))
#define SENSITIVE_PRO_D_TAG_WR_ACS_S 3
#define SENSITIVE_PRO_D_TAG_RD_ACS (BIT(2))
#define SENSITIVE_PRO_D_TAG_RD_ACS_S 2
#define SENSITIVE_PRO_I_TAG_WR_ACS (BIT(1))
#define SENSITIVE_PRO_I_TAG_WR_ACS_S 1
#define SENSITIVE_PRO_I_TAG_RD_ACS (BIT(0))
#define SENSITIVE_PRO_I_TAG_RD_ACS_S 0

#define SENSITIVE_CLOCK_GATE_REG (REG_SENSITIVE_BASE + 0x0EC)
#define SENSITIVE_CLK_EN (BIT(0))
#define SENSITIVE_CLK_EN_S 0

#define SENSITIVE_REG_DATE_REG (REG_SENSITIVE_BASE + 0xFFC)
#define SENSITIVE_DATE 0x0FFFFFFF
#define SENSITIVE_DATE_S 0
#define SENSITIVE_DATE_VERSION 0x1809042
