
#define SLCCONF0_REG (REG_SLC_BASE + 0x0)
#define SLC0_WR_RETRY_MASK_EN (BIT(18))
#define SLC0_WR_RETRY_MASK_EN_S 18
#define SLC0_TOKEN_SEL (BIT(15))
#define SLC0_TOKEN_SEL_S 15
#define SLC0_TOKEN_AUTO_CLR (BIT(14))
#define SLC0_TOKEN_AUTO_CLR_S 14
#define SLC0_TXDATA_BURST_EN (BIT(13))
#define SLC0_TXDATA_BURST_EN_S 13
#define SLC0_TXDSCR_BURST_EN (BIT(12))
#define SLC0_TXDSCR_BURST_EN_S 12
#define SLC0_TXLINK_AUTO_RET (BIT(11))
#define SLC0_TXLINK_AUTO_RET_S 11
#define SLC0_RXLINK_AUTO_RET (BIT(10))
#define SLC0_RXLINK_AUTO_RET_S 10
#define SLC0_RXDATA_BURST_EN (BIT(9))
#define SLC0_RXDATA_BURST_EN_S 9
#define SLC0_RXDSCR_BURST_EN (BIT(8))
#define SLC0_RXDSCR_BURST_EN_S 8
#define SLC0_RX_NO_RESTART_CLR (BIT(7))
#define SLC0_RX_NO_RESTART_CLR_S 7
#define SLC0_RX_AUTO_WRBACK (BIT(6))
#define SLC0_RX_AUTO_WRBACK_S 6
#define SLC0_RX_LOOP_TEST (BIT(5))
#define SLC0_RX_LOOP_TEST_S 5
#define SLC0_TX_LOOP_TEST (BIT(4))
#define SLC0_TX_LOOP_TEST_S 4
#define SLC_AHBM_RST (BIT(3))
#define SLC_AHBM_RST_S 3
#define SLC_AHBM_FIFO_RST (BIT(2))
#define SLC_AHBM_FIFO_RST_S 2
#define SLC0_RX_RST (BIT(1))
#define SLC0_RX_RST_S 1
#define SLC0_TX_RST (BIT(0))
#define SLC0_TX_RST_S 0

#define SLC0INT_RAW_REG (REG_SLC_BASE + 0x4)
#define SLC0_HOST_POP_EOF_ERR_INT_RAW (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_RAW_S 27
#define SLC0_RX_QUICK_EOF_INT_RAW (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_RAW_S 26
#define SLC_CMD_DTC_INT_RAW (BIT(25))
#define SLC_CMD_DTC_INT_RAW_S 25
#define SLC0_TX_ERR_EOF_INT_RAW (BIT(24))
#define SLC0_TX_ERR_EOF_INT_RAW_S 24
#define SLC0_WR_RETRY_DONE_INT_RAW (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_RAW_S 23
#define SLC0_HOST_RD_ACK_INT_RAW (BIT(22))
#define SLC0_HOST_RD_ACK_INT_RAW_S 22
#define SLC0_TX_DSCR_EMPTY_INT_RAW (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_RAW_S 21
#define SLC0_RX_DSCR_ERR_INT_RAW (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_RAW_S 20
#define SLC0_TX_DSCR_ERR_INT_RAW (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_RAW_S 19
#define SLC0_TOHOST_INT_RAW (BIT(18))
#define SLC0_TOHOST_INT_RAW_S 18
#define SLC0_RX_EOF_INT_RAW (BIT(17))
#define SLC0_RX_EOF_INT_RAW_S 17
#define SLC0_RX_DONE_INT_RAW (BIT(16))
#define SLC0_RX_DONE_INT_RAW_S 16
#define SLC0_TX_SUC_EOF_INT_RAW (BIT(15))
#define SLC0_TX_SUC_EOF_INT_RAW_S 15
#define SLC0_TX_DONE_INT_RAW (BIT(14))
#define SLC0_TX_DONE_INT_RAW_S 14
#define SLC0_TOKEN1_1TO0_INT_RAW (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_RAW_S 13
#define SLC0_TOKEN0_1TO0_INT_RAW (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_RAW_S 12
#define SLC0_TX_OVF_INT_RAW (BIT(11))
#define SLC0_TX_OVF_INT_RAW_S 11
#define SLC0_RX_UDF_INT_RAW (BIT(10))
#define SLC0_RX_UDF_INT_RAW_S 10
#define SLC0_TX_START_INT_RAW (BIT(9))
#define SLC0_TX_START_INT_RAW_S 9
#define SLC0_RX_START_INT_RAW (BIT(8))
#define SLC0_RX_START_INT_RAW_S 8
#define SLC_FRHOST_BIT7_INT_RAW (BIT(7))
#define SLC_FRHOST_BIT7_INT_RAW_S 7
#define SLC_FRHOST_BIT6_INT_RAW (BIT(6))
#define SLC_FRHOST_BIT6_INT_RAW_S 6
#define SLC_FRHOST_BIT5_INT_RAW (BIT(5))
#define SLC_FRHOST_BIT5_INT_RAW_S 5
#define SLC_FRHOST_BIT4_INT_RAW (BIT(4))
#define SLC_FRHOST_BIT4_INT_RAW_S 4
#define SLC_FRHOST_BIT3_INT_RAW (BIT(3))
#define SLC_FRHOST_BIT3_INT_RAW_S 3
#define SLC_FRHOST_BIT2_INT_RAW (BIT(2))
#define SLC_FRHOST_BIT2_INT_RAW_S 2
#define SLC_FRHOST_BIT1_INT_RAW (BIT(1))
#define SLC_FRHOST_BIT1_INT_RAW_S 1
#define SLC_FRHOST_BIT0_INT_RAW (BIT(0))
#define SLC_FRHOST_BIT0_INT_RAW_S 0

#define SLC0INT_ST_REG (REG_SLC_BASE + 0x8)
#define SLC0_HOST_POP_EOF_ERR_INT_ST (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_ST_S 27
#define SLC0_RX_QUICK_EOF_INT_ST (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_ST_S 26
#define SLC_CMD_DTC_INT_ST (BIT(25))
#define SLC_CMD_DTC_INT_ST_S 25
#define SLC0_TX_ERR_EOF_INT_ST (BIT(24))
#define SLC0_TX_ERR_EOF_INT_ST_S 24
#define SLC0_WR_RETRY_DONE_INT_ST (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_ST_S 23
#define SLC0_HOST_RD_ACK_INT_ST (BIT(22))
#define SLC0_HOST_RD_ACK_INT_ST_S 22
#define SLC0_TX_DSCR_EMPTY_INT_ST (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_ST_S 21
#define SLC0_RX_DSCR_ERR_INT_ST (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_ST_S 20
#define SLC0_TX_DSCR_ERR_INT_ST (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_ST_S 19
#define SLC0_TOHOST_INT_ST (BIT(18))
#define SLC0_TOHOST_INT_ST_S 18
#define SLC0_RX_EOF_INT_ST (BIT(17))
#define SLC0_RX_EOF_INT_ST_S 17
#define SLC0_RX_DONE_INT_ST (BIT(16))
#define SLC0_RX_DONE_INT_ST_S 16
#define SLC0_TX_SUC_EOF_INT_ST (BIT(15))
#define SLC0_TX_SUC_EOF_INT_ST_S 15
#define SLC0_TX_DONE_INT_ST (BIT(14))
#define SLC0_TX_DONE_INT_ST_S 14
#define SLC0_TOKEN1_1TO0_INT_ST (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_ST_S 13
#define SLC0_TOKEN0_1TO0_INT_ST (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_ST_S 12
#define SLC0_TX_OVF_INT_ST (BIT(11))
#define SLC0_TX_OVF_INT_ST_S 11
#define SLC0_RX_UDF_INT_ST (BIT(10))
#define SLC0_RX_UDF_INT_ST_S 10
#define SLC0_TX_START_INT_ST (BIT(9))
#define SLC0_TX_START_INT_ST_S 9
#define SLC0_RX_START_INT_ST (BIT(8))
#define SLC0_RX_START_INT_ST_S 8
#define SLC_FRHOST_BIT7_INT_ST (BIT(7))
#define SLC_FRHOST_BIT7_INT_ST_S 7
#define SLC_FRHOST_BIT6_INT_ST (BIT(6))
#define SLC_FRHOST_BIT6_INT_ST_S 6
#define SLC_FRHOST_BIT5_INT_ST (BIT(5))
#define SLC_FRHOST_BIT5_INT_ST_S 5
#define SLC_FRHOST_BIT4_INT_ST (BIT(4))
#define SLC_FRHOST_BIT4_INT_ST_S 4
#define SLC_FRHOST_BIT3_INT_ST (BIT(3))
#define SLC_FRHOST_BIT3_INT_ST_S 3
#define SLC_FRHOST_BIT2_INT_ST (BIT(2))
#define SLC_FRHOST_BIT2_INT_ST_S 2
#define SLC_FRHOST_BIT1_INT_ST (BIT(1))
#define SLC_FRHOST_BIT1_INT_ST_S 1
#define SLC_FRHOST_BIT0_INT_ST (BIT(0))
#define SLC_FRHOST_BIT0_INT_ST_S 0

#define SLC0INT_ENA_REG (REG_SLC_BASE + 0xC)
#define SLC0_HOST_POP_EOF_ERR_INT_ENA (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_ENA_S 27
#define SLC0_RX_QUICK_EOF_INT_ENA (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_ENA_S 26
#define SLC_CMD_DTC_INT_ENA (BIT(25))
#define SLC_CMD_DTC_INT_ENA_S 25
#define SLC0_TX_ERR_EOF_INT_ENA (BIT(24))
#define SLC0_TX_ERR_EOF_INT_ENA_S 24
#define SLC0_WR_RETRY_DONE_INT_ENA (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_ENA_S 23
#define SLC0_HOST_RD_ACK_INT_ENA (BIT(22))
#define SLC0_HOST_RD_ACK_INT_ENA_S 22
#define SLC0_TX_DSCR_EMPTY_INT_ENA (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_ENA_S 21
#define SLC0_RX_DSCR_ERR_INT_ENA (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_ENA_S 20
#define SLC0_TX_DSCR_ERR_INT_ENA (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_ENA_S 19
#define SLC0_TOHOST_INT_ENA (BIT(18))
#define SLC0_TOHOST_INT_ENA_S 18
#define SLC0_RX_EOF_INT_ENA (BIT(17))
#define SLC0_RX_EOF_INT_ENA_S 17
#define SLC0_RX_DONE_INT_ENA (BIT(16))
#define SLC0_RX_DONE_INT_ENA_S 16
#define SLC0_TX_SUC_EOF_INT_ENA (BIT(15))
#define SLC0_TX_SUC_EOF_INT_ENA_S 15
#define SLC0_TX_DONE_INT_ENA (BIT(14))
#define SLC0_TX_DONE_INT_ENA_S 14
#define SLC0_TOKEN1_1TO0_INT_ENA (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_ENA_S 13
#define SLC0_TOKEN0_1TO0_INT_ENA (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_ENA_S 12
#define SLC0_TX_OVF_INT_ENA (BIT(11))
#define SLC0_TX_OVF_INT_ENA_S 11
#define SLC0_RX_UDF_INT_ENA (BIT(10))
#define SLC0_RX_UDF_INT_ENA_S 10
#define SLC0_TX_START_INT_ENA (BIT(9))
#define SLC0_TX_START_INT_ENA_S 9
#define SLC0_RX_START_INT_ENA (BIT(8))
#define SLC0_RX_START_INT_ENA_S 8
#define SLC_FRHOST_BIT7_INT_ENA (BIT(7))
#define SLC_FRHOST_BIT7_INT_ENA_S 7
#define SLC_FRHOST_BIT6_INT_ENA (BIT(6))
#define SLC_FRHOST_BIT6_INT_ENA_S 6
#define SLC_FRHOST_BIT5_INT_ENA (BIT(5))
#define SLC_FRHOST_BIT5_INT_ENA_S 5
#define SLC_FRHOST_BIT4_INT_ENA (BIT(4))
#define SLC_FRHOST_BIT4_INT_ENA_S 4
#define SLC_FRHOST_BIT3_INT_ENA (BIT(3))
#define SLC_FRHOST_BIT3_INT_ENA_S 3
#define SLC_FRHOST_BIT2_INT_ENA (BIT(2))
#define SLC_FRHOST_BIT2_INT_ENA_S 2
#define SLC_FRHOST_BIT1_INT_ENA (BIT(1))
#define SLC_FRHOST_BIT1_INT_ENA_S 1
#define SLC_FRHOST_BIT0_INT_ENA (BIT(0))
#define SLC_FRHOST_BIT0_INT_ENA_S 0

#define SLC0INT_CLR_REG (REG_SLC_BASE + 0x10)
#define SLC0_HOST_POP_EOF_ERR_INT_CLR (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_CLR_S 27
#define SLC0_RX_QUICK_EOF_INT_CLR (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_CLR_S 26
#define SLC_CMD_DTC_INT_CLR (BIT(25))
#define SLC_CMD_DTC_INT_CLR_S 25
#define SLC0_TX_ERR_EOF_INT_CLR (BIT(24))
#define SLC0_TX_ERR_EOF_INT_CLR_S 24
#define SLC0_WR_RETRY_DONE_INT_CLR (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_CLR_S 23
#define SLC0_HOST_RD_ACK_INT_CLR (BIT(22))
#define SLC0_HOST_RD_ACK_INT_CLR_S 22
#define SLC0_TX_DSCR_EMPTY_INT_CLR (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_CLR_S 21
#define SLC0_RX_DSCR_ERR_INT_CLR (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_CLR_S 20
#define SLC0_TX_DSCR_ERR_INT_CLR (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_CLR_S 19
#define SLC0_TOHOST_INT_CLR (BIT(18))
#define SLC0_TOHOST_INT_CLR_S 18
#define SLC0_RX_EOF_INT_CLR (BIT(17))
#define SLC0_RX_EOF_INT_CLR_S 17
#define SLC0_RX_DONE_INT_CLR (BIT(16))
#define SLC0_RX_DONE_INT_CLR_S 16
#define SLC0_TX_SUC_EOF_INT_CLR (BIT(15))
#define SLC0_TX_SUC_EOF_INT_CLR_S 15
#define SLC0_TX_DONE_INT_CLR (BIT(14))
#define SLC0_TX_DONE_INT_CLR_S 14
#define SLC0_TOKEN1_1TO0_INT_CLR (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_CLR_S 13
#define SLC0_TOKEN0_1TO0_INT_CLR (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_CLR_S 12
#define SLC0_TX_OVF_INT_CLR (BIT(11))
#define SLC0_TX_OVF_INT_CLR_S 11
#define SLC0_RX_UDF_INT_CLR (BIT(10))
#define SLC0_RX_UDF_INT_CLR_S 10
#define SLC0_TX_START_INT_CLR (BIT(9))
#define SLC0_TX_START_INT_CLR_S 9
#define SLC0_RX_START_INT_CLR (BIT(8))
#define SLC0_RX_START_INT_CLR_S 8
#define SLC_FRHOST_BIT7_INT_CLR (BIT(7))
#define SLC_FRHOST_BIT7_INT_CLR_S 7
#define SLC_FRHOST_BIT6_INT_CLR (BIT(6))
#define SLC_FRHOST_BIT6_INT_CLR_S 6
#define SLC_FRHOST_BIT5_INT_CLR (BIT(5))
#define SLC_FRHOST_BIT5_INT_CLR_S 5
#define SLC_FRHOST_BIT4_INT_CLR (BIT(4))
#define SLC_FRHOST_BIT4_INT_CLR_S 4
#define SLC_FRHOST_BIT3_INT_CLR (BIT(3))
#define SLC_FRHOST_BIT3_INT_CLR_S 3
#define SLC_FRHOST_BIT2_INT_CLR (BIT(2))
#define SLC_FRHOST_BIT2_INT_CLR_S 2
#define SLC_FRHOST_BIT1_INT_CLR (BIT(1))
#define SLC_FRHOST_BIT1_INT_CLR_S 1
#define SLC_FRHOST_BIT0_INT_CLR (BIT(0))
#define SLC_FRHOST_BIT0_INT_CLR_S 0

#define SLCRX_STATUS_REG (REG_SLC_BASE + 0x24)
#define SLC0_RX_BUF_LEN 0x00000FFF
#define SLC0_RX_BUF_LEN_S 2
#define SLC0_RX_EMPTY (BIT(1))
#define SLC0_RX_EMPTY_S 1
#define SLC0_RX_FULL (BIT(0))
#define SLC0_RX_FULL_S 0

#define SLC0RXFIFO_PUSH_REG (REG_SLC_BASE + 0x28)
#define SLC0_RXFIFO_PUSH (BIT(16))
#define SLC0_RXFIFO_PUSH_S 16
#define SLC0_RXFIFO_WDATA 0x000001FF
#define SLC0_RXFIFO_WDATA_S 0

#define SLCTX_STATUS_REG (REG_SLC_BASE + 0x30)
#define SLC0_TX_EMPTY (BIT(1))
#define SLC0_TX_EMPTY_S 1
#define SLC0_TX_FULL (BIT(0))
#define SLC0_TX_FULL_S 0

#define SLC0TXFIFO_POP_REG (REG_SLC_BASE + 0x34)
#define SLC0_TXFIFO_POP (BIT(16))
#define SLC0_TXFIFO_POP_S 16
#define SLC0_TXFIFO_RDATA 0x000007FF
#define SLC0_TXFIFO_RDATA_S 0

#define SLC0RX_LINK_REG (REG_SLC_BASE + 0x3C)
#define SLC0_RXLINK_PARK (BIT(31))
#define SLC0_RXLINK_PARK_S 31
#define SLC0_RXLINK_RESTART (BIT(30))
#define SLC0_RXLINK_RESTART_S 30
#define SLC0_RXLINK_START (BIT(29))
#define SLC0_RXLINK_START_S 29
#define SLC0_RXLINK_STOP (BIT(28))
#define SLC0_RXLINK_STOP_S 28
#define SLC0_RXLINK_ADDR 0x000FFFFF
#define SLC0_RXLINK_ADDR_S 0

#define SLC0TX_LINK_REG (REG_SLC_BASE + 0x40)
#define SLC0_TXLINK_PARK (BIT(31))
#define SLC0_TXLINK_PARK_S 31
#define SLC0_TXLINK_RESTART (BIT(30))
#define SLC0_TXLINK_RESTART_S 30
#define SLC0_TXLINK_START (BIT(29))
#define SLC0_TXLINK_START_S 29
#define SLC0_TXLINK_STOP (BIT(28))
#define SLC0_TXLINK_STOP_S 28
#define SLC0_TXLINK_ADDR 0x000FFFFF
#define SLC0_TXLINK_ADDR_S 0

#define SLCINTVEC_TOHOST_REG (REG_SLC_BASE + 0x4C)
#define SLC0_TOHOST_INTVEC 0x000000FF
#define SLC0_TOHOST_INTVEC_S 0

#define SLC0TOKEN0_REG (REG_SLC_BASE + 0x50)
#define SLC0_TOKEN0 0x00000FFF
#define SLC0_TOKEN0_S 16
#define SLC0_TOKEN0_INC_MORE (BIT(14))
#define SLC0_TOKEN0_INC_MORE_S 14
#define SLC0_TOKEN0_INC (BIT(13))
#define SLC0_TOKEN0_INC_S 13
#define SLC0_TOKEN0_WR (BIT(12))
#define SLC0_TOKEN0_WR_S 12
#define SLC0_TOKEN0_WDATA 0x00000FFF
#define SLC0_TOKEN0_WDATA_S 0

#define SLC0TOKEN1_REG (REG_SLC_BASE + 0x54)
#define SLC0_TOKEN1 0x00000FFF
#define SLC0_TOKEN1_S 16
#define SLC0_TOKEN1_INC_MORE (BIT(14))
#define SLC0_TOKEN1_INC_MORE_S 14
#define SLC0_TOKEN1_INC (BIT(13))
#define SLC0_TOKEN1_INC_S 13
#define SLC0_TOKEN1_WR (BIT(12))
#define SLC0_TOKEN1_WR_S 12
#define SLC0_TOKEN1_WDATA 0x00000FFF
#define SLC0_TOKEN1_WDATA_S 0

#define SLCCONF1_REG (REG_SLC_BASE + 0x60)
#define SLC_CLK_EN (BIT(22))
#define SLC_CLK_EN_S 22
#define SLC_HOST_INT_LEVEL_SEL (BIT(19))
#define SLC_HOST_INT_LEVEL_SEL_S 19
#define SLC0_RX_STITCH_EN (BIT(6))
#define SLC0_RX_STITCH_EN_S 6
#define SLC0_TX_STITCH_EN (BIT(5))
#define SLC0_TX_STITCH_EN_S 5
#define SLC0_LEN_AUTO_CLR (BIT(4))
#define SLC0_LEN_AUTO_CLR_S 4
#define SLC_CMD_HOLD_EN (BIT(3))
#define SLC_CMD_HOLD_EN_S 3
#define SLC0_RX_CHECK_SUM_EN (BIT(2))
#define SLC0_RX_CHECK_SUM_EN_S 2
#define SLC0_TX_CHECK_SUM_EN (BIT(1))
#define SLC0_TX_CHECK_SUM_EN_S 1
#define SLC0_CHECK_OWNER (BIT(0))
#define SLC0_CHECK_OWNER_S 0

#define SLC0_STATE0_REG (REG_SLC_BASE + 0x64)
#define SLC0_STATE0 0xFFFFFFFF
#define SLC0_STATE0_S 0

#define SLC0_STATE1_REG (REG_SLC_BASE + 0x68)
#define SLC0_STATE1 0xFFFFFFFF
#define SLC0_STATE1_S 0

#define SLCBRIDGE_CONF_REG (REG_SLC_BASE + 0x74)
#define SLC_TX_PUSH_IDLE_NUM 0x0000FFFF
#define SLC_TX_PUSH_IDLE_NUM_S 16
#define SLC_HDA_MAP_128K (BIT(13))
#define SLC_HDA_MAP_128K_S 13
#define SLC0_TX_DUMMY_MODE (BIT(12))
#define SLC0_TX_DUMMY_MODE_S 12
#define SLC_FIFO_MAP_ENA 0x0000000F
#define SLC_FIFO_MAP_ENA_S 8
#define SLC_TXEOF_ENA 0x0000003F
#define SLC_TXEOF_ENA_S 0

#define SLC0_TO_EOF_DES_ADDR_REG (REG_SLC_BASE + 0x78)
#define SLC0_TO_EOF_DES_ADDR 0xFFFFFFFF
#define SLC0_TO_EOF_DES_ADDR_S 0

#define SLC0_TX_EOF_DES_ADDR_REG (REG_SLC_BASE + 0x7C)
#define SLC0_TX_SUC_EOF_DES_ADDR 0xFFFFFFFF
#define SLC0_TX_SUC_EOF_DES_ADDR_S 0

#define SLC0_TO_EOF_BFR_DES_ADDR_REG (REG_SLC_BASE + 0x80)
#define SLC0_TO_EOF_BFR_DES_ADDR 0xFFFFFFFF
#define SLC0_TO_EOF_BFR_DES_ADDR_S 0

#define SLC_AHB_TEST_REG (REG_SLC_BASE + 0x90)
#define SLC_AHB_TESTADDR 0x00000003
#define SLC_AHB_TESTADDR_S 4
#define SLC_AHB_TESTMODE 0x00000007
#define SLC_AHB_TESTMODE_S 0

#define SLC_SDIO_ST_REG (REG_SLC_BASE + 0x94)
#define SLC_FUNC1_ACC_STATE 0x0000001F
#define SLC_FUNC1_ACC_STATE_S 16
#define SLC_BUS_ST 0x00000007
#define SLC_BUS_ST_S 12
#define SLC_SDIO_WAKEUP (BIT(8))
#define SLC_SDIO_WAKEUP_S 8
#define SLC_FUNC_ST 0x0000000F
#define SLC_FUNC_ST_S 4
#define SLC_CMD_ST 0x00000007
#define SLC_CMD_ST_S 0

#define SLC_RX_DSCR_CONF_REG (REG_SLC_BASE + 0x98)
#define SLC0_RD_RETRY_THRESHOLD 0x000007FF
#define SLC0_RD_RETRY_THRESHOLD_S 5
#define SLC0_RX_FILL_EN (BIT(4))
#define SLC0_RX_FILL_EN_S 4
#define SLC0_RX_EOF_MODE (BIT(3))
#define SLC0_RX_EOF_MODE_S 3
#define SLC0_RX_FILL_MODE (BIT(2))
#define SLC0_RX_FILL_MODE_S 2
#define SLC0_INFOR_NO_REPLACE (BIT(1))
#define SLC0_INFOR_NO_REPLACE_S 1
#define SLC0_TOKEN_NO_REPLACE (BIT(0))
#define SLC0_TOKEN_NO_REPLACE_S 0

#define SLC0_TXLINK_DSCR_REG (REG_SLC_BASE + 0x9C)
#define SLC0_TXLINK_DSCR 0xFFFFFFFF
#define SLC0_TXLINK_DSCR_S 0

#define SLC0_TXLINK_DSCR_BF0_REG (REG_SLC_BASE + 0xA0)
#define SLC0_TXLINK_DSCR_BF0 0xFFFFFFFF
#define SLC0_TXLINK_DSCR_BF0_S 0

#define SLC0_TXLINK_DSCR_BF1_REG (REG_SLC_BASE + 0xA4)
#define SLC0_TXLINK_DSCR_BF1 0xFFFFFFFF
#define SLC0_TXLINK_DSCR_BF1_S 0

#define SLC0_RXLINK_DSCR_REG (REG_SLC_BASE + 0xA8)
#define SLC0_RXLINK_DSCR 0xFFFFFFFF
#define SLC0_RXLINK_DSCR_S 0

#define SLC0_RXLINK_DSCR_BF0_REG (REG_SLC_BASE + 0xAC)
#define SLC0_RXLINK_DSCR_BF0 0xFFFFFFFF
#define SLC0_RXLINK_DSCR_BF0_S 0

#define SLC0_RXLINK_DSCR_BF1_REG (REG_SLC_BASE + 0xB0)
#define SLC0_RXLINK_DSCR_BF1 0xFFFFFFFF
#define SLC0_RXLINK_DSCR_BF1_S 0

#define SLC0_TX_ERREOF_DES_ADDR_REG (REG_SLC_BASE + 0xCC)
#define SLC0_TX_ERR_EOF_DES_ADDR 0xFFFFFFFF
#define SLC0_TX_ERR_EOF_DES_ADDR_S 0

#define SLC_TOKEN_LAT_REG (REG_SLC_BASE + 0xD4)
#define SLC0_TOKEN 0x00000FFF
#define SLC0_TOKEN_S 0

#define SLC_TX_DSCR_CONF_REG (REG_SLC_BASE + 0xD8)
#define SLC_WR_RETRY_THRESHOLD 0x000007FF
#define SLC_WR_RETRY_THRESHOLD_S 0

#define SLC_CMD_INFOR0_REG (REG_SLC_BASE + 0xDC)
#define SLC_CMD_CONTENT0 0xFFFFFFFF
#define SLC_CMD_CONTENT0_S 0

#define SLC_CMD_INFOR1_REG (REG_SLC_BASE + 0xE0)
#define SLC_CMD_CONTENT1 0xFFFFFFFF
#define SLC_CMD_CONTENT1_S 0

#define SLC0_LEN_CONF_REG (REG_SLC_BASE + 0xE4)
#define SLC0_TX_NEW_PKT_IND (BIT(28))
#define SLC0_TX_NEW_PKT_IND_S 28
#define SLC0_RX_NEW_PKT_IND (BIT(27))
#define SLC0_RX_NEW_PKT_IND_S 27
#define SLC0_TX_GET_USED_DSCR (BIT(26))
#define SLC0_TX_GET_USED_DSCR_S 26
#define SLC0_RX_GET_USED_DSCR (BIT(25))
#define SLC0_RX_GET_USED_DSCR_S 25
#define SLC0_TX_PACKET_LOAD_EN (BIT(24))
#define SLC0_TX_PACKET_LOAD_EN_S 24
#define SLC0_RX_PACKET_LOAD_EN (BIT(23))
#define SLC0_RX_PACKET_LOAD_EN_S 23
#define SLC0_LEN_INC_MORE (BIT(22))
#define SLC0_LEN_INC_MORE_S 22
#define SLC0_LEN_INC (BIT(21))
#define SLC0_LEN_INC_S 21
#define SLC0_LEN_WR (BIT(20))
#define SLC0_LEN_WR_S 20
#define SLC0_LEN_WDATA 0x000FFFFF
#define SLC0_LEN_WDATA_S 0

#define SLC0_LENGTH_REG (REG_SLC_BASE + 0xE8)
#define SLC0_LEN 0x000FFFFF
#define SLC0_LEN_S 0

#define SLC0_TXPKT_H_DSCR_REG (REG_SLC_BASE + 0xEC)
#define SLC0_TX_PKT_H_DSCR_ADDR 0xFFFFFFFF
#define SLC0_TX_PKT_H_DSCR_ADDR_S 0

#define SLC0_TXPKT_E_DSCR_REG (REG_SLC_BASE + 0xF0)
#define SLC0_TX_PKT_E_DSCR_ADDR 0xFFFFFFFF
#define SLC0_TX_PKT_E_DSCR_ADDR_S 0

#define SLC0_RXPKT_H_DSCR_REG (REG_SLC_BASE + 0xF4)
#define SLC0_RX_PKT_H_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_PKT_H_DSCR_ADDR_S 0

#define SLC0_RXPKT_E_DSCR_REG (REG_SLC_BASE + 0xF8)
#define SLC0_RX_PKT_E_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_PKT_E_DSCR_ADDR_S 0

#define SLC0_TXPKTU_H_DSCR_REG (REG_SLC_BASE + 0xFC)
#define SLC0_TX_PKT_START_DSCR_ADDR 0xFFFFFFFF
#define SLC0_TX_PKT_START_DSCR_ADDR_S 0

#define SLC0_TXPKTU_E_DSCR_REG (REG_SLC_BASE + 0x100)
#define SLC0_TX_PKT_END_DSCR_ADDR 0xFFFFFFFF
#define SLC0_TX_PKT_END_DSCR_ADDR_S 0

#define SLC0_RXPKTU_H_DSCR_REG (REG_SLC_BASE + 0x104)
#define SLC0_RX_PKT_START_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_PKT_START_DSCR_ADDR_S 0

#define SLC0_RXPKTU_E_DSCR_REG (REG_SLC_BASE + 0x108)
#define SLC0_RX_PKT_END_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_PKT_END_DSCR_ADDR_S 0

#define SLC_SEQ_POSITION_REG (REG_SLC_BASE + 0x114)
#define SLC0_SEQ_POSITION 0x000000FF
#define SLC0_SEQ_POSITION_S 0

#define SLC0_DSCR_REC_CONF_REG (REG_SLC_BASE + 0x118)
#define SLC0_RX_DSCR_REC_LIM 0x000003FF
#define SLC0_RX_DSCR_REC_LIM_S 0

#define SLC_SDIO_CRC_ST0_REG (REG_SLC_BASE + 0x11C)
#define SLC_DAT3_CRC_ERR_CNT 0x000000FF
#define SLC_DAT3_CRC_ERR_CNT_S 24
#define SLC_DAT2_CRC_ERR_CNT 0x000000FF
#define SLC_DAT2_CRC_ERR_CNT_S 16
#define SLC_DAT1_CRC_ERR_CNT 0x000000FF
#define SLC_DAT1_CRC_ERR_CNT_S 8
#define SLC_DAT0_CRC_ERR_CNT 0x000000FF
#define SLC_DAT0_CRC_ERR_CNT_S 0

#define SLC_SDIO_CRC_ST1_REG (REG_SLC_BASE + 0x120)
#define SLC_ERR_CNT_CLR (BIT(31))
#define SLC_ERR_CNT_CLR_S 31
#define SLC_CMD_CRC_ERR_CNT 0x000000FF
#define SLC_CMD_CRC_ERR_CNT_S 0

#define SLC0_EOF_START_DES_REG (REG_SLC_BASE + 0x124)
#define SLC0_EOF_START_DES_ADDR 0xFFFFFFFF
#define SLC0_EOF_START_DES_ADDR_S 0

#define SLC0_PUSH_DSCR_ADDR_REG (REG_SLC_BASE + 0x128)
#define SLC0_RX_PUSH_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_PUSH_DSCR_ADDR_S 0

#define SLC0_DONE_DSCR_ADDR_REG (REG_SLC_BASE + 0x12C)
#define SLC0_RX_DONE_DSCR_ADDR 0xFFFFFFFF
#define SLC0_RX_DONE_DSCR_ADDR_S 0

#define SLC0_SUB_START_DES_REG (REG_SLC_BASE + 0x130)
#define SLC0_SUB_PAC_START_DSCR_ADDR 0xFFFFFFFF
#define SLC0_SUB_PAC_START_DSCR_ADDR_S 0

#define SLC0_DSCR_CNT_REG (REG_SLC_BASE + 0x134)
#define SLC0_RX_GET_EOF_OCC (BIT(16))
#define SLC0_RX_GET_EOF_OCC_S 16
#define SLC0_RX_DSCR_CNT_LAT 0x000003FF
#define SLC0_RX_DSCR_CNT_LAT_S 0

#define SLC0_LEN_LIM_CONF_REG (REG_SLC_BASE + 0x138)
#define SLC0_LEN_LIM 0x000FFFFF
#define SLC0_LEN_LIM_S 0

#define SLC0INT_ST1_REG (REG_SLC_BASE + 0x13C)
#define SLC0_HOST_POP_EOF_ERR_INT_ST1 (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_ST1_S 27
#define SLC0_RX_QUICK_EOF_INT_ST1 (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_ST1_S 26
#define SLC_CMD_DTC_INT_ST1 (BIT(25))
#define SLC_CMD_DTC_INT_ST1_S 25
#define SLC0_TX_ERR_EOF_INT_ST1 (BIT(24))
#define SLC0_TX_ERR_EOF_INT_ST1_S 24
#define SLC0_WR_RETRY_DONE_INT_ST1 (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_ST1_S 23
#define SLC0_HOST_RD_ACK_INT_ST1 (BIT(22))
#define SLC0_HOST_RD_ACK_INT_ST1_S 22
#define SLC0_TX_DSCR_EMPTY_INT_ST1 (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_ST1_S 21
#define SLC0_RX_DSCR_ERR_INT_ST1 (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_ST1_S 20
#define SLC0_TX_DSCR_ERR_INT_ST1 (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_ST1_S 19
#define SLC0_TOHOST_INT_ST1 (BIT(18))
#define SLC0_TOHOST_INT_ST1_S 18
#define SLC0_RX_EOF_INT_ST1 (BIT(17))
#define SLC0_RX_EOF_INT_ST1_S 17
#define SLC0_RX_DONE_INT_ST1 (BIT(16))
#define SLC0_RX_DONE_INT_ST1_S 16
#define SLC0_TX_SUC_EOF_INT_ST1 (BIT(15))
#define SLC0_TX_SUC_EOF_INT_ST1_S 15
#define SLC0_TX_DONE_INT_ST1 (BIT(14))
#define SLC0_TX_DONE_INT_ST1_S 14
#define SLC0_TOKEN1_1TO0_INT_ST1 (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_ST1_S 13
#define SLC0_TOKEN0_1TO0_INT_ST1 (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_ST1_S 12
#define SLC0_TX_OVF_INT_ST1 (BIT(11))
#define SLC0_TX_OVF_INT_ST1_S 11
#define SLC0_RX_UDF_INT_ST1 (BIT(10))
#define SLC0_RX_UDF_INT_ST1_S 10
#define SLC0_TX_START_INT_ST1 (BIT(9))
#define SLC0_TX_START_INT_ST1_S 9
#define SLC0_RX_START_INT_ST1 (BIT(8))
#define SLC0_RX_START_INT_ST1_S 8
#define SLC_FRHOST_BIT7_INT_ST1 (BIT(7))
#define SLC_FRHOST_BIT7_INT_ST1_S 7
#define SLC_FRHOST_BIT6_INT_ST1 (BIT(6))
#define SLC_FRHOST_BIT6_INT_ST1_S 6
#define SLC_FRHOST_BIT5_INT_ST1 (BIT(5))
#define SLC_FRHOST_BIT5_INT_ST1_S 5
#define SLC_FRHOST_BIT4_INT_ST1 (BIT(4))
#define SLC_FRHOST_BIT4_INT_ST1_S 4
#define SLC_FRHOST_BIT3_INT_ST1 (BIT(3))
#define SLC_FRHOST_BIT3_INT_ST1_S 3
#define SLC_FRHOST_BIT2_INT_ST1 (BIT(2))
#define SLC_FRHOST_BIT2_INT_ST1_S 2
#define SLC_FRHOST_BIT1_INT_ST1 (BIT(1))
#define SLC_FRHOST_BIT1_INT_ST1_S 1
#define SLC_FRHOST_BIT0_INT_ST1 (BIT(0))
#define SLC_FRHOST_BIT0_INT_ST1_S 0

#define SLC0INT_ENA1_REG (REG_SLC_BASE + 0x140)
#define SLC0_HOST_POP_EOF_ERR_INT_ENA1 (BIT(27))
#define SLC0_HOST_POP_EOF_ERR_INT_ENA1_S 27
#define SLC0_RX_QUICK_EOF_INT_ENA1 (BIT(26))
#define SLC0_RX_QUICK_EOF_INT_ENA1_S 26
#define SLC_CMD_DTC_INT_ENA1 (BIT(25))
#define SLC_CMD_DTC_INT_ENA1_S 25
#define SLC0_TX_ERR_EOF_INT_ENA1 (BIT(24))
#define SLC0_TX_ERR_EOF_INT_ENA1_S 24
#define SLC0_WR_RETRY_DONE_INT_ENA1 (BIT(23))
#define SLC0_WR_RETRY_DONE_INT_ENA1_S 23
#define SLC0_HOST_RD_ACK_INT_ENA1 (BIT(22))
#define SLC0_HOST_RD_ACK_INT_ENA1_S 22
#define SLC0_TX_DSCR_EMPTY_INT_ENA1 (BIT(21))
#define SLC0_TX_DSCR_EMPTY_INT_ENA1_S 21
#define SLC0_RX_DSCR_ERR_INT_ENA1 (BIT(20))
#define SLC0_RX_DSCR_ERR_INT_ENA1_S 20
#define SLC0_TX_DSCR_ERR_INT_ENA1 (BIT(19))
#define SLC0_TX_DSCR_ERR_INT_ENA1_S 19
#define SLC0_TOHOST_INT_ENA1 (BIT(18))
#define SLC0_TOHOST_INT_ENA1_S 18
#define SLC0_RX_EOF_INT_ENA1 (BIT(17))
#define SLC0_RX_EOF_INT_ENA1_S 17
#define SLC0_RX_DONE_INT_ENA1 (BIT(16))
#define SLC0_RX_DONE_INT_ENA1_S 16
#define SLC0_TX_SUC_EOF_INT_ENA1 (BIT(15))
#define SLC0_TX_SUC_EOF_INT_ENA1_S 15
#define SLC0_TX_DONE_INT_ENA1 (BIT(14))
#define SLC0_TX_DONE_INT_ENA1_S 14
#define SLC0_TOKEN1_1TO0_INT_ENA1 (BIT(13))
#define SLC0_TOKEN1_1TO0_INT_ENA1_S 13
#define SLC0_TOKEN0_1TO0_INT_ENA1 (BIT(12))
#define SLC0_TOKEN0_1TO0_INT_ENA1_S 12
#define SLC0_TX_OVF_INT_ENA1 (BIT(11))
#define SLC0_TX_OVF_INT_ENA1_S 11
#define SLC0_RX_UDF_INT_ENA1 (BIT(10))
#define SLC0_RX_UDF_INT_ENA1_S 10
#define SLC0_TX_START_INT_ENA1 (BIT(9))
#define SLC0_TX_START_INT_ENA1_S 9
#define SLC0_RX_START_INT_ENA1 (BIT(8))
#define SLC0_RX_START_INT_ENA1_S 8
#define SLC_FRHOST_BIT7_INT_ENA1 (BIT(7))
#define SLC_FRHOST_BIT7_INT_ENA1_S 7
#define SLC_FRHOST_BIT6_INT_ENA1 (BIT(6))
#define SLC_FRHOST_BIT6_INT_ENA1_S 6
#define SLC_FRHOST_BIT5_INT_ENA1 (BIT(5))
#define SLC_FRHOST_BIT5_INT_ENA1_S 5
#define SLC_FRHOST_BIT4_INT_ENA1 (BIT(4))
#define SLC_FRHOST_BIT4_INT_ENA1_S 4
#define SLC_FRHOST_BIT3_INT_ENA1 (BIT(3))
#define SLC_FRHOST_BIT3_INT_ENA1_S 3
#define SLC_FRHOST_BIT2_INT_ENA1 (BIT(2))
#define SLC_FRHOST_BIT2_INT_ENA1_S 2
#define SLC_FRHOST_BIT1_INT_ENA1 (BIT(1))
#define SLC_FRHOST_BIT1_INT_ENA1_S 1
#define SLC_FRHOST_BIT0_INT_ENA1 (BIT(0))
#define SLC_FRHOST_BIT0_INT_ENA1_S 0

#define SLCDATE_REG (REG_SLC_BASE + 0x1F8)
#define SLC_DATE 0xFFFFFFFF
#define SLC_DATE_S 0
#define SLC_DATE_VERSION 0x18080700

#define SLCID_REG (REG_SLC_BASE + 0x1FC)
#define SLC_ID 0xFFFFFFFF
#define SLC_ID_S 0
