 
#ifndef SPI_REGISTER_H_INCLUDED
#define SPI_REGISTER_H_INCLUDED

#define SPI_CMD_REG( i ) (REG_SPI_BASE( i ) + 0x000)
#define SPI_USR (BIT(24))
#define SPI_USR_S 24
#define SPI_CONF_BITLEN 0x00FFFFFF
#define SPI_CONF_BITLEN_S 0

#define SPI_ADDR_REG( i ) (REG_SPI_BASE( i ) + 0x004)
#define SPI_USR_ADDR_VALUE 0xFFFFFFFF
#define SPI_USR_ADDR_VALUE_S 0

#define SPI_CTRL_REG( i ) (REG_SPI_BASE( i ) + 0x008)
#define SPI_WR_BIT_ORDER (BIT(26))
#define SPI_WR_BIT_ORDER_S 26
#define SPI_RD_BIT_ORDER (BIT(25))
#define SPI_RD_BIT_ORDER_S 25
#define SPI_WP_REG (BIT(21))
#define SPI_WP_REG_S 21
#define SPI_FREAD_QUAD (BIT(20))
#define SPI_FREAD_QUAD_S 20
#define SPI_D_POL (BIT(19))
#define SPI_D_POL_S 19
#define SPI_Q_POL (BIT(18))
#define SPI_Q_POL_S 18
#define SPI_FREAD_DUAL (BIT(14))
#define SPI_FREAD_DUAL_S 14
#define SPI_FAST_RD_MODE (BIT(13))
#define SPI_FAST_RD_MODE_S 13
#define SPI_FCMD_QUAD (BIT(8))
#define SPI_FCMD_QUAD_S 8
#define SPI_FCMD_DUAL (BIT(7))
#define SPI_FCMD_DUAL_S 7
#define SPI_FADDR_QUAD (BIT(6))
#define SPI_FADDR_QUAD_S 6
#define SPI_FADDR_DUAL (BIT(5))
#define SPI_FADDR_DUAL_S 5
#define SPI_DUMMY_OUT (BIT(3))
#define SPI_DUMMY_OUT_S 3
#define SPI_EXT_HOLD_EN (BIT(2))
#define SPI_EXT_HOLD_EN_S 2

#define SPI_CTRL1_REG( i ) (REG_SPI_BASE( i ) + 0x00C)
#define SPI_CS_HOLD_DELAY 0x0000003F
#define SPI_CS_HOLD_DELAY_S 14
#define SPI_W16_17_WR_ENA (BIT(4))
#define SPI_W16_17_WR_ENA_S 4
#define SPI_RSCK_DATA_OUT (BIT(3))
#define SPI_RSCK_DATA_OUT_S 3
#define SPI_CLK_MODE_13 (BIT(2))
#define SPI_CLK_MODE_13_S 2
#define SPI_CLK_MODE 0x00000003
#define SPI_CLK_MODE_S 0

#define SPI_CTRL2_REG( i ) (REG_SPI_BASE( i ) + 0x010)
#define SPI_CS_DELAY_NUM 0x00000003
#define SPI_CS_DELAY_NUM_S 29
#define SPI_CS_DELAY_MODE 0x00000007
#define SPI_CS_DELAY_MODE_S 26
#define SPI_CS_HOLD_TIME 0x00001FFF
#define SPI_CS_HOLD_TIME_S 13
#define SPI_CS_SETUP_TIME 0x00001FFF
#define SPI_CS_SETUP_TIME_S 0

#define SPI_CLOCK_REG( i ) (REG_SPI_BASE( i ) + 0x014)
#define SPI_CLK_EQU_SYSCLK (BIT(31))
#define SPI_CLK_EQU_SYSCLK_S 31
#define SPI_CLKDIV_PRE 0x00001FFF
#define SPI_CLKDIV_PRE_S 18
#define SPI_CLKCNT_N 0x0000003F
#define SPI_CLKCNT_N_S 12
#define SPI_CLKCNT_H 0x0000003F
#define SPI_CLKCNT_H_S 6
#define SPI_CLKCNT_L 0x0000003F
#define SPI_CLKCNT_L_S 0

#define SPI_USER_REG( i ) (REG_SPI_BASE( i ) + 0x018)
#define SPI_USR_COMMAND (BIT(31))
#define SPI_USR_COMMAND_S 31
#define SPI_USR_ADDR (BIT(30))
#define SPI_USR_ADDR_S 30
#define SPI_USR_DUMMY (BIT(29))
#define SPI_USR_DUMMY_S 29
#define SPI_USR_MISO (BIT(28))
#define SPI_USR_MISO_S 28
#define SPI_USR_MOSI (BIT(27))
#define SPI_USR_MOSI_S 27
#define SPI_USR_DUMMY_IDLE (BIT(26))
#define SPI_USR_DUMMY_IDLE_S 26
#define SPI_USR_MOSI_HIGHPART (BIT(25))
#define SPI_USR_MOSI_HIGHPART_S 25
#define SPI_USR_MISO_HIGHPART (BIT(24))
#define SPI_USR_MISO_HIGHPART_S 24
#define SPI_USR_PREP_HOLD (BIT(23))
#define SPI_USR_PREP_HOLD_S 23
#define SPI_USR_CMD_HOLD (BIT(22))
#define SPI_USR_CMD_HOLD_S 22
#define SPI_USR_ADDR_HOLD (BIT(21))
#define SPI_USR_ADDR_HOLD_S 21
#define SPI_USR_DUMMY_HOLD (BIT(20))
#define SPI_USR_DUMMY_HOLD_S 20
#define SPI_USR_DIN_HOLD (BIT(19))
#define SPI_USR_DIN_HOLD_S 19
#define SPI_USR_DOUT_HOLD (BIT(18))
#define SPI_USR_DOUT_HOLD_S 18
#define SPI_USR_HOLD_POL (BIT(17))
#define SPI_USR_HOLD_POL_S 17
#define SPI_SIO (BIT(16))
#define SPI_SIO_S 16
#define SPI_USR_CONF_NXT (BIT(15))
#define SPI_USR_CONF_NXT_S 15
#define SPI_FWRITE_QUAD (BIT(13))
#define SPI_FWRITE_QUAD_S 13
#define SPI_FWRITE_DUAL (BIT(12))
#define SPI_FWRITE_DUAL_S 12
#define SPI_WR_BYTE_ORDER (BIT(11))
#define SPI_WR_BYTE_ORDER_S 11
#define SPI_RD_BYTE_ORDER (BIT(10))
#define SPI_RD_BYTE_ORDER_S 10
#define SPI_CK_OUT_EDGE (BIT(9))
#define SPI_CK_OUT_EDGE_S 9
#define SPI_RSCK_I_EDGE (BIT(8))
#define SPI_RSCK_I_EDGE_S 8
#define SPI_CS_SETUP (BIT(7))
#define SPI_CS_SETUP_S 7
#define SPI_CS_HOLD (BIT(6))
#define SPI_CS_HOLD_S 6
#define SPI_TSCK_I_EDGE (BIT(5))
#define SPI_TSCK_I_EDGE_S 5
#define SPI_TX_START_BIT 0x00000007
#define SPI_TX_START_BIT_S 1
#define SPI_DOUTDIN (BIT(0))
#define SPI_DOUTDIN_S 0

#define SPI_USER1_REG( i ) (REG_SPI_BASE( i ) + 0x01C)
#define SPI_USR_ADDR_BITLEN 0x0000003F
#define SPI_USR_ADDR_BITLEN_S 26
#define SPI_USR_DUMMY_CYCLELEN 0x000000FF
#define SPI_USR_DUMMY_CYCLELEN_S 0

#define SPI_USER2_REG( i ) (REG_SPI_BASE( i ) + 0x020)
#define SPI_USR_COMMAND_BITLEN 0x0000000F
#define SPI_USR_COMMAND_BITLEN_S 28
#define SPI_USR_COMMAND_VALUE 0x0000FFFF
#define SPI_USR_COMMAND_VALUE_S 0

#define SPI_MOSI_DLEN_REG( i ) (REG_SPI_BASE( i ) + 0x024)
#define SPI_USR_MOSI_DBITLEN 0x00FFFFFF
#define SPI_USR_MOSI_DBITLEN_S 0

#define SPI_MISO_DLEN_REG( i ) (REG_SPI_BASE( i ) + 0x028)
#define SPI_USR_MISO_DBITLEN 0x00FFFFFF
#define SPI_USR_MISO_DBITLEN_S 0

#define SPI_SLV_WR_STATUS_REG( i ) (REG_SPI_BASE( i ) + 0x02C)
#define SPI_SLV_WR_STATUS 0xFFFFFFFF
#define SPI_SLV_WR_STATUS_S 0

#define SPI_MISC_REG( i ) (REG_SPI_BASE( i ) + 0x030)
#define SPI_QUAD_DIN_PIN_SWAP (BIT(31))
#define SPI_QUAD_DIN_PIN_SWAP_S 31
#define SPI_CS_KEEP_ACTIVE (BIT(30))
#define SPI_CS_KEEP_ACTIVE_S 30
#define SPI_CK_IDLE_EDGE (BIT(29))
#define SPI_CK_IDLE_EDGE_S 29
#define SPI_Q_IDLE_OUT (BIT(27))
#define SPI_Q_IDLE_OUT_S 27
#define SPI_CD_IDLE_EDGE (BIT(26))
#define SPI_CD_IDLE_EDGE_S 26
#define SPI_CD_CMD_SET (BIT(25))
#define SPI_CD_CMD_SET_S 25
#define SPI_DQS_IDLE_EDGE (BIT(24))
#define SPI_DQS_IDLE_EDGE_S 24
#define SPI_SLAVE_CS_POL (BIT(23))
#define SPI_SLAVE_CS_POL_S 23
#define SPI_CD_ADDR_SET (BIT(22))
#define SPI_CD_ADDR_SET_S 22
#define SPI_MASTER_CS_POL 0x00000007
#define SPI_MASTER_CS_POL_S 6
#define SPI_CK_DIS (BIT(5))
#define SPI_CK_DIS_S 5
#define SPI_CS2_DIS (BIT(2))
#define SPI_CS2_DIS_S 2
#define SPI_CS1_DIS (BIT(1))
#define SPI_CS1_DIS_S 1
#define SPI_CS0_DIS (BIT(0))
#define SPI_CS0_DIS_S 0

#define SPI_SLAVE_REG( i ) (REG_SPI_BASE( i ) + 0x034)
#define SPI_SYNC_RESET (BIT(31))
#define SPI_SYNC_RESET_S 31
#define SPI_SLAVE_MODE (BIT(30))
#define SPI_SLAVE_MODE_S 30
#define SPI_TRANS_DONE_AUTO_CLR_EN (BIT(29))
#define SPI_TRANS_DONE_AUTO_CLR_EN_S 29
#define SPI_TRANS_CNT 0x0000000F
#define SPI_TRANS_CNT_S 23
#define SPI_INT_DMA_SEG_TRANS_EN (BIT(10))
#define SPI_INT_DMA_SEG_TRANS_EN_S 10
#define SPI_INT_TRANS_DONE_EN (BIT(9))
#define SPI_INT_TRANS_DONE_EN_S 9
#define SPI_INT_WR_DMA_DONE_EN (BIT(8))
#define SPI_INT_WR_DMA_DONE_EN_S 8
#define SPI_INT_RD_DMA_DONE_EN (BIT(7))
#define SPI_INT_RD_DMA_DONE_EN_S 7
#define SPI_INT_WR_BUF_DONE_EN (BIT(6))
#define SPI_INT_WR_BUF_DONE_EN_S 6
#define SPI_INT_RD_BUF_DONE_EN (BIT(5))
#define SPI_INT_RD_BUF_DONE_EN_S 5
#define SPI_TRANS_DONE (BIT(4))
#define SPI_TRANS_DONE_S 4

#define SPI_SLAVE1_REG( i ) (REG_SPI_BASE( i ) + 0x038)
#define SPI_SLV_LAST_ADDR 0x0000007F
#define SPI_SLV_LAST_ADDR_S 15
#define SPI_SLV_LAST_COMMAND 0x00000007
#define SPI_SLV_LAST_COMMAND_S 12
#define SPI_SLV_WR_DMA_DONE (BIT(11))
#define SPI_SLV_WR_DMA_DONE_S 11
#define SPI_SLV_WR_ADDR_BYTELEN 0x0000000F
#define SPI_SLV_WR_ADDR_BYTELEN_S 4
#define SPI_SLV_RD_ADDR_BYTELEN 0x0000000F
#define SPI_SLV_RD_ADDR_BYTELEN_S 0

#define SPI_SLAVE2_REG( i ) (REG_SPI_BASE( i ) + 0x03C)
#define SPI_SLV_RD_DMA_DONE (BIT(8))
#define SPI_SLV_RD_DMA_DONE_S 8
#define SPI_SLV_WR_DUMMY_BYTELEN 0x0000000F
#define SPI_SLV_WR_DUMMY_BYTELEN_S 4
#define SPI_SLV_RD_DUMMY_BYTELEN 0x0000000F
#define SPI_SLV_RD_DUMMY_BYTELEN_S 0

#define SPI_SLV_WRBUF_DLEN_REG( i ) (REG_SPI_BASE( i ) + 0x040)
#define SPI_CONF_BASE_BITLEN 0x0000007F
#define SPI_CONF_BASE_BITLEN_S 25
#define SPI_SLV_WR_BUF_DONE (BIT(24))
#define SPI_SLV_WR_BUF_DONE_S 24

#define SPI_SLV_RDBUF_DLEN_REG( i ) (REG_SPI_BASE( i ) + 0x044)
#define SPI_SEG_MAGIC_ERR (BIT(25))
#define SPI_SEG_MAGIC_ERR_S 25
#define SPI_SLV_RD_BUF_DONE (BIT(24))
#define SPI_SLV_RD_BUF_DONE_S 24
#define SPI_SLV_DMA_RD_BYTELEN 0x00FFFFFF
#define SPI_SLV_DMA_RD_BYTELEN_S 0

#define SPI_SLV_RD_BYTE_REG( i ) (REG_SPI_BASE( i ) + 0x048)
#define SPI_USR_CONF (BIT(31))
#define SPI_USR_CONF_S 31
#define SPI_DMA_SEG_MAGIC_VALUE 0x0000003F
#define SPI_DMA_SEG_MAGIC_VALUE_S 24
#define SPI_SLV_RDATA_BYTE 0x00FFFFFF
#define SPI_SLV_RDATA_BYTE_S 0

#define SPI_FSM_REG( i ) (REG_SPI_BASE( i ) + 0x050)
#define SPI_MST_DMA_RD_BYTELEN 0x00FFFFFF
#define SPI_MST_DMA_RD_BYTELEN_S 8
#define SPI_ST 0x0000000F
#define SPI_ST_S 0

#define SPI_HOLD_REG( i ) (REG_SPI_BASE( i ) + 0x054)
#define SPI_DMA_SEG_TRANS_DONE (BIT(7))
#define SPI_DMA_SEG_TRANS_DONE_S 7
#define SPI_HOLD_OUT_TIME 0x00000007
#define SPI_HOLD_OUT_TIME_S 4
#define SPI_HOLD_OUT_EN (BIT(3))
#define SPI_HOLD_OUT_EN_S 3
#define SPI_HOLD_VAL_REG (BIT(2))
#define SPI_HOLD_VAL_REG_S 2
#define SPI_INT_HOLD_ENA 0x00000003
#define SPI_INT_HOLD_ENA_S 0

#define SPI_DMA_CONF_REG( i ) (REG_SPI_BASE( i ) + 0x058)
#define SPI_DMA_OUTFIFO_EMPTY_ERR (BIT(25))
#define SPI_DMA_OUTFIFO_EMPTY_ERR_S 25
#define SPI_DMA_INFIFO_FULL_ERR (BIT(24))
#define SPI_DMA_INFIFO_FULL_ERR_S 24
#define SPI_DMA_OUTFIFO_EMPTY_CLR (BIT(23))
#define SPI_DMA_OUTFIFO_EMPTY_CLR_S 23
#define SPI_DMA_INFIFO_FULL_CLR (BIT(22))
#define SPI_DMA_INFIFO_FULL_CLR_S 22
#define SPI_RX_EOF_EN (BIT(21))
#define SPI_RX_EOF_EN_S 21
#define SPI_SLV_TX_SEG_TRANS_CLR_EN (BIT(20))
#define SPI_SLV_TX_SEG_TRANS_CLR_EN_S 20
#define SPI_SLV_RX_SEG_TRANS_CLR_EN (BIT(19))
#define SPI_SLV_RX_SEG_TRANS_CLR_EN_S 19
#define SPI_DMA_SLV_SEG_TRANS_EN (BIT(18))
#define SPI_DMA_SLV_SEG_TRANS_EN_S 18
#define SPI_DMA_CONTINUE (BIT(16))
#define SPI_DMA_CONTINUE_S 16
#define SPI_DMA_TX_STOP (BIT(15))
#define SPI_DMA_TX_STOP_S 15
#define SPI_DMA_RX_STOP (BIT(14))
#define SPI_DMA_RX_STOP_S 14
#define SPI_MEM_TRANS_EN (BIT(13))
#define SPI_MEM_TRANS_EN_S 13
#define SPI_OUT_DATA_BURST_EN (BIT(12))
#define SPI_OUT_DATA_BURST_EN_S 12
#define SPI_INDSCR_BURST_EN (BIT(11))
#define SPI_INDSCR_BURST_EN_S 11
#define SPI_OUTDSCR_BURST_EN (BIT(10))
#define SPI_OUTDSCR_BURST_EN_S 10
#define SPI_OUT_EOF_MODE (BIT(9))
#define SPI_OUT_EOF_MODE_S 9
#define SPI_OUT_AUTO_WRBACK (BIT(8))
#define SPI_OUT_AUTO_WRBACK_S 8
#define SPI_OUT_LOOP_TEST (BIT(7))
#define SPI_OUT_LOOP_TEST_S 7
#define SPI_IN_LOOP_TEST (BIT(6))
#define SPI_IN_LOOP_TEST_S 6
#define SPI_AHBM_RST (BIT(5))
#define SPI_AHBM_RST_S 5
#define SPI_AHBM_FIFO_RST (BIT(4))
#define SPI_AHBM_FIFO_RST_S 4
#define SPI_OUT_RST (BIT(3))
#define SPI_OUT_RST_S 3
#define SPI_IN_RST (BIT(2))
#define SPI_IN_RST_S 2

#define SPI_DMA_OUT_LINK_REG( i ) (REG_SPI_BASE( i ) + 0x05C)
#define SPI_DMA_TX_ENA (BIT(31))
#define SPI_DMA_TX_ENA_S 31
#define SPI_OUTLINK_RESTART (BIT(30))
#define SPI_OUTLINK_RESTART_S 30
#define SPI_OUTLINK_START (BIT(29))
#define SPI_OUTLINK_START_S 29
#define SPI_OUTLINK_STOP (BIT(28))
#define SPI_OUTLINK_STOP_S 28
#define SPI_OUTLINK_ADDR 0x000FFFFF
#define SPI_OUTLINK_ADDR_S 0

#define SPI_DMA_IN_LINK_REG( i ) (REG_SPI_BASE( i ) + 0x060)
#define SPI_DMA_RX_ENA (BIT(31))
#define SPI_DMA_RX_ENA_S 31
#define SPI_INLINK_RESTART (BIT(30))
#define SPI_INLINK_RESTART_S 30
#define SPI_INLINK_START (BIT(29))
#define SPI_INLINK_START_S 29
#define SPI_INLINK_STOP (BIT(28))
#define SPI_INLINK_STOP_S 28
#define SPI_INLINK_AUTO_RET (BIT(20))
#define SPI_INLINK_AUTO_RET_S 20
#define SPI_INLINK_ADDR 0x000FFFFF
#define SPI_INLINK_ADDR_S 0

#define SPI_DMA_INT_ENA_REG( i ) (REG_SPI_BASE( i ) + 0x064)
#define SPI_OUT_TOTAL_EOF_INT_ENA (BIT(8))
#define SPI_OUT_TOTAL_EOF_INT_ENA_S 8
#define SPI_OUT_EOF_INT_ENA (BIT(7))
#define SPI_OUT_EOF_INT_ENA_S 7
#define SPI_OUT_DONE_INT_ENA (BIT(6))
#define SPI_OUT_DONE_INT_ENA_S 6
#define SPI_IN_SUC_EOF_INT_ENA (BIT(5))
#define SPI_IN_SUC_EOF_INT_ENA_S 5
#define SPI_IN_ERR_EOF_INT_ENA (BIT(4))
#define SPI_IN_ERR_EOF_INT_ENA_S 4
#define SPI_IN_DONE_INT_ENA (BIT(3))
#define SPI_IN_DONE_INT_ENA_S 3
#define SPI_INLINK_DSCR_ERROR_INT_ENA (BIT(2))
#define SPI_INLINK_DSCR_ERROR_INT_ENA_S 2
#define SPI_OUTLINK_DSCR_ERROR_INT_ENA (BIT(1))
#define SPI_OUTLINK_DSCR_ERROR_INT_ENA_S 1
#define SPI_INLINK_DSCR_EMPTY_INT_ENA (BIT(0))
#define SPI_INLINK_DSCR_EMPTY_INT_ENA_S 0

#define SPI_DMA_INT_RAW_REG( i ) (REG_SPI_BASE( i ) + 0x068)
#define SPI_OUT_TOTAL_EOF_INT_RAW (BIT(8))
#define SPI_OUT_TOTAL_EOF_INT_RAW_S 8
#define SPI_OUT_EOF_INT_RAW (BIT(7))
#define SPI_OUT_EOF_INT_RAW_S 7
#define SPI_OUT_DONE_INT_RAW (BIT(6))
#define SPI_OUT_DONE_INT_RAW_S 6
#define SPI_IN_SUC_EOF_INT_RAW (BIT(5))
#define SPI_IN_SUC_EOF_INT_RAW_S 5
#define SPI_IN_ERR_EOF_INT_RAW (BIT(4))
#define SPI_IN_ERR_EOF_INT_RAW_S 4
#define SPI_IN_DONE_INT_RAW (BIT(3))
#define SPI_IN_DONE_INT_RAW_S 3
#define SPI_INLINK_DSCR_ERROR_INT_RAW (BIT(2))
#define SPI_INLINK_DSCR_ERROR_INT_RAW_S 2
#define SPI_OUTLINK_DSCR_ERROR_INT_RAW (BIT(1))
#define SPI_OUTLINK_DSCR_ERROR_INT_RAW_S 1
#define SPI_INLINK_DSCR_EMPTY_INT_RAW (BIT(0))
#define SPI_INLINK_DSCR_EMPTY_INT_RAW_S 0

#define SPI_DMA_INT_ST_REG( i ) (REG_SPI_BASE( i ) + 0x06C)
#define SPI_OUT_TOTAL_EOF_INT_ST (BIT(8))
#define SPI_OUT_TOTAL_EOF_INT_ST_S 8
#define SPI_OUT_EOF_INT_ST (BIT(7))
#define SPI_OUT_EOF_INT_ST_S 7
#define SPI_OUT_DONE_INT_ST (BIT(6))
#define SPI_OUT_DONE_INT_ST_S 6
#define SPI_IN_SUC_EOF_INT_ST (BIT(5))
#define SPI_IN_SUC_EOF_INT_ST_S 5
#define SPI_IN_ERR_EOF_INT_ST (BIT(4))
#define SPI_IN_ERR_EOF_INT_ST_S 4
#define SPI_IN_DONE_INT_ST (BIT(3))
#define SPI_IN_DONE_INT_ST_S 3
#define SPI_INLINK_DSCR_ERROR_INT_ST (BIT(2))
#define SPI_INLINK_DSCR_ERROR_INT_ST_S 2
#define SPI_OUTLINK_DSCR_ERROR_INT_ST (BIT(1))
#define SPI_OUTLINK_DSCR_ERROR_INT_ST_S 1
#define SPI_INLINK_DSCR_EMPTY_INT_ST (BIT(0))
#define SPI_INLINK_DSCR_EMPTY_INT_ST_S 0

#define SPI_DMA_INT_CLR_REG( i ) (REG_SPI_BASE( i ) + 0x070)
#define SPI_OUT_TOTAL_EOF_INT_CLR (BIT(8))
#define SPI_OUT_TOTAL_EOF_INT_CLR_S 8
#define SPI_OUT_EOF_INT_CLR (BIT(7))
#define SPI_OUT_EOF_INT_CLR_S 7
#define SPI_OUT_DONE_INT_CLR (BIT(6))
#define SPI_OUT_DONE_INT_CLR_S 6
#define SPI_IN_SUC_EOF_INT_CLR (BIT(5))
#define SPI_IN_SUC_EOF_INT_CLR_S 5
#define SPI_IN_ERR_EOF_INT_CLR (BIT(4))
#define SPI_IN_ERR_EOF_INT_CLR_S 4
#define SPI_IN_DONE_INT_CLR (BIT(3))
#define SPI_IN_DONE_INT_CLR_S 3
#define SPI_INLINK_DSCR_ERROR_INT_CLR (BIT(2))
#define SPI_INLINK_DSCR_ERROR_INT_CLR_S 2
#define SPI_OUTLINK_DSCR_ERROR_INT_CLR (BIT(1))
#define SPI_OUTLINK_DSCR_ERROR_INT_CLR_S 1
#define SPI_INLINK_DSCR_EMPTY_INT_CLR (BIT(0))
#define SPI_INLINK_DSCR_EMPTY_INT_CLR_S 0

#define SPI_IN_ERR_EOF_DES_ADDR_REG( i ) (REG_SPI_BASE( i ) + 0x074)
#define SPI_DMA_IN_ERR_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_DMA_IN_ERR_EOF_DES_ADDR_S 0

#define SPI_IN_SUC_EOF_DES_ADDR_REG( i ) (REG_SPI_BASE( i ) + 0x078)
#define SPI_DMA_IN_SUC_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_DMA_IN_SUC_EOF_DES_ADDR_S 0

#define SPI_INLINK_DSCR_REG( i ) (REG_SPI_BASE( i ) + 0x07C)
#define SPI_DMA_INLINK_DSCR 0xFFFFFFFF
#define SPI_DMA_INLINK_DSCR_S 0

#define SPI_INLINK_DSCR_BF0_REG( i ) (REG_SPI_BASE( i ) + 0x080)
#define SPI_DMA_INLINK_DSCR_BF0 0xFFFFFFFF
#define SPI_DMA_INLINK_DSCR_BF0_S 0

#define SPI_INLINK_DSCR_BF1_REG( i ) (REG_SPI_BASE( i ) + 0x084)
#define SPI_DMA_INLINK_DSCR_BF1 0xFFFFFFFF
#define SPI_DMA_INLINK_DSCR_BF1_S 0

#define SPI_OUT_EOF_BFR_DES_ADDR_REG( i ) (REG_SPI_BASE( i ) + 0x088)
#define SPI_DMA_OUT_EOF_BFR_DES_ADDR 0xFFFFFFFF
#define SPI_DMA_OUT_EOF_BFR_DES_ADDR_S 0

#define SPI_OUT_EOF_DES_ADDR_REG( i ) (REG_SPI_BASE( i ) + 0x08C)
#define SPI_DMA_OUT_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_DMA_OUT_EOF_DES_ADDR_S 0

#define SPI_OUTLINK_DSCR_REG( i ) (REG_SPI_BASE( i ) + 0x090)
#define SPI_DMA_OUTLINK_DSCR 0xFFFFFFFF
#define SPI_DMA_OUTLINK_DSCR_S 0

#define SPI_OUTLINK_DSCR_BF0_REG( i ) (REG_SPI_BASE( i ) + 0x094)
#define SPI_DMA_OUTLINK_DSCR_BF0 0xFFFFFFFF
#define SPI_DMA_OUTLINK_DSCR_BF0_S 0

#define SPI_OUTLINK_DSCR_BF1_REG( i ) (REG_SPI_BASE( i ) + 0x098)
#define SPI_DMA_OUTLINK_DSCR_BF1 0xFFFFFFFF
#define SPI_DMA_OUTLINK_DSCR_BF1_S 0

#define SPI_DMA_OUTSTATUS_REG( i ) (REG_SPI_BASE( i ) + 0x09C)
#define SPI_DMA_OUTFIFO_EMPTY (BIT(31))
#define SPI_DMA_OUTFIFO_EMPTY_S 31
#define SPI_DMA_OUTFIFO_FULL (BIT(30))
#define SPI_DMA_OUTFIFO_FULL_S 30
#define SPI_DMA_OUTFIFO_CNT 0x0000007F
#define SPI_DMA_OUTFIFO_CNT_S 23
#define SPI_DMA_OUT_STATE 0x00000007
#define SPI_DMA_OUT_STATE_S 20
#define SPI_DMA_OUTDSCR_STATE 0x00000003
#define SPI_DMA_OUTDSCR_STATE_S 18
#define SPI_DMA_OUTDSCR_ADDR 0x0003FFFF
#define SPI_DMA_OUTDSCR_ADDR_S 0

#define SPI_DMA_INSTATUS_REG( i ) (REG_SPI_BASE( i ) + 0x0A0)
#define SPI_DMA_INFIFO_EMPTY (BIT(31))
#define SPI_DMA_INFIFO_EMPTY_S 31
#define SPI_DMA_INFIFO_FULL (BIT(30))
#define SPI_DMA_INFIFO_FULL_S 30
#define SPI_DMA_INFIFO_CNT 0x0000007F
#define SPI_DMA_INFIFO_CNT_S 23
#define SPI_DMA_IN_STATE 0x00000007
#define SPI_DMA_IN_STATE_S 20
#define SPI_DMA_INDSCR_STATE 0x00000003
#define SPI_DMA_INDSCR_STATE_S 18
#define SPI_DMA_INDSCR_ADDR 0x0003FFFF
#define SPI_DMA_INDSCR_ADDR_S 0

#define SPI_W0_REG( i ) (REG_SPI_BASE( i ) + 0x0A4)
#define SPI_BUF0 0xFFFFFFFF
#define SPI_BUF0_S 0

#define SPI_W1_REG( i ) (REG_SPI_BASE( i ) + 0x0A8)
#define SPI_BUF1 0xFFFFFFFF
#define SPI_BUF1_S 0

#define SPI_W2_REG( i ) (REG_SPI_BASE( i ) + 0x0AC)
#define SPI_BUF2 0xFFFFFFFF
#define SPI_BUF2_S 0

#define SPI_W3_REG( i ) (REG_SPI_BASE( i ) + 0x0B0)
#define SPI_BUF3 0xFFFFFFFF
#define SPI_BUF3_S 0

#define SPI_W4_REG( i ) (REG_SPI_BASE( i ) + 0x0B4)
#define SPI_BUF4 0xFFFFFFFF
#define SPI_BUF4_S 0

#define SPI_W5_REG( i ) (REG_SPI_BASE( i ) + 0x0B8)
#define SPI_BUF5 0xFFFFFFFF
#define SPI_BUF5_S 0

#define SPI_W6_REG( i ) (REG_SPI_BASE( i ) + 0x0BC)
#define SPI_BUF6 0xFFFFFFFF
#define SPI_BUF6_S 0

#define SPI_W7_REG( i ) (REG_SPI_BASE( i ) + 0x0C0)
#define SPI_BUF7 0xFFFFFFFF
#define SPI_BUF7_S 0

#define SPI_W8_REG( i ) (REG_SPI_BASE( i ) + 0x0C4)
#define SPI_BUF8 0xFFFFFFFF
#define SPI_BUF8_S 0

#define SPI_W9_REG( i ) (REG_SPI_BASE( i ) + 0x0C8)
#define SPI_BUF9 0xFFFFFFFF
#define SPI_BUF9_S 0

#define SPI_W10_REG( i ) (REG_SPI_BASE( i ) + 0x0CC)
#define SPI_BUF10 0xFFFFFFFF
#define SPI_BUF10_S 0

#define SPI_W11_REG( i ) (REG_SPI_BASE( i ) + 0x0D0)
#define SPI_BUF11 0xFFFFFFFF
#define SPI_BUF11_S 0

#define SPI_W12_REG( i ) (REG_SPI_BASE( i ) + 0x0D4)
#define SPI_BUF12 0xFFFFFFFF
#define SPI_BUF12_S 0

#define SPI_W13_REG( i ) (REG_SPI_BASE( i ) + 0x0D8)
#define SPI_BUF13 0xFFFFFFFF
#define SPI_BUF13_S 0

#define SPI_W14_REG( i ) (REG_SPI_BASE( i ) + 0x0DC)
#define SPI_BUF14 0xFFFFFFFF
#define SPI_BUF14_S 0

#define SPI_W15_REG( i ) (REG_SPI_BASE( i ) + 0x0E0)
#define SPI_BUF15 0xFFFFFFFF
#define SPI_BUF15_S 0

#define SPI_W16_REG( i ) (REG_SPI_BASE( i ) + 0x0E4)
#define SPI_BUF16 0xFFFFFFFF
#define SPI_BUF16_S 0

#define SPI_W17_REG( i ) (REG_SPI_BASE( i ) + 0x0E8)
#define SPI_BUF17 0xFFFFFFFF
#define SPI_BUF17_S 0

#define SPI_DIN_MODE_REG( i ) (REG_SPI_BASE( i ) + 0x0EC)
#define SPI_TIMING_CLK_ENA (BIT(12))
#define SPI_TIMING_CLK_ENA_S 12
#define SPI_DIN3_MODE 0x00000007
#define SPI_DIN3_MODE_S 9
#define SPI_DIN2_MODE 0x00000007
#define SPI_DIN2_MODE_S 6
#define SPI_DIN1_MODE 0x00000007
#define SPI_DIN1_MODE_S 3
#define SPI_DIN0_MODE 0x00000007
#define SPI_DIN0_MODE_S 0

#define SPI_DIN_NUM_REG( i ) (REG_SPI_BASE( i ) + 0x0F0)
#define SPI_DIN3_NUM 0x00000003
#define SPI_DIN3_NUM_S 6
#define SPI_DIN2_NUM 0x00000003
#define SPI_DIN2_NUM_S 4
#define SPI_DIN1_NUM 0x00000003
#define SPI_DIN1_NUM_S 2
#define SPI_DIN0_NUM 0x00000003
#define SPI_DIN0_NUM_S 0

#define SPI_DOUT_MODE_REG( i ) (REG_SPI_BASE( i ) + 0x0F4)
#define SPI_DOUT4_MODE 0x00000007
#define SPI_DOUT4_MODE_S 12
#define SPI_DOUT3_MODE 0x00000007
#define SPI_DOUT3_MODE_S 9
#define SPI_DOUT2_MODE 0x00000007
#define SPI_DOUT2_MODE_S 6
#define SPI_DOUT1_MODE 0x00000007
#define SPI_DOUT1_MODE_S 3
#define SPI_DOUT0_MODE 0x00000007
#define SPI_DOUT0_MODE_S 0

#define SPI_DOUT_NUM_REG( i ) (REG_SPI_BASE( i ) + 0x0F8)
#define SPI_DOUT4_NUM 0x00000003
#define SPI_DOUT4_NUM_S 8
#define SPI_DOUT3_NUM 0x00000003
#define SPI_DOUT3_NUM_S 6
#define SPI_DOUT2_NUM 0x00000003
#define SPI_DOUT2_NUM_S 4
#define SPI_DOUT1_NUM 0x00000003
#define SPI_DOUT1_NUM_S 2
#define SPI_DOUT0_NUM 0x00000003
#define SPI_DOUT0_NUM_S 0

#define SPI_REG_DATE_REG( i ) (REG_SPI_BASE( i ) + 0x3FC)
#define SPI_DATE 0x0FFFFFFF
#define SPI_DATE_S 0
#define SPI_DATE_VERSION 0x1812110
#endif // SPI_REGISTER_H_INCLUDED
