 
#ifndef SPI_MEM_REGISTER_H_INCLUDED
#define SPI_MEM_REGISTER_H_INCLUDED

#define SPI_MEM_CMD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x000)
#define SPI_MEM_FLASH_READ (BIT(31))
#define SPI_MEM_FLASH_READ_S 31
#define SPI_MEM_FLASH_WREN (BIT(30))
#define SPI_MEM_FLASH_WREN_S 30
#define SPI_MEM_FLASH_WRDI (BIT(29))
#define SPI_MEM_FLASH_WRDI_S 29
#define SPI_MEM_FLASH_RDID (BIT(28))
#define SPI_MEM_FLASH_RDID_S 28
#define SPI_MEM_FLASH_RDSR (BIT(27))
#define SPI_MEM_FLASH_RDSR_S 27
#define SPI_MEM_FLASH_WRSR (BIT(26))
#define SPI_MEM_FLASH_WRSR_S 26
#define SPI_MEM_FLASH_PP (BIT(25))
#define SPI_MEM_FLASH_PP_S 25
#define SPI_MEM_FLASH_SE (BIT(24))
#define SPI_MEM_FLASH_SE_S 24
#define SPI_MEM_FLASH_BE (BIT(23))
#define SPI_MEM_FLASH_BE_S 23
#define SPI_MEM_FLASH_CE (BIT(22))
#define SPI_MEM_FLASH_CE_S 22
#define SPI_MEM_FLASH_DP (BIT(21))
#define SPI_MEM_FLASH_DP_S 21
#define SPI_MEM_FLASH_RES (BIT(20))
#define SPI_MEM_FLASH_RES_S 20
#define SPI_MEM_FLASH_HPM (BIT(19))
#define SPI_MEM_FLASH_HPM_S 19
#define SPI_MEM_USR (BIT(18))
#define SPI_MEM_USR_S 18
#define SPI_MEM_FLASH_PE (BIT(17))
#define SPI_MEM_FLASH_PE_S 17

#define SPI_MEM_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x004)
#define SPI_MEM_USR_ADDR_VALUE 0xFFFFFFFF
#define SPI_MEM_USR_ADDR_VALUE_S 0

#define SPI_MEM_CTRL_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x008)
#define SPI_MEM_FREAD_QIO (BIT(24))
#define SPI_MEM_FREAD_QIO_S 24
#define SPI_MEM_FREAD_DIO (BIT(23))
#define SPI_MEM_FREAD_DIO_S 23
#define SPI_MEM_WRSR_2B (BIT(22))
#define SPI_MEM_WRSR_2B_S 22
#define SPI_MEM_WP_REG (BIT(21))
#define SPI_MEM_WP_REG_S 21
#define SPI_MEM_FREAD_QUAD (BIT(20))
#define SPI_MEM_FREAD_QUAD_S 20
#define SPI_MEM_D_POL (BIT(19))
#define SPI_MEM_D_POL_S 19
#define SPI_MEM_Q_POL (BIT(18))
#define SPI_MEM_Q_POL_S 18
#define SPI_MEM_RESANDRES (BIT(15))
#define SPI_MEM_RESANDRES_S 15
#define SPI_MEM_FREAD_DUAL (BIT(14))
#define SPI_MEM_FREAD_DUAL_S 14
#define SPI_MEM_FASTRD_MODE (BIT(13))
#define SPI_MEM_FASTRD_MODE_S 13
#define SPI_MEM_TX_CRC_EN (BIT(11))
#define SPI_MEM_TX_CRC_EN_S 11
#define SPI_MEM_FCS_CRC_EN (BIT(10))
#define SPI_MEM_FCS_CRC_EN_S 10
#define SPI_MEM_FCMD_QUAD (BIT(8))
#define SPI_MEM_FCMD_QUAD_S 8
#define SPI_MEM_FCMD_DUAL (BIT(7))
#define SPI_MEM_FCMD_DUAL_S 7
#define SPI_MEM_DUMMY_OUT (BIT(3))
#define SPI_MEM_DUMMY_OUT_S 3

#define SPI_MEM_CTRL1_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x00C)
#define SPI_MEM_CS_DLY_EDGE (BIT(31))
#define SPI_MEM_CS_DLY_EDGE_S 31
#define SPI_MEM_CS_DLY_MODE 0x00000007
#define SPI_MEM_CS_DLY_MODE_S 28
#define SPI_MEM_CS_DLY_NUM 0x00000003
#define SPI_MEM_CS_DLY_NUM_S 26
#define SPI_MEM_CS_HOLD_DLY 0x00000FFF
#define SPI_MEM_CS_HOLD_DLY_S 14
#define SPI_MEM_CS_HOLD_DLY_RES 0x00000FFF
#define SPI_MEM_CS_HOLD_DLY_RES_S 2
#define SPI_MEM_CLK_MODE 0x00000003
#define SPI_MEM_CLK_MODE_S 0

#define SPI_MEM_CTRL2_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x010)
#define SPI_MEM_SYNC_RESET (BIT(31))
#define SPI_MEM_SYNC_RESET_S 31
#define SPI_MEM_CS_HOLD_TIME 0x00001FFF
#define SPI_MEM_CS_HOLD_TIME_S 13
#define SPI_MEM_CS_SETUP_TIME 0x00001FFF
#define SPI_MEM_CS_SETUP_TIME_S 0

#define SPI_MEM_CLOCK_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x014)
#define SPI_MEM_CLK_EQU_SYSCLK (BIT(31))
#define SPI_MEM_CLK_EQU_SYSCLK_S 31
#define SPI_MEM_CLKCNT_N 0x000000FF
#define SPI_MEM_CLKCNT_N_S 16
#define SPI_MEM_CLKCNT_H 0x000000FF
#define SPI_MEM_CLKCNT_H_S 8
#define SPI_MEM_CLKCNT_L 0x000000FF
#define SPI_MEM_CLKCNT_L_S 0

#define SPI_MEM_USER_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x018)
#define SPI_MEM_USR_COMMAND (BIT(31))
#define SPI_MEM_USR_COMMAND_S 31
#define SPI_MEM_USR_ADDR (BIT(30))
#define SPI_MEM_USR_ADDR_S 30
#define SPI_MEM_USR_DUMMY (BIT(29))
#define SPI_MEM_USR_DUMMY_S 29
#define SPI_MEM_USR_MISO (BIT(28))
#define SPI_MEM_USR_MISO_S 28
#define SPI_MEM_USR_MOSI (BIT(27))
#define SPI_MEM_USR_MOSI_S 27
#define SPI_MEM_USR_DUMMY_IDLE (BIT(26))
#define SPI_MEM_USR_DUMMY_IDLE_S 26
#define SPI_MEM_USR_MOSI_HIGHPART (BIT(25))
#define SPI_MEM_USR_MOSI_HIGHPART_S 25
#define SPI_MEM_USR_MISO_HIGHPART (BIT(24))
#define SPI_MEM_USR_MISO_HIGHPART_S 24
#define SPI_MEM_FWRITE_QIO (BIT(15))
#define SPI_MEM_FWRITE_QIO_S 15
#define SPI_MEM_FWRITE_DIO (BIT(14))
#define SPI_MEM_FWRITE_DIO_S 14
#define SPI_MEM_FWRITE_QUAD (BIT(13))
#define SPI_MEM_FWRITE_QUAD_S 13
#define SPI_MEM_FWRITE_DUAL (BIT(12))
#define SPI_MEM_FWRITE_DUAL_S 12
#define SPI_MEM_CK_OUT_EDGE (BIT(9))
#define SPI_MEM_CK_OUT_EDGE_S 9
#define SPI_MEM_CS_SETUP (BIT(7))
#define SPI_MEM_CS_SETUP_S 7
#define SPI_MEM_CS_HOLD (BIT(6))
#define SPI_MEM_CS_HOLD_S 6

#define SPI_MEM_USER1_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x01C)
#define SPI_MEM_USR_ADDR_BITLEN 0x0000003F
#define SPI_MEM_USR_ADDR_BITLEN_S 26
#define SPI_MEM_USR_DUMMY_CYCLELEN 0x000000FF
#define SPI_MEM_USR_DUMMY_CYCLELEN_S 0

#define SPI_MEM_USER2_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x020)
#define SPI_MEM_USR_COMMAND_BITLEN 0x0000000F
#define SPI_MEM_USR_COMMAND_BITLEN_S 28
#define SPI_MEM_USR_COMMAND_VALUE 0x0000FFFF
#define SPI_MEM_USR_COMMAND_VALUE_S 0

#define SPI_MEM_MOSI_DLEN_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x024)
#define SPI_MEM_USR_MOSI_DBITLEN 0x000007FF
#define SPI_MEM_USR_MOSI_DBITLEN_S 0

#define SPI_MEM_MISO_DLEN_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x028)
#define SPI_MEM_USR_MISO_DBITLEN 0x000007FF
#define SPI_MEM_USR_MISO_DBITLEN_S 0

#define SPI_MEM_RD_STATUS_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x02C)
#define SPI_MEM_WB_MODE 0x000000FF
#define SPI_MEM_WB_MODE_S 16
#define SPI_MEM_STATUS 0x0000FFFF
#define SPI_MEM_STATUS_S 0

#define SPI_MEM_EXT_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x030)
#define SPI_MEM_EXT_ADDR 0xFFFFFFFF
#define SPI_MEM_EXT_ADDR_S 0

#define SPI_MEM_MISC_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x034)
#define SPI_MEM_AUTO_PER (BIT(11))
#define SPI_MEM_AUTO_PER_S 11
#define SPI_MEM_CS_KEEP_ACTIVE (BIT(10))
#define SPI_MEM_CS_KEEP_ACTIVE_S 10
#define SPI_MEM_CK_IDLE_EDGE (BIT(9))
#define SPI_MEM_CK_IDLE_EDGE_S 9
#define SPI_MEM_SSUB_PIN (BIT(8))
#define SPI_MEM_SSUB_PIN_S 8
#define SPI_MEM_FSUB_PIN (BIT(7))
#define SPI_MEM_FSUB_PIN_S 7
#define SPI_MEM_CS_POL 0x00000003
#define SPI_MEM_CS_POL_S 5
#define SPI_MEM_TRANS_END_INT_ENA (BIT(4))
#define SPI_MEM_TRANS_END_INT_ENA_S 4
#define SPI_MEM_TRANS_END (BIT(3))
#define SPI_MEM_TRANS_END_S 3
#define SPI_MEM_CS1_DIS (BIT(1))
#define SPI_MEM_CS1_DIS_S 1
#define SPI_MEM_CS0_DIS (BIT(0))
#define SPI_MEM_CS0_DIS_S 0

#define SPI_MEM_TX_CRC_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x038)
#define SPI_MEM_TX_CRC_DATA 0xFFFFFFFF
#define SPI_MEM_TX_CRC_DATA_S 0

#define SPI_MEM_CACHE_FCTRL_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x03C)
#define SPI_MEM_FADDR_QUAD (BIT(8))
#define SPI_MEM_FADDR_QUAD_S 8
#define SPI_MEM_FDOUT_QUAD (BIT(7))
#define SPI_MEM_FDOUT_QUAD_S 7
#define SPI_MEM_FDIN_QUAD (BIT(6))
#define SPI_MEM_FDIN_QUAD_S 6
#define SPI_MEM_FADDR_DUAL (BIT(5))
#define SPI_MEM_FADDR_DUAL_S 5
#define SPI_MEM_FDOUT_DUAL (BIT(4))
#define SPI_MEM_FDOUT_DUAL_S 4
#define SPI_MEM_FDIN_DUAL (BIT(3))
#define SPI_MEM_FDIN_DUAL_S 3
#define SPI_MEM_CACHE_FLASH_USR_CMD (BIT(2))
#define SPI_MEM_CACHE_FLASH_USR_CMD_S 2
#define SPI_MEM_CACHE_USR_CMD_4BYTE (BIT(1))
#define SPI_MEM_CACHE_USR_CMD_4BYTE_S 1
#define SPI_MEM_CACHE_REQ_EN (BIT(0))
#define SPI_MEM_CACHE_REQ_EN_S 0

#define SPI_MEM_CACHE_SCTRL_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x040)
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN 0x000000FF
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN_S 22
#define SPI_MEM_CACHE_SRAM_USR_WCMD (BIT(20))
#define SPI_MEM_CACHE_SRAM_USR_WCMD_S 20
#define SPI_MEM_SRAM_ADDR_BITLEN 0x0000003F
#define SPI_MEM_SRAM_ADDR_BITLEN_S 14
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN 0x000000FF
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN_S 6
#define SPI_MEM_CACHE_SRAM_USR_RCMD (BIT(5))
#define SPI_MEM_CACHE_SRAM_USR_RCMD_S 5
#define SPI_MEM_USR_RD_SRAM_DUMMY (BIT(4))
#define SPI_MEM_USR_RD_SRAM_DUMMY_S 4
#define SPI_MEM_USR_WR_SRAM_DUMMY (BIT(3))
#define SPI_MEM_USR_WR_SRAM_DUMMY_S 3
#define SPI_MEM_USR_SRAM_QIO (BIT(2))
#define SPI_MEM_USR_SRAM_QIO_S 2
#define SPI_MEM_USR_SRAM_DIO (BIT(1))
#define SPI_MEM_USR_SRAM_DIO_S 1
#define SPI_MEM_CACHE_USR_SCMD_4BYTE (BIT(0))
#define SPI_MEM_CACHE_USR_SCMD_4BYTE_S 0

#define SPI_MEM_SRAM_CMD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x044)
#define SPI_MEM_SCMD_QUAD (BIT(17))
#define SPI_MEM_SCMD_QUAD_S 17
#define SPI_MEM_SADDR_QUAD (BIT(16))
#define SPI_MEM_SADDR_QUAD_S 16
#define SPI_MEM_SDOUT_QUAD (BIT(15))
#define SPI_MEM_SDOUT_QUAD_S 15
#define SPI_MEM_SDIN_QUAD (BIT(14))
#define SPI_MEM_SDIN_QUAD_S 14
#define SPI_MEM_SCMD_DUAL (BIT(13))
#define SPI_MEM_SCMD_DUAL_S 13
#define SPI_MEM_SADDR_DUAL (BIT(12))
#define SPI_MEM_SADDR_DUAL_S 12
#define SPI_MEM_SDOUT_DUAL (BIT(11))
#define SPI_MEM_SDOUT_DUAL_S 11
#define SPI_MEM_SDIN_DUAL (BIT(10))
#define SPI_MEM_SDIN_DUAL_S 10
#define SPI_MEM_SWB_MODE 0x000000FF
#define SPI_MEM_SWB_MODE_S 2
#define SPI_MEM_SCLK_MODE 0x00000003
#define SPI_MEM_SCLK_MODE_S 0

#define SPI_MEM_SRAM_DRD_CMD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x048)
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN 0x0000000F
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_S 28
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE 0x0000FFFF
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_S 0

#define SPI_MEM_SRAM_DWR_CMD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x04C)
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN 0x0000000F
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_S 28
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE 0x0000FFFF
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_S 0

#define SPI_MEM_SRAM_CLK_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x050)
#define SPI_MEM_SCLK_EQU_SYSCLK (BIT(31))
#define SPI_MEM_SCLK_EQU_SYSCLK_S 31
#define SPI_MEM_SCLKCNT_N 0x000000FF
#define SPI_MEM_SCLKCNT_N_S 16
#define SPI_MEM_SCLKCNT_H 0x000000FF
#define SPI_MEM_SCLKCNT_H_S 8
#define SPI_MEM_SCLKCNT_L 0x000000FF
#define SPI_MEM_SCLKCNT_L_S 0

#define SPI_MEM_FSM_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x054)
#define SPI_MEM_ST 0x00000007
#define SPI_MEM_ST_S 0

#define SPI_MEM_HOLD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x058)
#define SPI_MEM_HOLD_ENA 0x00000003
#define SPI_MEM_HOLD_ENA_S 0

#define SPI_MEM_DMA_CONF_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x05C)
#define SPI_MEM_DMA_CONTINUE (BIT(16))
#define SPI_MEM_DMA_CONTINUE_S 16
#define SPI_MEM_DMA_TX_STOP (BIT(15))
#define SPI_MEM_DMA_TX_STOP_S 15
#define SPI_MEM_DMA_RX_STOP (BIT(14))
#define SPI_MEM_DMA_RX_STOP_S 14
#define SPI_MEM_DMA_MEM_TRANS_ENA (BIT(13))
#define SPI_MEM_DMA_MEM_TRANS_ENA_S 13
#define SPI_MEM_OUT_DATA_BURST_EN (BIT(12))
#define SPI_MEM_OUT_DATA_BURST_EN_S 12
#define SPI_MEM_INDSCR_BURST_EN (BIT(11))
#define SPI_MEM_INDSCR_BURST_EN_S 11
#define SPI_MEM_OUTDSCR_BURST_EN (BIT(10))
#define SPI_MEM_OUTDSCR_BURST_EN_S 10
#define SPI_MEM_OUT_EOF_MODE (BIT(9))
#define SPI_MEM_OUT_EOF_MODE_S 9
#define SPI_MEM_OUT_AUTO_WRBACK (BIT(8))
#define SPI_MEM_OUT_AUTO_WRBACK_S 8
#define SPI_MEM_OUT_LOOP_TEST (BIT(7))
#define SPI_MEM_OUT_LOOP_TEST_S 7
#define SPI_MEM_IN_LOOP_TEST (BIT(6))
#define SPI_MEM_IN_LOOP_TEST_S 6
#define SPI_MEM_AHBM_RST (BIT(5))
#define SPI_MEM_AHBM_RST_S 5
#define SPI_MEM_AHBM_FIFO_RST (BIT(4))
#define SPI_MEM_AHBM_FIFO_RST_S 4
#define SPI_MEM_OUT_RST (BIT(3))
#define SPI_MEM_OUT_RST_S 3
#define SPI_MEM_IN_RST (BIT(2))
#define SPI_MEM_IN_RST_S 2
#define SPI_MEM_DMA_TX_ENA (BIT(1))
#define SPI_MEM_DMA_TX_ENA_S 1
#define SPI_MEM_DMA_RX_ENA (BIT(0))
#define SPI_MEM_DMA_RX_ENA_S 0

#define SPI_MEM_DMA_OUT_LINK_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x060)
#define SPI_MEM_OUTLINK_RESTART (BIT(30))
#define SPI_MEM_OUTLINK_RESTART_S 30
#define SPI_MEM_OUTLINK_START (BIT(29))
#define SPI_MEM_OUTLINK_START_S 29
#define SPI_MEM_OUTLINK_STOP (BIT(28))
#define SPI_MEM_OUTLINK_STOP_S 28
#define SPI_MEM_OUTLINK_ADDR 0x000FFFFF
#define SPI_MEM_OUTLINK_ADDR_S 0

#define SPI_MEM_DMA_IN_LINK_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x064)
#define SPI_MEM_INLINK_RESTART (BIT(30))
#define SPI_MEM_INLINK_RESTART_S 30
#define SPI_MEM_INLINK_START (BIT(29))
#define SPI_MEM_INLINK_START_S 29
#define SPI_MEM_INLINK_STOP (BIT(28))
#define SPI_MEM_INLINK_STOP_S 28
#define SPI_MEM_INLINK_AUTO_RET (BIT(20))
#define SPI_MEM_INLINK_AUTO_RET_S 20
#define SPI_MEM_INLINK_ADDR 0x000FFFFF
#define SPI_MEM_INLINK_ADDR_S 0

#define SPI_MEM_DMA_INT_ENA_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x068)
#define SPI_MEM_OUT_TOTAL_EOF_INT_ENA (BIT(8))
#define SPI_MEM_OUT_TOTAL_EOF_INT_ENA_S 8
#define SPI_MEM_OUT_EOF_INT_ENA (BIT(7))
#define SPI_MEM_OUT_EOF_INT_ENA_S 7
#define SPI_MEM_OUT_DONE_INT_ENA (BIT(6))
#define SPI_MEM_OUT_DONE_INT_ENA_S 6
#define SPI_MEM_IN_SUC_EOF_INT_ENA (BIT(5))
#define SPI_MEM_IN_SUC_EOF_INT_ENA_S 5
#define SPI_MEM_IN_ERR_EOF_INT_ENA (BIT(4))
#define SPI_MEM_IN_ERR_EOF_INT_ENA_S 4
#define SPI_MEM_IN_DONE_INT_ENA (BIT(3))
#define SPI_MEM_IN_DONE_INT_ENA_S 3
#define SPI_MEM_INLINK_DSCR_ERROR_INT_ENA (BIT(2))
#define SPI_MEM_INLINK_DSCR_ERROR_INT_ENA_S 2
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_ENA (BIT(1))
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_ENA_S 1
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_ENA (BIT(0))
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_ENA_S 0

#define SPI_MEM_DMA_INT_RAW_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x06C)
#define SPI_MEM_OUT_TOTAL_EOF_INT_RAW (BIT(8))
#define SPI_MEM_OUT_TOTAL_EOF_INT_RAW_S 8
#define SPI_MEM_OUT_EOF_INT_RAW (BIT(7))
#define SPI_MEM_OUT_EOF_INT_RAW_S 7
#define SPI_MEM_OUT_DONE_INT_RAW (BIT(6))
#define SPI_MEM_OUT_DONE_INT_RAW_S 6
#define SPI_MEM_IN_SUC_EOF_INT_RAW (BIT(5))
#define SPI_MEM_IN_SUC_EOF_INT_RAW_S 5
#define SPI_MEM_IN_ERR_EOF_INT_RAW (BIT(4))
#define SPI_MEM_IN_ERR_EOF_INT_RAW_S 4
#define SPI_MEM_IN_DONE_INT_RAW (BIT(3))
#define SPI_MEM_IN_DONE_INT_RAW_S 3
#define SPI_MEM_INLINK_DSCR_ERROR_INT_RAW (BIT(2))
#define SPI_MEM_INLINK_DSCR_ERROR_INT_RAW_S 2
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_RAW (BIT(1))
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_RAW_S 1
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_RAW (BIT(0))
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_RAW_S 0

#define SPI_MEM_DMA_INT_ST_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x070)
#define SPI_MEM_OUT_TOTAL_EOF_INT_ST (BIT(8))
#define SPI_MEM_OUT_TOTAL_EOF_INT_ST_S 8
#define SPI_MEM_OUT_EOF_INT_ST (BIT(7))
#define SPI_MEM_OUT_EOF_INT_ST_S 7
#define SPI_MEM_OUT_DONE_INT_ST (BIT(6))
#define SPI_MEM_OUT_DONE_INT_ST_S 6
#define SPI_MEM_IN_SUC_EOF_INT_ST (BIT(5))
#define SPI_MEM_IN_SUC_EOF_INT_ST_S 5
#define SPI_MEM_IN_ERR_EOF_INT_ST (BIT(4))
#define SPI_MEM_IN_ERR_EOF_INT_ST_S 4
#define SPI_MEM_IN_DONE_INT_ST (BIT(3))
#define SPI_MEM_IN_DONE_INT_ST_S 3
#define SPI_MEM_INLINK_DSCR_ERROR_INT_ST (BIT(2))
#define SPI_MEM_INLINK_DSCR_ERROR_INT_ST_S 2
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_ST (BIT(1))
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_ST_S 1
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_ST (BIT(0))
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_ST_S 0

#define SPI_MEM_DMA_INT_CLR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x074)
#define SPI_MEM_OUT_TOTAL_EOF_INT_CLR (BIT(8))
#define SPI_MEM_OUT_TOTAL_EOF_INT_CLR_S 8
#define SPI_MEM_OUT_EOF_INT_CLR (BIT(7))
#define SPI_MEM_OUT_EOF_INT_CLR_S 7
#define SPI_MEM_OUT_DONE_INT_CLR (BIT(6))
#define SPI_MEM_OUT_DONE_INT_CLR_S 6
#define SPI_MEM_IN_SUC_EOF_INT_CLR (BIT(5))
#define SPI_MEM_IN_SUC_EOF_INT_CLR_S 5
#define SPI_MEM_IN_ERR_EOF_INT_CLR (BIT(4))
#define SPI_MEM_IN_ERR_EOF_INT_CLR_S 4
#define SPI_MEM_IN_DONE_INT_CLR (BIT(3))
#define SPI_MEM_IN_DONE_INT_CLR_S 3
#define SPI_MEM_INLINK_DSCR_ERROR_INT_CLR (BIT(2))
#define SPI_MEM_INLINK_DSCR_ERROR_INT_CLR_S 2
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_CLR (BIT(1))
#define SPI_MEM_OUTLINK_DSCR_ERROR_INT_CLR_S 1
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_CLR (BIT(0))
#define SPI_MEM_INLINK_DSCR_EMPTY_INT_CLR_S 0

#define SPI_MEM_IN_ERR_EOF_DES_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x078)
#define SPI_MEM_DMA_IN_ERR_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_MEM_DMA_IN_ERR_EOF_DES_ADDR_S 0

#define SPI_MEM_IN_SUC_EOF_DES_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x07C)
#define SPI_MEM_DMA_IN_SUC_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_MEM_DMA_IN_SUC_EOF_DES_ADDR_S 0

#define SPI_MEM_INLINK_DSCR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x080)
#define SPI_MEM_DMA_INLINK_DSCR 0xFFFFFFFF
#define SPI_MEM_DMA_INLINK_DSCR_S 0

#define SPI_MEM_INLINK_DSCR_BF0_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x084)
#define SPI_MEM_DMA_INLINK_DSCR_BF0 0xFFFFFFFF
#define SPI_MEM_DMA_INLINK_DSCR_BF0_S 0

#define SPI_MEM_INLINK_DSCR_BF1_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x088)
#define SPI_MEM_DMA_INLINK_DSCR_BF1 0xFFFFFFFF
#define SPI_MEM_DMA_INLINK_DSCR_BF1_S 0

#define SPI_MEM_OUT_EOF_BFR_DES_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x08C)
#define SPI_MEM_DMA_OUT_EOF_BFR_DES_ADDR 0xFFFFFFFF
#define SPI_MEM_DMA_OUT_EOF_BFR_DES_ADDR_S 0

#define SPI_MEM_OUT_EOF_DES_ADDR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x090)
#define SPI_MEM_DMA_OUT_EOF_DES_ADDR 0xFFFFFFFF
#define SPI_MEM_DMA_OUT_EOF_DES_ADDR_S 0

#define SPI_MEM_OUTLINK_DSCR_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x094)
#define SPI_MEM_DMA_OUTLINK_DSCR 0xFFFFFFFF
#define SPI_MEM_DMA_OUTLINK_DSCR_S 0

#define SPI_MEM_OUTLINK_DSCR_BF0_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x098)
#define SPI_MEM_DMA_OUTLINK_DSCR_BF0 0xFFFFFFFF
#define SPI_MEM_DMA_OUTLINK_DSCR_BF0_S 0

#define SPI_MEM_OUTLINK_DSCR_BF1_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x09C)
#define SPI_MEM_DMA_OUTLINK_DSCR_BF1 0xFFFFFFFF
#define SPI_MEM_DMA_OUTLINK_DSCR_BF1_S 0

#define SPI_MEM_DMA_OUTSTATUS_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0A0)
#define SPI_MEM_DMA_OUTFIFO_EMPTY (BIT(31))
#define SPI_MEM_DMA_OUTFIFO_EMPTY_S 31
#define SPI_MEM_DMA_OUTFIFO_FULL (BIT(30))
#define SPI_MEM_DMA_OUTFIFO_FULL_S 30
#define SPI_MEM_DMA_OUTFIFO_CNT 0x0000007F
#define SPI_MEM_DMA_OUTFIFO_CNT_S 23
#define SPI_MEM_DMA_OUT_STATE 0x00000007
#define SPI_MEM_DMA_OUT_STATE_S 20
#define SPI_MEM_DMA_OUTDSCR_STATE 0x00000003
#define SPI_MEM_DMA_OUTDSCR_STATE_S 18
#define SPI_MEM_DMA_OUTDSCR_ADDR 0x0003FFFF
#define SPI_MEM_DMA_OUTDSCR_ADDR_S 0

#define SPI_MEM_DMA_INSTATUS_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0A4)
#define SPI_MEM_DMA_INFIFO_EMPTY (BIT(31))
#define SPI_MEM_DMA_INFIFO_EMPTY_S 31
#define SPI_MEM_DMA_INFIFO_FULL (BIT(30))
#define SPI_MEM_DMA_INFIFO_FULL_S 30
#define SPI_MEM_DMA_INFIFO_CNT 0x0000007F
#define SPI_MEM_DMA_INFIFO_CNT_S 23
#define SPI_MEM_DMA_IN_STATE 0x00000007
#define SPI_MEM_DMA_IN_STATE_S 20
#define SPI_MEM_DMA_INDSCR_STATE 0x00000003
#define SPI_MEM_DMA_INDSCR_STATE_S 18
#define SPI_MEM_DMA_INDSCR_ADDR 0x0003FFFF
#define SPI_MEM_DMA_INDSCR_ADDR_S 0

#define SPI_MEM_W0_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0A8)
#define SPI_MEM_BUF0 0xFFFFFFFF
#define SPI_MEM_BUF0_S 0

#define SPI_MEM_W1_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0AC)
#define SPI_MEM_BUF1 0xFFFFFFFF
#define SPI_MEM_BUF1_S 0

#define SPI_MEM_W2_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0B0)
#define SPI_MEM_BUF2 0xFFFFFFFF
#define SPI_MEM_BUF2_S 0

#define SPI_MEM_W3_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0B4)
#define SPI_MEM_BUF3 0xFFFFFFFF
#define SPI_MEM_BUF3_S 0

#define SPI_MEM_W4_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0B8)
#define SPI_MEM_BUF4 0xFFFFFFFF
#define SPI_MEM_BUF4_S 0

#define SPI_MEM_W5_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0BC)
#define SPI_MEM_BUF5 0xFFFFFFFF
#define SPI_MEM_BUF5_S 0

#define SPI_MEM_W6_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0C0)
#define SPI_MEM_BUF6 0xFFFFFFFF
#define SPI_MEM_BUF6_S 0

#define SPI_MEM_W7_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0C4)
#define SPI_MEM_BUF7 0xFFFFFFFF
#define SPI_MEM_BUF7_S 0

#define SPI_MEM_W8_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0C8)
#define SPI_MEM_BUF8 0xFFFFFFFF
#define SPI_MEM_BUF8_S 0

#define SPI_MEM_W9_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0CC)
#define SPI_MEM_BUF9 0xFFFFFFFF
#define SPI_MEM_BUF9_S 0

#define SPI_MEM_W10_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0D0)
#define SPI_MEM_BUF10 0xFFFFFFFF
#define SPI_MEM_BUF10_S 0

#define SPI_MEM_W11_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0D4)
#define SPI_MEM_BUF11 0xFFFFFFFF
#define SPI_MEM_BUF11_S 0

#define SPI_MEM_W12_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0D8)
#define SPI_MEM_BUF12 0xFFFFFFFF
#define SPI_MEM_BUF12_S 0

#define SPI_MEM_W13_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0DC)
#define SPI_MEM_BUF13 0xFFFFFFFF
#define SPI_MEM_BUF13_S 0

#define SPI_MEM_W14_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0E0)
#define SPI_MEM_BUF14 0xFFFFFFFF
#define SPI_MEM_BUF14_S 0

#define SPI_MEM_W15_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0E4)
#define SPI_MEM_BUF15 0xFFFFFFFF
#define SPI_MEM_BUF15_S 0

#define SPI_MEM_FLASH_WAITI_CTRL_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0E8)
#define SPI_MEM_WAITI_DUMMY_CYCLELEN 0x000000FF
#define SPI_MEM_WAITI_DUMMY_CYCLELEN_S 10
#define SPI_MEM_WAITI_CMD 0x000000FF
#define SPI_MEM_WAITI_CMD_S 2
#define SPI_MEM_WAITI_DUMMY (BIT(1))
#define SPI_MEM_WAITI_DUMMY_S 1
#define SPI_MEM_WAITI_EN (BIT(0))
#define SPI_MEM_WAITI_EN_S 0

#define SPI_MEM_FLASH_SUS_CMD_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0EC)
#define SPI_MEM_FLASH_PES (BIT(1))
#define SPI_MEM_FLASH_PES_S 1
#define SPI_MEM_FLASH_PER (BIT(0))
#define SPI_MEM_FLASH_PER_S 0

#define SPI_MEM_FLASH_SUS_CTRL_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0F0)
#define SPI_MEM_FLASH_PES_COMMAND 0x000000FF
#define SPI_MEM_FLASH_PES_COMMAND_S 9
#define SPI_MEM_FLASH_PER_COMMAND 0x000000FF
#define SPI_MEM_FLASH_PER_COMMAND_S 1
#define SPI_MEM_FLASH_PES_EN (BIT(0))
#define SPI_MEM_FLASH_PES_EN_S 0

#define SPI_MEM_SUS_STATUS_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0F4)
#define SPI_MEM_FLASH_SUS (BIT(0))
#define SPI_MEM_FLASH_SUS_S 0

#define SPI_MEM_TIMING_CALI_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0F8)
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN 0x00000003
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN_S 2
#define SPI_MEM_TIMING_CALI (BIT(1))
#define SPI_MEM_TIMING_CALI_S 1
#define SPI_MEM_TIMING_CLK_ENA (BIT(0))
#define SPI_MEM_TIMING_CLK_ENA_S 0

#define SPI_MEM_DIN_MODE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x0FC)
#define SPI_MEM_DIN3_MODE 0x00000007
#define SPI_MEM_DIN3_MODE_S 9
#define SPI_MEM_DIN2_MODE 0x00000007
#define SPI_MEM_DIN2_MODE_S 6
#define SPI_MEM_DIN1_MODE 0x00000007
#define SPI_MEM_DIN1_MODE_S 3
#define SPI_MEM_DIN0_MODE 0x00000007
#define SPI_MEM_DIN0_MODE_S 0

#define SPI_MEM_DIN_NUM_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x100)
#define SPI_MEM_DIN3_NUM 0x00000003
#define SPI_MEM_DIN3_NUM_S 6
#define SPI_MEM_DIN2_NUM 0x00000003
#define SPI_MEM_DIN2_NUM_S 4
#define SPI_MEM_DIN1_NUM 0x00000003
#define SPI_MEM_DIN1_NUM_S 2
#define SPI_MEM_DIN0_NUM 0x00000003
#define SPI_MEM_DIN0_NUM_S 0

#define SPI_MEM_DOUT_MODE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x104)
#define SPI_MEM_DOUT3_MODE 0x00000007
#define SPI_MEM_DOUT3_MODE_S 9
#define SPI_MEM_DOUT2_MODE 0x00000007
#define SPI_MEM_DOUT2_MODE_S 6
#define SPI_MEM_DOUT1_MODE 0x00000007
#define SPI_MEM_DOUT1_MODE_S 3
#define SPI_MEM_DOUT0_MODE 0x00000007
#define SPI_MEM_DOUT0_MODE_S 0

#define SPI_MEM_DOUT_NUM_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x108)
#define SPI_MEM_DOUT3_NUM 0x00000003
#define SPI_MEM_DOUT3_NUM_S 6
#define SPI_MEM_DOUT2_NUM 0x00000003
#define SPI_MEM_DOUT2_NUM_S 4
#define SPI_MEM_DOUT1_NUM 0x00000003
#define SPI_MEM_DOUT1_NUM_S 2
#define SPI_MEM_DOUT0_NUM 0x00000003
#define SPI_MEM_DOUT0_NUM_S 0

#define SPI_MEM_SPI_SMEM_TIMING_CALI_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x10C)
#define SPI_SMEM_EXTRA_DUMMY_CYCLELEN 0x00000003
#define SPI_SMEM_EXTRA_DUMMY_CYCLELEN_S 2
#define SPI_SMEM_TIMING_CALI (BIT(1))
#define SPI_SMEM_TIMING_CALI_S 1
#define SPI_SMEM_TIMING_CLK_ENA (BIT(0))
#define SPI_SMEM_TIMING_CLK_ENA_S 0

#define SPI_MEM_SPI_SMEM_DIN_MODE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x110)
#define SPI_SMEM_DIN3_MODE 0x00000007
#define SPI_SMEM_DIN3_MODE_S 9
#define SPI_SMEM_DIN2_MODE 0x00000007
#define SPI_SMEM_DIN2_MODE_S 6
#define SPI_SMEM_DIN1_MODE 0x00000007
#define SPI_SMEM_DIN1_MODE_S 3
#define SPI_SMEM_DIN0_MODE 0x00000007
#define SPI_SMEM_DIN0_MODE_S 0

#define SPI_MEM_SPI_SMEM_DIN_NUM_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x114)
#define SPI_SMEM_DIN3_NUM 0x00000003
#define SPI_SMEM_DIN3_NUM_S 6
#define SPI_SMEM_DIN2_NUM 0x00000003
#define SPI_SMEM_DIN2_NUM_S 4
#define SPI_SMEM_DIN1_NUM 0x00000003
#define SPI_SMEM_DIN1_NUM_S 2
#define SPI_SMEM_DIN0_NUM 0x00000003
#define SPI_SMEM_DIN0_NUM_S 0

#define SPI_MEM_SPI_SMEM_DOUT_MODE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x118)
#define SPI_SMEM_DOUT3_MODE 0x00000007
#define SPI_SMEM_DOUT3_MODE_S 9
#define SPI_SMEM_DOUT2_MODE 0x00000007
#define SPI_SMEM_DOUT2_MODE_S 6
#define SPI_SMEM_DOUT1_MODE 0x00000007
#define SPI_SMEM_DOUT1_MODE_S 3
#define SPI_SMEM_DOUT0_MODE 0x00000007
#define SPI_SMEM_DOUT0_MODE_S 0

#define SPI_MEM_SPI_SMEM_DOUT_NUM_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x11C)
#define SPI_SMEM_DOUT3_NUM 0x00000003
#define SPI_SMEM_DOUT3_NUM_S 6
#define SPI_SMEM_DOUT2_NUM 0x00000003
#define SPI_SMEM_DOUT2_NUM_S 4
#define SPI_SMEM_DOUT1_NUM 0x00000003
#define SPI_SMEM_DOUT1_NUM_S 2
#define SPI_SMEM_DOUT0_NUM 0x00000003
#define SPI_SMEM_DOUT0_NUM_S 0

#define SPI_MEM_CLOCK_GATE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x120)
#define SPI_MEM_CLK_EN (BIT(0))
#define SPI_MEM_CLK_EN_S 0

#define SPI_MEM_REG_DATE_REG( i ) (REG_SPI_MEM_BASE( i ) + 0x3FC)
#define SPI_MEM_DATE 0x0FFFFFFF
#define SPI_MEM_DATE_S 0
#define SPI_MEM_DATE_VERSION 0x1810250
#endif // SPI_MEM_REGISTER_H_INCLUDED
