
#define SYSTEM_ROM_CTRL_0_REG (REG_SYSTEM_BASE + 0x000)
#define SYSTEM_ROM_FO 0x00000003
#define SYSTEM_ROM_FO_S 0

#define SYSTEM_ROM_CTRL_1_REG (REG_SYSTEM_BASE + 0x004)
#define SYSTEM_ROM_PD 0x00000003
#define SYSTEM_ROM_PD_S 0

#define SYSTEM_SRAM_CTRL_0_REG (REG_SYSTEM_BASE + 0x008)
#define SYSTEM_SRAM_FO 0x003FFFFF
#define SYSTEM_SRAM_FO_S 0

#define SYSTEM_SRAM_CTRL_1_REG (REG_SYSTEM_BASE + 0x00C)
#define SYSTEM_SRAM_PD 0x003FFFFF
#define SYSTEM_SRAM_PD_S 0

#define SYSTEM_CPU_PERI_CLK_EN_REG (REG_SYSTEM_BASE + 0x010)
#define SYSTEM_CLK_EN_DEDICATED_GPIO (BIT(7))
#define SYSTEM_CLK_EN_DEDICATED_GPIO_S 7
#define SYSTEM_CLK_EN_ASSIST_DEBUG (BIT(6))
#define SYSTEM_CLK_EN_ASSIST_DEBUG_S 6
#define SYSTEM_CLK_EN_DIGITAL_SIGNATURE (BIT(5))
#define SYSTEM_CLK_EN_DIGITAL_SIGNATURE_S 5
#define SYSTEM_CLK_EN_HMAC (BIT(4))
#define SYSTEM_CLK_EN_HMAC_S 4
#define SYSTEM_CLK_EN_SECURE_BOOT (BIT(3))
#define SYSTEM_CLK_EN_SECURE_BOOT_S 3
#define SYSTEM_CLK_EN_RSA (BIT(2))
#define SYSTEM_CLK_EN_RSA_S 2
#define SYSTEM_CLK_EN_SHA (BIT(1))
#define SYSTEM_CLK_EN_SHA_S 1
#define SYSTEM_CLK_EN_AES (BIT(0))
#define SYSTEM_CLK_EN_AES_S 0

#define SYSTEM_CPU_PERI_RST_EN_REG (REG_SYSTEM_BASE + 0x014)
#define SYSTEM_RST_EN_DEDICATED_GPIO (BIT(7))
#define SYSTEM_RST_EN_DEDICATED_GPIO_S 7
#define SYSTEM_RST_EN_ASSIST_DEBUG (BIT(6))
#define SYSTEM_RST_EN_ASSIST_DEBUG_S 6
#define SYSTEM_RST_EN_DIGITAL_SIGNATURE (BIT(5))
#define SYSTEM_RST_EN_DIGITAL_SIGNATURE_S 5
#define SYSTEM_RST_EN_HMAC (BIT(4))
#define SYSTEM_RST_EN_HMAC_S 4
#define SYSTEM_RST_EN_SECURE_BOOT (BIT(3))
#define SYSTEM_RST_EN_SECURE_BOOT_S 3
#define SYSTEM_RST_EN_RSA (BIT(2))
#define SYSTEM_RST_EN_RSA_S 2
#define SYSTEM_RST_EN_SHA (BIT(1))
#define SYSTEM_RST_EN_SHA_S 1
#define SYSTEM_RST_EN_AES (BIT(0))
#define SYSTEM_RST_EN_AES_S 0

#define SYSTEM_CPU_PER_CONF_REG (REG_SYSTEM_BASE + 0x018)
#define SYSTEM_CPU_WAIT_MODE_FORCE_ON (BIT(3))
#define SYSTEM_CPU_WAIT_MODE_FORCE_ON_S 3
#define SYSTEM_PLL_FREQ_SEL (BIT(2))
#define SYSTEM_PLL_FREQ_SEL_S 2
#define SYSTEM_CPUPERIOD_SEL 0x00000003
#define SYSTEM_CPUPERIOD_SEL_S 0

#define SYSTEM_JTAG_CTRL_0_REG (REG_SYSTEM_BASE + 0x01C)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_0 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_0_S 0

#define SYSTEM_JTAG_CTRL_1_REG (REG_SYSTEM_BASE + 0x020)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_1 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_1_S 0

#define SYSTEM_JTAG_CTRL_2_REG (REG_SYSTEM_BASE + 0x024)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_2 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_2_S 0

#define SYSTEM_JTAG_CTRL_3_REG (REG_SYSTEM_BASE + 0x028)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_3 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_3_S 0

#define SYSTEM_JTAG_CTRL_4_REG (REG_SYSTEM_BASE + 0x02C)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_4 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_4_S 0

#define SYSTEM_JTAG_CTRL_5_REG (REG_SYSTEM_BASE + 0x030)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_5 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_5_S 0

#define SYSTEM_JTAG_CTRL_6_REG (REG_SYSTEM_BASE + 0x034)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_6 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_6_S 0

#define SYSTEM_JTAG_CTRL_7_REG (REG_SYSTEM_BASE + 0x038)
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_7 0xFFFFFFFF
#define SYSTEM_CANCEL_EFUSE_DISABLE_JTAG_TEMPORARY_7_S 0

#define SYSTEM_MEM_PD_MASK_REG (REG_SYSTEM_BASE + 0x03C)
#define SYSTEM_LSLP_MEM_PD_MASK (BIT(0))
#define SYSTEM_LSLP_MEM_PD_MASK_S 0

#define SYSTEM_PERIP_CLK_EN0_REG (REG_SYSTEM_BASE + 0x040)
#define SYSTEM_SPI4_CLK_EN (BIT(31))
#define SYSTEM_SPI4_CLK_EN_S 31
#define SYSTEM_ADC2_ARB_CLK_EN (BIT(30))
#define SYSTEM_ADC2_ARB_CLK_EN_S 30
#define SYSTEM_SYSTIMER_CLK_EN (BIT(29))
#define SYSTEM_SYSTIMER_CLK_EN_S 29
#define SYSTEM_APB_SARADC_CLK_EN (BIT(28))
#define SYSTEM_APB_SARADC_CLK_EN_S 28
#define SYSTEM_SPI3_DMA_CLK_EN (BIT(27))
#define SYSTEM_SPI3_DMA_CLK_EN_S 27
#define SYSTEM_PWM3_CLK_EN (BIT(26))
#define SYSTEM_PWM3_CLK_EN_S 26
#define SYSTEM_PWM2_CLK_EN (BIT(25))
#define SYSTEM_PWM2_CLK_EN_S 25
#define SYSTEM_UART_MEM_CLK_EN (BIT(24))
#define SYSTEM_UART_MEM_CLK_EN_S 24
#define SYSTEM_USB_CLK_EN (BIT(23))
#define SYSTEM_USB_CLK_EN_S 23
#define SYSTEM_SPI2_DMA_CLK_EN (BIT(22))
#define SYSTEM_SPI2_DMA_CLK_EN_S 22
#define SYSTEM_I2S1_CLK_EN (BIT(21))
#define SYSTEM_I2S1_CLK_EN_S 21
#define SYSTEM_PWM1_CLK_EN (BIT(20))
#define SYSTEM_PWM1_CLK_EN_S 20
#define SYSTEM_CAN_CLK_EN (BIT(19))
#define SYSTEM_CAN_CLK_EN_S 19
#define SYSTEM_I2C_EXT1_CLK_EN (BIT(18))
#define SYSTEM_I2C_EXT1_CLK_EN_S 18
#define SYSTEM_PWM0_CLK_EN (BIT(17))
#define SYSTEM_PWM0_CLK_EN_S 17
#define SYSTEM_SPI3_CLK_EN (BIT(16))
#define SYSTEM_SPI3_CLK_EN_S 16
#define SYSTEM_TIMERGROUP1_CLK_EN (BIT(15))
#define SYSTEM_TIMERGROUP1_CLK_EN_S 15
#define SYSTEM_EFUSE_CLK_EN (BIT(14))
#define SYSTEM_EFUSE_CLK_EN_S 14
#define SYSTEM_TIMERGROUP_CLK_EN (BIT(13))
#define SYSTEM_TIMERGROUP_CLK_EN_S 13
#define SYSTEM_UHCI1_CLK_EN (BIT(12))
#define SYSTEM_UHCI1_CLK_EN_S 12
#define SYSTEM_LEDC_CLK_EN (BIT(11))
#define SYSTEM_LEDC_CLK_EN_S 11
#define SYSTEM_PCNT_CLK_EN (BIT(10))
#define SYSTEM_PCNT_CLK_EN_S 10
#define SYSTEM_RMT_CLK_EN (BIT(9))
#define SYSTEM_RMT_CLK_EN_S 9
#define SYSTEM_UHCI0_CLK_EN (BIT(8))
#define SYSTEM_UHCI0_CLK_EN_S 8
#define SYSTEM_I2C_EXT0_CLK_EN (BIT(7))
#define SYSTEM_I2C_EXT0_CLK_EN_S 7
#define SYSTEM_SPI2_CLK_EN (BIT(6))
#define SYSTEM_SPI2_CLK_EN_S 6
#define SYSTEM_UART1_CLK_EN (BIT(5))
#define SYSTEM_UART1_CLK_EN_S 5
#define SYSTEM_I2S0_CLK_EN (BIT(4))
#define SYSTEM_I2S0_CLK_EN_S 4
#define SYSTEM_WDG_CLK_EN (BIT(3))
#define SYSTEM_WDG_CLK_EN_S 3
#define SYSTEM_UART_CLK_EN (BIT(2))
#define SYSTEM_UART_CLK_EN_S 2
#define SYSTEM_SPI01_CLK_EN (BIT(1))
#define SYSTEM_SPI01_CLK_EN_S 1
#define SYSTEM_TIMERS_CLK_EN (BIT(0))
#define SYSTEM_TIMERS_CLK_EN_S 0

#define SYSTEM_PERIP_CLK_EN1_REG (REG_SYSTEM_BASE + 0x044)
#define SYSTEM_SPI_SHARED_DMA_CLK_EN (BIT(0))
#define SYSTEM_SPI_SHARED_DMA_CLK_EN_S 0

#define SYSTEM_PERIP_RST_EN0_REG (REG_SYSTEM_BASE + 0x048)
#define SYSTEM_SPI4_RST (BIT(31))
#define SYSTEM_SPI4_RST_S 31
#define SYSTEM_ADC2_ARB_RST (BIT(30))
#define SYSTEM_ADC2_ARB_RST_S 30
#define SYSTEM_SYSTIMER_RST (BIT(29))
#define SYSTEM_SYSTIMER_RST_S 29
#define SYSTEM_APB_SARADC_RST (BIT(28))
#define SYSTEM_APB_SARADC_RST_S 28
#define SYSTEM_SPI3_DMA_RST (BIT(27))
#define SYSTEM_SPI3_DMA_RST_S 27
#define SYSTEM_PWM3_RST (BIT(26))
#define SYSTEM_PWM3_RST_S 26
#define SYSTEM_PWM2_RST (BIT(25))
#define SYSTEM_PWM2_RST_S 25
#define SYSTEM_UART_MEM_RST (BIT(24))
#define SYSTEM_UART_MEM_RST_S 24
#define SYSTEM_USB_RST (BIT(23))
#define SYSTEM_USB_RST_S 23
#define SYSTEM_SPI2_DMA_RST (BIT(22))
#define SYSTEM_SPI2_DMA_RST_S 22
#define SYSTEM_I2S1_RST (BIT(21))
#define SYSTEM_I2S1_RST_S 21
#define SYSTEM_PWM1_RST (BIT(20))
#define SYSTEM_PWM1_RST_S 20
#define SYSTEM_CAN_RST (BIT(19))
#define SYSTEM_CAN_RST_S 19
#define SYSTEM_I2C_EXT1_RST (BIT(18))
#define SYSTEM_I2C_EXT1_RST_S 18
#define SYSTEM_PWM0_RST (BIT(17))
#define SYSTEM_PWM0_RST_S 17
#define SYSTEM_SPI3_RST (BIT(16))
#define SYSTEM_SPI3_RST_S 16
#define SYSTEM_TIMERGROUP1_RST (BIT(15))
#define SYSTEM_TIMERGROUP1_RST_S 15
#define SYSTEM_EFUSE_RST (BIT(14))
#define SYSTEM_EFUSE_RST_S 14
#define SYSTEM_TIMERGROUP_RST (BIT(13))
#define SYSTEM_TIMERGROUP_RST_S 13
#define SYSTEM_UHCI1_RST (BIT(12))
#define SYSTEM_UHCI1_RST_S 12
#define SYSTEM_LEDC_RST (BIT(11))
#define SYSTEM_LEDC_RST_S 11
#define SYSTEM_PCNT_RST (BIT(10))
#define SYSTEM_PCNT_RST_S 10
#define SYSTEM_RMT_RST (BIT(9))
#define SYSTEM_RMT_RST_S 9
#define SYSTEM_UHCI0_RST (BIT(8))
#define SYSTEM_UHCI0_RST_S 8
#define SYSTEM_I2C_EXT0_RST (BIT(7))
#define SYSTEM_I2C_EXT0_RST_S 7
#define SYSTEM_SPI2_RST (BIT(6))
#define SYSTEM_SPI2_RST_S 6
#define SYSTEM_UART1_RST (BIT(5))
#define SYSTEM_UART1_RST_S 5
#define SYSTEM_I2S0_RST (BIT(4))
#define SYSTEM_I2S0_RST_S 4
#define SYSTEM_WDG_RST (BIT(3))
#define SYSTEM_WDG_RST_S 3
#define SYSTEM_UART_RST (BIT(2))
#define SYSTEM_UART_RST_S 2
#define SYSTEM_SPI01_RST (BIT(1))
#define SYSTEM_SPI01_RST_S 1
#define SYSTEM_TIMERS_RST (BIT(0))
#define SYSTEM_TIMERS_RST_S 0

#define SYSTEM_PERIP_RST_EN1_REG (REG_SYSTEM_BASE + 0x04C)
#define SYSTEM_SPI_SHARED_DMA_RST (BIT(0))
#define SYSTEM_SPI_SHARED_DMA_RST_S 0

#define SYSTEM_BT_LPCK_DIV_INT_REG (REG_SYSTEM_BASE + 0x050)
#define SYSTEM_BT_LPCK_DIV_NUM 0x00000FFF
#define SYSTEM_BT_LPCK_DIV_NUM_S 0

#define SYSTEM_BT_LPCK_DIV_FRAC_REG (REG_SYSTEM_BASE + 0x054)
#define SYSTEM_LPCLK_RTC_EN (BIT(28))
#define SYSTEM_LPCLK_RTC_EN_S 28
#define SYSTEM_LPCLK_SEL_XTAL32K (BIT(27))
#define SYSTEM_LPCLK_SEL_XTAL32K_S 27
#define SYSTEM_LPCLK_SEL_XTAL (BIT(26))
#define SYSTEM_LPCLK_SEL_XTAL_S 26
#define SYSTEM_LPCLK_SEL_8M (BIT(25))
#define SYSTEM_LPCLK_SEL_8M_S 25
#define SYSTEM_LPCLK_SEL_RTC_SLOW (BIT(24))
#define SYSTEM_LPCLK_SEL_RTC_SLOW_S 24
#define SYSTEM_BT_LPCK_DIV_A 0x00000FFF
#define SYSTEM_BT_LPCK_DIV_A_S 12
#define SYSTEM_BT_LPCK_DIV_B 0x00000FFF
#define SYSTEM_BT_LPCK_DIV_B_S 0

#define SYSTEM_CPU_INTR_FROM_CPU_0_REG (REG_SYSTEM_BASE + 0x058)
#define SYSTEM_CPU_INTR_FROM_CPU_0 (BIT(0))
#define SYSTEM_CPU_INTR_FROM_CPU_0_S 0

#define SYSTEM_CPU_INTR_FROM_CPU_1_REG (REG_SYSTEM_BASE + 0x05C)
#define SYSTEM_CPU_INTR_FROM_CPU_1 (BIT(0))
#define SYSTEM_CPU_INTR_FROM_CPU_1_S 0

#define SYSTEM_CPU_INTR_FROM_CPU_2_REG (REG_SYSTEM_BASE + 0x060)
#define SYSTEM_CPU_INTR_FROM_CPU_2 (BIT(0))
#define SYSTEM_CPU_INTR_FROM_CPU_2_S 0

#define SYSTEM_CPU_INTR_FROM_CPU_3_REG (REG_SYSTEM_BASE + 0x064)
#define SYSTEM_CPU_INTR_FROM_CPU_3 (BIT(0))
#define SYSTEM_CPU_INTR_FROM_CPU_3_S 0

#define SYSTEM_RSA_PD_CTRL_REG (REG_SYSTEM_BASE + 0x068)
#define SYSTEM_RSA_MEM_PD (BIT(0))
#define SYSTEM_RSA_MEM_PD_S 0

#define SYSTEM_SPI_SHARED_DMA_SEL_REG (REG_SYSTEM_BASE + 0x06C)
#define SYSTEM_SPI_SHARED_DMA_SEL (BIT(0))
#define SYSTEM_SPI_SHARED_DMA_SEL_S 0

#define SYSTEM_BUSTOEXTMEM_ENA_REG (REG_SYSTEM_BASE + 0x070)
#define SYSTEM_BUSTOEXTMEM_ENA (BIT(0))
#define SYSTEM_BUSTOEXTMEM_ENA_S 0

#define SYSTEM_CACHE_CONTROL_REG (REG_SYSTEM_BASE + 0x074)
#define SYSTEM_PRO_CACHE_RESET (BIT(2))
#define SYSTEM_PRO_CACHE_RESET_S 2
#define SYSTEM_PRO_DCACHE_CLK_ON (BIT(1))
#define SYSTEM_PRO_DCACHE_CLK_ON_S 1
#define SYSTEM_PRO_ICACHE_CLK_ON (BIT(0))
#define SYSTEM_PRO_ICACHE_CLK_ON_S 0

#define SYSTEM_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_REG (REG_SYSTEM_BASE + 0x078)
#define SYSTEM_ENABLE_DOWNLOAD_MANUAL_ENCRYPT (BIT(3))
#define SYSTEM_ENABLE_DOWNLOAD_MANUAL_ENCRYPT_S 3
#define SYSTEM_ENABLE_DOWNLOAD_G0CB_DECRYPT (BIT(2))
#define SYSTEM_ENABLE_DOWNLOAD_G0CB_DECRYPT_S 2
#define SYSTEM_ENABLE_DOWNLOAD_DB_ENCRYPT (BIT(1))
#define SYSTEM_ENABLE_DOWNLOAD_DB_ENCRYPT_S 1
#define SYSTEM_ENABLE_SPI_MANUAL_ENCRYPT (BIT(0))
#define SYSTEM_ENABLE_SPI_MANUAL_ENCRYPT_S 0

#define SYSTEM_RTC_FASTMEM_CONFIG_REG (REG_SYSTEM_BASE + 0x07C)
#define SYSTEM_RTC_MEM_CRC_FINISH (BIT(31))
#define SYSTEM_RTC_MEM_CRC_FINISH_S 31
#define SYSTEM_RTC_MEM_CRC_LEN 0x000007FF
#define SYSTEM_RTC_MEM_CRC_LEN_S 20
#define SYSTEM_RTC_MEM_CRC_ADDR 0x000007FF
#define SYSTEM_RTC_MEM_CRC_ADDR_S 9
#define SYSTEM_RTC_MEM_CRC_START (BIT(8))
#define SYSTEM_RTC_MEM_CRC_START_S 8

#define SYSTEM_RTC_FASTMEM_CRC_REG (REG_SYSTEM_BASE + 0x080)
#define SYSTEM_RTC_MEM_CRC_RES 0xFFFFFFFF
#define SYSTEM_RTC_MEM_CRC_RES_S 0

#define SYSTEM_REDUNDANT_ECO_CTRL_REG (REG_SYSTEM_BASE + 0x084)
#define SYSTEM_REDUNDANT_ECO_RESULT (BIT(1))
#define SYSTEM_REDUNDANT_ECO_RESULT_S 1
#define SYSTEM_REDUNDANT_ECO_DRIVE (BIT(0))
#define SYSTEM_REDUNDANT_ECO_DRIVE_S 0

#define SYSTEM_CLOCK_GATE_REG (REG_SYSTEM_BASE + 0x088)
#define SYSTEM_CLK_EN (BIT(0))
#define SYSTEM_CLK_EN_S 0

#define SYSTEM_REG_DATE_REG (REG_SYSTEM_BASE + 0xFFC)
#define SYSTEM_DATE 0x0FFFFFFF
#define SYSTEM_DATE_S 0
#define SYSTEM_DATE_VERSION 0x1810300
