 
// Mon Dec 19 11:52:58 HKT 2016
#ifndef HCI_REGISTER_H_INCLUDED
#define HCI_REGISTER_H_INCLUDED
 

#define UHCI_CONF0_REG( i ) (REG_UHCI_BASE( i ) + 0x0)
#define UHCI_UART_RX_BRK_EOF_EN (BIT(23))
#define UHCI_UART_RX_BRK_EOF_EN_S 23
#define UHCI_CLK_EN (BIT(22))
#define UHCI_CLK_EN_S 22
#define UHCI_ENCODE_CRC_EN (BIT(21))
#define UHCI_ENCODE_CRC_EN_S 21
#define UHCI_LEN_EOF_EN (BIT(20))
#define UHCI_LEN_EOF_EN_S 20
#define UHCI_UART_IDLE_EOF_EN (BIT(19))
#define UHCI_UART_IDLE_EOF_EN_S 19
#define UHCI_CRC_REC_EN (BIT(18))
#define UHCI_CRC_REC_EN_S 18
#define UHCI_HEAD_EN (BIT(17))
#define UHCI_HEAD_EN_S 17
#define UHCI_SEPER_EN (BIT(16))
#define UHCI_SEPER_EN_S 16
#define UHCI_MEM_TRANS_EN (BIT(15))
#define UHCI_MEM_TRANS_EN_S 15
#define UHCI_OUT_DATA_BURST_EN (BIT(14))
#define UHCI_OUT_DATA_BURST_EN_S 14
#define UHCI_INDSCR_BURST_EN (BIT(13))
#define UHCI_INDSCR_BURST_EN_S 13
#define UHCI_OUTDSCR_BURST_EN (BIT(12))
#define UHCI_OUTDSCR_BURST_EN_S 12
#define UHCI_UART2_CE (BIT(11))
#define UHCI_UART2_CE_S 11
#define UHCI_UART1_CE (BIT(10))
#define UHCI_UART1_CE_S 10
#define UHCI_UART0_CE (BIT(9))
#define UHCI_UART0_CE_S 9
#define UHCI_OUT_EOF_MODE (BIT(8))
#define UHCI_OUT_EOF_MODE_S 8
#define UHCI_OUT_NO_RESTART_CLR (BIT(7))
#define UHCI_OUT_NO_RESTART_CLR_S 7
#define UHCI_OUT_AUTO_WRBACK (BIT(6))
#define UHCI_OUT_AUTO_WRBACK_S 6
#define UHCI_OUT_LOOP_TEST (BIT(5))
#define UHCI_OUT_LOOP_TEST_S 5
#define UHCI_IN_LOOP_TEST (BIT(4))
#define UHCI_IN_LOOP_TEST_S 4
#define UHCI_AHBM_RST (BIT(3))
#define UHCI_AHBM_RST_S 3
#define UHCI_AHBM_FIFO_RST (BIT(2))
#define UHCI_AHBM_FIFO_RST_S 2
#define UHCI_OUT_RST (BIT(1))
#define UHCI_OUT_RST_S 1
#define UHCI_IN_RST (BIT(0))
#define UHCI_IN_RST_S 0

#define UHCI_INT_RAW_REG( i ) (REG_UHCI_BASE( i ) + 0x4)
#define UHCI_DMA_INFIFO_FULL_WM_INT_RAW (BIT(16))
#define UHCI_DMA_INFIFO_FULL_WM_INT_RAW_S 16
#define UHCI_SEND_A_Q_INT_RAW (BIT(15))
#define UHCI_SEND_A_Q_INT_RAW_S 15
#define UHCI_SEND_S_Q_INT_RAW (BIT(14))
#define UHCI_SEND_S_Q_INT_RAW_S 14
#define UHCI_OUT_TOTAL_EOF_INT_RAW (BIT(13))
#define UHCI_OUT_TOTAL_EOF_INT_RAW_S 13
#define UHCI_OUTLINK_EOF_ERR_INT_RAW (BIT(12))
#define UHCI_OUTLINK_EOF_ERR_INT_RAW_S 12
#define UHCI_IN_DSCR_EMPTY_INT_RAW (BIT(11))
#define UHCI_IN_DSCR_EMPTY_INT_RAW_S 11
#define UHCI_OUT_DSCR_ERR_INT_RAW (BIT(10))
#define UHCI_OUT_DSCR_ERR_INT_RAW_S 10
#define UHCI_IN_DSCR_ERR_INT_RAW (BIT(9))
#define UHCI_IN_DSCR_ERR_INT_RAW_S 9
#define UHCI_OUT_EOF_INT_RAW (BIT(8))
#define UHCI_OUT_EOF_INT_RAW_S 8
#define UHCI_OUT_DONE_INT_RAW (BIT(7))
#define UHCI_OUT_DONE_INT_RAW_S 7
#define UHCI_IN_ERR_EOF_INT_RAW (BIT(6))
#define UHCI_IN_ERR_EOF_INT_RAW_S 6
#define UHCI_IN_SUC_EOF_INT_RAW (BIT(5))
#define UHCI_IN_SUC_EOF_INT_RAW_S 5
#define UHCI_IN_DONE_INT_RAW (BIT(4))
#define UHCI_IN_DONE_INT_RAW_S 4
#define UHCI_TX_HUNG_INT_RAW (BIT(3))
#define UHCI_TX_HUNG_INT_RAW_S 3
#define UHCI_RX_HUNG_INT_RAW (BIT(2))
#define UHCI_RX_HUNG_INT_RAW_S 2
#define UHCI_TX_START_INT_RAW (BIT(1))
#define UHCI_TX_START_INT_RAW_S 1
#define UHCI_RX_START_INT_RAW (BIT(0))
#define UHCI_RX_START_INT_RAW_S 0

#define UHCI_INT_ST_REG( i ) (REG_UHCI_BASE( i ) + 0x8)
#define UHCI_DMA_INFIFO_FULL_WM_INT_ST (BIT(16))
#define UHCI_DMA_INFIFO_FULL_WM_INT_ST_S 16
#define UHCI_SEND_A_Q_INT_ST (BIT(15))
#define UHCI_SEND_A_Q_INT_ST_S 15
#define UHCI_SEND_S_Q_INT_ST (BIT(14))
#define UHCI_SEND_S_Q_INT_ST_S 14
#define UHCI_OUT_TOTAL_EOF_INT_ST (BIT(13))
#define UHCI_OUT_TOTAL_EOF_INT_ST_S 13
#define UHCI_OUTLINK_EOF_ERR_INT_ST (BIT(12))
#define UHCI_OUTLINK_EOF_ERR_INT_ST_S 12
#define UHCI_IN_DSCR_EMPTY_INT_ST (BIT(11))
#define UHCI_IN_DSCR_EMPTY_INT_ST_S 11
#define UHCI_OUT_DSCR_ERR_INT_ST (BIT(10))
#define UHCI_OUT_DSCR_ERR_INT_ST_S 10
#define UHCI_IN_DSCR_ERR_INT_ST (BIT(9))
#define UHCI_IN_DSCR_ERR_INT_ST_S 9
#define UHCI_OUT_EOF_INT_ST (BIT(8))
#define UHCI_OUT_EOF_INT_ST_S 8
#define UHCI_OUT_DONE_INT_ST (BIT(7))
#define UHCI_OUT_DONE_INT_ST_S 7
#define UHCI_IN_ERR_EOF_INT_ST (BIT(6))
#define UHCI_IN_ERR_EOF_INT_ST_S 6
#define UHCI_IN_SUC_EOF_INT_ST (BIT(5))
#define UHCI_IN_SUC_EOF_INT_ST_S 5
#define UHCI_IN_DONE_INT_ST (BIT(4))
#define UHCI_IN_DONE_INT_ST_S 4
#define UHCI_TX_HUNG_INT_ST (BIT(3))
#define UHCI_TX_HUNG_INT_ST_S 3
#define UHCI_RX_HUNG_INT_ST (BIT(2))
#define UHCI_RX_HUNG_INT_ST_S 2
#define UHCI_TX_START_INT_ST (BIT(1))
#define UHCI_TX_START_INT_ST_S 1
#define UHCI_RX_START_INT_ST (BIT(0))
#define UHCI_RX_START_INT_ST_S 0

#define UHCI_INT_ENA_REG( i ) (REG_UHCI_BASE( i ) + 0xC)
#define UHCI_DMA_INFIFO_FULL_WM_INT_ENA (BIT(16))
#define UHCI_DMA_INFIFO_FULL_WM_INT_ENA_S 16
#define UHCI_SEND_A_Q_INT_ENA (BIT(15))
#define UHCI_SEND_A_Q_INT_ENA_S 15
#define UHCI_SEND_S_Q_INT_ENA (BIT(14))
#define UHCI_SEND_S_Q_INT_ENA_S 14
#define UHCI_OUT_TOTAL_EOF_INT_ENA (BIT(13))
#define UHCI_OUT_TOTAL_EOF_INT_ENA_S 13
#define UHCI_OUTLINK_EOF_ERR_INT_ENA (BIT(12))
#define UHCI_OUTLINK_EOF_ERR_INT_ENA_S 12
#define UHCI_IN_DSCR_EMPTY_INT_ENA (BIT(11))
#define UHCI_IN_DSCR_EMPTY_INT_ENA_S 11
#define UHCI_OUT_DSCR_ERR_INT_ENA (BIT(10))
#define UHCI_OUT_DSCR_ERR_INT_ENA_S 10
#define UHCI_IN_DSCR_ERR_INT_ENA (BIT(9))
#define UHCI_IN_DSCR_ERR_INT_ENA_S 9
#define UHCI_OUT_EOF_INT_ENA (BIT(8))
#define UHCI_OUT_EOF_INT_ENA_S 8
#define UHCI_OUT_DONE_INT_ENA (BIT(7))
#define UHCI_OUT_DONE_INT_ENA_S 7
#define UHCI_IN_ERR_EOF_INT_ENA (BIT(6))
#define UHCI_IN_ERR_EOF_INT_ENA_S 6
#define UHCI_IN_SUC_EOF_INT_ENA (BIT(5))
#define UHCI_IN_SUC_EOF_INT_ENA_S 5
#define UHCI_IN_DONE_INT_ENA (BIT(4))
#define UHCI_IN_DONE_INT_ENA_S 4
#define UHCI_TX_HUNG_INT_ENA (BIT(3))
#define UHCI_TX_HUNG_INT_ENA_S 3
#define UHCI_RX_HUNG_INT_ENA (BIT(2))
#define UHCI_RX_HUNG_INT_ENA_S 2
#define UHCI_TX_START_INT_ENA (BIT(1))
#define UHCI_TX_START_INT_ENA_S 1
#define UHCI_RX_START_INT_ENA (BIT(0))
#define UHCI_RX_START_INT_ENA_S 0

#define UHCI_INT_CLR_REG( i ) (REG_UHCI_BASE( i ) + 0x10)
#define UHCI_DMA_INFIFO_FULL_WM_INT_CLR (BIT(16))
#define UHCI_DMA_INFIFO_FULL_WM_INT_CLR_S 16
#define UHCI_SEND_A_REG_Q_INT_CLR (BIT(15))
#define UHCI_SEND_A_REG_Q_INT_CLR_S 15
#define UHCI_SEND_S_REG_Q_INT_CLR (BIT(14))
#define UHCI_SEND_S_REG_Q_INT_CLR_S 14
#define UHCI_OUT_TOTAL_EOF_INT_CLR (BIT(13))
#define UHCI_OUT_TOTAL_EOF_INT_CLR_S 13
#define UHCI_OUTLINK_EOF_ERR_INT_CLR (BIT(12))
#define UHCI_OUTLINK_EOF_ERR_INT_CLR_S 12
#define UHCI_IN_DSCR_EMPTY_INT_CLR (BIT(11))
#define UHCI_IN_DSCR_EMPTY_INT_CLR_S 11
#define UHCI_OUT_DSCR_ERR_INT_CLR (BIT(10))
#define UHCI_OUT_DSCR_ERR_INT_CLR_S 10
#define UHCI_IN_DSCR_ERR_INT_CLR (BIT(9))
#define UHCI_IN_DSCR_ERR_INT_CLR_S 9
#define UHCI_OUT_EOF_INT_CLR (BIT(8))
#define UHCI_OUT_EOF_INT_CLR_S 8
#define UHCI_OUT_DONE_INT_CLR (BIT(7))
#define UHCI_OUT_DONE_INT_CLR_S 7
#define UHCI_IN_ERR_EOF_INT_CLR (BIT(6))
#define UHCI_IN_ERR_EOF_INT_CLR_S 6
#define UHCI_IN_SUC_EOF_INT_CLR (BIT(5))
#define UHCI_IN_SUC_EOF_INT_CLR_S 5
#define UHCI_IN_DONE_INT_CLR (BIT(4))
#define UHCI_IN_DONE_INT_CLR_S 4
#define UHCI_TX_HUNG_INT_CLR (BIT(3))
#define UHCI_TX_HUNG_INT_CLR_S 3
#define UHCI_RX_HUNG_INT_CLR (BIT(2))
#define UHCI_RX_HUNG_INT_CLR_S 2
#define UHCI_TX_START_INT_CLR (BIT(1))
#define UHCI_TX_START_INT_CLR_S 1
#define UHCI_RX_START_INT_CLR (BIT(0))
#define UHCI_RX_START_INT_CLR_S 0

#define UHCI_DMA_OUT_STATUS_REG( i ) (REG_UHCI_BASE( i ) + 0x14)
#define UHCI_OUT_EMPTY (BIT(1))
#define UHCI_OUT_EMPTY_S 1
#define UHCI_OUT_FULL (BIT(0))
#define UHCI_OUT_FULL_S 0

#define UHCI_DMA_OUT_PUSH_REG( i ) (REG_UHCI_BASE( i ) + 0x18)
#define UHCI_OUTFIFO_PUSH (BIT(16))
#define UHCI_OUTFIFO_PUSH_S 16
#define UHCI_OUTFIFO_WDATA 0x000001FF
#define UHCI_OUTFIFO_WDATA_S 0

#define UHCI_DMA_IN_STATUS_REG( i ) (REG_UHCI_BASE( i ) + 0x1C)
#define UHCI_RX_ERR_CAUSE 0x00000007
#define UHCI_RX_ERR_CAUSE_S 4
#define UHCI_IN_EMPTY (BIT(1))
#define UHCI_IN_EMPTY_S 1
#define UHCI_IN_FULL (BIT(0))
#define UHCI_IN_FULL_S 0

#define UHCI_DMA_IN_POP_REG( i ) (REG_UHCI_BASE( i ) + 0x20)
#define UHCI_INFIFO_POP (BIT(16))
#define UHCI_INFIFO_POP_S 16
#define UHCI_INFIFO_RDATA 0x00000FFF
#define UHCI_INFIFO_RDATA_S 0

#define UHCI_DMA_OUT_LINK_REG( i ) (REG_UHCI_BASE( i ) + 0x24)
#define UHCI_OUTLINK_PARK (BIT(31))
#define UHCI_OUTLINK_PARK_S 31
#define UHCI_OUTLINK_RESTART (BIT(30))
#define UHCI_OUTLINK_RESTART_S 30
#define UHCI_OUTLINK_START (BIT(29))
#define UHCI_OUTLINK_START_S 29
#define UHCI_OUTLINK_STOP (BIT(28))
#define UHCI_OUTLINK_STOP_S 28
#define UHCI_OUTLINK_ADDR 0x000FFFFF
#define UHCI_OUTLINK_ADDR_S 0

#define UHCI_DMA_IN_LINK_REG( i ) (REG_UHCI_BASE( i ) + 0x28)
#define UHCI_INLINK_PARK (BIT(31))
#define UHCI_INLINK_PARK_S 31
#define UHCI_INLINK_RESTART (BIT(30))
#define UHCI_INLINK_RESTART_S 30
#define UHCI_INLINK_START (BIT(29))
#define UHCI_INLINK_START_S 29
#define UHCI_INLINK_STOP (BIT(28))
#define UHCI_INLINK_STOP_S 28
#define UHCI_INLINK_AUTO_RET (BIT(20))
#define UHCI_INLINK_AUTO_RET_S 20
#define UHCI_INLINK_ADDR 0x000FFFFF
#define UHCI_INLINK_ADDR_S 0

#define UHCI_CONF1_REG( i ) (REG_UHCI_BASE( i ) + 0x2C)
#define UHCI_DMA_INFIFO_FULL_THRS 0x00000FFF
#define UHCI_DMA_INFIFO_FULL_THRS_S 9
#define UHCI_SW_START (BIT(8))
#define UHCI_SW_START_S 8
#define UHCI_WAIT_SW_START (BIT(7))
#define UHCI_WAIT_SW_START_S 7
#define UHCI_CHECK_OWNER (BIT(6))
#define UHCI_CHECK_OWNER_S 6
#define UHCI_TX_ACK_NUM_RE (BIT(5))
#define UHCI_TX_ACK_NUM_RE_S 5
#define UHCI_TX_CHECK_SUM_RE (BIT(4))
#define UHCI_TX_CHECK_SUM_RE_S 4
#define UHCI_SAVE_HEAD (BIT(3))
#define UHCI_SAVE_HEAD_S 3
#define UHCI_CRC_DISABLE (BIT(2))
#define UHCI_CRC_DISABLE_S 2
#define UHCI_CHECK_SEQ_EN (BIT(1))
#define UHCI_CHECK_SEQ_EN_S 1
#define UHCI_CHECK_SUM_EN (BIT(0))
#define UHCI_CHECK_SUM_EN_S 0

#define UHCI_STATE0_REG( i ) (REG_UHCI_BASE( i ) + 0x30)
#define UHCI_STATE0 0xFFFFFFFF
#define UHCI_STATE0_S 0

#define UHCI_STATE1_REG( i ) (REG_UHCI_BASE( i ) + 0x34)
#define UHCI_STATE1 0xFFFFFFFF
#define UHCI_STATE1_S 0

#define UHCI_DMA_OUT_EOF_DES_ADDR_REG( i ) (REG_UHCI_BASE( i ) + 0x38)
#define UHCI_OUT_EOF_DES_ADDR 0xFFFFFFFF
#define UHCI_OUT_EOF_DES_ADDR_S 0

#define UHCI_DMA_IN_SUC_EOF_DES_ADDR_REG( i ) (REG_UHCI_BASE( i ) + 0x3C)
#define UHCI_IN_SUC_EOF_DES_ADDR 0xFFFFFFFF
#define UHCI_IN_SUC_EOF_DES_ADDR_S 0

#define UHCI_DMA_IN_ERR_EOF_DES_ADDR_REG( i ) (REG_UHCI_BASE( i ) + 0x40)
#define UHCI_IN_ERR_EOF_DES_ADDR 0xFFFFFFFF
#define UHCI_IN_ERR_EOF_DES_ADDR_S 0

#define UHCI_DMA_OUT_EOF_BFR_DES_ADDR_REG( i ) (REG_UHCI_BASE( i ) + 0x44)
#define UHCI_OUT_EOF_BFR_DES_ADDR 0xFFFFFFFF
#define UHCI_OUT_EOF_BFR_DES_ADDR_S 0

#define UHCI_AHB_TEST_REG( i ) (REG_UHCI_BASE( i ) + 0x48)
#define UHCI_AHB_TESTADDR 0x00000003
#define UHCI_AHB_TESTADDR_S 4
#define UHCI_AHB_TESTMODE 0x00000007
#define UHCI_AHB_TESTMODE_S 0

#define UHCI_DMA_IN_DSCR_REG( i ) (REG_UHCI_BASE( i ) + 0x4C)
#define UHCI_INLINK_DSCR 0xFFFFFFFF
#define UHCI_INLINK_DSCR_S 0

#define UHCI_DMA_IN_DSCR_BF0_REG( i ) (REG_UHCI_BASE( i ) + 0x50)
#define UHCI_INLINK_DSCR_BF0 0xFFFFFFFF
#define UHCI_INLINK_DSCR_BF0_S 0

#define UHCI_DMA_IN_DSCR_BF1_REG( i ) (REG_UHCI_BASE( i ) + 0x54)
#define UHCI_INLINK_DSCR_BF1 0xFFFFFFFF
#define UHCI_INLINK_DSCR_BF1_S 0

#define UHCI_DMA_OUT_DSCR_REG( i ) (REG_UHCI_BASE( i ) + 0x58)
#define UHCI_OUTLINK_DSCR 0xFFFFFFFF
#define UHCI_OUTLINK_DSCR_S 0

#define UHCI_DMA_OUT_DSCR_BF0_REG( i ) (REG_UHCI_BASE( i ) + 0x5C)
#define UHCI_OUTLINK_DSCR_BF0 0xFFFFFFFF
#define UHCI_OUTLINK_DSCR_BF0_S 0

#define UHCI_DMA_OUT_DSCR_BF1_REG( i ) (REG_UHCI_BASE( i ) + 0x60)
#define UHCI_OUTLINK_DSCR_BF1 0xFFFFFFFF
#define UHCI_OUTLINK_DSCR_BF1_S 0

#define UHCI_ESCAPE_CONF_REG( i ) (REG_UHCI_BASE( i ) + 0x64)
#define UHCI_RX_13_ESC_EN (BIT(7))
#define UHCI_RX_13_ESC_EN_S 7
#define UHCI_RX_11_ESC_EN (BIT(6))
#define UHCI_RX_11_ESC_EN_S 6
#define UHCI_RX_DB_ESC_EN (BIT(5))
#define UHCI_RX_DB_ESC_EN_S 5
#define UHCI_RX_C0_ESC_EN (BIT(4))
#define UHCI_RX_C0_ESC_EN_S 4
#define UHCI_TX_13_ESC_EN (BIT(3))
#define UHCI_TX_13_ESC_EN_S 3
#define UHCI_TX_11_ESC_EN (BIT(2))
#define UHCI_TX_11_ESC_EN_S 2
#define UHCI_TX_DB_ESC_EN (BIT(1))
#define UHCI_TX_DB_ESC_EN_S 1
#define UHCI_TX_C0_ESC_EN (BIT(0))
#define UHCI_TX_C0_ESC_EN_S 0

#define UHCI_HUNG_CONF_REG( i ) (REG_UHCI_BASE( i ) + 0x68)
#define UHCI_RXFIFO_TIMEOUT_ENA (BIT(23))
#define UHCI_RXFIFO_TIMEOUT_ENA_S 23
#define UHCI_RXFIFO_TIMEOUT_SHIFT 0x00000007
#define UHCI_RXFIFO_TIMEOUT_SHIFT_S 20
#define UHCI_RXFIFO_TIMEOUT 0x000000FF
#define UHCI_RXFIFO_TIMEOUT_S 12
#define UHCI_TXFIFO_TIMEOUT_ENA (BIT(11))
#define UHCI_TXFIFO_TIMEOUT_ENA_S 11
#define UHCI_TXFIFO_TIMEOUT_SHIFT 0x00000007
#define UHCI_TXFIFO_TIMEOUT_SHIFT_S 8
#define UHCI_TXFIFO_TIMEOUT 0x000000FF
#define UHCI_TXFIFO_TIMEOUT_S 0

#define UHCI_ACK_NUM_REG( i ) (REG_UHCI_BASE( i ) + 0x6C)

#define UHCI_RX_HEAD_REG( i ) (REG_UHCI_BASE( i ) + 0x70)
#define UHCI_RX_HEAD 0xFFFFFFFF
#define UHCI_RX_HEAD_S 0

#define UHCI_QUICK_SENT_REG( i ) (REG_UHCI_BASE( i ) + 0x74)
#define UHCI_ALWAYS_SEND_EN (BIT(7))
#define UHCI_ALWAYS_SEND_EN_S 7
#define UHCI_ALWAYS_SEND_NUM 0x00000007
#define UHCI_ALWAYS_SEND_NUM_S 4
#define UHCI_SINGLE_SEND_EN (BIT(3))
#define UHCI_SINGLE_SEND_EN_S 3
#define UHCI_SINGLE_SEND_NUM 0x00000007
#define UHCI_SINGLE_SEND_NUM_S 0

#define UHCI_REG_Q0_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0x78)
#define UHCI_SEND_Q0_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q0_WORD0_S 0

#define UHCI_REG_Q0_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0x7C)
#define UHCI_SEND_Q0_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q0_WORD1_S 0

#define UHCI_REG_Q1_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0x80)
#define UHCI_SEND_Q1_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q1_WORD0_S 0

#define UHCI_REG_Q1_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0x84)
#define UHCI_SEND_Q1_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q1_WORD1_S 0

#define UHCI_REG_Q2_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0x88)
#define UHCI_SEND_Q2_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q2_WORD0_S 0

#define UHCI_REG_Q2_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0x8C)
#define UHCI_SEND_Q2_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q2_WORD1_S 0

#define UHCI_REG_Q3_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0x90)
#define UHCI_SEND_Q3_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q3_WORD0_S 0

#define UHCI_REG_Q3_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0x94)
#define UHCI_SEND_Q3_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q3_WORD1_S 0

#define UHCI_REG_Q4_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0x98)
#define UHCI_SEND_Q4_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q4_WORD0_S 0

#define UHCI_REG_Q4_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0x9C)
#define UHCI_SEND_Q4_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q4_WORD1_S 0

#define UHCI_REG_Q5_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0xA0)
#define UHCI_SEND_Q5_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q5_WORD0_S 0

#define UHCI_REG_Q5_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0xA4)
#define UHCI_SEND_Q5_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q5_WORD1_S 0

#define UHCI_REG_Q6_WORD0_REG( i ) (REG_UHCI_BASE( i ) + 0xA8)
#define UHCI_SEND_Q6_WORD0 0xFFFFFFFF
#define UHCI_SEND_Q6_WORD0_S 0

#define UHCI_REG_Q6_WORD1_REG( i ) (REG_UHCI_BASE( i ) + 0xAC)
#define UHCI_SEND_Q6_WORD1 0xFFFFFFFF
#define UHCI_SEND_Q6_WORD1_S 0

#define UHCI_ESC_CONF0_REG( i ) (REG_UHCI_BASE( i ) + 0xB0)
#define UHCI_SEPER_ESC_CHAR1 0x000000FF
#define UHCI_SEPER_ESC_CHAR1_S 16
#define UHCI_SEPER_ESC_CHAR0 0x000000FF
#define UHCI_SEPER_ESC_CHAR0_S 8
#define UHCI_SEPER_CHAR 0x000000FF
#define UHCI_SEPER_CHAR_S 0

#define UHCI_ESC_CONF1_REG( i ) (REG_UHCI_BASE( i ) + 0xB4)
#define UHCI_ESC_SEQ0_CHAR1 0x000000FF
#define UHCI_ESC_SEQ0_CHAR1_S 16
#define UHCI_ESC_SEQ0_CHAR0 0x000000FF
#define UHCI_ESC_SEQ0_CHAR0_S 8
#define UHCI_ESC_SEQ0 0x000000FF
#define UHCI_ESC_SEQ0_S 0

#define UHCI_ESC_CONF2_REG( i ) (REG_UHCI_BASE( i ) + 0xB8)
#define UHCI_ESC_SEQ1_CHAR1 0x000000FF
#define UHCI_ESC_SEQ1_CHAR1_S 16
#define UHCI_ESC_SEQ1_CHAR0 0x000000FF
#define UHCI_ESC_SEQ1_CHAR0_S 8
#define UHCI_ESC_SEQ1 0x000000FF
#define UHCI_ESC_SEQ1_S 0

#define UHCI_ESC_CONF3_REG( i ) (REG_UHCI_BASE( i ) + 0xBC)
#define UHCI_ESC_SEQ2_CHAR1 0x000000FF
#define UHCI_ESC_SEQ2_CHAR1_S 16
#define UHCI_ESC_SEQ2_CHAR0 0x000000FF
#define UHCI_ESC_SEQ2_CHAR0_S 8
#define UHCI_ESC_SEQ2 0x000000FF
#define UHCI_ESC_SEQ2_S 0

#define UHCI_PKT_THRES_REG( i ) (REG_UHCI_BASE( i ) + 0xC0)
#define UHCI_PKT_THRS 0x00001FFF
#define UHCI_PKT_THRS_S 0

#define UHCI_DATE_REG( i ) (REG_UHCI_BASE( i ) + 0xFC)
#define UHCI_DATE 0xFFFFFFFF
#define UHCI_DATE_S 0
#define UHCI_DATE_VERSION 0x16041001
 
#endif // HCI_REGISTER_H_INCLUDED
