
#define USB_WRAP_OTG_CONF_REG (REG_USB_WRAP_BASE + 0x000)
#define USB_WRAP_CLK_EN (BIT(31))
#define USB_WRAP_CLK_EN_S 31
#define USB_WRAP_PHY_TX_EDGE_SEL (BIT(21))
#define USB_WRAP_PHY_TX_EDGE_SEL_S 21
#define USB_WRAP_PHY_CLK_FORCE_ON (BIT(20))
#define USB_WRAP_PHY_CLK_FORCE_ON_S 20
#define USB_WRAP_AHB_CLK_FORCE_ON (BIT(19))
#define USB_WRAP_AHB_CLK_FORCE_ON_S 19
#define USB_WRAP_USB_PAD_ENABLE (BIT(18))
#define USB_WRAP_USB_PAD_ENABLE_S 18
#define USB_WRAP_PULLUP_VALUE (BIT(17))
#define USB_WRAP_PULLUP_VALUE_S 17
#define USB_WRAP_DM_PULLDOWN (BIT(16))
#define USB_WRAP_DM_PULLDOWN_S 16
#define USB_WRAP_DM_PULLUP (BIT(15))
#define USB_WRAP_DM_PULLUP_S 15
#define USB_WRAP_DP_PULLDOWN (BIT(14))
#define USB_WRAP_DP_PULLDOWN_S 14
#define USB_WRAP_DP_PULLUP (BIT(13))
#define USB_WRAP_DP_PULLUP_S 13
#define USB_WRAP_PAD_PULL_OVERRIDE (BIT(12))
#define USB_WRAP_PAD_PULL_OVERRIDE_S 12
#define USB_WRAP_VREF_OVERRIDE (BIT(11))
#define USB_WRAP_VREF_OVERRIDE_S 11
#define USB_WRAP_VREFL 0x00000003
#define USB_WRAP_VREFL_S 9
#define USB_WRAP_VREFH 0x00000003
#define USB_WRAP_VREFH_S 7
#define USB_WRAP_EXCHG_PINS (BIT(6))
#define USB_WRAP_EXCHG_PINS_S 6
#define USB_WRAP_EXCHG_PINS_OVERRIDE (BIT(5))
#define USB_WRAP_EXCHG_PINS_OVERRIDE_S 5
#define USB_WRAP_DBNCE_FLTR_BYPASS (BIT(4))
#define USB_WRAP_DBNCE_FLTR_BYPASS_S 4
#define USB_WRAP_DFIFO_PD (BIT(3))
#define USB_WRAP_DFIFO_PD_S 3
#define USB_WRAP_PHY_SEL (BIT(2))
#define USB_WRAP_PHY_SEL_S 2
#define USB_WRAP_SRP_SESSEND_VALUE (BIT(1))
#define USB_WRAP_SRP_SESSEND_VALUE_S 1
#define USB_WRAP_SRP_SESSEND_OVERRIDE (BIT(0))
#define USB_WRAP_SRP_SESSEND_OVERRIDE_S 0

#define USB_WRAP_TEST_CONF_REG (REG_USB_WRAP_BASE + 0x004)
#define USB_WRAP_TEST_RX_DM (BIT(6))
#define USB_WRAP_TEST_RX_DM_S 6
#define USB_WRAP_TEST_RX_DP (BIT(5))
#define USB_WRAP_TEST_RX_DP_S 5
#define USB_WRAP_TEST_RX_RCV (BIT(4))
#define USB_WRAP_TEST_RX_RCV_S 4
#define USB_WRAP_TEST_TX_DM (BIT(3))
#define USB_WRAP_TEST_TX_DM_S 3
#define USB_WRAP_TEST_TX_DP (BIT(2))
#define USB_WRAP_TEST_TX_DP_S 2
#define USB_WRAP_TEST_USB_OE (BIT(1))
#define USB_WRAP_TEST_USB_OE_S 1
#define USB_WRAP_TEST_ENABLE (BIT(0))
#define USB_WRAP_TEST_ENABLE_S 0

#define USB_WRAP_DATE_REG (REG_USB_WRAP_BASE + 0x3FC)
#define USB_WRAP_DATE 0xFFFFFFFF
#define USB_WRAP_DATE_S 0
#define USB_WRAP_DATE_VERSION 0x18092500
